Mo =  SIGMA [ Bi * (R**i)]   ,   Bi is i-th byte
i=0 to N

Ms = K * Mo


f =  16(k-1)/[32(16k-3) + (6/k)]  where k is the message length.

Ms     =  Ms0 + Ms1 + ...             - MoX

Ms  =  K*Mo + C where  C  is some arbitrary, well-known constant.
