filter     =  "(" filtercomp ")" *( ";" parameter )
parameter  =  "q" "=" qvalue
                /  ext-param "=" ext-value
qvalue     =  ( "0" [ "." 0*3DIGIT ] )
                /  ( "1" [ "." 0*3("0") ] )
ext-param  =  ALPHA *( ALPHA / DIGIT / "-" )
ext-value  =  <parameter value, according to the named parameter>
filtercomp =  and / or / not / item
and        =  "&" filterlist
or         =  "|" filterlist
not        =  "!" filter
filterlist =  1*filter
item       =  simple / set / ext-pred
set        =  attr "=" "[" setentry *( "," setentry ) "]"
setentry   =  value "/" range
range      =  value ".." value
simple     =  attr filtertype value
filtertype =  equal / greater / less
equal      =  "="
greater    =  ">="
less       =  "<="
attr       =  ftag
value      =  fvalue
ftag       =  <Feature tag, as defined in [3]>
fvalue     =  Boolean / number / token / string
Boolean    =  "TRUE" / "FALSE"
number     =  integer / rational
integer    =  [ "+" / "-" ] 1*DIGIT
rational   =  [ "+" / "-" ] 1*DIGIT "/" 1*DIGIT
token      =  ALPHA *( ALPHA / DIGIT / "-" )
string     =  DQUOTE *(%x20-21 / %x23-7E) DQUOTE
                   ; quoted string of SP and VCHAR without DQUOTE
ext-pred   =  <Extension constraint predicate, not defined here>

T = [ E1, E2, ... En ]  -->  (| (T=[E1]) (T=[E2]) ... (T=[En]) )
filter     =  orlist
orlist     =  "(" "|" andlist ")" / term
andlist    =  "(" "&" termlist ")" / term
termlist   =  1*term
term       =  "(" "!" simple ")" / simple

T = [ E1, E2, ... En ]  -->  (| (T=[E1]) (T=[E2]) ... (T=[En]) )
named-pred =  "(" fname *pname ")" ":-" filter
fname      =  ftag        ; Feature predicate name
pname      =  token       ; Formal parameter name

ext-pred   =  fname *param
param      =  expr

filter     =/ "(" filtercomp *( ";" parameter ) ")"
                   "where" 1*( named-pred ) "end"

fvalue     =/ number *WSP token

