dkim=  practices (plain-text; REQUIRED).  Possible values are as
      follows:

      OPEN  (Default) The Author Domain practice permits unsigned
         outbound mail.

      CLOSED  The Author Domain practice always initially signs mail
         containing the Author Domain by an Author Key Domain.

      LOCKED  The Author Domain practice always initially signs mail
         containing the Author Domain by an Author Key Domain.
         Furthermore, when a message is received without a Valid Author
         Signature, receiving hosts are requested to dismiss such
         messages.

      ABNF:

adsp-dkim-tag = %x64.6b.69.6d *WSP "="
                         *WSP ("OPEN" / "CLOSED" / "LOCKED")

