VQEvent  =  LocalMetrics CLRF
                     RemoteMetrics

LocalMetrics = ("LocalMetrics") HCOLON VoiceQualityMetrics
RemoteMetrics = ("RemoteMetrics") HCOLON VoiceQualityMetrics


VoiceQualityMetrics = ("VQMetrics") HCOLON CLRF
                               PacketLossMetrics CRLF
                               BurstMetrics CLRF
                               GapMetrics CLRF
                               DelayMetrics CLRF
                               SignalMetrics CLRF
                               QualityScores CLRF
PacketLossMetrics = ("plm") EQUALS loss-rate SPACE discard-rate
loss-rate	        = ("loss") HCOLON HEX (HH)
BurstMetrics	= ("burst") EQUALS density SPACE length
GapMetrics	= ("gap") EQUALS density SPACE length
density	        = ("den") HCOLON HEX (HH)
length	        = ("len") HCOLON HEX (HHHH)

DelayMetrics	= ("delay") EQUALS round-trip SPACE end-system
round-trip	= ("rt") COLON HEX (HHHH)
end-system	= ("es") COLON HEX (HHHH)


SignalMetrics	= ("signal") EQUALS signal SPACE echo-return-loss SPACE
signal		= ("sig") HCOLON HEX (HH)
echo-return-loss	= ("erl") HCOLON HEX (HH)
noise		= ("n") HCOLON HEX (HH)


QualityScores  = ("qs") EQUALS r-factor SPACE ext-r-factor SPACE mos-lq
r-factor	     = ("r") HCOLON HEX (HH)
ext-r-factor   = ("xr") HCOLON HEX (HH)
mos-lq         = ("ml") HCOLON HEX (H"."H)
mos-cq         = ("mc") HCOLON HEX (H"."H)

DialogID       = ("DialogID") HCOLON callid *(SEMI dialogid-param)
dialogid-param  = to-tag / from-tag / generic-param
callid          = token
to-tag          = "to-tag" EQUAL token
from-tag        = "from-tag" EQUAL token

VoiceQualityAlert = ("VQAlert") HCOLON SPACE ViolationMetric CRLF
                             VoiceQualityMetrics


ViolationMetric = ("AlertType") HCOLON ("rf"| "burst" | "erl" | "delay"
                                  token )


plm=loss:05 disc:02
burst=den:0 len:0
gap=den:2 len:0
delay=rt:200 es:140
signal=sig: rerl: n:
qs=r:82 xr:82 ml:3.4 mc:3.3
