rankingScheme = element r:scheme {
       atomCommonAttributes,
       attribute name { IRI }?,
       attribute label { text }?,
       attribute significance { 'ascending' | 'descending' }?,
       attribute precision { nonNegativeInteger }?,
       attribute step { decimal }?,
       attribute minimum { decimal }?,
       attribute maximum { decimal }?
name="tag:example.org,2006:movie_reviews"
label="Five Star Reviews"
precision="0"
step="1"
significance="ascending"
minimum="0"
maximum="5" />
rankingValue = element r:rank {
       atomCommonAttributes,
       attribute domain {IRI}?,
       attribute scheme {IRI}?,
       attribute label { text }?,
       { decimal }
     }

domain="http://example.org/movie_reviews"
scheme="tag:example.com,2006:movie_reviews"
label="Good">3.5</r:rank>
scheme="tag:example.org,2006:movie_reviews"
label="Good" >3.5</r:rank>

domain=""
scheme="tag:example.org,2006:movie_reviews"
label="Good">3.5</r:rank>

domain="http://www.example.org/movie_reviews"
scheme="tag:example.org,2006:movie_reviews"
label="Good">3.5</r:rank>

domain=""
scheme="tag:example.org,2006:movie_reviews"
label="Good">3.5</r:rank>
domain=""
scheme="tag:example.org,2006:movie_reviews"
label="Good">3.5</r:rank>
domain="http://example.org/anotherfeed.xml"
scheme="tag:example.org,2006:movie_reviews"
label="Good">3.5</r:rank>
