NextExp = n + PayloadSize + 1;
PayloadSize=0.

IPDV = Delay(SrcNum)-Delay(SrcNum-1)
s = 1, 2, 3, 5, 6, 7, 8, 4, 9, 10
i = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
                            /\
s = 1, 2, 3, 4, 7, 5, 6, 8, 9, 10
i = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
                      /\ /\

s = 1, 2, 3, 7, 8, 9,10, 4, 5, 6, 11
i = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11


rc = scanf("%d\n", &res);
NextExp = seqnum+1;
iReturn = 1;
r = (r+1) % MAX_N;
           for (j=0; j<min(l, MAX_N) && seqnum<ring[loop(r-j-1)]; j++)
iReturn = 1;
packet = atoi(argv[i]);
