from='xmpp-grid-client@mile-host.example/postures'
to='broker.security-grid.example'
id='disco1'>
from='broker.security-grid.example'
to='xmpp-grid-client@mile-host.example/postures'
id='disco1'>
node='secinfo'>
name='endpoint-posture'
jid='broker.security-grid.example'/>
name='iodef-1.0'
jid='broker.security-grid.example'/>
from='iodefclientabc@company.example'
to='pubsub.company.example'
id='nodes1'>
from='pubsub.company.example'
to='iodefclientabc@company.example'
id='nodes1'>
node='incident'
name='IODEF incident report'/>
