K_d = 1 s is the selection threshold.  The algorithm essentially
e=sum from k=0 to k=n-1 of [e_k/(2^(k+1))].

psi=[ (1 / (m-1) ) * (sum from k = 1 to k = m-1 of [ (theta_k -
T = (a*sum) over all i of [theta_i / Lambda_i] and psi_r = (a * sum)
a=1/[sum over all i of [1 / Lambda_i].

sj=[(psi_r)^2 + (psi_s)^2]^(1/2).

theta_c = integral over t of (omega_c(t) dt)

y_PLL = [ (V_s * mu) / ( (64 * T_c) ^ 2) ].

y_FLL = [ (V_s - x) / (8 * mu) ].

T_c = (2 ^ tau), in seconds.  PLL contributions should dominate at
