SYN=0.
                                        |    SOO   |
     a) SYN=1                           ,--------->|
SYN=1, the receiver processes PrefixOpts before OuterOpts, then
SYN=1 segment, the end of the Prefix TCP Options MUST be similarly
ACK=0) because a SYN is never resegmented.  However, for simplicity,
Q=10% and F=750B, the traffic overhead is 0.04%. It is as
SYN=1:  The structure in Figure 9a) is used on a SYN or SYN/ACK.  The
      sender locates the 4-octet Magic Number A at the end of the
      segment.  The sender right-aligns the 8-octet InSpace Option just
      before Magic Number A.  Then it right-aligns the Inner Options
      against the InSpace Option, all after the end of the TCP Payload.
      The start of the Inner Options is therefore 4 * (InOO +3) octets
      before the end of the segment, where InOO is read from within the
      InSpace Option.

      A receiver implementation will check whether Magic Number A is
      present at the end of the segment if it does not first find it at
      the start of the segment.  Although the InnerOptions are located
      at the end of the TCP Payload, they are considered to be applied
      before the first octet of the TCP Payload.

SYN=0:  The structure of the first non-SYN segment that contains any
      TCP Data is shown in Figure 9b).

      The receiver will find the second InSpace Option (InSpace#2)
      located SPS#1 octets from the start of the segment, where SPS#1 is
      the value of Sent Payload Size that was read from the InSpace
      Option in the previous (SYN=1) segment that started the half-
      connection.  Although the Inner Options are shifted, as for the
      first segment, they are still considered to be applied at the
      start of the TCP Data in this second segment.

