mplsNodeConfigLocalId              = 1,
 




mplsNodeConfigGlobalId             = 1234,
mplsNodeConfigNodeId               = 10,
mplsNodeConfigRowStatus         = createAndGo (4)

mplsNodeConfigLocalId              = 2,
mplsNodeConfigGlobalId             = 1234,
mplsNodeConfigNodeId               = 20,
mplsNodeConfigRowStatus         = createAndGo (4)
mplsNodeIpMapGlobalId             = 1234,
mplsNodeIpMapNodeId               = 10,
mplsNodeIpMapLocalId              = 1

mplsNodeIpMapGlobalId             = 1234,
mplsNodeIpMapNodeId               = 20,
mplsNodeIpMapLocalId              = 2
mplsTunnelIndex              = 1,
mplsTunnelInstance           = 1,
mplsTunnelIngressLSRId       = 1,

mplsTunnelEgressLSRId        = 2,
mplsTunnelName               = "TP co-routed bidirectional LSP",
mplsTunnelDescr              = "East to West",
mplsTunnelIsIf               = true (1),
mplsTunnelXCPointer          =
                                mplsXCLspId.4.0.0.0.1.1.0.4.0.0.0.1,
mplsTunnelSignallingProto    = none (1),
mplsTunnelSetupPrio          = 0,
mplsTunnelHoldingPrio        = 0,
mplsTunnelSessionAttributes  = 0,
mplsTunnelLocalProtectInUse  = false (0),
mplsTunnelResourcePointer    = mplsTunnelResourceMaxRate.5,
mplsTunnelInstancePriority   = 1,
mplsTunnelHopTableIndex      = 1,
mplsTunnelIncludeAnyAffinity = 0,
mplsTunnelIncludeAllAffinity = 0,
mplsTunnelExcludeAnyAffinity = 0,
mplsTunnelRole               = head (1),
mplsTunnelRowStatus          = createAndGo (4)
mplsTunnelOppositeDirTnlPtr       = 0.0
mplsOutSegmentIndex          = 0x0000001,
mplsOutSegmentInterface      = 13, -- outgoing interface
mplsOutSegmentPushTopLabel   = true(1),
mplsOutSegmentTopLabel       = 22, -- outgoing label

mplsOutSegmentTrafficParamPtr   = 0.0,
mplsOutSegmentRowStatus         = createAndGo (4)
mplsInSegmentIndex           = 0x0000001
mplsInSegmentLabel           = 21, -- incoming label
mplsInSegmentNPop            = 1,
mplsInSegmentInterface       = 13, -- incoming interface

mplsInSegmentTrafficParamPtr    = 0.0,
mplsInSegmentRowStatus          = createAndGo (4)
mplsXCIndex                = 0x01,
mplsXCInSegmentIndex       = 0x00000000,
mplsXCOutSegmentIndex      = 0x00000001,
mplsXCLspId                = 0x0102 -- unique ID
mplsXCLabelStackIndex      = 0x00,
mplsXCRowStatus            = createAndGo(4)

mplsXCIndex                = 0x01,
mplsXCInSegmentIndex       = 0x00000001,
mplsXCOutSegmentIndex      = 0x00000000,
mplsXCLspId                = 0x0102 -- unique ID
mplsXCLabelStackIndex      = 0x00,
mplsXCRowStatus            = createAndGo(4)
mplsXCExtTunnelPointer         = mplsTunnelName.1.1.1.2
mplsXCOppositeDirXCPtr         = 
                                 mplsXCLspId.4.0.0.0.1.4.0.0.0.1.1.0
mplsXCExtTunnelPointer         = mplsTunnelName.1.1.1.2
mplsXCOppositeDirXCPtr         = 
                                 mplsXCLspId.4.0.0.0.1.1.0.4.0.0.0.1
mplsTunnelIndex              = 1,
mplsTunnelInstance           = 1,
mplsTunnelIngressLSRId       = 1,

mplsTunnelEgressLSRId        = 2,
mplsTunnelName               = "TP associated bi-directional
                                     forward LSP",
mplsTunnelDescr              = "East to West",
mplsTunnelIsIf               = true (1),
mplsTunnelXCPointer          =
                                mplsXCLspId.4.0.0.0.1.1.0.4.0.0.0.1,
mplsTunnelSignallingProto    = none (1),
mplsTunnelSetupPrio          = 0,
mplsTunnelHoldingPrio        = 0,
mplsTunnelSessionAttributes  = 0,
mplsTunnelLocalProtectInUse  = false (0),
mplsTunnelResourcePointer    = mplsTunnelResourceMaxRate.5,
mplsTunnelInstancePriority   = 1,
mplsTunnelHopTableIndex      = 1,
mplsTunnelIncludeAnyAffinity = 0,
mplsTunnelIncludeAllAffinity = 0,
mplsTunnelExcludeAnyAffinity = 0,
mplsTunnelRole               = head (1),
mplsTunnelRowStatus          = createAndGo (4)
mplsOutSegmentIndex          = 0x0000001,
mplsOutSegmentInterface      = 13, -- outgoing interface
mplsOutSegmentPushTopLabel   = true(1),
mplsOutSegmentTopLabel       = 22, -- outgoing label

mplsOutSegmentTrafficParamPtr   = 0.0,
mplsOutSegmentRowStatus         = createAndGo (4)
mplsXCIndex                = 0x01,
mplsXCInSegmentIndex       = 0x00000000,
mplsXCOutSegmentIndex      = 0x00000001,
mplsXCLspId                = 0x0102 -- unique ID
mplsXCLabelStackIndex      = 0x00,
mplsXCRowStatus            = createAndGo(4)

mplsXCExtTunnelPointer         = mplsTunnelName.1.1.1.2
mplsXCOppositeDirXCPtr         = 
                                mplsXCLspId.4.0.0.0.1.4.0.0.0.1.1.0
mplsTunnelIndex              = 2,
mplsTunnelInstance           = 1,
mplsTunnelIngressLSRId       = 2,
mplsTunnelEgressLSRId        = 1,
mplsTunnelName               = "TP associated bi-directional
                                     reverse LSP",
mplsTunnelDescr              = "West to East",
mplsTunnelIsIf               = true (1),
mplsTunnelXCPointer          =
                                mplsXCLspId.4.0.0.0.1.4.0.0.0.1.1.0,
mplsTunnelSignallingProto    = none (1),
mplsTunnelSetupPrio          = 0,
mplsTunnelHoldingPrio        = 0,
mplsTunnelSessionAttributes  = 0,
mplsTunnelLocalProtectInUse  = false (0),

mplsTunnelResourcePointer    = mplsTunnelResourceMaxRate.5,
mplsTunnelInstancePriority   = 1,
mplsTunnelHopTableIndex      = 1,
mplsTunnelIncludeAnyAffinity = 0,
mplsTunnelIncludeAllAffinity = 0,
mplsTunnelExcludeAnyAffinity = 0,
mplsTunnelRole               = head (1),
mplsTunnelRowStatus          = createAndGo (4)
mplsInSegmentNPop            = 1,   mplsInSegmentInterface       =
mplsInSegmentTrafficParamPtr    = 0.0,   mplsInSegmentRowStatus   
            = createAndGo (4) }

mplsXCIndex                = 0x01,
mplsXCInSegmentIndex       = 0x00000001,
mplsXCOutSegmentIndex      = 0x00000000,
mplsXCLspId                = 0x0102 -- unique ID
mplsXCLabelStackIndex      = 0x00,
mplsXCRowStatus            = createAndGo(4)
mplsXCExtTunnelPointer         = mplsTunnelName.1.1.1.2
mplsXCOppositeDirXCPtr         = 
 




                                 mplsXCLspId.4.0.0.0.1.1.0.4.0.0.0.1
