Yi = g^x mod N,

EkeSharedSecret = prf(0+, g^(x*y) mod N)

Ke2 = prf+(EkeSharedSecret, "HUSH encryption" | IDi | IDr)

Ka2 = prf+(EkeSharedSecret, "HUSH authentication" | IDi | IDr)

AUTH = prf(prf(Shared Secret, Ni2 | Nr2 | IDi | IDr),
AUTH = prf(prf(Shared Secret, Ni2 | Nr2 | IDi | IDr),
