a=record nor a=recordpref.


        UA A                                                   UA B
        (SRC)                                                   |
          |                                                     |
          |                [SRC recording starts]               |
          |(1) INVITE (SDP offer + a=record:on)                 |
          |---------------------------------------------------->|
          |                             (2) 200 OK (SDP answer) |
          |<----------------------------------------------------|
          |(3) ACK                                              |
          |---------------------------------------------------->|
          |(4) RTP                                              |
          |<===================================================>|
          |                                                     |
          |   [UA B wants to set preference to no recording]    |
          |           (5) INVITE (SDP offer + a=recordpref:off) |
          |<----------------------------------------------------|
          |   [SRC honors the preference and stops recording]   |
          |(6) 200 OK (SDP answer + a=record:off)               |
          |---------------------------------------------------->|
          |                                             (7) ACK |
          |<----------------------------------------------------|


          Figure 4: Recording indication and recording preference

v=0
o=SRC 2890844526 2890844526 IN IP4 198.51.100.1
s=-
c=IN IP4 198.51.100.1
t=0 0
m=audio 12240 RTP/AVP 0 4 8
a=sendonly
a=label:1
m=video 22456 RTP/AVP 98
a=rtpmap:98 H264/90000
a=fmtp:98 profile-level-id=42A01E;
sprop-parameter-sets=Z0IACpZTBYmI,aMljiA==
a=sendonly
a=label:2
m=audio 12242 RTP/AVP 0 4 8
a=sendonly
a=label:3
m=video 22458 RTP/AVP 98
a=rtpmap:98 H264/90000
a=fmtp:98 profile-level-id=42A01E;
sprop-parameter-sets=Z0IACpZTBYmI,aMljiA==
a=sendonly
a=label:4



attribute =/ record-attr
record-attr = "record:" indication
indication = "on" / "off" / "paused"

v=0
o=SRS 0 0 IN IP4 198.51.100.20
s=-
c=IN IP4 198.51.100.20
t=0 0
m=audio 10000 RTP/AVP 0
a=recvonly
a=label:1
m=video 10002 RTP/AVP 98
a=rtpmap:98 H264/90000
a=fmtp:98 profile-level-id=42A01E;
sprop-parameter-sets=Z0IACpZTBYmI,aMljiA==
a=recvonly
a=label:2
m=audio 10004 RTP/AVP 0
a=recvonly
a=label:3
m=video 10006 RTP/AVP 98
a=rtpmap:98 H264/90000
a=fmtp:98 profile-level-id=42A01E;
sprop-parameter-sets=Z0IACpZTBYmI,aMljiA==
a=recvonly
a=label:4



attribute =/ recordpref-attr
recordpref-attr = "a=recordpref:" pref
pref = "on" / "off" / "pause" / "nopreference"

v=0
o=SRS 2890844526 2890844526 IN IP4 198.51.100.1
s=-
c=IN IP4 198.51.100.1
t=0 0
m=audio 12240 RTP/AVP 0 4 8
a=sendonly
a=label:1

