dataTypeSemantics="identifier"
fieldId="300" applicability="data" status="current"
group="common">
fieldId="301" applicability="data" status="current"
group="common">
dataTypeSemantics="identifier"
fieldId="302" applicability="option" status="current"
group="common">
fieldId="304" applicability="option" status="current"
group="common">
fieldId="305" applicability="option" status="current"
group="common">
fieldId="306" applicability="option" status="current"
group="common">
fieldId="307" applicability="option" status="current"
group="common">
fieldId="308" applicability="option" status="current"
group="common">
fieldId="309" applicability="option" status="current"
group="common">
fieldId="310" applicability="option" status="current"
group="common">
fieldId="311" applicability="option" status="current"
group="common">
fieldId="313" applicability="data" status="current"
group="common">
fieldId="314" applicability="data" status="current"
group="common">
fieldId="315" applicability="data" status="current"
group="common">
fieldId="316" applicability="data" status="current"
group="common">
fieldId="317" applicability="data" status="current"
group="common">
fieldId="318" applicability="data" status="current"
group="common">
fieldId="319" applicability="data" status="current"
group="common">
fieldId="320" applicability="data" status="current"
group="common">
fieldId="321" applicability="data" status="current"
group="common">
fieldId="323" applicability="data" status="current"
group="common">
fieldId="324" applicability="data" status="current"
group="common">
fieldId="325" applicability="data" status="current"
group="common">
fieldId="326" applicability="data" status="current"
group="common">
