pid = getpid(); 
    
trigger_params = (void *)malloc(sizeof(struct gen_trig_param)); 
  
handle0 = trig_register (xl0,source trigger,pid); 
        
retval = sigemptyset(&look_for_these); 
retval = sigaddset(&look_for_these,SIGUSR1);  
retval = sigprocmask(SIG_BLOCK,&look_for_these,NULL); 
sigval = sigwait(&look_for_these,&sig); 
retval = get_trigger_info(trigger_params, &more_flag, pid); 
