SKEYID = prf(pre-shared key, Nx | Ny)

SKEYID = prf(Nx | Ny, g^xy)

SKEYID = prf(hash(Nx | Ny), M-CKYI | M-CKYR)

M_SKEYID = prf(DEF-KEY,[A2_own][XOR [A2_peer]] | M-CKYI | M-CKYR)

KEYMAT = prf(M_SKEYID, g^xy | protocol | SPI | Nx | Ny)

N = (Number of required SAs to systems -> R)

N =  Number of required SAs to systems -> R
         + messages for trustee & TRD authentication

ends_here = TRUE
N =  Number of required SAs to systems -> R
         + messages for trustee & TRD authentication

N =  Number of required SAs to systems -> R
         + messages for trustee & TRD authentication

