A-------B=======C-------E
             |               |
             +-------D-------+

TTL=n and LSR at TTL=n+1, there is no guarantee that traversal of
R1 ==== S1 ==== R2

R1 ==== S1 ==== R2

R1 ==== S1 ---- R2

