oauth_token=ab3cd9j4ks73hf7g&oauth_token_secret=xyz4992k83j47x0b&
oauth_callback_confirmed=true

oauth_verifier=473829k9302sa

oauth_token=j49ddk933skd9dks&oauth_token_secret=ll399dj47dskfjdk

oauth_consumer_key="dpf43f3p2l4k3l03",
oauth_signature_method="PLAINTEXT",
oauth_signature="kd94hf93k423kf44%26",
oauth_timestamp="1191242090",
oauth_nonce="hsu94j3884jdopsl",
oauth_version="1.0",
oauth_callback="http%3A%2F%2Fprinter.example.com%2Fready"

oauth_token=hh5s93j4hdidpola&oauth_token_secret=hdhd0244k9j7ao03&
oauth_callback_confirmed=true
oauth_token=hh5s93j4hdidpola&oauth_verifier=hfdp7dh39dks9884

oauth_consumer_key="dpf43f3p2l4k3l03",
oauth_token="hh5s93j4hdidpola",
oauth_signature_method="PLAINTEXT",
oauth_signature="kd94hf93k423kf44%26hdhd0244k9j7ao03",
oauth_timestamp="1191242092",
oauth_nonce="dji430splmx33448",
oauth_version="1.0"
oauth_verifier="hfdp7dh39dks9884"

oauth_token=nnch734d00sl2jdk&oauth_token_secret=pfkkdhi9sl3r4s00

auth_token=nnch734d00sl2jdk&oauth_version=1.0&size=original"

oauth_consumer_key="dpf43f3p2l4k3l03",
oauth_token="nnch734d00sl2jdk",
oauth_signature_method="HMAC-SHA1",
oauth_signature="tR3%2BTy81lMeYAr%2FFid0kMTYa%2FWM%3D",
oauth_timestamp="1191242096",
oauth_nonce="kllo9940pd9333jh",
oauth_version="1.0"

