mplsVpnVrfConfIndex          = 1,
mplsVpnVrfName               = "RED",
mplsVpnVrfDescripton         = "Intranet of Company ABC",
mplsVpnVrfRouteDistinguisher = 100:1,
mplsVpnVrfRouteDistinguisher = 100:2,
mplsVpnVrfRouteDistinguisher = 100:1,

mplsVpnVrfBgpAddrFamilyVpnv4Unicast = true (1),
mplsVpnVrfBgpAFNeighborPEAddr       = 10.10.10.1 {the other PE},
mplsVpnVrfBgpAFNeighborPEType       = IpV4
   

mplsVpnVrfName                      = "RED",
mplsVpnVrfBgpAddrFamilyVpnv4Unicast = true (1),
mplsVpnVrfBgpAFNeighborCEAddr       = 192.123.123.1 {adjacent CE},
mplsVpnVrfBgpAFNeighborCEType       = IpV4
   
mplsVpnVrfName                      = "RED",
mplsVpnVrfNetType                   = rip(2),
mplsVpnVrfRipNetPrefix              = 192.123.123.4 {the network
                                         prefix  to the adjacent CE),

mplsVpnVrfName                    = "RED",
mplsVpnVrfIpRouteVrfForwByType    = IpV4 (1)
mplsVpnVrfIpRouteVrfForwByAddr    = 192.123.123.1 {forwarded by},
mplsVpnVrfIpRouteRedistributeConn = true (1)
