a=dcmap:2 label="chat";subprotocol="MSRP"

m=application 54111 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 198.51.100.79
a=max-message-size:100000
a=sctp-port:5000
a=setup:actpass
a=fingerprint:SHA-1 \
          4A:AD:B9:B1:3F:82:18:3B:54:02:12:DF:3E:5D:49:6B:19:E5:7C:AB
a=tls-id:4a756565cddef001be82
a=dcmap:0 label="chat";subprotocol="MSRP"
a=dcsa:0 setup:active
a=dcsa:0 accept-types:message/cpim text/plain
a=dcsa:0 path:msrps://bob.example.com:54111/si438dsaodes;dc
a=dcmap:2 label="file transfer";subprotocol="MSRP"
a=dcsa:2 sendonly
a=dcsa:2 setup:active
a=dcsa:2 accept-types:message/cpim
a=dcsa:2 accept-wrapped-types:*
a=dcsa:2 path:msrps://bob.example.com:54111/jshA7we;dc
a=dcsa:2 file-selector:name:"picture1.jpg" \
           type:image/jpeg size:1463440 hash:sha-1:\
           FF:27:0D:81:14:F1:8A:C3:35:3B:36:64:2A:62:C9:3E:D3:6B:51:B4
a=dcsa:2 file-transfer-id:rjEtHAcYVZ7xKwGYpGGwyn5gqsSaU7Ep
a=dcsa:2 file-disposition:attachment
a=dcsa:2 file-date:creation:"Mon, 12 Jan 2018 15:01:31 +0800"
a=dcsa:2 file-icon:cid:id2@bob.example.com
a=dcsa:2 file-range:1-1463440

