paraname=value,...

property = value1 OR property = value2 .OR property = valueN
        
required="yes">language</propertyReference>
type="uri">http://adserver.acmecorp.com/</property>
          <propertySchema>
               <propertyDefinition id="1">
                    <propertyName>workgroupID</propertyName>
                    <propertyType default="yes">freeform</propertyType>
                    <propertyType
default="no">domainname</propertyType>
                    </propertyDefinition>
                    <propertyDefinition id="2">
                    <propertyName>BannerAdServer</propertyName>
                    <propertyType default="yes">URI</propertyType>
source="explicit">CA</property>
    <property name="language" type="rfc1766">fr-CA</property>
 </query>
