resume-command = "RESUME" SP transid-value CRLF

resume-reply = "355" SP octet-offset SP text CRLF

esmtp-param     =/  transid-param
transid-param   =   "TRANSID=" transid-value
transid-value   =   "<" transid-spec ">"
transid-spec    =   dot-string "@" domain

esmtp-param     =/  transoff-param
transoff-param  =   "TRANSOFF=" octet-offset
octet-offset    =   1*20DIGIT

