contents = *chunk finalChunk
chunk      = header payload CR LF
header     = "CHK" SP messageNumber SP length SP isMore CR LF
messageNumber   = 1..2147483647
length   = 0..2147483647
isMore       = "MORE" / "LAST"
payload    = *OCTET
finalChunk = finalHeader CR LF
finalHeader  = "CHK" SP "0" SP "0" SP "LAST" CR LF

type="text/xhtml+xml"

type="text/xhtml+xml"

type="text/xhtml+xml"

type="text/xhtml+xml"

type="text/xhtml+xml"

