prodid-value =  ownerid ownerprefix textid

ownerd =        "-//"
ownerprefix =   compname "/" prodname

textid =        "//NONSGML" space version "//EN"
compname =      1*WORD
prodname =      1*WORD
version =               <product version identifier>
rstatus =       "REQUEST-STATUS" ":" statcode ";"
                        statdesc [";" extdata]

statcode =      3*DIGIT
statdesc =      *WORD
extdata =       *WORD
TYPE=ROOM parameter value pair
charset=UTF-8

