type=value

attribute          = (att-field ":" att-value) / att-field
att-field          = token
att-value          = byte-string

extension-config-list = ["+"] ext-cap-name "=" ext-cap-list
ext-cap-name          = 1*(ALPHA / DIGIT)
                          ; ALPHA and DIGIT defined in RFC5234
ext-cap-list          = 1*VCHAR  ; VCHAR defined in RFC5234

sel-extension-config = ext-cap-name "=" 1*VCHAR

v=0
a=bcap:1 CT:200
a=icap:1 Video conference
m=audio 54320 RTP/AVP 0
a=mcap:1 L16/8000/1
a=mcap:2 L16/16000/2
a=pcfg:1 m=1|2, pt=1:99,2:98
m=video 66544 RTP/AVP 100
a=mcap:3,4 H263-1998/90000
a=rtpmap:100 H264/90000
a=pcfg:10 m=3 pt=3:101 b=1 i=1

     Example SDP offer with bcap and icap defined at
b=<bwtype>:<bandwidth>

att-field       = "bcap"
att-value       = bw-cap-num 1*WSP bwtype ":" bandwidth
bw-cap-num      = 1*10(DIGIT)   ; DIGIT defined in RFC5234

extension-config-list  = bandwidth-config-list
bandwidth-config-list  = ["+"] "b=" bw-cap-list *(BAR bw-cap-list)
                            ; BAR defined in RFC5939
bw-cap-list            = bw-cap-num *("," bw-cap-num)
bw-cap-num             = 1*10(DIGIT)   ; DIGIT defined in RFC5234

       Figure 1: Syntax of the bandwidth parameter in lcfg and pcfg
                                attributes
ext-cap-name = "b"

sel-extension-config = sel-bandwidth-config
sel-bandwidth-config = "b=" bw-cap-list  ; bw-cap-list as above.

      Figure 2: Syntax of the bandwidth parameter in acfg attributes

a=icap:1 Document Camera

att-field       = "icap"
att-value       = title-cap-num 1*WSP text
                                    ; text defined in RFC4566
title-cap-num    = 1*10(DIGIT)   ; DIGIT defined in RFC5234

ext-cap-name = "i"

ext-cap-list = title-cap-list

extension-config-list = title-config-list
title-config-list    = ["+"] "i=" title-cap-list
title-cap-list       = title-cap-num *(BAR title-cap-num)
                                      ; BAR defined in RFC5939
title-cap-num        = 1*10(DIGIT) ; DIGIT defined in RFC5234

    Figure 3: Syntax of the title capability parameter in lcfg and pcfg
                                attributes

