DA=132.146.243.30.  The  returning  traffic  will be recognised as
DA=FEDC:BA98::7654:3210.   Note that this packet can now be routed
DA=120.130.26.10. On receiving the packet, the NAT-PT,  recognises
