suit-manifest = {
  suit.manifest-version,
  suit.digest-info,
  suit.text-reference,
  suit.nonce,
  suit.sequence-number,
  ? suit.pre-condition,
  ? suit.post-condition,
  ? suit.directives,
  ? suit.resources,
  ? suit.processors,
  ? suit.targets,
  ? suit.extensions,
