FRVCA = ---------------------------------------------- * 100,
                  IntervalTime  ExcludedOutageTime

FRMTTR = -----------,
               OutageCount

FRMTBSO = ----------------------------------------------
                             OutageCount

FDR = ----------------------------------- = ------------------
           (FramesOfferedc + FramesOfferede)          FramesOfferedc+e

FDRc = ----------------
          FramesOfferedc

FDRe = ----------------
          FramesOfferede

DDR = ------------------------------- = ---------------
           (DataOfferedc + DataOfferede)         DataOfferedc+e

DDRc = -------------
          DataOfferedc

DDRe = -------------
          DataOfferede

