maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
processContents="lax" minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
processContents="lax" minOccurs="0"/>
elementFormDefault="qualified"

attributeFormDefault="unqualified"

version="0.02"
targetNamespace="urn:ietf:params:xml:ns:clue-message"
xmlns="urn:ietf:params:xml:ns:clue-message"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

schemaLocation="data-model-schema-05.xsd"/>

maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
processContents="lax" minOccurs="0"/>
minOccurs="0"/>
processContents="lax" minOccurs="0"/>
maxOccurs="1"/>
processContents="lax" minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
processContents="lax" minOccurs="0"/>
