version="1" state="full"> 
        <conferences resource="sip:A@example.com"> 
         <conference id="sip:conference_111@example.com" display-
name="sip:conference_111@example.com" status="active"/> 
        </conferences> 
      </conference-list> 
    
    

version="1" state="full"> 
       <conferences resource="sip:A@example.com"> 
        <conference id="sip:conference_111@example.com" display-
name="sip:conference_111@example.com" status="active"/> 
       </conferences> 
      </conference-list> 
    
xmlns="urn:ietf:params:xml:ns:conference_list" 
targetNamespace="urn:ietf:params:xml:ns:conference_list" 
elementFormDefault="qualified"> 
     <xs:element name="conference-list"> 
       <xs:complexType> 
         <xs:sequence> 
           <xs:element name="conferences"> 
             <xs:complexType> 
               <xs:sequence> 
                 <xs:element name="conference" 
maxOccurs="unbounded"> 
                   <xs:complexType> 
                     <xs:attribute name="id" use="required"> 
                       <xs:simpleType> 
                         <xs:restriction base="xs:string"/> 
                       </xs:simpleType> 
                     </xs:attribute> 
                     <xs:attribute name="display-name" 
use="required"> 
                       <xs:simpleType> 
                         <xs:restriction base="xs:string"/> 
                       </xs:simpleType> 
                     </xs:attribute> 
 
 
    

                     <xs:attribute name="status" 
use="required"> 
                       <xs:simpleType> 
                         <xs:restriction base="xs:string"> 
                           <xs:enumeration value="active"/> 
                           <xs:enumeration value="closed"/> 
                         </xs:restriction> 
                       </xs:simpleType> 
                     </xs:attribute> 
                   </xs:complexType> 
                 </xs:element> 
               </xs:sequence> 
               <xs:attribute name="resource" use="required"> 
                 <xs:simpleType> 
                   <xs:restriction base="xs:string"/> 
                 </xs:simpleType> 
               </xs:attribute> 
             </xs:complexType> 
           </xs:element> 
         </xs:sequence> 
         <xs:attribute name="version" use="required"> 
           <xs:simpleType> 
             <xs:restriction base="xs:integer"/> 
           </xs:simpleType> 
         </xs:attribute> 
         <xs:attribute name="state" use="required"> 
           <xs:simpleType> 
             <xs:restriction base="xs:string"> 
               <xs:enumeration value="partial"/> 
               <xs:enumeration value="full"/> 
             </xs:restriction> 
           </xs:simpleType> 
 
 
    

         </xs:attribute> 
       </xs:complexType> 
     </xs:element> 
version="1" state="full"> 
name="sip:conference_111@example.com" status="active"/> 
        <conference id="sip:conference_112@example.com" display-
name="sip:conference_112@example.com" status="active"/> 
        <conference id="sip:conference_113@example.com" display-
name="sip:conference_113@example.com" status="active"/> 
        <conference id="sip:conference_114@example.com" display-
name="sip:conference_114@example.com" status="active"/> 
       </conferences> 
      </conference-list> 

 
 
    

    
version="2" state="partial"> 
       <conferences resource="sip:Bob@example.com"> 
        <conference id="sip:conference_111@example.com" display-
name="sip:conference_111@example.com" status="closed"/> 
 
 
    

        <conference id="sip:conference_114@example.com" display-
name="sip:conference_114@example.com" status="closed"/> 
        <conference id="sip:conference_115@example.com" display-
name="sip:conference_115@example.com" status="active"/> 
       </conferences> 
      </conference-list> 
    
version="1" state="full"> 
       <conferences resource="sip:Bob@example.com"> 
        <conference id="sip:conference_112@example.com" display-
name="sip:conference_112@example.com" status="active"/> 
        <conference id="sip:conference_113@example.com" display-
name="sip:conference_113@example.com" status="active"/> 
        <conference id="sip:conference_115@example.com" display-
name="sip:conference_115@example.com" status="active"/> 
       </conferences> 
      </conference-list> 
    
