from='romeo@example.net/orchard'
to='juliet@example.com'
type='probe'/>

from='juliet@example.com/balcony'
to='romeo@example.net/orchard'
from='juliet@example.com/balcony'
to='romeo@example.net/orchard'
from='juliet@example.com/balcony'
to='romeo@example.net/orchard'
type='unavailable'
