CHALLENGE="123456" NAME="" PASSWORD="")
NAME="" PASSWORD="")
XAUTH_MESSAGE = 'The system has assigned you a
XAUTH_MESSAGE = 'Enter your new PIN containing
XAUTH_MESSAGE = 'You must start using a new
MESSAGE = 'Enter your new PIN containing 4-6
XAUTH_MESSAGE = 'The system has assigned you a

XAUTH_MESSAGE = 'Your token is out of sync with
Challenge = 0x01020304050607080910111213141516)
