SRVNAME = (ALPHA / *([HYPHEN] ALNUM)) /
                (1*DIGIT ((HYPHEN ALNUM) / ALPHA) *([HYPHEN] ALNUM))
ALNUM   = ALPHA / DIGIT   ; A-Z, a-z, 0-9
HYPHEN  = %x2d            ; "-"
ALPHA   = <See [RFC5234]>
DIGIT   = <See [RFC5234]>


