Cache-Status   = sh-list

hit          = sh-boolean
fwd          = sh-token
fwd-status   = sh-integer
ttl          = sh-integer
stored       = sh-boolean
collapsed    = sh-boolean
key          = sh-string

