identity-request-data = displayable-string [ %d0 network-info ]
displayable-string = *CHAR

network-info = attribute "=" value

attribute =  1*( ALPHA / "-" / "_" / DIGIT)

value = 1*( %x01-2B / %x2D-FF ) ; any non-null UTF-8 char except ","

value = Realm [ ";" Realm ]


NAIRealms=anyisp.com;mnc123.mcc334.3gppnetwork.org


