MAC = DSKPP-PRF(K_AC, AC->ClientID||URL_S||R_C||[R_S], 16)

K_AC = PBKDF2(AC->password, R_C || K, iter_count, 16)

K_PROV = DSKPP-PRF(k,s,dsLen), where

k = R_C (i.e., the secret random value chosen by the DSKPP
s = "Key generation" || K || R_S (where K is the key used to
dsLen = (desired length of K_PROV whose first half constitutes
K_PROV = K_MAC || K_TOKEN

dsLen = len(R_C), where "len" is the length of R_C
DS = DSKPP-PRF(K_SHARED, "Encryption" || R_S, dsLen)

msg_hash = SHA-256(msg_1, ..., msg_n)

dsLen = len(msg_hash)

MAC = DSKPP-PRF (K_MAC, "MAC 1 computation" || msg_hash, dsLen)

K_PROV = K_MAC || K_TOKEN

msg_hash = SHA-256(msg_1, ..., msg_n)

dsLen = len(msg_hash)

MAC = DSKPP-PRF (K_MAC, "MAC 1 computation" || msg_hash ||
MAC = DSKPP-PRF (K_MAC', "MAC 2 computation" || ServerID || R,
targetNamespace="urn:ietf:params:xml:ns:keyprov:dskpp"
elementFormDefault="qualified" attributeFormDefault="unqualified"
version="1.0">
schemaLocation=
schemaLocation="keyprov-pskc-1.0.xsd"/>
use="required"/>
use="required"/>
use="required"/>
type="dskpp:PlatformType"/>
type="dskpp:PlatformType"/>
type="dskpp:KeyProtectionDataType" minOccurs="0"/>
type="xs:anyURI"/>
type="dskpp:PayloadType" minOccurs="0"/>
type="dskpp:KeyPackageFormatType"/>
type="dskpp:IdentifierType" minOccurs="0"/>
type="dskpp:AuthenticationMacType"/>
type="dskpp:NonceType"/>
type="xs:int"/>
type="xs:anyURI"/>
type="xs:anyURI" />
type="pskc:KeyContainerType"/>
type="dskpp:DeviceIdentifierDataType" />
type="xs:base64Binary"/>
type="dskpp:TokenPlatformInfoType" />
type="dskpp:AuthenticationDataType" />
type="xs:anyURI"/>
processContents="strict" />
type="dskpp:AbstractExtensionType"/>
type="dskpp:KeyProvTriggerType">
type="dskpp:InitializationTriggerType" />
type="dskpp:KeyProvClientHelloPDU">
type="dskpp:DeviceIdentifierDataType" />
type="xs:base64Binary" />
type="dskpp:NonceType" />
type="dskpp:AlgorithmsType" />
type="dskpp:AlgorithmsType" />
type="dskpp:AlgorithmsType" />
name="SupportedProtocolVariants"
type="dskpp:ProtocolVariantsType" />
type="dskpp:KeyPackagesFormatType" />
type="dskpp:AuthenticationDataType" />
type="dskpp:ExtensionsType" />
type="dskpp:KeyProvServerHelloPDU">
type="dskpp:AlgorithmType"/>
type="dskpp:AlgorithmType" />
type="dskpp:AlgorithmType"/>
type="ds:KeyInfoType"/>
type="dskpp:KeyPackageFormatType" />
type="dskpp:ExtensionsType" />
type="dskpp:MacType"/>
type="dskpp:KeyProvClientNoncePDU">
type="xs:base64Binary"/>
type="dskpp:AuthenticationDataType" />
type="dskpp:ExtensionsType" />
type="dskpp:IdentifierType" use="required"/>
type="dskpp:KeyProvServerFinishedPDU">
type="dskpp:KeyPackageType" />
type="dskpp:ExtensionsType" />
type="dskpp:AuthenticationMacType" />
AlgorithmLocation="Software"/>
Version="1.0">
Version="1.0">
Version="1.0"
Status="Continue"
SessionID="4114">
Version="1.0"
SessionID="4114"
Status="Continue">
MacAlgorithm="urn:ietf:params:xml:ns:keyprov:dskpp:prf-aes-128">
cXcycmFuZG9tMzEyYXNkZXIzOTRqdw==
SessionID="4114"
Version="1.0">
Version="1.0"
Status="Success"
SessionID="4114">
Id="MBK000000001"
Algorithm=







                            "urn:ietf:params:xml:ns:keyprov:pskc:hotp">
Encoding="DECIMAL"/>
MacAlgorithm=
                 "urn:ietf:params:xml:ns:keyprov:dskpp:prf-sha256">
Version="1.0">
c2pBsXWhL4O7nk0S2ZrLMsQZ6HcsXgdmHo=
                           </ds:X509Certificate>
                       </ds:X509Data>
                   </ds:KeyInfo>
               </dskpp:Payload>
           </dskpp:TwoPass>
       </dskpp:SupportedProtocolVariants>
       <dskpp:SupportedKeyPackages>
           <dskpp:KeyPackageFormat>
               urn:ietf:params:xml:ns:keyprov:dskpp:pskc-key-container
           </dskpp:KeyPackageFormat>
       </dskpp:SupportedKeyPackages>
       <dskpp:AuthenticationData>







           <dskpp:ClientID>AC00000A</dskpp:ClientID>
           <dskpp:AuthenticationCodeMac>
               <dskpp:Nonce>
                   ESIzRFVmd4iZqrvM3e7/ESIzRFVmd4iZqrvM3e7/ESI=
               </dskpp:Nonce>
               <dskpp:IterationCount>100000</dskpp:IterationCount>
               <dskpp:Mac
MacAlgorithm=
Version="1.0"
Status="Success"
SessionID="4114">
c2pBsXWhL4O7nk0S2ZrLMsQZ6HcsXgdmHo=
                       </ds:X509Certificate>
                   </ds:X509Data>







               </pskc:EncryptionKey>
               <pskc:KeyPackage>
                   <pskc:DeviceInfo>
                       <pskc:Manufacturer>
                          TokenVendorAcme
                       </pskc:Manufacturer>
                       <pskc:SerialNo>
                          987654321
                       </pskc:SerialNo>
                       <pskc:StartDate>
                          2009-09-01T00:00:00Z
                       </pskc:StartDate>
                       <pskc:ExpiryDate>
                          2014-09-01T00:00:00Z
                       </pskc:ExpiryDate>
                   </pskc:DeviceInfo>
                   <pskc:Key
Id="MBK000000001"
Algorithm=
                          "urn:ietf:params:xml:ns:keyprov:pskc:hotp">
Encoding="DECIMAL"/>
Algorithm=
eylG5vK8NTo47vZTatL5UxmbmOX2HvaVQ=
                                       </xenc:CipherValue>
                                   </xenc:CipherData>
                               </pskc:EncryptedValue>
                           </pskc:Secret>
                           <pskc:Counter>
                               <pskc:PlainValue>0</pskc:PlainValue>
                           </pskc:Counter>
                       </pskc:Data>
                       <pskc:Policy>
                           <pskc:KeyUsage>OTP</pskc:KeyUsage>
                       </pskc:Policy>
                   </pskc:Key>







               </pskc:KeyPackage>
           </dskpp:KeyContainer>
       </dskpp:KeyPackage>
       <dskpp:Mac
MacAlgorithm=
              "urn:ietf:params:xml:ns:keyprov:dskpp:prf-sha256">
Version="1.0">
MacAlgorithm=
Version="1.0"
Status="Success"
SessionID="4114">
Algorithm=
                       "http://www.w3.org/2000/09/xmldsig#hmac-sha1">
Algorithm=
Id="MBK000000001"
Algorithm=
                           "urn:ietf:params:xml:ns:keyprov:pskc:hotp">
Encoding="DECIMAL"/>







Algorithm=
Tg==
MacAlgorithm=
              "urn:ietf:params:xml:ns:keyprov:dskpp:prf-sha256">
Version="1.0">
MacAlgorithm=
K4YvLMN6Q1DZvtShoCxQag==
Version="1.0"
Status="Success"
SessionID="4114">
Algorithm=
Algorithm=
                      "http://www.w3.org/2000/09/xmldsig#hmac-sha1">
Algorithm=
Id="MBK000000001"
Algorithm=
                          "urn:ietf:params:xml:ns:keyprov:pskc:hotp">
Encoding="DECIMAL"/>
Algorithm=
cOrF8VoK254tZKnrAjiD5cdw==
pbgEbVYxoYs0x41wdeC7eDRbUEk=
bLen = (AES output block length in octets)
n = CEILING( dsLen / bLen)
j = dsLen - (n - 1) * bLen

B1 = F (k, s, 1) ,
B2 = F (k, s, 2) ,
Bn = F (k, s, n)

DS = B1 || B2 || ... || Bn<0..j-1>

n = 16 / 16 = 1

j = 16 - (1 - 1) * 16 = 16

DS = B1 = F (k, s, 1) = CMAC-AES (k, INT (1) || s)

bLen = 32
n = CEILING( dsLen / bLen)
j = dsLen - (n - 1) * bLen

B1 = F (k, s, 1),
B2 = F (k, s, 2),
Bn = F (k, s, n)

DS = B1 || B2 || ... || Bn<0..j-1>

n = CEILING( 16 / 32 ) = 1

j = 16 - (1 - 1) * 32 = 16







B1 = F (k, s, 1) = HMAC-SHA256 (k, INT (1) || s)

DS = B1<0 ... 15>

