account-uri=https://example.net/registration/1234"
account-uri=https://example.net/registration/2345"

acme-methods=dns-01,xyz-01"

account-uri=https://example.net/registration/1234; \
acme-methods=dns-01"
account-uri=https://example.net/registration/2345; \
acme-methods=http-01"

acme-methods=dns-01,non-acme"

