Ver = 0001, for this format of VRTE

Reserved = all bits 0, till more extensions are added

VPN_ID = the 7 octet VPN ID, corresponding to the VPN traffic
             being tunneled. Refer [RFC 2685].

PayloadProtocol = protocol corresponding to the payload. Mostly
                      it is expected to be IP.

TunnelTag = a 4 octet value for additional tagging.


Ver = 0001, for this format of VTE

Reserved = all bits 0, till more extensions are added

VPN_ID = the 7 octet VPN ID, corresponding to the VPN traffic
             being tunneled. Refer [RFC 2685].

PDU_Len = Two octet integer specifying the total length of this PDU
              in octets starting from version field.

MessageCode = This identifies what message is carried in this PDU.



Reserved = all bits 0, till more extensions are added

Length = number of octets in this AVP, starting from 'reserved'.

VendorID = IANA assigned enterprise code.

AttributeID = Identifier for the Attribute

AttributeValue = Value for the Attribute


