resp-text-code =/ "UNAVAILABLE" / "AUTHENTICATIONFAILED" /
                         "AUTHORIZATIONFAILED" / "EXPIRED" /
                         "CONTACTADMIN" / "ACL" / "INUSE" / "EXPUNGED" /
                         "CORRUPTION" / "SERVERBUG" / "CLIENTBUG" /
                         "NOBODYPART" / "CANNOT" / "LIMIT" / "OVERQUOTA"
                         / "ALREADYEXISTS" / "NONEXISTENT"


