RC=1 . . . . . . . . . . . . . . . . . . . . . . . . . . . 15
RC=1, it MUST treat the packet as if the Recycled flag were cleared
RC=0:  If an implementation of a new protocol uses RC=0, its packets
      will traverse middleboxes, but it will suffer a small fraction of
      false positives when recognising which packets using the new
      protocol -- occasionally it will mistakenly assume a packet is
      using the new protocol when it is actually just random noise in
      the IP ID field from a pre-existing implementation.








RC=1:  If an implementation of a new protocol uses RC=1, its packets
      may be black-holed by some middleboxes, but it will be certain
      which packets use the new protocol and which don't.

RC=0 (i.e., RC=X, where 'X' means don't care).  Figure 7 shows the
RC=0 or RC=1.  All zeros was deliberately chosen as the common
