PME=<packet matching expression>
PME='if in and udp src port 55 and src host 10.1.1.1 and udp dst
action=pass

PME='dst host 10.1.1.1 and udp dst port 55'

PME='dst host 10.1.2.42 and udp dst port 66 if out and src host
action=PASS
modifier='dst host = 10.1.1.1, udp dst port = 55'
PME='if in and udp src port 55 and src host 10.1.1.1 and udp dst
modifier='tos0x10'

PME='if in and udp src port 55 and src host 10.1.1.1 and udp dst
PME='if in and udp src port 55 and src host 10.1.1.1 and udp dst
PME='if in and not src net 10.1.2'
action=drop(no_ICMP)

PME='if in and tcp dst port 80'
REFLEXIVE='permit=yes, timer=180s, apply_to=out'

PME='if=out and tcp src port 80 and src host 10.1.3.1 and tcp dst
PME='if in and tcp dst port 80'
modifier='ip dst host = 10.1.4.4'
reflexive_rules='permit=yes, inactivity_timer=240s, if=dmz'

PME='if=dmz and tcp src port 80 and src host 10.1.4.4 and tcp dst
modifier='ip src host=10.1.3.1'

