Msg-type = 1   Indicates address-mapping cache request
                    message.

Msg-type = 2      Indicates a message reply type.

Msg-type = 3      Indicates a message reply type.

Msg-type = 4    Indicates acknowledgement type.

Msg-type = 5       Indicates a keepalive message type.

