type="application/atom+xml"
href="NotificationURI Goes Here"
title="The Title of the Site" />

xmlns="http://purl.org/atom/ns#draft-ietf-atompub-format-03">
       <head>
         <title>Example Feed</title>
         <link href="http://example.org/"/>
         <updated>2003-12-13T18:30:02Z</updated>
         <author>
           <name>John Doe</name>
         </author>
       </head>
xmlns="http://purl.org/atom/ns#draft-ietf-atompub-format-03">
       <head>
         <title>Example Feed</title>
         <link href="http://example.org/"/>
         <updated>2003-12-13T18:30:02Z</updated>
         <author>
           <name>John Doe</name>
         </author>
         <notification href="http://example.org/notificationURI" />
      </head>
      <entry>
        <title>Atom-Powered Robots Run Amok</title>
        <link href="http://example.org/2003/12/13/atom03"/>
        <id>vemmi://example.org/2003/32397</id>
        <updated>2003-12-13T18:30:02Z</updated>
        <notification href="http://example.org/2003/32397/notificationURI" />
      </entry>
