DIALOG-URL        = sip-ind dialog-ind "@" hostport
                        dialog-parameters

sip-ind           = "sip:" / "sips:"
dialog-ind        = "dialog"

dialog-parameters = [ init-parameters ]
                        [ vxml-parameters ]
                        [ uri-parameters ]

init-parameters   = init-param [ init-parameters ]

init-param        = ";" (dialog-param /
                             maxage-param /
                             maxstale-param /
                             method-param /
                             postbody-param)

dialog-param      = "voicexml=" vxml-url ; vxml-url follows the URI
                                             ; syntax defined in RFC3986
maxage-param      = "maxage=" 1*DIGIT

maxstale-param    = "maxstale=" 1*DIGIT

method-param      = "method=" ("get" / "post")

postbody-param    = "postbody=" token

vxml-parameters   = vxml-param [ vxml-parameters ]

vxml-param        = ";" vxml-keyword "=" vxml-value

vxml-keyword      = token

vxml-value        = token


voicexml=http://appserver.example.com/promptcollect.vxml; \
maxage=3600;maxstale=0

voicexml=http://as1.example.com/da.vxml

userAuthorized = true
pin = 1234
nomatches = 0

id=1234&pin=0000
