mplsXCIndex = 2,
mplsInSegmentIfIndex = 0,
mplsInSegmentLabel = 0,
mplsOutSegmentIndex = 3,
mplsXCLabelStackIndex = 0
mplsOutSegmentIndex = 3,
mplsOutSegmentIfIndex = 50,
mplsOutSegmentPushTopLabel = true,
mplsOutSegmentTopLabel = 150
mplsTunnelIndex = 4,
mplsTunnelInstance = 0, -- primary tunnel
mplsTunnelIngressLSRID = 1.1.1.1,
mplsTunnelEgressLSRID = 2.2.2.2
mplsFTNIndex = 1,
mplsFTNDescr = "Rule #1 for destination address 1.4.0.1",
mplsFTNMask = 0x80, -- source address only
mplsFTNAddrType = ipv4,
mplsFTNDestAddrMin = 1.4.0.1,
mplsFTNDestAddrMax = 1.4.0.1,
mplsFTNActionType = redirectLsp(1),
mplsFTNActionPointer = mplsXCLspId.2.0.0.3
mplsFTNMapIndex = 1,
mplsFTNPrevIndex = 0, -- first FTN entry on this interface
mplsFTNMapCurrIndex = 1,
mplsFTNIndex = 2,
mplsFTNDescr = "Rule #2 for net 1.2.0.0",
mplsFTNMask = 0x40, -- destination address only
mplsFTNAddrType = ipv4,
mplsFTNDestAddrMin = 1.3.0.0,
mplsFTNDestAddrMax = 1.5.0.0,
mplsFTNActionType = redirectTunnel(2),
mplsFTNActionPointer = mplsTunnelName.4.0.4.1.1.1.1.4.2.2.2.2
mplsFTNMapIndex = 1,
mplsFTNPrevIndex = 1,
mplsFTNMapCurrIndex = 2
mplsTunnelIndex = 3,
mplsTunnelInstance = 0, -- primary tunnel
mplsTunnelIngressLSRID = 3.3.3.3,
mplsTunnelEgressLSRID = 4.4.4.4
mplsFTNIndex = 3,
mplsFTNDescr = "Rule #3 for destination prefix 1.4.0.0/16",
mplsFTNMask = 0x40, -- destination address only
mplsFTNAddrType = ipv4,
mplsFTNDestAddrMin = 1.4.0.0,
mplsFTNDestAddrMax = 1.4.255.255,
mplsFTNActionType = redirectTunnel,
mplsFTNActionPointer = mplsTunnelName.3.0.4.3.3.3.3.4.4.4.4.4
mplsFTNMapIndex = 1,
mplsFTNPrevIndex = 1,
mplsFTNMapCurrIndex = 3
mplsFTNMapPrevIndex = 3, -------->+  |  | | |
mplsFTNMapCurrIndex = 2) ----+    |  |  | | |
                                                |    |  |  | | |
mplsFTNPerfCurrIndex = 2) --------------+ | |
                                                             | |
mplsFTNPerfCurrIndex = 3) ---------------+ |
                                                               |
mplsFTNPerfCurrIndex = 1) ------------------+


