sec-gp="feedca570000";app-gp="group1";
cs_alg="-8";cs_alg_crv="6";
cs_key_kty="1";cs_key_crv=6";
cs_kenc="1",
rel="authorization-server";
anchor="coap://[2001:db8::ab]/group-oscore/feedca570000"

sec-gp="feedca570000";app-gp="group1";
cs_alg="-8";cs_alg_crv="6";
cs_key_kty="1";cs_key_crv=6";
cs_kenc="1",
sec-gp="ech0ech00000";app-gp="group2";
cs_alg="-8";cs_alg_crv="6";
cs_key_kty="1";cs_key_crv=6";
cs_kenc="1",
sec-gp="abcdef120000";app-gp="group3";
app-gp="group4";cs_alg="-8";
cs_alg_crv="6";cs_key_kty="1";
cs_key_crv=6";cs_kenc="1",
rel="authorization-server";
anchor="coap://[2001:db8::ab]/group-oscore/feedca570000",
rel="authorization-server";
anchor="coap://[2001:db8::ab]/group-oscore/ech0ech00000",
rel="authorization-server";
anchor="coap://[2001:db8::ab]/group-oscore/abcdef120000"

sec-gp="feedca570000";app-gp="group1";
cs_alg="-8";cs_alg_crv="6";cs_key_kty="1";
cs_key_crv=6";cs_kenc="1";anchor="coap://[2001:db8::ab]"

base="coap://[ff35:30:2001:db8::23]"

sec-gp="feedca570000";app-gp="group1";
cs_alg="-8";cs_alg_crv="6";cs_key_kty="1";
cs_key_crv=6";cs_kenc="1";anchor="coap://[2001:db8::ab]"
sec-gp="feedca570000";app-gp="group1";
cs_alg="-8";cs_alg_crv="6";cs_key_kty="1";
cs_key_crv=6";cs_kenc="1";anchor="coap://[2001:db8::ab]",
sec-gp="ech0ech00000";app-gp="group2";
cs_alg="-8";cs_alg_crv="6";cs_key_kty="1";
cs_key_crv=6";cs_kenc="1";anchor="coap://[2001:db8::ab]",
sec-gp="abcdef120000";app-gp="group3";
app-gp="group4";cs_alg="-8";cs_alg_crv="6";
cs_key_kty="1";cs_key_crv=6";cs_kenc="1";
anchor="coap://[2001:db8::ab]"

sec-gp="feedca570000";
app-gp="grp_R2-4-015",
sec-gp="feedsc590000";
app-gp="grp_schedule"

base="coap://[ff05::5:1]"

base="coap://[ff05::5:2]"

rt="core.osc.mbr";sec-gp="feedca570000";
app-gp="grp_R2-4-015";anchor="coap://[2001:db8::ab]"
rt="core.osc.mbr";sec-gp="feedsc590000";
app-gp="grp_schedule";anchor="coap://[2001:db8::ab]"

