SubstreamCtrl = "SubstreamCtrl:"
                   substream-id * (";" sustream-id)
substream-id  = [stream-uri ","]
                   substream-type "," substream_id
stream-uri        = RTSP-URI
substream-type= "SVC" / "MVC" / token


substream_id    = layer-id
                     /(dependency-id ","temporal-id "," quality-id)
layer-id        = "layer_id=" layer_id_value
layer_id_value  = 1*4DIGIT                              ;0~2047
dependency-id   = "dependency_id=" dependency_id_value
dependency_id_value = DIGIT                             ;0~7
temporal-id     = "temporal_id="  temporal_id_value
temporal_id_value = DIGIT                               ;0~7
quality-id              = "quality_id=" quality_id_value
quality_id_value = 1*2DIGIT                             ;0~15
DIGIT           =  %x30-39              ;any US-ASCII digit "0".."9"


v=0
o=- 2890844256 2890842807 IN IP4 198.51.100.5
s=RTSP Session
i=An Example of substream control usage
e=adm@example.com
c=IN IP4 0.0.0.0
a=control: *
a=range: npt=0-0:10:34.10
t=0 0
m=video 20000 RTP/AVP 97
a=rtpmap:97 H264-SVC/90000
a=fmtp:97 profile-level-id=53000c; packetization-mode=1;
sprop-parameter-sets={sps0},{sps1},{pps0},{pps1};
sprop-operation-point-info=<1,0,0,0,4de00a,3200,176,144,128,
dest_addr="192.0.2.53:8002"/"192.0.2.53:8003";
src_addr="198.51.100.5:9002"/"198.51.100.5:9003";

ssrc=0D12F123:seq=12345;rtptime=3450012,



