ipDiffServCodePoint=0, applicationTag='12...24', 
octetTotalCount=123456 } 
         
ipDiffServCodePoint=0, applicationTag='1...1', 
octetTotalCount=123456 } 
         
ipDiffServCodePoint=0, applicationTag='2...90', 
octetTotalCount=123456 } 
         
protocol=17, ipDiffServCodePoint=0, 
applicationTag='3..161', octetTotalCount=123456 } 
      
ipDiffServCodePoint=0, applicationTag='13...10000', 
octetTotalCount=123456 } 
         
protocol=17, destinationTransportPort=23, 
applicationTag='3..80', octetTotalCount=123456 } 
                     
applicationName="foo", 
applicationDescription="The Cisco foo protocol", 
         
scope=applicationTag='13...10000', 
applicationName="Citrix", 
applicationDescription="A Citrix application" } 
         
dataType="string" 
group="application" 
elementId="94" applicability="all" status="current"> 
dataType="octetArray" 
group="application" 
dataTypeSemantics="identifer" 
elementId="95" applicability="all" status="current"> 
dataType="string" 
group="application" 
elementId="96" applicability="all" status="current"> 
