Pmin=0, meaning with average queue length below Qmin, there will be no
diffServMinRateRel = (diffServMinRateAbs*1000000)/ifSpeed

diffServMinRateRel = diffServMinRateAbs/ifHighSpeed"
diffServMinRateRel = (diffServMinRateAbs*1000000)/ifSpeed

diffServMinRateRel = diffServMinRateAbs/ifHighSpeed"
diffServMaxRateRel = (diffServMaxRateAbs*1000000)/ifSpeed

diffServMaxRateRel = diffServMaxRateAbs/ifHighSpeed"
diffServMaxRateRel = (diffServMaxRateAbs*1000000)/ifSpeed
diffServMaxRateRel = diffServMaxRateAbs/ifHighSpeed"
