m=<media> <port> <proto> <fmt> ...

m=application 54111 SCTP/DTLS 54111
a=sctpmap:54111 t38 1


m=application 54111 DTLS/SCTP 5000
c=IN IP4 79.97.215.79
a=sctpmap:5000 webrtc-datachannel max-message-size=100000 streams=16



sctpmap-attr        =  "a=sctpmap:" sctpmap-number
                                 app [max-message-size] [streams]
sctpmap-number      =  1*DIGIT
app                 =  token
max-message-size    =  "max-message-size" EQUALS 1*DIGIT
streams             =  "streams" EQUALS 1*DIGIT"


m=application 54111 SCTP 54111
c=IN IP4 192.0.2.2
a=setup:actpass
a=connection:new
a=sctpmap:54111 t38 1

                                 Figure 1

m=application 54321 SCTP 54321
c=IN IP4 192.0.2.1
a=setup:passive
a=connection:new
a=sctpmap:t54321 t38 1

                                 Figure 2

m=application 54321 SCTP *
c=IN IP4 192.0.2.1
a=setup:passive
a=connection:existing

                                 Figure 3

m=application 54111 SCTP *
c=IN IP4 192.0.2.2
a=setup:active
a=connection:existing

                                 Figure 4

m=application 54111 DTLS/SCTP 5000
c=IN IP4 192.0.2.2
a=setup:actpass
a=connection:new
a=fingerprint:SHA-1 \
             4A:AD:B9:B1:3F:82:18:3B:54:02:12:DF:3E:5D:49:6B:19:E5:7C:AB
a=sctpmap:5000 webrtc-DataChannel max-message-size=100000 streams=16



                                 Figure 5

m=application 62442 DTLS/SCTP 5001
c=IN IP4 192.0.2.1
a=setup:actpass
a=connection:new
a=fingerprint:SHA-1 \
             4A:AD:B9:B1:3F:82:18:3B:54:02:12:DF:3E:5D:49:6B:19:E5:7C:AB
a=sctpmap:5001 webrtc-DataChannel max-message-size=100000 streams=16


                                 Figure 6


sctpmap-attr        =  "a=sctpmap:" sctpmap-number
                                 app [max-message-size] [streams]
sctpmap-number      =  1*DIGIT
app                 =  token
max-message-size    =  "max-message-size" EQUALS 1*DIGIT
streams             =  "streams" EQUALS 1*DIGIT"


