Link = Version CRLF [ Source CRLF ] [ Destination CRLF ] Type
Schema-Version = "Schema-Version" ":" 1*Digit "." 1*Digit 
Source = "Source" ":" ( URI | "SET" ) 
Destination = "Destination" ":" ( URI | "SET" ) 
Type = "Type" ":" token
LinkResult = Version CRLF LinkSource CRLF LinkDestination CRLF
LinkSource = "Source" ":" URI 
LinkDestination = "Destination" ":" URI 
Type = "Type" ":" token

UnLink = Version CRLF Source CRLF Destination CRLF Type CRLF
Schema-Version = "Schema-Version" ":" 1*Digit "." 1*Digit 
LinkSource = "Source" ":" URI 
LinkDestination = "Destination" ":" URI 
Type = "Type" ":" token
UnLinkResult = Version CRLF 1*(LinkSource CRLF LinkDestination
Schema-Version = "Schema-Version" ":" 1*Digit "." 1*Digit 
LinkSource = "Source" ":" URI 
LinkDestination = "Destination" ":" URI 
Type = "Type" ":" token
LinkSearchMethod = Schema-Version CRLF [SearchPoints] CRLF
SearchPoints = "SearchPoints" ":" 1#URI 
SearchPattern = "SearchPattern" ":" 1*SearchOperations
SearchOperations = And | Or | Not | Item
And = "&" 2*SearchOperations
Or = "|" 2*SearchOperations
Not = "!" SearchOperations 
Item = Operator CompareTo MatchPattern
Operator = "=" | "!="
CompareTo = "Source" | "Destination" | "Type"
MatchPattern = 1*(token | " *") CRLF 
Scope = "Scope" ":" 1*Digit | "Sub" 

Type = "DAV/LinkResponse"

Entry = [OnSource] [OnDestination] Type
OnSource = ["ON"] "Source" ":" URI CRLF
OnDestination = ["ON"] "Destination" ":" URI CRLF
Type = "Type" ":" token CRLF

GetLinksMethod = Schema-Version CRLF TaggedType CRLF
TaggedType = "Type" ":" #type | "All"
GetLinkValMethod = Schema-Version CRLF TaggedType CRLF 
SETLINKVAL = Schema-Version CRLF LINK CRLF PutDestination CRLF ;
PutWhere = "Put-Where" ":" "Source" | "Destination"

Type = "DAV/History"
Name = VersionToken
Rel = ("ParentEntry" | "ChildEntry" | "SiblingEntry")
Version = Token
HREF = Pointer to a web collection w/more information
Rel = ("Parent" | "Child" | "Sibling")
Version = Token
HREF = Pointer to a parent, child, or sibling.
Type = "DAV/Identifier"

ContactURI = "URI"

LockBody = Schema-Version LockEntry CRLF TimeOut CRLF 
                     [LockRange CRLF] [LockOwner CRLF]
LockEntry = "LockEntry" ":" LockWriteExclusive 
LockWriteExclusive = "write exclusive" 
TimeOut = "TimeOutSeconds" ":" TimeOutVal 
TimeOutVal = 1*digit | "Infinite" 
LockRange = "LockRange" ":" 1*digit "-" (1*digit | "eof++") 
LockOwner = "LockOwner" ":" URI
ResourceLockResponse = WC_Open LockResponse WC_Close 
WC_Open = "<"WC VERSION=<">1.0<"> TYPE="
LockToken = token

LockResponse = *WCAT LockData *WCAT 
LockData = "<WCDATA>" LockURI LockBody LockGranted "</WCDATA>"
                      ; LockBody production from Section 4.2.2

LockURI = "ResourceLocked" ":" URI
LockGranted = "LockGranted" ":" RFC1123-date [*digit]  ;*digit
WC_Close = "</WC>" 
UnlockRequest = Schema-Version UnLockToken
UnLockToken = "UnLock-Token" ":" LockToken 
src = URI of the resource
dest = URI of the lock discovery WC
type = "LockInfo" 

LockDiscoveryResponse = WC_Open LockResponse OtherFields WC_Close

WC_Open = "<"WC VERSION=<">1.0<"> TYPE=<">DAV/LockDiscovery<">
NAME=<">" LockToken "<">>"
LockResponse = *WCAT LockData *WCAT 
LockData = "<WCDATA>" LockBody LockGranted "</WCDATA>" 
LockGranted = RF1123-date [*digit] 
OtherFields = (implementation specific) * 
WC_Close = "</WC>" 
copy = Schema-Version CRLF destination CRLF copylink CRLF
Schema-Version = 1*DIGIT "." 1*DIGIT
destination = "destination" ":" URI
copylink = "copylink" ":" value
value = "true" | "false"
request-version = "Request-Version" ":" token
Move = Schema-Version CRLF destination CRLF movelink CRLF
Schema-Version = 1*DIGIT "." 1*DIGIT
destination = "destination" ":" URL
movelink = "movelink" ":" value
value = "true" | "false"
request-version = "Request-Version" ":" token

MessageCollection = Version CRLF CollectionType CRLF
CollectionType = "Collection Type" ":" ("HC" | Text)
CREATECOLLECTIONERROR = WC_OPEN Type WC_CLOSE
ContentError = "DAV/Error/CreateCollection"
Type = "Do Not Support Type" ":" ("HC" | Text)

AddResource = Version CRLF URIType CRLF URIEntry CRLF
URIType = "Type" ":" ("Relative" | "Absolute")
URIEntry = "URI" ":" (relativeURI | absoluteURI)

RemoveResource = AddResource

PropagateLevel = "PropagateLevel" ":" (1*Digit | "Infinity")

Type = "DAV/Error/Prop/FailedAt"

Entry = "Propagation Mechanism Failed at" ":" *(Relative |
Relative = "Base" ":" Absolute_URI "Relative" ":" *Relative_URI
Checkout        = Schema-Version CRLF [Derived-From CRLF]
Schema-Version  = "Schema-Version" ":" 1*DIGIT "." 1*DIGIT

Derived-From    = "Derived-From" ":" #token

Request-Version = "Request-Version" ":" token

Request-Lock    = "Request-Lock" ":" "Exclusive" "Write"

Request-Intent  = "Request-Intent" ":" ("true" | "false")

Request-Working-Loc = "Request-Working-Loc" ":" ("Client" |
Request-Visibility = "Request-Visibility" ":" Visible-When
Visible-When    = ("Always" | "If_Locked" | "Never") 
Visible-Where   = ("On_CheckOut_Root" | "On_Working" | "On_Both")

CheckoutResult     = WC-Open CheckoutResultData WC-Close

WC-Open            = "<WC VERSION =<">1.0<"> TYPE
CheckoutResultData = *WCAT WCCheckoutData WCAT

WCAT               = {arbitrary, server-defined Web Collection
WCCheckoutData     = "<WCDATA>" DerivedTree DerivedRoot [WorkURI]

                               [WorkVersion] [Visibility]














CheckIn          = Schema-Version CRLF [Derived-From CRLF]

                             [Working-Resource CRLF] [Request-Version CRLF] 














Body = 1#("URI" ":" URI | "Entity" ":" entity-body) 

           

Type = application/servermerge

Merge = Schema-Version CRLF MergeType CRLF [MergeEntities CRLF] 
                  ReturnType CRLF [ReturnURI CRLF]
MergeType = "Merge Types" ":" ("URIs" | "Bodies" | "URIs"
MergeEntities = "Merge Entries" ":" #URI
ReturnType = "Return Result" ":" ("URI" | "Body")
ReturnURI = "Return Location" ":" URI
Command_Comment = "Comment" ":" CommentVal
CommentVal = URI | comment 

MaxLengthHeader = "MaxLength" ":" Size Partial CRLF
Size = "Size" ":" Bytes-Unit 1*Digit
Partial = "Partial" ":" ("Acceptable" | "Not Acceptable") 

           

IfLockHeader = "If-Lock" ":" #LockToken CRLF 

           

CommandComments  = ("CCMD" | "Command-Comments") ":"
LangTaggedString = Lang UTF-8   ; See RFC 2044 for UTF-8
Lang             = "(" LangTag ")"
LangTag          = 1*8ALPHA *("-"1*8ALPHA)

           

Overwrite = "Overwrite" ":" ("Yes" | "No")
LinkSearch = "LinkSearch" ":" HTTP_url ; See section 3.2.2 of
LinkSearchSuffix = "?" Attribute
Attribute = token

LinkPrefix = "LinkPrefix" ":" HTTP_url
LinkPrefixSuffix = "?" URL LinkSearchSuffix

