SA => Sender Server: SA represents an email server where the sender 
      is known. 
    
SB => Recipient Server: SB represents an email server where the 
ASCII=> American Standard Code for Information Interchange (ASCII) is 
IP => Internet Protocol (IP) is designed for use in interconnected 
MIME => Multipurpose Internet Mail Extensions (MIME) is an extension 
RFC => Request For Comment (RFC) forms a series of notes, started in 
SMTP => Simple Mail Transfer Protocol (SMTP) is to transfer any mail 
TCP => Transmission Control Protocol (TCP) is intended for use as a 
