TRN = 0

AUG = 0

RTT=10ms, M=1500B, the data not transmitted in time due to a packet
M = packet size in Bytes. The following analyses assumes W=W0.
I = 2*RTT*W/2 = RTT*W = RTT^2*C/(8*M).

D = C/8*I/4 = C^2*RTT^2/(256*M)



