v= Version (plain-text; REQUIRED).  Identifies the record retrieved
bimi-version = %x76 *WSP "=" *WSP %x42.49.4d.49 1DIGIT

a= Authority Evidence Location (plain-text; URI; OPTIONAL).  If
bimi-evidence-location = %x61 *WSP "=" bimi-uri

bimi-uri = \[FWS\] URI \[FWS\]

l= location (URI; REQUIRED).  The value of this tag is either empty
bimi-location = %x6c *WSP "=" bimi-uri

bimi-sep = *WSP %x3b *WSP

bimi-record = bimi-version (bimi-sep bimi-location) (bimi-sep bimi-evidence-location) \[bimi-sep\]

v=BIMI1; l=; a=;

selector = sub-domain *( "." sub-domain )

v= Version (plain-text; REQUIRED).  The version of BIMI.  It MUST
bimi-header-version = "v" *WSP "=" *WSP "BIMI" 1DIGIT

s= Selector (plain-text; REQUIRED).  The location of the BIMI DNS
bimi-selector = "s" *WSP "=" *WSP selector

bimi-selector-header = bimi-header-version bimi-sep bimi-selector \[bimi-sep\]

v= Version (plain-text; REQUIRED).  The version of BIMI.  It MUST
bimi-location-header-uri = "l" *WSP "=" bimi-uri

bimi-evidenced-location-header-uri = "a" *WSP "=" bimi-uri

bimi-location-header-location-only = bimi-location-header-uri

bimi-location-header-evidence-only = bimi-evidence-location-header-uri

bimi-location-header-both = bimi-location-header-uri bimi-evidence-location-header-uri

bimi-location-options = bimi-location-header-location-only / bimi-location-header-evidence-only / bimi-location-header-both

bimi-location-header = bimi-header-version bimi-sep bimi-location-options \[bimi-sep\]

base64string    =  ALPHADIGITPS *([FWS] ALPHADIGITPS)
                      [ [FWS] "=" [ [FWS] "=" ] ]

bimi-indicator-header = bimi-sep base64string \[bimi-sep\]

dkim=pass (signature was verified) header.d=example.com;
dmarc=pass header.from=example.com;
bimi=pass header.d=example.com header.selector=brand;

