docType="files-in-ebml-demo" version="1">
id="0x42F7" minOccurs="1" maxOccurs="1" range="1" default="1"
type="uinteger"/>
path="1*1(\EBML\EBMLMaxSizeLength)" id="0x42F3" minOccurs="1"
maxOccurs="1" range="8" default="8" type="uinteger"/>
type="master">
type="master" minOccurs="1">
id="0x614E" type="utf-8"
minOccurs="1">
id="0x464D" type="string"
minOccurs="1">
path="1*1(\Files\File\ModificationTimestamp)" id="0x4654"
type="date" minOccurs="1">
type="binary" minOccurs="1">
docType="matroska">".

EBMLFullPath          = [EBMLParentPath] EBMLElementPath
EBMLParentPath        = EBMLFixedParent EBMLLastParent
EBMLFixedParent       = *(EBMLPathAtom)
EBMLElementPath       = EBMLPathAtom / EBMLPathAtomRecursive
EBMLPathAtom          = PathDelimiter EBMLAtomName
EBMLPathAtomRecursive = "(1*(" EBMLPathAtom "))"
EBMLLastParent        = EBMLPathAtom / EBMLGlobalParent
EBMLGlobalParent      = "(" GlobalParentOccurence "\)"
EBMLAtomName          = 1*(EBMLNameChar)
EBMLNameChar          = ALPHA / DIGIT / "-" / "."
PathDelimiter         = "\"
GlobalParentOccurence = [PathMinOccurrence] "*" [PathMaxOccurrence]
PathMinOccurrence     = 1*DIGIT ; no upper limit
PathMaxOccurrence     = 1*DIGIT ; no upper limit

minOccurs="1" maxOccurs="1">
type="master">
type="float" maxOccurs="1">
type="string" maxOccurs="1">
targetNamespace="https://ietf.org/cellar/ebml"
elementFormDefault="qualified" version="01">

schemaLocation="http://www.w3.org/MarkUp/SCHEMA/xhtml11.xsd"/>

minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="1"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
