statusInformation =
statusInformation =
tmTransportDomain  = snmpTLSTCPDomain or snmpDTLSUDPDomain as
          appropriate.
tmTransportAddress  = The address the message originated from.

tmSecurityLevel  = The derived tmSecurityLevel for the session,
          as discussed in Section 3.1.2 and Section 5.3.

tmSecurityName  = The derived tmSecurityName for the session as
          discussed in Section 5.3.  This value MUST be constant during
          the lifetime of the session.

tmSessionID  = The tlstmSessionID described in step 1 above.

statusInformation =
statusInformation =
statusInformation =           -- errorIndication or success
statusInformation =
vacmSecurityModel              = 4 (TSM)
vacmSecurityName               = "Joe Cool"
vacmGroupName                  = "administrators"
vacmSecurityToGroupStorageType = 3 (nonVolatile)
vacmSecurityToGroupStatus      = 4 (createAndGo)

snmpTargetAddrName             =  "toNRAddr"
snmpTlstmAddrServerFingerprint =  ""
snmpTlstmAddrServerIdentity    =  "server.example.org"
snmpTlstmAddrStorageType       =  3         (nonVolatile)
snmpTlstmAddrRowStatus         =  4         (createAndGo)

snmpTargetAddrName              = "toNRAddr"
snmpTargetAddrTDomain           = snmpTLSTCPDomain
snmpTargetAddrTAddress          = "192.0.2.1:XXXsnmptls-trap"
snmpTargetAddrTimeout           = 1500
snmpTargetAddrRetryCount        = 3
snmpTargetAddrTagList           = "toNRTag"
snmpTargetAddrParams            = "toNR"     (MUST match above)
snmpTargetAddrStorageType       = 3          (nonVolatile)
snmpTargetAddrColumnStatus      = 4          (createAndGo)

snmpTargetParamsName            = toNR
snmpTargetParamsMPModel         = SNMPv3
snmpTargetParamsSecurityModel   = 4 (TransportSecurityModel)
snmpTargetParamsSecurityName    = "Joe Cool"
snmpTargetParamsSecurityLevel   = 3          (authPriv)
snmpTargetParamsStorageType     = 3          (nonVolatile)
snmpTargetParamsRowStatus       = 4          (createAndGo0

snmpTlstmCertToTSNID          = 1
                                       (chosen by ordering preference)
snmpTlstmCertToTSNFingerprint = HASH (appropriate fingerprint)
snmpTlstmCertToTSNMapType     = snmpTlstmCertSANAny
snmpTlstmCertToTSNData        = ""  (not used)
snmpTlstmCertToTSNStorageType = 3   (nonVolatile)
snmpTlstmCertToTSNRowStatus   = 4   (createAndGo)

snmpTlstmCertToTSNID           = 1
                                        (chosen by ordering preference)
snmpTlstmCertToTSNFingerprint  = HASH (appropriate fingerprint)
snmpTlstmCertToTSNMapType      = snmpTlstmCertSpecified
snmpTlstmCertToTSNSecurityName = "Joe Cool"
snmpTlstmCertToTSNStorageType  = 3  (nonVolatile)
snmpTlstmCertToTSNRowStatus    = 4  (createAndGo)
