Len = 1     |     0-255     |
               +-+-+-+-+-+-+-+-+

                0                   1
                0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5
               +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Len = 2     |            0-65535            |
               +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

Len = 3 is 24 bits, Len = 4 is 32 bits etc.


         Figure 3:  Variable length unsigned integer value format

link-value        = "<" URI-Reference ">" *( ";" link-param )
link-param        = ( ( "desc" "=" URI )
                       | ( "name" "=" quoted-string )
                       | ( "type" "=" ( media-type | media-code) )
                       | ( "id" "=" integer )
                       | ( link-extension ) )
link-extension    = ( parmname [ "=" ( ptoken | quoted-string ) ] )
ptoken            = 1*ptokenchar
ptokenchar        = "!" | "#" | "$" | "%" | "&" | "'" | "("
                       | ")" | "*" | "+" | "-" | "." | "/" | DIGIT
                       | ":" | "<" | "=" | ">" | "?" | "@" | ALPHA
                       | "[" | "]" | "^" | "_" | "`" | "{" | "|"
                       | "}" | "~"
media-code        = see Section 11.2
media-type        = type-name "/" subtype-name


