Full-Request   = Request-Line             
                 *( General-Header          
                  | Request-Header          
                  | Entity-Header )  CRLF       
                 [ Entity-Body ]
                  
Entity-Header  = Allow                     
                 | Content-Encoding          
                 | Content-Length            
                 | Content-Type              
                 | Expires                   
                 | Last-Modified             
                 | extension-header            
                        
