Decision-Flags='Install' (Figure 2 - step 7). To reject the requested 
Flags='install' and includes the suggested SLS in the Client Specific
Report-Type=Success or reject the suggested SLS by sending a RPT
