c=<nettype> <addrtype> <connection-address>

c=PSTN E164 +15551234

c=PSTN - -

m=<media> <port> <proto> <fmt> ...

m=audio 9 PSTN 3 0 8

m=audio 9 PSTN -

m=video 9 PSTN 34

m=video 9 PSTN -

a=cs-correlation:callerid:+15551234

a=cs-correlation:dtmf:14D*3

a=cs-correlation:uuie dtmf

a=cs-correlation:uuie:2890W284hAT452612908awudfjang908 dtmf:14D*3

o=<username> <sess-id> <sess-version> <nettype> <addrtype>
connection-field   =  [%x63 "=" nettype SP addrtype SP
e164-address       =  ["+"] 1*15DIGIT
cs-correlation-attr= "cs-correlation:" corr-mechanisms
corr-mechanisms    = corr-mech *(SP corr-mech)
corr-mech          = caller-id-mech / uuie-mech / dtmf-mech / ext-mech
caller-id-mech     = "callerid" [":" caller-id-value]
caller-id-value    = ["+"] 1*DIGIT
uuie-mech          = "uuie" [":" uuie-value]
uuie-value         = 1*32(ALPHA/DIGIT)
dtmf-mech          = "dtmf" [":" dtmf-value]
dtmf-value         = 1*32(DIGIT / %x41-44 / %x23 / %x2A )
ext-mech           = token
v=0
o=jdoe 2890844526 2890842807 IN IP4 192.0.2.5
s=
t=0 0
m=audio 9 PSTN -
c=PSTN E164 +15551234
a=setup:actpass
a=connection:new
a=cs-correlation:uuie:2890W284hAT452612908awudfjang908

                          Figure 4: SDP offer (1)


