T=0: Optional (may drop this field if this OH-TYPE is unknown) 
T=1: Mandatory (should not process this message if this OH-TYPE
                    is unknown)

C=0: More Optional Header fields follow
C=1: End of Optional Header fields group (i.e., this is the last OH)

PL=8*[(L+9)/8]-2-L.
L=4    #1       #2       #3       #4    padding  padding
type = 0xxx Physical Address
                       10xx L2RH
                       110x Reserved
                       1110 Logical Address
                       1111 Symbols
