template-type=service:diameter

template-version=0.0
template-description=
     The DIAMETER protocol is defined by draft-calhoun-diameter-17.txt

template-url-syntax=
url-path= ; The standard service URL syntax is used.
               ; For example: 'service:diameter://aaa.example.com:1812

supported-extensions= string L M
supported-transports= string L M
vendor-flag="disallowed" mandatory-flag="required">
         <name> Proxy-State </name>
         <type>
           <grouped>
             <member-name> State-Creator </member-name>
             <member-name> State-Opaque </member-name>
           </grouped>
         </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Host-IP-Address </name>
         <type ip-address="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Host-Name </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="disallowed">
         <name> Vendor-Name </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="disallowed">
         <name> Firmware-Revision </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> User-Password </name>
         <type> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> CHAP-Password </name>
         <type> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> NAS-IP-Address </name>
         <type ip-address="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> NAS-Port </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Service-Type </name>
         <type> Unsigned32 </type>
         <value>
           <val> 1 </val>
           <desc> Login </desc>
         </value>
         <value>
           <val> 2 </val>
           <desc> Framed </desc>
         </value>
         <value>
           <val> 3 </val>
           <desc> Callback Login </desc>
         </value>
         <value>
           <val> 4 </val>
           <desc> Callback Framed </desc>
         </value>
         <value>
           <val> 5 </val>
           <desc> Outbound </desc>
         </value>
         <value>
           <val> 6 </val>
           <desc> Administrative </desc>
         </value>
         <value>
           <val> 7 </val>
           <desc> NAS Prompt </desc>
         </value>
         <value>
           <val> 8 </val>
           <desc> Authenticate Only </desc>
         </value>
         <value>
           <val> 9 </val>
           <desc> Callback NAS Prompt </desc>
         </value>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Framed-Protocol </name>
         <type> Unsigned32 </type>
         <value> <val> 1 </val> <desc> PPP </desc> </value>
         <value> <val> 2 </val> <desc> PPP </desc> </value>
         <value>
           <val> 3 </val>
           <desc> AppleTalk Remote Access Protocol (ARAP) </desc>
         </value>
         <value>
           <val> 4 </val>
           <desc>
          Gandalf proprietary SingleLink/MultiLink protocol
           </desc>
         </value>
         <value>
           <val> 5 </val>
           <desc> Xylogics proprietary IPX/SLIP </desc>
         </value>
         <value> <val> 6 </val> <desc> X.75 Synchronous </desc> </value>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Framed-IP-Address </name>
         <type ip-address="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Framed-IP-Netmask </name>
         <type ip-address="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Framed-Routing </name>
         <type> Unsigned32 </type>
         <value> <val> 0  </val> <desc> None </desc> </value>
         <value>
           <val> 1 </val>
           <desc> Send routing packets </desc>
         </value>
         <value>
           <val> 2 </val>
           <desc> Listen for routing packets </desc>
         </value>
         <value> <val> 3 </val> <desc> Send and Listen </desc> </value>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Filter-Id </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Framed-MTU </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Framed-Compression </name>
         <type> Unsigned32 </type>
         <value>
           <val> 0 </val>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Login-IP-Host </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Login-Service </name>
         <type> Unsigned32 </type>
         <value>
           <val> 0 </val>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Login-TCP-Port </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Reply-Message </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Callback-Number </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Callback-Id </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Framed-IP-Route </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Framed-IPX-Route </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Idle-Timeout </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Called-Station-Id </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Calling-Station-Id </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> NAS-Identifier </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Login-LAT-Service </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Login-LAT-Node </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Login-LAT-Group </name>
         <type> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Framed-Appletalk-Link </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Framed-Appletalk-Network </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Framed-Appletalk-Zone</name>
         <type> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> CHAP-Challenge </name>
         <type> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> NAS-Port-Type </name>
         <type> Unsigned32 </type>
         <value> <val> 0 </val> <desc> Async </desc> </value>
         <value> <val> 1 </val> <desc> Sync </desc>     </value>
         <value> <val> 2 </val> <desc> ISDN Sync </desc> </value>
         <value> <val> 3 </val> <desc> ISDN Async V.120 </desc> </value>
         <value> <val> 4 </val> <desc> ISDN Async V.110 </desc> </value>
         <value> <val> 5 </val> <desc> Virtual </desc> </value>
         <value> <val> 6 </val> <desc> PIAFS </desc> </value>
         <value>
           <val> 7 </val>
           <desc>  HDLC Clear Channel</desc>
         </value>
         <value> <val> 8 </val> <desc> X.25 </desc> </value>
         <value> <val> 9 </val> <desc> X.75 </desc> </value>
         <value> <val> 10 </val> <desc> G.3 Fax </desc> </value>
         <value>
           <val> 11 </val>
           <desc> </desc>
         </value>
         <value>
           <val> 12 </val>
           <desc> </desc>
         </value>
         <value>
           <val> 13 </val>
           <desc> </desc>
         </value>
         <value>
           <val> 14 </val>
           <desc> </desc>
         </value>
         <value> <val> 15 </val> <desc> Ethernet </desc> </value>
         <value> <val> 16 </val> <desc> xDSL </desc> </value>
         <value> <val> 17 </val> <desc> Cable </desc> </value>
         <value>
           <val> 18 </val>
           <desc> Wireless - Other </desc>
         </value>
         <value>
           <val> 19 </val>
           <desc> Wireless - IEEE 802.11  </desc>
         </value>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Port-Limit </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Login-LAT-Port </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Tunnel-Group </name>
         <type>
           <grouped>
             <member-name> Tunnel-Type </member-name>
             <member-name> Tunnel-Medium-Type </member-name>
             <member-name> Tunnel-Preference </member-name>
             <member-name> Tunnel-Client-Endpoint </member-name>
             <member-name> Tunnel-Server-Endpoint </member-name>
             <member-name> Tunnel-Password </member-name>
             <member-name> Tunnel-Private-Group-ID </member-name>
             <member-name> Tunnel-Assignment-Id </member-name>
             <member-name> Tunnel-Preference </member-name>
             <member-name> Tunnel-Client-Auth-ID </member-name>
             <member-name> Tunnel-Server-Auth-ID </member-name>
             </grouped>
         </type>
         <description>
           Tunnel AVPs are all accumulated into a Tunnel-Group.
           Each potential tunnel configuration is represented by
           a Tunnel-Group AVP.
         </description>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Tunnel-Type </name>
         <type> Unsigned32 </type>
         <value>
           <val> 1 </val>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Tunnel-Medium-Type </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Tunnel-Client-Endpoint </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Tunnel-Server-Endpoint </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Tunnel-Password </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Tunnel-Private-Group-ID</name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Tunnel-Assignment-Id </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Tunnel-Preference </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Tunnel-Client-Auth-ID </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Tunnel-Server-Auth-ID </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> </name>
         <type printable="true" > OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> </name>
         <type> Unsigned32 </type>
         <value>
           <val> 1 </val>
           <desc> AUTHENTICATE_ONLY </desc>
         </value>
         <value>
           <val> 2 </val>
           <desc> AUTHORIZE_ONLY </desc>
         </value>
         <value>
           <val> 3 </val>
           <desc> AUTHORIZE_AUTHENTICATE </desc>
         </value>
vendor-flag="disallowed" mandatory-flag="required">
         <name> EAP-Payload </name>
         <type> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Query-Index </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Resource-Token </name>
         <type>
           <grouped>
             <member-name> Session-ID </member-name>
             <member-name> Host-Name </member-name>
             <member-name> User-Name </member-name>
             <member-name> Timestamp </member-name>
             <member-name> Extension-Id </member-name>
             <member-name> Resource-Bag </member-name>
           </grouped>
         </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Resource-Bag </name>
         <type> OctetString </type>
         <description>
           This AVP encapsulates arbitrary user data.  This could
           be in the form of a vendor specified AVP with a group
           data type, for example.
         </description>
vendor-flag="disallowed" mandatory-flag="required">
         <name> MIP-Reg-Request </name>
         <type> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> MIP-Reg-Reply </name>
         <type> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> MN-AAA-Auth </name>
         <type>
           <group>
             <member-name> MN-AAA-SPI </member-name>
             <member-name> Authentication-Input-Data-Length </member-name>
             <member-name> Authenticator-Length </member-name>
             <member-name> Authenticator-Offset </member-name>
           </group>
         </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> MN-AAA-SPI </name>
         <type> Unsigned32 </type>
         <description>
            The SPI which indicates the algorithm by which the targeted
            AAA server (AAAH) should attempt to validate the
            Authenticator computed by the mobile node over the
            Registration Request data
         </description>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Authentication-Input-Data-Length </name>
         <type> Unsigned32 </type>
         <description>
            The length in bytes of the Registration Request data (data
            portion of MIP-Reg-Request AVP) that should be used as
            input to the algorithm (indicated by the MN-AAA SPI) used
            to determine whether the Authenticator Data supplied by the
            Mobile Node is valid.
         </description>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Authenticator-Length </name>
         <type> Unsigned32 </type>
         <description>
            The length of the authenticator to be validated by the
            targeted AAA server (i.e., AAAH).
         </description>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Authenticator-Offset </name>
         <type> Unsigned32 </type>
         <description>
            The offset into the Registration Request Data, of the
            authenticator to be validated by the targeted AAA server
            (i.e., AAAH).
vendor-flag="disallowed" mandatory-flag="required">
         <name> MN-to-FA-Key </name>
         <type>
           <grouped>
             <member-name> Peer-SPI </member-name>
             <member-name> Mobility-SA-Key </member-name>
           </grouped>
         </type>
         <description>
            The MN-to-FA-Key AVP contains the data immediately
            following the Mobile IP extension header of the
            "Unsolicited MN-FA Key From AAA Subtype", as documented
            in draft-calhoun-mobileip-aaa-key-01.txt.
         </description>
vendor-flag="disallowed" mandatory-flag="required">
         <name> MN-to-HA-Key </name>
         <type>
           <grouped>
             <member-name>  Peer-SPI </member-name>
             <member-name>  Mobility-SA-Key </member-name>
           </grouped>
         </type>
         <description>
            The HA-to-MN-Key AVP contains the data immediately
            following the Mobile IP extension header of the
            "Unsolicited MN-HA Key From AAA Subtype", as documented
            in draft-calhoun-mobileip-aaa-key-01.txt.
         </description>
vendor-flag="disallowed" mandatory-flag="required">
         <name> FA-to-MN-Key </name>
         <type>
           <grouped>
             <member-name> Peer-SPI  </member-name>
             <member-name> Mobility-SA-Key </member-name>
           </grouped>
         </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> FA-to-HA-Key </name>
         <type>
           <grouped>
             <member-name> Peer-SPI  </member-name>
             <member-name> Mobility-SA-Key </member-name>
           </grouped>
         </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> HA-to-MN-Key </name>
         <type>
           <grouped>
             <member-name> Peer-SPI  </member-name>
             <member-name> Mobility-SA-Key </member-name>
           </grouped>
         </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> HA-to-FA-Key </name>
         <type>
           <grouped>
             <member-name> Peer-SPI  </member-name>
             <member-name> </member-name>
           </grouped>
         </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Peer-SPI </name>
         <type> Unsigned32 </type>
         <description>
            A 32-bit opaque value, which the target MUST use to index
            all the necessary information recovered from the security
            information after it is decoded.
         </description>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Mobility-SA-Key </name>
         <type> OctetString </type>
         <description>
           This contains the key used to create a Mobility Security
           Association between the mobility nodes.
         </description>
vendor-flag="disallowed" mandatory-flag="required">
         <name> FA-MN-Preferred-SPI </name>
         <type> Unsigned32 </type>
         <description>
         </description>
vendor-flag="disallowed" mandatory-flag="required">
         <name> FA-HA-Preferred-SPI </name>
         <type> Unsigned32 </type>
         <description>
         </description>
vendor-flag="disallowed" mandatory-flag="required">
         <name> </name>
         <type> </type>
         <description>
         </description>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Mobile-Node-Address </name>
         <type ip-address="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Home-Agent-Address </name>
         <type ip-address="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Previous-FA-NAI </name>
         <type printable="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Previous-FA-Addr </name>
         <type ip-address="true"> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> MIP-Feature-Vector </name>
         <type> Unsigned32 </type>
         <description>
           The value of this AVP is added with flag values set
vendor-flag="disallowed" mandatory-flag="required">
         <name> Accounting-Record-Type </name>
         <type> Unsigned32 </type>
         <value>
           <val> 1 </val>
vendor-flag="disallowed" mandatory-flag="required">
         <name> ADIF-Record </name>
         <type> OctetString </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Accounting-Interim-Interval </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Accounting-Delivery-Max-Batch </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Accounting-Delivery-Max-Delay </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Accounting-Record-Number </name>
         <type> Unsigned32 </type>
vendor-flag="disallowed" mandatory-flag="required">
         <name> Accounting-State </name>
         <type> Unsigned32 </type>
         <value> <val> 1 </val> <desc> ENABLED </desc> </value>
         <value> <val> 2 </val> <desc> DISABLED </desc> </value>
