K_i = F(K_{i+1}). Hence F MUST take an input of size n_1 and map
D=1 indicates that this packet discloses the key of a previous
C=1 indicates that the commitment value of the next key chain is
L=1 indicates that the last key of the previous key chain is dis-
