auth-failure = "Auth-Failure:" [CFWS] token [CFWS] CRLF
         ; "token" must be a registered authentication failure type
         ; as specified elsewhere in this memo

delivery-result = "Delivery-Result:" [CFWS]
                         ( "delivered" / "spam" /"policy" /
                           "reject" / "other" ) [CFWS] CRLF

dkim-header = "DKIM-Canonicalized-Header:" [CFWS]
                     base64string CRLF
         ; "base64string" is imported from [DKIM]

dkim-domain = "DKIM-Domain:" [CFWS] domain [CFWS] CRLF

dkim-identity = "DKIM-Identity:" [CFWS] [ local-part ] "@"
                       domain-name [CFWS] CRLF
         ; "local-part" is imported from [MAIL]

dkim-selector = "DKIM-Selector:" [CFWS] token [CFWS] CRLF

dkim-adsp-dns = "DKIM-ADSP-DNS:" [CFWS]
                       quoted-string [CFWS] CRLF
         ; "quoted-string" is imported from [MAIL]

dkim-body = "DKIM-Canonicalized-Body:" [CFWS]
                   base64string CRLF

dkim-selector-dns = "DKIM-Selector-DNS:" [CFWS]
                           quoted-string [CFWS] CRLF

spf-dns = "SPF-DNS:" : { "txt" / "spf" } [FWS] ":" [FWS]
                  domain [FWS] ":" [FWS] quoted-string
boundary="------------Boundary-00=_3BCR4Y7kX93yP9uUPRhg";
report-type=feedback-report
from=anexample.example.com; dkim=fail (bodyhash);spf=pass
s=testkey; d=example.net; h=From:To:Subject:Date;
bh=2jUSOH9NhtVGCQWNr9BrIAPreKQjO6Sn7XIkfJVOzv8=;
b=AuUoFEfDxTDkHlLXSZEpZj79LICEps6eda7W3deTVFOk4yAUoqOB
