dst=node2-3, SLA)|            |              |             |
         |··········>|            |              |             |
         |           |2.Path compute req         |             |
         |           |(src={node2-1,node2-2},    |             |
         |           | dst=node2-3)              |             |
         |           |···········>|              |             |
         |           |3.Path compute resp        |             |
         |           |({tracks2},{links_quality})|             |
         |           |<···········|              |             |
PSE={node2-1,node2-2},        |              |             |
