href="/finance/feeds/default/portfolios/1/positions"/>
href="/finance/feeds/default/portfolios/1"/>
href="/finance/feeds/default/portfolios/1/positions">
href="/finance/feeds/default/portfolios/1"/>
href="/finance/feeds/default/portfolios/1/positions">
                    ...
              </atom:feed>
href="/finance/feeds/default/portfolios/1"/>
             ...
href="/finance/feeds/default/portfolios/1"/>
href="/finance/feeds/default/portfolios/1/positions"/>
href="/finance/feeds/default/portfolios/1"/>
        <atom:entry>
        <atom:link rel="detail"
href="/finance/feeds/default/portfolios/1/positions"/>
href="/finance/feeds/default/portfolios/1">
                    ...
              </atom:entry>
href="/finance/feeds/default/portfolios/1/positions"/>
             ...
hierarchyType =
     attribute h:role { "master" | "detail" }
href="/collection/master1/collection">
href='/finance/feeds/default/service'/>
type='application/atom+xml;type=feed' title='positions'
href='/finance/feeds/default/portfolios/1/positions'/>
href='/finance/feeds/default/portfolios/1'/>
return1w='0.0' return1y='0.0' return3m='0.0' return3y='0.0'
return4w='0.0' return5y='0.0' returnOverall='0.0' returnYTD='0.0'/>
type='application/atom+xml;type=feed' title='positions'
href='/finance/feeds/default/portfolios/2/positions'/>
type='text/html'
href='http://finance.example.com/portfolio/2'/>
href='/finance/feeds/default/portfolios/2'/>
return1w='0.0' return1y='0.0' return3m='0.0' return3y='0.0'
return4w='0.0' return5y='0.0' returnOverall='0.0' returnYTD='0.0'/>
exchange='NASDAQ' fullName='Siebel Systems' symbol='SEBL'/>
term='http://api.example.com/finance/2008#position'/>
href='/finance/feeds/default/portfolios/1/positions/NASD:SEBL'/>
return1w='0.0' return1y='0.0' return3m='0.0' return3y='0.0'
return4w='0.0' return5y='0.0' returnOverall='0.0' returnYTD='0.0'/>
symbol='SEBL'/>
