title="You do not have enough credits."; balance=30;
account="http://api.example.com/account/12345"

title="Hi there"; detail="something happened."
title="Hi there"; title*=UTF-8''Hi%20there; another=bar;
rel="describedby";
