a =============    CN is a node with basic IP     =============
                 |           |             |           |           |
                 |    HoTI   |             |           |           |
