rel="urn:ietf:params:push"
rel="urn:ietf:params:push:receipt"
date           = Thu, 11 Dec 2014 23:56:55 GMT
last-modified  = Thu, 11 Dec 2014 23:56:55 GMT
cache-control  = private
content-type   = ...
content-length = ...

