coverage="base base+body-sha-256",
timestamp="137131190"


coverage="base",
timestamp="137131200",
nonce="dj83hs9s",
auth="djosJKDKJSD8743243/jdk33klY="


challenge       = "Token" RWS token-challenge

token-challenge = realm
                      CS coverage-list
                      [ CS timestamp ]

coverage-list   = "coverage" "=" <"> 1#coverage-name <">
coverage-name   = "none" /
                      "base" /
                      "base+body-sha-256" /
                      token

timestamp       = "timestamp" "=" <"> 1*DIGIT <">

CS              = OWF "," OWF


credentials    = "Token" RWS token-response

token-response = token-id
                     CS coverage
                     [ CS nonce ]
                     [ CS timestamp ]
                     [ CS auth ]

token-id         = "token" "=" <"> token <">
coverage         = "coverage" "=" <"> coverage-name <">
nonce            = "nonce" "=" <"> token <">
auth             = "auth" "=" <"> token <">


Authentication-Error   = "Authentication-Error" ":"
                             OWS #1error-param

error-param            = error-code /
                             error-info /
                             error-message /
                             auth-param

error-code      = "error-code"    "=" <"> token <">
error-info      = "error-info"    "=" <"> token <">
error-message   = "error-message" "=" quoted-string


method-name     = "none" /
                      "hmac-sha-1" /
                      "hmac-sha-256" /
                      "rsassa-pkcs1-v1.5-sha-256" /
                      token


digest = HMAC-SHA1 (key, text)


digest = HMAC-SHA256 (key, text)


S = RSASSA-PKCS1-V1_5-SIGN (K, M)


