newsURL      =  scheme ":" [ news-server ] [ refbygroup | message ]
scheme       =  "news" | "snews" | "nntp"
news-server  =  "//" server "/"
refbygroup   = group [ "/" messageno [ "-" messageno ] ]
message      = local-part "@" domain

