f = [(s + T x N_S + chOff) mod N_C]          (Equation 1)

Configuration = {
      ? 2   : [ +Link_Layer_Key ],     ; link-layer key set
      ? 3   : Short_Identifier,        ; short identifier
      ? 4   : bstr,                    ; JRC address
      ? 6   : [ *bstr ],               ; blacklist
      ? 7   : uint,                    ; join rate
      ? TBD : [ +Permutation_Key ],    ; permutation key set
      ? TBD : Permutation_Cipher       ; permutation cipher
Permutation_Key = (
         key_value          : bstr
j = random integer such that 0 <= j <= i;
N_S = 3 // Slotframe size, in timeslots

N_C = 4 // Available channel offsets

X_s = {1, 1, 2} // Original timeslot utilization pattern {Tx, Tx, Rx}

X_c = {3, 1, 0} // Original channelOffset utilization pattern

K_s = { 0xce, 0xb0, 0x09, 0xae, 0xa4, 0x45, 0x44, 0x51,
           0xfe, 0xad, 0xf0, 0xe6, 0xb3, 0x6f, 0x45, 0x55 }

K_c = { 0xce, 0xb0, 0x09, 0xae, 0xa4, 0x45, 0x44, 0x51,
           0xfe, 0xad, 0xf0, 0xe6, 0xb3, 0x6f, 0x45, 0x56 }

