Type = 3
KEYMAT = K1 | K2 | K3 | ...
          where

K1   = SHA-1( Kij | sort(HIT-I | HIT-R) | I | J | 0x01 )
K2   = SHA-1( Kij | K1 | 0x02 )
K3   = SHA-1( Kij | K2 | 0x03 )
K255 = SHA-1( Kij | K254 | 0xff )
K256 = SHA-1( Kij | K255 | 0x00 )
I = Ltrunc( PHASH ( S | HIT-I | HIT-R | IP-I | IP-R ), 64)

