R1 = The initial Root key pair
R2 = The second generation Root key pair
H2 = Thumbprint (hash) of the public key of R2
C1 = Self-signed certificate for R1, which also contains H2

R3 = The third generation Root key pair
H3 = Thumbprint (hash) the public key of R3
C2 = Self-signed certificate for R2, which contains H3

