CR               = %x0D    ; carriage return
HTAB             = %x09    ; horizontal tab
LF               = %x0A    ; line feed
SP               = %x20    ; space
VCHAR            = %x21-7E ; visible (printing) characters

json-field-value = #json-field-item
json-field-item  = JSON-Text
                      ; see [RFC7159], Section 2,
                      ; post-processed so that only VCHAR characters
                      ; are used

Content-Length = 1*DIGIT

Content-Length = #number
                    ; number: [RFC7159], Section 6

WWW-Authenticate = 1#challenge

challenge   = auth-scheme [ 1*SP ( token68 / #auth-param ) ]

