From-header = "From" ": " [ Formal-name ] "<" URI ">"
To-header   = "To"   ": " [ Formal-name ] "<" URI ">"
Cc-header   = "cc"   ": " [ Formal-name ] "<" URI ">"

DISTSENDm       = %x44.49.53.54.53.45.4E.44  ; DISTSEND in caps

Method          = SENDm / REPORTm / AUTHm / DISTSENDm
                   / ext-method
headers = To-Path CRLF From-Path CRLF 1*( header CRLF )

header  =   Message-ID
             / Report-Success
             / Report-Failure
             / Byte-Range
             / Status
             / Distribution
             / ext-header

Distribution  = "Distribution:" SP recipient-URI *( SP recipient-URI)

recipient-URI = addr-spec / MSRP-url / telephone-uri /
                   nickname-urn / absolute-URI

nickname-urn = URN

