a=ptime:[packet time]

a=maxptime:[maximum packet time]

m=audio 1234 RTP/AVP 0 4 8
ptime=30

                                 Example1
m=audio 1234 RTP/AVP 4 0
a=rtpmap:4 G723/8000
a=rtpmap:0 PCMU/8000
a=ptime:20
a=fmtp:4 bitrate=6400

                                  Method1

m=audio 1234 RTP/AVP 4 0
a=rtpmap:4 G723/8000
a=fmtp:4 bitrate=6400
a=rtpmap:0 PCMU/8000
a=ptime:20

                                  Method2

m=audio 1234 RTP/AVP 0 18  4
a=rtpmap:18 G729/8000
a=ptime:30

a=rtpmap:0 PCMU/8000
a=ptime:40

a=rtpmap:4 G723/8000
a=ptime:60

                                  Method3

m=audio 1234 RTP/AVP 0 18  4
a=mptime 40 30 60

                                  Method4

m=audio 1234 RTP/AVP 0
a=rtpmap:0 PCMU/8000
a=ptime:40

m=audio 1234 RTP/AVP 18
a=rtpmap:18 G729/8000
a=ptime:30

m=audio 1234 RTP/AVP 4
a=rtpmap:4 G723/8000
a=ptime:60
                                  Method6

m=audio 1234 RTP/AVP 4 18
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=yes;ptime=20
a=maxptime:40

a=rtpmap 4 G723/8000
a=fmtp:4 bitrate=6.3;annexa=yes;ptime=30
a=maxptime:60

                                  Method7

a=vsel:G729 10 10000 G726-32 40 10000
a=vsel:G729 - - G726-32 - -

                                  Method8

