mid-attribute = "a=mid:" identification-tag
identification-tag = token
                        ; token is defined in RFC4566

group-attribute ="a=group:" semantics
                     *(SP identification-tag)
semantics = "OL" / semantics-extension
semantics-extension = token
                         ; token is defined in RFC4566

v=0
o=Alice 292742730 29277831 IN IP4 233.252.0.74
c=IN IP4 233.252.0.79
t=0 0
a=group:OL 1 2
m=video 30000 RTP/AVP 31
a=mid:1
m=audio 30002 RTP/AVP 31
a=mid:2

v=0
o=Alice 292742730 29277831 IN IP4 233.252.0.74
c=IN IP4 233.252.0.79
t=0 0
a=group:OL 1 2
m=video 30000 RTP/AVP 31
a= content:slides
a=mid:1
m=video 30002 RTP/AVP 31
a=content:speaker
a=mid:2

