Length=XX: The length of this option, counted in bytes - not 
              counting the Code and Length bytes. This is a variable
              length Option, therefore the length value will change 
              based on the shape within the Option.

Geotype=1  X-coordinate - this necessitates there be a 
                 Latitude Geovalue present.

Geotype=2  Y-coordinate - this necessitates there be a 
                 Longitude Geovalue present.

Geotype=3  Z-coordinate - this necessitates there be an
                 Altitude Geovalue present.

Geotype=4  Unit of Measurement Altitude (UofMA) - this 
                 necessitates there be an Altitude unit of measurement 
                 Geovalue present.

Geotype=4, Geovalue=1 - meters above or below the datum 0 plane.  

Geotype=4, Geovalue=2 - building floor.  

Geovalue=3 MUST be a plus '+' or minus '-' sign byte, indicating:

      For Geotype=3 - whether the altitude Geovalue is positive (above 
                      datum 0) or negative (below datum 0).




Geotype=2 (Y-coordinate) present.  Geotype=3 (Z-coordinate) and 
Geotype=4 (UofMA) MUST be implemented to comply with this 
shape=1.

Geotypes=11 (Datum) and =12 (Valid-for) are OPTIONAL, but MAY change
Geotype=5  Radius - the straight line from the point at the 
                 center of the circle, extending out a given distance 
                 (this is the Geovalue of the Radius Geotype).

Geotype=1 (the X-coordinate representing the center of the 
                 circle)
Geotype=2 (the Y-coordinate representing the center of the 
                 circle)
Geotype=5 (the Radius value from the center X/Y point of the 
                 circle)

Geotypes=7 through =10, which detail a Centerpoint (see Section 3.3 
shape=2.

Geotypes=11 (Datum) and =12 (Valid-for) are OPTIONAL, but MAY change
Geotype=6  # of Points - each point, in 2D, is a point of X and
                              Y coordinates.

Geotype=6, Geotype=1, Geotype=2, Geotype=1, Geotype=2, Geotype=1,
Geotype=2, etc...

Geotype=6, Geotype=1, Geotype=2, Geotype=3, Geotype=4, 
Geotype=1, Geotype=2, etc ...




Geotype=7  Polygon Centerpoint X-Coordinate - server calculated
                 center point X-Coordinate within a supplied polygon.

Geotype=8  Polygon Centerpoint Y-Coordinate - server calculated
                 center point X-Coordinate within a supplied polygon.

Geotype=9 Polygon Centerpoint Z-Coordinate - server calculated
                 center point X-Coordinate within a supplied polygon.

Geotype=10 Polygon Centerpoint Unit of Measurement Altitude - 
                 this is the same as the (UofMA) for Geotype=4 (from 
                 section 3.1).

Geotypes=7 through =10 MUST NOT appear in a shape=2 (circle) Option.
Geotype=7, Geotype=8, Geotype=9, Geotype=10

shape=3.

Geotype=9 and =10 MUST NOT be present without the corresponding 
Geotypes=7 and =8.  

Geotypes=11 (Datum) and =12 (Valid-for) are OPTIONAL in either a 2D 
Geotype=11 Datum - the base line of reference from which 
              measurements are taken out from (here both horizontally 
              and vertically).

Geovalue=1; two other datum combinations are included here.

Datum = 1 denotes WGS84 (EPSG4326) for 2D, and (EPSG4979) for 3D 
           (depending on whether an altitude Geotype is present).

Datum = 2 denotes the horizontal datum NAD83 as defined by the EPSG 
           as their CRS Code 4269; North American Vertical Datum of 
           1988 (NAVD88) is the associated vertical datum for NAD83

Datum = 3 denotes the vertical datum NAD83 as defined by the EPSG as
           their CRS Code 4269; Mean Lower Low Water (MLLW) is the
           associated vertical datum for NAD83

Geotype=12 Valid-for - measured in seconds the location within this 
              Option is to be considered good, before needing a 
              refresh, which maps to PIDF.  

Geovalue=3), the client determines that the PIDF-LO needs place 
Geovalue=1), the client has two options:

srsName="urn:ogc:def:crs:EPSG::4326" for 2D representations, and

srsName="urn:ogc:def:crs:EPSG::4979" for 3D representations.

substitutionGroup="gml:_CoordinateReferenceSystem"/>

substitutionGroup="gml:_CoordinateReferenceSystem"/>

Geotype=11 (Datum). If no Geotype=11 is present in this Option, it 
Datum = 1 denotes WGS84 (EPSG4326) for 2D, and (EPSG4979) for 3D 
           (depending on whether an altitude Geotype is present).

Datum = 2 denotes the horizontal datum NAD83 as defined by the EPSG 
           as their CRS Code 4269; North American Vertical Datum of 
           1988 (NAVD88) is the associated vertical datum for NAD83

Datum = 3 denotes the vertical datum NAD83 as defined by the EPSG as
           their CRS Code 4269; Mean Lower Low Water (MLLW) is the
           associated vertical datum for NAD83


