FQDN = Fully Qualified Domain Name
A = IP address
I = Identifier
L = Locator
P = Transport-layer port number

CN  = Correspondent Node
D  = Device
H  = Host
SBR  = Site Border Router

CN  = Correspondent Node
H  = Host
SBR  = Site Border Router

L_1 = global Locator value 1
L_2 = global Locator value 2
SBR = Site Border Router

CP     = coordination protocol
L_1    = global Locator value 1
L_2    = global Locator value 2
SBR_A  = Site Border Router A
SBR_B  = Site Border Router P

L_A  = global Locator value A
L_B  = global Locator value B
SBR  = Site Border Router

H = host
L_1 = global Locator value 1
L_2 = global Locator value 2
SBR = Site Border Router

