Preamble-Headers =  ( Version CRLF State *CRLF ) /
                       ( State CRLF Version *CRLF )

Version          =  "Version" HCOLON 1*DIGIT

State            =  "State" HCOLON ( "full" / "partial" )


Bodypart-Headers =  * (   Resource-URI
                          / Subscription-State
                          / content
                          / description
                          / encoding
                          / id
                         ) CRLF

Resource-URI     =  "Resource-URI" HCOLON ( name-addr / addr-spec )


