op     = BOOTREQUEST
htype  = Ethernet or (From "Assigned Numbers" RFC)
hlen   = 6 or (Hardware address length in octets)
hops   = 0
xid    = selected by client
secs   = 0
flags  = 0
ciaddr = mobile node's home address
yiaddr = 0
siaddr = 0
giaddr = 0
chaddr = mobile node's MAC address
giaddr = home agent's address

op     = BOOTREPLY
htype  = Ethernet or (From "Assigned Numbers" RFC)
hlen   = 6 or (Hardware address length in octets)
hops   = 0
xid    = same as "xid" field of DHCPINFORM message
secs   = 0
flags  = 0
ciaddr = mobile node's home address (from 'ciaddr' of DHCPINFORM)
yiaddr = 0
siaddr = 0
giaddr = home agent's address (from 'giaddr' of DHCPINFORM)
chaddr = mobile node's MAC address (from 'chaddr' of DHCPINFORM)
op     = BOOTREQUEST
htype  = Ethernet or (From "Assigned Numbers" RFC)
hlen   = 6 or (Hardware address length in octets)
hops   = 0
xid    = selected by client
secs   = 0
flags  = 0
ciaddr = mobile node's home address
yiaddr = 0
siaddr = 0
giaddr = 0
chaddr = mobile node's MAC address
giaddr = home agent's address

op     = BOOTREPLY
htype  = Ethernet or (From "Assigned Numbers" RFC)
hlen   = 6 or (Hardware address length in octets)
hops   = 0
xid    = same as "xid" field of DHCPINFORM message
secs   = 0
flags  = 0
ciaddr = mobile node's home address (from 'ciaddr' of DHCPINFORM)
yiaddr = 0
siaddr = 0
giaddr = home agent's address (from 'giaddr' of DHCPINFORM)
chaddr = mobile node's MAC address (from 'chaddr' of DHCPINFORM)
op     = BOOTREQUEST
htype  = Ethernet or (From "Assigned Numbers" RFC)
hlen   = 6 or (Hardware address length in octets)
hops   = 0
xid    = selected by client
secs   = 0
flags  = 0
ciaddr = mobile node's home address
yiaddr = 0
siaddr = 0
giaddr = 0
chaddr = mobile node's MAC address
op     = BOOTREPLY
htype  = Ethernet or (From "Assigned Numbers" RFC)
hlen   = 6 or (Hardware address length in octets)
hops   = 0
xid    = same as "xid" field of DHCPINFORM message
secs   = 0
flags  = 0
ciaddr = mobile node's home address (from 'ciaddr' of DHCPINFORM)
yiaddr = 0
siaddr = 0
giaddr = 0
chaddr = mobile node's MAC address (from 'chaddr' of DHCPINFORM)
