from_class  = keystring
to_class    = keystring
dbisMapAttr = from_class EQUALS to_class

from_attr   = keystring
to_attr     = keystring
classname   = keystring
dbisMapAttr = [classname SEMI] from_attr EQUALS to_attr

