dkim=   Outbound signing practices for the domain (plain-text;
      REQUIRED).  Possible values are as follows:

      unknown   The domain might sign some or all email.

      all    All mail from the domain is signed with an Author
         Signature.

      discardable   All mail from the domain is signed with an Author
         Signature.  Furthermore, if a message arrives without a valid
         Author Signature due to modification in transit, submission via
         a path without access to a signing key, or other reason, the
         domain encourages the recipient(s) to discard it.

      ABNF:
adsp-dkim-tag = %x64.6b.69.6d *WSP "=" *WSP
                            ("unknown" / "all" / "discardable")

