uncertainty = 2 ^ ( 8 - x )

x = 8 - ceil( log2( uncertainty ) )

AType = 0, to denote that the floor isn't known.  An altitude coded
Uncertainty = 2 ^ ( 21 - x )

x = 21 - ceil( log2( uncertainty ) )

mask = 0x3ffffffff >> resolution
lowvalue = value & ~mask
highvalue = value | mask + 1

scale = 2 ^ ( 9 - resolution )
lowvalue = floor( value / scale ) * scale
highvalue = lowvalue + scale

distance = 2 ^ (8 - uncertainty)
lowvalue = value - distance
highvalue = value + distance

distance = 2 ^ (21 - uncertainty)
lowvalue = value - distance

Latitude = 0x053c1f751,
Latitude = 0001010011110000011111011101010001
Longitude = 0xf50ba5b97,
Longitude = 1101010000101110100101101110010111

AltRes = 30, 0x1e, 011110
AType = 2, 0x02, 000010
Altitude = 103, 0x00006700, 000000000000000110011100000000

x = 8 - ceil( log2( -33.8570095 - -33.857720 ) )

x = 8 - ceil( log2( 151.2152005 - 151.214495 ) )

x = 21 - ceil( log2( 33.7 - 0 ) )

