MAC_P = CMAC-AES-128(AK, ID_P||ID_S||RAND_S||RAND_P)

MAC_S = CMAC-AES-128(AK, ID_S||RAND_P)

E=1 in its reply (the fourth EAP-PSK message) and include an EXT
IV=0x0123456789ABCDEFFEDCBA9876543210 (this value has been
