Answer = response-code [answertext] CRLF
	    text CRLF
	    "."	CRLF

text		 = %d1-9 /	     ; all octets except
		   %d11-12 /	     ; US-ASCII	NUL, CR	and LF
		   %d14-255

answertext	 = WSP *( ALPHA	/ DIGIT	/ "+" /	"-" / "/" / "_"	/
			      "." / ","	/ ":" /	"=" / "?" / "!"	/ SP )

utc-time	 = 14DIGIT  ; the date and time	of the server in UTC
			    ; YYYYMMDDhhmmss
response-code = 3DIGIT   ; three digit number

name			 =  plain-component *("." component)
component		 =  plain-component / encoded-word
encoded-word		 =  1*(	lowercase / DIGIT /
				"+" / "-" / "/"	/ "_" /	"=" / "?" )
plain-component	 =  component-start *component-rest
component-start	 =  lowercase /	DIGIT
lowercase		 =  %x61-7A ; letter a-z lowercase
component-rest	 =  component-start / "+" / "-"	/ "_"

help-cmd =  "HELP" [WSP commandname]	CRLF

commandname =  "DATA" / "DATE" / "GETP" / "GETA" /
		  "HELP" / "HIER" / "INFO" / "LIST" /
		  "LSTR" / "QUIT" / "VERS"

help-answer =  "410"	[answertext] CRLF
		  text CRLF
		  "." CRLF
help-answer =/ "100"	[answertext] CRLF
		  text CRLF
		  "." CRLF
info-cmd =  "INFO" CRLF

info-answer =  "400"	[answertext] CRLF
		  text CRLF
		  "." CRLF
info-answer =/ "101"	[answertext] CRLF
		  text CRLF
		  "." CRLF

date-cmd =  "DATE" CRLF

date-answer =  "511"	[answertext] CRLF
		  text CRLF
		  "." CRLF
date-answer =/ "300"	[answertext] CRLF
		  utc-time [answertext]	CRLF
		  "." CRLF

vers-cmd =  "VERS" [WSP level] CRLF

level = 1*5DIGIT ; the valid	range is 1 - 32767

vers-answer =  "202"	[answertext] CRLF
		  level	[answertext] CRLF
		  "." CRLF
vers-answer =/ "302"	[answertext] CRLF
		  level	[answertext] WSP level CRLF
		  "." CRLF
vers-answer =/ "402"	[answertext] CRLF
		  level	[answertext] WSP level CRLF
		  "." CRLF
vers-answer =/ "510"	[answertext] CRLF
		  level	[answertext] CRLF
		  "." CRLF

quit-cmd =  "QUIT" CRLF

quit-answer = "201" [answertext] CRLF

list-cmd =  "LIST" (	WSP "*"	/ 1*(WSP name))	CRLF

list-answer =  "610"	[answertext] CRLF
		  *(listdata CRLF)
		  "." CRLF
list-answer =/ "401"	[answertext] CRLF
		  text CRLF
		  "." CRLF
list-answer =/ "510"	[answertext] CRLF
		   text	CRLF
		   "." CRLF

listdata    =  name WSP list-status

list-status =  "Complete"	/
		  "Incomplete"	/
		  "Obsolete"	/
		  "Unknown"	/
		  "Unmoderated"	/
		  "Readonly"	/
		  "Moderated"	/
		  "Removed"	   ; list-status is case-insensitive

lstr-cmd = "LSTR" ( WSP "*" / 1*(WSP	name ["*" / ".*"]) ) CRLF

lstr-answer =  "610"	[answertext] CRLF
		  *(listdata CRLF)
		  "." CRLF
lstr-answer =/ "401"	[answertext] CRLF
		  text CRLF
		  "." CRLF
lstr-answer =/ "510"	[answertext] CRLF
		  text CRLF
		  "." CRLF

listdata    =  name WSP list-status

list-status =  "Complete"	/
		  "Incomplete"	/
		  "Obsolete"	/
		  "Unknown"	/
		  "Unmoderated"	/
		  "Readonly"	/
		  "Moderated"	/
		  "Removed"	   ; list-status is case-insensitive
hier-cmd  = "HIER" 1*(WSP name) [WSP	selection] CRLF

selection = *( "," header )	      ;	Describes the data fields
				      ;	that are requested
header    = ALPHA *(	ALPHA /	"-" ) ;	According to section 6.3.4

hier-answer =  "611"	[answertext] CRLF
		  *(hierdata CRLF)
		  "." CRLF
hier-answer =/ "510"	[answertext] CRLF
		  *(text CRLF)
		  "." CRLF
hier-answer =/ "401"	[answertext] CRLF
		  *(text CRLF)
		  "." CRLF

hierdata    =  "Name:" WSP text CRLF
		  "Status:" WSP	text CRLF
		  *(header ":" WSP text	CRLF)
		  [("Ctl-PGP-Key:" CRLF	PGP-answer /
		    "Mod-PGP-Key:" CRLF	PGP-answer)]

data-cmd  = "DATA" 1*(WSP name) [WSP	selection] CRLF

data-answer =  "612"	[answertext] CRLF
		  *(datadata CRLF)
		  "." CRLF
data-answer =/ "510"	[answertext] CRLF
		  text CRLF
		  "." CRLF
data-answer =/ "401"	[answertext] CRLF
		  text CRLF
		  "." CRLF

datadata    =  "Name:" WSP text CRLF
		  "Status:" WSP	text CRLF
		  *(header ":" WSP text	CRLF)
		  [("Ctl-PGP-Key:" CRLF	PGP-answer /
		    "Mod-PGP-Key:" CRLF	PGP-answer)]

getp-cmd =  "GETP" WSP username WSP password	WSP timestamp
	       WSP ( name / "*"	) CRLF

username =  *1( VCHAR ) / "0" ; Length of VCHAR >= 1

password =  *1( VCHAR ) / "0" ; Length of VCHAR >= 1

timestamp   =  utc-time / ; date and	time of	the last retrieval
		  "0"	     ; force the transmission of data

getp-answer =  "613"	[answertext] CRLF
		  pgp-ascii-armor-start	; this is according to [RFC2440]
		  *(getpdata CRLF)
		  pgp-ascii-armor-end	; this is according to [RFC2440]
		  "." CRLF
getp-answer =/ "213"	[answertext] CRLF
		  text CRLF
		  "." CRLF
getp-answer =/ "430"	[answertext] CRLF
		  text CRLF
		  "." CRLF
getp-answer =/ "411"	[answertext] CRLF
		  text CRLF
		  "." CRLF
getp-answer =/ "510"	[answertext] CRLF
		  text CRLF
		  "." CRLF

getpdata   =	  "Name:" WSP text CRLF
		  "Status:" WSP	text CRLF
		  "Serial:" WSP	timestamp CRLF
		  *(header ":" WSP text	CRLF)
		  [("Ctl-PGP-Key:" CRLF	PGP-answer /
		    "Mod-PGP-Key:" CRLF	PGP-answer)]

geta-cmd =  "GETA" WSP username WSP password	WSP
	       timestamp WSP name CRLF
geta-answer =  "615"	[answertext] CRLF
		  pgp-ascii-armor-start	; this is according to [RFC2440]
		  *(getadata CRLF)
		  pgp-ascii-armor-end	; this is according to [RFC2440]
		  "." CRLF
geta-answer =/ "215"	[answertext] CRLF
		   text	CRLF
		   "." CRLF
geta-answer =/ "430"	[answertext] CRLF
		  text CRLF
		  "." CRLF
geta-answer =/ "411"	[answertext] CRLF
		  text CRLF
		  "." CRLF
geta-answer =/ "510"	[answertext] CRLF
		  text CRLF
		  "." CRLF

getadata   =	  "Name:" WSP text CRLF
		  "Status:" WSP	text CRLF
		  "Serial:" WSP	timestamp CRLF
		  *(header ":" WSP text	CRLF)
		  [("Ctl-PGP-Key:" CRLF	PGP-answer/
		    "Mod-PGP-Key:" CRLF	PGP-answer)]

K-=Xwgc
PGP-answer =	"V" SP Version CRLF
Version  = text
User-ID  = text
Bits	    = text
Key-ID   = text
Finger   = text
Location = text
Keyblock = text


K-=Xwgc
