NPATTERNS = 224. In the first octet of every compressed header only 
A=STATIC,          A=STATIC,      A=IRREGULAR(1)        A=STATIC, 
B=IRREGULAR(2)   B=READ(LTABLE,3)      B=STATIC           B=STATIC 
    
         ---               ---               ---                 --- 
        | 3%|             | 8%|             | 5%|               |54%| 
        | 4 |             | 3 |             | 2 |               | 1 | 
         ---               ---               ---                 --- 
          | X             / D \               | X               / 0 
          |              /     \              |                / 
          |             /       \             |               / 
         ---         ---         ---         ---             / 
        | 6%|       | 8%|       | 8%|       |10%|           / 
        | 2 |       | 2 |       | 1 |       | 1 |          / 
         ---         ---         ---         ---          / 
          | X         | X         1 \       / 0          / 
          |           |              \     /            / 
          |           |               \   /            / 
         ---         ---               ---            / 
        |12%|       |16%|             |18%|          / 
        | 1 |       | 1 |             | 1 |         / 
         ---         ---               ---         / 
          1 \       / 0               / 0         / 
             \     /                 /           / 
              \   /                 /           / 
               ---                 /           / 
              |28%|               /           / 
              | 1 |              /           / 
               ---              /           / 
                1 \            /           / 
                   \          /           / 
                    \        /           / 
                     \      /           / 
                      \    /           / 
                        ---           / 
                       |46%|         / 
                       | 1 |        / 
                        ---        / 
                         1 \      / 
                            \    / 
                             \  / 
                             ---- 
                            |100%| 
                            | 1  | 
                             ---- 
    
           Figure 3 : An example of a Hierarchical Huffman tree 
    
    
NCODEWORDS=i (i.e. NCODEWORDS is the total number of codewords 
F = Format from row of TABLE(i) 
N = corresponding entry for N from row of TABLE(i) 
P = P(i)*corresponding entry for P from row of TABLE(i) 
F = {Format i1 of TABLE(1), Format i2 of 
                        TABLE(2), ... , Format iNT of TABLE(NT)} 
N = [N(i1) of TABLE(i1)]* ... *[N(iNT) of TABLE(iNT)] 
P = [P(i1) of TABLE(i1)]* ... *[P(iNT) of TABLE(iNT)] 
NPOINTS = sum of all N values for all rows in the table. 
    
P = 0 
N = (NPATTERNS - NPOINTS) mod (2^ALIGN-1) 
