A = 0:  Sequential (e.g. the first block goes to address 1, the
      second block to address 2, etc.)








A = 1:  Staggered (e.g. for every n between 0 and ((65536-R)/(F+D))-1
      , address 1 receives ports n*F+R, address 2 receives ports
      (1+n)*F+R, etc.)

A = 2:  Round robin (e.g. the subscriber receives the same port
      number across a pool of external IP addresses.  If the subscriber
      is to be assigned more ports than there are in the external IP
      pool, the subscriber receives the next highest port across the IP
      pool, and so on.  Thus, if there are 10 IP addresses in a pool and
      a subscriber is assigned 1000 ports, the subscriber would receive
      a range such as ports 2000-2099 across all 10 external IP
      addresses).

A = 3:  Interlaced horizontally (e.g. each address receives every Cth
      port spread across a pool of external IP addresses).

A = 4:  Cryptographically random port assignment (Section 2.2 of
      [RFC6431]).  If this algorithm is used, the Service Provider needs
      to retain the keying material and specific cryptographic function
      to support reversibility.

