A = 0, allocate a buffer of default size (as decided by the
A = 1, allocate a buffer of size defined in the Buffer Size
B = 0, do not buffer data.
B = 1, start to buffer data.

D = 0, do not stop buffering or delete MN's buffer.
D = 1, stop, deliver all packets buffered so far to the MN
F = 0, do not forward the data.
F = 1, forward the data.

I = 0, Identification field is not included.
I = 1, Identification field is included.

K = 0, FA should not send any acknowledgement message.
K = 1, FA should send an acknowledgement message.
L = 0, a fixed length buffer.
L = 1, a variable length buffer.

A = 0, FA accepts the buffer specifications.
A = 1, FA partially accepts the buffer specifications. New
                    specifications are sent with the appropriate
                    extensions.
A = 2, FA rejects the buffer specifications.

C = 0, buffer or forward packets that have the same
                     IP addresses as listed in this extension.
C = 1, buffer or forward packets that do not have the same
                     IP addresses as listed in this extension.

