n=1 is preceding frame n=2. Within one payload all frames between the
k=0;
max = max(F(0),..,F(N-1));
S = 8 - k%8;
k=0;
S = 8 - k%8;
m=audio 49120 RTP/AVP 97
a=rtpmap:97 AMR/8000
a=fmtp:97 mode-set=0,2,5,7; maxframes=1


