scs-cookie        = scs-cookie-name "=" scs-cookie-value
scs-cookie-name   = token
scs-cookie-value  = eDATA "|" eATIME "|" eTID "|" eIV "|" eAUTHTAG
eDATA             = 1*base64url-character
eATIME            = 1*base64url-character
eTID              = 1*base64url-character
eIV               = 1*base64url-character
eAUTHTAG          = 1*base64url-character

                                 Figure 1

AUTHTAG = HMAC(base64url(DATA)  "|"
                  base64url(ATIME) "|"
                  base64url(TID)   "|"
                  base64url(IV))

scs-cookie-value = e(DATA)||e(ATIME)||e(TID)||e(IV)||e(tag)

Expires=...; Path=...; Domain=...;

validity_period="start_time, duration") that can be verified by
