rap-service     = "unsigned short" service-name "(" parameters ");"
service-name        = <upper and lower case alpha and numeric>
parameters      = parameter [ ";" parameter ]
parameter       = [ "const" ] param-data-type parameter-name
                      [ "[" size "]" ]
param-data-type = <from parameter descriptor tables below>
parameter-name      = <upper and lower case alpha and numeric>
size                = <string of ASCII 0-9>
rap-struct      = "struct" struct-name "{" members "}"
members         = member [  ";" member ]
member          = member-data-type member-name [ "[" size "]" ]
member-data-type    = <from data descriptor tables below>
OWF = Ex(swab(P14), N8)

