Identity = "Identity" HCOLON signed-identity-digest
signed-identity-digest = LDQUOT 32LHEX RDQUOT

Identity-Info = "Identity-Info" HCOLON ident-info
Ident-info = LAQUOT absoluteURI RAQUOT

digest-string = addr-spec HCOLON callid HCOLON SIP-Date
                HCOLON addr-spec HCOLON message-body

