SPE = 2,396.160 Mbit/s and STS-192c SPE = 9,584.640 Mbit/s.

        Table 1. SONET Virtual Concatenation

      Bit rate     Without            With
     --------------------------------------------

      100Mbit/s   STS-3c (67%)  STS-1-2v (100%)
      200Mbit/s   STS-12c(33%)  STS-1-4v (100%)
      1Gbit/s     STS-48c(42%)  STS-3c-7v (95%)


