base64          = *(4base64-char)

base64-char     = ALPHA / DIGIT / "+" / "/"
                    ; Case-sensitive

   The following modifications are made to the Formal Syntax in [IMAP]:

changekey       = "CHANGEKEY" SP mailbox

resp-text-code  =/ "MAILBOXKEY" SP base64

url             = astring
                   ; contains imapurl as defined below

urlfetch        = "FETCH" SP 1*url

urlfetch-data   = "*" SP "URLFETCH" 1*(url nstring)

   The following modifications are made to the Formal Syntax in [IMAPURL]:

enc-urlauth     = base64
                    ; BASE64 as described in [MIME-IMB]

imapurl         = "imap://" iserver "/" [icommand] [iurlauth]

iexpire         = ";EXPIRE=" date-time
                    ; date-time defined in [DATETIME]

iurlauth        = ";URLAUTH=" enc-urlauth


