Remote-Party-ID    = "Remote-Party-ID" ":" [display-name]
                                "<" addr-spec ">" *(";" rpi-token)

rpi-token          = rpi-id | rpi-type | rpi-auth |
                                                other-rpi-token

rpi-id             = "rpi-id" "=" ("private" | "unavailable"
                                                                | "na")

rpi-type           = "rpi-type" "=" ("operator" | token)

rpi-auth           = "auth" "=" auth-scheme #auth-param
auth-scheme        = token
auth-param         = token "=" (token | quoted-string)

other-rpi-token    = token ["=" (token | quoted-string)]

other-param        = (token | (token "=" (token | quoted-string)))
                          | "private"

auth=pgp signature="abc", signed-by="PA";
auth=pgp signature="xyz", signed-by="PB"

rpi-auth        = "auth" "=" auth-scheme #auth-param
auth-scheme     = "pgp"
auth-param      = pgp-response

Anonymity       = "Anonymity" ":"  *privacy-tag
privacy-tag     = "Full" | "URI" | "Name" | "IPAddr" | "Off"

OSPS            = "OSPS" ":" OSPS-Tag
OSPS-Tag        = "BLV" | "EI" | token

