mailrealm-name = 1*TEXT-UTF8-CHAR

mailream-imapservers = 1*CHAR *(NUL 1*CHAR)
mailrealm-smtpservers = 1*CHAR *(NUL 1*CHAR)
mailrealm-ldapservers = 1*CHAR *(NUL 1*CHAR)
mailbox-name = 1*TEXT-UTF8-CHAR

mailbox-imapname = 1*CHAR

mailbox-expand-url = URL
                       ;; as defined in [IMAP-URL]

mailbox-expand-server = 1*CHAR

mailbox-servers = *(NUL 1*CHAR)

mailbox-subscribed = number

mailbox-state = number

mailbox-post = url

mailbox-archive = time

mailbox-createtime = time

mailbox-quota = *(quota_resource)
                    ;; multi-valued
quota_resource = atom SP number SP number

mailbox-acl = *(acl_data)
acl_data = identifier SP acl_rights
acl_rights = string
