xxDw==)

signature = sign(SIG_RDATA | RR(1) | RR(2)... ) where

            "|" denotes append

            SIG_RDATA is the wire format of the SIG RDATA fields with
               the Signer's Name field in cannonical form.
               the Signature field excluded.

            RR(i) = fqdn | class | type | TTL | RDATA length | RDATA

               fqdn is the Fully Qualified Domain Name in canonical
               form.

               All RR(i) MUST have the same fqdn as the SIG RR.

               All RR(i) MUST have the same class as the SIG RR.

               All RR(i) MUST have the RR type listed in SIG RR's
               Type Covered field.

               All RR(i) MUST have the TTL listed in the SIG Original
               TTL Field

               All names in the RDATA field are in canonical form

               The set of all RR(i) is sorted into cannonical order.


rJFXXDsybfEDdwoajAY= )

digest = digest_algorithm( cannonical FQDN of KEY RR | KEY_RR_rdata)

            "|" denotes append

KEY_RR_rdata = Flags | Protocol | Algorithm | Public Key


