mdn-request-header = "Disposition-Notification-To" ":" 
                 mailbox *("," mailbox) 

Disposition-Notification-Options = 
                 "Disposition-Notification-Options" ":"  
                                disposition-notification-parameters 

disposition-notification-parameters = parameter *(";" parameter)

parameter = attribute "=" importance "," value *("," value) 

importance = "required" / "optional" 
original-recipient-header =    
                 "Original-Recipient" ":" address-type ";" generic-address 

disposition-notification-content = [ reporting-ua-field CRLF ] 
          [ mdn-gateway-field CRLF ] 
          [ original-recipient-field CRLF ] 
          final-recipient-field CRLF 
          [ original-message-id-field CRLF ] 
          disposition-field CRLF 
          *( failure-field CRLF ) 
          *( error-field CRLF ) 
          *( warning-field CRLF ) 
          *( extension-field CRLF ) 

address-type = atom 

mta-name-type = atom 

reporting-ua-field = "Reporting-UA" ":" ua-name 
                 [ ";" ua-product ] 


ua-name = *text 

ua-product = *text 

mta-name = *text 

original-recipient-field =   
                 "Original-Recipient" ":" address-type ";"  
                 generic-address 

generic-address = *text 

final-recipient-field =  
                 "Final-Recipient" ":" address-type ";" generic-address 

original-message-id-field =  
          "Original-Message-ID" ":" msg-id 

disposition-field =  
                 "Disposition" ":" disposition-mode ";"    
                 disposition-type    
                 [ "/" disposition-modifier 
                 *( "," disposition-modifier ) ] 

disposition-mode = action-mode "/" sending-mode 

action-mode = "manual-action" / "automatic-action" 

sending-mode = "MDN-sent-manually" / "MDN-sent-automatically" 

disposition-type = "displayed"  
                  / "deleted" 

disposition-modifier = "error" 
                 / disposition-modifier-extension 

disposition-modifier-extension = atom 

failure-field = "Failure" ":" *text 

error-field = "Error" ":" *text 

warning-field = "Warning" ":" *text 

mdn-request-header =  
          "Disposition-Notification-To" ":" 
                 mailbox *("," mailbox) 

Disposition-Notification-Options =  
                 "Disposition-Notification-Options" ":" 
                 disposition-notification-parameters 

disposition-notification-parameters =  
                 parameter *(";" parameter) 

parameter = attribute "=" importance "," value *("," value) 

importance = "required" / "optional" 

original-recipient-header =  
                 "Original-Recipient" ":" address-type ";" generic-address 

disposition-notification-content =  
                 [ reporting-ua-field CRLF ]  
                 [ mdn-gateway-field CRLF ]  
                 [ original-recipient-field CRLF ]  
                 final-recipient-field CRLF  
                 [ original-message-id-field CRLF ]  
                 disposition-field CRLF  
                 *( failure-field CRLF )  
                 *( error-field CRLF )  
                 *( warning-field CRLF )  
                 *( extension-field CRLF ) 

address-type = atom 

mta-name-type = atom 

reporting-ua-field = "Reporting-UA" ":" ua-name [ ";" ua-product ] 

ua-name = *text 

ua-product = *text 

mdn-gateway-field = "MDN-Gateway" ":" mta-name-type ";" mta-name 

mta-name = *text 
generic-address = *text 

final-recipient-field =  
                 "Final-Recipient" ":" address-type ";" generic-address 

disposition-field =  
                 "Disposition" ":" disposition-mode ";"  
                 disposition-type  
                 [ "/" disposition-modifier    
                 *( "," disposition-modifier ) ] 

disposition-mode = action-mode "/" sending-mode 

action-mode = "manual-action" / "automatic-action" 

sending-mode = "MDN-sent-manually" / "MDN-sent-automatically" 

disposition-type = "displayed"    
                 / "deleted" 

disposition-modifier =  "error" / disposition-modifier-extension 

disposition-modifier-extension = atom 

original-message-id-field = "Original-Message-ID" ":" msg-id 

failure-field = "Failure" ":" *text 

error-field = "Error" ":" *text 

warning-field = "Warning" ":" *text 

extension-field = extension-field-name ":" *text 

extension-field-name = atom 
boundary="RAA14128.773615765/example.com" 
      
