xmlns="urn:ietf:params:xml:ns:EmergencyCallData:control"
xmlns="urn:ietf:params:xml:ns:EmergencyCallData:control">

xmlns="urn:ietf:params:xml:ns:EmergencyCallData:control">

purpose=emergencyCallData.eCall.MSD
purpose=emergencyCallData.control
xmlns="urn:ietf:params:xml:ns:EmergencyCallData:control">

purpose=emergencyCallData.control
xmlns="urn:ietf:params:xml:ns:EmergencyCallData:control">

purpose=emergencyCallData.eCall.MSD
targetNamespace="urn:ietf:params:xml:ns:EmergencyCallData:control"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

        <xs:import namespace="http://www.w3.org/XML/1998/namespace"/>

        <xs:element name="EmergencyCallData.control"
type="pi:controlType"/>

type="pi:capabilitiesType"/>
minOccurs="0"
maxOccurs="unbounded"/>
maxOccurs="unbounded">
type="xs:token"
use="required"/>
type="xs:boolean"
use="required"/>
type="xs:token">
type="xs:string"/>
processContents="skip"/>
minOccurs="0"
maxOccurs="unbounded"/>
type="xs:anyURI"
use="required"/>
type="xs:boolean"/>
type="pi:requestType"
minOccurs="1"
maxOccurs="unbounded"/>
minOccurs="0"
maxOccurs="unbounded"/>
minOccurs="0"
maxOccurs="unbounded"/>
use="required"/>
type="xs:duration"/>
type="xs:string"/>
type="xs:token"/>
content="text/html;charset=iso-8859-1"/>
