start = acme-record / bundle / tstr

acme-record = {
     id-chal,
     token-bundle,
     ? key-auth-digest ; present for Response Bundles
id-chal = (1 => bstr)
token-bundle = (2 => bstr)
key-auth-digest = (3 => bstr)

