FillOrder = 1, 2.  SHORT.
         TIFF Class F readers must be able to read data in both bit
         orders, but the vast majority of facsimile products store data
         LSB first, exactly as it appears on the telephone line.
                 1 = Most Significant Bit first.
                 2 = Least Significant Bit first.
     
ImageWidth = 1728, 2048, 2482, 2592, 3072, 3723, 3456, 4096, 4964.
         SHORT or LONG.  These are the fixed page widths in pixels
         defined in CCITT Group 3.
         
NewSubFileType = 2.  LONG.
         The value 2 identifies a single page of a multi-page image.
     
ResolutionUnit = 2,3.  SHORT.
         The units of measure for resolution:
             2 = Inch
             3 = Centimeter
     
XResolution = 204, 200, 300, 400, 406 (inches). RATIONAL.
         The horizontal resolution of the image expressed in pixels per
         resolution unit.  Some existing TIFF-F implementations may also
         support values of 77 (cm).
     
YResolution = 98, 196, 100, 200, 300, 392, 400  (inches). RATIONAL.
         The vertical resolution of the image expressed in pixels per
         resolution unit. Some existing TIFF-F implementations may also
         support values of 77, 38.5 (cm).
     
Compression = 3,4.  SHORT.
         This is a required Class F tag.  Modified Huffman, one-
         dimensional encoding with "byte-aligned" EOLs is selected by
         setting 3.  An EOL is said to be byte-aligned when Fill bits
         have been added as  necessary before EOL codes such that EOL
         always ends on a byte  boundary, thus ensuring an EOL-sequence
         of a 1 byte preceded  by a zero nibble: xxxx0000 00000001.  The
         data in a Class F image is not terminated with an RTC (see
         sections 3.8.4 and 3.8.5).  For two-dimensional encoding, set
         the value of the compression tag to 4 (see section 3.8.2).
         
T4Options = 4,5.  LONG.
         This tag is required for TIFF Class-F if the one-dimensional
         compression method has been specified (i.e. by setting the
         value of the Compression tag to 3).  Data is one-dimensional
         and EOLs must be byte-aligned. Uncompressed data is not
         allowed.
                bit 0 = 0 for 1-Dimensional
                bit 1 = must be 0 (uncompressed data not allowed)
                bit 2 = 1 for byte-aligned EOLs
         
T6Options = 0  LONG.
         This tag is required for TIFF Class F if the two-dimensional
         compression method is specified (i.e. by setting the value of
         the Compression tag to 4).  Data is two-dimensional and there
         is no use of EOLs. Uncompressed data is not allowed. In earlier
         versions of TIFF, this tag was named Group4Options. The
         significance has not changed and the present definition is
         compatible.  This field is made up of a set of 32 flag bits.
         Unused bits must be set to 0. Bit 0 is the low-order bit. The
         default value is 0 (all bits 0).
                bit 0 = 0 for 2-Dimensional
                bit 1 = must be 0 (uncompressed data not allowed)
         
BitsPerSample = 1.  SHORT.
         Since facsimile is a black-and-white medium, this must be 1
         (the default) for all files.
        
PhotometricInterp = 0,1.  SHORT.
         This tag allows notation of an inverted ("negative") image:
                 0 = normal
                 1 = inverted
     
SamplesPerPixel = 1.  SHORT.
         The value of 1 denotes a bi-level, grayscale, or palette color
         image.
         
Tag  = 326  (146 hex)
Type = SHORT or LONG
        
Tag = 327 (147 hex)
Type = SHORT
N = 0
             0 = Data contains no lines with incorrect pixel counts or
                regenerated lines  (i.e., computer generated)
             1 = Lines with an incorrect pixel count were regenerated by
                receiving device
             2 = Lines with an incorrect pixel count existed, but were
                not regenerated by receiving device
         
Tag  = 328 (148 hex)
Type =  LONG or SHORT
         
CleanFaxData = 0, 1, 2.  BYTE.
         This tag indicates whether lines with incorrect pixel count are
         actually in the data or if the receiving facsimile device
         replaced them with regenerated lines.
              0 = Data contains no lines with incorrect pixel counts or
                  regenerated lines (i.e., computer generated)
              1 = Lines with an incorrect pixel count were regenerated
                  by receiving device
              2 = Lines with an incorrect pixel count existed, but were
                  not regenerated by receiving device
              
     ConsecutiveBadFaxLines.  LONG or SHORT.
         The maximum number of consecutive scan lines with incorrect
         pixel count encountered by the facsimile device reception.
         
     DateTime.  ASCII.
         Date and time in the format YYYY:MM:DD HH:MM:SS, in 24-hour
         format. String length including NUL byte is 20 bytes. Space
         between DD and HH.
         
     DocumentName.  ASCII.
         This is the name of the document from which the document was
         scanned.
         
     ImageDescription.  ASCII.
         This is an ASCII string describing the contents of the image.
         
     Orientation.  SHORT.
         This tag might be useful for displayers that always want to
         show the same orientation, regardless of the image.  The
         default value of 1 is "0th row is visual top of image, and 0th
         column is the visual left."  An 180-degree rotation is 3.  See
         [TIFF] for an explanation of other values.
     
