I_message = HDR, T, RAND, [IDi], 
               {SP}, DHi, KEMAC 
                           I_message 
                    ----------------------->   R_message = HDR, T, 
                                                [IDr], IDi, DHr, DHi, 
                                                 KEMAC 
                             R_message 
                    <---------------------- 
 
TGK = g**(xi * yi)                        TGK = g**(xi * yi) 
 
 
     Figure 1: HMAC-authenticated Diffie-Hellman key based exchange, 
            where xi and xr are randomly chosen respectively 
                  by the initiator and the responder. 
 
 
     The DHHMAC key exchange SHALL be done according to Figure 1. The 
     initiator chooses a random value xi, and sends an HMACed message 
     including g**xi and a timestamp to the responder (optionally also 
     including its identity). 
   
     The group parameters (e.g., the group G) are a set of parameters 
     chosen by the initiator.  The responder chooses a random positive 
     integer xr, and sends an HMACed message including g**xr and the 
     timestamp to the initiator (optionally also providing its 
     identity). 
   
     Both parties then calculate the TGK, g**(xi * xr). 
   
     The HMAC authentication is due to provide authentication of the DH 
     half-keys, and is necessary to avoid man-in-the-middle attacks. 
   
   
     This approach is less expensive than digitally signed Diffie-
     Hellman.  It requires first of all, that both sides compute one 
     exponentiation and one HMAC, then one HMAC verification and 
     finally another Diffie-Hellman exponentiation. 
      
     With off-line pre-computation, the initial Diffie-Hellman half-key 
     MAY be computed before the key management transaction and thereby 
     MAY further reduce the overall round trip delay as well as reduce 
     the risk of denial-of-service attacks. 
   
     Processing of the TGK SHALL be accomplished as described in MIKEY 
     [1] chapter 4. 
   
     The computed HMAC result SHALL be conveyed in the KEMAC payload 
     field where the MAC fields holds the HMAC result.  The HMAC shall 
     be computed over the entire message using auth_key, see also 
     section 4.2. 
 
             HMAC-authenticated Diffie-Hellman for MIKEY January 2003 

      
      
      
      
 
I_message = HDR, T, [IDi], 
               {SP}, [DHi], KEMAC 
                           I_message 
                    ----------------------->   R_message = HDR, T, 
                                                [IDr], IDi, [DHr, DHi], 
                                                 KEMAC 
                             R_message 
                    <---------------------- 
 
