attr=<attribute id>
cond=alarm_condition
cause=alarm_cause
mh=model_handle
rel=relation
lmh=left_model_handle
rmh=right_model_handle.
type=event_type
text=event_text
lh=landscape_handle ]
mth=model_type_handle
val=value ...]
lh=landscape_handle ]
aid=alarm_id
rel=relation
lmh=left_model_handle
rmh=right_model_handle.
mh=model_handle
val=value
lh=landscape_handle ]
mth=model_type_handle
lh=landscape_handle ]
mth=model_type_handle
attr=attribute_id
mth=model_type_handle
attr=attribute_id,val=value
attribute=<..>,
value=..

attribute=<..>,
value=..


attribute=<user name>,
value=user name
attribute=<user name>,
value=user name
attribute=<user password>,
value=password
attribute=<user password>,
value=password


attribute=<user name>,
value=user name
attribute=<user name>,
value=user name
attribute=<user password>,
value=password
attribute=<user password>,
value=password


attribute=<..>,
value=..
attribute=<..>,
value=..



attribute=<..>,
value=..
attribute=<..>,
value=..
attribute=<..>,
value=..
attribute=<..>,
value=..


