targetNamespace="urn:ietf:params:xml:ns:pidf:geopriv10:domain-auth"
xmlns="urn:ietf:params:xml:ns:pidf:geopriv10:domain-auth"
elementFormDefault="unqualified"
attributeFormDefault="unqualified">

minOccurs="0" maxOccurs="unbounded"/>
type="xsd:dateTime">
Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116"
entity="pres:user@example.com">
Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
             <dsig:SignatureMethod
Algorithm="http://www.w3.org/2000/09/xmldsig#dsa-sha1"/>
             <dsig:Reference URI="">
               <dsig:Transforms>
                 <dsig:Transform
Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                 <dsig:Transform
Algorithm="urn:ietf:params:xml:ns:pidf:geopriv10:domain-auth#PIDF-LO"
     />
               </dsig:Transforms>
               <dsig:DigestMethod
Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
               <dsig:DigestValue>
                 60NvZvtdTB+7UnlLp/H24p7h4bs=
               </dsig:DigestValue>
             </dsig:Reference>
           </dsig:SignedInfo>
           <dsig:SignatureValue>
             juS5RhJ884qoFR8flVXd/rbrSDVGn40CapgB7qeQiT+rr0NekEQ6BHhUA8
             dT3+BCTBUQI0dBjlml9lwzENXvS83zRECjzXbMRTUtVZiPZG2pqKPnL2YU
             3A9645UCjTXU+jgFumv7k78hieAGDzNci+PQ9KRmm//icT7JaYztgt4=
           </dsig:SignatureValue>
           <dsig:KeyInfo>
             <dsig:RetrievalMethod
URI="https://example.com/signature/pidfsigner.crt"
Type="http://www.w3.org/2000/09/xmldsig#X509Data"/>
entity="pres:user@example.com">
