userid=23 , id=34     ----|             |--- label='10'
userid=23 , id=35     ----|             |--- label='11'
userid=23 , id=36     ----|             |--- label='12'
userid=24 , id=24     ----|             |
userid=24 , id=35     ----|             |
                              |-------------|


v=0
c=IN IP4 131.164.74.2
t=0 0
m=audio 30000 RTP/AVP 0
a=label:10


v=0
c=IN IP4 131.164.74.2
t=0 0
m=audio 30000 RTP/AVP 0
a=label:10

v=0
c=IN IP4 131.164.74.2
t=0 0
m=video 30002 RTP/AVP 31
a=label:11


v=0
c=IN IP4 131.164.74.2
t=0 0
m=video 30002 RTP/AVP 31
a=label:11


