version=<Z(x*256+y)>, indicates the version of the 3GPP TS 
spldesc=<value1,value2,...> indicates the way the server sends 
tx3g=<base64-value-1>,<base64-value-2>,...This parameter MUST be 
width=<integer-value> indicates the width in pixels of the text 
height=<integer-value> indicates the height in pixels of the 
tx=<integer-value>, indicates the horizontal translation offset 
ty=<integer-value>, indicates the vertical translation offset in 
layer=<integer-value>, indicates the proximity of the text track 
brand=<brand-name>, where <brand-name> indicates the "best use" 
cbrand=<brand-name-1>,<brand-name-2>,...indicates the list of 
mver=<version-value>, "Minor version" where <version-value> is a 
m=video <portnumber> RTP/<RTP profile> <dynamic payload type> 
    
a=rtpmap:<payload type> 3gpp-tt/<rate> 
    
parameter= <value1,value2,value3>, for "tx3g" and "spldesc".  The 
a=fmtp:<dynamic payload type> <parameter name>=<value>[ 
parameter=<value> pairs.  Details on the versioning are found in 
SIDX=6, then the active interval is now different: [0,6] plus 
     
    
    
