interval = e.g. 2 * RTT
threshold = e.g. 1/2 * buffer size
timeout_expiry = now(), with now() returning the current time

timeout_expiry = now() + interval
tau = a preset parameter controlling the adaptation speed;
                e.g. 500 milliseconds or 5 * initial_interval
cumTime = 0; the cumulative time above/below threshold
state = CLEAR; the recent overflow state of the queue

state = OVERFLOW
state = DRAIN
state = CLEAR

cumTime = max(cumTime, 0)
cumTime = min(cumTime, some sanity limit
                            of several minutes)
interval = initial_interval/(1+cumTime/tau)

timeout_expiry = now() + interval
queue_delay = now() - p.time



timeout_expiry = now() + interval
