s-expr      = "(" tag *s-part ")"

tag         = octet-string

s-part      = octet-string / s-expr / star-form

octet-string = decimal ":" 1*octet ; The number of octets should
decimal     = nzdigit *digit

nzdigit     = "1" / "2" / "3" / "4" / "5" / "6" / "7" / "8" / "9"

digit       = "0" / nzdigit

octet       = %x00-FF

star-form   = "(1:*" [ set / range / prefix / suffix ] ")"

x = (http (page index.html)(action GET)(user olav))

y = (http (page index.html)(action GET)(user))

z = (http (page index.html)(action)(user olav))

set = "3:set" 1*s-expr

rangespec      = alpha / numeric / date / time / ipv4 / ipv6

alpha          = "5:alpha" [lole utf8string [goge utf8string]] /
numeric        = "7:numeric" [ lole number [ goge number ]] / [
date           = "4:date" [ goge dat [ lole dat ]] / [ lole dat [
time           = "4:time" [ lole hms [ goge hms ]] / [ goge hms [
ipv4           = "4:ipv4" [ lole ipnum [ goge ipnum ]] / [ goge
ipv6           = "4:ipv6" [ lole ip6num [ goge ip6num ]] / [ goge
lole           = "2:lt" / "2:le"

goge           = "2:gt" / "2:ge"

number         = decimal ":" 1*digit

dat            = decimal ":" date-time   ; date format as
date-fullyear  = 4DIGIT

date-month     = 2DIGIT  ; 01-12

date-mday      = 2DIGIT  ; 01-28, 01-29, 01-30, 01-31 dependent on
time-hour      = 2DIGIT  ; 00-23

time-minute    = 2DIGIT  ; 00-59

time-second    = 2DIGIT  ; 00-58, 00-59, 00-60 based on leap
time-secfrac   = "." 1*DIGIT

time-numoffset = ("+" / "-") time-hour ":" time-minute

time-offset    = "Z" / time-numoffset

partial-time   = time-hour ":" time-minute ":" time-second

full-date      = date-fullyear "-" date-month "-" date-mday

full-time      = partial-time time-offset

date-time      = full-date "T" full-time

hms            = decimal ":" partial-time
ipnum          = decimal ":" 1*3digit "." 1*3digit "." 1*3digit
ip6num         = IPv6address ; as defined in [RFC2373]

utf8string     = decimal ":" 1*UTF8

UTF8           = %x01-09 / %x0B-0C / %x0E-7F / UTF8-2 / UTF8-3 /
UTF8-1         = %x80-BF

UTF8-2         = %xC0-DF UTF8-1

UTF8-3         = %xE0-EF 2UTF8-1

UTF8-4         = %xF0-F7 3UTF8-1

UTF8-5         = %xF8-FB 4UTF8-1

UTF8-6         = %xFC-FD 5UTF8-1

prefix = "6:prefix" utf8string

suffix = "6:suffix" utf8string

s-expr         = "(" tag *s-part ")"

tag            = octet-string

s-part         = octet-string / s-expr / star-form

octet-string   = decimal ":" 1*octet ; The number of octets must
decimal        = nzdigit *digit

nzdigit        = "1" / "2" / "3" / "4" / "5" / "6" / "7" / "8" /
digit          = "0" / nzdigit

octet          = %x00-FF

star-form      = "(1:*" [ set / range / prefix / suffix ] ")"

set            = "3:set" 1*s-expr

range          = "5:range" rangespec

rangespec      = alpha / numeric / date / time / ipv4 / ipv6

alpha          = "5:alpha" [lole utf8string [goge utf8string]] /
numeric        = "7:numeric" [ lole number [ goge number ]] / [
date           = "4:date" [ goge dat [ lole dat ]] / [ lole dat [
time           = "4:time" [ lole hms [ goge hms ]] / [ goge hms [
ipv4           = "4:ipv4" [ lole ipnum [ goge ipnum ]] / [ goge
ipv6           = "4:ipv6" [ lole ip6num [ goge ip6num ]] / [ goge
lole           = "2:lt" / "2:le"

goge           = "2:gt" / "2:ge"

number         = decimal ":" 1*digit

dat            = decimal ":" date-time ; date-time format as
hms            = decimal ":" partial-time  ; partial-time as
ipnum          = decimal ":" 1*3digit "." 1*3digit "." 1*3digit
ip6num         = IPv6address ; as defined in [RFC2373]

utf8string     = decimal ":" 1*UTF8

UTF8           = %x01-09 / %x0B-0C / %x0E-7F / UTF8-2 / UTF8-3 /
UTF8-1         = %x80-BF

UTF8-2         = %xC0-DF UTF8-1

UTF8-3         = %xE0-EF 2UTF8-1

UTF8-4         = %xF0-F7 3UTF8-1

UTF8-5         = %xF8-FB 4UTF8-1

UTF8-6         = %xFC-FD 5UTF8-1

prefix         = "6:prefix" utf8string

suffix         = "6:suffix" utf8string

typespecific   = *UTF8
