schemaLocation="TBD"
version="1.0">
transactionID="12345.1">1111</SwarmID>
concurrentLinks="HIGH"
onlineTime="NORMAL"
uploadBWlevel="NORMAL">5</PeerNum>
priority="1" />
priority="2"
type="HOST"
connection="ADSL" />
schemaLocation="TBD"
version="1.0">
priority="1"
type="REFLEXIVE"
connection="3G"
asn="64496" />
asn="64496" />
asn="64496" />
schemaLocation="TBD"
version="1.0">
schemaLocation="TBD"
version="1.0">
schemaLocation="TBD"
version="1.0">
concurrentLinks="HIGH"
onlineTime="NORMAL"
uploadBWlevel="NORMAL">5</PeerNum>
schemaLocation="TBD"
version="1.0">
asn="64496" />
asn="64496" />
schemaLocation="TBD"
version="1.0">
priority="1"
type="REFLEXIVE"
connection="3G"
asn="64496" />
asn="64496" />
asn="64496" />
schemaLocation="TBD"
version="1.0">
 




chunkmapSize="25">
chunkmapSize="15">
chunkmapSize="5">
chunkmapSize="5">
chunkmapSize="5">
schemaLocation="TBD"
version="1.0">
