xmlns="urn:ietf:params:xml:ns:yang:ietf-segment-routing">
xmlns="urn:ietf:params:xml:ns:yang:ietf-segment-routing-mpls">
xmlns="urn:ietf:params:xml:ns:yang:ietf-segment-routing">
xmlns="urn:ietf:params:xml:ns:yang:ietf-segment-routing-mpls">
