n= Human readable notes regarding the record (quoted-printable with
      semicolon encoded in addition to the standard characters;
      OPTIONAL, default is no notes).

o= Outbound signing policy for the entity (plain-text; OPTIONAL,
      default is "~").  Possible values are as follows:

      ~  The entity signs some but not all email.

      -  All mail from the entity is signed; unsigned email MUST NOT be
         accepted, but email signed with a Verifier Acceptable Third
         Party Signature SHOULD be accepted.

      !  All mail from the entity is signed; Third-Party signatures
         SHOULD NOT be accepted

      .  This entity never sends email.  The "." policy can be used to
         "short circuit" searches from subdomains; for example, the
         "ad.jp" domain might use this.  If an initial policy search
         receives this policy then the email SHOULD NOT be accepted; if
         found while searching parent domains then the search should
         terminate as though no policy record was found.

      ^  Repeat query at user level.  This value MUST NOT be used in
         user-level policy records.  A Verifier MUST look up the
         selector for "<user>._policy" where <user> is the local-part of
         the Originator Address (i.e., the portion of the address before
         the "@" character).
r= Email address for reports and inquiries regarding the signing
      policy for this entity (plain-text; OPTIONAL, default is no
      contact address available).

t= A vertical-bar separated list of flags (plain-text; OPTIONAL,
      default is that no flags are set).  Flag values are:

      y  The entity is testing signing policy, and the verifier SHOULD
         NOT consider a message suspicious based on the record.

u= Reserved for future reference to a URI to provide more detailed
      policy information.


