packet = makeSNMPpacket(K[VPN Instance or FECinVPN], 
                       FlagTriggerDominoEffect);

SNMPpacket = CP-ReceivePacket(dPE); // from dPE
Label = ExtractLabel(SNMPpacket); // extract LI label
FlagTriggerDominoEffect = ExtractFlags(SNMPpacket);
packet = DP-ReceivePacket(Interface);
