DF=1 in the outer IPv4 header of other SEAL packets once the path has
Segment=0) in their SEAL headers.  When the ITE receives a potential
S-MSS = MIN(S-MSS/2, 128) .  This limited halving procedure accounts
DF=0/1 is based on the subnetwork trust basis for receiving ICMP PTB
