client-final-message-without-proof =
                        channel-binding "," nonce [","
                        extensions]

otp                                = "o=" saslname
client-final-message-without-proof =
                        channel-binding "," nonce "," otp
                        ["," extensions]

server-error-value-ext = "replayed-otp" /
                     "invalid-otp" /
                     value

