ReqMAC = MAC<CapKey>(Req, Nonceln)

STRIPE_SPARSE = 1,
STRIPE_DENSE = 2
stripe_width = stripe_unit * N; where N = |dev_list|
dev_offset = floor(file_offset / stripe_width) * stripe_unit +
                  file_offset % stripe_unit

dev_idx = floor(file_offset / stripe_unit) mod N


LAYOUT_NFSV4_FILES = 1
LAYOUTIOMODE_READ          = 1,
LAYOUTIOMODE_RW            = 2,
LAYOUTIOMODE_ANY           = 3,
RECALL_FILE = 1,
RECALL_FSID = 2
