HASH_x = prf (SSK,CM_b) where CM is a control message body
                           such as Binding Update (BU) or
                           Binding Acknowledgement (BA).

DIGSIG_i = < N_i | PBk_i | Iid > PrivateKey_i


Iid = HASH (IIP | RIP | Pubkey_i)


SSK = prf (g^(PRk_r X PBk_i), N_i | N_r)

HASH_r = prf (N_i | N_r, g^PBk_i | g^PBk_r | PublicKey_i
                | PublicKey_r | DIGSIG_r | SPI | HASH_type)

DIGSIG_r = < N_r | PBk_r | Rid > PrivateKey_r

Rid = HASH (IIP | RIP | PublicKey_i )

SSK = prf (g^(PRk_i X PBk_r), N_i | N_r)

DIGSIG_i = < N_i | Iid > PrivateKey_i

Iid = HASH (IIP | RIP | Pubkey_i)

SSK = prf (HASH (N_i | N_r | RAND_r),
               IIP | RIP | PublicKey_i | PublicKey_r)

HASH_r = prf (SSK, PublicKey_i | PublicKey_r | DIGSIG_r
                  | SPI | HASH_type | [FQDN_r])

DIGSIG_r = < < RAND_r > PublicKey_i | N_r | Rid > PrivateKey_r
Rid = HASH (IIP | RIP | PublicKey_r)

SSK = prf (N_i | N_r,MNIP | CNIP | PublicKey_i | PublicKey_r)


HASH_i = prf(SSK, g^PBk_i | PublicKey_i | DIGSIG_i | SPI
               | HASH_type |[ FQDN_i ])

HASH_r = prf(SSK, g^PBk_i | g^PBk_r | PublicKey_i |
               PublicKey_r | DIGSIG_r | SPI | HASH_type
               | [ FQDN_r ])


HASH_i = prf(SSK, PublicKey_i | DIGSIG_i | SPI
               | HASH_type | [ FQDN_i ])

HASH_r = prf(SSK,PublicKey_i | PublicKey_r | DIGSIG_r
               | SPI | HASH_type | [ FQDN_r ])


