Property = space [domain] * (space ";" parameter) space

domain = label *("." label)
label = 1* (ALPHA / DIGIT / "_" / "-" )

space = *(SP / HTAB)

parameter =  / space tag "=" value

tag = 1* (ALPHA / DIGIT)

value = *VCHAR | DQUOTE *(%x20-21 / %x23-7E) DQUOTE


