template-type=wpad
template-version=0.0

template-description=
    This is an abstract service type for WPAD configuration URLs.

template-url-syntax=
url-path= ; an URL for the configuration data, as defined in [4].

config-method= string M X
access-protocol= string
