cookie-av           = expires-av / max-age-av / domain-av /
                         path-av / secure-av / httponly-av /
                         first-party-only-av / extension-av
first-party-only-av = "First-Party-Only"
