waitTime = addHoldDownTime
                + 3 * (DNSKEY RRSIG Signature Validity) / 2
                + 2 * MAX(TTL of all records)

waitTime = 30 + 3 * (10) / 2 + 2 * (1)  (days)
waitTime = 47                           (days)
