jwsec = ("U" "." header64 "." compressed64) /
           ("S" "." header64 "." compressed64 "." signature64) /
           ("E" "." header64 "." enckey64 "." ciphertext64) /
           (ext "." header64 *("." component64))
             ; note: "X" matches "X" or "x" in ABNF

ext = %x41-5A / %x61-7A ; A-Z a-z

header64 = 1*b64url ; base64url-encoded UTF-8-encoded JSON object

compressed64 = *b64url ; input data, optionally compressed
signature64  = *b64url ; digital signature or MAC
enckey64     = *b64url ; encrypted per-message key
ciphertext64 = *b64url ; IV, encrypted data, and authentication tag
component64  = *b64url

b64url = %x41-5A / %x61-7A / %x30-39 / %x2D / %x5F
           ;   A-Z       a-z       0-9      -      _

signature  = SIGN(("S" or "s") "." B64(header) "." B64(compressed))

additionalData  = ("E" or "e") "." B64(header) "." B64(enckey)

ciphertext  = [iv] ENCRYPT(plaintext) authtag

