TXW_MAX_RTE = 16kBps
TXW_ADV_SECS = 5 seconds,
TXW_SECS = 35 seconds,
TXW_BYTES = 560kB,
TXW_SQNS = 383 (rounded up),

TXW_TRAIL = n
TXW_INC = n+53
TXW_LEAD = n+382

SPM_TYPE = 0x00

OD_TYPE =  0x10
RD_TYPE =  0x11

NAK_TYPE =  0x20
NNAK_TYPE = 0x21

NCF_TYPE =  0x30

RSN_TYPE = 0x40

