version="0" state="full">
id="8ajksjda7s"
duration-subscribed="509"
event="approved" >sip:subcriber@university.edu</watcher>
id="hh8juja87s997-ass7"
display-name="Mr. Subscriber"
event="subscribe">sip:subcriber@organization.org</watcher>
targetNamespace="urn:ietf:params:xml:ns:watcherinfo"
schemaLocation="http://www.w3.org/2001/03/xml.xsd" />
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
use="required"/>
minOccurs="0" maxOccurs="unbounded"/>
content="text/html;charset=iso-8859-1"/>
