Answer-Mode = "Answer-Mode" HCOLON answer-mode
answer-mode = "Manual" / "ManualReq" / "Auto" / "AutoReq"
Alert-Mode = "Alert-Mode" HCOLON alert-mode
alert-mode = "Normal" / "Null"

Alert-Mode = "alertmode"

Answer-Mode = "answermode"

Answer-Mode = "answermode"


methods="INVITE,BYE,OPTIONS,CANCEL,ACK"

