RSeq          =  "RSeq" ":" response-num
RAck          =  "RAck" ":" response-num CSeq-num Method
response-num  =  1*DIGIT
CSeq-num      =  1*DIGIT


Prack  =  "PRACK"


v=0
s=Let's talk
b=CT:128
c=IN IP4 north.east.isi.edu
m=audio 3456 RTP/AVP 5 0 7
m=video 2232 RTP/AVP 31



v=0
s=Let's talk
b=CT:128
c=IN IP4 machine.bell-tel.com
m=audio 3456 RTP/AVP 5 0 7
m=video 2232 RTP/AVP 31



v=0
s=Let's talk
b=CT:128
c=IN IP4 north.east.isi.edu
m=audio 3456 RTP/AVP 5 0 7
m=video 2232 RTP/AVP 31



