b64token    = 1*( ALPHA / DIGIT /
                       "-" / "." / "_" / "~" / "+" / "/" ) *"="
credentials = "Bearer" 1*SP b64token

access_token=mF_9.B5f-4.1JqM

scope="openid profile email"
scope="urn:example:channel=HBO&urn:example:rating=G,PG-13"

error="invalid_token",
error_description="The access token expired"

