tag_name=value_description      with zero or more values

tag_name={value_description}    with a single value

html=version

        Indicates support for the given HTML version.  Predefined
        values are 1.0, 2.0, 3.2.  Example: Accept-Features: html=2.0,
html=3.2, *


