Protocol         = "Protocol" ":" 1#bag
Protocol-Request = "Protocol-Request" ":" 1#bag

bag              = "{" bagname 1*LWS *bagitem "}"
bagname          = token | URI
bagitem          = bag | token | quoted-string

word             = token | quoted-string
token            = 1*<any CHAR except CTLs or tspecials>
tspecials        = "(" | ")" | "<" | ">" | "@"
                        | "," | ";" | ":" | "\" | <">
                        | "/" | "[" | "]" | "?" | "="
                        | "{" | "}" | SP  | HT

quoted-string    = ( <"> *(qdtext) <"> )
qdtext           = <any CHAR except <"> and CTLs but including LWS>

