yeardiff = (double)atoi(argv[1]) - EPOCH;

cryptoperf = yeardiff / 1.5;
cryptoperf = pow(2.0, cryptoperf);

multiplier = yeardiff / 3.0;
multiplier = pow(2.0, multiplier);
cracktime = pow(2.0, 55.0);
cracktime = pow(2.0, 8.0*6.0);
cracktime = pow(2.0, 64.0);
cracktime = pow(2.0, 8.0*6.0);
