mab_key = "DSA:deadbeefcafe001a"
foo == "bar"
foo=="bar";

foo=="bar" -> _MAX_TRUST;

user_name == "root" -> "full_access";       # clause (4)

a=="b" ->  { b=="c" -> "value1";
d=="e"  -> "value2";
foo == "bar" -> {
                        @a == 1/0 -> "oneval";    # subclause 1
                        @a == 2 -> "anotherval";  # subclause 2
                      };

Bob="RSA:d1234f"      # Bob's key
app_domain = "RFC822-EMAIL"
address = "mab@keynote.research.att.com"
app_domain = "RFC822-EMAIL"
address = "mab@keynote.research.att.com"
name = "M. Blaze"

app_domain = "RFC822-EMAIL"
address = "angelos@dsl.cis.upenn.edu"
app_domain = "RFC822-EMAIL"
address = "mab@keynote.research.att.com"
name = "M. Blaze"
app_domain = "RFC822-EMAIL"
address = "mab@keynote.research.att.com"
name = "J. Feigenbaum"

app_domain = "SPEND"
dollars = "45"
unmentioned_attribute = "whatever"
app_domain = "SPEND"
dollars = "550"

app_domain = "SPEND"
dollars = "5500"
app_domain = "SPEND"
dollars = "150"

app_domain = "SPEND"
dollars = "550"
app_domain = "SPEND"
dollars = "5500"


