Appl = signaling application

                     Figure 2: "On path" NSIS proxy

Appl = signaling         PA = Proxy for signaling
                   application            application

                    Figure 3: "Off path" NSIS proxy

