string => string
boolean => "True" | "False"
uintX => normal text mapping
sintX => normal text mapping
realX => <<currently under discussion in the DMTF>>
datetime => directory generalized time string

SuperiorPath = "PolicyRepository.CCN=""PolicyRepository",
PolicyRepositoryName=""MyRepository"""
CCN="QosPolicyCondition"
PolicyConditionName="MyCondition"

NamePath = "PolicyRepository.CCN=""PolicyRepository",
PolicyRepositoryName=""MyRepository"";
PolicyConditionName=""MyCondition"""

PolicyRepositoryName=""MyRepository"";
PolicyConditionName=""MyCondition"""

                                   minus

PolicyRepositoryName=""MyRepository"""

                                   which equals

PolicyConditionName=""MyCondition"""

cimName="PolicyCondition.CCN=""QosPolicyCondition"",
PolicyConditionName=""MyCondition"""

cimName="PolicyCondition.CCN=""BgpPolicyCondition"",
PolicyConditionName=""MyCondition"""

SuperiorPath = "System.CCN=""System"",Name=""MySystem"";
                      PolicyRule.CCN=""PolicyRule",
PolicyRuleName=""MyRule"""
CCN="QosPolicyCondition"
PolicyConditionName="MyCondition"

NamePath = "System.CCN=""System"",Name=""MySystem"";
                  PolicyRule.CCN=""PolicyRule",
PolicyRuleName=""MyRule"";
PolicyConditionName=""MyCondition"""

PolicyRuleName=""MyRule"";
PolicyConditionName=""MyCondition"""

                                   minus

PolicyRuleName=""MyRule"""

                                   which equals

PolicyConditionName=""MyCondition"""


