duplex="half"/> 
type="application/vxml+xml" 
name="sample" 
src="http://server.example.com/scripts/foo.vxml"/> 
id="conn:192.0.2.6:9684/dialog:sample"> 
type="application/moml+xml" duplex="half"> 
duplex="half" type="application/moml+xml"> 
T1 =====================RTP======================================> | 
                                 | <--INFO (MSML event:conf-id)------ | 
                                 | -----OK--------------------------> | 
                                 | ---INFO (MSML dialog[rec name])--> | 
                                 | <----OK--------------------------- | 
                                 | <--INFO (MSML event:recordexit)--- | 
                                 | -----OK--------------------------> | 
                                 | ---INFO (MSML createconf+join)---> | 
                                 | <----OK--------------------------- | 
       T2 ---------INVITE------> | 
       T2 <----------OK--------- | 
       T2 ---------ACK---------> | 
                                 | ---INVITE (MSML dialog[welcome])-> | 
                                 | <----OK--------------------------- | 
                                 | ---ACK---------------------------> | 
       T2 <================RTP======================================> | 
                                 | <--INFO (MSML event:conf-id)------ | 
                                 | -----OK--------------------------> | 
                                 | ---INFO (MSML dialog[rec name])--> | 
                                 | <----OK--------------------------- | 
                                 | <--INFO (MSML event:recordexit)--- | 
                                 | -----OK--------------------------> | 
                                 | ---INFO (MSML join)--------------> | 
                                 | <----OK--------------------------- | 
elementFormDefault="qualified" attributeFormDefault="unqualified"> 
type="msmlEventNameValue.datatype"/> 
type="msmlEventName.datatype" use="required"/> 
type="msmlEventSource.datatype" 
use="required"/> 
type="confID.datatype"/> 
type="dialogID.datatype"/> 
type="operatorID.datatype"/> 
use="required" fixed="1.0"/> 
use="required"/> 
type="conferenceType.datatype" use="optional"  
default="audio.advanced"/> 
type="msmlInstanceID.datatype"/> 
default="false"/> 
default="5s"/> 
use="required"/> 
default="true"/> 
type="independentID.datatype" use="required"/> 
type="dialogLanguage.datatype" use="required"/> 
type="msmlInstanceID.datatype"/> 
use="optional"/> 
use="required"/> 
use="required"/> 
use="required"/> 
use="required"/> 
use="required"/> 
use="required"/> 
use="required"/> 
use="required" fixed="application/moml+xml"/> 
type="msmlInstanceID.datatype" use="optional"/> 
use="required"/> 
use="required"/> 
use="required"/> 
use="required"/> 
use="required"/> 
type="boolean.datatype" default="false"/> 
use="required"/> 
use="required"/> 
elementFormDefault="qualified"  
attributeFormDefault="unqualified"> 
value="conf:[a-zA-Z0-9.:-_]+(/oper:[a-zA-Z0-9.:-_]+)+"/> 
value="conn:[a-zA-Z0-9.:-_]+(/oper:[a-zA-Z0-9.:-_]+)+"/> 
value="conf:[a-zA-Z0-9.:-_]+/dialog:[a-zA-Z0-9.:-_]+"/> 
 
 
 
 
value="conn:[a-zA-Z0-9.:-_]+/dialog:[a-zA-Z0-9.:-_]+"/> 
value="conf:[a-zA-Z0-9.:-_]+(/oper:[a-zA-Z0-9.:-_]+)*"/> 
value="conn:[a-zA-Z0-9.:-_]+(/oper:[a-zA-Z0-9.:-_]+)*"/> 
