icap_URI = scheme ":" net_path [ "?" query ]

scheme = "icap"
   
net_path = "//" authority [ abs_path ]

authority = [ userinfo @ ] <host> [ ":" <port> ]
      
reqmod_encapsulated = "Encapsulated" ":"
                  [ "req-hdr" = (integer)] [ "req-body" = (integer)]

respmod_encapsulated = "Encapsulated" ":"
                  [ "req-hdr" = (integer)] [ "res-hdr" = (integer) ]
                  [ "res-body" = (integer)]

