X-Frame-Options = "DENY"
                   / "SAMEORIGIN"
                   / ( "ALLOW-FROM" RWS SERIALIZED-ORIGIN )

RWS             = 1*( SP / HTAB )
                       ; required whitespace


