t=0        0.0 (1st frame)         3.1        (1 AS frame)
t=0.1      0.1                     3.1 - 3.2  (2 AS frames)
       ...
t=2.9      2.9                     3.1 - 6.0
t=3.0      3.0                     3.1 - 6.1  (AS buffer is full)
t=3.1      3.1                     3.2 - 6.2  (a stale frame purged)
       ...
       ...
       ...
t=37      37.0                    37.1 - 40.1 (always hold the next
       ...                                           3.1 sec worth of AS
                                                     media)

