Answer = response-code [answertext] CRLF
	    text CRLF
	    "."	CRLF

text	      =	%d1-9 /		  ; all	octets except
answertext =	WSP *(ALPHA / DIGIT / "+" / "-"	/ "/" /	"_" /
		    "="	/ "?" /	"!" / SP)

utc-time   =	14DIGIT	 ; The date and	time of	the server in UTC
			 ; YYYYMMDDhhmmss

hierarchy-name	 =  newsgroup-name ; these two are identical
newsgroup-name	 =  plain-component *("." component)
component		 =  plain-component / encoded-word
encoded-word		 =  lowercase /	DIGIT
			 =/ "+"	/ "-" /	"/" / "_" / "="	/ "?"
plain-component	 =  first-component-start component-rest
first-component-start = lowercase
component-start	 =  lowercase /	digit
lowercase		 =  %x61-7a ; letter a-z lowercase
component-rest	 =  component-start / "+" / "-"	/ "_"

help-cmd = "HELP" [WSP commandname] CRLF

commandname =  "DATA" / "DATE" / "GETL" / "GETP" / "GETA"
	       =/ "HELP" / "HIER" / "INFO" / "LIST" / "LSTR"
	       =/ "QUIT" / "VERS"

help-answer =  "410"	[answertext] CRLF
		  text CRLF
		  "." CRLF
	       =/ "100"	[answertext] CRLF
		  text CRLF
		  "." CRLF

info-cmd =  "INFO" CRLF

info-answer =  "400"	[answertext] CRLF
		  text CRLF
		  "." CRLF
	       =/ "101"	[answertext] CRLF
		  text CRLF
		  "." CRLF

date-cmd =  "DATE" CRLF

date-answer =  "511"	[answertext] CRLF
		  text CRLF
		  "." CRLF
	       =/ "300"	[answertext] CRLF
		  utc-time [answertext]	CRLF
		  "." CRLF

vers-cmd =  "VERS" [WSP level] CRLF

level = 1*5DIGIT ; the valid	range is 1 - 32767

vers-answer =  "202"	[answertext] CRLF
		  level	[answertext] CRLF
		  "." CRLF
	       =/ "302"	[answertext] CRLF
		  level	[answertext] WSP level CRLF
		  "." CRLF
	       =/ "402"	[answertext] CRLF
		  level	[answertext] WSP level CRLF
		  "." CRLF
	       =/ "510"	[answertext] CRLF
		  level	[answertext] CRLF
		  "." CRLF

quit-cmd =  "QUIT" CRLF

quit-answer = "201" [answertext] CRLF
list-cmd =  "LIST" (	WSP "*"	/ 1*(WSP hierarchy-name)) CRLF

list-answer =  "610"	[answertext] CRLF
		  *(listdata CRLF)
		  "." CRLF
	       =/ "401"	[answertext] CRLF
		  text CRLF
		  "." CRLF
	       =/ "530"	[answertext] CRLF
		   text	CRLF
		   "." CRLF

listdata    =  newsgroup-name WSP list-status CRLF

list-status =  "Complete"
	       =/ "Incomplete"
	       =/ "Obsolete"
	       =/ "Unknown"
	       =/ "Unmoderated"
	       =/ "Readonly"
	       =/ "Moderated"
	       =/ "Removed"
	       ; list-status is	case-insensitive

lstr-cmd = "LSTR" ( WSP "*" / 1*(WSP	hierarchy-name)) CRLF

lstr-answer =  "610"	[answertext] CRLF
		  *(listdata CRLF)
		  "." CRLF
	       =/ "401"	[answertext] CRLF
		  text CRLF
		  "." CRLF
	       =/ "530"	[answertext] CRLF
		  text CRLF
		  "." CRLF

listdata    =  newsgroup-name WSP list-status CRLF

list-status =  "Complete"
	       =/ "Incomplete"
	       =/ "Obsolete"
	       =/ "Unknown"
	       =/ "Unmoderated"
	       =/ "Readonly"
	       =/ "Moderated"
	       =/ "Removed"
	       ; list-status is	case-insensitive

hier-cmd =  "HIER" [WSP range] 1*(WSP hierarchy-name) CRLF

range    = header *(	"," header ) ; Describes the data fields
				     ; that are	requested
header   = ALPHA *( ALPHA / "-" ) ; According to section 6.3.4
hier-answer =  "611"	[answertext] CRLF
		  *(hierdata CRLF)
		  "." CRLF
	       =/ "530"	[answertext] CRLF
		  *(text CRLF)
		  "." CRLF
	       =/ "401"	[answertext] CRLF
		  *(text CRLF)
		  "." CRLF

hierdata    =  "Name:" WSP test CRLF
		  "Status:" WSP	text CRLF
		  *(header ":" WSP text	CRLF)
		  ["Ctl-PGP-Key:" CRLF PGP-answer]
		  ["Mod-PGP-Key:" CRLF PGP-answer]

data-cmd =  "DATA" [WSP range] 1*(WSP newsgroup-name) CRLF

data-answer =  "612"	[answertext] CRLF
		  *(datadata CRLF)
		  "." CRLF
	       =/ "530"	[answertext] CRLF)
		  text CRLF
		  "." CRLF
	       =/ "401"	[answertext] CRLF
		  text CRLF
		  "." CRLF

datadata    =  "Name:" WSP test CRLF
		  "Status:" WSP	text CRLF
		  *(header ":" WSP text	CRLF)
		  ["Ctl-PGP-Key:" CRLF PGP-answer]
		  ["Mod-PGP-Key:" CRLF PGP-answer]

getl-cmd =  "GETL" CRLF
getl-answer =  "614"	[answertext] CRLF
		  *(getldata)
		  "." CRLF
	       =/ "401"	[answertext] CRLF
		  text CRLF
		  "." CRLF


getldata    = *(newsgroup-name CRLF)

getp-cmd =  "GETP" WSP username WSP password	WSP timestamp
	       ( WSP "0" / *( WSP hierarchy-name )) CRLF

username =  *1( VCHAR ) / "0" ; Length of VCHAR >= 1

password =  *1( VCHAR ) / "0" ; Length of VCHAR >= 1

timestamp   =  utc-time ; date and time of the last retrieval
	       =/ "0"	   ; force the transmission of data

getp-answer =  "613"	[answertext] CRLF
		  pgp-start-mark ; this	is according to	[RFC2440]
		  "GETP" WSP "SIGN" WSP	method CRLF
		  "GETP" WSP "BEGIN" CRLF
		  *(getpdata CRLF)
		  "GETP" WSP "END" CRLF
		  pgp-end-mark ; this is according to [RFC2440]
		  "." CRLF
	       =/ "213"	[answertext] CRLF
		  text CRLF
		  "." CRLF
	       =/ "430"	[answertext] CRLF
		  text CRLF
		  "." CRLF
	       =/ "411"	[answertext] CRLF
		  text CRLF
		  "." CRLF
	       =/ "530"	[answertext] CRLF
		  text CRLF
		  "." CRLF

method      =  "PGP2" / "PGP5" / "GPG"
		  ; PGP	version	2, PGP version 5 and GnuPG
getpdata   =	 "Name:" WSP text CRLF
		  "Status:" WSP	text CRLF
		  *(header ":" WSP text	CRLF)
		  ["Ctl-PGP-Key:" CRLF PGP-answer]
		  ["Mod-PGP-Key:" CRLF PGP-answer]

fR5aQJfwKhE=
geta-cmd =  "GETA" WSP username WSP password	WSP
	       timestamp WSP hierarchy-name CRLF

geta-answer =  "615"	[answertext] CRLF
		  pgp-start-mark ; this	is according to	[RFC2440]
		  "GETA" WSP "SIGN" WSP	method CRLF
		  "GETA" WSP "BEGIN" CRLF
		  *(getadata CRLF)
		  "GETA" WSP "END" CRLF
		  pgp-end-mark ; this is according to [RFC2440]
		  "." CRLF
	       =/ "215"	[answertext] CRLF
		   text	CRLF
		   "." CRLF
	       =/ "430"	[answertext] CRLF
		  text CRLF
		  "." CRLF
	       =/ "411"	[answertext] CRLF
		  text CRLF
		  "." CRLF
	       =/ "530"	[answertext] CRLF
		  text CRLF
		  "." CRLF

getadata   =	 "Name:" WSP text CRLF
		  "Status:" WSP	text CRLF
		  *(header ":" WSP text	CRLF)
		  ["Ctl-PGP-Key:" CRLF PGP-answer]
		  ["Mod-PGP-Key:" CRLF PGP-answer]

fR5aQJfwKhE=
K-=Xwgc
PGP-answer =	"V" SP Version CRLF
K-=Xwgc
