rtcweb-media-constraint = media-type constraint-type constraint
media-type              = "audio" / "video"
constraint-type         = "Min" / "Max" / "Enum"
constraint              = %x41-5A 0*constraint-char
constraint-char         = ALPHA / DIGIT
   

