F = 0x80                    C = 0x00000000
H = Operator's defined      T = none
L = 18 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = Operator's defined      T = none
L = 18 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = Operator's defined      T = none
L = 18 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = 0x00                    T = none
L = 18 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = Operator's defined      T = none
L = 18 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = Operator's defined      T = Type_1 (Peer_AS)
L = 25 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = Operator's defined      T = Type_1 (Peer_AS)
L = 25 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = Operator's defined      T = Type_1 (Peer_AS)
L = 25 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = 0x00                    T = none
L = 18 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = 0x00                    T = none
L = 18 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = 0x00                    T = none
L = 18 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = 0x00                    T = none
L = 18 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = 0x00                    T = none
L = 18 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = 0x00                    T = Type_1 (Peer_AS)
L = 25 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = Operator's defined      T = Type_1 (AS#)
L = 25 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = Operator's defined      T = Type_1 (AS#)
L = 25 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = Operator's defined      T = Type_1 (AS#)
L = 29 octets               E = none
R = IANA assigned           P = Type_4 (0xAA)

F = 0x80                    C = 0x00000000
H = Operator's defined      T = Type_1 (AS#)
L = 29 octets               E = none
R = IANA assigned           P = Type_4 (0xAA)

F = 0x80                    C = 0x00000000
H = Operator's defined      T = Type_1 (AS#)
L = 25 octets               E = none
R = IANA assigned           P = none

F = 0x80                    C = 0x00000000
H = Operator's defined      T = none
L = 22 octets               E = none
R = IANA assigned           P = Type_4 (ABBBBBBB)

F = 0x80                    C = 0x00000000
H = Operator's defined      T = none
L = 22 octets               E = none
R = IANA assigned           P = Type_4 (0xAA) max AS_PATH radius

F = 0x80                    C = 0x00000000
H = Operator's defined      T = none
L = 26 octets               E = none
R = IANA assigned           P = Type_8 (5 UTF-8 characters)

F = 0x80                    C = 0x00000000
H = 0x00                    T = 0x00000978 (dec 2424)
L = 0x001D (dec 29 octets)  E = none
R = IANA assigned           P = 0x04 (dec 4)




















