PACESharedSecret = KA(SKEi, PKEi, GE) = KA(SKEr, PKEr,
AUTHi = prf(prf+(PACESharedSecret, "PACE Authentication i" | IDr |
AUTHr = prf(prf+(PACESharedSecret, "PACE Authentication r" | IDi |
SASharedSecret = g^ir

