dkim=  Outbound signing practices for the domain (plain-text;
      REQUIRED).  Possible values are as follows:

      unknown  The domain may sign some or all email.

      all  All mail from the domain is signed; unsigned email MUST be
         considered Suspicious.  The domain may send messages through
         agents that may modify and re-sign messages, so email signed
         with a Verifier Acceptable Third-Party Signature SHOULD NOT be
         considered Suspicious.

      strict  All mail from the domain is signed; messages lacking a
         valid Originator Signature MUST be considered Suspicious.  The
         domain does not expect to send messages through agents that may
         modify and re-sign messages.
            NON-NORMATIVE RATIONALE:  Strict practices may be used by
            entities which send only transactional email to individual
            addresses and which are willing to accept the consequence of
            having some mail which is re-signed appear suspicious in
            return for additional control over their addresses.  Strict
            practices may also be used by entities which do not send
            (and therefore do not sign) any email.

      ABNF:

ssp-dkim-tag = "dkim" [FWS] "=" [FWS] ("unknown" /
                             "all" / "strict")

handling=  Non-compliant message handling request for the domain
      (plain-text; OPTIONAL).  Possible values are as follows:

      process  Messages which are Suspicious from this domain SHOULD be
         processed by the verifier, although the SSP failure MAY be
         considered in subsequent evaluation of the message.  This is
         the default value.

      deny  Messages which are Suspicious from this domain MAY be
         rejected, bounced, or otherwise not delivered at the option of
         the verifier.

            NON-NORMATIVE EXPLANATION:  The "deny" practice is intended
            for use by domains that value security over deliverability.
            For example, a domain used by a financial institution to
            send transactional email, which signs all of its messages,
            might consider their concern about phishing messages
            purporting to come from their domain to be higher than their
            concern about some some legitimate messages not being
            delivered.  The "handling=deny" practice allows them to
            express that concern in a way that can be acted upon by
            verifiers, if they so choose.

      ABNF:

ssp-handling-tag = "handling" [FWS] "=" [FWS] ("process" /
                               "deny")

t= Flags, represented as a colon-separated list of names (plain-text;
      OPTIONAL, default is that no flags are set).  Flag values are:

      y  The domain is testing signing practices, and the Verifier
         SHOULD NOT consider a message suspicious based on the record.
      s  The signing practices apply only to the named domain, and not
         to subdomains.

      ABNF:

ssp-t-tag     = %x75 [FWS] "=" [FWS] ssp-t-tag-flag
                           0*( [FWS] ":" [FWS] ssp-t-tag-flag )
ssp-t-tag-flag = "y" / "s" / hyphenated-word
                           ; for future extension
hyphenated-word =  ALPHA [ *(ALPHA / DIGIT / "-")
                                (ALPHA / DIGIT) ]

