v=0
o=romeo 289087 289087 IN IP4 orchard.montague.example.net
s=-
c=IN IP4 orchard.montague.example.net
t=0 0
m=audio 39923 RTP/AVP 0
a=rtpmap:0 PCMU/8000
c=IN IP4 xmpp.montague.example.net
t=0 0
m=message 5222 xmpp/tcp chat
a=direction:both
a=jid:romeo@montague.example.net/orchard
a=thread:283461923759234

v=0
o=juliet 289087 289087 IN IP4 balcony.thecappulets.example.com
s=-
c=IN IP4 balcony.thecappulets.example.com
t=0 0
m=audio 0 RTP/AVP 0
a=rtpmap:0 PCMU/8000
c=IN IP4 impish.thecapulets.example.com
t=0 0
m=message 5222 xmpp/tcp chat
a=direction:passive
a=jid:juliet@thecappulets.example.com/balcony

to="romeo@montague.example.net/orchard"
from="juliet@thecappulets.example.com/balcony"
type="chat">
to="juliet@thecappulets.example.com/balcony"
from="romeo@montague.example.net/orchard"
type="chat">
to="romeo@montague.example.net/orchard"
from="juliet@thecappulets.example.com/balcony"
type="chat">
entity="pres:juliet@thecapulets.example.com">
entity="pres:juliet@thecapulets.example.com">
