H       = Host requesting end-to-end RSVP reservations
R       = RSVP router
Agg     = Aggregator (PCN-ingress-node)
Deag    = Deaggregator (PCN-egress-node)
I       = Interior Router (PCN-interior-node)
Class = 248 (PCN)
C-Type = 1 (RSVP-AGGREGATE-IPv4-PCN-request

        +-------------+-------------+-------------+-------------+
        |     IPv4 PCN-ingress-node Address (4 bytes)           |
        +-------------+-------------+-------------+-------------+
        |     IPv4 PCN-egress-node Address (4 bytes)            |
        +-------------+-------------+-------------+-------------+
        |     IPv4 Decision Point Address (4 bytes)             |
        +-------------+-------------+-------------+-------------+
        |R|     Reserved                                        |
        +-------------+-------------+-------------+-------------|

Class = 248 (PCN)
C-Type = 2 (RSVP-AGGREGATE-IPv6-PCN-request 

        +-------------+-------------+-------------+-------------+
        |                                                       |
        +                                                       +
        |                                                       |
        +     IPv6 PCN-ingress-node Address (16 bytes)          +
        |                                                       |
        +                                                       +
        |                                                       |
        +-------------+-------------+-------------+-------------+
        |                                                       |
        +                                                       +
        |                                                       |
        +     IPv6 PCN-egress-node Address (16 bytes)           +
        |                                                       |
        +                                                       +
        |                                                       |
        +-------------+-------------+-------------+-------------+
        |                                                       |
        +                                                       +
        |                                                       |
        +     Decision Point Address (16 bytes)                 +
        |                                                       |
        +                                                       +
        |                                                       |
        +-------------+-------------+-------------+-------------+
        |R|     Reserved                                        |
        +-------------+-------------+-------------+-------------+


Class = 248 (PCN)
C-Type = 3 (RSVP-AGGREGATE-IPv4-PCN-response)

        +-------------+-------------+-------------+-------------+
        |     IPv4 PCN-ingress-node Address (4 bytes)           |
        +-------------+-------------+-------------+-------------+
        |     IPv4 PCN-egress-node Address (4 bytes)            |
        +-------------+-------------+-------------+-------------+
        |     IPv4 Decision Point Address (4 bytes)             |
        +-------------+-------------+-------------+-------------+
        | PCN-sent-rate                                         |
        +-------------+-------------+-------------+-------------+

Class = 248 (PCN)
C-Type = 4 (RSVP-AGGREGATE-IPv6-PCN-response)

        +-------------+-------------+-------------+-------------+
        |                                                       |
        +                                                       +
        |                                                       |
        +     IPv6 PCN-ingress-node Address (16 bytes)          +
        |                                                       |
        +                                                       +
        |                                                       |
        +-------------+-------------+-------------+-------------+
        |                                                       |
        +                                                       +
        |                                                       |
        +     IPv6 PCN-egress-node Address (16 bytes)           +
        |                                                       |
        +                                                       +
        |                                                       |
        +-------------+-------------+-------------+-------------+
        |                                                       |
        +                                                       +
        |                                                       |
        +     Decision Point Address (16 bytes)                 +
        |                                                       |
        +                                                       +
        |                                                       |
        +-------------+-------------+-------------+-------------+
        | PCN-sent-rate                                         |
        +-------------+-------------+-------------+-------------+

 


