p_C = ( p_CL / k )^2                  (1)

p_C = (p')^2.                         (2)

p_CL = k*p'.                          (3)

p_L = max(p'_L, p_CL),                (4)

U=1):

U=1).  Comparing it with the maximum out of two is the same as the
U=1 has been used in experiments so far, but results might be even
k=2^k'.

k=8) would achieve throughput equivalence, and experiments verified
