fssi=E:1400,WSR:191

dw_max_size = (max_lat * br_in) / (8 * E)

dw_max_size = (max_lat * br_out * cr) / (8 * E)

ew_max_size = dw_max_size * WSR / 255

dw_max_size = max_NSS_observed * 255 / WSR

max_lat_for_encoding = max_lat * WSR / 255

ls_max_size = 2 * dw_max_size

ls_max_size = max(2 * dw_max_size, LS_MIN_SIZE_DEFAULT)

