targetNamespace="http://lightweightcurrency.org"
xmlns="http://schemas.xmlsoap.org/wsdl/"
xmlns="http://www.w3.org/2001/XMLSchema">
type="impl:ArrayOfTransaction"/>
name="queryRequest"/>
name="queryResponse"/>
transport="http://schemas.xmlsoap.org/soap/http"/>
encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
namespace="http://lightweightcurrency.org"
use="encoded"/>
encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
namespace="http://lightweightcurrency.org"
use="encoded"/>
location="http://p2p-market.org/issuer/Account"/>
