R-flag = 0 (actual length of the header with padding 24 bytes = 3
R-flag = 1 (actual length of the header 24 bytes = 3 * 8 bytes)

R-flag = 0 (actual length of the header 24 bytes = 3 * 8 bytes)

accept = application/pvd+json

content-type = application/pvd+json
content-length = 116

