EP = 1 in the forwarding entry for the BFER.  If EP = 1, the
Packet = the packet received by BFR;
BFR-NBR = F.  The F-BM for each of these two rows in the BIFT is the
BFER = 0/NULL}.

        +--------------+--------------+----------+----------------+
        |    BFR-id    |  BFR-Prefix  |  BFR-NBR |  {EP,BE-BFER}  |
        |(SI:BitString)| of Dest BFER |(Next Hop)|  (Backup Info) |
        +==============+==============+==========+================+
        |  1 (0:00001) |      D       |  D/NULL  |EP=1, BE-BFER=H |
        +--------------+--------------+----------+----------------+
        |  2 (0:00010) |      F       |    F     |EP=0, BE-BFER=0 |
        +--------------+--------------+----------+----------------+
        |  3 (0:00100) |      E       |    F     |EP=0, BE-BFER=0 |
        +--------------+--------------+----------+----------------+
        |  4 (0:01000) |      H       |    H     |EP=0, BE-BFER=0 |
        +--------------+--------------+----------+----------------+
        |  5 (0:10000) |      A       |    B     |EP=0, BE-BFER=0 |
        +--------------+--------------+----------+----------------+

                   Figure 7: EP-BIRT for BFER D on BFR C

BFER=0}.  The F-BM for each of these two rows in the EP-BIFT is the
BE-BFER = H) in Packet's BitString to one.  The BitString in Packet
BitString = 01000.

