xmlns="http://purl.org/atom/ns#draft-ietf-atompub-format-01">
     <head>
       <title>Example Feed</title>
       <link rel="alternate" type="text/html"
href="http://example.org/index.atom"/>
href="http://example.org/2003/12/13/atom03"/>
