DELTA_t = (t-t0)/t0 can be modeled by a zero-mean Laplacian
r = R_min
r = r + l

R_ref = min (Rf_max, max(Rf_min, R_v))

r_current = r
t_current = t_current + 1
t_current = ((t_current + 1 - SkipFrames)
                               % (size_traces-SkipFrames)) + SkipFrames


size_lo = Traces[r_current][t_current]
size_hi = Traces[r_current + l][t_current]
distance_lo = (R_v - r_current) / l
framesize = size_hi*distance_lo + size_lo*(1-distance_lo)

w = R_v / Rf_min
framesize = max(fs_min, factor * Traces[Rf_min][t_current])

w = R_v / Rf_max
framesize = min(fs_max, w * Traces[Rf_max][t_current])

