rtcp-xr-attrib =  "a=rtcp-xr:"
                     [xr-format *(SP xr-format)] CRLF

xr-format = RTP-flows-syn
                  / audio-video-ofset
                  / multimedia-quality-metrics
                  / video-stream-loss-metrics
                  / video-stream-burst-metrics
                  / video-stat-summary
                  / layered-video-stat-metrics

RTP-flows-syn = "RTP-flows-syn"
                         ["=" max-size]
max-size = 1*DIGIT ; maximum block size in octets

audio-video-ofset = "audio-video-ofset"
                           ["=" max-size]
max-size = 1*DIGIT ; maximum block size in octets

video-stream-burst-metrics = "video-stream-burst-metrics"
                               ["=" max-size]
max-size = 1*DIGIT ; maximum block size in octets

video-stream-loss-metrics = "video-stream-loss-metrics"
                                 ["=" stat-flag *("," stat-flag)]
stat-flag = "key Frame loss and duplication"
                           / "derivation Frame loss and duplication"

video-stat-summary = "video-stat-summary"
                                 ["=" stat-flag *("," stat-flag)]
stat-flag = "key Frame loss and duplication"
                           / "derivation Frame loss and duplication"


layered-stream-stat-metrics = "layered-stream-stat-metrics"
                              ["=" stat-flag *("," stat-flag)]
stat-flag = "base layer packet"
                           / "enhancment layer packet"

multimedia-quality-metrics = "multimedia-quality-metrics"
                               ["=" stat-flag *("," stat-flag)]
stat-flag = "Interval Metric"
                        / "MOS-V"
                        / "MOS-A"
                        / "MOS-AV"
                        / "VSTQ"

