o=Example, st=CA, c=US).   However, registration infrastructure and
domain = null;
domain = "";
domain = ".";
domain = null;
dc=example,dc=net               example.net
uid=jdoe,dc=example,dc=net      example.net
dc=.                            .            [2]
dc=example,dc=net,dc=.          .            [3]
dc=example,dc=.,dc=net          net          [4]
dc=example.net                  example.net  [5]
cn=Jane Doe,o=example,c=us      null
uid=jdoe,dc=example,c=us        null
dc=example,o=example,dc=net     net
dc=example+o=example,dc=net     net
dc=example,o=us+dc=net          null

dc=.

dc=. and dc=. if further domainComponents are found to the left.

base="dc=example,dc=net"
scope=base
filter=(objectclass=*)
base="cn=subordinate,dc=example,dc=net"
scope=base
filter=(objectclass=*)
matchedDN="dc=example,dc=net"
