AC  ==>|U-PE1|               |     |                 |U-PE2|==> AC
           | \   |               +-----+                 |   / |
           |  \--|======================================>|--/  |
           +-----+             PSN Tunnel                +-----+

        Fig. 1:  Reflector Networking in Simple relay Mode

Nexthop   = R   |  R  |  Dest.  PE = PE1
