A = some-large-random-number
B = SHA1(A)

mtrk-parameter  = "MTRK=" mtrk-certifier [ ":" mtrk-timeout ]
mtrk-certifier  = base64        ; authenticator
mtrk-timeout    = 1*9digit      ; seconds until timeout


           A is stored in the originator's tracking database to
envid-parameter = "ENVID=" unique-envid
unique-envid    = local-envid "@" fqhn
local-envid     = xtext
fqhn            = xtext

