context=+1-732", identifying a more specific context. However, the 
URL="http://ms1.oisp-c.example.com/whisper/20070206092700-
expiration="Tues, 06 Feb 2007 09:30:00 GMT"; 
URL="http://ms1.oisp-c.example.com/whisper/20070206092700-
expiration="Tues, 06 Feb 2007 09:30:00 GMT"; 
voicexml=http://vxmlserver.example.net/cgi-bin/script.vxml \ 
voicexml=http://vxmlserver.example.net/cgi-bin/script.vxml 
Info=intercepted number ) 
SAP=intcpt type ) 
