comp=sigcomp to its URI in the Record-Route header field.

comp=sigcomp to the topmost entry of the Via header field.

comp=sigcomp to the topmost entry of the Via header field. The
comp=sigcomp, the response SHOULD be compressed. Otherwise, the
compression-param  =  "comp=" ("sigcomp" / other-compression)
other-compression  =  token


via-compression    =  "comp" EQUAL ("sigcomp" / other-compression)
other-compression  =  token


