content="text/html;charset=iso-8859-1"/>
entity="pres:someone@example.com" version="0"
state="full">

entity="pres:someone@example.com" version="1"
state="partial">

              <tuple id="cg231jcr">
                <status><basic>closed</basic>
                </status>
                <contact priority="1.0">
                      im:pep@example.com</contact>
                <note xml:lang="en">This is an update of existing
                tuple sent in previous notification</note>
              </tuple>

              <tuple id="wsqw798jcr">
                <status><basic>open</basic>
                </status>
                <contact priority="0.4">
                      im:mac@hut.com</contact>
                <note xml:lang="en">This is a completely new
                tuple not sent in previous notification</note>
              </tuple>
              <note xml:lang="en">
elementFormDefault="qualified"
attributeFormDefault="unqualified">

schemaLocation="http://www.w3.org/2001/xml.xsd"/>
type="tns:partial-presence"/>
type="tns:removed_tuple"
minOccurs="0"/>
   	    </xs:sequence>
   	    <xs:attribute name="version"
type="xs:nonNegativeInteger"
use="required"/>
   	    <xs:attribute name="state" use="required">
   	    <xs:simpleType>
type="xs:ID"
minOccurs="1"
maxOccurs="unbounded"/>
