type="ds:KeyInfoType" minOccurs="0"/>
type="pskc:KeyAlgorithmType" minOccurs="0"/>
type="pskc:KeyPropertiesType" minOccurs="0"
maxOccurs="unbounded"/>
type="pskc:DeviceType" minOccurs="1"
maxOccurs="unbounded"/>
type="ds:SignatureType" minOccurs="0"/>
type="pskc:ExtensionsType" minOccurs="0"
maxOccurs="unbounded"/>
           </xs:sequence>
           <xs:attribute name="Version" type="pskc:VersionType"
use="required"/>
use="optional"/>
definition="http://ACME/MyExtension1.html">blah</Myextension1>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="1"/>
type="pskc:PINPolicyType" minOccurs="0"/>
minOccurs="0"/>
type="xs:dateTime" minOccurs="0"/>
type="pskc:ExtensionsType" minOccurs="0"
maxOccurs="unbounded"/>
           </xs:sequence>
           <xs:attribute name="ID" type="xs:ID"
use="required"/>
type="pskc:KeyAlgorithmType" use="optional"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
type="pskc:ExtensionsType" minOccurs="0"
maxOccurs="unbounded"/>
definition="http://ACME/MyExtension1.html">blah</Myextension1>
type="pskc:ExtensionsType" minOccurs="0"
maxOccurs="unbounded"/>
definition="http://ACME/MyExtension1.html">blah</Myextension1>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="1"/>
type="pskc:PINPolicyType" minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
type="pskc:ExtensionsType" minOccurs="0"
maxOccurs="unbounded"/>
use="required"/>
type="pskc:KeyAlgorithmType" use="optional"/>
use="optional"/>
definition="http://ACME/MyExtension1.html">blah</Myextension1>
type="xs:int"/>
type="xenc:EncryptedDataType"/>
type="xs:base64Binary" minOccurs="0"/>
minOccurs="0" maxOccurs="1"/>
minOccurs="0" maxOccurs="1"/>
minOccurs="0" maxOccurs="1"/>
minOccurs="0" maxOccurs="1"/>
minOccurs="0" maxOccurs="1"/>
maxOccurs="unbounded"/>
type="pskc:ValueFormatType"
use="required"/>
type="xs:unsignedInt" use="required"/>
type="xs:unsignedInt" use="required"/>
type="xs:boolean" default="false"/>
type="pskc:ValueFormatType"
use="required"/>
type="xs:unsignedInt" use="required"/>
type="xs:boolean" default="false"/>
type="pskc:ExtensionsType" minOccurs="0"
maxOccurs="unbounded"/>
default="false"/>
default="false"/>
default="false"/>
default="false"/>
default="false"/>
definition="http://ACME/MyExtension1.html">blah</Myextension1>
minOccurs="0"/>
type="xs:unsignedInt" minOccurs="0"/>
type="xs:unsignedInt" minOccurs="0"/>
type="pskc:ValueFormatType" minOccurs="0"/>
type="pskc:ExtensionsType" minOccurs="0"
maxOccurs="unbounded"/>
definition="http://ACME/MyExtension1.html">blah</Myextension1>
minOccurs="0" maxOccurs="unbounded"/>
xmlns="urn:ietf:params:xml:ns:keyprov:pskc:1.0"
xmlns="urn:ietf:params:xml:ns:keyprov:pskc:1.0"
type="pskc:KeyDerivationMethodType" minOccurs="0"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
use="required"/>
xmlns="urn:ietf:params:xml:ns:keyprov:pskc:1.0"
Version="1.0">
       <EncryptionKey>
         <DerivedKey Id="#Passphrase1">
           <CarriedKeyName>Passphrase1</CarriedKeyName>
           <KeyDerivationMethod
Algorithm=
KeyId="0755225266">
             <pskc:Issuer>AnIssuer</pskc:Issuer>
             <pskc:Usage OTP="true">
                 <pskc:ResponseFormat Length="8"
Format="DECIMAL"/>
targetNamespace="urn:ietf:params:xml:ns:keyprov:pskc:1.0"
elementFormDefault="qualified" attributeFormDefault="unqualified"
version="1.0">
    <xs:import namespace="http://www.w3.org/2000/09/xmldsig#"
schemaLocation=
schemaLocation="http://www.w3.org/TR/
minOccurs="0"/>
minOccurs="0"/>
type="pskc:KeyPropertiesType" minOccurs="0"
maxOccurs="unbounded"/>
minOccurs="1" maxOccurs="unbounded"/>
minOccurs="0"/>
type="pskc:ExtensionsType" minOccurs="0"
maxOccurs="unbounded"/>
use="required"/>
type="xs:ID" use="optional"/>





type="xs:string" minOccurs="0"/>
type="pskc:UsageType" minOccurs="0"/>
type="xs:string" minOccurs="0"/>
type="xs:string" minOccurs="0"/>
minOccurs="0" maxOccurs="1"/>
type="pskc:PINPolicyType" minOccurs="0"/>
type="xs:dateTime" minOccurs="0"/>
type="xs:dateTime" minOccurs="0"/>
type="pskc:ExtensionsType" minOccurs="0"
maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:attribute name="ID"
type="xs:ID" use="required"/>
type="pskc:KeyAlgorithmType"
use="optional"/>
type="xs:string" minOccurs="0"/>
type="pskc:UsageType"/>
                        <xs:element name="KeyProfileId"
type="xs:string" minOccurs="0"/>
type="xs:string" minOccurs="0"/>
type="xs:string" minOccurs="0"/>
minOccurs="0" maxOccurs="1"/>





type="pskc:PINPolicyType" minOccurs="0"/>
type="xs:dateTime" minOccurs="0"/>
type="xs:dateTime" minOccurs="0"/>
minOccurs="0"/>
type="pskc:ExtensionsType" minOccurs="0"
maxOccurs="unbounded"/>
type="xs:string" use="required"/>
type="pskc:KeyAlgorithmType"
use="required"/>
type="xs:IDREF" use="optional"/>
type="pskc:binaryDataType"
minOccurs="0" maxOccurs="1"/>
type="pskc:longDataType"
minOccurs="0" maxOccurs="1"/>
type="pskc:intDataType"
minOccurs="0" maxOccurs="1"/>
type="pskc:intDataType"
minOccurs="0" maxOccurs="1"/>
type="pskc:intDataType"
minOccurs="0" maxOccurs="1"/>
minOccurs="0" maxOccurs="unbounded"/>
type="xs:base64Binary"/>
type="xenc:EncryptedDataType"/>





type="xs:base64Binary" minOccurs="0"/>
type="xs:int"/>
type="xenc:EncryptedDataType"/>
type="xs:base64Binary" minOccurs="0"/>
type="xs:string"/>
type="xenc:EncryptedDataType"/>
type="xs:base64Binary" minOccurs="0"/>
type="xs:long"/>
type="xenc:EncryptedDataType"/>
type="xs:base64Binary" minOccurs="0"/>
type="pskc:KeyDerivationMethodType" minOccurs="0"/>
minOccurs="0"/>





maxOccurs="unbounded"/>
use="required"/>
type="pskc:PINUsageModeType"/>
minOccurs="0"/>
type="xs:unsignedInt" minOccurs="0"/>
type="xs:unsignedInt" minOccurs="0"/>
type="pskc:ValueFormatType" minOccurs="0"/>
type="pskc:ExtensionsType" minOccurs="0"
maxOccurs="unbounded"/>
use="optional"/>
processContents="lax" minOccurs="0"
maxOccurs="unbounded"/>
minOccurs="0"/>





minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
type="pskc:ExtensionsType" minOccurs="0"
maxOccurs="unbounded"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
type="pskc:ExtensionsType" minOccurs="0"
maxOccurs="unbounded"/>
type="pskc:ValueFormatType" use="required"/>
use="required"/>
use="required"/>
default="false"/>
type="pskc:ValueFormatType" use="required"/>
use="required"/>
default="false"/>





type="pskc:ExtensionsType" minOccurs="0"
maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="OTP" type="xs:boolean" default="false"/>
            <xs:attribute name="CR" type="xs:boolean" default="false"/>
            <xs:attribute name="Integrity" type="xs:boolean"
default="false"/>
default="false"/>
default="false"/>
maxOccurs="unbounded"/>
use="optional"/>
content="text/html;charset=iso-8859-1"/>
xmlns="urn:ietf:params:xml:ns:keyprov:pskc:1.0">
       <Device>
           <DeviceInfo>
               <Manufacturer>Manufacturer</Manufacturer>
               <SerialNo>987654321</SerialNo>
           </DeviceInfo>
           <Key KeyAlgorithm="http://www.ietf.org/keyprov/pskc#hotp"
KeyId="987654321">
               <Issuer>Issuer</Issuer>
               <Usage OTP="true">
                   <ResponseFormat Length="8"
Format="DECIMAL"/>
MTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
xmlns="urn:ietf:params:xml:ns:keyprov:pskc:1.0">
       <Device>
           <DeviceInfo>
               <Manufacturer>Manufacturer</Manufacturer>
               <SerialNo>0755225266</SerialNo>
           </DeviceInfo>
           <Key KeyAlgorithm="http://www.ietf.org/keyprov/pskc#hotp"
KeyId="0755225266">
               <Issuer>AnIssuer</Issuer>
               <Usage OTP="true">
                   <ResponseFormat Length="6" Format="DECIMAL"/>
               </Usage>
                           <Data>
                   <Secret>
                       <PlainValue>
MTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
KeyAlgorithm="http://www.ietf.org/keyprov/pskc#pin">
               <Usage>
                   <ResponseFormat Length="4" Format="DECIMAL"/>
               </Usage>
                           <Data>
                   <Secret>
                       <PlainValue>
MTIzNA==
xmlns="urn:ietf:params:xml:ns:keyprov:pskc:1.0"
KeyId="0755225266">
               <Issuer>AnIssuer</Issuer>
               <Usage OTP="true">
                   <ResponseFormat Length="8" Format="DECIMAL"/>
               </Usage>
               <Data>
                 <Secret>
                    <EncryptedValue>
                       <xenc:EncryptionMethod
Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc"/>
                         <xenc:CipherData>
                            <xenc:CipherValue>
                  gVc5jCsntSD1rhIgwWxmWNvEIkpTgn0E6+OH5mDPAok=
                             </xenc:CipherValue>
                         </xenc:CipherData>
                     </EncryptedValue>
                     <ValueMAC>JIOeKMISfMTy7og7Saq0CZrLdfE=</ValueMAC>
                 </Secret>
                <Counter>
                 <PlainValue>0</PlainValue>
                </Counter>
               </Data>
Version="1.0">
     <pskc:EncryptionKey>
       <pskc:DerivedKey Id="#Passphrase1">
         <pskc:CarriedKeyName>Passphrase1</pskc:CarriedKeyName>
         <pskc:KeyDerivationMethod
Algorithm=
KeyId="0755225266">
             <pskc:Issuer>AnIssuer</pskc:Issuer>
             <pskc:Usage OTP="true">
                 <pskc:ResponseFormat Length="6" Format="DECIMAL"/>
             </pskc:Usage>
             <pskc:Data>
                 <pskc:Secret>
                     <pskc:EncryptedValue Id="ED">
                         <xenc:EncryptionMethod Algorithm=
                         "http://www.w3.org/2001/04/xmlenc#kw-aes128"/>
                         <xenc:CipherData>
                          <xenc:CipherValue>rf4dx3rvEPO0vKtKL14NbeVu8nk=
                          </xenc:CipherValue>
                         </xenc:CipherData>
                     </pskc:EncryptedValue>





                 </pskc:Secret>
                 <pskc:Counter>
                     <pskc:PlainValue>0</pskc:PlainValue>
                 </pskc:Counter>
             </pskc:Data>
Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
KeyId="0755225266">
xmlns="urn:ietf:params:xml:ns:keyprov:pskc:1.0"
KeyAlgorithm="http://www.ietf.org/keyprov/
Max="8" Format="DECIMAL"/>
Length="8" Format="DECIMAL"/>
Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc"/>
                         <xenc:CipherData>
                             <xenc:CipherValue>
                     gVc5jCsntSD1rhIgwWxmWNvEIkpTgn0E6+OH5mDPAok=
                             </xenc:CipherValue>
                         </xenc:CipherData>
                     </EncryptedValue>
                     <ValueMAC>JIOeKMISfMTy7og7Saq0CZrLdfE=</ValueMAC>
                 </Secret>
                   <Counter>
                       <PlainValue>0</PlainValue>
                   </Counter>
xmlns="urn:ietf:params:xml:ns:keyprov:pskc:1.0"
KeyId="0755225266">
               <Issuer>AnIssuer</Issuer>
               <Usage OTP="true">
                   <ResponseFormat Length="6" Format="DECIMAL"/>
               </Usage>
               <Data>
                 <Secret>
                     <EncryptedValue>
                         <xenc:EncryptionMethod
Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc"/>
                         <xenc:CipherData>
                             <xenc:CipherValue>
                     gVc5jCsntSD1rhIgwWxmWNvEIkpTgn0E6+OH5mDPAok=
                             </xenc:CipherValue>
                         </xenc:CipherData>
                     </EncryptedValue>
                     <ValueMAC>JIOeKMISfMTy7og7Saq0CZrLdfE=</ValueMAC>
                 </Secret>
                 <Time>
                     <PlainValue>0</PlainValue>
                 </Time>
                 <TimeInterval>
                     <PlainValue>30</PlainValue>
                 </TimeInterval>
xmlns="urn:ietf:params:xml:ns:keyprov:pskc:1.0">
           <KeyProperties ID="KPID1"
KeyAlgorithm="http://www.ietf.org/keyprov/pskc#hotp">
                   <Issuer>Issuer</Issuer>
                   <Usage OTP="true">
                           <ResponseFormat Length="8"
Format="DECIMAL"/>
KeyId="987654321">
               <Data>
                   <Secret>
                       <PlainValue>
MTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
KeyId="987654322">
               <Data>
                   <Secret>
                       <PlainValue>





MTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
