S=1 indentifies a set of parameters standardized by ITU; while
S=0 identifies a non-standardized set of parameters.

V=0 only parameter value, V=1 parameter value and variance.

ParamSource = 1.
         Identify the ITU document that defines the following parameter
         list.  Currently [ITU.G697] defines this value 1 for this
         parameter.
ParamSource = 0 (proposal).
         List of parameters within [I-D.ietf-ccamp-wson-iv-info].
         [Editor Note: Value to be confirmed through ITU Liaison].
W = 0.  Wavelength Dependency flag.  There is no wavelength
W = 1.  Wavelength Dependency flag.  There is wavelength
