call-id   =  "call-id" EQUAL DQUOTE callid DQUOTE
from-tag  =  "from-tag" EQUAL token
to-tag    =  "to-tag" EQUAL token

version="1.0">
version="1.0">
xmlns="urn:ietf:params:xml:ns:kpml"
elementFormDefault="qualified"
attributeFormDefault="unqualified">
use="optional"/>
use="optional"/>
use="optional"/>
use="optional"/>
use="optional"/>
use="optional"/>
use="optional"/>
use="optional"/>
content="text/html;charset=iso-8859-1"/>
version="1.0">
version="1.0">
version="1.0">
digits="94015551212" tag="RI-number"/>
version="1.0">
v=0
o=UserA 2890844526 2890844526 IN IP4 client.subA.example.com
s=Session SDP
c=IN IP4 client.subA.example.com
t=3034423619 0
m=audio 49170 RTP/AVP 0
a=rtpmap:0 PCMU/8000


v=0
o=UserB 2890844527 2890844527 IN IP4 client.subB.example.com
s=Session SDP
c=IN IP4 client.subB.example.com
t=3034423619 0
m=audio 3456 RTP/AVP 0
a=rtpmap:0 PCMU/8000

version="1.0">
version="1.0">
version="1.0">
digits="***"/>
