nbn_nss     = prefix "-" nbn_string

prefix      = cc_prefix / reg_prefix

cc_prefix   = iso_cc *( ":" subspc )

iso_cc      = 2ALPHA
                       ; country code as assigned by ISO 3166, part 1 --
                       ; identifies the national library
                       ; to which the branch is delegated

subspc      = 1*ALPHANUM
                       ; as assigned by the respective national library

reg_prefix  = 3*ALPHANUM
                       ; as assigned by the Library of Congress --
                       ; identifies a trusted third party
                       ; to which the bracnh is delegated

nbn_string  = <specific per prefix>
                       ;  must follow RFC 3986 <path-rootless> syntax

