Remote-Party-ID    = "Remote-Party-ID" ":" [display-name]
                                "<" addr-spec ">" *(";" rpi-token)

rpi-token          = rpi-screen | rpi-type | other-rpi-token

rpi-screen         = "rpi-screen" "=" ("no" | "yes" )

rpi-type           = "rpi-type" "=" 1#token

other-rpi-token    = token ["=" (token | quoted-string)]

other-user         = token  | "private"

Anonymity       = "Anonymity" ":"  1#privacy-tag
privacy-tag     = "full" | "uri" | "name" | "ipaddr" | "off"

user=private>
