Prid=1, DistProtocol=eBGP+OSPF, MaxRoutes=500.000, MaxVrfs=500,
ORFMgt = False;
Prid=1, TunnelSupport=mplsTunnel, Type=network;
Prid=2, TunnelSupport=mpls      , Type=customer;
Prid=3, TunnelSupport=none      , Type=customer;
Prid=1, Name="Customer", Capability=ppvpn2547IfCaps.2;
Prid=2, Name="Customer", Capability=ppvpn2547IfCaps.3;
Prid=3, Name="Network",  Capability=ppvpn2547IfCaps.1;
Prid=1, Roles=VPN1,      CapSetName="Customer", IfIndex=1;
Prid=2, Roles=VPN1,      CapSetName="Customer", IfIndex=2;
Prid=3, Roles=VPN1+VPN2, CapSetName="Customer", IfIndex=3;
Prid=4, Roles=SP,        CapSetName="Network",  IfIndex=4;
Prid=1, Roles=VPN1,      IfName="Customer", VrfId=0,
Descr="Intranet", RD=XX, MaxRoutes=1000;
Prid=2, Roles=VPN1+VPN2, IfName="Customer", VrfId=1,
Descr="Extranet", RD=YY, MaxRoutes=2000;
Prid=1, Type=both  , VrfId=0, RT="VPN1",
Decsr="CUG VPN1";
Prid=2, Type=both  , VrfId=1, RT="VPN1",
Decsr="CUG VPN1";
Prid=3, Type=import, VrfId=1, RT="VPN2-Hub", 
Descr="Hub Site VPN2";
Prid=1, IfIndex=1, VpnClassif=enterprise, 
RouteDistProtocol="OSPF";
Prid=2, IfIndex=2, VpnClassif=enterprise, 
RouteDistProtocol="eBGP";
Prid=3, IfIndex=3, VpnClassif=enterprise, 
RouteDistProtocol="eBGP";
Prid=1, VrfId=0, PeerRole=PE, AddrType=Ipv4, Addr=192.123.122.1;
Prid=2, VrfId=0, PeerRole=PE, AddrType=Ipv4, Addr=192.123.145.5;
Prid=3, VrfId=0, PeerRole=PE, AddrType=Ipv4, Addr=192.123.12.34;
Prid=4, VrfId=1, PeerRole=PE, AddrType=Ipv4, Addr=192.156.78.25;
Prid=5, VrfId=1, PeerRole=PE, AddrType=Ipv4, Addr=192.123.9.125;
Id=1, Selection=ppvpn2547Selection,
Usage=ppvpn2547RouteCountUsage, 
Threshold=ppvpn2547Threshold;
Id=2, Selection=ppvpn2547Selection,
Usage=ppvpn2547LabelCountUsage, 
Threshold=ppvpn2547Threshold;
Prid=1, Vrf=ppvpn2547Vrf.1;
Prid=2, Vrf=ppvpn2547Vrf.2;
Prid=1, Thresh=10.000;
Id=1, Sel=ppvpn2547Selection.1, Usage=ppvpn2547RouteCountUsage,
Interval=10, Threshold=ppvpn2547Treshold.1, Flags=threshold;
Id=2, Sel=ppvpn2547Selection.2, Usage=ppvpn2547LabelCountUsage,
Interval=20, Threshold=NULL,                Flags=changeOnly;
