timeout = (average-interval ^ 2) * count / period              (1)


timeout = MAX[min-interval, (average-interval ^ 2) * count / period] (2)


   min-interval:  The value of the "min-interval" parameter conveyed in
      the Subscription-State header field, in seconds.

   The formula in (2) makes sure that for all the possible values of the
   "min-interval" and "average-interval" parameters, with "average-
   interval" > "min-interval", the timeout never results in a lower
   value than the value of the "min-interval" parameter.

   In some situation it may be beneficial for the notifier to achieve an
   adaptive minimum rate in a different way than the algorithm detailed
   in this document allows.  However, the notifier MUST comply with any
   "min-interval" or "max-interval" parameters that have been
   negotiated.


event-param    =/  min-interval-param
subexp-params  =/  min-interval-param
min-interval-param =   "min-interval" EQUAL delta-seconds

event-param    =/  max-interval-param
subexp-params  =/  max-interval-param
max-interval-param =   "max-interval" EQUAL delta-seconds

event-param    =/  average-interval-param
subexp-params  =/  average-interval-param
average-interval-param =   "average-interval" EQUAL delta-seconds


