M = { (Timestamp B(E0) - Timestamp A),  
                 (Timestamp B(E1) - Timestamp A), ... 
                 (Timestamp B(En) - Timestamp A) } 
      
M = {L(I,E1),L(I,E2), à, L(I,En)} 
      
Result = MAX(M) û MIN(M) 
      
