SKEYSEED = prf(SK_d, KE  | Ni | Nr | KE(1) | Ni(1) | Nr(1) ...
                                         | KE(n) | Ni(n) | Nr(n))

KEYMAT = prf+ (SK_d, KE  | Ni | Nr | KE(1) | Ni(1) | Nr(1) ...
                                         | KE(n) | Ni(n) | Nr(n))

