header = attr ":" value "\n"
attr = token
value = rest-of-line
dictionary-client-id = 1*BASE64URLDIGIT
dictionary-server-id = 1*BASE64URLDIGIT
payload = 1*PAYLOADBYTE
vcdiff-payload = 1*PAYLOADBYTE
partial-url = HTTP_url | abs_path [ "?" query ]

dictionary-metadata = 1*dictionary-header "\n"
dictionary-header = "domain" ":" value "\n"
portlist = 1#portnum
portnum = 1*DIGIT

definition = dictionary-metadata payload

header = "Avail-Dictionary" ":" 1#dictionary-client where dictionary-
sdch-not-used-header = "X-SDCH-Encoding" ":" "0"

dictionary-compression-response = dictionary-server-id "\0" vcdiff-
