play=http://audio.example.net/allcircuitsbusy.g711

play=file://fileserver.example.net/geminii/yourHoroscope.wav


ANNC-URL        = sip-ind annc-ind "@" hostport
                       annc-parameters uri-parameters

sip-ind         = "sip:" / "sips:"
annc-ind        = "annc"

annc-parameters = ";" play-param [ ";" content-param ]
                                    [ ";" delay-param]
                                    [ ";" duration-param ]
                                    [ ";" repeat-param ]
                                    [ ";" locale-param ]
                                    [ ";" variable-params ]
                                    [ ";" extension-params ]

play-param      = "play=" prompt-url

content-param   = "content-type=" MIME-type
delay-param     = "delay=" delay-value

delay-value     = 1*DIGIT

duration-param  = "duration=" duration-value

duration-value  = 1*DIGIT

repeat-param    = "repeat=" repeat-value

repeat-value    = 1*DIGIT | "forever"

locale-param    = "locale=" token
                        ; per RFC3066, usually
                        ; ISO639-1_ISO3166-1
                        ; e.g., en, en_US, en_UK, etc.

variable-params = param-name "=" variable-value

param-name      = "param" DIGIT ; e.g., "param1"

variable-value  = 1*(ALPHA | DIGIT)

extension-params = extension-param [ ";" extension-params ]

extension-param  = token "=" token

play=file://fs.example.net/clips/my-intro.dvi; \
content-type=video/mpeg%3bencode%d3314M-25/625-50
prompt-url      = "/provisioned/" announcement-id

announcement-id = 1*(ALPHA | DIGIT)

voicexml=http://vxmlserver.example.net/cgi-bin/script.vxml

DIALOG-URL        = sip-ind dialog-ind "@" hostport
                          dialog-parameters

sip-ind           = "sip:" / "sips:"
dialog-ind        = "dialog"

dialog-parameters = ";" dialog-param [ vxml-parameters ]
                                        [ uri-parameters ]

dialog-param      = "voicexml=" dialog-url

vxml-parameters   = vxml-param [ vxml-parameters ]

vxml-param        = ";" vxml-keyword "=" vxml-value

vxml-keyword      = token

vxml-value        = token

CONF-URL        = sip-ind conf-ind "=" instance-id "@" hostport
                     [ uri_parameters ]

sip-ind         = "sip:" / "sips:"

conf-ind        = "conf"

instance-id     = token

