S2=S1+L; S3=S2+L, ... 
         
         
                       |============ |            
                       |             |           
                       | <--- L ---> |        
                       |             |         
                       |   |============ |      
                       |   |             | 
                       |   | <--- L ---> |     
                       |   |             |           
                       |   |   |============ |  
                       |   |   |             |              
                       |   |   | <--- L ---> |  
                       |   |   |             |      
                       |   |   |   |============ |  
                       |   |   |   |             |    
                       |   |   |   | <--- L ---> | 
                      S1   |   |   |             | 
                           |   |   |             | 
                           |   |   |             | 
                          S2   |   |             | 
                               |   |             | 
                               |   |             | 
                              S3   |             | 
                                   |             | 
                                   |             | 
                                  S4 
         
               Figure 5 : Sliding eoEnergyParametersIntervalMode 
         
