type=6 (Mandatory Object missing) and Error-value=TBD (FEC object
value=TBD (FEC object missing).

Error-value = TBD :                 FEC object missing
Error-value = TBD :                 SR capability was
                                                     not advertised

