XRT = {SN, SAN-ID, RCVF, CSR+Q, MTUR, LRT}
LRT = For each node: {ADDR,NAME,CAPA,LA,SRQR} }
		    Part-1: PacketWay EEP messages
		    -------------------------------


T=0: Optional (may drop this field if this OH-TYPE is unknown)
T=1: Mandatory (should not process this message if this OH-TYPE is unknown)

C=0: More trailer fields follow
C=1: End of Optional fields group (OH or OT)

L=4    #1       #2       #3       #4    padding  padding
SAN-ID   = (as received in RT)
RCVF     = (RCVF, me)
CSR      = ( (me->Sender-of-RT), CSR )
MinMTU   = Min(my-MTU, MinMTU)
Local-RT = (as received in RT)

e=0: Big-Endian order
e=1: Little-Endian order

CSR=(A:Rab->Rac,*:Rac->Rca,C:Rca->Rcd,*:Rcd->Rdc),
E=3 (0b0011) indicates that all the data is 64-bit, in Big Endian order. 
