SMS=+1-408-555-123456

value             = message-centre-id
message-centre-id = ["+"] phone-number
phone-number     = 1*phonedigit
phonedigit       = digit / "-" / "."
digit            = "0" / "1" / "2" / "3" / "4" / "5" /
                            "6" / "7" / "8" / "9"

SMS=+1-408-555-1234/VIA=+358-50-123-1234

value        = network-type
network-type = "GSM" / other-type
other-type   = string

SMS=+1-408-555-1234/VIA=+358-50-123-1234/NET=GSM

value             = message-centre-id
message-centre-id = ["+"] phone-number
phone-number      = 1*phonedigit
phonedigit        = digit / "-" / "."
digit             = "0" / "1" / "2" / "3" / "4" / "5" /
                             "6" / "7" / "8" / "9"

value        = network-type
network-type = "GSM" / other-type
other-type   = string

