targetNamespace="urn:ietf:params:xml:ns:pidf:geopriv10:dynamic10"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

substitutionGroup="gml:_Geometry"/>

type="gml:DirectionPropertyType"/>
type="gml:MeasureType"/>
type="gml:DirectionPropertyType"/>
type="gml:MeasureType"/>
srsName="urn:ogc:def:crs:EPSG::4979">

uom="urn:ogc:def:uom:EPSG::9102">
uom="urn:ogc:def:uom:EPSG::9102">
uom="urn:ietf:params:ns:geopriv:dynamic:uom#mps">
uom="urn:ogc:def:uom:EPSG::9102">
uom="urn:ogc:def:uom:EPSG::9202">
uom="urn:ietf:params:ns:geopriv:dynamic:uom#mps2">
content="text/html;charset=iso-8859-1"/>
