Options = (V6-bit|E-bit|R-bit)
Type = 2                     ;connects to N3
Metric = 1                   ;cost to N3
Options = (V6-bit|E-bit|R-bit)
               Attached Router = 192.0.2.4    ;Router ID
               Attached Router = 192.0.2.1    ;Router ID
               Attached Router = 192.0.2.2    ;Router ID
               Attached Router = 192.0.2.3    ;Router ID

                        Network-LSA for Network N3

Metric = 4                  ;maximum to components
PrefixLength = 48
PrefixOptions = 0
Options = (V6-bit|E-bit|R-bit)  ;RT7's capabilities
Metric = 14                     ;cost to RT7
Metric = 2
PrefixLength = 40
PrefixOptions = 0
Options = (V6-bit|E-bit|R-bit)
PrefixLength = 56
PrefixOptions = 0
PrefixLength = 56           ;N3's prefix
PrefixOptions = 0
Metric = 0
PrefixLength = 56           ;N4's prefix
PrefixOptions = 0
Metric = 2                  ;N4 interface cost
