m = <media> : [<port>] : <transport> : <fmt list>
                 [& a = <attribute> [: <value list>]]
streamURI     = "stream://" connection "/" sessionname "#"
                       [time "&"] media *["&" media]

connection    = address [":" port]
address       = addressnumber | addressname
addressnumber = digits "." digits "." digits "." digits
digits        = 1*digit
addressname   = *[domainlevel "."] toplevel
domainlevel   = alphadigit |
                       alphadigit *[alphadigit | "-"] alphadigit
toplevel      = alpha |
                       alpha *[alphadigit | "-"] alphadigit
alphadigit    = alpha | digit

sessioname    = 1*uchar

time          = "t=" starttime ":" stoptime
starttime     = digits
stoptime      = digits

media         = "m=" mediatype ":" [port] ":" transport ":" formatlist
                       *["&" attribute]
mediatype     = "audio" | "video" | "application" | "data" | "control"
transport     = 1*uchar
formatlist    = format *[":" format]
format        = 1*uchar
attribute     = "a=" attributename *[":" value]
attributename = 1*uchar
value         = 1*uchar

qos_attribute = "a=qos" ":" R_PRI ":" R_MTU ":" R_PPS ":" R_UTU ":"
                       R_CDLY ":" R_CCHG ":" R_RDLY ":" R_RCHG
R_PRI         = digits
R_MTU         = digits
R_PPS         = digits
R_UTU         = digits
R_CDLY        = digits
R_CCHG        = digits
R_RDLY        = digits
R_RCHG        = digits

