oauth_token=ab3cd9j4ks73hf7g&oauth_token_secret=xyz4992k83j47x0b

oauth_consumer_key="0685bd9184jfhq22",
oauth_token="ad180jjd733klru7",
oauth_signature_method="HMAC-SHA1",
oauth_signature="wOJIO9A2W5mFwDgiDvZbTSMK%2FPY%3D",
oauth_timestamp="137131200",
oauth_nonce="4572616e48616d6d65724c61686176",
oauth_version="1.0"

unreserved = ALPHA, DIGIT, '-', '.', '_', '~'

a=1, c=hi%20there, f=25, f=50, f=a, z=p, z=t

a=1&c=hi%20there&f=25&f=50&f=a&z=p&z=t
S = RSASSA-PKCS1-V1_5-SIGN (K, M)

oauth_consumer_key=dpf43f3p2l4k3l03&oauth_signature_method=PLAINTEXT&
oauth_signature=kd94hf93k423kf44%26&oauth_timestamp=1191242090&
oauth_nonce=hsu94j3884jdopsl&oauth_version=1.0

oauth_token=hh5s93j4hdidpola&oauth_token_secret=hdhd0244k9j7ao03
oauth_callback=http%3A%2F%2Fprinter.example.com%2Frequest_token_ready

oauth_token=hh5s93j4hdidpola

oauth_consumer_key=dpf43f3p2l4k3l03&
oauth_token=hh5s93j4hdidpola&oauth_signature_method=PLAINTEXT&
oauth_signature=kd94hf93k423kf44%26hdhd0244k9j7ao03&
oauth_timestamp=1191242092&
oauth_nonce=dji430splmx33448&oauth_version=1.0

oauth_token=nnch734d00sl2jdk&oauth_token_secret=pfkkdhi9sl3r4s00

e=kllo9940pd9333jh&oauth_signature_method=HMAC-SHA1&oauth_timesta
mp=1191242096&oauth_token=nnch734d00sl2jdk&oauth_version=1.0&size
oauth_consumer_key="dpf43f3p2l4k3l03",
oauth_token="nnch734d00sl2jdk",
oauth_signature_method="HMAC-SHA1",
oauth_signature="tR3%2BTy81lMeYAr%2FFid0kMTYa%2FWM%3D",
oauth_timestamp="1191242096",
oauth_nonce="kllo9940pd9333jh",
oauth_version="1.0"

oauth_consumer_key=dpf43f3p2l4k3l03&oauth_token=nnch734d00sl2jdk&
oauth_signature_method=HMAC-SHA1&
oauth_signature=tR3%2BTy81lMeYAr%2FFid0kMTYa%2FWM%3D&
oauth_timestamp=1191242096&
oauth_nonce=kllo9940pd9333jh&oauth_version=1.0

