Version = 0

E = echo packet
I = information packet (see section 2.1.3)
R = request packet = 0 / response packet = 1
S = singleton packet, used for one-way probes, not echoed






  
   
Version = 4

IHL = 5

Identification = 0

Flags = DF

