inetIpv6NetworkSyntax = vSixPart ":" vSixPart ":" vSixPart 
            ":" vSixPart ":" vSixPart ":" vSixPart ":" vSixPart ":" 
            vSixPart "/" vSixPrefix 
      
vSixPart = 4*4nibblePart 
      
nibblePart = hexadecimal digit between "0" and "F" inclusive 
      
vSixPrefix = decimal value between "1" and "128" inclusive, 
            with the non-affective leading zeroes removed 
      
cn=3ffe:ffff:0000:0000:0000:0000:0000:0000/32, 
cn=inetResources,dc=ip6,dc=arpa 
dc=example,dc=net" 
      
