PA      = protocol authority for the user plane or the control   
               plane protocol ID 
                             0       = PPP DLL. Reserved for MPLS/PW     
                                       control protocol identification. 
                             1       = ISO NLPID (other than 0x80) 
                             2       = IP protocol number 
                             3       = Ethertype 
                             4       = SNAP (ISO NLPID=0x80, e.g., IEEE   
                                       802.1 MAC type) 
                             5-15    = reserved 
PA=1: ISO NLPID value other than 0x80 (32 bits) 
      
      0                   1                   2                   3 
      0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 
PA=2, IP protocol number (32 bits) 
    
   
   
      
      0                   1                   2                   3 
      0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 
PA=3: Ethertypes (32 bits) 
      
      0                   1                   2                   3 
      0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 
PA=4: SNAP protocols such as 802.1 MAC types and private protocols 
