Reverse-path = Path

Forward-path = Path

Path = "<" [ A-d-l ":" ] Mailbox ">"

A-d-l = At-domain *( "," A-d-l )    ; Note that this form, the
                                 so-called "source route", MUST BE
								 accepted, SHOULD NOT be generated,
								 and SHOULD be ignored.

At-domain = "@" Domain

Mail-parameters = *( SP Keyword "=" Argument )

Rcpt-parameters =  *( SP Keyword "=" Argument )

Keyword  = Ldh-str
Argument = Atom

Domain = sub-domain 1*("." sub-domain) / address-literal

sub-domain = let-dig *(ldh-str)
address-literal = "[" IPv4-address-literal / 
                  IPv6-address-literal / General-address-literal "]"
IPv4-address-literal = snum 3*3("." snum)
IPv6-address-literal = "IPv6" SP IPv6-addr-string
IPv6-addr-string = String         ; IPv6 address in standard form
                                       [IPv6AddrSpec].  Since this
									   form uses colon characters,
									   the String will actually need
									   to be quoted in all cases.
General-address-literal = Standardized-tag SP String
Standardized-tag = Ldh-str        ; Specified in a
                                       standards-track RFC 
                                       and registered with IANA
snum = 1*3Digit                   ; representing a decimal integer
                                       value in the range 0 through 255 
let-dig = Alpha / Digit
ldh-str = *( Alpha / Digit / "-" ) let-dig

Mailbox = Local-part "@" Domain

Local-part = Dot-string / Quoted-string

String = Atom / Quoted-string

special = <<Msg-fmt-special>> /     [[placeholder, see above]]
             the control characters (ASCII codes 0 through 31
			 inclusive and 127)

Return-path-line = "Return-Path:" FWS Reverse-path CRLF

Time-stamp-line = "Received:" FWS Stamp CRLF

Stamp = From-domain By-domain Opt-info ";"
          Daytime

From-domain = "FROM" FWS Extended-Domain FWS 

By-domain = "BY" FWS Extended-Domain FWS

Extended-Domain = Domain / 
           ( Domain FWS "(" Address-literal ")" ) /
           Address-literal

Opt-info = [Via] [With] [ID] [For]

Via = "VIA" FWS Link FWS 

With = "WITH" FWS Protocol FWS 

ID = "ID" FWS String FWS 

For = "FOR" FWS Path FWS 

Link = <<>> / Addtl-Link
Addtl-Link = Atom       ; Additional standard names for links are
						  registered with the Internet Assigned
						  Numbers Authority (IANA).
						  SMTP servers SHOULD NOT use unregistered
						  names. 
Protocol = "ESMTP" / "SMTP" / Attdl-Protocol
Attdl-Protocol = Atom    ; Additional standard names for protocols
                           are registered with the Internet Assigned
						   Numbers Authority (IANA).  SMTP servers
						   SHOULD NOT use unregistered names.

Daytime =  FWS Date FWS Time

Date = DD FWS Mon FWS YYYY

       Note that the earlier form, which permits two-digit years, has
       been deprecated.  SMTP systems MUST use four-digit years.

Time = HH ":" MM ":" SS  FWS  Zone

DD = 1*2Digit           ; the one or two decimal integer day of the
					      month in the range 1 to 31.

Mon = "JAN" | "FEB" | "MAR" | "APR" | "MAY" | "JUN" |
             "JUL" | "AUG" | "SEP" | "OCT" | "NOV" | "DEC"

YYYY = 4*4Digit         ; the four decimal integer year in the range
                          0000 to 9999. 

HH = 2*2Digit           ; the two decimal integer hour of the day in
                          the range 00 to 24.

MM = 2*2Digit            ; the two decimal integer minute of the hour
                           in the range 00 to 59.

SS = 2*2Digit ["." 1*Digit]
                         ; the two decimal integer second of the
						   minute in the range 00 to 59, with
						   optional fractional seconds.

Zone = ( "+" / "-" ) 4*4Digit [ SP "(" String ")" ]
                         ; A four digit, signed time zone offset,
						   such as -0600 for US Eastern Standard
						   Time.  This may be supplemented by a time
						   zone name in parentheses, e.g., "-0800
						   (PDT)".  See  ##___ for additional
						   discussion. 

          Note that there is no default; time zone information
          is required and MUST be supplied.




		                       
