HD = ------------------------------------------
        log(maximum number of allocatable objects)

HDmin =  ------------------------------------------ = 0
            log(maximum number allocatable of objects)

HDmax =  ------------------------------------------ = 1
            log(maximum number allocatable of objects)


L = -------------------------------------
       maximum number of addressable objects
   

H = ------------------------
            available bits

H = -------------------------------------------
       log2(maximum number of allocatable objects)


                                     log10(X)
H = ----------------------------------------------
       log10(maximum number of allocatable objects)

                                     log(X)
H = --------------------------------------------
       log(maximum number of allocatable objects)


Hmin = 0
Hmax = log10(2) = 0.3010

