SET_TO_SERVER_TIME4 = 0,
SET_TO_CLIENT_TIME4 = 1
LAYOUT4_NFSV4_1_FILES   = 1,
LAYOUT4_OSD2_OBJECTS    = 2,
LAYOUT4_BLOCK_VOLUME    = 3
LAYOUTIOMODE4_READ          = 1,
LAYOUTIOMODE4_RW            = 2,
LAYOUTIOMODE4_ANY           = 3
DENY=NONE) to parallel the NFS version 3 protocol's practice for
modified = TRUE;
sc = sc + 1;
time_modify = time_metadata = current_time;
STATUS4_FIXED = 1,
STATUS4_VERSIONED = 2,
STATUS4_UPDATED = 3,
STATUS4_WRITABLE = 4,
STATUS4_ABSENT = 5
FILEDS4_SIMPLE  = 1,
FILEDS4_COMPLEX = 2
STRIPE4_SPARSE = 1,
STRIPE4_DENSE = 2
ds_fh_list = [<6, 1, 0x17>, <1, 0, 0x12>, <5, 0, 0x22>,
                      <2, 0, 0x13>, <3, 0, 0x14>, <4, 0, 0x15>]

nfl_stripe_indices = [5, 2, 4, 0, 1, 3]

stripe_width = stripe_unit_size * N;
         where N = number of <data server, filehandle pairs>
             in flattened nfl_ds_fh_list

data_file_offset = floor(file_offset / stripe_width)
         * stripe_unit_size
         + file_offset % stripe_unit_size

data_server_idx = floor(file_offset / stripe_unit_size) mod N

UNCHECKED4      = 0,
GUARDED4        = 1,
EXCLUSIVE4      = 2
OPEN4_NOCREATE  = 0,
OPEN4_CREATE    = 1
NFS_LIMIT_SIZE          = 1,
NFS_LIMIT_BLOCKS        = 2
OPEN_DELEGATE_NONE      = 0,
OPEN_DELEGATE_READ      = 1,
OPEN_DELEGATE_WRITE     = 2,
OPEN_DELEGATE_NONE_EXT  = 3 /* new to v4.1 */
CLAIM_NULL              = 0,
CLAIM_PREVIOUS          = 1,
CLAIM_DELEGATE_CUR      = 2,
CLAIM_DELEGATE_PREV     = 3,

CLAIM_FH                = 4, /* new to v4.1 */

CLAIM_DELEG_CUR_FH      = 5, /* new to v4.1 */

CLAIM_DELEG_PREV_FH     = 6 /* new to v4.1 */
WND4_NOT_WANTED         = 0,
WND4_CONTENTION         = 1,
WND4_RESOURCE           = 2,
WND4_NOT_SUPP_FTYPE     = 3,
WND4_WRITE_DELEG_NOT_SUPP_FTYPE = 4,
WND4_NOT_SUPP_UPGRADE   = 5,
WND4_NOT_SUPP_DOWNGRADE = 6,
WND4_CANCELED           = 7,
WND4_IS_DIR             = 8
RPC_GSS_SVC_NONE        = 1,
RPC_GSS_SVC_INTEGRITY   = 2,
RPC_GSS_SVC_PRIVACY     = 3
UNSTABLE4       = 0,
DATA_SYNC4      = 1,
FILE_SYNC4      = 2
CDFC4_FORE              = 0x1,
CDFC4_BACK              = 0x2,
CDFC4_FORE_OR_BOTH      = 0x3,
CDFC4_BACK_OR_BOTH      = 0x7
CDFS4_FORE        = 0x1,
CDFS4_BACK        = 0x2,
CDFS4_BOTH        = 0x3
GDD4_OK         = 0,
GDD4_UNAVAIL    = 1
SECINFO_STYLE4_CURRENT_FH       = 0,
SECINFO_STYLE4_PARENT           = 1
OP_CB_GETATTR           = 3,
OP_CB_RECALL            = 4,
OP_CB_ILLEGAL           = 10044
LAYOUTRECALL4_FILE = 1,
LAYOUTRECALL4_FSID = 2,
LAYOUTRECALL4_ALL  = 3
NOTIFY4_CHANGE_CHILD_ATTRS = 0,
NOTIFY4_CHANGE_DIR_ATTRS = 1,
NOTIFY4_REMOVE_ENTRY = 2,
NOTIFY4_ADD_ENTRY = 3,
NOTIFY4_RENAME_ENTRY = 4,
NOTIFY4_CHANGE_COOKIE_VERIFIER = 5
