charset=US-ASCII"".

boundary="---- next message ----"

id="oc=jpbe0M2Yt4s@thumper.bellcore.com"

id="oc=jpbe0M2Yt4s@thumper.bellcore.com";
number=2

id="oc=jpbe0M2Yt4s@thumper.bellcore.com"

number=1; total=2
id="ABC@host.com"; number=2; total=2

access-type=local-file;
name="/u/nsb/Me.gif"
site="thumper.bellcore.com"; mode="image";
access-type=ANON-FTP; directory="pub";
expiration="Fri, 14 Jun 1991 19:13:14 -0400 (EDT)"

name="/u/nsb/writing/rfcs/RFC-MIME.ps";
site="thumper.bellcore.com";
expiration="Fri, 14 Jun 1991 19:13:14 -0400 (EDT)"
access-type=mail-server
server="listserv@bogus.bitnet";
expiration="Fri, 14 Jun 1991 19:13:14 -0400 (EDT)"

boundary=unique-boundary-1

