QNAME= d.b.c.example. QTYPE=A

RCODE=NXDOMAIN
QNAME= d.b.c.example. QTYPE=A

RCODE=NXDOMAIN
QNAME= c.a.a.example. QTYPE=A

RCODE=NXDOMAIN
QNAME= e.example. QTYPE=A

RCODE=NXDOMAIN
QNAME= g.example. QTYPE=A

RCODE=NXDOMAIN
QNAME= d.b.c.example. QTYPE=A

RCODE=ANSWER
QNAME= #.c.example. QTYPE=A

RCODE=NXDOMAIN                                       ; Black hat answer !!!!
