authority="com" registryType="dreg2"
entityClass="domain-handle" entityName="tcs-com-1" >

authority="com" registryType="dreg2"
entityClass="contact-handle" entityName="beb140">
authority="com" registryType="dreg2"
entityClass="organization-handle" entityName="dch-01">
authority="com" registryType="dreg2"
entityClass="contact-handle" entityName="beb140" >
authority="com" registryType="dreg2"
entityClass="organization-handle" entityName="dch-01">
authority="com" registryType="dreg2"
entityClass="organization-handle" entityName="dch-01" >
authority="com" registryType="dreg2"
entityClass="domain-handle" entityName="tcs-com-1" >

authority="com" registryType="dreg2"
entityClass="organization-handle" entityName="bigco-001">
authority="com" registryType="dreg2"
entityClass="organization-handle" entityName="dch-01">
authority="com" registryType="dreg2"
entityClass="organization-handle" entityName="bigco-001" >
authority="com" registryType="dreg2"
entityClass="organization-handle" entityName="dch-01">
authority="com" registryType="dreg2"
entityClass="organization-handle" entityName="dch-01" >
authority="iana.org" registryType="dreg2"
entityClass="domain-handle" entityName="example-com-1">
authority="iana.org" registryType="dreg2"
entityClass="host-handle" entityName="research7" />
authority="iana.org" registryType="dreg2"
entityClass="host-handle" entityName="nsol184" />
authority="com"
registryType="dreg2"
entityClass="contact-handle"
entityName="VGRS" />
authority="iana.org" registryType="dreg2"
entityClass="contact-handle" entityName="dconrad" />
authority="iana.org" registryType="dreg2"
entityClass="host-handle" entityName="nsol184" >
authority="iana.org" registryType="dreg2"
entityClass="contact-handle" entityName="dconrad" />
authority="iana.org" registryType="dreg2"
entityClass="contact-handle" entityName="dconrad" >
authority="com" registryType="dreg2"
entityClass="org-handle" entityName="vrsn1" >
authority="com" entityClass="contact-handle"
entityName="mak21" registryType="dreg2">
language="en">Mark Kosters</iris:displayName>
authority="iana.org" registryType="dreg2"
entityClass="registration-authority" entityName="iana" >
authority="iana.org" registryType="dreg2"
entityClass="iris" entityName="id" />
authority="com" registryType="dreg2"
entityClass="registration-rule" entityName="rule1" >
registryType="urn:ietf:params:xml:ns:dreg2"
entityClass="contact-handle"
entityName="mak21" />

targetNamespace="urn:ietf:params:xml:ns:dreg2"
elementFormDefault="qualified" >

name="findRegistrarsByNameType">
base="iris:queryType">
ref="dreg:baseDomain"
minOccurs="0"
maxOccurs="1" />
name="namePart"
type="dreg:exactOrPartialMatchParameter"
minOccurs="0"
maxOccurs="1" />
name="findRegistrarsByName"
type="dreg:findRegistrarsByNameType"
substitutionGroup="iris:query" />

name="findDomainsByContactType">
base="iris:queryType">
ref="dreg:baseDomain"
minOccurs="0"
maxOccurs="1" />
ref="dreg:correspondenceSearchGroup" />
name="contactHandle"
type="dreg:exactMatchParameter" />
name="commonName"
type="dreg:exactOrPartialMatchParameter" />
type="dreg:searchRoleType"
name="role"
minOccurs="0"
maxOccurs="1" />
name="language"
type="language"
minOccurs="0"
maxOccurs="unbounded"/>
name="findDomainsByContact"
type="dreg:findDomainsByContactType"
substitutionGroup="iris:query" />

name="findDomainsByOrganizationType">
base="iris:queryType">
ref="dreg:baseDomain"
minOccurs="0"
maxOccurs="1" />
ref="dreg:correspondenceSearchGroup" />
name="organizationHandle"
type="dreg:exactMatchParameter" />
name="legalId"
type="dreg:exactMatchParameter" />
name="name"
type="dreg:exactOrPartialMatchParameter" />
name="tradingName"
type="dreg:exactOrPartialMatchParameter" />
type="dreg:searchRoleType"
name="role"
minOccurs="0"
maxOccurs="1" />
name="language"
type="language"
minOccurs="0"
maxOccurs="unbounded"/>
name="findDomainsByOrganization"
type="dreg:findDomainsByOrganizationType"
substitutionGroup="iris:query" />

name="findOrganizationsByContactType">
base="iris:queryType">
ref="dreg:correspondenceSearchGroup" />
name="contactHandle"
type="dreg:exactMatchParameter" />
name="commonName"
type="dreg:exactOrPartialMatchParameter" />
type="dreg:searchRoleType"
name="role"
minOccurs="0"
maxOccurs="1" />
name="language"
type="language"
minOccurs="0"
maxOccurs="unbounded"/>
name="findOrganizationsByContact"
type="dreg:findOrganizationsByContactType"
substitutionGroup="iris:query" />

name="findDomainsByNameType">
base="iris:queryType">
name="namePart"
type="dreg:partialMatchParameter" />
name="findDomainsByName"
type="dreg:findDomainsByNameType"
substitutionGroup="iris:query" />

name="findDomainsByIDNType">
base="iris:queryType">
name="namePart"
type="dreg:exactMatchParameter" />
name="language"
type="language"
minOccurs="0"
maxOccurs="unbounded"/>
name="findDomainsByIDN"
type="dreg:findDomainsByIDNType"
substitutionGroup="iris:query" />

name="findContactsType">
base="iris:queryType">
ref="dreg:correspondenceSearchGroup" />
name="commonName"
type="dreg:exactOrPartialMatchParameter" />
name="language"
type="language"
minOccurs="0"
maxOccurs="unbounded"/>
name="findContacts"
type="dreg:findContactsType"
substitutionGroup="iris:query" />

name="findOrganizationsType">
base="iris:queryType">
ref="dreg:correspondenceSearchGroup" />
name="name"
type="dreg:exactOrPartialMatchParameter" />
name="tradingName"
type="dreg:exactOrPartialMatchParameter" />
name="legalId"
type="dreg:exactMatchParameter" />
name="language"
type="language"
minOccurs="0"
maxOccurs="unbounded"/>
name="findOrganizations"
type="dreg:findOrganizationsType"
substitutionGroup="iris:query" />

name="findDomainsByHostType">
base="iris:queryType">
ref="dreg:baseDomain"
minOccurs="0"
maxOccurs="1" />
name="hostName"
type="dreg:exactMatchParameter" />
name="hostHandle"
type="dreg:exactMatchParameter" />
name="ipV4Address"
type="dreg:exactMatchParameter" />
name="ipV6Address"
type="dreg:exactMatchParameter" />
name="findDomainsByHost"
type="dreg:findDomainsByHostType"
substitutionGroup="iris:query" />

name="listRegistrationRulesType">
base="iris:queryType">
ref="dreg:baseDomain"
minOccurs="0"
maxOccurs="1" />
name="ruleSubject"
minOccurs="0"
maxOccurs="1">
name="listRegistrationRules"
type="dreg:listRegistrationRulesType"
substitutionGroup="iris:query" />

name="correspondenceSearchGroup">
name="eMail"
type="dreg:domainResourceParameter" />
name="city"
type="dreg:exactMatchParameter" />
name="region"
type="dreg:exactMatchParameter" />
name="postalCode"
type="dreg:exactMatchParameter" />
name="exactOrPartialMatchParameter">
ref="dreg:partialMatchGroup" />
ref="dreg:exactMatchGroup" />
name="exactMatchParameter">
ref="dreg:exactMatchGroup" />
name="partialMatchParameter">
ref="dreg:partialMatchGroup" />
name="domainResourceParameter" >
ref="dreg:exactMatchGroup" />
name="inDomain"
type="token" />
name="baseDomain"
type="normalizedString" />

name="beginsWith"/>
name="contains"/>
name="endsWith"/>
name="exactMatchGroup">
name="exactMatch"
type="normalizedString" />
name="domainType">
base="iris:resultType">
name="domainName"
type="token" />
name="idn"
type="token"
minOccurs="0"
maxOccurs="1" />
name="domainHandle"
type="dreg:normalizedStringPrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1" />
name="nameServer"
minOccurs="0"
maxOccurs="unbounded">
base="iris:entityType">
name="lame"
type="dreg:lameReasonType" />
name="registeredHost"
type="iris:entityType"
minOccurs="0"
maxOccurs="unbounded" />
name="registrant"
type="iris:entityType"
minOccurs="0"
maxOccurs="unbounded" />
name="lastRepresentativeModificationDateTime"
type="dreg:dateTimePrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1" />
name="lastRepresentativeModificationBy"
type="iris:entityType"
minOccurs="0"
maxOccurs="1" />
name="status"
minOccurs="0"
maxOccurs="1">
name="reservedDelegation"
minOccurs="0"
maxOccurs="1"
type="dreg:domainStatusType" />
name="assignedAndActive"
minOccurs="0"
maxOccurs="1"
type="dreg:domainStatusType" />
name="assignedAndInactive"
minOccurs="0"
maxOccurs="1"
type="dreg:domainStatusType" />
name="assignedAndOnHold"
minOccurs="0"
maxOccurs="1"
type="dreg:domainStatusType" />
name="revoked"
minOccurs="0"
maxOccurs="1"
type="dreg:domainStatusType" />
name="transferPending"
minOccurs="0"
maxOccurs="1"
type="dreg:domainStatusType" />
name="registryLock"
minOccurs="0"
maxOccurs="1"
type="dreg:domainStatusType" />
name="registrarLock"
minOccurs="0"
maxOccurs="1"
type="dreg:domainStatusType" />
name="other"
minOccurs="0"
maxOccurs="1"
type="dreg:domainStatusType" />
name="enhancedStatus"
minOccurs="0"
maxOccurs="1">
minOccurs="0"
maxOccurs="unbounded">
name="active"
type="dreg:enhancedStatusType" />
name="inactive"
type="dreg:enhancedStatusType" />
name="lame"
type="dreg:lameEnhancedStatusType" />
name="resolvable"
type="dreg:enhancedStatusType" />
name="dispute"
type="dreg:enhancedStatusType" />
name="renew"
type="dreg:enhancedStatusType" />
name="addPeriod"
type="dreg:enhancedStatusType" />
name="renewPeriod"
type="dreg:enhancedStatusType" />
name="autoRenewPeriod"
type="dreg:enhancedStatusType" />
name="transferPeriod"
type="dreg:enhancedStatusType" />
name="redemptionPeriod"
type="dreg:enhancedStatusType" />
name="restore"
type="dreg:enhancedStatusType" />
name="domainVariant"
type="iris:entityType"
minOccurs="0"
maxOccurs="unbounded" />
name="registrationReference"
type="iris:entityType"
minOccurs="0"
maxOccurs="1" />
name="registry"
type="dreg:hostingEntityType"
minOccurs="0"
maxOccurs="1" />
name="registrar"
type="dreg:hostingEntityType"
minOccurs="0"
maxOccurs="1" />
name="registrationServiceProvider"
type="dreg:hostingEntityType"
minOccurs="0"
maxOccurs="1" />
name="initialDelegationDateTime"
type="dreg:dateTimePrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1" />
name="lastRenewalDateTime"
type="dreg:dateTimePrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1" />
name="expirationDateTime"
type="dreg:dateTimePrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1" />
name="lastDelegationModificationDateTime"
type="dreg:dateTimePrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1" />
name="lastDelegationModificationBy"
type="iris:entityType"
minOccurs="0"
maxOccurs="1" />
name="lastLamenessCheckDateTime"
type="dreg:dateTimePrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1" />
name="lastResolutionVerificationDateTime"
type="dreg:dateTimePrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1" />
name="signatureLife"
minOccurs="0"
maxOccurs="1">
name="delegationSignerData"
minOccurs="0"
maxOccurs="unbounded">
type="unsignedShort"/>
type="unsignedByte"/>
type="unsignedByte"/>
type="hexBinary"/>
minOccurs="0">
type="unsignedShort"/>
type="unsignedByte"/>
type="unsignedByte"/>
ref="iris:seeAlso"
minOccurs="0"
maxOccurs="unbounded" />
name="domain"
type="dreg:domainType"
substitutionGroup="iris:result" />

base="iris:entityType">
name="hosting"
type="boolean" />
name="hostType">
base="iris:resultType">
name="hostHandle"
type="dreg:normalizedStringPrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1" />
name="hostName"
type="normalizedString" />
name="ipV4Address"
type="token"
minOccurs="0"
maxOccurs="unbounded" />
name="ipV6Address"
type="token"
minOccurs="0"
maxOccurs="unbounded" />
name="hostRepresentative"
type="iris:entityType"
minOccurs="0"
maxOccurs="unbounded" />
name="enhancedStatus"
minOccurs="0"
maxOccurs="1">
minOccurs="0"
maxOccurs="unbounded">
name="linked"
type="dreg:enhancedStatusType" />
name="lame"
type="dreg:lameEnhancedStatusType" />
name="resolvable"
type="dreg:enhancedStatusType" />
ref="iris:seeAlso"
minOccurs="0"
maxOccurs="unbounded" />
name="host"
type="dreg:hostType"
substitutionGroup="iris:result" />

name="organizationBaseType">
base="iris:resultType">
name="name"
type="dreg:normalizedStringPrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1"/>
name="tradingName"
type="dreg:normalizedStringPrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="unbounded"/>
name="legalId"
type="dreg:normalizedStringPrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="unbounded" />
ref="iris:seeAlso"
minOccurs="0"
maxOccurs="unbounded" />
name="organizationType">
base="dreg:organizationBaseType">
name="organizationHandle"
type="dreg:normalizedStringPrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1" />
name="enhancedStatus"
minOccurs="0"
maxOccurs="1">
minOccurs="0"
maxOccurs="unbounded">
name="linked"
type="dreg:enhancedStatusType" />
name="organization"
type="dreg:organizationType"
substitutionGroup="iris:result" />
name="contactType">
base="iris:resultType">
name="contactHandle"
type="dreg:normalizedStringPrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1" />
name="commonName"
type="dreg:normalizedStringPrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1"/>
name="language"
type="language"
minOccurs="0"
maxOccurs="1" />
name="type"
minOccurs="0"
maxOccurs="1">
name="person"
type="dreg:contactTypeType" />
name="role"
type="dreg:contactTypeType" />
name="organization"
type="dreg:contactTypeType" />
name="other"
type="dreg:contactTypeType" />
name="organization"
type="dreg:normalizedStringPrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1" />
name="translatedContact"
type="iris:entityType"
minOccurs="0"
maxOccurs="unbounded" />
name="enhancedStatus"
minOccurs="0"
maxOccurs="1">
minOccurs="0"
maxOccurs="unbounded">
name="linked"
type="dreg:enhancedStatusType" />
ref="iris:seeAlso"
minOccurs="0"
maxOccurs="unbounded" />
name="contact"
type="dreg:contactType"
substitutionGroup="iris:result" />

type="dreg:stringPrivacyType" nillable="true"
minOccurs="0" maxOccurs="unbounded"/>
type="dreg:stringPrivacyType" nillable="true"
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded">
nillable="true" minOccurs="0" maxOccurs="1"/>
nillable="true" minOccurs="0" maxOccurs="1"/>
nillable="true" minOccurs="0" maxOccurs="1"/>
type="dreg:normalizedStringPrivacyType" nillable="true"
minOccurs="0" maxOccurs="1"/>
nillable="true" minOccurs="0" maxOccurs="1"/>
nillable="true" minOccurs="0" maxOccurs="unbounded"/>
nillable="true" minOccurs="0" maxOccurs="unbounded"/>
name="registrationAuthorityType">
base="dreg:organizationBaseType">
name="registrationAuthorityHandle"
type="dreg:normalizedStringPrivacyType"
nillable="true"
minOccurs="0"
maxOccurs="1" />
name="serviceInstance"
type="iris:entityType"
minOccurs="0"
maxOccurs="1" />
minOccurs="0"
maxOccurs="3">
name="registry">
name="registrar">
name="registrationServiceProvider">
name="other">
name="domain"
type="token"
minOccurs="0"
maxOccurs="unbounded" />
name="enhancedStatus"
minOccurs="0"
maxOccurs="1">
minOccurs="0"
maxOccurs="unbounded">
name="linked"
type="dreg:enhancedStatusType" />
name="suspended"
type="dreg:enhancedStatusType" />
name="operational"
type="dreg:enhancedStatusType" />
name="registrationAuthority"
type="dreg:registrationAuthorityType"
substitutionGroup="iris:result" />

name="registrationRuleType">
base="iris:resultType">
name="ruleId"
type="dreg:ruleIdType"
minOccurs="0"
maxOccurs="1" />
name="subRuleId"
type="dreg:ruleIdType"
minOccurs="0"
maxOccurs="unbounded" />
ref="iris:seeAlso"
minOccurs="0"
maxOccurs="unbounded" />
name="ruleIdType">
base="token">
name="authority"
type="token"
use="required" />
name="registrationRule"
type="dreg:registrationRuleType"
substitutionGroup="iris:result" />

type="iris:entityType" minOccurs="0"
maxOccurs="unbounded"/>
type="iris:entityType"
minOccurs="0" maxOccurs="unbounded"/>
type="iris:entityType"
minOccurs="0" maxOccurs="unbounded"/>
type="iris:entityType" minOccurs="0"
maxOccurs="unbounded"/>
type="iris:entityType" minOccurs="0"
maxOccurs="unbounded"/>
type="iris:entityType" minOccurs="0"
maxOccurs="unbounded"/>
type="iris:entityType"
minOccurs="0" maxOccurs="unbounded"/>
type="iris:entityType" minOccurs="0"
maxOccurs="unbounded"/>
nillable="true" minOccurs="0" maxOccurs="1"/>
type="dreg:dateTimePrivacyType" nillable="true" minOccurs="0"
maxOccurs="1"/>
type="dreg:dateTimePrivacyType" nillable="true" minOccurs="0"
maxOccurs="1"/>
type="dreg:enhancedStatusType"/>
type="dreg:enhancedStatusType"/>
name="privacyLabelAttributeGroup">
name="private"
type="boolean" />
name="denied"
type="boolean" />
name="doNotRedistribute"
type="boolean" />
name="specialAccess"
type="boolean" />
name="dateTimePrivacyType">
base="dateTime">
ref="dreg:privacyLabelAttributeGroup" />
name="stringPrivacyType">
base="string">
ref="dreg:privacyLabelAttributeGroup" />
name="normalizedStringPrivacyType">
base="normalizedString">
ref="dreg:privacyLabelAttributeGroup" />
name="tokenPrivacyType">
base="token">
ref="dreg:privacyLabelAttributeGroup" />
name="domainStatusType">
name="appliedDate"
type="dateTime"
minOccurs="0"
maxOccurs="1" />
name="description"
minOccurs="0"
maxOccurs="unbounded">
base="string">
name="language"
type="language"
use="required" />
ref="dreg:privacyLabelAttributeGroup" />
name="scope"
type="string" />
name="enhancedStatusType">
name="appliedDate"
type="dateTime"
minOccurs="0"
maxOccurs="1" />
name="ticket"
type="token"
minOccurs="0"
maxOccurs="unbounded" />
name="description"
minOccurs="0"
maxOccurs="unbounded">
base="string">
name="language"
type="language"
use="required" />
name="subStatus"
minOccurs="0"
maxOccurs="1">
base="token">
type="token"
use="required"
name="authority"/>
ref="dreg:privacyLabelAttributeGroup" />
name="actor">
base="string">
value="registry"/>
value="registrar"/>
value="registrationServiceProvider"/>
name="disposition">
base="string">
value="prohibited"/>
value="pending"/>
name="scope"
type="token" />
name="contactTypeType">
name="description"
minOccurs="0"
maxOccurs="unbounded">
base="string">
name="language"
type="language"
use="required" />
ref="dreg:privacyLabelAttributeGroup" />
type="dreg:lameReasonType" />
name="searchTooWide"
type="iris:codeType"
substitutionGroup="iris:genericCode" />

name="languageNotSupportedType">
base="iris:codeType">
name="unsupportedLanguage"
type="language"
minOccurs="1"
maxOccurs="unbounded" />
name="languageNotSupported"
type="dreg:languageNotSupportedType"
substitutionGroup="iris:genericCode" />

xmlns="urn:ietf:params:xml:ns:dreg2"
authority="com" registryType="dreg2"
entityClass="domain-handle" entityName="tcs-com-1" >
authority="" registryType="dreg2"
entityClass="host-handle" entityName="research7" />
authority="" registryType="dreg2"
entityClass="host-handle" entityName="nsol184" />
authority="iana.org" registryType="dreg2"
entityClass="contact-handle" entityName="beb140" />
authority="net" registryType="dreg2"
entityClass="contact-handle"
entityName="mak21" >
xmlns="urn:ietf:params:xml:ns:dreg2"
authority="com" registryType="dreg2"
entityClass="host-handle" entityName="nsol184" >
authority="com" registryType="dreg2"
entityClass="contact-handle"
entityName="dconrad" >
authority="com" registryType="dreg2"
entityClass="contact-handle"
entityName="dconrad" />
authority="net">

