method=0b000000000001 (Binding) and is encoded into the first 16 bits
method=0b000000000001, and is encoded into the first 16 bits as
key = OpaqueString(password)
key = MD5(username ":" OpaqueString(realm) ":" OpaqueString(password))

   Where MD5 is defined in [RFC1321] and the OpaqueString profile is
   defined in [RFC8265].

   The 16-byte key is formed by taking the MD5 hash of the result of
   concatenating the following five fields: (1) the username, with any
   quotes and trailing nulls removed, as taken from the USERNAME
   attribute (in which case OpaqueString has already been applied); (2)
   a single colon; (3) the realm, with any quotes and trailing nulls
   removed and after processing using OpaqueString; (4) a single colon;
   and (5) the password, with any trailing nulls removed and after
   processing using OpaqueString.  For example, if the username was
   'user', the realm was 'realm', and the password was 'pass', then the
   16-byte HMAC key would be the result of performing an MD5 hash on the
   string 'user:realm:pass', the resulting hash being
   0x8493fbc53ba582fb4c044c456bdc40eb.

   The structure of the key when used with long-term credentials
   facilitates deployment in systems that also utilize SIP.  Typically,
   SIP systems utilizing SIP's digest authentication mechanism do not
   actually store the password in the database.  Rather, they store a
   value called H(A1), which is equal to the key defined above.

   When a PASSWORD-ALGORITHM is used, the key length and algorithm to
   use are described in Section 17.5.1.

userhash = SHA256(username ":" realm)

key = MD5(username ":" realm ":" OpaqueString(password))

key = SHA256(username ":" realm ":" OpaqueString(password))

