NextExp = s + 1; 
Type-P-Reordered = False;  
Type-P-Reordered = True  
    
SequenceDiscontinuty = True; 
SeqDiscontinutySize = s - NextExp; 
SequenceDiscontinuty = False; 
NextExp = s + 1; 
  
Type-P-Reordered = False; 
    
Type-P-Reordered = True; 
SequenceDiscontinuty = False; 
    
r = 0; /* r is the run counter */ 
x = 0; /* x is the number of runs */ 
  
a = 0; /* a is the accumulator of in-order packets */ 
p = 0; /* p is the number of packets */ 
q = 0; /* q is the sum of the squares of the runs counted */ 
 
r = 0; 
p = 36 
x = 3 
a = 33 
q = 3 * (11*11) = 363 
p = 36 
x = 3 
a = 33 
  
q = 1 + 1 + 961 = 963 
s={1,2,3,7,8,9,4,5,6}, packets 4, 5, and 6 are reordered, but only 
IPDV = Delay(SrcNum)-Delay(SrcNum-1) 
s = 1, 2, 3, 5, 6, 7, 8, 4, 9, 10 
i = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 
                            /\ 
    
s = 1, 2, 3, 4, 7, 5, 6, 8, 9, 10 
i = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 
                      /\ /\ 
    
s = 1, 2, 3, 7, 8, 9,10, 4, 5, 6, 11 
i = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11 
    
    
Reordered = TRUE for Packets 5 and 6, and they are all associated 
s = 1, 2, 3, 6, 7, 4, 5, 8, 9, 10, 12, 13, 11, 14, 15, 16 
i = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 
    
r = 1, 2, 3, 4, 5, 0, 0, 1, 2,  3,  4,  5,  0,  1,  2,  3, ... 
e=2. There are two different reordering discontinuities, one at 
rc = scanf("%d\n", &res); 
NextExp = seqnum+1; 
  
iReturn = 1; 
r = (r+1) % MAXN; 
iReturn = 1; 
packet = atoi(argv[i]); 
reordered = %d\n",  receive_packets, reorder_packets_Al, 
NextExp=0; 
NextExpFrag=0; 
NextExp = s+1; 
NextExpFrag = 0; 
Reordering = False; 
NextExpFrag = FragOffset+1; 
Reordering = False; 
NextExpFrag = FragOffset+1; 
Reordering = False; 
Reordering = True; /* fragment reordered  */ 
Reordering = True; 
Reordering = True; 
