profile             = profile-uri "/" iris-urn-abbrev
                           "/" registry-urn-abbrev
profile-uri         = "http://iana.org/beep/"
iris-urn-abbrev     = // as specified by IRIS
registry-urn-abbrev = // as specified by IRIS

serverName="com" attribute during the BEEP session instantiation.
