targetNamespace="urn:ietf:params:xml:ns:traceroute-1.0"
type="tr:_inetAddressUnknown"/>

type="tr:_inetAddressASNumber"/>

type="tr:_inetAddressDns"/>
type="tr:_inetAddressUnknown"/>

type="tr:_inetAddressIpv4"/>

type="tr:_inetAddressIpv6"/>

type="tr:_inetAddressASNumber"/>
type="tr:inetAddressWithoutDns">





type="tr:_inetAddressDns">
name="MPLSLabelStackEntry">
type="tr:_roundTripTime">
type="tr:operationResponseStatus">
type="tr:string255">
type="xs:boolean">
type="xs:unsignedByte">
type="tr:inetAddressWithoutDns">
type="xs:unsignedInt">
type="tr:string255">
type="xs:unsignedByte">
type="xs:boolean">
type="tr:u8nonzero">
type="tr:string255">
type="tr:inetAddressWithoutDns">
type="tr:_Metadata"/>

name="Measurement">
type="tr:_Metadata"/>

name="MeasurementResult"
type="tr:_Measurement"/>
