timeStamp='2000-05-14T13:30:00-08:00'>
lastUpdate='2000-05-14T13:02:00-08:00'
publisherInfo='http://www.example.com/fred/'>
destination='apex:fred/appl=im@example.com'
availableUntil='2000-05-14T14:02:00-08:00' />
availableUntil='2525-12-31T23:59:59-08:00' />
transID='100' />
timeStamp='2000-05-14T13:30:00-08:00'>
lastUpdate='2000-05-14T13:02:00-08:00'
publisherInfo='http://www.example.com/fred/'>
destination='apex:fred/appl=im@example.com'
availableUntil='2000-05-14T14:02:00-08:00' />
transID='2' />
duration='86000' action='subscribe' />
