u-PE1===============n-PE3===============PE5
                 ||                  || \             /|| 
                 ||  Redundancy      ||  \           / ||
                 ||  Provider RSTP   ||   Full-Mesh .  ||        
                 ||                  ||  /           \ ||
                 ||                  || /             \||
u-PE2---------------n-PE4==============PE6     
                      Backup PW

