TaskReporting=FastAbort is operational on that third-
TaskReporting=FastAbort (section 9.1) semantics defined by this 
TaskReporting=FastAbort is operational on a session, the 
TaskReporting=FastAbort functionality (section 9.1), it may end 
TaskReporting=FastAbort operational (FastAbort sessions) even 
AsyncEvent=5 as defined in section 8.1.  Note that an initiator 
DataSegmentLength = 0 

 

TaskReporting=<list-of-values> 
 
Class=0x00): 

Class=0x01): 

Class=0x02): 

Class=0x03): 

