Loctype=101  X-coordinate - this necessitates there be a 
                 Latitude Locvalue present.

Loctype=102  Y-coordinate - this necessitates there be a 
                 Longitude Locvalue present.

Loctype=103  Z-coordinate - this necessitates there be an
                 Altitude Locvalue present.

Loctype=104  Unit of Measurement Altitude (UofMA) - this 
                 necessitates there be an Altitude unit of measurement 
                 Locvalue present.

Loctype=104, Locvalue=1 - meters above or below the datum 0 plane.  

Loctype=104, Locvalue=2 - building floor above or below the ground 
                             floor. This value has local significance 
                             only. 

Loctype=102 (Y-coordinate) present.  Loctype=103 (Z-coordinate) and 
Loctype=104 (UofMA) MUST be implemented to comply with this 
shape=1.

Loctypes=111(Datum) and =112(Valid-for) are OPTIONAL, but MAY change
Loctype=105  Radius - the straight line from the point at the 
                 center of the circle, extending out a given distance 
                 (this is the Locvalue of the Radius Loctype).

Loctype=101 (the X-coordinate representing the center of the 
                   circle)



Loctype=102 (the Y-coordinate representing the center of the 
                   circle)
Loctype=105 (the Radius value from the center X/Y point of the 
                   circle)

Loctypes=107 through =110, which detail a Centerpoint (see Section 
shape=2.

Loctypes=111 (Datum) and =112 (Valid-for) are OPTIONAL, but MAY 
shape=103  (polygon) of this TLV type, and that is an indication of 
Loctype=106 # of Points - each point, in 2D, is a point of X and
                              Y coordinates.

Loctype=106, Loctype=101, Loctype=102, Loctype=101, Loctype=102, 
Loctype=101, Loctype=102, etc...

Loctype=106, Loctype=101, Loctype=102, Loctype=103, Loctype=104, 
Loctype=101, Loctype=102, etc ...

Loctype=107 Polygon Centerpoint X-Coordinate - server calculated
                  center point X-Coordinate within a supplied polygon.

Loctype=108 Polygon Centerpoint Y-Coordinate - server calculated
                  center point X-Coordinate within a supplied polygon.

Loctype=109 Polygon Centerpoint Z-Coordinate - server calculated
                  center point X-Coordinate within a supplied polygon.

Loctype=110 Polygon Centerpoint Unit of Measurement Altitude - 
                  this is the same as the (UofMA) for Loctype=104 (from
                  section 2.1).

Loctypes=107 through =110 MUST NOT appear in a shape=102 (circle) 
Loctype=107, Loctype=108, Loctype=109, Loctype=110

shape=3.

Loctype=109 and =110 MUST NOT be present without the corresponding 
Loctypes=107 and =108.  

Loctypes=111 (Datum) and =112 (Valid-for) are OPTIONAL in either a 
Loctype=111 Datum - the base line of reference from which 
               measurements are taken out from (here both horizontally 
               and vertically).

Locvalue=1; two other datum combinations are included here.

Datum = 1 denotes WGS84 (EPSG4326) for 2D, and (EPSG4979) for 3D 
           (depending on whether an altitude Loctype is present).

Datum = 2 denotes the horizontal datum NAD83 as defined by the EPSG 
           as their CRS Code 4269; North American Vertical Datum of 
           1988 (NAVD88) is the associated vertical datum for NAD83

Datum = 3 denotes the horizontal datum NAD83 as defined by the EPSG 
           as their CRS Code 4269; Mean Lower Low Water (MLLW) is the 
           associated vertical datum for NAD83

Loctype=112 Valid-for - measured in seconds the location within this
               TLV type is to be considered good, before needing a 
               refresh, which maps to PIDF.  





Locvalue=3), the PIDF-LO generator needs to place the altitude 
Locvalue=1), PIDF-LO generator has two options:

srsName="urn:ogc:def:crs:EPSG::4326" for 2D representations, and

srsName="urn:ogc:def:crs:EPSG::4979" for 3D representations.

substitutionGroup="gml:_CoordinateReferenceSystem"/>

substitutionGroup="gml:_CoordinateReferenceSystem"/>

Loctype=111 (Datum). If no Loctype=111 is present in this Option, it 
Datum = 1 denotes WGS84 (EPSG4326) for 2D, and (EPSG4979) for 3D 
           (depending on whether an altitude Loctype is present).

Datum = 2 denotes the horizontal datum NAD83 as defined by the EPSG 
           as their CRS Code 4269; North American Vertical Datum of 
           1988 (NAVD88) is the associated vertical datum for NAD83

Datum = 3 denotes the vertical datum NAD83 as defined by the EPSG as
           their CRS Code 4269; Mean Lower Low Water (MLLW) is the
           associated vertical datum for NAD83


