tcp_dst         = 80 443 8080
udp_dst         = 5901



tcp_src         = 7880 56000



gcd = con->mpath[0].weight_out;
lcm = gcd;
gcd = CALCULATE_GCD(gcd, con->mpath[i].weight_out);
lcm = (lcm * con->mpath[i].weight_out ) / gcd;
min_idx = 0;
min_inc = lcm + 1;
p = &con->mpath[i];
cinc = p->selection_increment + (lcm / p->weight_out);
min_idx = i;
min_inc = cinc;
