Subscription    =  "Subscription" HCOLON (sub-param *(COMMA
                      sub-param))
sub-param       =  event-type *(SEMI sub-param)
sub-event-param =  sub-aor / sub-event-param / tag-param / generic-param
sub-aor         =  "aor" EQUAL (SIP-URI / SIPS-URI)
sub-event-param =  "e-param" EQUAL quoted-string

