targetNamespace="http://oval.mitre.org/XMLSchema/
elementFormDefault="qualified" version="5.11">
namespace="http://oval.mitre.org/XMLSchema/oval-common-5"
schemaLocation="oval-common-schema.xsd"/>
namespace="http://www.w3.org/2000/09/xmldsig#"
schemaLocation="xmldsig-core-schema.xsd"/>
uri="http://oval.mitre.org/XMLSchema/
uri="http://www.w3.org/2001/XMLSchema-instance"
context="oval-def:oval_definitions">
test="oval-def:definitions or oval-def:tests or
type="oval:GeneratorType">
type="oval-def:DefinitionsType"
minOccurs="0" maxOccurs="1">
type="oval-def:TestsType" minOccurs="0"
maxOccurs="1">
type="oval-def:ObjectsType"
minOccurs="0" maxOccurs="1">
type="oval-def:StatesType" minOccurs="0"
maxOccurs="1">
type="oval-def:VariablesType"
minOccurs="0" maxOccurs="1">
minOccurs="0" maxOccurs="1">
xpath="oval-def:definitions/oval-def:definition"/>
refer="oval-def:definitionKey">
refer="oval-def:testKey">
refer="oval-def:objectKey">
refer="oval-def:stateKey">
refer="oval-def:variableKey">
refer="oval-def:objectKey">
xpath=".//oval-def:object_reference"/>
refer="oval-def:stateKey">
substitutionGroup="oval:notes">





select="name()"/> parent ID:
type="xsd:string" minOccurs="0"
maxOccurs="unbounded"/>
minOccurs="1" maxOccurs="unbounded"/>
type="oval-def:DefinitionType">
id="oval-def_required_criteria">





context="oval-def:oval_definitions/
minOccurs="0" maxOccurs="1"/>
type="oval-def:MetadataType">
maxOccurs="1"/>
type="oval-def:CriteriaType" minOccurs="0"
maxOccurs="1"/>
type="oval:DefinitionIDPattern"
use="required"/>
type="xsd:nonNegativeInteger" use="required"/>
type="oval:ClassEnumeration" use="required"/>
type="xsd:boolean" use="optional"
default="false"/>
type="oval-def:AffectedType" minOccurs="0"
maxOccurs="unbounded">
type="oval-def:ReferenceType"
minOccurs="0" maxOccurs="unbounded"/>
type="xsd:string"/>
processContents="lax"/>
namespace="##other" processContents="lax"/>
type="xsd:string" minOccurs="0"
maxOccurs="unbounded"/>
type="xsd:string" minOccurs="0"
maxOccurs="unbounded"/>
type="oval:FamilyEnumeration" use="required"
use="required"/>
use="required"/>
type="xsd:anyURI" use="optional"/>
maxOccurs="unbounded">
type="oval-def:CriteriaType"/>
type="oval-def:CriterionType"/>
type="oval-def:ExtendDefinitionType"/>
type="xsd:boolean" use="optional"/>
type="oval:OperatorEnumeration"
use="optional" default="AND"/>
type="xsd:boolean" use="optional"
default="false"/>
type="oval:NonEmptyStringType"
use="optional"/>
type="xsd:boolean" use="optional"/>
type="oval:TestIDPattern" use="required"/>
type="xsd:boolean" use="optional"
default="false"/>
type="oval:NonEmptyStringType"
use="optional"/>
type="xsd:boolean" use="optional"/>
type="oval:DefinitionIDPattern"
use="required"/>
type="xsd:boolean" use="optional"
default="false"/>
type="oval:NonEmptyStringType"
use="optional"/>
minOccurs="1" maxOccurs="unbounded"/>
type="oval-def:TestType" abstract="true">
check_existence = 'all_exist' and a regex
context="oval-def:oval_definitions/
test="not(*[local-name()='state'])"
                   ><sch:value-of select="@id"/> - No
minOccurs="0" maxOccurs="1"/>
maxOccurs="1"/>
type="oval:TestIDPattern" use="required"/>
type="xsd:nonNegativeInteger" use="required"/>
type="oval:ExistenceEnumeration"
use="optional" default="at_least_one_exists"/>
type="oval:CheckEnumeration" use="required"/>
type="oval:OperatorEnumeration"
use="optional" default="AND"/>
type="oval:NonEmptyStringType"
use="required"/>
type="xsd:boolean" use="optional"
default="false"/>
type="oval:ObjectIDPattern" use="required"/>
type="oval:StateIDPattern" use="required"/>
minOccurs="1" maxOccurs="unbounded"/>
type="oval-def:ObjectType" abstract="true">
minOccurs="0" maxOccurs="1"/>
maxOccurs="1"/>
type="oval:ObjectIDPattern" use="required"/>
type="xsd:nonNegativeInteger" use="required"/>
type="oval:NonEmptyStringType"
use="optional"/>
type="xsd:boolean" use="optional"
default="false"/>





context="oval-def:oval_definitions/
test="name(./../..) =
context="oval-def:oval_definitions/
test="name(./../../..) =
select="../../../@id"/> - Each
context="oval-def:oval_definitions/
test="name(./../../../..) =
select="../../../../@id"/> - Each
minOccurs="1" maxOccurs="2"/>
type="oval:ObjectIDPattern"
minOccurs="1" maxOccurs="2"/>
minOccurs="0" maxOccurs="unbounded"/>
type="oval-def:SetOperatorEnumeration"
use="optional" default="UNION"/>
type="oval-def:FilterActionEnumeration"
use="optional" default="exclude"/>
minOccurs="1" maxOccurs="unbounded"/>
type="oval-def:StateType" abstract="true">
minOccurs="0" maxOccurs="1"/>
maxOccurs="1"/>
type="oval:StateIDPattern" use="required"/>
type="xsd:nonNegativeInteger" use="required"/>
type="oval:OperatorEnumeration"
use="optional" default="AND"/>
type="oval:NonEmptyStringType"
use="optional"/>
type="xsd:boolean" use="optional"
default="false"/>
minOccurs="1" maxOccurs="unbounded"/>
type="oval-def:VariableType" abstract="true">
minOccurs="0" maxOccurs="1"/>
maxOccurs="1"/>
type="oval:VariableIDPattern" use="required"/>
type="xsd:nonNegativeInteger" use="required"/>
type="oval:SimpleDatatypeEnumeration">
type="oval:NonEmptyStringType"
use="required"/>
type="xsd:boolean" use="optional"
default="false"/>
substitutionGroup="oval-def:variable">
base="oval-def:VariableType">
maxOccurs="unbounded">
type="oval-def:PossibleValueType"/>
name="possible_restriction"
type="oval-def:PossibleRestrictionType"
type="xsd:string" use="required"/>
type="oval-def:RestrictionType"
minOccurs="1" maxOccurs="unbounded"/>
type="oval:OperatorEnumeration"
use="optional" default="AND"/>
use="required"/>
type="oval:OperationEnumeration"
use="required"/>
substitutionGroup="oval-def:variable">
base="oval-def:VariableType">
type="oval-def:ValueType"
minOccurs="1" maxOccurs="unbounded"
substitutionGroup="oval-def:variable">
base="oval-def:VariableType">
ref="oval-def:ComponentGroup"/>
type="oval-def:ObjectComponentType"/>
type="oval-def:VariableComponentType"/>
type="oval-def:LiteralComponentType"/>
id="oval-def_literal_component">
context="oval-def:literal_component">
test="not(@datatype='record')"
                   ><sch:value-of
select="ancestor::*/@id"/> - The
type="oval:SimpleDatatypeEnumeration"
use="optional" default="string"/>
type="oval:ObjectIDPattern" use="required"/>
type="oval:NonEmptyStringType"
use="required"/>
type="oval:NonEmptyStringType"
use="optional"/>
type="oval:VariableIDPattern" use="required"
type="oval-def:ArithmeticFunctionType"/>
type="oval-def:BeginFunctionType"/>
type="oval-def:ConcatFunctionType"/>
type="oval-def:EndFunctionType"/>
type="oval-def:EscapeRegexFunctionType"/>
type="oval-def:SplitFunctionType"/>
type="oval-def:SubstringFunctionType"/>
type="oval-def:TimeDifferenceFunctionType"/>
type="oval-def:RegexCaptureFunctionType"/>
type="oval-def:UniqueFunctionType"/>





type="oval-def:CountFunctionType"/>
type="oval-def:GlobToRegexFunctionType"/>
id="oval-def_arithmeticfunctionrules">
context="oval-def:arithmetic/
test="@datatype='float' or @datatype='int'"
context="oval-def:arithmetic/
value="@var_ref"/>
test="ancestor::oval-def:oval_definitions/
maxOccurs="unbounded">
type="oval-def:ArithmeticEnumeration"
use="required"/>
id="oval-def_beginfunctionrules">
context="oval-def:begin/
test="not(@datatype) or @datatype='string'"
context="oval-def:begin/
value="@var_ref"/>
test="ancestor::oval-def:oval_definitions/
type="xsd:string" use="required"/>
id="oval-def_concatfunctionrules">
context="oval-def:concat/
test="not(@datatype) or @datatype='string'"
context="oval-def:concat/
value="@var_ref"/>
test="ancestor::oval-def:oval_definitions/
maxOccurs="unbounded">
id="oval-def_endfunctionrules">
context="oval-def:end/oval-def:literal_component">
test="not(@datatype) or @datatype='string'"
context="oval-def:end/oval-def:variable_component">
value="@var_ref"/>
test="ancestor::oval-def:oval_definitions/
type="xsd:string" use="required"/>
id="oval-def_escaperegexfunctionrules">
context="oval-def:escape_regex/
test="not(@datatype) or @datatype='string'"
context="oval-def:escape_regex/
value="@var_ref"/>
test="ancestor::oval-def:oval_definitions/
id="oval-def_splitfunctionrules">
context="oval-def:split/
test="not(@datatype) or @datatype='string'"
context="oval-def:split/
value="@var_ref"/>
test="ancestor::oval-def:oval_definitions/
type="xsd:string" use="required"/>
id="oval-def_substringfunctionrules">
context="oval-def:substring/
test="not(@datatype) or @datatype='string'"
context="oval-def:substring/
value="@var_ref"/>
test="ancestor::oval-def:oval_definitions/
type="xsd:int" use="required"/>
type="xsd:int" use="required"/>
name="TimeDifferenceFunctionType">





id="oval-def_timedifferencefunctionrules">
context="oval-def:time_difference/
test="not(@datatype) or
context="oval-def:time_difference/
value="@var_ref"/>
test="ancestor::oval-def:oval_definitions/
type="oval-def:DateTimeFormatEnumeration"
use="optional" default="year_month_day"/>
type="oval-def:DateTimeFormatEnumeration"
use="optional" default="year_month_day"/>
id="oval-def_regexcapturefunctionrules">
context="oval-def:regex_capture/
test="not(@datatype) or @datatype='string'"
context="oval-def:regex_capture/
value="@var_ref"/>
test="ancestor::oval-def:oval_definitions/
type="xsd:string"/>
id="oval-def_globtoregexfunctionrules">
context="oval-def:glob_to_regex/
test="not(@datatype) or @datatype='string'"
context="oval-def:glob_to_regex/
value="@var_ref"/>
test="ancestor::oval-def:oval_definitions/
type="xsd:boolean" use="optional"
default="false"/>
C=complete, I=incomplete, DNE=does not
id="oval-def_definition_entity_rules">
context="oval-def:objects/*/*[@var_ref]|
value="@var_ref"/>
select="../@id"/> - a var_ref has
select="name()"/> entity so no
test="( (not(@datatype)) and
context="oval-def:objects/*/*[@var_ref]|
context="oval-def:objects/*/*[@var_check]|
context="oval-def:states/*/*[@var_ref]|
context="oval-def:states/*/*[@var_check]|
context="oval-def:objects/*/*[not(@datatype)]|
test="not(@operation) or
select="@operation"/>' for the
context="oval-def:objects/*/*[@datatype='binary']|
test="not(@operation) or
select="@operation"/>' for the
context="oval-def:objects/*/*[@datatype='boolean']|
test="not(@operation) or
select="@operation"/>' for the
context="oval-def:objects/*/*
test="not(@operation) or
select="@operation"/>' for the
context="oval-def:objects/*/*
test="not(@operation) or
select="@operation"/>' for the
context="oval-def:objects/*/*
test="not(@operation) or
select="@operation"/>' for the
context="oval-def:objects/*/*
test="not(@operation) or
select="@operation"/>' for the
context="oval-def:objects/*/*





test="not(@operation) or
select="@operation"/>' for the
context="oval-def:objects/*/*[@datatype='int']|
test="not(@operation) or
select="@operation"/>' for the
context="oval-def:objects/*/*
test="not(@operation) or
select="@operation"/>' for the
context="oval-def:objects/*/*
test="not(@operation) or
select="@operation"/>' for the
context="oval-def:objects/*/*
test="not(@operation) or
select="@operation"/>' for the
context="oval-def:objects/*/*
test="not(@operation) or
select="@operation"/>' for the
context="oval-def:objects/*/*
test="not(@operation) or @operation='equals'"
                   ><sch:value-of select="../@id"/> -
select="@operation"/>' for the
id="oval-def_no_var_ref_with_records">
context="oval-def:objects/*/*
id="oval-def_definition_entity_type_check_rules">





context="oval-def:objects/*/*
test="(not(contains(.,'.'))) and
select="name()"/> entity is 'int'
type="oval:DatatypeEnumeration"
use="optional" default="string">
type="oval:OperationEnumeration"
use="optional" default="equals">
use="optional" default="false">
type="oval:VariableIDPattern" use="optional">
type="oval:CheckEnumeration" use="optional">
abstract="true">
ref="oval-def:EntityAttributeGroup"/>
abstract="true">
ref="oval-def:EntityAttributeGroup"/>
name="EntityObjectIPAddressType">
base="oval-def:EntitySimpleBaseType">
use="required">
base="oval:SimpleDatatypeEnumeration">
value="ipv4_address"/>
value="ipv6_address"/>
name="EntityObjectIPAddressStringType">
base="oval-def:EntitySimpleBaseType">
use="optional" default="string">
base="oval:SimpleDatatypeEnumeration">
value="ipv4_address"/>
value="ipv6_address"/>
name="EntityObjectAnySimpleType">
base="oval-def:EntitySimpleBaseType">
type="oval:SimpleDatatypeEnumeration"
use="optional" default="string"/>
base="oval-def:EntitySimpleBaseType">
memberTypes="xsd:hexBinary oval:EmptyStringType"
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="binary"/>
base="oval-def:EntitySimpleBaseType">
memberTypes="xsd:boolean oval:EmptyStringType"
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="boolean"/>
base="oval-def:EntitySimpleBaseType">
memberTypes="xsd:float oval:EmptyStringType"
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="float"/>
base="oval-def:EntitySimpleBaseType">
memberTypes="xsd:integer oval:EmptyStringType"
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="int"/>
base="oval-def:EntitySimpleBaseType">
type="oval:SimpleDatatypeEnumeration"
use="optional" fixed="string"/>
base="oval-def:EntitySimpleBaseType">
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="version"/>
base="oval-def:EntityComplexBaseType">
type="oval-def:EntityObjectFieldType"
minOccurs="0" maxOccurs="unbounded"/>
ref="oval-def:EntityAttributeGroup"/>
type="oval:CheckEnumeration"
use="optional" default="all"/>
name="EntityStateSimpleBaseType"
abstract="true">
base="oval-def:EntitySimpleBaseType">
type="oval:CheckEnumeration"
use="optional" default="all"/>
type="oval:ExistenceEnumeration"
use="optional"
default="at_least_one_exists"/>
name="EntityStateComplexBaseType"
abstract="true">
base="oval-def:EntityComplexBaseType">
type="oval:CheckEnumeration"
use="optional" default="all"/>
type="oval:ExistenceEnumeration"
use="optional"
default="at_least_one_exists"/>
base="oval-def:EntityStateSimpleBaseType">
use="required">
base="oval:SimpleDatatypeEnumeration">
value="ipv4_address"/>
value="ipv6_address"/>
name="EntityStateIPAddressStringType">
base="oval-def:EntityStateSimpleBaseType">
use="optional" default="string">
base="oval:SimpleDatatypeEnumeration">
value="ipv4_address"/>
value="ipv6_address"/>
base="oval-def:EntityStateSimpleBaseType">
type="oval:SimpleDatatypeEnumeration"
use="optional" default="string"/>
base="oval-def:EntityStateSimpleBaseType">
memberTypes="xsd:hexBinary oval:EmptyStringType"
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="binary"/>
base="oval-def:EntityStateSimpleBaseType">
memberTypes="xsd:boolean oval:EmptyStringType"
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="boolean"/>
base="oval-def:EntityStateSimpleBaseType">
memberTypes="xsd:float oval:EmptyStringType"
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="float"/>
base="oval-def:EntityStateSimpleBaseType">
memberTypes="xsd:integer oval:EmptyStringType"
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="int"/>
base="oval-def:EntityStateSimpleBaseType">
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="evr_string"/>
name="EntityStateDebianEVRStringType">
base="oval-def:EntityStateSimpleBaseType">
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="debian_evr_string"
base="oval-def:EntityStateSimpleBaseType">
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="version"/>
name="EntityStateFileSetRevisionType">
base="oval-def:EntityStateSimpleBaseType">
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="fileset_revision"
name="EntityStateIOSVersionType">
base="oval-def:EntityStateSimpleBaseType">
use="optional" default="string">
base="oval:SimpleDatatypeEnumeration">
base="oval-def:EntityStateSimpleBaseType">
type="oval:SimpleDatatypeEnumeration"
use="optional" fixed="string"/>
base="oval-def:EntityStateComplexBaseType">
type="oval-def:EntityStateFieldType"
minOccurs="0" maxOccurs="unbounded"/>
ref="oval-def:EntityAttributeGroup"/>
type="oval:CheckEnumeration"
use="optional" default="all"/>
