next_ephemeral = min_ephemeral;

count = max_ephemeral - min_ephemeral + 1;

port = next_ephemeral;
next_ephemeral = min_ephemeral;
num_ephemeral = max_ephemeral - min_ephemeral + 1;
next_ephemeral = min_ephemeral + (random() % num_ephemeral);
count = num_ephemeral;

next_ephemeral = min_ephemeral;
num_ephemeral = max_ephemeral - min_ephemeral + 1;
next_ephemeral = min_ephemeral + (random() % num_ephemeral);
count = num_ephemeral;

next_ephemeral = min_ephemeral + (random() % num_ephemeral);
next_ephemeral = 0;

num_ephemeral = max_ephemeral - min_ephemeral + 1;
offset = F(local_IP, remote_IP, remote_port, secret_key);
count = num_ephemeral;

port = min_ephemeral + (next_ephemeral + offset) % num_ephemeral;
num_ephemeral = max_ephemeral - min_ephemeral + 1;
offset = F(local_IP, remote_IP, remote_port, secret_key);
index = G(offset);
count = num_ephemeral;

port = min_ephemeral + (offset + table[index]) % num_ephemeral;
s = socket();
