value = (byte[0] << 8*(n-1)) | (byte[1] << 8*(n-2)) |
              ... | byte[n-1];
additional_data = seq_num + TLSPlaintext.type +
                        TLSPlaintext.version

AEADEncrypted = AEAD-Encrypt(write_key, nonce, plaintext,
                                   additional_data)

key_block = PRF(MS,
                      "key expansion",
                      SecurityParameters.server_random +
                      SecurityParameters.client_random);

hs_master_secret = PRF(pre_master_secret, "handshake master secret",
                           session_hash)
                           [0..47];

master_secret = PRF(hs_master_secret, "extended master secret",
                          session_hash)
                          [0..47];

resumption_premaster_secret = PRF(hs_master_secret,
                                        "resumption premaster secret",
                                        session_hash)
                                        [0..47];

session_hash = Hash(handshake_messages)

