ID=17)

ID=18)

ID=20)

ID=21)

ID=22)

ID=23)

ID=26)







measured_overload_rate = 
Sum_Mi =0
Sum_Mi = Sum_Mi + Mi
signaled_overload_rate = measured_overload_rate - Sum_Mi, 

incoming_encoded-DSCP_rate = 
     = (received number of "encoded_DSCP" during T) * N)/T;

total_congested_bandwidth = N*input_remarked_bytes/T

terminated_bandwidth = 0;
priority_class = 0;
terminated_bandwidth =  
priority_class = priority_class + 1;
incoming_congestion_rate = input_notified_bytes/T

m = 200 octets
r = 10000 octets/s
b = 2000 octets

p = r = 10000 octets/s
MPS = 220 octets.

r = p of initial e2e <TMOD-1> parameter
m = large;
b = large;

r = p of initial e2e <TMOD-1> parameter = 10000 octets/s
m = MPS of initial e2e <TMOD-1> parameter = 220 octets

b = p * "period of time".

b = 10000 octets/s * 1.5 seconds = 15000 octets

r = 10000 octets/s
p = 10000 octets/s
m = 220 octets
b = 15000 octets
MPS = 220 octets


