purpose_specific_key = PRF(SecurityParameters.master_secret,
                              PURPOSE_SPECIFIC_STRING,
                              SecurityParameters.server_random +
                              SecurityParameters.client_random).

