DNS-SVCB-Keys = sf-list

dns-svcb-keys = 1, 5

DNS-SVCB-Params = sf-list

dns-svcb-params = "svc2.example.com.";priority=1;ttl=3600;p1=:aDIsaDM=:;p5=:MTIzLi4u:,
                  "svc.example.com.";priority=2;ttl=3600;p1=:aDI=:;p5=:YWJjLi4u:

