Value=[TBD] (Attempted LSP setup/download/label-range reservation if
Error-value=[TBD](SR capability was not advertised) and terminate the
value=10 (SRP object missing).

PST = 1 (defined in [I-D.ietf-pce-segment-routing]) can be reused
Error-type=6 (Mandatory Object missing) and Error-value=[TBD] (Label
