body = *line (contact-field eol) *line

line = *1(field / comment) eol

eol = *WSP [CR] LF

field = contact-field / encryption-field / acknowledgement-field /
fs = ":"

comment = "#" *(WSP / VCHAR / %xA0-E007F)
contact-field = "Contact" fs SP (email / uri / phone)

email = <Email address as per [RFC5322]>

phone = "+" *1(DIGIT / "-" / "(" / ")" / SP)

uri = <URI as per [RFC3986]>

encryption-field = "Encryption" fs SP uri

signature-field = "Signature" fs SP uri

policy-field = "Policy" fs SP uri

acknowledgement-field = "Acknowledgement" fs SP uri

ext-field = field-name fs SP unstructured

field-name = <as per section 3.6.8 of [RFC5322]>

unstructured = <as per section 3.2.5 of [RFC5322]>

