Status-Type = Interim-Update (3)) would contain all of the
Type="Authorize-Only" MUST contain a State attribute.

Message-Authenticator = HMAC-MD5 (Type, Identifier, Length,
Message-Authenticator = HMAC-MD5 (Type, Identifier, Length,
Message-Authenticator = HMAC-MD5 (Type, Identifier, Length,
