xmlns="urn:ietf:params:netconf:capability:notification:1.0">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">

xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
targetNamespace="urn:ietf:params:xml:ns:netmod:notification"
elementFormDefault="qualified"
attributeFormDefault="unqualified">
schemaLocation="http://www.w3.org/2001/xml.xsd"/>
schemaLocation=
     "http://www.iana.org/assignments/xml-registry/schema/netconf.xsd"/>
schemaLocation=
type="xs:string"/>
type="xs:boolean"/>
type="xs:dateTime" minOccurs="0">
type="manageEvent:ReplayCompleteNotificationType"
substitutionGroup="ncEvent:notificationContent">
                <xs:annotation>
          <xs:documentation>
            This notification is sent to signal the end of a replay
            portion of a subscription.
          </xs:documentation>
xmlns="urn:ietf:params:netconf:capability:notification:1.0"
targetNamespace=
          "urn:ietf:params:netconf:capability:notification:1.0"
elementFormDefault="qualified"
attributeFormDefault="unqualified"
            xml:lang="en">

schemaLocation="http://www.w3.org/2001/xml.xsd">
schemaLocation=
type="streamNameType" minOccurs="0">
type="netconf:filterInlineType"
minOccurs="0">
minOccurs="0" >
minOccurs="0" >
type="createSubscriptionType"
substitutionGroup="netconf:rpcOperation">
type="NotificationContentType" abstract="true"/>

severity=minor).  Nevertheless, it may be used for defining simple
xmlns="urn:ietf:params:netconf:capability:notification:1.0">
xmlns="urn:ietf:params:netconf:capability:notification:1.0">
xmlns="urn:ietf:params:netconf:capability:notification:1.0">
select="/ex:event[ex:eventClass='fault' and
                (ex:severity='minor' or ex:severity='major'
                     or ex:severity='critical')]"/>
severity=major) | (fault & severity = minor) | (fault &
card=Ethernet0)))


xmlns="urn:ietf:params:netconf:capability:notification:1.0">
select="/ex:event[
                    ex:eventClass='fault' and ex:severity='minor') or
                    (ex:eventClass='fault' and ex:severity='major') or
                    ex:eventClass='fault' and ex:severity='critical') or
                    (ex:eventClass='fault' and
                    ex:reportingElement/ex:card='Ethernet0') or
                    ex:eventClass='state' or
                    ex:eventClass='config']"/>
