preferences = IPV6_PREFER_SRC_TMP;

s = socket(ai->ai_family, ...);
ai = ai->ai_next;
flags = IPV6_PREFER_SRC_TMP;
extlen = sizeof(flags);
cmsglen = CMSG_SPACE(extlen);
cmsgptr = malloc(cmsglen);
extptr = CMSG_DATA(cmsgptr);

flags = IPV6_PREFER_SRC_COA;
