i2rs-trace-log = timestamp client-id actor-id client-addr operation
                    operation-data result-code
client-id      = uuid
actor-id       = byte-string
byte-string    = *( %x01-09  /  %x0B-0C  /  %x0E-FF )
                    ; any byte except NUL, CR or LF
client-addr    = IP-literal / IPv4address
operation      = ALPHA *( ALPHA / "_" / "-" / "(" / ")" )
operation-data = *VCHAR
result-code    = 1*( ALPHA / DIGIT / "-" / "_" / "(" / ")" )


