T = SET-CREATE
T = SET-REPLACE
T = DEL
           |
           +- T = Path-data
                |
                + -- flags
                + -- IDCount
                + -- IDs
                |
                +- T = Path-data
                   |
                   + -- flags
                   + -- IDCount
                   + -- IDs
                   |
                   +- T = Path-data
                      |
                      + -- flags
                      + -- IDCount
                      + -- IDs
                      + -- T = KEYINFO
                      |    + -- KEY_ID
                      |    + -- KEY_DATA
                      +- T = Path-data
                           |
                           + -- flags
                           + -- IDCount
                           + -- IDs


Type = "REPORT" --- this type of operation is for FE to
Type = "SET" --- this operation is to set LFB attributes

Type = "DEL" --- this operation to delete some LFB
Type = "SET-RESPONSE" --- this operation is for the
Type = "DEL-RESPONSE" --- this operation is for the
Type = "GET" --- this operation is to request to get LFB
Type = "GET-RESPONSE" --- this operation is to response to
MessageType = 'EventNotification'.  The ACK flag in the header
Type = "REPORT" --- this type of operation is for FE to
ElementID = 10 (i.e index 10 from z[]), lengthof(all below)
                 ElementIDof(a), lengthof(a), valueof(a)
                 ElementIDof(b), lengthof(b), valueof(b)
ElementID = 15 (index 15 from z[]), lengthof(all below)
                 ElementIDof(a), lengthof(a), valueof(a)
                 ElementIDof(c), lengthof(c), valueof(c)

OPER = GET-TLV
           Path-data TLV: IDCount = 1, IDs = 1
OPER = GET-RESPONSE-TLV
           Path-data-TLV:
flags=0, IDCount = 1, IDs = 1
OPER = SET-REPLACE-TLV
           Path-data-TLV:
flags = 0,  IDCount = 1, IDs = 2
OPER = SET-RESPONSE-TLV
           Path-data-TLV:
flags = 0,  IDCount = 1, IDs = 2
OPER = GET-TLV
           Path-data-TLV:
IDCount = 1, IDs = 4
OPER = GET-RESPONSE-TLV
           Path-data-TLV:
flags = 0, IDCount = 1, IDs = 4
FULLDATA=TLV: L = XXX, V=
                           a series of: index, j1value,j2value  entries
                           representing the entire table
OPER = SET-CREATE-TLV
           Path-data-TLV:
flags = 0 , IDCount = 1, IDs=4
flags = 0, IDCount = 1, IDs = 0
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 4
flags = 0, IDCount = 1, IDs = 5
OPER = SET-RESPONSE-TLV
           Path-data-TLV:
flags = 0 , IDCount = 1, IDs=4
flags = 0, IDCount = 1, IDs = 0
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 4
flags = 0, IDCount = 1, IDs = 5
OPER = SET-REPLACE-TLV
           Path-data TLV:
flags =  0 , IDCount = 1, IDs=4
flags = 0, IDCount = 1, IDs = 0
flags = 0, IDCount = 1, IDs = 2
OPER = SET-REPLACE-TLV
           Path-data TLV:
flags =  0 , IDCount = 1, IDs=4
flags = 0, IDCount = 1, IDs = 0
flags = 0, IDCount = 1, IDs = 2
OPER = GET-TLV
           Path-data TLV:
IDCount = 2, IDs=4.0

OPER = GET-RESPONSE-TLV
           Path-data TLV:
IDCount = 2, IDs=4.0
OPER = GET-TLV
           Path-data-TLV:
flags = 0, IDCount = 1, IDs=4
flags = 0, IDCount = 1, IDs = 0
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 4
flags = 0, IDCount = 1, IDs = 5


OPER = GET-RESPONSE-TLV
           Path-data-TLV:
flags = 0, IDCount = 1, IDs=4
flags = 0, IDCount = 1, IDs = 0
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 4
flags = 0, IDCount = 1, IDs = 5
OPER = SET-CREATE-TLV
           Path-data-TLV:
flags = 0, IDCount = 2, IDs=4.5
OPER = SET-RESPONSE-TLV
           Path-data TLV:
flags = 0, IDCount = 1, IDs=4.5
OPER = SET-CREATE-TLV
           Path-data -TLV:
flags = FIND-EMPTY, IDCount = 1, IDs=4
OPER = SET-RESPONSE
           Path-data TLV:
flags = 0, IDCount = 2, IDs=4.7
OPER = GET-TLV
           Path-data TLV:
flags = 0, IDCount = 1, IDs=3

OPER = GET-RESPONSE-TLV
           Path-data TLV
flags = 0, IDCount = 1, IDs=3
OPER = GET-TLV
           Path-data-TLV:
flags = F_SELKEY  IDCount = 1, IDs=6
KEYINFO-TLV = KEYID=1, KEY_DATA=100

OPER = GET-RESPONSE-TLV
           Path-data TLV:
flags = 0, IDCount = 1, IDs=6.10
OPER = DEL-TLV
           Path-data TLV:
flags = F_SELKEY  IDCount = 1, IDs=4
OPER = DELETE-RESPONSE-TLV
           Path-data TLV:
flags = 0  IDCount = 2, IDs=4.15
OPER = GET-TLV
           Path-data-TLV:
flags = 0 IDCount = 1, IDs=5

OPER = GET-RESPONSE-TLV
        Path-data TLV:
flags = 0  IDCount = 1, IDs=5
               FULLDATA TLV, Length = XXXX
                   index, someidv, TLV: T=FULLDATA, L = 4+strlen(namev),
V = namev
V = namev
V = namev
V = namev
OPER = SET-CREATE-TLV
           Path-TLV:
flags = 0, IDCount = 2,  IDs=4.20
OPER = SET-REPLACE-TLV
           Path-data-TLV:
flags = F_SELKEY, IDCount = 1, IDs=3
KEYINFO = KEYID=1 KEY_DATA=10
flags = 0  IDCount = 1, IDs=2
OPER = SET-RESPONSE-TLV
           Path-data-TLV
flags = 0 IDCount = 3, IDs=4.20
OPER = SET-RESPONSE-TLV
           Path-data TLV
flags = 0 IDCount = 2, IDs=3.16
flags = 0  IDCount = 1, IDs = 2
OPER = SET-RESPONSE-TLV
           Path-data TLV
flags = 0 IDCount = 1, IDs=3
KEYINFO = KEYID=1 KEY_DATA=10
flags = 0  IDCount = 1, IDs = 2
PER = SET-REPLACE-TLV
       Path-data TLV
flags = 0, IDCount = 1, IDs = 6
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 5
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 7
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 9
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
OPER = SET-RESPONSE-TLV
       Path-data TLV
flags = 0, IDCount = 1, IDs = 6
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 5
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 7
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 9
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
operation = GET-TLV
           Path-data-TLV
flags = 0  IDCount = 5, IDs=7.10.2.4.1

operation = GET-RESPONSE-TLV
           Path-data-TLV
flags = 0  IDCount = 5, IDs=7.10.2.4.1
operation = GET-TLV
           Path-data-TLV
flag = F_SELKEY, IDCount=3, IDS = 7.10.2
IDCount = 1, IDS = 2 //select x2

operation = GET-RESPONSE-TLV
           Path-data-TLV
flag = 0, IDCount=5, IDS = 7.10.2.11
flags = 0  IDCount = 1, IDS = 2
operation = SET-REPLACE-TLV
           Path-data-TLV
flags = 0  IDCount = 2, IDs=6.10
flags = 0, IDCount = 1, IDs=1
V = {111}
flags = 0  IDCount = 2, IDs=2.20
flags = 0, IDCount = 1, IDs=1
V = {222}
flags = 0, IDCount = 3, IDs=2.30.1
V = {333}
operation = SET-RESPONSE-TLV
           Path-data-TLV
flags = 0  IDCount = 2, IDs=6.10
flags = 0, IDCount = 1, IDs=1
flags = 0  IDCount = 2, IDs=2.20
flags = 0, IDCount = 1, IDs=1
flags = 0, IDCount = 3, IDs=2.30.1
operation = SET-REPLACE-TLV
           Path-data TLV :
flags = 0, IDCount = 3, IDs=6.10.1
V = {111}
flags = 0, IDCount = 5, IDs=6.10.1.20.1
V = {222}
flags = 0, IDCount = 7, IDs=6.10.1.20.1.30.1
V = {333}
operation = SET-REPLACE-TLV
           Path-data TLV :
flags = 0, IDCount = 3, IDs=6.10.1
flags = 0, IDCount = 5, IDs=6.10.1.20.1
flags = 0, IDCount = 7, IDs=6.10.1.20.1.30.1
operation = GET-TLV
           Path-data-TLV
flags = 0  IDCount = 0

operation = GET-RESPONSE-TLV
           Path-data-TLV
flags = 0  IDCount = 0
