dc=foo,dc=com) and parallels the TLD DIT of the registry.

cn=nameserver1, |       |        cn=nameserver1, |       |
dc=foo,dc=net ) |       |        dc=bar,dc=net ) |       |
                   |       |                        |       |
          name server      |               name server      |
          (i.e.            |               (i.e.            |
cn=nameserver2,  |               cn=nameserver2,  |
dc=foo,dc=net )  |               dc=bar,dc=net )  |
                           |                                |
                registrar referral               registrar referral
                (i.e.                            (i.e.
cn=registrar,                    cn=registrar,
dc=foo,dc=net )                  dc=bar,dc=net )


dc=org DIT   dc=org DIT   dc=org DIT


dc=foo,dc=net       )  dc=foo,dc=net    )
       |
       |
cn=nameserver1,
dc=foo,dc=net     )


