charset=3Dus-ascii         ia5-text                     7.1
charset=3Diso-8859-x       EBP - GeneralText            7.2
page-length=3DA4
page-width=3DA4
encoding=3D1-dimensional
resolution=3DCoarse

page-length=3DA4             no bit set
page-length=3DB4          19              21
page-length=3DUnlimited   20              20

page-width=3DA4              no bit set
page-width=3DA3           18              22
page-width=3DB4           17              23

encoding=3D1-dimensional     no bit set
encoding=3D2-dimensional  16              8
encoding=3DUncompressed   26              30

resolution=3DCoarse          no bit set
resolution=3DFine         15              9

class=3Dformatted

byte =3D first bit of the G3Fax). The bitstring is
