origin            = "origin" ":" OWS [ "null" / origin-list ] OWS
origin-list       = serialized-origin *( 1*SP serialized-origin )
serialized-origin = scheme "://" host [ ":" port ]
      ; <scheme>, <host>, <port> productions from RFC3986

