message-header  =/ References
References      =  "References" HCOLON reference *(COMMA reference)
reference       =  callid *( SEMI reference-param )
reference-param =  rel-param / generic-param
rel-param       =  "rel" EQUAL rel-value
rel-value       =  "chain" / "inquiry" / "refer" / "sequel"
                    /  "xfer" /  gen-value

