Version      = 0.0

Description  =
         The wp-ldap (or White Pages via LDAP) service type provides
         attributes for looking up people via the LDAP protocol.

Version      = 0.0

Description  =
         The wp-whois++ (or White Pages via WHOIS++) service type provides
         attributes for looking up people via the WHOIS++ protocol.

Version      = 0.0

Description  =
      The wp-ph (or White Pages via PH) service type provides attributes
      for defining services for looking up people via the PH protocol.

Version      = 0.0

Description  =
      The yp-z3950r (or Yellow Pages by Z39.50) service type provides
      attributes for looking up documents via the Z39.50 protocol.

Version      = 0.0

Description  =
      The yp-z3950s (or Yellow Pages by Z39.50) service type provides
      attributes for looking up documents via the Z39.50 session.

