F=1 further frames follow, F=0 last frame.
   
L=1. LEN specifies the number of octets in the current AMR frame
F=1 further frames follow, F=0 last frame.
   
n=1 is preceding frame n=2.

max = max(F(0),..,F(N-1));
k = H;
S = 8 - k%8;
FT = 3. The AMR frame header is followed by the AMR frame payload,
