T_WC = (N.L_BD   +    L_BE)/R.               (Eq. 1)
 
T_WC = (13L_BD + L_BE)/R,               Eq. (2)
 
S = R,  and D = 0, where R = link-speed.
 
S = R,  and D = L_max/R, where L_max is the maximum packet-size of
S = R_share (WFQ), and D = L_max/R, where BD is  assigned  to  one
S = R_share,    D ~ L_sum/R, where "R_share" is  relatively  large
