DCluster = "DCluster" ":" #( <"> uri-prefix <">)
uri-prefix = scheme ":" "//" host [ ":" port ] [ abs_path ]
               | abs_path
               | rel_path

DTemplate = "DTemplate" ":"
                        #( <"> dt-uri <"> [ "/" dt-param])
dt-uri = absoluteURI | abs_path
dt-param = "etag" "=" entity-tag

