methods="INVITE,OPTIONS,BYE,CANCEL,ACK";schemes="sip,http";
uri-user="<user>";uri-domain="example.com"




Qo =  ---------
                       2



Qa  =     |      ------
                  |       i=1
                  |                              if M>0
                  |  ------------------
                  |
                  |        M
                  |      ------
                  |      \
                  |       \
                  |       /     Si
                  |      /
                  |      ------
                  \       i=1
                   \
                    \



methods="INVITE";msgserver;q=0.2
methods="INVITE";video;q=0.3
Request-Disposition  =  ( "Request-Disposition" / "d" ) HCOLON
                                directive *(COMMA directive)
directive            =  proxy-directive / cancel-directive /
                                fork-directive / recurse-directive /
                                parallel-directive / queue-directive)
proxy-directive      =  "proxy" / "redirect"
cancel-directive     =  "cancel" / "no-cancel"
fork-directive       =  "fork" / "no-fork"
recurse-directive    =  "recurse" / "no-recurse"
parallel-directive   =  "parallel" / "sequential"
queue-directive      =  "queue" / "no-queue"
Accept-Contact    =  ("Accept-Contact" / "a") HCOLON ac-value
                             *(COMMA ac-value)
Reject-Contact    =  ("Reject-Contact" / "j") HCOLON rc-value
                             *(COMMA rc-value)
ac-value          =  "*" *(SEMI ac-params)
rc-value          =  "*" *(SEMI rc-params)
ac-params         =  feature-param / c-p-q / req-param
                             / explicit-param / generic-param
rc-params         =  feature-param / req-param
                             / explicit-param / generic-param
feature-param     =  enc-feature-tag [EQUAL LDQUOT (tag-value-list
                             / string-value ) RDQUOT]
enc-feature-tag   =  base-tags / other-tags
base-tags         =  "attendant" / "audio" / "automata" /
                             "class" / "duplex" / "data" /
                             "control" / "mobility" / "description" /
                             "events" / "priority" / "methods" /
                             "schemes" / "application" / "video" /
                             "msgserver" / "language" / "type" /
                             "isfocus" / "uri-user" / "uri-domain"
other-tags        =  "+" ftag-name
ftag-name         =  ALPHA *( ALPHA / DIGIT / "!" / ""' /
                             "." / "-" / "%" )
tag-value-list    =  tag-value *("," tag-value)
tag-value         =  ["!"] (token-nobang / boolean / numeric)
token-nobang      =  1*(alphanum / "-" / "." / "%" / "*"
                             / "_" / "+" / "`" / "'" / "~" )
boolean           =  "TRUE" / "FALSE"
numeric           =  "#" numeric-relation number
numeric-relation  =  ">=" / "<=" / "=" / (number ":")
number            =  [ "+" / "-" ] 1*DIGIT ["." 0*DIGIT]
string-value      =  "<" qdtext ">"
req-param         =  "require"
explicit-param    =  "explicit"


contact-params  =  c-p-q / c-p-expires / feature-param
                           / contact-extension


are =. >= or <=, the filter is of the form:



foo=A,bar=B,baz=C,bop=F is in the feature set described by the
