lang    = 2*3 ALPHA  ; shortest ISO 639 tag
           =/ registered-lang
extlang = 2*15 ALPHA ; additional language subtag
script  = 4 ALPHA    ; ISO 15924 tag
region  = 2 ALPHA    ; ISO 3166 tag
           =/ 3 DIGIT   ; UN country number
variant =  5*15 alphanum
extensions      = 1* ("-" value) ; private use extensions
value           = 1*32 alphanum
registered-lang = 5*15 alphanum
grandfathered-registrations = ALPHA * (alphanumdash)
alphanum     = (ALPHA / DIGIT)
alphanumdash = (alphanum / "-")

                      Figure 1: Language Tag ABNF

language-range = language-tag / "*"

