targetNamespace="urn:ietf:params:xml:ns:dreg1"
elementFormDefault="qualified" >

minOccurs="0" maxOccurs="1" />
type="dreg:listRegistrarsType"
substitutionGroup="iris:query" />

minOccurs="0" maxOccurs="1" />
type="dreg:exactMatchParameter" />
type="language"
minOccurs="0" maxOccurs="unbounded"/>
type="dreg:findDomainsByRegistrantType"
substitutionGroup="iris:query" />

minOccurs="0" maxOccurs="1" />
type="dreg:partialMatchParameter" />
type="dreg:findDomainsByNameType"
substitutionGroup="iris:query" />

minOccurs="0" maxOccurs="1" />
type="dreg:partialMatchParameter" />
type="language"
minOccurs="0" maxOccurs="unbounded"/>
type="dreg:findDomainsByI18NNameType"
substitutionGroup="iris:query" />

type="language"
minOccurs="0" maxOccurs="unbounded"/>
type="dreg:findContactsType"
substitutionGroup="iris:query" />

minOccurs="0" maxOccurs="1" />
type="dreg:exactMatchParameter" />
type="dreg:exactMatchParameter" />
type="dreg:exactMatchParameter" />
type="dreg:exactMatchParameter" />
type="dreg:findDomainsByHostType"
substitutionGroup="iris:query" />
type="dreg:exactOrPartialMatchParameter" />
type="dreg:exactOrPartialMatchParameter" />
type="dreg:domainResourceParameter" />
type="dreg:exactMatchParameter" />
type="dreg:exactMatchParameter" />
type="dreg:exactMatchParameter" />
type="token" />
type="normalizedString" />

minOccurs="1" maxOccurs="1" >
minOccurs="0" maxOccurs="1" >
type="normalizedString" />
type="normalizedString" />
type="dreg:normalizedStringOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
minOccurs="0" maxOccurs="1" >
minOccurs="1" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="1">
minOccurs="1" maxOccurs="1" />
minOccurs="0" maxOccurs="1">
minOccurs="1" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="1">
minOccurs="1" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="1">
minOccurs="1" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="1">
minOccurs="1" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="1">
minOccurs="1" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="1">
minOccurs="1" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="1">
minOccurs="1" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="1">
minOccurs="1" maxOccurs="unbounded" />
type="dreg:dateTimeOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
minOccurs="0" maxOccurs="1">
minOccurs="0" maxOccurs="1">
nillable="true"
type="dreg:dateTimeOmissionType" />
nillable="true"
type="dreg:dateTimeOmissionType" />
nillable="true"
type="dreg:dateTimeOmissionType" />
nillable="true"
type="dreg:dateTimeOmissionType" />
nillable="true"
type="dreg:dateTimeOmissionType" />
nillable="true"
type="dreg:dateTimeOmissionType" />
minOccurs="0" maxOccurs="1">
minOccurs="0" maxOccurs="1">
minOccurs="0" maxOccurs="1">
minOccurs="0" maxOccurs="1" />
type="dreg:dateTimeOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:dateTimeOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:dateTimeOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:dateTimeOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
minOccurs="0" maxOccurs="1">
type="dreg:dateTimeOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
minOccurs="0" maxOccurs="1" />
type="dreg:domainType"
substitutionGroup="iris:result" />

type="normalizedString" />
minOccurs="0" maxOccurs="1">
minOccurs="0" maxOccurs="1">
nillable="true"
type="dreg:dateTimeOmissionType" />
nillable="true"
type="dreg:dateTimeOmissionType" />
minOccurs="0" maxOccurs="1">
type="dreg:normalizedStringOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="normalizedString" />
minOccurs="0" maxOccurs="1" >
type="token"
minOccurs="1" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="1">
type="token"
minOccurs="1" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="1" >
minOccurs="1" maxOccurs="unbounded" />
type="dreg:dateTimeOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:dateTimeOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:dateTimeOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
minOccurs="0" maxOccurs="1" />
type="dreg:hostType"
substitutionGroup="iris:result" />

type="normalizedString" />
type="dreg:normalizedStringOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1"/>
type="language"
minOccurs="0" maxOccurs="1" />
type="dreg:normalizedStringOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:stringOmissionType"
nillable="true"
minOccurs="0" maxOccurs="2" />
type="dreg:stringOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:stringOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:stringOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:normalizedStringOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:tokenOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:normalizedStringOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:normalizedStringOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:dateTimeOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:dateTimeOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="dreg:dateTimeOmissionType"
nillable="true"
minOccurs="0" maxOccurs="1" />
type="iris:seeAlsoType"
nillable="true"
minOccurs="0" maxOccurs="1" />
minOccurs="0" maxOccurs="1" />
type="dreg:contactType"
substitutionGroup="iris:result" />

type="string"
minOccurs="0" maxOccurs="1" />
minOccurs="0" maxOccurs="3">
type="dreg:registrationAuthorityType"
substitutionGroup="iris:result" />

type="iris:codeType"
substitutionGroup="iris:genericCode" />

type="iris:codeType"
substitutionGroup="iris:genericCode" />

Qt69V6OhYfFsJjvoNEOh1k2dgzXhSlzP3OMVSKRlBzGcO8=
xmlns="urn:ietf:params:xml:ns:dreg1"
authority="com" registryType="dreg1"
entityClass="domain-handle" entityName="tcs-com-1" >
authority="com" registryType="dreg1"
entityClass="host-handle" entityName="research7" />
authority="com" registryType="dreg1"
entityClass="host-handle" entityName="nsol184" />
authority="com" registryType="dreg1"
entityClass="contact-handle" entityName="beb140">
bagRef="x1"
authority="com" registryType="dreg1"
entityClass="contact-handle" entityName="mak21">
authority="com" registryType="dreg1"
entityClass="service-definition" entityName="notice" />
xmlns="urn:ietf:params:xml:ns:dreg1"
authority="com" registryType="dreg1"
entityClass="contact-handle" entityName="beb140" >
authority="com" registryType="dreg1"
entityClass="service-definition" entityName="notice" >
Qt69V6OhYfFsJjvoNEOh1k2dgzXhSlzP3OMVSKRlBzGcO8=
xmlns="urn:ietf:params:xml:ns:dreg1"
authority="com" registryType="dreg1"
entityClass="domain-handle" entityName="tcs-com-1" >
authority="com" registryType="dreg1"
entityClass="host-handle" entityName="research7" />
authority="com" registryType="dreg1"
entityClass="host-handle" entityName="nsol184" />
authority="net" registryType="dreg1"
entityClass="contact-handle" entityName="beb140" />
authority="net" registryType="dreg1"
entityClass="contact-handle"
entityName="mak21" >
xmlns="urn:ietf:params:xml:ns:dreg1"
authority="com" registryType="dreg1"
entityClass="host-handle" entityName="nsol184" >
authority="com" registryType="dreg1"
entityClass="contact-handle"
entityName="dblacka" >
authority="com" registryType="dreg1"
entityClass="contact-handle" entityName="dblacka" >
registryType="dreg1" entityClass="named-query"
entityName="my-servers" >
authority="verisignlabs.com" registryType="dreg1"
entityClass="host-handle" entityName="nsol184" />

authority="verisignlabs.com" registryType="dreg1"
entityClass="host-handle" entityName="research7" />

authority="verisignlabs.com" registryType="dreg1"
entityClass="host-handle" entityName="scooter" />

