p=>  |  |  <=s                    p=>  |  |  <=s                   
             +------+                          +------+                      
             |  MN  |                          |  MN  |                      
             +------+                          +------+                      
    
                                                                            
                (a)                               (b) 
   
               Figure 1. Multi-interface terminal scenario 
                                              
