over_time = (CurrentTime - TS.SndMax_time) - TS2_PASADF_MAXADV;
Measured_RTT = ((GetIntTS1() + TS.SndOff)
                                        - RSEG.TSecr + TS1_RTTM_G);
Measured_RTT = ((GetIntTS2() + TS.SndOff)
                                        - RSEG.TSecr + TS2_RTTM_G);
elapsed_time = GetTime() - TS.RcvMin_time;
elapsed_time = GetTime() - TS.RcvMin_time;
exp_ts = (TS.RcvMin + time2ts(elapsed_time));
Measured_RTT = ((GetIntTS1() + TS.SndOff)
                                        - RSEG.TSecr + TS1_RTTM_G);
Measured_RTT = ((GetIntTS2() + TS.SndOff)
                                        - RSEG.TSecr + TS2_RTTM_G);
over_time = ((GetTime() - TS.SndMax_time)
                             - TS2_PASADF_MAXADV);
option-length=2) is to negotiate the enabling of a feature, it could
Measured_RTT = GetTS() - RSEG.TSecr + TS_RTTM_G;
