CoA=2::1 |        | CoA=3::1 
HoA=1::1 |        | HoA=1::2 
                               |        | 
                          +--------------------+   
                          |    Mobile Router   | 
                          +--------------------+    
                                    | prefix=1:1::/96 
CoA=3::1 |        | CoA=4::1 
HoA=1::1 |        | HoA=2::1 
                               |        | 
                          +--------------------+   
                          |    Mobile Router   | 
                          +--------------------+    
                                    | prefix=1:1::/96, 2:1::/96 
CoA=3::1 |                | CoA=4::1 
HoA=1::1 |                | HoA=2::1 
                            |                | 
                      +----------+      +----------+ 
                      |  Mobile  |      |  Mobile  | 
                      | Router 1 |      | Router 2 | 
                      +----------+      +----------+ 
prefix=1:1::/96 |                 | prefix=2:1::/96 
                    -------?--------?--------?------- 
                                    | 
                           +----------------+ 
                           | Mobile Network | address=1:1::x 
                           |      Node x    |    or 2:1::x 
                           +----------------+ 
    
