delivery-status-content =
          per-message-fields 1*( CRLF per-recipient-fields )

address-type = atom

diagnostic-type = atom

mta-name-type = atom

per-message-fields =
          [ original-envelope-id-field CRLF ]
          reporting-mta-field CRLF
          [ dsn-gateway-field CRLF ]
          [ received-from-mta-field CRLF ]
          [ arrival-date-field CRLF ]
          *( extension-field CRLF )


original-envelope-id-field =
          "Original-Envelope-Id" ":" envelope-id

envelope-id = *text

reporting-mta-field =
          "Reporting-MTA" ":" mta-name-type ";" mta-name

mta-name = *text

dsn-gateway-field = "DSN-Gateway" ":" mta-name-type ";" mta-name

received-from-mta-field =
          "Received-From-MTA" ":" mta-name-type ";" mta-name

arrival-date-field = "Arrival-Date" ":" date-time

per-recipient-fields =
          [ original-recipient-field CRLF ]
          final-recipient-field CRLF
          action-field CRLF
          status-field CRLF
          [ remote-mta-field CRLF ]
          [ diagnostic-code-field CRLF ]
          [ last-attempt-date-field CRLF ]
          [ will-retry-until-field CRLF ]
          *( extension-field CRLF )


original-recipient-field =
          "Original-Recipient" ":" address-type ";" generic-address

generic-address = *text

final-recipient-field =
          "Final-Recipient" ":" address-type ";" generic-address

action-field = "Action" ":" action-value

action-value =
          "failed" / "delayed" / "delivered" / "relayed" / "expanded"

status-field = "Status" ":" status-code

status-code = DIGIT "." 1*3DIGIT "." 1*3DIGIT

          ; White-space characters and comments are NOT allowed within a
          ; status-code, though a comment enclosed in parentheses MAY follow
          ; the last numeric subfield of the status-code.  Each numeric
          ; subfield within the status-code MUST be expressed without
          ; leading zero digits.


remote-mta-field = "Remote-MTA" ":" mta-name-type ";" mta-name

diagnostic-code-field =
          "Diagnostic-Code" ":" diagnostic-type ";" *text

last-attempt-date-field = "Last-Attempt-Date" ":" date-time
will-retry-until-field = "Will-Retry-Until" ":" date-time

NOTIFY=NEVER parameter to the RCPT command), or

action-field = "Action" ":" action-value

action-value =
     "failed" / "delayed" / "delivered" / "relayed" / "expanded"

address-type = atom

arrival-date-field = "Arrival-Date" ":" date-time

delivery-status-content =
     per-message-fields 1*( CRLF per-recipient-fields )

diagnostic-code-field =
     "Diagnostic-Code" ":" diagnostic-type ";" *text

diagnostic-type = atom

dsn-gateway-field = "DSN-Gateway" ":" mta-name-type ";" mta-name

envelope-id = *text

extension-field = extension-field-name ":" *text

extension-field-name = atom

final-recipient-field =
     "Final-Recipient" ":" address-type ";" generic-address

generic-address = *text

last-attempt-date-field = "Last-Attempt-Date" ":" date-time

mta-name = *text

mta-name-type = atom

original-envelope-id-field =
     "Original-Envelope-Id" ":" envelope-id

original-recipient-field =
     "Original-Recipient" ":" address-type ";" generic-address

per-message-fields =
     [ original-envelope-id-field CRLF ]
per-recipient-fields =
     [ original-recipient-field CRLF ]
     final-recipient-field CRLF
     action-field CRLF
     status-field CRLF
     [ remote-mta-field CRLF ]
     [ diagnostic-code-field CRLF ]
     [ last-attempt-date-field CRLF ]
     [ will-retry-until-field CRLF ]
     *( extension-field CRLF )

received-from-mta-field =
     "Received-From-MTA" ":" mta-name-type ";" mta-name

remote-mta-field = "Remote-MTA" ":" mta-name-type ";" mta-name

reporting-mta-field =
     "Reporting-MTA" ":" mta-name-type ";" mta-name

status-code = DIGIT "." 1*3DIGIT "." 1*3DIGIT

     ; White-space characters and comments are NOT allowed within a
     ; status-code, though a comment enclosed in parentheses MAY follow
     ; the last numeric subfield of the status-code.  Each numeric
     ; subfield within the status-code MUST be expressed without
     ; leading zero digits.

status-field = "Status" ":" status-code

will-retry-until-field = "Will-Retry-Until" ":" date-time
boundary="RAA14128.773615765/CS.UTK.EDU"

boundary="JAA13167.773673707/CS.UTK.EDU"

boundary="84229080704991.122306.SYS30"

boundary=foobar

