Version = 0 
 
    

 
 
 
 
P = Packet Type : 4 bits 
    
      Value   Packet Type 
    
      0000     Echo Request 
      0001     Echo Reply 
      0010     Information Request 
      0011     Information Reply 
 
      0100-    Reserved for Redirection Packet Types 
      0111 
 
      1000-    Reserved for Future use 
      1111            
       
R = Record Path Record : 1 bit 
F = Fastpath ONLY Records Requested : 1 bit 
T = Timestamps Requested : 1 bit 
D = Data Section Present : 1 bit 
A = turnAround Options : 1 bit 
    
    
    
TT = Timestamp Type 
      0 = Undefined 
      1 = Local source 
      2 = External (Stratum ?) source 
      3 = Reserved 
      4 = Reserved 
      5 = ~UTC 
      6 = UTC 
      7 = No Timestamp 
    
F = Processed in "Fastpath" 
      0 No 
      1 Yes 
    
AT = Address Type 
      0 = IP address of interface 
      1 = IP address of interface (non-responsive) 
      2 = IP address of interface + IPMP proxy Address  
      3 = Non-IP address 
    
L = Stamping Location 
      0 = Packet RX 
      1 = Packet TX 
      2 = Internal processing 
      3 = Unspecified 
    
A = Accuracy  
      0-31, most accurate bit position in timestamp, compared to 'real 
      time clock' on the device, this will be the worst of the number of 
      bits of resolution of the device's clock and the maximum time 
      difference between the real time clock at the time the packet is 
      stamped and the value of the timestamp placed in the packet. 
    
T = Tunnel [De/En]capsulation Point 
      0 = No 
      1 = Yes 
    
 
 
 
 
E = Extensions 
      0 = No 
      1 = Yes 
    
R = Reserved 
    
    
    
P = Path Records Requested 
F = Swap Faux Ports 
T = TTL Reset 
R = Record Route Set 
    
    
P = Proxy Address Present 
    
T = Timestamps Present 
    
I = Information Request Extensions Present 
    
Version = 0. 
    
    
Version = 4 
    
IHL = 5 
    
Identification = unspecified 
    
Flags = DF 
    
