Encryption = #encryption_params
encryption_params = [ parameter *( OWS ";" OWS parameter ) ]

PRK = HMAC-SHA-256(salt, IKM)

cek_info = "Content-Encoding: aesgcm" || 0x00 || context

CEK = HMAC-SHA-256(PRK, cek_info || 0x01)
nonce_info = "Content-Encoding: nonce" || 0x00 || context

NONCE = HMAC-SHA-256(PRK, nonce_info || 0x01) XOR SEQ

Crypto-Key = #crypto_key_params
crypto_key_params = [ parameter *( OWS ";" OWS parameter ) ]
salt="m2hJ_NttRtFyUiMRPwfpHA"

salt="NfzOeuV5USPRA-n_9s1Lag",
keyid="bob/keys/123";
salt="bDMSGoc2uobK_IhavSHsHA"; rs=1200

