Type=GSS-API, which is sent to the peer. This occurs whether the call
EAP-Type=EAP GSS
                         (GSS Start,
                          S and O bits set),
EAP-Type=EAP GSS
EAP-Type=EAP GSS
EAP-Type=EAP GSS
L = Length included
M = More fragments
S = EAP GSS start
O = Options present
R = Reserved

L = Length included
M = More fragments
S = EAP GSS start
O = Options present
R = Reserved

EAP-Type=EAP GSS
EAP-Type=EAP GSS
EAP-Type=EAP GSS
EAP-Type=EAP GSS ->
                         EAP-Request/
EAP-Type=EAP GSS
EAP-Type=EAP GSS ->
                         EAP-Request/
EAP-Type=EAP GSS
EAP-Type=EAP GSS
EAP-Type=EAP GSS
L_S = length in bytes of secret;
L_S1 = L_S2 = ceil(L_S / 2);

