priority = (2^24)*(type preference) +
              (2^8)*(local preference) +
              (2^0)*(256 - component ID)


RTO = MAX (500ms, Ta * (Num-Of-Cands))


RTO = MAX (500ms, Ta * N * (Num-Waiting + Num-In-Progress))

