macro-string = *( macro-char / VCHAR )
macro-char   = ( "%{" ALPHA transformer *delimiter "}" )
                    / "%%" / "%_" / "%-"
transformer  = [ *DIGIT ] [ "r" ]
delimiter    = "." / "-" / "+" / "," / "/" / "_" / "="

l = local-part passed to the client authorization function.
s = Same as "%{l}@%{o}".
o = original domain passed to the client authorization function.
d = current domain passed to the client authorization function.
i = SMTP client IP (nibble format when an IPv6 address).
p = SMTP client domain name
v = client IP version string: "in-addr" for ipv4 or "ip6" for ipv6
r = domain name of the SMTP server.

elementFormDefault="qualified" attributeFormDefault="unqualified"
blockDefault="#all" xmlns="urn:ietf:params:xml:schema:marid-1"
maxOccurs="unbounded">
                         <xs:complexType>
                           <xs:sequence>
                             <xs:choice minOccurs="0"
maxOccurs="unbounded">
                               <xs:element name="a"
type="ExtensibleString"/>
type="ExtensibleString"/>
type="ExtensibleString"/>
type="ExtensibleString"/>
type="ExtensibleString"/>
type="ExtensibleString"/>
processContents="lax" minOccurs="0"
maxOccurs="unbounded"/>
use="optional" default="pass"/>
processContents="lax"/>
minOccurs="0" maxOccurs="unbounded"/>
use="optional" default="fail"/>
use="optional"/>
processContents="lax"/>
minOccurs="0" maxOccurs="unbounded"/>
use="optional" default="false"/>
processContents="lax"/>
