Mode=options
Seen=0,Send=Tag_A] ----------------------->
Mode=Options
Mode=options
Seen=Tag_Z,Send=1]
Mode=options                            Mode=options
Seen=0,Send=Tag_A] --------\   /-----   Seen=0, Send=Tag_Z]
Mode=options		         \---> [Header Flags=FIR|RES|ACK
Seen=Tag_Z,Send=Tag_A]----\             Mode=options          
                                   \ /-------   Seen=Tag_A,Send=Tag_Z]
                                    \ 
                                   / \-------> (Cancel T1-init timer)
Mode=options                               
Seen=Tag_Z,Send=1] ------------------> 
                                               ..
                                               [Header Flags=ACK|DAT  
Mode=options   
Mode=GAR
Part=0,Of=1
Seen=1,Send=1,Size=100]-------------> (Start T2-receive timer)
Mode=GAR
Part=0,Of=1
Seen=1,Send=101,Size=100]----------->
Mode=GAR
Part=0,Of=1
Seen=1,Send=201,Size=100]----------->
Mode=0
Part=0,Of=0
Seen=301,Send=1]
Mode=GAR
Part=0,Of=1
Seen=1,Send=301,Size=100]-----------> (Start T2-receive timer)
Mode=GAR
Part=0,Of=1
Seen=401,Send=1,Size=45]
Part=0,Of=0
Seen=46,Send=401]------------------> (cancel T3-send timer)
Mode=GAR
Part=0,Of=1
Seen=1,Send=501,Size=100]-----------> (Start T2-receive timer)
Mode=GAR
Part=0,Of=1                           {App sends 1 message}
Seen=1,Send=601,Size=100]-\       /-- (cancel T2-receive timer)
Mode=GAR
Part=0,Of=1
Seen=101,Send=601,Size=100]---------> (Cancel T3-send timer)
Mode=0
Part=0,Of=0
Seen=701,Send=101]


Mode=GAR
Part=0,Of=1
Seen=146,Send=701,Size=100]--------> (Start T2-receive timer)
Mode=GAR
Part=0,Of=1
Seen=146,Send=801,Size=100]-----X (lost)
Mode=GAR
Part=0,Of=1
Seen=146,Send=901,Size=100]--------> (A gap detected in data)
Mode=GAR
Part=0,Of=1
Seen=146,Send=701,Size=100]--------> (Start T2-receive timer)
Mode=GAR
Part=0,Of=1
Seen=146,Send=801,Size=100]-----X (lost)
Mode=GAR
Part=0,Of=1
Seen=146,Send=901,Size=100]--------> (A gap is detected)
Mode=GAR                          /  Mode=GAR
Part=0,Of=1                      /   Part=0,Of=1
Seen=146,Send=801,Size=100]-    /    Seen=801,Send=146,Size=100]
Part=0,Of=1
Seen=1001,Send=146,Size=100]
                                             (Restart T3-send timer)
Part=0,Of=0
Seen=246,Send=1001]----------------> (Cancel T3-send timer)

Mode=GAR
Part=0,Of=1
Seen=146,Send=1001,Size=100]--------> (Start T2-receive timer)
Mode=GAR
Part=0,Of=1
Seen=146,Send=1101,Size=100]-------->
Mode=GAR
Part=0,Of=1
Seen=146,Send=1201,Size=100]-------->
Seen=146,Send=1301]-----------------> (cancel T2-receive timer)
                                         /--- [Header Flags=ACK
                                        /       Mode=WNR
                                       /        Part=0,Of=0
                                      /         Seen=1301,Send=146]
Mode=GAR
Part=0,Of=1
Seen=146,Send=1301,Size=100]--------> (Start T2-receive timer)

Mode=GAR
Part=0,Of=1
Seen=46,Send=0x7ffff000,Size=100]----> (Start T2-receive timer)
Seen=146,Send=0x7ffff100]------------> (cancel T2-receive timer)
                                      /------- [Header Flags=ACK
                                     /          Mode=WNR
                                    /           Part=0,Of=0
                                   /            Seen=7fffff100,Send=46]
Mode=GAR
Part=0,Of=1
Seen=46,Send=2,Size=100]-------------> (Start T2-receive timer)
Part=0,Of=1
Seen=102,Send=46,Size=100]
                                               (Start T3-send timer)

Mode=SHU
Seen=146,Send=1301,------------------------> to Endpoint X

Mode=SHU
Seen=1496,Send=101,------------------------> to Endpoint Y

Mode=SHU
Seen=1460,Send=201-------------------------> to Endpoint Z

Mode=SHU
Seen=146,Send=1301]------------------------> to Endpoint X

Mode=GAR
Part=0,Of=1
Seen=1,Send=1,Size=100]-------------> (Start T2-receive timer)
Mode=GAR
Part=0,Of=1
Seen=1,Send=101,Size=100]----------->
Mode=GAR|RE1
Part=0,Of=1
Seen=1,Send=201,Size=100]----------->
Mode=0
Part=0,Of=0
Seen=301,Send=1]


Mode=UNR
Part=0,Of=1
Seen=1,Send=11001,Size=100]-------->

Mode=UNR
Part=0,Of=1
Seen=1,Send=11101,Size=100]-------->

                                             {App sends 1 message}
                                   <------- [Header Flags=DAT|ACK
Mode=UNR
Part=0,Of=1
Seen=11201,Send=1,Size=450]

Mode=UNR
Part=0,Of=1
Seen=451,Send=11201,Size=100]------>

Mode=UNR
Part=0,Of=1
Seen=451,Send=11301,Size=100]------>


Mode=UNR|RE1
Part=0,Of=1
Seen=1,Send=11001,Size=100]-------->

Mode=UNR|RE1
Part=0,Of=1
Seen=1,Send=11101,Size=100]\       /-->
                                    \     /
                                     \   /   (User reads/Receives all 
Mode=UNR|RE1                   \  
Part=0,Of=1                   / \ 
Seen=451,Send=11201,Size=100]/   \---> { Datagram is discarded }

Mode=UNR|RE1
Part=0,Of=1
Seen=1,Send=11301,Size=100]\       /-->
                                    \     /
                                     \   /   
Mode=UNR|RE1                   \  
Part=0,Of=1                   / \ 
Seen=451,Send=11401,Size=100]/   \--->(User reads/Receives all 
                                               datagrams in order
                                               11301 & 11401)




Mode=UNR
Part=0,Of=1
Seen=11201,Send=1,Size=450]
Mode=UNR
Part=0,Of=1
Seen=451,Send=11201,Size=100]------>

Mode=GAR
Part=0,Of=1
Seen=451,Send=11301,Size=100]------> (Start T2-receive timer)
Mode=GAR
Part=0,Of=1
Seen=451,Send=11401,Size=100]------> (Start T2-receive timer)
Mode=0
Part=0,Of=0
Seen=11501,Send=146]

Mode=GAR|BUN
Part=0,Of=1
Seen=146,Send=1001,Size=308]--------> (Start T2-receive timer)
Mode=0
Part=0,Of=0
Seen=1309,Send=146]

Mode=GAR|BUN
Part=0,Of=3
Seen=146,Send=1001,Size=4072]-------> (Start T2-receive timer)
Mode=GAR|BUN
Part=1,Of=3
Seen=146,Send=5073,Size=4072]------->
Mode=GAR|BUN
Part=2,Of=3
Seen=146,Send=9145,Size=400]-------->
Mode=BRO
Part=0,Of=1
Seen=0,Send=0,Size=200]--------------> (Datagram may appear
                                                more than once.)
Mode=BRO
Part=0,Of=1
Seen=0,Send=0,Size=100]-------------->

Mode=BRO|UNR
Part=0,Of=1
Seen=0,Send=5,Size=250]--------------> (may receive more
                                                than one copy)
Mode=BRO|UNR
Part=0,Of=1
Seen=0,Send=6,Size=500]--------------> (may receive more
                                                than one copy)


Mode=BRO|UNR
Part=0,Of=1
Seen=0,Send=17859,Size=300]---------->

Mode=BRO|UNR
Part=0,Of=1
Seen=1,Send=1,Size=250]--------------> (record new sequence
                                                number, datagram may
                                                appear more than once)
Mode=BRO|UNR
Part=0,Of=1
Seen=1,Send=2,Size=250]--------------> (may appear more than
                                                once)
Mode=BRO|UNR
Part=0,Of=1
Seen=1,Send=3,Size=500]--------------> (may appear more than
                                                once)
Mode=BRO|UNR
Part=0,Of=1
Seen=1,Send=4,Size=500]--------------> (may appear more than
                                                once)
Mode=BRO|UNR
Part=0,Of=1
Seen=0,Send=5,Size=100]--------------> (may appear more than
                                                once)


