n=50041&r=
r=<?xml version="1.0" encoding="utf-8"?>
OrigRegistrarId="50041" RecipientRegistrarId="50041" Rows="1">
           <FeTimeStamp Year="2007" Month="10" Day="19" Hour="14"
Minute="7" Second="51" TimeZoneOffset="+13:00" />
Minute="00" Second="00" TimeZoneOffset="+13:00" />
OrigRegistrarId="50041">
      <BillingAmount Amount="6.00">
          <EffectiveDate Year="2004" Month="01" Day="01" Hour="04"
Minute="00" Second="00" TimeZoneOffset="+13:00" />
Minute="00" Second="00" TimeZoneOffset="+13:00" />
Minute="00" Second="00" TimeZoneOffset="+13:00" />
Minute="00" Second="00" TimeZoneOffset="+13:00" />
Minute="00" Second="00" TimeZoneOffset="+13:00" />
RegistrantRef="Example registrant" RegistrarId="50041"
TransStatus="PendingConfirmation" Type="Create">
Second="31" TimeZoneOffset="+13:00" Year="2008" />
Second="31" TimeZoneOffset="+13:00" Year="2008" />
Second="31" TimeZoneOffset="+13:00" Year="2008" />
RegistrantRef="RS1001" RegistrarId="50041" Status="Active"
Term="1" UDAI="ke783oe9">
Email="j.smith@mydomain.example.org">
City="Wellington" CountryCode="NZ" PostalCode="6135" />
Email="admin@myisp.example.org">
City="Wellington" CountryCode="NZ" PostalCode="6001" />
Email="tech@myisp.example.org">
City="Wellington" CountryCode="NZ" PostalCode="6001" />
Day="1" Month="2" Year="2009" TimeZoneOffset="+13:00" />
Day="1" Month="2" Year="2008" TimeZoneOffset="+13:00" />
RegistrarId="50041">
Month="2" Year="2008" TimeZoneOffset="+13:00" />
Second="00" Day="1" Month="4" Year="2008" TimeZoneOffset="+13" />
Severity="er">
OrigRegistrarId="50041">
       <RawRequest>
           <XML>&lt;NZSRSRequest VerMajor="2" ...</XML>
           <Signature>-----BEGIN PGP SIGNATURE-----...</Signature>
       </RawRequest>
       <RawResponse>
           <XML>&lt;NZSRSResponse VerMajor="2" ...</XML>
           <Signature>-----BEGIN PGP SIGNATURE-----...</Signature>
       </RawResponse>
Email="custserv@myisp.example.org">
City="Wellington" CountryCode="NZ" PostalCode="6001" />
Email="admin@myisp.example.org">
City="Wellington" CountryCode="NZ" PostalCode="6001" />
Email="tech@myisp.example.org">
City="Wellington" CountryCode="NZ" PostalCode="6001" />
RegistrarId="50041">
Month="2" Year="2008" TimeZoneOffset="+13:00" />
CreateByRegistrarId="50001" Frequency="01:00:00"
Parameters="" ProcessName="BuildDnsZoneFiles">
Second="30" TimeZoneOffset="+13:00" Year="2008" />
City="Example" CountryCode="NZ" PostalCode="99001"
Province="" />
Minute="00" Second="00" TimeZoneOffset="+13:00" />
Minute="59" Second="59" TimeZoneOffset="+13:00" />
Minute="00" Second="00" TimeZoneOffset="+13:00" />

