ct=TBD2 stands for Content-Format "application/voucher-cms+cbor, and
ct=TBD3 stands for Content-Format "application/voucher-cose+cbor".

Ver = 1
T = 0 (CON)
Code = 0x01 (0.01 is GET)
Payload = [Empty]

Ver=1
T=2 (ACK)
Code = 0x45 (2.05 Content)
Payload =
MEgF10vqXv02gL1jLw==

Payload =
Payload =
CN=802.1AR CA
OU=IoT/serialNumber=Wt1234
CN=802.1AR CA
YMLOUz8sG0LxwItfwXs98ylUh0aGpAyLtw==
gqi4tMFfSJ0iEwt8kszfWXK4rLgJS2mnpQ==
VwW3k5FDSOH5PCuB6IzL4o6QgA9mlF77vs5PdB0O3hjrEAjvfponnA==
