a=video-resolution:<size> 
size="SQCIF" "=" mpi | "QCIF" "=" mpi | "CIF" "=" mpi | 
mpi=1*3DIGIT 
xmax=1*3DIGIT 
ymax=1*3DIGIT 
   
   
a=video-frame:<request> 
   
fmb=1*2DIGIT 
nmb=1*2DIGIT 
fgb=1*2DIGIT 
ngb=1*2DIGIT 
   
   

       5. IANA Considerations  
       
