r_b = [1, b, b^2, ..., b^(R-1)]

u_b = r_b*P
Extra=0 (OK)  The handshaking procedure completed successfully and
         the streaming toward the new lower peers has started.

Extra=1 (NO_Resource)  The node has exhausted its share of upload
         bandwidth and it cannot satisfy the request.

Extra=2 (NO_Reply)  The handshaking procedure did not complete
         successfully since the lower peer did not acknowledge the
         Set_Default request (see the handshaking procedure in
         Section 6).
Extra=0 (OK)  No error, the streaming toward the lower peers has
         stopped.

Extra=3 (NO_Target)  The target specified in the packet is not a
         lower peer of the node or it is not receiving data from the
         specified channel.

Extra=0 (OK)  No error, the streaming to the old lower peers has
         stopped and the streaming to the new peer has started.

Extra=2 (NO_Reply)  The handshaking procedure did not complete
         successfully since the lower peer did not acknowledge the
         Set_Default request (see the handshaking procedure
         (Section 6)).  The streaming to the old peer is nevertheless
         stopped.

Extra=3 (NO_Target)  The old peer is not a lower peer of the node.
         No action is taken.

NAT_Method=0 is assigned by [ppetp-ice] to an ICE-based
Version=4 (IPv4)  The Address field is 32 bits long and
            contains the IPv4 address

Version=6 (IPv6)  The Address field is 128 bits long and
            contains the IPv6 address

K=H(S | NONCE)
v=0
c=IN IP4 ppetp.example.com
m=video 12345 RTP/AVP/PPETP 34
a=control: rtsps://live.example.com/concert/video

USERNAME=bob, USE-NONCE=88888,
LOCAL-NONCE=11111, SIGNATURE=23xgajdav)

NONCE=88888, LOCAL-NONCE=25252,
PROTOCOL=https,
PARAMETER=netmanager.example.com/12345?q=da...c23,
SIGNATURE=daghj391)

tr-id="32455"/>
v=0
c=IN IP4 alice.example.com
m=video 4242 RTP/AVP/PPETP 34

r = [1, B, B^2, ..., B^(R-1)]

U=r*G

C=2^(d-1) c_{d-1} + 2^(d-2) c_{d-2} + ... 2 c_1  + c_0
C = b_0 + 256 b_1 + 256^2 b_2 + ...

L=(gf_size*R) * ceil (length (P) / (gf_size*R))
