X_Pps = -----------------------------------------------
              R * (sqrt(2*p/3) + 12*sqrt(3*p/8)*p*(1+32*p^2))

OH = 40 / Outer Payload Size / Inner Packet Size
NF0 = ----------------------------------
            Outer Payload Size - IP Overhead

NF = CEILING(NF0)

OH = NF * (IP Overhead + IPsec Overhead)
          - IP Overhead
          + NF * (Outer Payload Size - IP Overhead)
          - Inner Payload Size

OH = NF * (IPsec Overhead + Outer Payload Size)
          - (IP Overhead + Inner Payload Size)

OH = NF * (IPsec Overhead + Outer Payload Size)
          - Inner Packet Size

