PDV=D99.9thPercentile - Dmin

MoE= alpha * ----------
                 sqrt(N)

Xpd= ----------- * 100, where: X1 - result for 1-flow
                 X1                   Xn - result for n-flows




