priority="***" type="***"/>
priority="***" type="***"/>
port="###" />                  <!-- IPv4 -->
port="###" />                  <!-- IPv6 -->
LiveStream=TRUE the Tracker will will additionally search the
port="###" />
port="###" />
bitmapsize="###">
targetNamespace="http://www.example.org/ppsp/"
elementFormDefault="qualified">
 




namespace="http://www.example.org/manifest/"
schemaLocation="manifest.xsd" />	
type="ppsp:TrackerMessage" />
maxOccurs="1" />
maxOccurs="1" />
maxOccurs="1" />
maxOccurs="1" />
maxOccurs="1" 
type="xs:dateTime" />
maxOccurs="1">
maxOccurs="unbounded" 
type="ppsp:PeerAddress" />
maxOccurs="1">
maxOccurs="unbounded" 
type="ppsp:Stat" />
maxOccurs="1">
maxOccurs="unbounded" 
type="ppsp:PeerInfo" />
maxOccurs="1">
maxOccurs="unbounded" 
type="ppsp:PeerAddress" />
maxOccurs="1" 
type="xs:string" />
 




maxOccurs="1" 
type="xs:string" />
maxOccurs="1" 
type="xs:integer" />
minOccurs="0" maxOccurs="1" />
maxOccurs="1" 
type="xs:integer" />
maxOccurs="1">
type="manifest:ChunkSegment" />
substitutionGroup="ppsp:ProtoDirection">
