prop-restriction    = "(" description component method
               1*MUST-component *MAY-component *not-component ")"

description    = "DESCRIPTION" *ws text
component      = "COMPONENT" *ws ("CALPROPOS" / "VEVENT" /
                      "VTODO" / "VJOURNAL")
method         = "METHOD" *ws <any of the methods defined in this
                       memo for the associated calendar component>

MUST-component = "MUST COMPONENT =" *ws ("VEVENT" / "VTODO" /
                      "VJOURNAL" / "VTIMEZONE" / "VALARM" /
                      "VFREEBUSY" / "X-TOKEN")
                      *ws "(" [ws] 1*MUST-props *ws
                      *MAY-props *ws *not-props *ws ")"

MAY-component  = "MAY COMPONENT =" *ws ("VEVENT" / "VTODO" /
                      "VJOURNAL" / "VTIMEZONE" / "VALARM" /
                      "VFREEBUSY" / "X-TOKEN")
                      *ws "(" [ws] ((*MUST-props *ws
                      *MAY-props *ws *not-props *ws) / any) ")"

not-component  = "NOT COMPONENT =" *ws ("VEVENT" / "VTODO" /
                      "VJOURNAL" / "VTIMEZONE" / "VALARM" /
                      "VFREEBUSY" /"X-TOKEN")

MUST-props     = "MUST PROPERTY =" *ws restriction-list
MAY-props      = "MAY PROPERTY =" *ws (restriction-list / any)
not-props      = "NOT PROPERTY =" *ws (restriction-list)

restriction-list    = restriction
                         / restriction *ws "," *ws restriction
restriction    = property-name
                      [*ws "{" parm-or-val-restriction "}"]
property-name  = <any of the valid properties for the component>
parm-or-val-restriction  = <a text string description of a
                    constraint on the property parameters
                    or values>
any       = "ANY"  -- Specifies that any permissible
                 properties are allowed - -

ws        = HTAB / SPACE

HTAB      = <Horizontal TAB character>
SPACE     = <Required Space character>
STATUS=NEEDS-ACTION on Attendees}, DESCRIPTION{MAYBE
STATUS=NEEDS ACTION, Owner and Organizer if different,
TO="Mailto:E@example.com":Mailto:C@example.com
DELEGATED-FROM=_Mailto:C@example.com_:Mailto:E@example.com
DELEGATED-TO="Mailto:E@example.com":Mailto:C@example.com
DELEGATED-FROM="Mailto:C@example.com":Mailto:E@example.com
DELEGATED-FROM="Mailto:C@example.com":Mailto:E@example.com
DELEGATED-FROM="Mailto:C@example.com":Mailto:E@example.com
