NAME_NFS_URL    = 1,
NAME_NFS_IP     = 2,
NAME_SMB        = 3
NAME_IPV4       = 1,
NAME_IPV6       = 2
NAME_ACCESS     = 1,
NAME_MASTER     = 2,
NAME_VOLID      = 3,
NAME_STRING     = 4
NAME_RO         = 0,
NAME_RW         = 1
Fd = open("/nfs/sun.com/corp/data/spreadsheet.pdf", ...);

NAME_NFS_URL    = 1,
NAME_NFS_IP     = 2,
NAME_SMB        = 3
NAME_IPV4       = 1,
NAME_IPV6       = 2
NAME_ACCESS     = 1,
NAME_MASTER     = 2,
NAME_VOLID      = 3,
NAME_STRING     = 4
NAME_RO         = 0,
NAME_RW         = 1
