Type="Authorize-Only" when the session terminates in order to refund
Service-Type="Authorize-Only" must contain a State attribute.
PPAC=00...00011}
PPAQ={QID=5, VQ = 5MB,
VTH = 4.5 MB}}
PPAQ={QID=5, VQ=4.5MB,
REASON=THRESHOLD REACHED}}
PPAQ={QID=8, VQ=12MB,
VTH = 11.5 MB}}
PPAQ={QID=8, VQ=7 MB,
REASON=ACCESS SERV TERMINATED}}
Reason="initial request" is included (see Section 3.7.1).  The PPS
PPAC=00...00111}
PPAQ={QID=5, VQ = 20MB,
VTH = 18 MB}, PTS={
QID=5, PTS{TSI=300sec,
TITSU=6000sec}}
PPAQ={QID=5, VQ=14MB,
REASON=TITSU APPROACH.},
TSI={QID=5, VUATS=11MB}}
PPAQ={QID=8, VQ=30MB,
VTH = 28 MB},PTS={
QUD=8, PTS=95 sec}}
PPAQ={QID=8, VQ=17 MB,
REASON=ACCESS SERV TERMINATED},
PTS={QID=8, VUATS=2.5 MB}
PPAC=00...00101111}
PPAQ={QID=5, VQ = 5MB,
poolID=1,mult=1}}
SID="A", RGROUP=1}}
                           -------(6)-------->

                           [allocates 50 min
                                       quota]

PPAQ={QID=7, DQ=3000sec
poolID=1,RGROUP=1, SID="A"
mult=1747.63}}
PPAQ={QID=5, VQ=4MB,
REASON=QUOTA REACHED,
PoolID=1, mult=1}
PPAQ={QID=7, DQ=3300sec
REASON=QUOTA REACHED,
PoolID=1, mult=1747.63,
SID="A",RGROUP=1}}
PPAQ={QID=8, VQ=8MB,
PoolID=1, mult=1, RGROUP=1},
PPAQ={QID=9, DQ=4800sec
PoolID=1, mult=1747.63,
SID="A"}}
PPAQ={QID=8, VQ=6.5MB,
REASON=ACCESS SERV TERMINATED,
PoolID=1, mult=1}
PPAQ={QID=9, DQ=5400sec
REASON=ACCESS SERV TERMINATED,
PoolID=1, mult=1747.63,
SID="A",RGROUP=1}}
multiplier = 1 for the access service.  Note that, since 5MB =
PoolID=1 and the multiplier is 1.  Similarly, the PPAQ that grants
PoolID=1 and multiplier=1747.63.  The resulting Access Response
PPAQ={QID=321, SID=X, RQ=650,
REASON=10 (ONE-TIME CHARGING}}
PPAQ={SID=X, VQ=10MB,
REQ_ACT=2(PRICE ENQUIRY}}
PPAQ={SID=X, VQ=10MB,
PPAQ={SID=X, VQ=10MB,
REQ_ACT=BALANCE CHECK}}
PPAQ={SID=X, VQ=10MB,
