telephone-uri       =  "tel:" subscriber *param                       |
subscriber          =  global-number / local-number                   |
global-number       =  global-number-part [isdn-subaddress]           |
global-number-part  =  "+" 1*phonedigit                               |
local-number        =  local-number-part [isdn-subaddress]            |
                               [context]                                      |
local-number-part   =  1*phonedigit                                   |
isdn-subaddress     =  ";isub=" 1*phonedigit                          |
context             =  ";phone-context=" descriptor *("," descriptor) |
descriptor          =  domainname / global-number-part                |
domainname          =  *( domainlabel "." ) toplabel [ "." ]          |
domainlabel         =  alphanum                                       |
                               / alphanum *( alphanum / "-" ) alphanum        |
toplabel            =  ALPHA / ALPHA *( alphanum / "-" ) alphanum     |
param               =  ";" pname ["=" pvalue ]                        |
pname               =  1*uric                                         |
pvalue              =  *uric                                          |
phonedigit          =  HEXDIG / visual-separator                      |
visual-separator    =  "-" / "." / "(" / ")"                          |
alphanum            =  ALPHA / DIGIT                                  |


