a=max-sources:<source count>
a=max-sources:unlimited


max-sources-attr = "max-sources:" ( 1*DIGIT / "unlimited" )

attribute =/ max-sources-attr

           Figure 1: Syntax of the "max-sources" media attribute


