Transaction = 50003 {
Context = $ {
Add = A5555  { Media {
Stream = 1 {
                       LocalControl {
Mode = SendReceive,
Events=1234{
                          al/on, dd/ce {DigitMap=Dialplan0}},
DigitMap= Dialplan0{(8xxxxxxx)}
Transaction = 50003 {
Context = $ {
Add = A5555  { Media {
Stream = 1 {
                       LocalControl {
Mode = SendReceive,
Events=1234{
                       al/on, dd/ce {DigitMap=Dialplan0}},
DigitMap= Dialplan0{(8xxxxxxx)}
                       }}}
   
Transaction = 50003 {
Context = $ {
Add = $  { Media {
Stream = 1 {
Mode = SendReceive,
v=0
   
   
c=IN IP4 $
m=audio $ RTP/AVP 4
a=ptime:30
