xmlns="urn:ietf:params:xml:ns:nttdm-1.0"
targetNamespace="urn:ietf:params:xml:ns:nttdm-1.0"
elementFormDefault="qualified"
attributeFormDefault="unqualified">
type="nttdm:eTT_Short_Description"/>

type="nttdm:eTT_Impact_Assessment"/>

type="nttdm:stringlist"/>





 



