param      = impp-param ; Only impp parameters are allowed

value      = uri

impp-param = "TYPE" "=" impp-type *("," impp-type)

impp-type  = "PERSONAL" / "BUSINESS" / ; purpose of communications
                 "HOME" / "WORK" / "MOBILE" /
                 "PREF" /
                 iana-token / x-name;
                 ; Values are case insensitive


