LossComp = 10 * sqrt(Loss{Link});
LossComp = 3;
PathEquivLoad = 0;
Load = LinkEquivLoad{Link}
PathEquivLoad = Load;
PathSetMaxLoad = 0;
Load = PathEquivLoad{Path};
PathSetEquivLoad = Load;
PathSetEquivLoad = Load;
PathSetMaxLoad = Load;
Load = PathSetEquivLoad{PathSet};
TotalTraffic = 0;
TotalCapacity = 0;
Capacity = LinkCapacity{Link};
Capacity = LinkCapacity{Link};
Then = PathSetArray{PathSet,Util};
Elapsed = NOW - Then;
LoadComp = LOAD_COMP_OFFS
                  + ((MAX_NEW_PATH - Util) / MAX_NEW_PATH);
PathContribution = PATH_COMP_OFFS
                      + GetPathContribution(PathSet);
NewPaths = FindAlternatePath(PathSet);
BestNewPath = GetBestNewPath(NewPaths);
MostCapacity = 0;
ExcessCapacity = LinkCapacity{Link}
                      * (1 - PathEquivLoad{NewPath});
Capacity = ExcessCapacity;
Capacity = ExcessCapacity;
MostCapacity = Capacity;
BestNewPath = NewPath;
Load = PathSetEquivLoad{PathSet};
NewPaths = SPF(Egress{PathSet});
TargetShare = 0;
TargetIncr = INITIAL_MOVE_INCREMENT;
MaxLoad = PathSetMaxLoad{PathSet};
Elapsed = NOW - PathSetBelowMax{PathSet};
Traffic = 0;
ExcessCapacity = 0;
Excess = ExcessCapacity(Path);
TimeToDeletion = PATH_DEL_PERSIST
              * (1 + (Traffic / ExcessCapacity));
HighCost = 0;
Cost = PathLinkCosts(Path);
PathToDelete = Path;
HighCost = Cost;
LowShare = TrafficShare{PathSet,Path};
TargetShare = TrafficShare{PathSet,PathToDelete};
Shares = TargetShare
                      * Capacity{Path} / TotalCapacity;
Shares = 1;
Shares = TrafficShare{PathSet,PathToDelete};
Egress = Egress{PathSet};
Elapsed = NOW - LastRecheckSPF{PathSet};
RelativeLoad = GetPathContribution(PathSet);
Paths = FindAlternatePath(PathSet);
BestNewPath = GetBestNewPath(NewPaths);
NewCost = PathLinkCosts(BestNewPath);
