header = stream-type payload-size

stream-type =  %x6D /              ; m for main stream
                     %x73 /              ; s for sub stream
                     %x74                ; t for end of sub stream 

payload-size = quotation-mark      ;an integer in quotes
                     digit * ( digit ) 
                     quotation-mark  

quotation-mark = %x22              ; "

digit = %x30-39                    ; a text number

instruction     =   function-name arg-list

function-name   =   quote escaped-string quote

arg-list        =   start-arg-list [ arg *(arg-separator arg ) ]
 




arg             =   null / quote escaped-string quote

quote           =   %x22              ; "

start-arg-list  =   %x5B              ; [

end-arg-list    =   %x5D              ; ]

arg-separator   =   %x2C              ; ,

