R = RTT * ( 1 + 1/(cwnd/smss) )

TSecr = <SYN>.TSval XOR TS.return


C  = (TSecr >> local mask) - (TSval >> remote mask) * ---------------
    t                                                    local interval

ADJ = FRAC.rem / FRAC.loc

