Keys = KDFi(master-secret, client-random, server-random, other-
Keys = KDF(master-secret, client-random, server-random, other-
Keys = KDF(master-secret, client-random, server-random, other-
M1 = M || 0:L || Pad* 
    
MAC = HMAC(Ki, M1) 
    
Data = {M2}Kc 
    
KDF= PRF(master_secret, label, 
            client-random || server-random ||  
            context-value-length || context-value) 
    
    
s = PRK = HMAC(client-random || server-random, master-secret) 
    
KDF = PRF(PRK, f(L, Label, context)) 
    
