dilation=nnn
         Typically IP packets will be MIME labeled for transmission over
         email or other application level protocols.  Such transmission
         is normally slower than lower level network protocols.  If such
         transmission is being used to establish connectivity, the
         sender of a datagram may wish to advice the recipient of the
         estimated time dilation factor.  For example, if datagrams
         typically take around a second and occsionally up to ten
         seconds end-to-end but its more like a minute and occasionally
         up to ten minutes if they are MIME encoded in email, a
         "dilation=60" parameter would be reasonable.  Although IP and
         TCP are defined as timing idependent protocols, many
         implementations actually have timeouts built in.  An effective
         technique in some cases to defeat these timeouts is to
         repeatedly resend the last packet received.  This is, if a MIME
         encoded TCP packet is being sent from Host A to Host B in the
         figure above where the applications are gatewaying the packets
         to the real IP stack, repeated transmisison of this packet by
         the application on Host B to the stack may stave off timeouts.
         Similarly, the repeated transmission to the real IP stack on
         Host A of the last reply TCP packet may stave off time outs
         there.

address=xxx,mmm
         Full, if slow, IP connectivity via an application level
         protocol such as RFC 822 email, in the absence of NAT
         technology, would require that routing nad/or interface entries
         be installed at each end.  This parameter enables the sender to
         indicate what address mask and value it wishes to have
         installed in routing and/or interfacetables at the receiver
         host so as to accomplish this. Return traffic matching this
         address/mask should be routed as indicated for specific
         protocols below.  A ficticious example would be
         "address=10.9.8.0,255.255.255.0".








