P-Early-Media = "P-Early-Media" HCOLON  
                       [ em-param *(COMMA em-param) ] 
em-param      = "sendrecv" / "sendonly" / "recvonly"  
                       / "inactive" / "gated" / token 
    
    
