ADJ=18).  The latter representation carries more significant
R = RTT * ( 1 + 1/(cwnd/smss) )

C  = (TSecr >> local mask) - (TSval >> remote mask) * ---------------
    t                                                    local interval

ADJ = FRAC.rem / FRAC.loc

