RM =00.  The R_res of its Qos routing table entry is assigned
RM =01, to update the bandwidth reservation.  An intermediate node
avgQi = 0
count = -1
avgQ = (1 - Wq) x avgQ + Wq x Q,
m = f(idle time, S),
avgQ = (1 – Wq)^m x avgQ,
P_b = maxp x (avgQi – minth_Qi)/(mawth_Qi – minth_Qi),
P_a = p_b/(1 – count x p_b),  
count = 0,
count = 0,
count = -1,

