d= Author domain (plain-text; REQUIRED).  This value names the domain
      of the Author, which is delegating signing authority to one or
      more other domains.

t= Delegation target (plain-text; OPTIONAL).  This value is a comma-
      separated list of domain names to which the authority to sign on
      behalf of the Author domain is being delegated.  When not present,
      this list is inferred from the domain names present in the
      recipient fields (To, Cc) of the header.

