parent="true"> field.  All the child CSV file definition data for the
type="emailFwd:emailAddrType" and isRequired="true".

isRequired="true".

type="positiveInteger".  The attribute "isRequired" MUST equal
cksum="F72A19A8">
isRequired="true".

cksum="B3FBC311">
type="emailFwd:emailAddrType" and isRequired="true".

type="emailFwd:statusValueType" and isRequired="true".

cksum="A7A59EB0">
isRequired="true".

isRequired="true".
isRequired="true".

isRequired="true".

cksum="C71A9998">
isRequired="true".

cksum="6B23C283">
isRequired="true".

isRequired="true".

type="positiveInteger".  The attribute "isRequired" MUST equal
cksum="3019A23F">
type="defReg:statusValueType" and isRequired="true".

cksum="21D85E27">
isRequired="true".

isRequired="true".

isRequired="true".

cksum="6303FBAF">
cksum="B6ED701B">
type="nameWatch:nameType" and isRequired="true".

type="nameWatch:emailAddrType".

type="nameWatch:freqType" and the possible values of "daily",
isRequired="true".

type="positiveInteger".  The attribute "isRequired" MUST equal
cksum="75E2D01F">
type="nameWatch:statusValueType" and isRequired="true".
cksum="A2C261DC">
isRequired="true".

isRequired="true".

isRequired="true".

cksum="FE25CA7B">
cksum="6D4BB372">
targetNamespace="http://www.nic.name/rde/rdeEmailFwd-1.0"
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

type="rdeEmailFwd:abstractContentType"
substitutionGroup="rde:content" abstract="true"/>
substitutionGroup="rdeEmailFwd:abstractEmailFwd"/>
type="rdeEmailFwd:deleteType"
substitutionGroup="rde:delete"/>

minOccurs="0" maxOccurs="11"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
type="rde:rrType"/>
minOccurs="0"/>
type="rde:rrType" minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
type="rdeEmailFwd:transferDataType"
minOccurs="0"/>
type="eppcom:trStatusType"/>
type="rde:rrType"/>
type="dateTime"/>
type="rde:rrType"/>
type="dateTime"/>
type="dateTime" minOccurs="0"/>
type="emailFwd:emailAddrType" minOccurs="0"
maxOccurs="unbounded"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

substitutionGroup="rde:content"/>

substitutionGroup="rde:delete"/>
substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

default="emailFwd\:emailAddrType"/>
substitutionGroup="rdeCsv:field"/>
default="emailFwd\:contactAttrType"/>
substitutionGroup="rdeCsv:field"/>
default="emailFwd\:statusValueType"/>
targetNamespace="http://www.nic.name/rde/rdeDefReg-1.0"
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

type="rdeDefReg:abstractContentType"
substitutionGroup="rde:content" abstract="true"/>
substitutionGroup="rdeDefReg:abstractDefReg"/>
type="rdeDefReg:deleteType"
substitutionGroup="rde:delete"/>

minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="11"/>
type="rde:rrType"/>
minOccurs="0"/>
type="rde:rrType" minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
type="rdeDefReg:transferDataType"
minOccurs="0"/>
type="eppcom:trStatusType"/>
type="rde:rrType"/>
type="dateTime"/>
type="rde:rrType"/>
type="dateTime"/>
type="dateTime" minOccurs="0"/>
type="eppcom:roidType" minOccurs="0"
maxOccurs="unbounded"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

substitutionGroup="rde:content"/>

substitutionGroup="rde:delete"/>

substitutionGroup="rdeCsv:field"/>
default="defReg\:nameType"/>
substitutionGroup="rdeCsv:field"/>
default="defReg\:levelType"/>
substitutionGroup="rdeCsv:field"/>
default="defReg\:statusValueType"/>
substitutionGroup="rdeCsv:field"/>
default="defReg\:tmType"/>
substitutionGroup="rdeCsv:field"/>
default="defReg\:ccType"/>
substitutionGroup="rdeCsv:field"/>
default="date"/>
substitutionGroup="rdeCsv:field" />
default="eppcom\:clIDType" />
targetNamespace="http://www.nic.name/rde/rdeNameWatch-1.0"
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">
type="rdeNameWatch:abstractContentType"
substitutionGroup="rde:content" abstract="true"/>
substitutionGroup="rdeNameWatch:abstractnameWatch"/>
type="rdeNameWatch:deleteType"
substitutionGroup="rde:delete"/>

minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="11"/>
type="rde:rrType"/>
minOccurs="0"/>
type="rde:rrType" minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
type="rdeNameWatch:transferDataType"
minOccurs="0"/>
type="eppcom:trStatusType"/>
type="rde:rrType"/>
type="dateTime"/>
type="rde:rrType"/>
type="dateTime"/>
type="dateTime" minOccurs="0"/>
type="eppcom:roidType" minOccurs="0"
maxOccurs="unbounded"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

substitutionGroup="rde:content"/>

substitutionGroup="rde:delete"/>

substitutionGroup="rdeCsv:field"/>
default="nameWatch\:nameType"/>
substitutionGroup="rdeCsv:field"/>
default="nameWatch\:emailAddrType"/>
substitutionGroup="rdeCsv:field"/>
default="nameWatch\:freqType"/>
substitutionGroup="rdeCsv:field"/>
default="nameWatch\:statusValueType"/>
