av-pairs        =       av-pair *(";" av-pair)
av-pair         =       attr ["=" value]                ; optional value
attr            =       token
value           =       token | quoted-string

set-cookie      =       "Set-Cookie2:" cookies
cookies         =       1#cookie
cookie          =       NAME "=" VALUE *(";" set-cookie-av)
NAME            =       attr
VALUE           =       value
set-cookie-av   =       "Comment" "=" value
                |       "CommentURL" "=" <"> http_URL <">
                |       "Discard"
                |       "Domain" "=" value
                |       "Max-Age" "=" value
                |       "Path" "=" value
                |       "Port" [ "=" <"> portlist <"> ]
                |       "Secure"
                |       "Version" "=" 1*DIGIT
portlist        =       1#portnum
portnum         =       1*DIGIT

NAME=VALUE
     REQUIRED.  The name of the state information (``cookie'') is NAME,
     and its value is VALUE.  NAMEs that begin with $ are reserved and
     MUST NOT be used by applications.

     The VALUE is opaque to the user agent and may be anything the
     origin server chooses to send, possibly in a server-selected
     printable ASCII encoding.  ``Opaque'' implies that the content is
     of interest and relevance only to the origin server.  The content
     may, in fact, be readable by anyone that examines the Set-Cookie2
     header.

Comment=value
     OPTIONAL.  Because cookies can be used to derive or store private
     information about a user, the value of the Comment attribute allows
     an origin server to document how it intends to use the cookie.  The
     user can inspect the information to decide whether to initiate or
     continue a session with this cookie.  Characters in value MUST be
     in UTF-8 encoding. [RFC2279]

CommentURL="http_URL"
     OPTIONAL.  Because cookies can be used to derive or store private
     information about a user, the CommentURL attribute allows an origin
     server to document how it intends to use the cookie.  The user can
     inspect the information identified by the URL to decide whether to
     initiate or continue a session with this cookie.

Domain=value
     OPTIONAL.  The value of the Domain attribute specifies the domain
     for which the cookie is valid.  If an explicitly specified value
     does not start with a dot, the user agent supplies a leading dot.

Max-Age=value
     OPTIONAL.  The value of the Max-Age attribute is delta-seconds, the
     lifetime of the cookie in seconds, a decimal non-negative integer.
     To handle cached cookies correctly, a client SHOULD calculate the
     age of the cookie according to the age calculation rules in the
     HTTP/1.1 specification [RFC2616].  When the age is greater than
     delta-seconds seconds, the client SHOULD discard the cookie.  A
     value of zero means the cookie SHOULD be discarded immediately.

Path=value
     OPTIONAL.  The value of the Path attribute specifies the subset of
     URLs on the origin server to which this cookie applies.

Version=value
     REQUIRED.  The value of the Version attribute, a decimal integer,
     identifies the version of the state management specification to
     which the cookie conforms.  For this specification, Version=1
     applies.

cookie          =       "Cookie:" cookie-version 1*((";" | ",") cookie-value)
cookie-value    =       NAME "=" VALUE [";" path] [";" domain] [";" port]
cookie-version  =       "$Version" "=" value
NAME            =       attr
VALUE           =       value
path            =       "$Path" "=" value
domain          =       "$Domain" "=" value
port            =       "$Port" [ "=" <"> value <"> ]

cookie2 =       "Cookie2:" cookie-version

Path="/acme"

Customer="WILE_E_COYOTE"; $Path="/acme";
Part_Number="Rocket_Launcher_0001"; $Path="/acme"
Customer="WILE_E_COYOTE"; $Path="/acme";
Part_Number="Rocket_Launcher_0001"; $Path="/acme";
Shipping="FedEx"; $Path="/acme"
Path="/acme"

Path="/acme/ammo"

Part_Number="Riding_Rocket_0023"; $Path="/acme/ammo";
Part_Number="Rocket_Launcher_0001"; $Path="/acme"

session_id="1234" and sets the default domain victim.cracker.edu.

session-id="1111", with Domain=".cracker.edu".

