Strm=0,Seq=1 & user data]--\
Frag=0]      --------\  /        [TSN=init TSN_Z +1,
                            \/          Strm=0,Seq=2 & user data 2]
                     <------/\          
                              \
                               \------>

ssthresh = max(cwnd/2, 2*MTU)
cwnd = ssthresh

