Class  =  9  (FlowSpec class) 
Class  = 12  (Sender_Tspec class) 
 
C-type =  3  (MPLS Sender_Tspec/FlowSpec object) 
 
SubObj-num = 1 : OA-Traffic Profile PHBID 
                
SubObj-num = 2 : OA-Traffic Profile Simple Exp 
           

  
TP-style = 1  (Tspec parameters as defined for RSVP) 
      
TP-style = 2  (Simple bandwidth parameter) 
       
Code = 14, see Appendix B of [1]). 
 
