name="distributed printer service">
name="purchase order processing">
ENP = "ENP" ":" "1.0"

If = "If" ":" ( 1*No-tag-list | 1*Tagged-list)
No-tag-list = List
Tagged-list = Resource 1*List
Resource = Coded-url
List = "(" 1*(["Not"](State-token ")"
State-token = Coded-url
Coded-url = "<" URI ">"
