Query = getPassword(userid = Request.UserID)
destination = Request.Destination,
bandwidth = Request.Bandwidth,
starttime = Request.StartTime,
duration = (Request.StopTime - Request.StartTime))
Reply = Authentication@131.211.32.73(
Identity = Request.Identity,
AuthenticationData = Request.AuthenticationData )
KRBReply = authenticate( username = Request.Identity.UserName,
servername = Request.AuthenticationData.ServerName,
preauthentication =
                             Request.AuthenticationData.PreAuthentication );

