OPES-System = "OPES-System" ":" #trace-entry

OPES-Processor = "OPES-Processor" ":" #trace-entry

OPES-Service = "OPES-Service" ":" #trace-entry

trace-entry = opes-agent-id *( ";" parameter )

opes-agent-id = absoluteURI


Mode = Aggregate

