targetNamespace="urn:ietf:params:xml:ns:media_control" 
elementFormDefault="qualified" xmlns=" 
minOccurs="0" maxOccurs="unbounded" /> 
                  <xsd:element name="general_error" type="xs:string" 
minOccurs="0" maxOccurs="unbounded" /> 
               </xsd:sequence> 
            </xsd:complexType> 
        </xsd:element> 
         
        <!-- Video control primitive. Each primitive is directed either 
minOccurs="0" maxOccurs="unbounded" /> 
           </xsd:sequence> 
           <xsd:attribute name="type" type="primitive_type" 
use="optional" default="cmd" /> 
           <xsd:attribute name="stream" type="stream_type" 
use="optional" default="all" /> 
        </xsd:complexType> 
         
        <xsd:simpleType name="primitive_type"> 
                <xsd:restriction base="xsd:string"> 
                        <xsd:enumeration value="cmd" /> 
                        <xsd:enumeration value="ind" /> 
                        <xsd:enumeration value="req" /> 
                        <xsd:enumeration value="rsp" /> 
                </xsd:restriction> 
        </xsd:simpleType> 
 
        <xsd:simpleType name="stream_type"> 
                <xsd:restriction base="xsd:string"> 
                        <xsd:enumeration value="mid" /> 
     
type="xsd:nonNegativeInteger" use="optional" default="0" /> 
                        <xsd:attribute name="no_of_gobs" 
type="xsd:nonNegativeInteger" use="optional" default="1" /> 
                    </xsd:complexType> 
                </xsd:element> 
                <xsd:element name="mb_fast_update"> 
                   <xsd:complexType> 
                       <xsd:attribute name="first_gob" 
type="xsd:nonNegativeInteger" use="optional" default="0" /> 
                           <xsd:attribute name="first_mb"  
type="xsd:nonNegativeInteger" use="optional" default="1" /> 
                       <xsd:attribute name="no_of_mbs" 
type="xsd:nonNegativeInteger" use="optional" default="1" /> 
                   </xsd:complexType> 
                </xsd:element> 
            </xsd:choice> 
        </xsd:complexType> 
    
content="text/html;charset=utf-8"/> 
