acp-information = acp-device-info "@" acp-domain

acp-device-info = "ani.acp+" acp-address [ "+" rsub extensions ]

acp-address = 32hex-dig

hex-dig = DIGIT / "a" / "b" / "c" / "d" / "e" / "f"

rsub = [ domain-name ] ; empty if not used

acp-domain = domain-name

routing-subdomain = [ rsub " ." ] acp-domain

domain-name = ; <domain> according to section 3.5 of [RFC1034]

extensions = *( "+" extension )

extension = ; future definition.  Must fit into [RFC5322] simple dot-
acp-information =   anima.acp+fda379A6f6ee00000200000064000000+area51
routing-subdomain = area51.research.acp.example.com

flood-message = [M_FLOOD, session-id, initiator, ttl,
                     +[objective, (locator-option / [])]]

objective = ["AN_join_registrar", objective-flags, loop-count,
                                           objective-value]

objective-flags = sync-only  ; as in GRASP spec
sync-only =  4               ; M_FLOOD only requires synchronization
loop-count      = 255        ; mandatory maximum
objective-value = text       ; name of the (list of) of supported
                                 ; protocols: "EST-TLS" for RFC7030.

flood-message = [M_FLOOD, session-id, initiator, ttl,
                            +[objective, (locator-option / [])]]

objective = ["AN_ACP", objective-flags, loop-count,
                                                  objective-value]

objective-flags = sync-only ; as in the GRASP specification
sync-only =  4    ; M_FLOOD only requires synchronization
loop-count = 1    ; limit to link-local operation
objective-value = text ; name of the (list of) secure
                                  ; channel negotiation protocol(s)

Zone = zero is the default addressing scheme in an autonomic domain.
remote-peer = [ local-address, method, remote-address ]
local-address  = ip-address
remote-address = transport-address
transport-address =
          [ (ip-address | pattern) ?( , protocol ?(, port)) (, pmtu) ]
ip-address = (ipv4-address | ipv6-address )
method = "IKEv2" / "dTLS" / ..
pattern = some IP address set

