AMSK = KDF(EMSK, key label, optional application data) 
    

 
 
 
 
KDF = PRF(EMSK, key label + "\0", application data) 
    
EAP-CMSK_0 = EMSK_0 
EAP-CMSK_n =  
         PRF(EAP-CMSK_n-1, "combined master session key", EMSK_n) 
 
 
 
 
        
EAP-CMSK_n = PRF(EAP-CMSK_n-1 + EMSK_n, "combined master session 
