targetNamespace=
elementFormDefault="qualified" version="5.11">
namespace="http://oval.mitre.org/XMLSchema/
schemaLocation="oval-common-schema.xsd"/>
namespace="http://www.w3.org/2000/09/xmldsig#"
schemaLocation="xmldsig-core-schema.xsd"/>
uri="http://www.w3.org/2001/XMLSchema-instance"
name="oval_system_characteristics">
type="oval:GeneratorType">
type="oval-sc:SystemInfoType">
name="collected_objects"
type="oval-sc:CollectedObjectsType"
minOccurs="0" maxOccurs="1">
type="oval-sc:SystemDataType"
minOccurs="0" maxOccurs="1">
minOccurs="0" maxOccurs="1">
xpath="oval-sc:collected_objects/
xpath="oval-sc:system_data/*"/>
refer="oval-sc:itemKey">
xpath=
type="xsd:string">
type="xsd:string">
type="xsd:string">
type="xsd:string">
type="oval-sc:InterfacesType">
maxOccurs="unbounded"
processContents="lax">
type="oval-sc:InterfaceType"
minOccurs="0"
maxOccurs="unbounded">
type="xsd:string">
type="xsd:string">
type="xsd:string">
type="oval-sc:ObjectType"
minOccurs="1"
maxOccurs="unbounded"/>
type="oval:MessageType"
minOccurs="0"
maxOccurs="unbounded">
type="oval-sc:VariableValueType"
minOccurs="0"
maxOccurs="unbounded">
type="oval-sc:ReferenceType"
minOccurs="0"
maxOccurs="unbounded">
type="oval:ObjectIDPattern"
use="required"/>
type="xsd:nonNegativeInteger"
use="required"/>
type="xsd:nonNegativeInteger"
use="optional" default="1"/>
type="xsd:string" use="optional"/>
type="oval-sc:FlagEnumeration"
use="required"/>
base="xsd:anySimpleType">
type="oval:VariableIDPattern"
use="required"/>
type="oval:ItemIDPattern"
use="required"/>
minOccurs="1"
maxOccurs="unbounded"/>
type="oval-sc:ItemType" abstract="true">
type="oval:MessageType"
minOccurs="0" maxOccurs="50"/>
type="oval:ItemIDPattern"
use="required"/>
type="oval-sc:StatusEnumeration"
use="optional" default="exists"/>
value="does not exist">
value="not applicable">
value="does not exist">
name="EntityAttributeGroup">
id="oval-sc_entity_rules">
context=
test="not(@status) or @status='exists'
select="../@id"/> - a



    


select="name()"/> entity
select="name()"/> entity is not valid given a datatype of int.
context="oval-sc:system_data/*/*[not(
test="(not(contains(.,'.'))) and
select="../@id"/> - The
select="name()"/> entity
type="oval:DatatypeEnumeration"
use="optional" default="string">
type="xsd:boolean" use="optional"
default="false">
type="oval-sc:StatusEnumeration"
use="optional" default="exists">
name="EntityItemSimpleBaseType"
abstract="true">
base="xsd:anySimpleType">
ref="oval-sc:EntityAttributeGroup"
name="EntityItemComplexBaseType"
abstract="true">
ref="oval-sc:EntityAttributeGroup"/>
name="EntityItemIPAddressType">
base="oval-sc:EntityItemSimpleBaseType">
base="xsd:string"/>
use="required">
base="oval:SimpleDatatypeEnumeration">
value="ipv4_address"/>
value="ipv6_address"/>
name="EntityItemIPAddressStringType">
base="oval-sc:EntityItemSimpleBaseType">
base="xsd:string"/>
use="optional"
default="string">
base="oval:SimpleDatatypeEnumeration">
value="ipv4_address"/>
value="ipv6_address"/>
value="string"/>
name="EntityItemAnySimpleType">
base="oval-sc:EntityItemSimpleBaseType">
base="xsd:string"/>
type="oval:SimpleDatatypeEnumeration"
use="optional"
default="string"/>



    


base="oval-sc:EntityItemSimpleBaseType">
memberTypes="xsd:hexBinary
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="binary"
base="oval-sc:EntityItemSimpleBaseType">
memberTypes="xsd:boolean
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="boolean"
base="oval-sc:EntityItemSimpleBaseType">
memberTypes="xsd:float oval:EmptyStringType"
type="oval:SimpleDatatypeEnumeration"



    


use="required" fixed="float"/>
base="oval-sc:EntityItemSimpleBaseType">
memberTypes="xsd:integer
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="int"/>
base="oval-sc:EntityItemSimpleBaseType">
base="xsd:string"/>
type="oval:SimpleDatatypeEnumeration"
use="optional" fixed="string"
base="oval-sc:EntityItemComplexBaseType">
type="oval-sc:EntityItemFieldType"
minOccurs="0"
maxOccurs="unbounded"/>
base="xsd:anySimpleType">
use="required">
base="xsd:string">
value="[^A-Z]+"/>
ref="oval-sc:EntityAttributeGroup"
base="oval-sc:EntityItemSimpleBaseType">
base="xsd:string"/>
type="oval:SimpleDatatypeEnumeration"
use="required" fixed="version"
name="EntityItemFilesetRevisionType">
base="oval-sc:EntityItemSimpleBaseType">
base="xsd:string"/>
type="oval:SimpleDatatypeEnumeration"
use="required"
fixed="fileset_revision"/>
name="EntityItemIOSVersionType">
base="oval-sc:EntityItemSimpleBaseType">
base="xsd:string"/>
type="oval:SimpleDatatypeEnumeration"
use="required"
fixed="ios_version"/>



    


name="EntityItemEVRStringType">
base="oval-sc:EntityItemSimpleBaseType">
base="xsd:string"/>
type="oval:SimpleDatatypeEnumeration"
use="required"
fixed="evr_string"/>
name="EntityItemDebianEVRStringType">
base="oval-sc:EntityItemSimpleBaseType">
base="xsd:string"/>
type="oval:SimpleDatatypeEnumeration"
use="required"
fixed="debian_evr_string"/>
