serviceurl =  "service:" service-type ":" service-part

urlpath = [ "/" ]

feature = A, B
enhancement = C

feature = "A" , "B enhanced by C"

esc-char     = "&" "#" 1*DIGIT ";"

attribute  =  keyword / tag "=" 1#value CRLF CRLF

safe-chars =  <any character except "," which is reserved.>
white-sp   =  SPACE / CR / LF / TAB
key-chars  =  <any safe-chars except for white-sp which is
                     not allowed.>

tag        =  1*safe-chars
keyword    =  1*key-chars
value      =  string / integer / boolean / opaque

string     =  1*safe-chars

integer    =  [-] 1*DIGIT
                      ; The integer MUST fall within the range of
                      ; values a 32 bit integer may take, ie.
                      ; "-2147483648" to "2147483647".

boolean    =  "TRUE" / "FALSE"
                      ; These values are the only exception to the
                      ; Internationalization rules in Section 8.0.
                      ; Independent of the translation of the
                      ; attributes, the boolean values remain the
                      ; indicated strings.

rad64-char =  ALPHA / DIGIT / "+" / "-" / white-sp

opaque     =  1*DIGIT ":" 4*rad64-char
                      ; The digits define the original length of the
                      ; opaque value. The restricted character string
                      ; is the radix-64 encoding of the opaque value.
                      ; See [RFC 1521], Section 5.2.

                      ; NOTE:  White space is ignored in decoding
                      ; radix-64 values.

discovery-addr = ipv4-addrport / ipv6-addrport / "NONE"

byte          = 1*3DIGIT
                         ; This value MUST be between 0..255
ipv4-addrport = byte "." byte "." byte "." byte [":" 1*DIGIT]

hex           = DIGIT / "A" / "B" / "C" / "D" / "E" /
                                 "a" / "b" / "c" / "d" / "e"
ipv6-addrport = 32hex [":" 1*DIGIT]

version = 1*DIGIT '.' 1*DIGIT

tmpl-attr   =  attr-tag attr-val

safe-char   =  Any character other than "," and ":"
attr-tag    =  1*[safe-char]
attr-val    =  [type] [m] [l] "::" default "::" description

type        =  ["STRING" | "BOOLEAN" | "INTEGER" | "OPAQUE"]
default     =  1*[safe-char]
description =  1*[safe-char]
m           =  SPACE "M"
l           =  SPACE "L"

serviceurl    = "service:" service-type ":" service-part

service-type  = 1*[ low-alpha / DIGIT / "+" / "-" / "." ]
service-part  = "//" login [ "/" urlpath ]

login         = [ user [ ":" password ] "@" ] hostport
hostport      = host [ ":" port ]
host          = hostname / hostnumber
hostname      = *[ domainlabel "." ] toplabel
okchar        = ALPHA / DIGIT
domainlabel   = okchar / okchar *[ okchar / "-" ] okchar
toplabel      = ALPHA / ALPHA *[ okchar / "-" ] okchar
hostnumber    = ipv4-number / ipv6-number
ipv4-number   = 1*3DIGIT "." 1*3DIGIT "." 1*3DIGIT "." 1*3DIGIT
ipv6-number   = 32hex
port          = 1*DIGIT
user          = *[ uchar / ";" / "?" / "&" / "=" ]
password      = *[ uchar / ";" / "?" / "&" / "=" ]
urlpath       = *xchar ; each Service Type must define its own
                             ; syntax.  See Section

safe          = "$" / "-" / "_" / "." / "+"
extra         = "!" / "*" / "'" / "(" / ")" / ","
hex           = DIGIT / "A" / "B" / "C" / "D" / "E" /
                              "a" / "b" / "c" / "d" / "e"
escape        = "%" hex hex
reserved      = ";" / "/" / "?" / ":" / "@" / "&" / "="
unreserved    = ALPHA / DIGIT / safe / extra

uchar         = unreserved / escape
xchar         = unreserved / reserved / escape

version      = 0.0

description  =
        The NFS service type provides attributes which define the
        contents and policies of server mount points.  It defines
        three types of storage:
           (1) installations (software ready to use)
           (2) distributions (software ready to install)
           (3) space         (ready for others to use)
        Each of these attributes have record structured attribute
        values which are described below.

distributions = M :: NONE ::
        Software distributions&#44; ready to install on other systems.
        The value will have 5 fields&#44; separated by a tab.
        The fields are:
          - distribution name including relative path from the mount
            point (could be the name of a tar file&#44; a self
            extracting archive&#44; etc. (String)
          - platform the distribution is intended to be run on.
            (String)
          - the size of the distribution in KB (required to install it).
            (Integer)
          - the date and or version number of the distribution. (String)
          - a description of the distribution. (String: default = NONE)

installations = M :: NONE ::
        An installation is a program which is available on a file
        server.
          - relative path and name of executable. (String)
          - platform the installed program is intended to be run on.
            (String)
          - the date and version number of the installed program.
            (String)
          - required configuration to use the program (set environment
            variables&#44; required libraries&#44; etc.) (String:
default = NONE)
documents = M :: NONE::
        A document or group of documents can be advertised on a server
        so as to allow distributed search for the document.
          - relative path and name of the document or document directory
            (String)
          - format the document(s) are in (String)
          - a list of keywords (separated by semicolons).  These
            keywords may be determined by an organization which has an
            indexing policy&#44; or done in an ad hoc manner.  These
            keywords do not have to be guessed&#44; they can be
            accumulated and presented to a user or queried for.)
            (String)
          - date and or version of the document. (String)
          - description of the document (String: default = NONE )

space = M :: NONE ::
        Space indicates that a filesystem has room for temporary files.
          - Available space (in KB). (Integer)
          - Policy statement (how long can files be left on the server&#44;
            will files be considered temporary and removed when convenient?)
            (String)"

documents =
        ./slides \t powerpoint \t marketing&#44; quarterly reports \t
          10/15/96 \t This directory contains slides are from
          presentations made over the last year.
        ./meeting-notes \t text \t planning&#44; update \t 10/22/96 \t
          This directory is a repository for all group meetings.
          We keep it up to date and hold our meetings once every
          25 days.,
        ./cartoons \t gif \t silly \t 3/23/96 \t This directory has
          a bunch of silly cartoons from a website I like.

distributions=NONE

installations=NONE

space=NONE"

space=NONE

documents=NONE

distributions=
       ./wp-zog/distrib/wp-zog-1-31-sol25.tar.Z \t Sol2.5 \t
          2054 kb \t 01/13/96 \t version 1.31 \t
          Word processor from Zog Corp - for X/Motif.,
       ./wp-zog/distrib/wp-zog-1-31-win32.zip \t Win32 \t
          3056 kb \t 01/13/96 \t version 1.31 \t
          Word processor from Zog Corp - for Windows NT and 95,
       ./wp-zog/distrib/wp-zog-1-31-mac.hqx \t MacOS7.5 \t
          1980 kb \t 02/23/96 \t version 1.31m \t
          Word processor from Zog Corp - for Macintosh,
       ./cp-foo/distrib/cp-foo-2-01-sol25.tar.Z \t Sol2.5 \t
          1044 kb \t 08/02/95 version 2.01 \t
          Calender Program from Foo - for Solaris 2.5,
       ./cp-foo/distrib/cp-foo-2-11-win32.zip \t Win32 \t
          2096 kb \t 11/30/95 \t version 2.11 \t
          Calander Program from Foo - for Windows 95,
       ./cp-foo/distrib/cp-foo-1-4-mac.hqx \t MacOS7.5 \t
          733 kb \t 03/23/95 \t version 1.4 \t
          Calander Program from Foo - for Macintosh

installations=
       ./wp-zog/sol-inst/wp-zog \t Sol2.5 \t 01/13/96 version 1.31 \t
          \t Word processor from Zog Corp - for X/Motif.,
       ./wp-zog/mac-inst/wp-zog \t MacOS7.5 \t 02/23/96 version 1.31m \t
            Word processor from Zog Corp - for Macintosh,
       ./cp-foo/sol-inst/cp-foo \t Sol2.5 \t 08/02/95 version 2.01 \t
           Set CP-HOME environment variable to ./cp-foo/inst/cp-foo \t
           Calander Program from Foo - for Solaris 2.5,
       ./cp-foo/mac-inst/MyCal \t MacOS7.5 \t 03/23/95 version 1.4 \t
           \t Calander Program from Foo - for Macintosh"

name    = 1*[ DIGIT / ALPHA ]
urlpath = "/" name

version = 0.0

Description =
          The LPR service provides line printer spooling&#44; using
          the BSD Unix print spooling protocol&#44; formalized in
          RFC 1179.  The attributes associated with the LPR
          service refer to the printer actual printing service
          will be performed.

Status = INTEGER L :: 1 ::
          The status is taken from the Printer Status object of the
          host MIB&#44; hrDeviceStatus.  The enumerated values have
          the following definitions:
             1 = unknown    The state is unknown.
             2 = running    The device is up:  No known errors.
             3 = warning    Still operational: Agent has been warned.
             4 = testing    Not available:  In the 'testing' state.
             5 = down       Not available.

Operator = :: NONE ::
          The name and possibly telephone number of the person
          responsible for operating the printer.  This value should
          be obtained from the prtGeneralTable of the Printer MIB&#44;
          from the prtGeneralCurrentOperator object of the
          prtGeneralEntry if possible.

version = 0.0

Description =
         Clients which wish to make use of POP3 services need to
         be configured to use the correct POP3 server.  The server
         may or may not be able to use the APOP authentication
         mechanism.  Clients are able to discover which POP3 server
         is the correct one for them and whether they can use APOP
         to authenticate themselves.  Finally&#44; the POP3 server
         policy statement may be included.

Mailboxes = M L :: NONE ::
         This is a list of all users (by user name) which the
         POP3 server supports.

APOP = BOOLEAN L :: FALSE ::
         This attribute determines whether the POP3 server supports
         the POP3 AUTHentication command [RFC1734].

Policy = :: NONE ::
         This describes the POP3 policy regarding use.  In particular
         users may be dissuaded from keeping mail on the server or
         keeping more than a certain amount of mail on the server."

Mailboxes = larry, curly, moe, shemp

APOP = FALSE

Policy = Mail should not be left on the server."

Mailboxes = larry, curly, moe, shemp
APOP = FALSE

Anweisung = Mail darf nicht auf dem Server bleiben."

