from='juliet@capulet.net/balcony'
id='183ef129'
to='romeo@montegue.net'
type='chat'>
from='juliet@capulet.net/balcony' id='183ef129'
to='romeo@montegue.net' type='chat'><thread>
from='juliet@capulet.net/balcony'
id='6410ed123'
to='romeo@montegue.net'
type='chat'>
stamp='2010-02-28T18:00:00Z'>
nDdLAMyeMZedlrHCS4lp6PzeblDD0Jk2HQ==
targetNamespace='urn:ietf:params:xml:ns:xmpp-objenc'
xmlns='urn:ietf:params:xml:ns:xmpp-objenc'
elementFormDefault='qualified'>

