TCHAR  = VCHAR / SP / HTAB    ; visible plus white space 
RCHAR  = ALPHA / DIGIT / "," / "." / ":" / "!" / 
                    "@" / "#" / "$" / "%" / "^" / 
                    "&" / "(" / ")" / "-" / "_" / 
                    "+" / "?" / "/" / "\" / "'" / 
                    DQUOTE   ; <"> -- double quote character (%x22) 
SCHAR  = RCHAR / "=" ; 
    
token  = 1*RCHAR 
    
mode              = "MODE" SP "Z" CRLF 
    
mode-response     = mode-good / mode-bad 
mode-good         = "200" SP response-message CRLF 
mode-bad          = "451" SP response-message CRLF / 
                        = "501" SP response-message CRLF 
response-message  = *TCHAR 
    

 
 
 
mode-feat   = SP "MODE" SP "Z" [SP eng-list] CRLF 
eng-list    = *(eng-desc ",") 
eng-desc    = 1*(eng-name eng-opts) 
eng-name    = ALPHA*(ALPHA / DIGIT / "-" / ".") 
eng-opts    = *("(" opts-list ")") 
opts-list   = 1*(opt-name ",") 
opt-name    = ALPHA*(ALPHA / DIGIT) 
    
opts  = "OPTS" SP "MODE" SP "Z" [ SP 1*(name SP value ",") ] 
name  = ALPHA*(ALPHA / DIGIT) 
value = 1*RCHAR 
    
eng-option  = eng-label SP eng-value 
eng-label   = "ENGINE" 
eng-value   = ALPHA*(ALPHA / DIGIT / "-" / ".") 
 
lvl-option  = lvl-label SP lvl-value 
lvl-label   = "LEVEL" 
lvl-value   = 1*DIGIT 
 
blk-option  = blk-label SP blk-value 
blk-label   = "BLOCKSIZE" 
blk-value   = 1*DIGIT 
    
