Error-Type = TBD ("Binding SID failure") and Error Value = TBD
Error-value = TBD (recommended 1):  Invalid SID
Error-value = TBD (recommended 2):  Unable to allocate
                                                     binding SID

