external_aad = bstr .cbor aad_array

aad_array = [
      oscore_version : uint,
      algorithms : [alg_aead : int / tstr ,
                    alg_countersign : int / tstr ,
                    ? par_countersign : any],
      request_kid : bstr,
      request_piv : bstr,
      options : bstr
