id = 1000> and <prefix = loopback-PE2, intent-id = 2000>, which are
intent-id = 1000> is:

      metric-type: Unidirectional Link Delay

      metric: assume an initial value of 0

      metric-credit information:

         Count of Sources: 1

S-Flag = 1, F-Flag = 0, P-Flag = 0

S-Flag = 1, F-Flag = 0, P-Flag = 0

intent-id = 1000> is:

      metric-type: Unidirectional Link Delay

      metric: assume an initial value of 0

      metric-credit information:

         Count of Sources: 1

S-Flag = 1, F-Flag = 0, P-Flag = 1

S-Flag = 1, F-Flag = 0, P-Flag = 1

S-Flag = 1, F-Flag = 0, P-Flag = 0

intent-id = 1000>, which is advertised to ASBR3.  The metric related
S-Flag = 1, F-Flag = 0, P-Flag = 0

