DefToneString = "(" DefToneElement ["*" RepeatCount ] ")"
RepeatCount = %d1-32767 / %d0
DefToneElement = ToneName ["," ToneDuration [ "," ToneAmplitude ]]

ToneName = (Package id, Tone id) / "#"FreqValue /
FreqValue = %d0-4000; in Hertz

AnnouncementParameterList = AnnouncementID ["," SubstitutionString]

AnnouncementID = 1*VCHAR; Unique identifier for an audio
SubstitutionString = """1*VCHAR"""; a string to be inserted into an
ToneDuration = %d1-32767 / %d0 ; In Milliseconds

        NOTE: ToneDuration of 0 indicates infinite duration or duration
        defined  by the Tone id.

ToneAmplitude = "-"%d32-1 / %d0; In dBm0

RingingTone = ((0x0005,0x0031),((#480)+(#620)),250,-24)*0



