uri="urn:ietf:params:xml:ns:indeNode-1.0">2

xmlns="http://www.w3.org/2001/XMLSchema"

elementFormDefault="qualified">

type="indeNode:abstractContentType"

substitutionGroup="inde:content" abstract="true"/>

substitutionGroup="indeNode:abstractNode"/>

substitutionGroup="inde:delete"/>

type="indeNode:prefixType"/>

type="indeNode:nameType"/>

type="indeNode:natureType"/>

type="indeNode:addrType/>

type="indeNode:ipAddrType"/>

type="indeNode:credType"/>

type="indeNode:credTypeType"/>

type="indeNode:credNoType"/>




type="indeNode:nameType"/>

type="indeNode:profileType"/>

type="indeNode:contactType"/>

type="indeNode:streetType"

minOccurs="1" maxOccurs="2" />

type="indeNode:credTypeEnumType" use="required" />

value="MainlandTravelPermitForHongKongAndMacaoResidents"/>

value="MainlandTravelPermitForTaiwanResidents"/>




value="ResidencePermitForHongKongMacaoTaiwanResidents"/>

value="ProductionLicenseOrLicenseOfIndustrialProducts"/>

type="indeNode:prefixType" minOccurs="0"

maxOccurs="unbounded"/>

xmlns="http://www.w3.org/2001/XMLSchema"

elementFormDefault="qualified">

substitutionGroup="inde:content"/>

maxOccurs="unbounded"/>

uri="urn:ietf:params:xml:ns:indeNode-1.0">2

uri="urn:ietf:params:xml:ns:indeNode-1.0">1

