varint-terminator = %x00-7f
varint-continuation = %x80-ff
unsigned-varint = *8varint-continuation varint-terminator

base-identifier = <ascii character>
multibase = base-identifier {base-encoded-data}
hash-function-code = unsigned-varint
hash-digest-size = unsigned-varint
hash = {hash function output}

multihash = hash-function-code hash-digest-size hash

