Id =
Definition =
Type =
Defs =
Types =
Definition =
Ids =
Defs =
Types =
ID= =
Entries =
Controls =
Defs =
Types =
ID=
Start=
Period=
Count=
Action=
TRLs =
Types =
Id =
Start =
Predicate =
Count =
Action =
SRLs =
Types =
Value=
Value=
Value=
Value=
Single    ===>  | Length | Octet 1 | ... | Octet N |
