total_size=0;
N = 0;
pos = 0;
sum = 0;
s = payload[pos++];
b=AS: The maximum bandwidth (in kbit/s) allowed for CELT,
m=audio 8088 RTP/AVP 97

a=rtpmap:97 CELT/48000

m=audio 8088 RTP/AVP 97

b=AS:64

a=rtmap:97 CELT/48000

m=audio 8008 RTP/AVP 97

a=ptime: 21

a=rtpmap:97 CELT/44100
a=fmtp:97 frame-size=512;

m=audio 8008 RTP/AVP 97

a=ptime: 5

a=rtpmap:97 CELT/44100/2

a=fmtp:97 frame-size=256;

b=AS: parameters SHOULD also be ignored since the low-overhead:
m=audio 8008 RTP/AVP 97
a=ptime: 5

a=rtpmap:97 CELT/48000/6

a=fmtp:97 low-overhead=256/1/86,86,43,30;mapping=2,2,1,1/
