v=0 
o=- 25678 753849 IN IP4 192.0.2.1 
s=  
c=IN IP4 192.0.2.1 
t=0 0 
m=audio 53456 RTP/AVP 0 18  
a=tcap:1 RTP/SAVP  
a=acap:1 crypto:1 AES_CM_128_HMAC_SHA1_80              
         inline:WVNfX19zZW1jdGwgKCkgewkyMjA7fQp9CnVubGVz|2^20|1:4 
a=pcfg:1 t=1 a=1   
 
 
    






    

v=0 
o=- 24351 621814 IN IP4 192.0.2.2 
s=  
c=IN IP4 192.0.2.2 
t=0 0 
m=audio 54568 RTP/SAVP 0 18  
a=crypto:1 AES_CM_128_HMAC_SHA1_80 
            inline:PS1uQCVeeCFCanVmcjkpPywjNWhcYD0mXXtxaVBR|2^20|1:4
a=acfg:1 t=1 a=1 

v=0 
o=- 25678 753850 IN IP4 192.0.2.1 
s=  
c=IN IP4 192.0.2.1 
t=0 0 
m=audio 53456 RTP/SAVP 0 18  
a=crypto:1 AES_CM_128_HMAC_SHA1_80               
         inline:WVNfX19zZW1jdGwgKCkgewkyMjA7fQp9CnVubGVz|2^20|1:4 

v=0 
o=- 24351 621815 IN IP4 192.0.2.2 
s=  
c=IN IP4 192.0.2.2 
t=0 0 
m=audio 54568 RTP/SAVP 0 18  
a=crypto:1 AES_CM_128_HMAC_SHA1_80 
            inline:PS1uQCVeeCFCanVmcjkpPywjNWhcYD0mXXtxaVBR|2^20|1:4 

v=0 
o=- 24351 621814 IN IP4 192.0.2.2 
s=  
c=IN IP4 192.0.2.2 
 
 
    






    

t=0 0 
m=audio 54568 RTP/AVP 0 18   

a=csup: <option-tag-list> 

att-value         = option-tag-list 
option-tag-list   = option-tag *("," option-tag) 
option-tag        = token    ; defined in [RFC4566] 

a=csup:cap-v0 

a=csup:foo 
 
 
    






    

a=csup:bar 

a=csup:cap-v0,foo,bar 

a=creq: <option-tag-list> 

 
 
    






    

att-value   = option-tag-list 

a=creq:cap-v0 

a=creq:foo 

a=creq:bar 

a=creq:cap-v0,foo,bar 

a=acap: <att-cap-num> <att-par> 

att-value   = att-cap-num 1*WSP att-par 
att-cap-num = 1*DIGIT ;defined in [RFC5234] 
att-par     = attribute  ;defined in RFC 4566 

a=acap:1 ptime:20 
    
a=acap:2 ptime:30 

a=acap:3 key-mgmt:mikey AQAFgM0XflABAAAAAAAAAAAAAAsAyONQ6gAA 
a=acap:4 crypto:1 AES_CM_128_HMAC_SHA1_32    
            inline:NzB4d1BINUAvLEw6UzF3WSJ+PSdFcGdUJShpX1Zj|2^20|1:32  

a=tcap: <trpr-cap-num> <proto-list> 

att-value      = trpr-cap-num 1*WSP proto-list 
trpr-cap-num   = 1*DIGIT ;defined in [RFC5234] 
proto-list     = proto *(1*WSP proto) ; defined in RFC 4566 

a=tcap:1 RTP/AVP 

a=tcap:2 RTP/AVPF 

a=tcap:3 RTP/SAVP RTP/SAVPF 

a=pcfg: <config-number> [<pot-cfg-list>] 

att-value      = config-number [1*WSP pot-cfg-list] 
config-number  = 1*DIGIT ;defined in [RFC5234] 
pot-cfg-list   = pot-config *(1*WSP pot-config) 
pot-config     = attribute-config-list / 
                       transport-protocol-config-list / 
                       extension-config-list 

v=0 
o=- 25678 753849 IN IP4 192.0.2.1 
s=  
c=IN IP4 192.0.2.1 
t=0 0 
m=audio 53456 RTP/AVP 0 18 
a=tcap:1 RTP/SAVP RTP/SAVPF 
a=acap:1 crypto:1 AES_CM_128_HMAC_SHA1_32    
         inline:NzB4d1BINUAvLEw6UzF3WSJ+PSdFcGdUJShpX1Zj|2^20|1:32  
a=pcfg:1 t=1 a=1 
a=pcfg:2 t=2 a=1   

delete-attributes = DELETE ( "m"    ; media attributes 
                              / "s"    ; session attributes 
                              / "ms" ) ; media and session attributes 
    
mo-att-cap-list      = mandatory-optional-att-cap-list | 
                                    mandatory-att-cap-list | 
                                       optional-att-cap-list 

mandatory-optional-att-cap-list  = mandatory-att-cap-list   
                                             "," optional-att-cap-list 
mandatory-att-cap-list           = att-cap-list 
optional-att-cap-list            = "[" att-cap-list "]" 

att-cap-list      = att-cap-num *("," att-cap-num) 
att-cap-num       = 1*DIGIT   ;defined in [RFC5234] 
BAR               = "|"        
DELETE            = "-"  
    
 
 
    






    

a=pcfg:1 a=-m:1,2,[3,4]|1,7,[5] 

transport-protocol-config-list =  
                           "t=" trpr-cap-num *(BAR trpr-cap-num) 
trpr-cap-num        = 1*DIGIT   ; defined in [RFC5234] 

extension-config-list= ["+"] ext-cap-name "="  
                                    ext-cap-list  
ext-cap-name               = 1*(ALPHA / DIGIT) 
ext-cap-list               = 1*VCHAR      ; defined in [RFC5234] 

v=0 
o=- 25678 753849 IN IP4 192.0.2.1 
s=  
c=IN IP4 192.0.2.1 
t=0 0 
m=audio 53456 RTP/AVPF 0 18  
a=acap:1 crypto:1 AES_CM_128_HMAC_SHA1_32    
         inline:NzB4d1BINUAvLEw6UzF3WSJ+PSdFcGdUJShpX1Zj|2^20|1:32  
a=tcap:1 RTP/AVPF RTP/AVP RTP/SAVP RTP/SAVPF 
a=pcfg:1 t=4|3 a=1 
a=pcfg:8 t=1|2 

a=acfg: <config-number> [<sel-cfg-list>] 


 
 
    






    

att-value      = config-number [1*WSP sel-cfg-list] 
                        ;config-number defined in Section 3.5.1.  
sel-cfg-list   = sel-cfg *(1*WSP sel-cfg) 
sel-cfg        = sel-attribute-config / 
                           sel-transport-protocol-config / 
                           sel-extension-config 
    
sel-attribute-config =  
               "a=" [delete-attributes ":"] mo-att-cap-list 
                                    ; defined in Section 3.5.1.  
    
sel-transport-protocol-config = 
               "t=" trpr-cap-num    ; defined in Section 3.5.1.  
    
sel-extension-config = 
               ext-cap-name "=" 1*VCHAR   ; defined in Section 3.5.1.  

v=0 
o=- 24351 621814 IN IP4 192.0.2.2 
s=  
c=IN IP4 192.0.2.2 
t=0 0 
m=audio 54568 RTP/SAVPF 0  
a=crypto:1 AES_CM_128_HMAC_SHA1_32    
         inline:WSJ+PSdFcGdUJShpX1ZjNzB4d1BINUAvLEw6UzF3|2^20|1:32
a=acfg:1 t=4 a=1 

v=0 
o=alice 2891092738 2891092738 IN IP4 lost.example.com 
s=  
t=0 0 
c=IN IP4 lost.example.com 
a=tool:foo 
a=acap:1 key-mgmt:mikey AQAFgM0XflABAAAAAAAAAAAAAAsAyO...    
a=tcap:1 RTP/SAVP RTP/AVP 
m=audio 59000 RTP/AVP 98 
a=rtpmap:98 AMR/8000 
a=acap:2 crypto:1 AES_CM_128_HMAC_SHA1_32    
         inline:NzB4d1BINUAvLEw6UzF3WSJ+PSdFcGdUJShpX1Zj|2^20|1:32  
a=pcfg:1 t=1 a=1|2 
m=video 52000 RTP/AVP 31 
a=rtpmap:31 H261/90000 
a=acap:3 crypto:1 AES_CM_128_HMAC_SHA1_80 
 
 
    






    

         inline:d0RmdmcmVCspeEc3QGZiNWpVLFJhQX1cfHAwJSoj|2^20|1:32 
a=pcfg:1 t=1 a=1|3 
    

v=0 
o=alice 2891092738 2891092738 IN IP4 lost.example.com 
s=  
t=0 0 
c=IN IP4 lost.example.com 
a=tool:foo 
a=key-mgmt:mikey AQAFgM0XflABAAAAAAAAAAAAAAsAyO...    
m=audio 59000 RTP/SAVP 98 
a=rtpmap:98 AMR/8000 
m=video 52000 RTP/SAVP 31 
a=rtpmap:31 H261/90000 
    
v=0 
o=alice 2891092738 2891092738 IN IP4 lost.example.com 
s=  
t=0 0 
c=IN IP4 lost.example.com 
a=tool:foo 
m=audio 59000 RTP/SAVP 98 
a=crypto:1 AES_CM_128_HMAC_SHA1_32    
         inline:NzB4d1BINUAvLEw6UzF3WSJ+PSdFcGdUJShpX1Zj|2^20|1:32  
 
 
    






    

a=rtpmap:98 AMR/8000 
m=video 52000 RTP/SAVP 31   
a=crypto:1 AES_CM_128_HMAC_SHA1_80 
         inline:d0RmdmcmVCspeEc3QGZiNWpVLFJhQX1cfHAwJSoj|2^20|1:32 
a=rtpmap:31 H261/90000 

v=0 
o=alice 2891092738 2891092738 IN IP4 lost.example.com 
s=  
t=0 0 
c=IN IP4 lost.example.com 
a=key-mgmt:mikey AQAFgM0XflABAAAAAAAAAAAAAAsAyO...    
a=tool:foo 
m=audio 59000 RTP/SAVP 98 
a=rtpmap:98 AMR/8000 
m=video 52000 RTP/SAVP 31   
a=crypto:1 AES_CM_128_HMAC_SHA1_80 
         inline:d0RmdmcmVCspeEc3QGZiNWpVLFJhQX1cfHAwJSoj|2^20|1:32   
a=rtpmap:31 H261/90000 

v=0 
o=- 25678 753849 IN IP4 192.0.2.1 
s=  
c=IN IP4 192.0.2.1 
t=0 0 
m=audio 53456 RTP/AVP 0 18  
a=tcap:1 RTP/SAVPF RTP/SAVP RTP/AVPF  
a=acap:1 crypto:1 AES_CM_128_HMAC_SHA1_80              
         inline:WVNfX19zZW1jdGwgKCkgewkyMjA7fQp9CnVubGVz|2^20|1:4  
FEC_ORDER=FEC_SRTP 
a=acap:2 key-mgmt:mikey AQAFgM0XflABAAAAAAAAAAAAAAsAyO...    
a=acap:3 rtcp-fb:0 nack 
a=pcfg:1 t=1 a=1,3|2,3 
a=pcfg:2 t=2 a=1|2 
a=pcfg:3 t=3 a=3   

v=0 
o=- 25678 753849 IN IP4 192.0.2.1 
s=  
c=IN IP4 192.0.2.1 
t=0 0 
m=audio 53456 RTP/AVP 0 18  
a=tcap:1 RTP/SAVPF RTP/SAVP RTP/AVPF  
a=acap:1 crypto:1 AES_CM_128_HMAC_SHA1_80              
         inline:WVNfX19zZW1jdGwgKCkgewkyMjA7fQp9CnVubGVz|2^20|1:4  
FEC_ORDER=FEC_SRTP 
a=acap:2 rtcp-fb:0 nack 
a=pcfg:1 t=1 a=1,[2] 
a=pcfg:2 t=2 a=1 
 
 
    






    

a=pcfg:3 t=3 a=[2] 
       
v=0 
o=- 24351 621814 IN IP4 192.0.2.2 
s=  
c=IN IP4 192.0.2.2 
 
 
    






    

t=0 0 
m=audio 54568 RTP/AVPF 0 18  
a=rtcp-fb:0 nack  
a=acfg:1 t=3 a=[2] 

v=0 
o=- 25678 753850 IN IP4 192.0.2.1 
s=  
c=IN IP4 192.0.2.1 
t=0 0 
m=audio 53456 RTP/AVPF 0 18  
a=rtcp-fb:0 nack 

v=0 
o=- 24351 621815 IN IP4 192.0.2.2 
s=  
c=IN IP4 192.0.2.2 
t=0 0 
m=audio 54568 RTP/AVPF 0 18  
a=rtcp-fb:0 nack 
 
 
    






    

v=0 
o=- 24351 621814 IN IP4 192.0.2.2 
s=  
c=IN IP4 192.0.2.2 
t=0 0 
m=audio 54568 RTP/AVP 0 18  

v=0 
o=- 25678 753849 IN IP4 192.0.2.1 
s=  
t=0 0 
c=IN IP4 192.0.2.1 
a=acap:1 key-mgmt:mikey AQAFgM0XflABAAAAAAAAAAAAAAsAyO...    
a=tcap:1 RTP/SAVPF RTP/SAVP RTP/AVPF 
m=audio 59000 RTP/AVP 98 
a=rtpmap:98 AMR/8000 
a=acap:2 crypto:1 AES_CM_128_HMAC_SHA1_32    
         inline:NzB4d1BINUAvLEw6UzF3WSJ+PSdFcGdUJShpX1Zj|2^20|1:32  
a=pcfg:1 t=2 a=1|2 
m=video 52000 RTP/AVP 31 
a=rtpmap:31 H261/90000 
a=acap:3 crypto:1 AES_CM_128_HMAC_SHA1_80 
         inline:d0RmdmcmVCspeEc3QGZiNWpVLFJhQX1cfHAwJSoj|2^20|1:32 
a=acap:4 rtcp-fb:* nack 
a=pcfg:1 t=1 a=1,4|3,4   
a=pcfg:2 t=2 a=1|3 
a=pcfg:3 t=3 a=4   

v=0 
o=- 24351 621814 IN IP4 192.0.2.2 
s=  
t=0 0 
c=IN IP4 192.0.2.2 
m=audio 54568 RTP/SAVP 98 
a=rtpmap:98 AMR/8000 
a=crypto:1 AES_CM_128_HMAC_SHA1_32    
         inline:WSJ+PSdFcGdUJShpX1ZjNzB4d1BINUAvLEw6UzF3|2^20|1:32  
a=acfg:1 t=2 a=2   
m=video 55468 RTP/SAVPF 31 
a=rtpmap:31 H261/90000 
a=crypto:1 AES_CM_128_HMAC_SHA1_80 
         inline:AwWpVLFJhQX1cfHJSojd0RmdmcmVCspeEc3QGZiN|2^20|1:32 
a=rtcp-fb:* nack 
a=acfg:1 t=1 a=3,4 
    
v=0 
o=- 25678 753849 IN IP4 192.0.2.1 
s=  
t=0 0 
c=IN IP4 192.0.2.1 
m=audio 59000 RTP/SAVP 98 
a=rtpmap:98 AMR/8000 
a=crypto:1 AES_CM_128_HMAC_SHA1_32    
         inline:NzB4d1BINUAvLEw6UzF3WSJ+PSdFcGdUJShpX1Zj|2^20|1:32  
m=video 52000 RTP/SAVPF 31 
a=rtpmap:31 H261/90000 
a=crypto:1 AES_CM_128_HMAC_SHA1_80 
         inline:d0RmdmcmVCspeEc3QGZiNWpVLFJhQX1cfHAwJSoj|2^20|1:32 
a=rtcp-fb:* nack 

v=0 
o=- 24351 621814 IN IP4 192.0.2.2 
s=  
t=0 0 
c=IN IP4 192.0.2.2 
m=audio 54568 RTP/SAVP 98 
a=rtpmap:98 AMR/8000 
a=crypto:1 AES_CM_128_HMAC_SHA1_32    
         inline:WSJ+PSdFcGdUJShpX1ZjNzB4d1BINUAvLEw6UzF3|2^20|1:32  
m=video 55468 RTP/SAVPF 31 
a=rtpmap:31 H261/90000 
a=crypto:1 AES_CM_128_HMAC_SHA1_80 
         inline:AwWpVLFJhQX1cfHJSojd0RmdmcmVCspeEc3QGZiN|2^20|1:32 
a=rtcp-fb:* nack 

v=0 
o=- 24351 621814 IN IP4 192.0.2.2 
s=  
t=0 0 
c=IN IP4 192.0.2.2 
m=audio 54568 RTP/AVP 98 
a=rtpmap:98 AMR/8000 
m=video 55468 RTP/AVP 31 
a=rtpmap:31 H261/90000 
a=rtcp-fb:* nack 

v=0 
o=- 25678 753849 IN IP4 192.0.2.1 
s=  
 
 
    






    

t=0 0 
c=IN IP4 192.0.2.1 
a=key-mgmt:mikey AQEFgM0XflABAAAAAAAAAAAAAAYAyO... 
m=audio 59000 RTP/AVP 98 
a=rtpmap:98 AMR/8000 
a=acfg:1 t=2 a=1 
m=video 52000 RTP/SAVPF 31 
a=rtpmap:31 H261/90000 
a=rtcp-fb:* nack 
a=acfg:1 t=1 a=1,4 

v=0 
o=- 25678 753849 IN IP4 192.0.2.1 
s=  
t=0 0 
c=IN IP4 192.0.2.1 
a=key-mgmt:mikey AQAFgM0XflABAAAAAAAAAAAAAAsAyO...    
m=audio 59000 RTP/SAVP 98 
a=rtpmap:98 AMR/8000 
a=acap:1 crypto:1 AES_CM_128_HMAC_SHA1_32    
         inline:NzB4d1BINUAvLEw6UzF3WSJ+PSdFcGdUJShpX1Zj|2^20|1:32  
a=pcfg:1 a=-s:1 
m=video 52000 RTP/SAVP 31 
a=rtpmap:31 H261/90000 
a=acap:2 crypto:1 AES_CM_128_HMAC_SHA1_80 
         inline:d0RmdmcmVCspeEc3QGZiNWpVLFJhQX1cfHAwJSoj|2^20|1:32
a=pcfg:1 a=-s:2 

v=0 
o=- 24351 621814 IN IP4 192.0.2.2 
s=  
t=0 0 
c=IN IP4 192.0.2.2 
m=audio 54568 RTP/SAVP 98 
a=rtpmap:98 AMR/8000 
a=crypto:1 AES_CM_128_HMAC_SHA1_32    
         inline:WSJ+PSdFcGdUJShpX1ZjNzB4d1BINUAvLEw6UzF3|2^20|1:32  
a=acfg:1 a=-s:1 
m=video 55468 RTP/SAVP 31 
a=rtpmap:31 H261/90000 
a=crypto:1 AES_CM_128_HMAC_SHA1_80 
         inline:AwWpVLFJhQX1cfHJSojd0RmdmcmVCspeEc3QGZiN|2^20|1:32 
a=acfg:1 a=-s:2 

v=0 
o=- 25678 753849 IN IP4 192.0.2.1 
s=  
t=0 0 
c=IN IP4 192.0.2.1 
a=acap:1 key-mgmt:mikey AQAFgM0XflABAAAAAAAAAAAAAAsAyO...    
 
 
    






    

m=audio 59000 RTP/SAVP 98 
a=rtpmap:98 AMR/8000 
a=crypto:1 AES_CM_128_HMAC_SHA1_32    
         inline:NzB4d1BINUAvLEw6UzF3WSJ+PSdFcGdUJShpX1Zj|2^20|1:32  
a=acap:2 rtpmap:98 AMR/8000 
a=pcfg:1 a=-m:1,2 
m=video 52000 RTP/SAVP 31 
a=rtpmap:31 H261/90000 
a=acap:3 crypto:1 AES_CM_128_HMAC_SHA1_80 
         inline:d0RmdmcmVCspeEc3QGZiNWpVLFJhQX1cfHAwJSoj|2^20|1:32 
a=acap:4 rtpmap:31 H261/90000 
a=pcfg:1 a=-m:1,4 

