RCODE=0 (No Error), then the initiator sends out two queries: One for
QNAME=www.example.com, QTYPE=A

QNAME=www.example.com, QTYPE=HIPHI

QNAME=www.example.com, QTYPE=HIPRVS

QNAME=www.example.com, QTYPE=A

QNAME=www.example.com, QTYPE=HIPHI

QNAME=www.example.com, QTYPE=HIPRVS
QNAME=www.example.com, QTYPE=A

QNAME=www.example.com, QTYPE=HIPHI

QNAME=www.example.com, QTYPE=HIPRVS

UIMoId== )

