a=humintlang-send:<language tag>
a=humintlang-recv:<language tag>

m=audio 49170 RTP/AVP 0
a=humintlang-send:en
a=humintlang-recv:en

m=video 51372 RTP/AVP 31 32
a=humintlang-send:ase*
a=humintlang-recv:ase*

m=audio 49250 RTP/AVP 20
a=humintlang-send:es*
a=humintlang-recv:es*
a=humintlang-send:eu*
a=humintlang-recv:eu*
a=humintlang-send:en*
a=humintlang-recv:en*

m=text 45020 RTP/AVP 103 104
a=humintlang-send:gr
a=humintlang-recv:gr

language="en,es,ase"

language="en";q=0.8
