billing-information  =  *info-header 
info-header    =  "header-name" HCOLON header-value *(COMMA 
Advice-State =  "Advice-State" HCOLON Advice-States 
Advice-State = "final" | "intermediate" 
    
Charge-Type = "Charge-Type" HCOLON Charge-Types 
Charge-Types = "normal" | "reverse" | "free" | other-type 
other-type = token 
    
Charge-Units = "Charge-Units" HCOLON 1*DIGIT["." 1*DIGIT] 
    
Charge-Units = 12.2 
    
    
Currency-Units = "Currency-Units" HCOLON 1*DIGIT["." 1*DIGIT] 
    
Currency-Units = 1.4 
    
    

 
 
 
 
Currency-Identifier = "Currency-ID" HCOLON quoted-string 
    
     For certain currencies like "Yuan" or "Yen" the symbol may not be 
     a part of the ASCII definition and may required UTF-8 symbols. 
      
Duration = "Duration" HCOLON 1*DIGIT ["." 1*DIGIT] 
    
Bill-Identifier = "Bill-ID" HCOLON token [ô@ö token] 
    
    
Service-Type = "Service-Type" HCOLON Service-Types 
 
 
 
 
Service-Types = "cfu" | "cfb" | "cfnr" | "ct" | other-services 
other-services = token 
    
    
     The meanings of the service types are as follows 
     cfu -  Call Forward Unconditional 
     cfb -  Call Forward Busy 
     cfnr - Call Forward No Resposne 
     ct -   Call Transfer 
    
Hash = "Hash" HCOLON (32LHEX | token )ö;ö Alg-param 
Alg-param = ôalgorithmö EQUAL (ômd5ö | token) 
    
Billing-Information = *(Information-Header) 
    
Information-Header  =   (Advice-State  
                        /  Charge-Type 
                        /  Charge-Units 
                        /  Currency-Units 
                        /  Currency-Identifier 
                        /  Duration  
                        /  Bill-Identifier 
                        /  Service-Type 
                        /  Hash 
                        /  extension-header ) 
 
 
 
 
    
Advice-State =  "Advice-State" HCOLON Advice-States 
Advice-State = "final" | "intermediate" 
    
Charge-Type = "Charge-Type" HCOLON Charge-Types 
Charge-Types = "normal" | "reverse" | "free" | other-type 
other-type = token 
    
Charge-Units = "Charge-Units" HCOLON 1*DIGIT["." 1*DIGIT] 
    
Currency-Units = "Currency-Units" HCOLON 1*DIGIT["." 1*DIGIT] 
    
Currency-Identifier = "Currency-ID" HCOLON quoted-string 
    
Duration = "Duration" HCOLON 1*DIGIT 
    
Bill-Identifier = ôBill-IDö HCOLON token [ô@ö token] 
    
Service-Type = "Service-Type" HCOLON Service-Types 
Service-Types = "cfu" | "cfb" | "cfnr" | "ct" | other-services 
other-services = token 
    
Hash = "Hash" HCOLON (32LHEX | token )ö;ö Alg-param 
Alg-param = ôalgorithmö EQUAL (ômd5ö | token) 
    
extension-header  =  header-name HCOLON header-value 
header-name       =  token 
header-value      =  *(TEXT-UTF8char / UTF8-CONT / LWS) 
    
