entity="sip:t-jones@example.com">
           <tuple id="0">
             <status>
               <basic>open</basic>
        	     <es:activities>
               <es:activity>on-the-phone</es:activity>
m=message 5060 sip <SIP URI>

m=message 5060 sip <SIP URI>

