tmTransport = snmpSSHDomain
tmAddress = an snmpSSHAddress
tmRequestedSecurityLevel = ["noAuthNoPriv" | "authNoPriv" |
tmTransportSecurityLevel = "authPriv"
tmSecurityName = the principal name [to be] authenticated by SSH.
tmSameSecurity = true or false, depending on whether the Security
tmTransportDomain = snmpSSHDomain
tmTransportAddress = a snmpSSHAddress
tmSecurityLevel = "authPriv"
tmsSecurityName = the principal name authenticated by SSH.  By
statusInformation =
statusInformation =
statusInformation =
statusInformation =
