home_token = First (128, HMAC_SHA1(Kcn, (HV | home_nonce | 0)))

home_token = First (128, HMAC_SHA1(Kcn, (HV | home_nonce | 0)))
HV = SHA1 (HoA | RN)

careof_token = First (128, HMAC_SHA1(Kcn, (CoA | HV | careof_nonce
Kbm = SHA1(home_token | careof_token)

MAC = First (128, HMAC_SHA1(Kbm, (CoA | CN | BU)))

MAC = First (128, HMAC_SHA1(Kbm, (CoA | CN | BA)))

Kbm = SHA1(home_token | careof_token | 0)

Ken = SHA1(home_token | careof_token | 1)

ENC = AES (Ken, HoA | RN)

MAC = First (128, HMAC_SHA1(Kbm, (CoA | CN | BU)))

MAC = First (128, HMAC_SHA1(Kbm, (CoA | CN | BA)))

MAC = First (128, HMAC_SHA1(Kbm, (CoA | CN | BU)))

MAC = First (128, HMAC_SHA1(Kbm, (CoA | CN | BA)))

