m=video
a=simulcast:recv a,b,c
a=please-send-ssrcs

pc = new RTCPeerConnection({showSsrcInSimulcastOffer: true})

m=video
a=simulcast:send hi,mid,low
a=rid:hi send
a=rid:mid send
a=rid:low send
a=ssrc-group:FID 123 456 789
a=ssrc:123 cname:foo
a=ssrc:456 cname:foo
a=ssrc:789 cname:foo

a=ssrc-group.  Each of these is defined in an RFC with security
