mean = Sum of Burst Durations / Number of Bursts

var = ( Sum of Squares of Burst Durations - Number of Bursts * mean^2
rtcp-xr-attrib = "a=" "rtcp-xr" ":" [xr-format *(SP xr-format)] CRLF

xr-format = xr-format / xr-bgl-block

xr-bgl-block = "xr-bgl"
