Network=IPv4,IPv6

Transport=Tcp

TransportSecurity=SSL3,TLS

Application=IRCFile

IPv4Address = 1*3digit "." 1*3digit "." 1*3digit "." 1*3digit

IPv6Address =  hexseq | hexseq "::" [hexseq] | "::" [hexseq]
hexseq = hex4 *( ":" hex4 )
hex4 = 1*4hexdig

Port=9834

ErrorTokens=Network,TransportSecurity

ErrorMessage="I do not trust you."
File="my file.txt"

Size=93424

Offset=7543

Multi=9874
dcc2-publish       = `DCC2` 1*(space (ConnectionTokens | AppTokens))

ConnectionTokens = ConnectionToken [ 1* (space ConnectionToken)]

AppTokens = Apptoken [ 1* (space AppToken) ]

ConnectionToken = 1*TokenChars [ ('=' | '+=' ) 1*TokenChars [ 1* (',' 1*TokenChars) ] ]

AppToken = 1*TokenChars [ ('=' | '+=' ) dcc2-quotedname ]

TokenChars = 1* (digit | alpha)

dcc2-quotedname = 1*filechar | (%d34 1*(filechar | space ) %d34)

filechar = digit | alpha | filepunct

filepunct = %d33 %d35-41 %d43-46 %d61 %d64 %d91 %d93-95 %d123 %d125-126
dcc2-response = 'DCC2' space ( 'Accept' | 'CannotAccept' | 'Refused' ) 1*(space Token)

Token = 1*TokenChars [ '=' dcc2-quotedname ]


