nonNegativeIntegerConstruct =
         atomCommonAttributes,
         xsd:nonNegativeInteger

expiresElement = element age:expires { atomDateConstruct }

maxageElement = element age:max-age { nonNegativeIntegerConstruct }

