C-Type = 1 (IEEE Canonical Address format)

C-Type = 1 (IEEE 802 Canonical Address Format as defined below)
class = 165.

               0              1               2               3
C-Type=1 (IEEE Canonical address format), such a version of the L2
