link-info       =  link-info-data
link-info       =/ link-info-data "," network-id
link-info       =/ link-info-data "," 1*OCTET
link-info-data  =  "bw=" 1*DIGIT bandwidth
bandwidth       =  "kbps" / "Mbps" / "kB"
network-id      =  "nid=" network-id-list
network-id-list =  1*base64
network-id-list =/ 1*base64 ";" network-id-list
network-id-list =/ 1*base64 "," 1*OCTET
base64          =  ALPHA / DIGIT / "+" / "/" / "="

