K = cubic_root(W_max*beta/C) (Eq. 2)

W_max = cwnd;    // remember the window size before reduction
cwnd = cwnd * (1-beta);    // window reduction

                                 Figure 1

W_last_max = W_max;            // remember the last W_max.
W_max = W_max*(2-beta)/2;      // further reduce W_max.
W_last_max = W_max             // remember the last W_max.

                                 Figure 2

RTT = 100ms.  The average window size W is in MSS-sized segments.

                                  Table 1

RTT = 10ms.  The average window size W is in MSS-sized segments.

                                  Table 2






RTT = 10ms and p=10^-6, TCP has an average window of 1200 packets.
