ip=1.2.3.4) }    -->

                                   <-- HDR, SK {EAP(success),
                                            DHCP(ACK, ip=1.2.3.4),
                                            SAr2,
                                            TSi(1.2.3.4-1.2.3.4),
                                            TSr(0.0.0.0-
                                            255.255.255.255)}

ip=1.2.3.4)}     -->

                                   <-- HDR, SK {IDr, [CERT,]
                                            AUTH,
                                            DHCP(ACK, ip=1.2.3.4),
                                            SAr2,
                                            TSi(1.2.3.4-1.2.3.4),
                                            TSr(0.0.0.0-
                                            255.255.255.255)}

