INFLIGHTMAX = 4 and TIMEOUT = 1500 milli-seconds.

INFLIGHTMAX = 4 + 3 * ( RTT / PT ) * ( RTT / RTT_RECENT )

TIMEOUT = INFLIGHTHIGH * PT + 2 * RTT_MAX

RTT_RECENT = ALPHA * TRIP + (1-ALPHA) * RTT_RECENT

