Source ==>|device1|====>|device2|====>|device3|====>|device4|===>Sink 
             +-------+     +-------+     +-------+     +-------+ 
    
Source ==>|domainA|====>|domainB|====>|domainC|====>|domainC|===>Sink 
             +-------+     +-------+     +-------+     +-------+ 
    
