Prefer       =  "Prefer" ":" 1#preference

preference   =  "return-no-content" | preference-extension
preference-extension =  token [ "=" ( token | quoted-string )
                             *prefer-params ]
prefer-params =  ";" token [ "=" ( token | quoted-string ) ]

