flood-message = [M_FLOOD, session-id, initiator, ttl,
                    +[objective, (locator-option / [])]]

objective = ["AN_Proxy", objective-flags, loop-count,
                                          objective-value]

ttl             = 180000     ; 180,000 ms (3 minutes)
initiator = ACP address to contact Registrar
objective-flags   = sync-only  ; as in GRASP spec
sync-only         =  4         ; M_FLOOD only requires synchronization
loop-count        =  1         ; one hop only
objective-value   =  any       ; none

locator-option    = [ O_IPv6_LOCATOR, ipv6-address,
                       transport-proto, port-number ]
ipv6-address      = the v6 LL of the Proxy
port-number      = selected by Proxy

           Figure 10: CDDL definition of Proxy Discovery message

flood-message = [M_FLOOD, session-id, initiator, ttl,
                    +[objective, (locator-option / [])]]

objective = ["AN_join_registrar", objective-flags, loop-count,
                                          objective-value]

initiator = ACP address to contact Registrar
objective-flags = sync-only  ; as in GRASP spec
sync-only =  4               ; M_FLOOD only requires synchronization
loop-count      = 255        ; mandatory maximum
objective-value = text       ; name of the (list of) of supported
                                ; protocols: "EST-TLS" for RFC7030.

       Figure 13: CDDL definition for Registrar announcement message

locator1  = [O_IPv6_LOCATOR, fd45:1345::6789, 6,  443]
locator2  = [O_IPv6_LOCATOR, fd45:1345::6789, 17, 5683]
locator3  = [O_IPv6_LOCATOR, fe80::1234, 41, nil]

audit-log-response = {
     "version": uint,
     "events": [ + event ]
     "truncation": {
       ? "nonced duplicates": uint,
       ? "nonceless duplicates": uint,
       ? "arbitrary": uint,
     }
event = {
     "date": text,
     "domainID": text,
     "nonce": text / null,
     "assertion": "verified" / "logged" / "proximity",
     ? "truncated": uint,
enrollstatus-post = {
       "version": uint,
       "status": bool,
       "reason": text,
       ? "reason-context" : { $$arbitrary-map }
     }
XMmtlTkBNIC3VWofZsKHSjgdz1PpWFOnrBHUABnSWqEvAMiKxOA=
jHzXm3AgkbThfw==
TkBNIC3VWofZsKHSjgdz1PpWFOnrBHUABnSWqEvAMiKxOA="}}

