Transmit_Form = Encode(Encrypt(Canonicalize(Local_Form)))
Local_Form = DeCanonicalize(Decipher(Decode(Transmit_Form)))

LjEPMA0GA1UECxMGQmV0YSAxMQ8wDQYDVQQLEwZOT1RBUlk=,
EtE7K2QDeVMCyXsdJlA8fA==

YSBibGFuayBsaW5lOg0KDQpUaGlzIGlzIHRoZSBlbmQuDQo=
LjEPMA0GA1UECxMGQmV0YSAxMQ8wDQYDVQQLEwZOT1RBUlk=,66

