to="example.com" id="..." type="get">
to="user@example.com/resource" id="..." type="result">
to="example.com" id="..." type="get">
to="other@example.net/check"
id="..." type="get">
content = cleartext || sender.sign(cleartext)
ciphertext = encrypt(keys[keyid].key, nonce, content)

from='juliet@example.com/balcony'
id='ktx72v49'
to='romeo@example.net'
type='chat'
from='juliet@example.com/balcony'
id='ktx72v49'
to='romeo@example.net'
type='chat'>
nonce = HKDF(0, sender.fullJID, 'nonce', N_MAX) XOR seqno

to="muc@example.com"
type="set">
to="example.com"
id="..." type="get">
to="example.com"
id="..." type="result">
