TR1==========+---------+==========TR3
  |           |         |
  D1          |         |
  |           |   DUT   |
TR2==========|         |
              +---------+

TR1==========+---------+==========TR3
  |           |         |
  D1          |         |
  |           |   DUT   |
TR2==========|         |
              |         |
                  ...
TRn==========+---------+


TR1==========+---------+==========TR3
  |           |         |
  D1          |         |
  |           |   DUT   |
TR2==========|         |
              |         |
                  ...
TRn==========+---------+

TR1==========+---------+==========TR3
  |           |         |
  D1          |         |
  |           |   DUT   |
TR2==========|         |
              |         |
                  ...
TRF==========+---------+

