mud-uri   = "https://" authority  "/.well-known/mud/" mud-rev
                  "/" model "/" dev-rev *( "?" extras )
              ; authority is from RFC3986
mud-rev   = "v1"
model     = segment  ; from RFC3986
dev-rev   = segment  ; from RFC3986
extras    = query    ; from RFC3986


xmlns="urn:ietf:params:xml:ns:yang:ietf-access-control-list"
