xmlns="urn:ietf:params:xml:ns:ers"  
targetNamespace="urn:ietf:params:xml:ns:ers"  
elementFormDefault="qualified"  
attributeFormDefault="unqualified"> 
type="EncryptionInfo" minOccurs="0"/> 
type="SupportingInformationType" minOccurs="0"/> 
type="ArchiveTimeStampSequenceType"/> 
fixed="1.0"/> 
type="ObjectIdentifier"/> 
type="DigestMethodType"/> 
type="CanonicalizationMethodType"/> 
type="ArchiveTimeStampType"  
maxOccurs="unbounded" /> 
use="required"/> 
maxOccurs="unbounded"/> 
use="required"/> 
type="CryptographicInformationType" minOccurs="0"/> 
maxOccurs="unbounded"/> 
use="required"/> 
maxOccurs="unbounded"/> 
use="required"/> 
use="optional"/> 
maxOccurs="unbounded"> 
maxOccurs="unbounded"/> 
use="required"/> 
use="required"/> 
maxOccurs="unbounded"> 
maxOccurs="unbounded"/> 
use="required"/> 
 
 
 
    

