rel="impl-info"

anchor="coap://spurious.example.com:5683",
anchor="coap://[2001:db8:3::123]:61616"

anchor="coap://[2001:db8:3::124]",
anchor="coap://[2001:db8:3::124]",
anchor="coap://[2001:db8:3::124]"

anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616"

anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616"

anchor="coap://sensor1.example.com",
if="sensor"; anchor="coap://sensor1.example.com",
if="sensor"; anchor="coap://sensor1.example.com",
anchor="coap://sensor1.example.com/sensors/temp",
anchor="coap://sensor1.example.com/sensors/temp",
anchor="coap://sensor2.example.com",
if="sensor"; anchor="coap://sensor2.example.com",
if="sensor"; anchor="coap://sensor2.example.com",
anchor="coap://sensor2.example.com/sensors/temp",
anchor="coap://sensor2.example.com/sensors/temp"

et="core.rd-group";anchor="coap://[ff35:30:2001:db8::1]",
et="core.rd-group";
anchor="coap://[ff35:30:2001:db8::1]"

base=authority parameter value)

R = used at registration, L = used at lookup, A = expressed in link
base="coap://[ff05::1]"

ep= and removed the h= and ins= parameters.

ep= parameter to be present.

rt="temperature"; anchor="coap://spurious.example.com:5683",
rt="light-lux"; if="sensor";
anchor="coap://local-proxy-old.example.com:5683"

anchor="coap://spurious.example.com:5683",
if="sensor"; anchor="coaps://new.example.com:5684",

base="coap://[ff05:;1]",
base="coap://[ff35:30:2001:db8::1]"

anchor="coap://spurious.example.com:5683",
et="oic.d.sensor";ct="40",
et="oic.d.sensor";ct="40";d="floor-3"

rel="hosts".

rel="describedby"

anchor="coap://[2001:db8:f0::1]"

anchor="coap://[2001:db8:f0::1]",
anchor="coap://[2001:db8:f0::1]",
anchor="coap://[2001:db8:f0::1]/sensors/temp";rel=alternate,
anchor="coap://[2001:db8:f0::1]/sensors/temp";rel="describedby"

anchor="coap+tcp://simple-host1.example.com"

at="coap+tcp://[2001:db8:f1::2]"

if="core.s"; anchor="coap://[2001:db8:f1::2]"

if="core.s";anchor="coap+tcp://[2001:db8:f1::2]"
