grant_type=refresh_token&refresh_token=tGzv3JOkF0XG5Qx2TlKWIA
scope       = scope-token *( SP scope-token )
scope-token = 1*( %x21 / %x23-5B / %x5D-7E )


grant_type=authorization_code&code=SplxlOBeZQQYbYS6WxSbIA
grant_type=password&username=johndoe&password=A3ddj3w


grant_type=client_credentials


grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Asaml2-
grant_type=refresh_token&refresh_token=tGzv3JOkF0XG5Qx2TlKWIA


nonce="274312:dj83hs9s",
mac="kDZvddkndxvhGRXZhvuDjEWhGeE="


type-name  = 1*name-char
name-char  = "-" / "." / "_" / DIGIT / ALPHA
param-name  = 1*name-char
name-char   = "-" / "." / "_" / DIGIT / ALPHA


response-type  = response-name *( SP response-name )
response-name  = 1*response-char
response-char  = "_" / DIGIT / ALPHA


error      = 1*error-char
error-char = %x20-21 / %x23-5B / %x5D-7E



VSCHAR     = %20-7E
NQCHAR     = %x21 / %x23-5B / %x5D-7E
NQSCHAR    = %x20-21 / %x23-5B / %x5D-7E
UNICODENOCTRLCHAR = <Any Unicode character other than ( %x0-1F / %x7F )>
client-id     = *VSCHAR

client-secret = *VSCHAR

response-type = response-name *( SP response-name )
response-name = 1*response-char
response-char = "_" / DIGIT / ALPHA

scope       = scope-token *( SP scope-token )
scope-token = 1*NQCHAR

state      = 1*VSCHAR

redirect-uri      = URI-reference
error             = 1*NQSCHAR

error-description = 1*NQSCHAR

error-uri         = URI-reference

grant-type = grant-name / URI-reference
grant-name = 1*name-char
name-char  = "-" / "." / "_" / DIGIT / ALPHA

code       = 1*VSCHAR

access-token = 1*VSCHAR
token-type = type-name / URI-reference
type-name  = 1*name-char
name-char  = "-" / "." / "_" / DIGIT / ALPHA

expires-in = 1*DIGIT

username = *UNICODENOCTRLCHAR

password = *UNICODENOCTRLCHAR

refresh-token = 1*VSCHAR

param-name = 1*name-char
name-char  = "-" / "." / "_" / DIGIT / ALPHA


