ct=16 stands for the Content-Format "application/cose", and ct=TBD2
Ver = 1
T = 0 (CON)
Code = 0x01 (0.01 is GET)
Payload = [Empty]

Ver=1
T=2 (ACK)
Code = 0x45 (2.05 Content)
Payload =
Payload =
Payload =
Payload =
