SharedSecret = OWF (ClientName, PassPhrase, ServerName)

PassKey = (OWF)N (SharedSecret)

AuthProof = OWF (PassKey, Time-C, Confounder-C, PassKey)

AuthVerif = OWF (PassKey, Time-C, Confounder-C, PassKey)

AuthConfirm = OWF (PassKey, Confounder-S, Time-C, Confounder-C,
                         PassKey)

AuthVerif = OWF (PassKey, Confounder-S, Time-C, Confounder-C, 
                      PassKey)

IDK = OWF ( PassKey, server-name, Time-C, Confounder-C, PassKey )

CDK = OWF ( PassKey, server-name, Confounder-C, Time-C, PassKey )

mic = OWF ( IDK, Data-Encoding, IDK )

seal = OWF ( IDK, Data-Encoding, IDK )

seal = OWF ( CDK, Data-Encoding, IDK )

C0 = B0 XOR OWF(CDK)

Cn = Bn XOR OWF(Cn-1, CDK)

