SKEYSEED = prf(Ni | Nr, g^ir)
SK_d = prf(SKEYSEED, g^ir | Ni | Nr | CKY-I | CKY-R | 0)
SK_a = prf(SKEYSEED, SK_d | g^ir | Ni | Nr | CKY-I | CKY-R | 1)
SK_e = prf(SKEYSEED, SK_a | g^ir | Ni | Nr | CKY-I | CKY-R | 2)

KEYMAT = K1 | K2 | K3 | ...
K1 = prf(SK_x, 0)
K2 = prf(SK_x, K1)
K3 = prf(SK_x, K2)
KEYMAT = prf(SK_d, protocol | SPI | Nin | Nout )

KEYMAT = prf(SK_d, g(p2)^ir | protocol | SPI | Nin | Nout )

KEYMAT = K1 | K2 | K3 | ...
K1 = prf(SK_d, [ g(p2)^ir | ] protocol | SPI | Nin | Nout)
K2 = prf(SK_d, K1 | [ g(p2)^ir | ] protocol | SPI | Nin | Nout)
K3 = prf(SK_d, K2 | [ g(p2)^ir | ] protocol | SPI | Nin | Nout)
SKEYSEED = prf(SK_d (old), [g(p2)^ir] | 0 | CKY-I | CKY-R | Ni |
