D=25/  |----+   :  :   +---| X       X |---+   :  :   +----|  \ D=25
   /    |        :  :       |   X   X   |       :  :        |    \   V/24
D=15 X  |----+   :  :   +---| X       X |---+   :  :   +----|  X D=10
       X|PE12|...:  :...|212|-----------|232|...:  :...|PE22|X
        |----+          +---|   D=10    |---+          +----|
        |                   |           |                   |
        |     AS 1          |           |     AS 2          |
        +-------------------+           +-------------------+



               Figure 6: VPN CAR reference topology

   The following network design assumptions apply to the reference
   topology above, as an example:

   -  Independent ISIS/OSPF SR instance in each AS.

   -  eBGP peering link between VPN ASBRs 121-211, 121-212, 122-211,
      122-212.

   -  VPN service is running between PEs via service RRs in each AS
      to local ASBRs.  Between ASBRs, its Option-B i.e. next hop self
      for VPN SAFI.

   -  CE1 is dual homed to PE11 and PE12.  Similarly, CE2 is dual
      homed to PE21 and PE22.

   -  Peering links have equal cost metric

   -  Peering links have delay configured or measured as shown by
      "D".

   -  CE2 advertises prefix V/24 to CE1.  It is advertised as RD:V/24
      between PEs, including color-awareness

