flags = "",
service = "isatap",
regexp =  "",
replacement = Fully Qualified Domain Name of the isatap router


flags = "",
service = "isatap",
regexp =  "",
replacement = "r21.example.com"



flags = "",
service = "TB",
regexp =  "",
replacement = Fully Qualified Domain Name of the Tunnel Broker


flags = "",
service = "TB",
regexp =  "",
replacement = "tb.example.com"



