tmTransport = snmpSSHDomain

tmAddress = a snmpSSHAddress

tmSecurityLevel = "authPriv"

tmSecurityName = the principal name authenticated by SSH.  How
tmSameSession = for outgoing messages, to indicate whether the
sshtmSessionID = [DISCUSS: SSH transport session identifier]

tmTransportDomain = snmpSSHDomain

tmTransportAddress = a snmpSSHAddress

tmSecurityLevel = "authPriv"
tmsSecurityName = the principal name authenticated by SSH.  How
statusInformation =
statusInformation =
statusInformation =
statusInformation =
sshtmUserStatus=createAndWait)
