protocol="application/pgp-signature";
micalg="pgp-sha1";
boundary="===============AAAAAAAAAA=="
boundary="------------010307000006020005010307"

name="TrnGranger.eml.gpg"
filename="TrnGranger.eml.gpg"

kQ==
