I=10: Interval Duration - the reported value applies to the
I=11: Cumulative Duration - the reported value applies to the
I=01: Sampled Value - the reported value is a sampled
mean = Sum of Burst Durations / Number of Bursts

var = ( Sum of Squares of Burst Durations - Number of Bursts *
I=10: Interval Duration - the reported value applies to the
I=11: Cumulative Duration - the reported value applies to the
I=01: Sampled Value - the reported value is a sampled
xr-format = / xr-bglss-block
               / xr-bgdss-block
               / xr-fiss-block
xr-bglss-block= "burst-gap-loss-stat"
xr-bgdss-block = "burst-gap-discard-stat"
xr-fiss-block= "frame-impairment-stat"
