extension-field    = media-features CRLF

media-features     = "Accept-Features" ":"
                            media-feature-tags
media-feature-tags = <*text as defined by other documents,
                            with LWSP wrapping)

