message         = [authorize-id] TAB authenticate-id TAB password

ACHAR           = %x20..7E

PCHAR           = %x01..09 / %x0B..0C / %x0E..7F

TAB             = %x09

authenticate-id = 1*255ACHAR

authorize-id    = 1*255ACHAR

password        = 1*255PCHAR
