ust_status_ok                 = 0,   /* no errors                   */
ust_status_fail               = 1,   /* unspecified failure         */
ust_status_unsupported_param  = 2,   /* parameter not supported     */
ust_status_alloc_fail         = 3,   /* memory allocation failure   */
ust_status_init_fail          = 4,   /* initialization failure      */
ust_status_auth_fail          = 5,   /* authentication check failed */
ust_status_replay_fail        = 6    /* replay check failed         */
