header-name = [":"] 1*header-char

header-char = "!" / "#" / "$" / "%" / "&" / "'" /
                  "*" / "+" / "-" / "." / "^" / "_" /
                  "`" / "|" / "~" / DIGIT / LOWERALPHA

LOWERALPHA = %x61-7A


