sonetPathCurrentWidth           = 3, 
pwVcCepCfgSonetPaylaodLength    = 783 -- payload bytes 
pwVcCepCfgMinPktLength          = 0   -- no minimum 
pwVcCepCfgPktReorder            = FALSE 
pwVcCepCfgEnableDBA             = ais 
pwVcCepCfgRtpHdrSuppress        = FALSE 
pwVcCepCfgJtrBfrDepth           = 500 -- micro-seconds 

pwVcCepCfgConsecPktsInsync      = 2   -- Exit  LOPS state 
pwVcCepCfgConsecMissingOutSync  = 10  -- Enter LOPS state 

pwVcCepCfgPktErrorPlayOutValue  = playAllOnes 

pwVcCepCfgMissingPktsToSes      =  3  -- packets, 
pwVcCepCfgSesToUas              =  2  -- seconds, 
pwVcCepCfgSecsToExitUas         = 10  -- seconds, 

pwVcCepCfgRowStatus             = createAndGo 
pwVcCepSonetIfIndex     = 23 -- Index of associated entry 
                               -- in sonetPathCurrent table. 

pwVcCepSonetTimeSlot    = 1  -- Starting time slot. 

pwVcCepCfgIndex         = 9  -- Index of associated entry 
                               -- in pwVcCepCfg table (above). 
