targetNamespace="urn:ietf:params:xml:ns:spit-policy"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

schemaLocation="http://www.w3.org/2001/xml.xsd"/>

type="xs:string"/>

type="xs:integer" default="0"/>

type="xs:integer" default="0"/>

