s = ibf_salt % 64;
k = key

k = (k >> s) | (k << (64 - k))
salt = 0
XTR=HMAC-SHA256
PRF=HMAC-SHA256
key = HKDF(XTR, PRF, salt, element)
key = key modulo 2^64 // Truncate
bucket = CRC32(key)

i = 0
filled = 0
element_already_in_bucket = false
j = 0
element_already_in_bucket = true
x = (bucket << 32) | i
bucket = CRC32(x)

