Type = 8: DREQ     Diagnostic Request

Type = 9: DREP     Diagnostic Reply

target=response address given in the DREQ header, else set
target = the last address in ROUTE.

R-error=0x01. The requester can overcome this problem by sending a
