x = 0;
index = ((x * 7) + y) % 3;
pdu = newPDU();
portSpeed = getVar("ifSpeed." + ev(0));

oid = "";
oid = "ifType.3";
oid = "";
rate = counterRate("ifInOctets.$*", 300);
rate = counterRate("ifInOctets.$*", 300, 0,
                                 "sysUpTime.0", 1);
delta = counterRate("ifInErrors.$*", 0);
done = 0;
oid = "ipForwardIfIndex.0.0.0.0.13.0.192.168.1.1";
index = 11;
dest   =  parseIndex(oid, index, String, 4);
proto  =  parseIndex(oid, index, Integer, 0);
policy =  parseIndex(oid, index, Integer, 0);
nextHop = parseIndex(oid, index, String, 4);
statusInformation =          -- success or
statusInformation =          -- success or
