P=1: the PCS takes into account the "request priority" in its 
P=0: the PCS does not take the request priority into account 
    
M=1: the PCS is capable of computing more than one paths obeying a 
M=0: the PCS cannot compute more than one path obeying a set of 
D=1: the PCS is capable of computing diversely (link, node, SRLG) 
D=0: the PCS is not capable of computing diversely routed paths. 
E=1: the PCS is capable of computing TE LSP paths excluding some 
E=0: the PCS is not capable of computing paths excluding network 
G=1: the PCS supports the computation of CSPF with various metrics 
G=0: the PCS just computes the CSPF based on the TE metric 
    
