r = MAX_RTP_RATE*AVG_RTP_SIZE

p = MAX_RTP_RATE*MAX_RTP_SIZE

MIN_RTP_SIZE = MIN_AU_SIZE	 Plus AL-PDU and RTP  overhead

MIN_RTP_SIZE = Sum of the MIN_AU_SIZEs from each of the N AL-PDUs
               Plus AL-PDU and RTP  overhead

m = MIN_RTP_SIZE IP datagram size

M = MAX_RTP_SIZE IP datagram size

S = MAX_DELAY - (b/r + Ctot/r + Dtot).
				  
