tableLookup = 1.

tableLookup = 1.

fieldType = FT_FP
fieldType = FT_F2_ONB
fieldType = FT_F2_ONB
sig = m^d mod n
s = (m')^d mod n
sig = (r^-1) * s mod n
MacLen = 4
HexInputBytes =
HexOuputBytes = 25d9f281
MacLen = 4
HexInputBytes =
HexOuputBytes = fe9f43a5
MacLen = 8
HexInputBytes =
HexOuputBytes = 4981df90a4c7e5cc
MacLen = 8
HexInputBytes =
HexOuputBytes = dba728ba227bcc85

MacLen = 4
HexSaltBytes = 76543210
HexKey = fedcba98
HexInputBytes =
HexOuputBytes =
MacLen = 8
HexSaltBytes = 76543210
HexKey = fedcba98
HexInputBytes =
HexOuputBytes =
RSA_REGISTER_SIZE == RSA_32_BIT_REGISTER
