TYPE = "custom"

VALUE = {custom defined}

TYPE = "claim-client-assertion-saml-1.0"

VALUE = {base64-encoded SAML assertion}

TYPE = "claim-client-claims-oidc-1.0"

VALUE = {set of oidc reserved claims}

TYPE = "custom"

VALUE = {custom defined}

TYPE = "claim-client-claims-oidc-1.0"

VALUE = {set of oidc reserved claims}
TYPE = "claim-client-redirect-1.0"

VALUE = {value of the scope at AS}

