Emergency-dialstring       = "Emergency-dialstring " HCOLON 
                                Emergency-dialstring-value *(COMMA 
                                Emergency-dialstring-value)
Emergency-dialstring-value = (numeric-string "." service-identifier /
                                option-tag)
service-identifier         =  token-nodot
token-nodot                =  1*( alphanum / "-"  / "!" / "%" / "*"
                                  / "_" / "+" / "`" / "'" / "~" )
option-tag                 =  string

   NOTE: we aren't sure this BNF is correct.  The goal is to get this 
         Result as a Request:

   Emergency-Dialstring: <psap.police; country-code=country>, 
                         <psap.fire; country-code=country>

   And this result in a Response (the example here is for the US):

   Emergency-Dialstring: <911.psap; country-code=us> 


