lw-ap-req = { // version number will match tkt vno.
        uint16           message type
        lw-ticket        ticket
        lw-authenticator authenticator
lw-ap-reply = {
        uint16            version number
        uint16            message type
        uint16            extensions field length
        extfield          extensions field
        encryptedpart     lw-encreplypart
lw-encreplypart = {
        key            subkey
        uint64         sequence number
        uint32         time0
        uint32         time1
lw-ticket = {
        uint16          version number
        namestring      server name     // not present in service ticket
                                        // UTF-8 encoding
        namestring      server realm
        uint16          extensions field length
        extfield        extensions field
        encryptedpart   encticket
encticket = {
        namestring     client name
        namestring     client realm
        key            session key
        uint32         logon time      // not present in service ticket
        uint32         expiration time
        uint32         renew time      // not present in service ticket
namestring = {
        uint16         name length
        string         name           // UTF-8 encoding
extfield = {
        uint16         type0
        uint16         length0
        uchar[length0] data0
        uint16         type1
        uint16         length1
        uchar[length1] data1
        ...
lw-authenticator = {      //  version number matches ticket vno
        uint32      time0
        uint32      time1
        key         subkey
        uint64      sequence number
        uint16      extensions field length
        extfield    extensions field
servicetkt-skey = {
        encryptedpart   encsrvtktskey  // encrypted in the TGT skey
encsrvtktskey = {
        key             service tkt session key
enckdcreppart = {
        encryptedpart   local-kdc-rep-body  // encrypted in srvtktskey
local-kdc-rep-body = {
        namestring server name  // UTF-8 encoding
        namestring server realm // UTF-8 encoding
        uint32     expiration time // could add to servicetkt-skey too
key = {
        uint16        keytype
        uint16        length
        uchar[length] keyvalue
encryptedpart = {
        uint16        etype
        uint16        keyversion
        uint16        length
        uchar[length] ciphertext    // define ciphertext for RC4,
                                    // AES etypes
lw-passthrough = {
        ap-req        lw-ap-req  // using client TGT or client
                                 // xrealm TGT
        ticket        lw-ticket  // server or KDC lw-tgt
ErrorMessage = {
        uint16        error code
        uint16        extensions field length
        extfield      extensions field
