property = value1 OR property = value2 .OR property = valueN 

type="freeform">companies</property>
        <property name="geography" type="ISO3166-1">FR</property>
status-code = class "." subject "." detail
class = "2"/"3"/"4"/"5"
subject = 1*3digit
detail = 1*3digit

