S1 = H3(A|B|PW|g^Ra?|g^Rb|(g^Ra?)^Rb)

            Alice 
              verifies that Y <> 0;
              divides Y by H2(A|B|PW) to get g^Rb?, the recovered value of g^Rb. 
              authenticates Bob by checking if computed S1 equals received S1;
