status="pending"/>
policy=       +----------+                                         
policy = accept  | |          +-------+          |               
                          | |subscribe |       |          |               
                          | +----------|waiting|----------+               
                          +----------->|       |                          
                           timeout     |       |                          
                                       +-------+                          
                                                                          



status="pending"/>
status="active" event="approved" />
