m=audio 55954 RTP/AVP 98 99
a=rtpmap:98 EVRCWB0/16000
a=rtpmap:99 EVRCB0/8000
a=fmtp:98 mode-set-recv=0,4;sendmode=0
a=fmtp:99 recvmode=0 sendmode=4

m=audio 55954 RTP/AVP 98
a=rtpmap:98 EVRCWB0/16000
a=fmtp:98 mode-set-recv=4;sendmode=4

m=audio 49120 RTP/AVP 97 98
a=rtpmap:97 EVRCWB/16000
a=rtpmap:98 EVRCB0/8000
a=fmtp:97 mode-set-recv=0,4;sendmode=0
a=fmtp:98 recvmode=0 sendmode=0
a=maxptime:120



m=audio 49120 RTP/AVP 97 98
a=rtpmap:97 EVRCWB0/16000
a=rtpmap:98 EVRCB0/8000
a=fmtp:97 mode-set-recv=0,4;sendmode=0
a=fmtp:98 recvmode=0 sendmode=0



m=audio 49120 RTP/AVP 97
a=rtpmap:97 EVRCWB0/16000
a=fmtp:97 mode-set-recv=4;sendmode=4


m=audio 49120 RTP/AVP 97 98
a=rtpmap:97 EVRCWB1/16000
a=fmtp:97 mode-set-recv=4;sendmode=4
a=maxptime:100
m=audio 49120 RTP/AVP 97 98
a=rtpmap:97 EVRCWB/16000
a=rtpmap:98 EVRCB0/8000
a=fmtp:97 silencesupp=1;dtxmax=32;dtxmin=12;hangover=1 \
mode-set-recv=0,4; sendmode=0
a=fmtp:98 recvmode=0 sendmode=0
a=maxptime:120


m=audio 49120 RTP/AVP 97 98
a=rtpmap:97 EVRCWB/16000
a=rtpmap:98 EVRCB0/8000
a=fmtp:97 silencesupp=0;dtxmax=32;dtxmin=12;hangover=1 \
mode-set-recv=0,4;sendmode=0
a=fmtp:98 recvmode=0 sendmode=0
a=maxptime:120


m=audio 49120 RTP/AVP 97
a=rtpmap:97 EVRCB/8000
a=fmtp:97 recvmode=0 sendmode=4
a=maxptime:120


m=audio 49120 RTP/AVP 97
a=rtpmap:97 EVRCB0/8000
a=fmtp:97 recvmode=0 sendmode=4
m=audio 55954 RTP/AVP 98 99
a=rtpmap:98 EVRCWB0/16000
a=rtpmap:99 EVRCB0/8000
a=fmtp:98 mode-set-recv=0,4;sendmode=0
a=fmtp:99 recvmode=0 sendmode=0

m=audio 55954 RTP/AVP 99
a=rtpmap:99 EVRCB0/8000




m=audio 55954 RTP/AVP 98 99
a=rtpmap:98 EVRCWB0/16000
a=rtpmap:99 EVRCB0/8000
a=fmtp:98 mode-set-recv=0,4; sendmode=0
a=fmtp:99 recvmode=0 sendmode=0

m=audio 55954 RTP/AVP 99
a=rtpmap:99 EVRCB0/8000
a=fmtp:99 recvmode=0 sendmode=4

m=audio 55954 RTP/AVP 99
a=rtpmap:99 EVRCB0/8000
a=fmtp:99 recvmode=0 sendmode=4

m=audio 55954 RTP/AVP 99
a=rtpmap:99 EVRCB0/8000

m=audio 55954 RTP/AVP  99
a=rtpmap:99 EVRCB0/8000

m=audio 55954 RTP/AVP 99
a=rtpmap:99 EVRCB0/8000
a=fmtp:99 recvmode=0 sendmode=4
