Claims-Set = {
    * $$Claims-Set-Claims
    * Claim-Label .feature "extended-claims-label" => any
Claim-Label = int / text
string-or-uri = text

iss-claim-label = JC<"iss", 1>
sub-claim-label = JC<"sub", 2>
aud-claim-label = JC<"aud", 3>
exp-claim-label = JC<"exp", 4>
nbf-claim-label = JC<"nbf", 5>
iat-claim-label = JC<"iat", 6>
cti-claim-label = CBOR-ONLY<7>  ; jti in JWT: different name and text

CWT-cnf = {
     (1: CWT-COSE-Key) //
     (2: CWT-Encrypted_COSE_Key) //
     (3: CWT-kid)
CWT-COSE-Key = COSE_Key
CWT-Encrypted_COSE_Key = COSE_Encrypt / COSE_Encrypt0
CWT-kid = bytes

CWT-scope = bytes / text

CWT-ace-profile = $CWT-ACE-Profiles /
     int .feature "ace_profile-extend"
CWT-cnonce = bytes

CWT-exi = uint ; in seconds (5.10.3)

