i = 65,536 * t + s,

IV = ROC || FLAG || M || PT  || SEQ || TS || SSRC

k_s = 0.

ct   = ct + 1 mod 2^128                       (Eq. 2)

m = k_s || 0x555..5,

IV = SRTCP index || FLAG || PT || 0..0 || SSRC

version      = 2
padding      = 0
extension    = 0
timestamp    = 50681de5
SSRC         = 5c621599

FLAG = 0
