x=A for Upstream (L->R)

x=A for Upstream (L->R)

x=A for Downstream (L->R)

                                       IE  x=A
                                      resp x=<>
x=A, s: resp
x=A for Upstream (L->R)

x=B for Upstream (L->R)

x=B should be the value used, determines that the result of
x=A for Upstream (L->R)

x=A for Downstream (L->R)

                                       IE  x=B
                                      resp x=<>
x=B, s: resp
                          <- conflict detected!
                          <- resolution x=B
x=A for Upstream (L->R)

x=B, s: resp
x=A for Downstream (L->R)

                                     IE   bw=6Mbps
                                     resp bw=<>
dJT=2, uMinBW=4mbps, uMaxBW=5mbps, uMinBW=5mbps,
MaxBW=10mbps)

dJT=2, uMinBW=4mbps, uMaxBW=5mbps, uMinBW=5mbps,
MaxBW=10mbps)

