user             =  1*( unreserved / escaped / user-unreserved )
user-unreserved  =  "&" / "=" / "+" / "$" / "," / ";" / "?" / "/"
unreserved       =  alphanum / mark
mark             =  "-" / "_" / "." / "!" / "~" / "*" / "'"
                          / "(" / ")"

local-part  =  word *("." word)
word        =  atom / quoted-string
atom        =  1*<any CHAR except specials, SPACE and CTLs>
CHAR        =  <any ASCII character>
specials    =  "(" / ")" / "<" / ">" / "@" / "," / ";"
                     / ":" / "\" / <"> /  "." / "[" / "]"

seconds = 1 hour) applies.

