N1---SW1=====                      |  NVGRE/ |   |             |
       /        \  +-------------+    |  SRv6   |---|             |
     N2          \ |             |    |         |   +-------------+
                  \|     PE2     |----|         |
                   |             |    |         |
                   +-------------+    |         |
                                      |         |
                                      |         |
                                      +---------+

        Figure 1: ARP/ND Synchronizing and IP Aliasing without IRB

H1=10.2        |  +-----+   +------+ |         H4=20.2
H2=10.3        |  |VPWS1|---|IPVRF1| |
H3=10.4        |  +-----+   |      | |
                     |            +------+ |
                     +---------------------+


             Figure 2: ARP/ND Synchronizing for IRC Interfaces

