H = A high water mark (in units of number of unacknowledged LSAs)
L = A low water mark (in units of number of unacknowledged LSAs)
F = The factor by which the above gap is to be increased during
           congestion and decreased after coming out of congestion.
T = Minimum time that has to elapse before the existing gap
           is considered for change.
Gmin = Minimum allowed value of gap.
Gmax = Maximum allowed value of gap.

Gmax = 1 second.

F    = The factor by which the gap between sending successive LSAs to
          a neighbor is to be increased during congestion and decreased 
          after coming out of congestion (used in Recommendation 4).
          Example value is 2.

Gmax = Maximum allowed value of gap between sending successive LSAs 
          to a neighbor (used in Recommendation 4). Example value is 1
          second.

Gmin = Minimum allowed value of gap between sending successive LSAs 
          to a neighbor (used in Recommendation 4). Example value is 
          20 ms.

H    = A high water mark (in units of number of unacknowledged LSAs).
          Exceeding this mark would trigger a potential increase in the
          gap between sending successive LSAs to a neighbor.
          (used in Recommendation 4). Example value is 20.

K    = A multiplicative constant used in increasing the RxmtInterval
          value used during successive retransmissions of the same LSA
          (used in Recommendation 3). Example value is 2.

L    = A low water mark (in units of number of unacknowledged LSAs)
          Dropping below this mark would trigger a potential decrease 
          in the gap between sending successive LSAs to a neighbor.
          (used in Recommendation 4). Example value is 10.

n    = Upper limit on the number of adjacencies to be brought up
          simultaneously (used in Recommendation 5).

Rmax = The maximum allowed value of RxmtInterval (used in 
          Recommendation 3). Example value is 40 seconds.

Rmin = The minimum allowed value of RxmtInterval (used in 
          Recommendation 3). Example value is 5 seconds.



T    = Minimum time that has to elapse before the existing gap 
          between sending successive LSAs to a neighbor 
          is considered for change (used in Recommendation 4). Example 
          value is 1 second.

