mud-url   = "https://" authority  "/.well-known/mud/" mud-rev
                  "/" modelinfo ( "?" extras )
                  ; authority is from RFC3986
mud-rev   = "v1"
modelinfo = segment  ; from RFC3986
extras    = query    ; from RFC3986


Description = the Manufacturer Usage Description (MUD) Uniform
Reference = < this document >
