chatroom = chatroom-label ":" chat-token *(SP chat-token)
chatroom-label = "chatroom"
chat-token = (nicknames-token | private-msg-token | token)
nicknames-token = "nicknames"
private-msg-token = "private-messages"

a=chatroom:nickname private-messages

Nickname = [Display-Name] (nickname URI)

ext-method =/ NICKNAMEm
NICKNAMEm = %x4E.49.43.4B.4E.41.4D.45 ; NICKNAME in caps
ext-header =/ Set-Nickname
                       ; ext-header is specified in RFC XXXX
                       ; name-addr is specified in RFC 3261
Set-Nickname = "Set-Nickname" ":" name-addr
ext-header =/ Proposed-Nickname
Proposed-Nickname = "Proposed-Nickname" ":" name-addr
                             *(COMMA name-addr)

