name="coverpage.tiff"
         Content-Transfer-Encoding: base64
         Content-Description: This part is a coverpage
         Content-Disposition: attachment; filename="coverpage.tiff"

        
name="document.tiff";
name="document.tiff"
         Content-Transfer-Encoding: base64
         Content-Description: This document probably has a coverpage
         Content-Disposition: attachment; filename="document.tiff"

        
name="mruhl.vcf"
filename="mruhl.vcf"

