host==>|SLG| Subnet |SLG| Subnet |SLG+-+SLG| Subnet( Server )
           +---+   #1   +---+   #2   +---+ +---+   #3   `------'
           /____________//___________/     /________________/
           /____________//___________/     /________________/
                 :              :                  :
                 :              :                  :
             .--.           .--.               .--.
            (    )-.       (    )-.           (    )-.
          .' Access '    .' Core   '        .'  Data  '
          ( Network   )  ( Network   )      (  Center   )
           (        -'    (        -'        (        -'
            '-(     )      '-(     )          '-(     )
               '---'          '---'              '---'

         \______ ______/ \_____ _____/    \________ ________/
                V              V                   V
             Domain#1       Domain#2            Domain#3

         \_____________ _____________/    \________ ________/
                       V                           V
           Domain of Administrator#A     Domain of Administrator#B


             Figure 1: E2E-NS composed of multiple NS subnets
host ====>| SLG |      NS Subnet#1
                |@Edge|    _______________
                |     |-->/______________
                |     |      NS Subnet#2
                |     | :        :
                +-----+


                   Figure 2: NS subnet selection of SLG

