AvgPacketSize = average size of all packets placed in the 
BW = bandwidth of the outgoing interface 
         
Rate = percentage of bandwidth of outgoing interface to be 
QOC = Queue Occupancy Count 
         
QOC = QOC + 1 
AvgPacketSize = 200 bytes 
AvgPacketSize = 200 bytes 
