pstndatauri    =/ ( "pstndata:" sendndatatype )
sendndatatype  = "send-n/" digitsmin [ "-" digitsmax ]
digitsmin      = e164digitcount
digitsmax      = e164digitcount
e164digitcount = %x30-%x39 / (%x31 %x30-%x35)
                            ; 0 - 15 digits, per E.164
