n = (Length - 1)/2  (Length is the number of groups of 8 octets)

DLCI=unknown (overwritten by the receiver).

DLCI=50.

DLCI=70 (filled in by the receiver).

DLCI=50.

DLCI=50 (was Target in Solicitation Message).

DLCI=70 (was Source in Solicitation Message).

DLCI=50 (was Target in Solicitation Message).

DLCI=70 (was Source in Solicitation Message).

