rtcp-xr-attrib =  "a=rtcp-xr:"
                     [xr-format *(SP xr-format)] CRLF

xr-format = decodability-metrics

decodability-metrics = "decodability-metrics"
                               ["=" stat-flag *("," stat-flag)]
stat-flag = "TS Synchronization Loss "
                      / "Sync byte error "
                      / "Continuity count error "
                     / "Transport error"
                     / "PCR related error"
                     / "PTS error"

