m=audio 30000 RTP/AVP 0
c=IN IP4 192.0.2.1

m=audio 31000 RTP/AVP 0
c=IN IP4 192.0.2.5

m=audio 30000 RTP/AVP 0
c=IN IP4 192.0.2.2
a=curr:qos e2e none
a=des:qos mandatory e2e sendrecv
m=video 30002 RTP/AVP 31
c=IN IP4 192.0.2.2
a=curr:qos e2e none
a=des:qos mandatory e2e sendrecv

m=audio 31000 RTP/AVP 0
c=IN IP4 192.0.2.5
a=curr:qos e2e none
a=des:qos mandatory e2e sendrecv
a=conf:qos e2e recv
m=video 30002 RTP/AVP 31
c=IN IP4 192.0.2.5
a=curr:qos e2e none
a=des:qos mandatory e2e sendrecv
a=conf:qos e2e recv

m=audio 30000 RTP/AVP 0
c=IN IP4 192.0.2.2
a=curr:qos e2e send
a=des:qos mandatory e2e sendrecv
m=video 30002 RTP/AVP 31
c=IN IP4 192.0.2.2
a=curr:qos e2e send
a=des:qos mandatory e2e sendrecv

m=audio 31000 RTP/AVP 0
c=IN IP4 192.0.2.5
a=curr:qos e2e sendrecv
a=des:qos mandatory e2e sendrecv
m=video 30002 RTP/AVP 31
c=IN IP4 192.0.2.5
a=curr:qos e2e sendrecv
a=des:qos mandatory e2e sendrecv

m=audio 31000 RTP/AVP 0
c=IN IP4 192.0.2.5
m=video 30002 RTP/AVP 31
c=IN IP4 192.0.2.5
a=curr:qos e2e sendrecv
a=des:qos mandatory e2e sendrecv

m=audio 30000 RTP/AVP 0
c=IN IP4 192.0.2.2
m=video 30002 RTP/AVP 31
c=IN IP4 192.0.2.2
a=curr:qos e2e send
a=des:qos mandatory e2e sendrecv
m=audio 31000 RTP/AVP 0
c=IN IP4 192.0.2.5
m=video 30002 RTP/AVP 31
c=IN IP4 192.0.2.5

m=audio 30000 RTP/AVP 0
c=IN IP4 192.0.2.2
m=video 30002 RTP/AVP 31
c=IN IP4 192.0.2.2


