b = b_1.b_2...b_m if and only if

N = { sysUpTime, alpha, beta,
                alpha.1, beta.1, alpha.2, beta.2 }
R = { sysUpTime.0, alpha.1, beta.1,
                alpha.2, beta.2, gamma.1, delta.1 }

N = { alpha, beta, alpha.1, beta.1,
                beta.2, alpha.2, sysUpTime, beta.3, alpha.3, alpha.4 }

R = { alpha.1, beta.1, alpha.2, beta.3, alpha.3,
                sysUpTime.0, gamma.1, alpha.4, delta.1 }

