targetNamespace="urn:ietf:params:xml:ns:geopriv:held:lm"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

source="urn:ietf:params:xml:schema:geopriv:held:lm">
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
use="required"/>
type="xs:hexBinary" minOccurs="0"/>
type="lm:dhcpRemoteType" minOccurs="0"/>
type="xs:hexBinary" minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
use="optional"/>
minOccurs="1" maxOccurs="64"/>
minOccurs="0" maxOccurs="unbounded"/>
default="false"/>
default="false"/>
minOccurs="0"/>
minOccurs="0"/>
use="required"/>
default="true"/>
type="xs:nonNegativeInteger"/>
minOccurs="0" maxOccurs="unbounded"/>
