OPENID-param =  pid-param / pref-param /
               any-param
OPENID-value =  uri

SOCIALPROFILE-param =  pid-param / pref-param /
               any-param
SOCIALPROFILE-value =  uri

ALBUM-param =  pid-param / pref-param /
               any-param
ALBUM-value =  uri

DEPICTION-param =  pid-param / pref-param /
               any-param
DEPICTION-value =  uri

SOCIALCODE-param =  pid-param / pref-param /
               any-param
SOCIALCODE-value =  text

INTEREST-param =  pid-param / pref-param /
               any-param
INTEREST-value =  text

XX-param =  pid-param / pref-param /
               any-param
XX-value =  text

