version="2"
type="message type">
version = "2"
start = element msg {
     attribute version { version } ,
     ( ( attribute type { "query" }, query_elt* ) |
       ( attribute type { "reply" }, reply_elt* ) )
tag = attribute tag { xsd:token { maxLength="1024" } }

base64 = xsd:base64Binary

uri_t = xsd:anyURI { maxLength="4096" }
uri = attribute uri { uri_t }

object_handle = xsd:string {
maxLength = "255"
pattern="[\-_A-Za-z0-9/]*"
error = xsd:token { maxLength="1024" }

config_payload = (element bpki_crl { base64 }?)

client_handle = attribute client_handle { object_handle }

client_payload = (
     attribute base_uri { uri_t }?,
     element bpki_cert { base64 }?,
     element bpki_glue { base64 }?
client_clear_replay = (
     attribute clear_replay_protection { "yes" }?
report_error_reply = element report_error {
     tag?,
     attribute error_code { error },
     xsd:string { maxLength="512000" }?
type="query"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
action="set">
type="reply"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
action="set"/>
type="query"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
action="get"/>
type="reply"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
action="get">
type="query"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
action="create"
base_uri="rsync://wombat.invalid/"
client_handle="3">
hdEq3ORv7RZMJNYqv1HQ3wUE2B7fCPFv7EUwzaCds1kgRQ==
type="reply"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
action="create"
client_handle="3"/>
type="query"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
action="set"
client_handle="3">
hdEq3ORv7RZMJNYqv1HQ3wUE2B7fCPFv7EUwzaCds1kgRQ==
type="reply"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
action="set"
client_handle="3"/>
type="query"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
action="get"
client_handle="3"/>
type="reply"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
action="get"
base_uri="rsync://wombat.invalid/"
client_handle="3">
hdEq3ORv7RZMJNYqv1HQ3wUE2B7fCPFv7EUwzaCds1kgRQ==
type="query"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
action="list"/>
type="reply"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
action="list"
client_handle="3">
hdEq3ORv7RZMJNYqv1HQ3wUE2B7fCPFv7EUwzaCds1kgRQ==
type="query"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
action="destroy"
client_handle="3"/>
type="reply"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
action="destroy"
client_handle="3"/>
type="query"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
uri="rsync://wombat.invalid/Alice/blCrcCp9ltyPDNzYKPfxc.cer">
type="reply"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
uri="rsync://wombat.invalid/Alice/blCrcCp9ltyPDNzYKPfxc.cer"/>
type="query"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
uri="rsync://wombat.invalid/Alice/blCrcCp9ltyPDNzYKPfxc.cer"/>
type="reply"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
uri="rsync://wombat.invalid/Alice/blCrcCp9ltyPDNzYKPfxc.cer"/>
type="reply"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
error_code="your_hair_is_on_fire">
type="reply"
version="2"
xmlns="http://www.hactrn.net/uris/rpki/publication-spec/">
error_code="your_hair_is_on_fire"/>
