operation="get/create/modify/delete" 
transaction="stop-on-error/ 
                                 continue-on-error/ 
                                 rollback-on-error"/> 
operation="get" 
transaction="continue-on-error" 
xmlns="http://www.ietf.org/mops" 
xmlns="http://www.ietf.org/mops" 
operation="get" 
transaction="continue-on-error" 
xmlns="http://www.ietf.org/mops" 
xmlns="http://www.ietf.org/mops" 
operation="get" 
xmlns="http://www.ietf.org/mops" 
 
 
 
 
xmlns="http://www.ietf.org/mops" 
operation="modify" 
transaction="continue-on-error" 
xmlns="http://www.ietf.org/mops" 
name="Ethernet1/5"> 
xmlns="http://www.ietf.org/mops" 
operation="create" 
transaction="rollback-on-error" 
xmlns="http://www.ietf.org/mops" 
xmlns="http://www.ietf.org/mops" 
operation="modify" 
transaction="stop-on-error" 
xmlns="http://www.ietf.org/mops" 
xmlns="http://www.ietf.org/mops" 
xmlns="http://www.ietf.org/mops"/> 
    
xmlns="http://www.ietf.org/mops"/> 
xmlns="http://www.ietf.org/mops" 
xmlns="http://www.ietf.org/mops" 
targetNamespace="http://www.ietf.org/mops" 
xmlns="http://www.ietf.org/mops" 
elementFormDefault="qualified"> 
    
type="ApplicationError"/> 
use="required"/> 
use="required"/> 
use="required"/> 
use="required"/> 
use="required"/> 
use="required"/> 
targetNamespace="http://www.ietf.org/mops/capabilities" 
xmlns="http://www.ietf.org/mops/capabilities" 
elementFormDefault="qualified"> 
    
use="optional" default="no-op"/> 
use="optional" default="no-op"/> 
use="optional" default="no-op"/> 
use="optional" default="no-op"/> 
operation="get" 
transaction="continue-on-error" 
xmlns="http://www.ietf.org/mops" 
xmlns="http://www.ietf.org/mops" 
                     
targetNamespace="http://www.ietf.org/mops/absbinding.wsdl" 
xmlns="http://www.ietf.org/mops/absbinding.wsdl" 
targetNamespace="http://www.ietf.org/mops/soapbinding.wsdl" 
xmlns="http://www.ietf.org/mops/soapbinding.wsdl" 
location="http://www.ietf.org/mops/abscore.wsdl"> 
    
type="absbinding:PerformOperation"> 
transport="http://schemas.xmlsoap.org/soap/http"> 
soapAction="http://www.ietf.org/mops/PerformOperation" 
style="document"/> 
type="absbinding:AbortOperation"> 
transport="http://schemas.xmlsoap.org/soap/http"> 
soapAction="http://www.ietf.org/mops/AbortOperation" 
style="document"/> 
type="absbinding:NotificationUnconfirm"> 
transport="http://schemas.xmlsoap.org/soap/http"> 
soapAction= 
                   "http://www.ietf.org/mops/NotificationUnconfirm" 
style="document"/> 
type="absbinding:NotificationConfirm"> 
transport="http://schemas.xmlsoap.org/soap/http"> 
soapAction= 
 
 
 
 
                   "http://www.ietf.org/mops/NotificationConfirm" 
style="document"/> 
targetNamespace="http://www.ietf.org/mops/model" 
xmlns="http://www.ietf.org/mops/model" 
elementFormDefault="qualified"> 
    
use="optional" default="no-op"/> 
use="optional" default="no-op"/> 
type="xsd:string" 
use="optional" default="candidate"/> 
use="optional" default="no-op"/> 
operation="modify" 
transaction="rollback-on-error" 
xmlns="http://www.ietf.org/mops" 
xmlns="http://www.ietf.org/mops" 
