Len= Len1 + Len2 + ...+ Lenn + n.


   Code   Len   Len1            Len2
  +-----+-----+-----+----------+-----+--------------+----
  | TBD |  N  |  L1 |  class 1 | L2  |    class 2   |...
  +-----+-----+-----+----------+-----+--------------+----


