I = 1 indicates the presence of the Input Wavelength Constraints
O = 1 indicates the presence of the Output Wavelength Constraints
B = 1 indicates that a single wavelength constraints field
I = 1 or 0 indicates the presence or absence of the Input Available
O = 1 or 0 indicates the presence or absence of the Output Available
B = 1 indicates that a single Available Wavelength Set Field
I = 1 indicates if the resource blocks identified in the RB set
O = 1 indicates if the resource blocks identified in the RB set
B = 1 indicates if the resource blocks identified in the RB set
S=0, identify non-ITU code points

S=1, identify ITU application codes

T=0: Reserved

T=1: 1R Regenerator

T=2: 2R Regenerator

T=3: 3R Regenerator

C=0: Reserved

C=1: Fixed Regeneration Point

C=2: Selective Regeneration Pools

WI =|     |,  WE =|     |
              | 1 1 |       | 0 1 |
              +-----+       +-----+


                    +-----------+                      +------+
                    |           |--------------------->|      |
                    |           |--------------------->|  C   |
              /|    |           |--------------------->|  o   |
             /D+--->|           |--------------------->|  m   |
            + e+--->|           |                      |  b   |=======>
