border=none 
       suppress borders - useful with graphics etc. 

border=frame 
       outer border around table only 

border=basic 
       horizontal border between THEAD and TBODY, and between TBODY and
       TFOOT 

border=rows 
       like border=basic with an outer border, plus horizontal borders
       between rows 

border=cols 
       like border=basic with an outer border, plus vertical borders
       between columns 

border=all 
       borders around all cells, including an outer border 

border=all cols=5>. 

align=char, e.g. char=":". The default character is "." 

