VRID=1  +-----------+      +-----------+
H  =  Host computer
MR  =  Master Router
BR  =  Backup Router
                            *  =  IPv6 Address
priority=255, since it is the IPv6 address owner for the virtual
VRID=1  +-----------+      +-----------+  VRID=2
H  =  Host computer
MR  =  Master Router
BR  =  Backup Router
                            *  =  IPv6 Address
IPv6_Address=B).  In this case Rtr2 will assert itself as Master for
VRID=2 while Rtr1 will act as a backup.  This scenario demonstrates a
