iax-uri = "iax:" [userinfo "@" ]host[":" port][ "/" number[ "?"
userinfo = <as specified in RFC 3986>

host = <as specified in RFC 3986>

port = <as specified in RFC 3986>

number = *(unreserved | sub-delims | pct-encoded )

context = *(unreserved | sub-delims | pct-encoded )

unreserved = <as specified in RFC 3986>

sub-delims = <as specified in RFC 3986>

pct-encoded = <as specified in RFC 3986>

January == 1, February == 2, etc).  The timezone of the clock MUST be
