unsolicited_synch-message = [M_UNSOLIDSYNCH, session-id,
selective-flood-option = [O_SELECTIVE_FLOOD, +O_MATCH-CONDITION,
O_MATCH-CONDITION = [O_MATCH-CONDITION, Obj1, match-rule, Obj2]
Obj1 = text

match-rule = GREATER / LESS / WITHIN / CONTAIN

Obj2 = text

match-object = NEIGHBOR / SELF

action = FORWARD / DROP

subscription-objection-option = [SUBSCRIPTION, 2, 2, subobj]
objective-name = SUBSCRIPTION

objective-flags = 2

loop-count = 2

subobj = text

Unsubscribe-objection-option = [UNSUBSCRIB, 2, 2, unsubobj]

objective-name = SUBSCRIPTION

objective-flags = 2

loop-count = 2

unsubobj = text

publish-objection-option = [PUBLISH, 2, 2, pubobj]
objective-name = PUBLISH

objective-flags = 2

loop-count = 2

pubobj = text

