xmlns="http://esp.nongnu.org/2005.1"
targetNamespace="http://esp.nongnu.org/2005.1"
elementFormDefault="qualified"
attributeFormDefault="unqualified">
MAX="unbounded"/>
    <E N="implementation" MIN="0" MAX="unbounded">
     <CT mixed="true">
      <A N="level" T="Identifier" use="required"/>
      <A N="certification" T="CertificationRequirement"/>
     </CT>
    </E>
    <E N="type" T="ReferenceGroup" MIN="1" MAX="1"/>
    <E N="chapter" T="Chapter" MIN="1" MAX="unbounded"/>
    <E N="issues" T="TicketSystem" MIN="1" MAX="unbounded"/>
   </SEQ>
   <A N="class" T="PolicyClass" use="required"/>
   <A N="extension" T="ExtImpCategory" use="required"/>
   <A N="implementation" T="ExtImpCategory" use="required"/>
   <A N="lang" T="xsd:language" use="required"/>
   <A N="lastChanged" T="xsd:date" use="required"/>
   <A N="revision" T="Revision" use="required"/>
   <A N="extends" T="xsd:anyURI"/>
  </CT>
