AUTH_TYPE    =  "" | auth-scheme
auth-scheme  =  "Basic" | "Digest" | "PGP" | token


CONTENT_LENGTH  =  "" | 1*digit
CONTENT_TYPE  =  "" | media-type


GATEWAY_INTERFACE  =  "SIP-CGI" "/" major "." minor
major              =  1*digit
minor              =  1*digit


REMOTE_ADDR  =  hostnumber
hostnumber   =  IPv4address | IPv6address


REMOTE_HOST  =  hostname


REMOTE_IDENT  =  *CHAR


REMOTE_USER  =  *OCTET


REQUEST_METHOD    =  sip-method
sip-method        =  "INVITE" | "BYE" | "OPTIONS" | "CANCEL"
                             | "REGISTER" | "ACK"
                             | extension-method
extension-method  =  token


REQUEST_TOKEN  =  token


REQUEST_URI  =  SIP-URL


RESPONSE_STATUS  =  Status-Code


RESPONSE_REASON  =  Reason-Phrase


RESPONSE_TOKEN  =  token


SCRIPT_COOKIE  =  token


SERVER_NAME  =  hostname | hostnumber


SERVER_PORT  =  1*digit


SERVER_PROTOCOL    =  SIP-Version | extension-version
                              | extension-token
extension-version  =  protocol "/" 1*digit "." 1*digit
protocol           =  1*( alphanum | "+" | "-" | "." )
extension-token    =  token


SERVER_SOFTWARE  =  1*product
product          =  token [ "/" product-version ]
product-version  =  token


Status  =  SIP-Version 3*digit SP reason-phrase NL


Proxy-Request  =  "CGI-PROXY-REQUEST" SIP-URL SIP-Version


Forward-Response  =  "CGI-FORWARD-RESPONSE" Response-Name SIP-Version
Response-Name     =  response-token | "this"


Script-Cookie  =  "CGI-SET-COOKIE" token SIP-Version


CGI-Again  =  "CGI-AGAIN" "yes" | "no" SIP-Version
Request-Token  =  "CGI-Request-Token" ":" token


Remove  =  "CGI-Remove" ":" 1#field-name


