lang=<lang-code>  OPTIONAL, but MAY occur multiple times.

tzid=<identifier>  OPTIONAL, and MAY occur multiple times.  MUST
         NOT be present if the "changedsince" parameter is present.  The
         value of the "dtstamp" member in the response applies to the
         entire set of data, rather than the subset requested with the
         "tzid" query parameter, and allows the client to determine if
         it needs to refresh its full set of timezone data.

format=<media-type>  OPTIONAL, but MUST occur only once.

lang=<lang-code>  OPTIONAL, but MAY occur multiple times.

tzid=<identifier>  REQUIRED, and MUST occur only once.

truncate=<year>  OPTIONAL, and MUST occur only once.  See
         Section 5.9 for details.

tzid=<identifier>  REQUIRED, but MUST only occur once.

lang=<lang-code>  OPTIONAL, but MAY occur multiple times.

start=date or date-time:  OPTIONAL, but MUST occur only once.  If
         present, specifies the start of the period of interest.  If
         "start" is omitted, the date is assumed to be January 1st of
         the current year.
end=date or date-time:  OPTIONAL, but MUST occur only once.  If
         present, specifies the end of the period of interest.  If "end"
         is omitted, the value is the start year + 10.

name=<text>  REQUIRED, but MUST only occur once.

lang=<lang-code>  OPTIONAL, but MAY occur multiple times.

equivalent-tzid    = "EQUIVALENT-TZID" etzidpropparam ":"
                           [tzidprefix] text CRLF

etzidpropparam     = *(";" other-param)

