maxplaybackrate=48000).  They MUST NOT be specified in an SSRC-
sprop-stereo=1).  These same OPTIONAL media type parameters MAY
m=audio 54312 RTP/AVP 101
a=rtpmap:101 opus/48000/2


m=audio 54312 RTP/AVP 101
a=rtpmap:101 opus/48000/2
a=fmtp:101 maxplaybackrate=16000; sprop-maxcapturerate=16000;
maxaveragebitrate=20000; stereo=1; useinbandfec=1; usedtx=0
a=ptime:40
a=maxptime:40


m=audio 54312 RTP/AVP 101
a=rtpmap:101 opus/48000/2
a=fmtp:101 stereo=1; sprop-stereo=1


m=audio 54312 RTP/AVP 100
a=rtpmap:100 opus/48000/2

