MTU=1500  |         | MTU=1500
                 v         |
MTU=1500 |         | MTU=1500
                 v         |
               +-------------+
               |  Router 4   |
               +-------------+
                      |
                      | MTU=9000
                      |
               +-------------+
               |    Host B   |
               +-------------+

