header = {"typ":"JWT","alg":"ES256"}
body = { "aud":"https://push.example.net",
            "exp":1453341205,
            "sub":"mailto:push@example.com" }

                   Figure 2: Example JWT Header and Body

