port="53" ux="Legacy Resolver" )
port="53" esniconfig="..."
ux="Preferred Example's Choice" )

port="53" esniconfig="..." ux= )
port="53" ux="Legacy Resolver" )
port="53" esniconfig="..."
ux="Preferred Example's Choice" )

port="53" esniconfig="..." ux= )
port="443" esniconfig="..."
ux="Testing QUIC")

port=443 host=resolver.example.com
port=443 host=resolver.example.com
port=443 host=resolver.example.com
port=443 host=resolver.example.com
port=443 host=resolver.example.com
port=443 host=resolver.example.com
