socket= acceptllcp()                 socket=connectllcp() 
                     |                                     | 
                 Send SYMMM       ------------>       Receive SYMM 
                     |                                     | 
               Receive CONNECT   <-------------  Send CONNECT, DSAP=1 
                  Check SN                       SN = "com.ietf.tls" 
                     |                                     | 
                  Send CC        -------------->       Receive CC 
socket= connectllcp()                socket= acceptllcp() 
                     |                                     | 
SN = "com.ietf.tls"                        Check SN 
                     |                           Allocate Ephemeral SAP 
                     |                                     | 
                 Receive CC       <--------------       Send CC 
                     |                                     | 
                     |                                     | 
                   Done                                   Done 
    
                         Figure 7. Connection Choreography 
 
 
socket= acceptllcp(TLS-SAP)            socket=connectllcp(TLS-SAP) 
                  |                                     | 
                  |                            DSAP=well-known value 
                  |                          Allocate Ephemeral SSAP 
                  |                                     | 
                  |                                    Done 
                  |                                     | 
                  |                                 sendllcp() 
                  |                                     | 
              Send SYMM    ------------------>     Receive SYMM 
                  |                                     | 
             Receive UI    <------------------       Send UI 
             Check DSAP                                 | 
                  |                                     | 
                Done                                    
    
                         Figure 15. Connection Choreography 
    
socket= connectllcp(TLS-SAP)        socket= acceptllcp(TLS-SAP) 
                     |                                     | 
DSAP=well-known value                           | 
NFCID3i= 5C A9 BE E1 C0 35 A0 BF 16 0F 
BSi= 00 
BRi= 00 
PPi= 02, 64 bytes of Transport Data, Gt bytes available 
NFCID3t= AA 99 88 77 66 55 44 33 22 11 
BSt= 00 
BRt= 00 
TO= 09, WT= 6363 ms 
PPt= 03, 64 bytes of Transport Data, NAD available, Gt bytes 
NFCID3i= 5C A9 BE E1 C0 35 A0 BF 16 0F 
BSi= 00 
BRi= 00 
PPi= 02, 64 bytes of Transport Data, Gt bytes available 
NFCID3t= AA 99 88 77 66 55 44 33 22 11 
BSt= 00 
BRt= 00 
TO= 09, WT= 6363 ms 
PPt= 03, 64 bytes of Transport Data, NAD available, Gt bytes 
