CS = Content Server
BR = Border Router
I1 = P-CDN and S-CDN Multicast Interconnection (MBGP or BGMP)
I2 = S-CDN and EU Multicast Connection

      Figure 1 - Content Distribution via End to End Native Multicast

AR = AMT Relay
AG = AMT Gateway
I1 = AMT Interconnection between P-CDN and S-CDN
I2 = S-CDN and EU Multicast Connection

          Figure 3 - AMT Interconnection between P-CDN and S-CDN

CS = Content Server
BR = Border Router
AR = AMT Relay
I1 = P-CDN and S-CDN Multicast Interconnection (MBGP or BGMP)
I2 = AMT Connection between S-CDN and EU

               Figure 4 - AMT Tunnel Connecting S-CDN and EU

CS = Content Source
AR = AMT Relay
I2 = AMT Tunnel Connecting EU to P-CDN Relay through Non-Multicast
      Enabled S-CDN.

          Figure 5 - AMT Tunnel Connecting P-CDN AMT Relay and EU

