cookie=h(S,x) to x, but otherwise does nothing with the request. When
c=h(S,x) and if so, continues processing. (If Bob has recently
SPI=ci, the NAPT would not be able to differentiate.  But since SPIs
type=UDP (17). Then there is a UDP header, with destination
port=4500. After the UDP header is either an ESP packet or an IKE
