Error-value=TBD:  LSP Identifiers TLV missing

Error-value=TBD:  Percentage is not hundred.
                                    for explicit mode
Error-value=TBD:  Specified LSP-ID is not existing.
                                    for explicit mode
Error-value=TBD:  Specified LSP-ID is not operational.
                                    for explicit mode



