ether-addr  = macAddress
hostname    = rn / en	; depending on class, see below

ethers-entry = ether-addr SPACE hostname

hostname   = rn / en      ; depending on class, see below
params     = bootParameter *(SPACE bootParameter)

bootparams-entry = hostname SPACE params

