extension-field = [ call-duration CRLF ]
                        [ transmitted-pages CRLF ]
                        [ media-features CRLF ]

call-duration     = "Call-Duration" ":" elapsed-time
transmitted-pages = "Transmitted-Pages" ":" xmit-pages
media-features    = "Media-Features" ":" media-feature-tags

elapsed-time = hour ":" minute ":" second
      
hour    = 2DIGIT
minute  = 2DIGIT
second  = 2DIGIT
      
xmit-pages = 1*DIGIT
media-feature-tags = *text   <per [MEDIA-FEATURES]>
      
