deprecation-header = "Deprecation:" SP "version"=vval, "date"=dval,
                        *( extension )
extension = property-name "=" property-value
property-name = DQUOTE token DQUOTE
token = <token, defined as in [RFC7230], Section 3.2.6>
vval = property-value
property-value = DQUOTE *( pchar ) DQUOTE
pchar = %x23 / %x2B-3A / %x41-5A / %x61-7A / %x7C
         ; US-ASCII characters
dval = DQUOTE HTTP-date DQUOTE

type="text/html"

type="text/html"

