SERIAL_BITS = 32.

December == "12". The dash must be included.
key=value in the data part of a Login or Text Request or Response.
Key=value pairs may span PDU boundaries. An initiator or target that
ErrorRecoveryLevel=1 when transport connection failure is not a
ErrorRecoveryLevel=2 when the connection failure is also of high
ErrorRecoveryLevel=2 whenever there is a relatively high likelihood
ErrorRecoveryLevel=0. The initiator MUST ignore the A bit set to 1
key=value pair can start in one PDU and continue on the next. In
key=value pairs of its own as part of a sequence and not only in
AuthMethod = <list-of-values>

KRB_AP_REQ=<KRB_AP_REQ>

KRB_AP_REP=<KRB_AP_REP>

SPKM_REQ=<SPKM-REQ>

SPKM_ERROR=<SPKM-ERROR>

SPKM_REP_TI=<SPKM-REP-TI>

SPKM_REP_IT=<SPKM-REP-IT>

SRP_U=<U> TargetAuth=Yes   /* or TargetAuth=No */

SRP_GROUP=<G1,G2...> SRP_s=<s>

SRP_A=<A> SRP_GROUP=<G>

SRP_B=<B>

SRP_M=<M>

SRP_HM=<H(A | M | K)>

CHAP_A=<A1,A2...>

CHAP_A=<A> CHAP_I=<I> CHAP_C=<C>



CHAP_N=<N> CHAP_R=<R>

CHAP_N=<N> CHAP_R=<R> CHAP_I=<I> CHAP_C=<C>

CHAP_N=<N> CHAP_R=<R>

HeaderDigest = <list-of-values>
DataDigest = <list-of-values>

MaxConnections=<numerical-value-from-1-to-65535>

TargetName=<iSCSI-name-value>

TargetName=iqn.1993-11.com.disk-vendor:diskarrays.sn.45678
TargetName=eui.020000023B040506

InitiatorName=<iSCSI-name-value>

InitiatorName=iqn.1992-04.com.os-vendor.plan9:cdrom.12345
InitiatorName=iqn.2001-02.com.ssp.users:customer235.host90

TargetAlias=<iSCSI-local-name-value>

TargetAlias=Bob-s Disk
TargetAlias=Database Server 1 Log Disk
TargetAlias=Web Server 3 Disk 20

InitiatorAlias=<iSCSI-local-name-value>

InitiatorAlias=Web Server 4
InitiatorAlias=spyalley.nsa.gov
InitiatorAlias=Exchange Server

TargetAddress=domainname[:port][,portal-group-tag]

TargetAddress=10.0.0.1:5003,1
TargetAddress=[1080:0:0:0:8:800:200C:417A],65
TargetAddress=[1080::8:800:200C:417A]:5003,1
TargetAddress=computingcenter.example.com,23


TargetPortalGroupTag=<16-bit-binary-value>

TargetPortalGroupTag=1

InitialR2T=<boolean-value>

InitialR2T=No. Only the first outgoing data burst (immediate data



ImmediateData=<boolean-value>

MaxRecvDataSegmentLength=<numerical-value-512-to-(2**24-1)>

MaxBurstLength=<numerical-value-512-to-(2**24-1)>

FirstBurstLength=<numerical-value-512-to-(2**24-1)>

DefaultTime2Wait=<numerical-value-0-to-3600>

DefaultTime2Retain=<numerical-value-0-to-3600>

MaxOutstandingR2T=<numerical-value-from-1-to-65535>
DataPDUInOrder=<boolean-value>

DataSequenceInOrder=<boolean-value>

ErrorRecoveryLevel=<numerical-value-0-to-2>

SessionType= <Discovery|Normal>

OFMarker=<boolean-value>
IFMarker=<boolean-value>

OFMarkInt=<numeric-range-from-1-to-65535>
IFMarkInt=<numeric-range-from-1-to-65535>

OFMarkInt=<numeric-value-from-1-to-65535>|Reject
IFMarkInt=<numeric-value-from-1-to-65535>|Reject

InitiatorName=iqn.1999-07.com.os:hostid.77
TargetName=iqn.1999-07.com.example:diskarray.sn.88
AuthMethod=KRB5,SRP,None

AuthMethod=KRB5


KRB_AP_REQ=<krb_ap_req>

KRB_AP_REP=<krb_ap_rep>

MaxBurstLength=8192
InitiatorName=iqn.1999-07.com.os:hostid.77
TargetName=iqn.1999-07.com.example:diskarray.sn.88
AuthMethod=SRP,KRB5,None

AuthMethod=KRB5

KRB_AP_REQ=krb_ap_req

InitiatorName=iqn.1999-07.com.os:hostid.77
TargetName=iqn.1999-07.com.example:diskarray.sn.88
AuthMethod=SPKM1,KRB5,None

AuthMethod=SPKM1

SPKM_REQ=<spkm-req>

SPKM_REP_TI=<spkm-rep-ti>

SPKM_REP_IT=<spkm-rep-it>

InitiatorName=iqn.1999-07.com.os:hostid.77
TargetName=iqn.1999-07.com.example:diskarray.sn.88
AuthMethod=SPKM1,SPKM2

AuthMethod=SPKM2

SPKM_REQ=<spkm-req>

InitiatorName=iqn.1999-07.com.os:hostid.77
TargetName=iqn.1999-07.com.example:diskarray.sn.88
AuthMethod=KRB5,SRP,None

AuthMethod=SRP

SRP_U=<user>
TargetAuth=Yes

SRP_N=<N>
SRP_g=<g>
SRP_s=<s>

SRP_A=<A>

SRP_B=<B>

SRP_M=<M>

SRP_HM=<H(A | M | K)>

InitiatorName=iqn.1999-07.com.os:hostid.77
TargetName=iqn.1999-07.com.example:diskarray.sn.88
AuthMethod=KRB5,SRP,None

AuthMethod=SRP

SRP_U=<user>
TargetAuth=No

SRP_N=<N>
SRP_g=<g>
SRP_s=<s>

SRP_A=<A>

SRP_B=<B>

SRP_M=<M>

InitiatorName=iqn.1999-07.com.os:hostid.77
TargetName=iqn.1999-07.com.example:diskarray.sn.88
AuthMethod=KRB5,CHAP,None

AuthMethod=CHAP

CHAP_A=<A1,A2>

CHAP_A=<A1>
CHAP_I=<I>
CHAP_C=<C>

CHAP_N=<N>
CHAP_R=<R>
CHAP_I=<I>
CHAP_C=<C>

CHAP_N=<N>
CHAP_R=<R>

InitiatorName=iqn.1999-07.com.os:hostid.77
TargetName=iqn.1999-07.com.example:diskarray.sn.88
AuthMethod=KRB5,CHAP,None

AuthMethod=CHAP

CHAP_A=<A1,A2>

CHAP_A=<A1>
CHAP_I=<I>
CHAP_C=<C>

CHAP_N=<N>
CHAP_R=<R>

InitiatorName=iqn.1999-07.com.os:hostid.77
TargetName=iqn.1999-07.com.example:diskarray.sn.88
InitiatorName=iqn.1999-07.com.os:hostid.77
TargetName=iqn.1999-07.com.example:diskarray.sn.88
AuthMethod=KRB5,SRP,None

AuthMethod=None

TargetName=<target-name-goes-here>

TargetAddress=<hostname-or-ipaddress>[:<tcp-port>],<portal-
       group-tag>

SendTargets=All

TargetName=iqn.1993-11.com.example:diskarray.sn.8675309

TargetName=iqn.1993-11.com.example:diskarray.sn.8675309
TargetAddress=10.1.0.45:3000,1
TargetAddress=10.1.1.45:3000,2
TargetName=iqn.1993-11.com.example:diskarray.sn.1234567
TargetAddress=10.1.0.45:3000,1
TargetAddress=10.1.1.45:3000,2

TargetName=iqn.1993-11.com.example:diskarray.sn.8675309


TargetAddress=10.1.0.45:3000,1
TargetAddress=10.1.1.46:3000,1
TargetAddress=10.1.0.47:3000,2
TargetAddress=10.1.1.48:3000,2
TargetAddress=10.1.1.49:3000,3

send-data-SNACK = TRUE;
LastRequiredDataSN = CurrentPDU.DataSN;
             } else {
               if (TCB.SoFarInOrder = TRUE) {
                   if (current DataSN is expected) {
                        Increment TCB.ExpectedDataSN.
                   } else {














send-data-SNACK = TRUE;
send-data-SNACK = TRUE;
LastRequiredDataSN = CurrentPDU.DataSN - 1;
send-status-SNACK = TRUE;
send-recovery-R2T = TRUE;
send-recovery-R2T = TRUE;
send-recovery-R2T = TRUE;
snack-failure = FALSE;
snack-failure = TRUE;
snack-failure = TRUE;

send-status-SNACK = FALSE;
send-status-SNACK = TRUE;
send-status-SNACK = TRUE;
send-status-SNACK = FALSE;
send-status-SNACK = Evaluate-a-StatSN(Connection,
                                           CurrentPDU);
AffectedConnection = Connection;
NewConnection = Pick-A-Logged-In-Connection(Session);
NewConnection = Connection;
NewConnection = Pick-A-Logged-In-Connection(Session);
NewConnection =
                     CreateTransportConnection(Session.OtherEndInfo);
DifferentConnection =
                  Pick-A-Logged-In-Connection(Session);
                Build-And-Send-Async(DifferentConnection,
                      DroppedConnection, DefaultTime2Wait,
                        DefaultTime2Retain);
Y   = Yes (cleared/discarded/reset on the event specified in the
       row).  Unless otherwise noted, the clearing action is only
       applicable for the issuing initiator port.
N   = No  (not affected on the event specified in the row, i.e.,
       stays at previous value).
NA  = Not Applicable or Not Defined.

                         +-----+-----+-----+-----+-----+
                         |IT(1)|IC(2)|CT(5)|ST(6)|PP(7)|
