ct=50 stands for the Content-Format "application/json", ct=16 stands
ct=TBD2 stands for Content-Format "application/voucher-cms+cbor,
ct=TBD3 stands for Content-Format "application/voucher-cose+cbor;
cose-type="cose-sign1.  The latter two are defined in this document.

Ver = 1
T = 0 (CON)
Code = 0x01 (0.01 is GET)
Payload = [Empty]

Ver=1
T=2 (ACK)
Code = 0x45 (2.05 Content)
Payload =
Payload =
Payload =
Payload =
