SAFI=128) in VPN-specific routing tables.  For topological,
SAF=128.  The backbone IP AF(j) could be native IPv6 or native IPv4.
AFBR3=(AS2 transit core)=AFBR4--
                                   |                         | island
                                   +*************************+
                                            Softwire 2


AFBR3=(AS2 transit core)=AFBR4--
                                   |                         |island
                                   +*************************+
                                            Softwire 3


AFASBR2=(AS2 transit core)=AFBR2--
                                                                  island


