t=20050704142754  - corresponds to RFC2822 date
                   "Mon, 4 Jul 2005 14:27:54 -0500"
t=20050503 - corresponds to May 3, 2005

charset="us-ascii"
charset="us-ascii"
charset="us-ascii"
charset="us-ascii"
c=simple,mimeform; a=sha1; d="0ZOMSM79tU+ujUVmjaOkRBmad8k="

d="0ZOMSM79tU+ujUVmjaOkRBmad8k="

charset="us-ascii"
c=simple,mimeform; a=sha1; d="0ZOMSM79tU+ujUVmjaOkRBmad8k="

h=content-type,message-id,mime-version;
a=sha1; d="0ZOMSM79tU+ujUVmjaOkRBmad8k="
charset="US-ASCII"
u="<218C460.u314@example.com> <218C460.u315@example.com>";
a=sha1; d="0ZOMSM79tU+ujUVmjaOkRBmad8k="
protocol="application/pkcs7-signature"; micalg=sha1
h=content-type,mime-version,message-id,date;
c=nofws; d="rNqZDKbZ4eFzs/6Z67ivfIA2JPs="

a=sha1; d="MSU3X80gRiNX1r2sjRzV4thQ5cs="

d="HlT99tyN/wczesmLuavpsr5qXbc="

t=2005070412341200).

h=Content-Type,Last-Modified,ETag; c=bare;
c=bare; d="MpUuKLUmoKUapc4q2kMyw3XzEUo="
t=2005070510302601) being used in email header to provide hash of
u="<218C460.u314@example.com> <218C460.u315@example.com>
          <fl0332.k1@example.org>";
h="content-type,mime-version,content-id,content-digest,
          content-originator"; d="MJkDZynIX7LCZ8LBO/KB2UGQmU0="
u="<218C460.u314@example.com> <218C460.u315@example.com>";
h=content-type,mime-version,content-id,content-digest;
d="COb/tgPpFD4JNS2vYelZAkk4aHU="
a=sha1; d="MSU3X80gRiNX1r2sjRzV4thQ5cs="

d="HlT99tyN/wczesmLuavpsr5qXbc="

Content-Digest = "Content-Digest" ":" FWS version parameters

version = "v=" version-number CFWS ";"

version-number = "1.0" / unknown-version

unknown-version = number-major "." number-minor

number-major = 1*(digit)

number-minor = 1*(digit)

parameters = *(CFWS ";" FWS parameter) CFWS data-parameter
        *(CFWS ";" FWS parameter)

data-parameter = ";" FWS "d=" value

parameter = algorithm / headerfieldlist / canonicalization /
        size / timestamp / hostinfo / undefined-parameter
undefined-parameter = undefined-name "=" undefined-value

undefined-name = token

undefined-value = value

algorithm  = "a=" algorithm-name

algorithm-name =  "md5" / "sha1" / "sha224" / "sha256" /
        "sha384" / "sha512" / undefined-value
canonicalization = "c=" [header-canonicalization ","]
        body-canonicalization
header-canonicalization = "bare" / "simple" /
        "nofws" / undefined-value
body-canonicalization = "bare" / "text" /
        "mimeform" / "nofws" / "none" / undefined-value

size       = "l=" 1*(digit)

timestamp  = "t=" timestamp-value

timestamp-value = 1*(digit) ["." 1*(digit)]

hostinfo   = "i=" value

headerfieldlist = "h=" headerfield *("," headerfield)

headerfield = field-name
field-name    =       1*ftext [ "*" ]

ftext         =       %d33-57 /      ; Any character except
                            %d59-126       ; controls, SP, and ":"

digit         =       %d48-57        ; Numeric Digit

value = token / quoted-string

token = 1*<any ASCII CHAR except SPACE, CTLs, or tspecials>

tspecials =  "(" / ")" / "<" / ">" / "@" / "," / ";" / ":" /
                   "\" / <"> /"/" / "[" / "]" / "?" / "="
EDigest = "EDigest" ":" FWS version edigest-parameters

edigest-parameters = *(CFWS ";" FWS ed-parameter) CFWS data-parameter
        *(CFWS ";" FWS ed-parameter)

ed-parameter = algorithm / headerfieldlist / canonicalization /
        size / timestamp / hostinfo / urlinfo / undefined-parameter
urlinfo = "u=" quoted-url / content-id
quoted-url = %d34 urldata $d34
urldata = oneurl 0*(FWS oneurl)

oneurl  = "<" value ">"
