xmlns="urn:ietf:params:xml:ns:contact-1.0" type="int">
elementFormDefault="qualified">

maxOccurs="2"/>
elementFormDefault="qualified">

maxOccurs="unbounded"/>
minOccurs="0"/>
           <element name="contact" type="rwsDomain:contactType"
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
elementFormDefault="qualified">

maxOccurs="unbounded"/>
elementFormDefault="qualified">

maxOccurs="unbounded"/>
