type            = "t=" type-value
                    ; Complies with "attr-val" syntax.
type-value      = "otp" / value
                    ; Type of second factor.
                    ; Should be registered with IANA.
second-factor   = "f=" second-factor-value
                    ; Complies with "attr-val" syntax.
second-factor-value = 6DIGIT / value

server-error-value-ext =
              "second-factor-failed" /
              "second-factor-value-missing"

value = <as defined in RFC 5802>


i=4096
t=otp,f=776804,
p=v0X8v3Bz2T0CJGbJQyF0X+HI4Ts=
