Conveyer1=OK, Conveyer2=OK # %%

SIG=2.

certInitialRepeat = number of times each Certificate Block should be
certResendDelay  = maximum time delay in seconds to delay before next
certResendCount  = maximum number of sent messages to delay before
sigNumberResends = number of times a Signature Block is resent.

sigResendDelay   = maximum time delay in seconds from original
sigResendCount   = maximum number of sent messages to delay before
