Challenge = Ltrunc(SHA1(I|J),K)
Challenge-response = Ltrunc(SHA1(I|Rand),K)
Challenge-proof = Ltrunc(SHA1(I|Challenge-response),K)
Type = 1
HIT = Initiator's HIT
Type = 2
HIT = Responder's HIT
Type = 3
HIT = Initiator's HIT
Type = 4
HIT = Responder's HIT
Type = 5
HIT = Sender's HIT
Type = 6
HIT = Sender's HIT
Type = 10
HIT = Announcer's HIT
KEYMAT = K1 | K2 | K3 | ...
         where

K1 = HMAC-SHA1(Kij | sort(Resp-SPI | Init-SPI) | 1)

K2 = HMAC-SHA1(Kij | K1 | 2)
K3 = HMAC-SHA1(Kij | K2 | 3)
