K = Key, S = Seed, LEN = output length, represented as binary
T1 = HMAC-SHA1(K, S | LEN | 0x01)
T2 = HMAC-SHA1 (K, T1 | S | LEN | 0x02)
T3 = HMAC-SHA1 (K, T2 | S | LEN | 0x03)
T4 = HMAC-SHA1 (K, T3 | S | LEN | 0x04)
CSK = PRF+(TK, "Session Key Generating Function", OutputLength)

EAP-Type=PP-EAP
EAP-Type=PP-EAP
EAP-Type=PP-EAP
EAP-Type=PP-EAP
EAP-Type=PP-EAP
