tls-cipher-clause  =  CFWS "tls" FWS tls-cipher

tls-cipher         =  tls-cipher-suite-name / tls-cipher-suite-hex

tls-cipher-name    =  ALPHA *(ALPHA / DIGIT / "_")
tls-cipher-hex     =  "0x" 4HEXDIG

version=1.2 won't be saved if the currently negotiated tls-version
