IW = MaxIW; # assume this is in bytes, and indicates an integer
CWND = IW;
IWnotchecked = 1; # true

IWnotchecked = 0; # never check again
IWnotchecked = 0; # never do this entire "if" again
IWnotchecked = 0; # you're beyond the IW so stop checking
IW = IW * MulDecr;
IW = IW + AddIncr;
