K = string-to-key(OTP)

K = string-to-key(OTP)

K = random-to-key(R)

K1 = random-to-key(shared secret)
K2 = string-to-key(OTP)

K = random-to-key(R1 ^ R2)

K1 = string-to-key(Password)
K2 = string-to-key(OTP)

K = random-to-key(shared secret)
