rtcp-xr-attrib =  "a=rtcp-xr:"
                                 [xr-format *(SP xr-format)] CRLF
xr-format = RTP-flows-init-syn-delay
                         / RTP-flows-syn-offset
RTP-flows-init-syn-delay = "RTP-flows-init-syn-delay"
                                          ["=" max-size]
RTP-flow-syn-offset = "RTP-flows-syn-offset"
                                     ["=" max-size]
max-size = 1*DIGIT ; maximum block size in octets

