grant_type=refresh_token&refresh_token=tGzv3JOkF0XG5Qx2TlKWIA
grant_type=authorization_code&code=SplxlOBeZQQYbYS6WxSbIA
scope       = scope-token *( SP scope-token )
scope-token = 1*( %x21 / %x23-5B / %x5D-7E )

code-verifier = 43*128unreserved
unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"
ALPHA = %x41-5A / %x61-7A
DIGIT = %x30-39

code_challenge = BASE64URL-ENCODE(SHA256(ASCII(code_verifier)))

code_challenge = code_verifier

code-challenge = 43*128unreserved
unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"
ALPHA = %x41-5A / %x61-7A
DIGIT = %x30-39

grant_type=authorization_code&code=SplxlOBeZQQYbYS6WxSbIA
grant_type=client_credentials

grant_type=refresh_token&refresh_token=tGzv3JOkF0XG5Qx2TlKWIA

grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code
b64token    = 1*( ALPHA / DIGIT /
                    "-" / "." / "_" / "~" / "+" / "/" ) *"="
credentials = "Bearer" 1*SP b64token

access_token=mF_9.B5f-4.1JqM

scope="openid profile email"
scope="urn:example:channel=HBO&urn:example:rating=G,PG-13"

error="invalid_token",
error_description="The access token expired"

type-name  = 1*name-char
name-char  = "-" / "." / "_" / DIGIT / ALPHA

param-name  = 1*name-char
name-char   = "-" / "." / "_" / DIGIT / ALPHA

response-type  = response-name *( SP response-name )
response-name  = 1*response-char
response-char  = "_" / DIGIT / ALPHA

error      = 1*error-char
error-char = %x20-21 / %x23-5B / %x5D-7E

VSCHAR     = %x20-7E
NQCHAR     = %x21 / %x23-5B / %x5D-7E
NQSCHAR    = %x20-21 / %x23-5B / %x5D-7E
UNICODECHARNOCRLF = %x09 /%x20-7E / %x80-D7FF /
                       %xE000-FFFD / %x10000-10FFFF

client-id     = *VSCHAR

client-secret = *VSCHAR

response-type = response-name *( SP response-name )
response-name = 1*response-char
response-char = "_" / DIGIT / ALPHA

scope       = scope-token *( SP scope-token )
scope-token = 1*NQCHAR

state      = 1*VSCHAR

redirect-uri      = URI-reference

error             = 1*NQSCHAR

error-description = 1*NQSCHAR

error-uri         = URI-reference

grant-type = grant-name / URI-reference
grant-name = 1*name-char
name-char  = "-" / "." / "_" / DIGIT / ALPHA
code       = 1*VSCHAR

access-token = 1*VSCHAR

token-type = type-name / URI-reference
type-name  = 1*name-char
name-char  = "-" / "." / "_" / DIGIT / ALPHA

expires-in = 1*DIGIT

refresh-token = 1*VSCHAR

param-name = 1*name-char
name-char  = "-" / "." / "_" / DIGIT / ALPHA

code-verifier = 43*128unreserved
unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"
ALPHA = %x41-5A / %x61-7A
DIGIT = %x30-39
code-challenge = 43*128unreserved
unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"
ALPHA = %x41-5A / %x61-7A
DIGIT = %x30-39

