Key             =  [( "Key" | "y" ) 
                        (":" key-format)
                        ("=" key-param)]
key-param       =  1*( alphanum)
key-format      =  ( "Header" | "Key32" | "Key8" )
     
X = Version bit: Should always be set to zero (0)      
Y = Shim Format: 0 = Key32, 1 = Key8.
      
X = Version bit: Should always be set to zero (0)      
Y = Shim Format: 0 = Key32, 1 = Key8.
      
