rt=abuse,fraud,virus,other; re=isprelations@example.com;"

rt=abuse,fraud,virus,other; re=isprelations@example.com;"

re=postmaster@example.net;"

gu=http://postmaster.example.net/fbl/"

gu=http://postmaster.example.net/fbl/"; rf=ARF;
r=abuse+arf@example.net; rt=abuse,fraud,other;
re=postmaster@example.net;"

gu=http://postmaster.example.net/auth/"


