U = (.b0 b1 b2 ... b31)    [note the binary point]
k = 0;
t = k + (xdec[i]*ydec[j]) + w[i + j];
k = t/EXP2POW32;
ret = w[2];
buf = &next->out[4*i];
U = OWPunif_rand64(next);

U = MASK32(U);  /* Keep only the fractional part. */
J = OWPulong2num64(j);

V = OWPunif_rand64(next);
tmp = OWPunif_rand64(next);
V = tmp;
lambda=1).  An implementation SHOULD produce delay values in seconds
SID = 0x2872979303ab47eeac028dab3829dab2
SID = 0x0102030405060708090a0b0c0d0e0f00
SID = 0xdeadbeefdeadbeefdeadbeefdeadbeef
SID = 0xfeed0feed1feed2feed3feed4feed5ab
