v=0
o=- 53655765 2353687637 IN IP4 as.com
s=-
c=IN IP4 as.com
t=0 0
m=application 5757 TCP/ESCS
a=setup:active
a=connection:new


v=0
o=- 53655765 2353687638 IN IP4 ms.org
s=MediaCtrl
c=IN IP4 ms.org
t=0 0
m=application 7575 TCP/ESCS *
a=connection:new
a=setup:passive


id2="1536067209~913cd14c">
connection-id="1536067209~913cd14c">
value="http://www.ms.org/prompts/connected.gsm"/>
reason="Dialog started" dialogid="05ded7b"/>


value="http://www.ms.org/recording-05ded7b.wav"/>
connection-id="1536067209~913cd14c">
value="http://www.ms.org/recording-05ded7b.wav"/>
reason="Dialog started" dialogid="6faf4e0"/>


