iphoneurl    = "iphone:" hostport [ "/" [ formats | media *[ "," media ] ]

formats      = format | formats "," format
format       = digits | encodingname [ ":" clockrate
                                            [ ":" encodingparameter ] ]

media        = medium *[ "&" attribute ] *[ "&" medium *[ "&" attribute ] ]

medium       = rtpmedium
rtpmedium    = "m=rtp:" port ":" payloadtype
payloadtype  = format | dynamicpayloadtype ":" format
dynamicpayloadtype  = digits

encodingname = 1*unreserved
clockrate    = digits
encodingparameter = digits

attribute    = dtmfattr

dtmfattr     = "a=dtmf:" dtmfdigits
dtmfdigits   = 1*[ digit | "*" | "#" | "u" | "p" ]

m=rtp:9000:99:DVI4:8000&m=rtp:9001:100:JPEG:8000

