metric-type = A value from the IGP metric type registry

A------B====C====F====D
                  |              |
                   ------E-------

                       Figure 7: Parallel interfaces

Granularity = 20G

