feature = element f:feature {
       atomCommonAttributes,
       attribute ref    { atomUri },
       attribute href   { atomUri }?,
       attribute label  { text }?,
       (anyElement)*
anyElement = element * - f:feature {
       (attribute * { text }
         | text
         | anyElement)*
xmlns="http://www.w3.org/2007/app"
ref="http://purl.org/atompub/features/1.0/supportsDraft" />
