M=1 if there are more segments or sets M=0 otherwise.  For each non-
NEXTHDR="No Next Header" [RFC2460] in the SEAL header), then splits
S_MRU=0, but this may cause tunnel MTU underruns in some environments
Offset=0 in the IP header) of a fragmented SEAL packet, it sends an
I=1 in the SEAL header to a SEAL-layer pending-reassembly queue
MF=1 and Offset=0 in the outer IP header) of a SEAL protocol
