l_r=max{l_{1r},l_{2r}} the smoothed estimation of number of bytes
alpha_r = --------------------
                                 |collected_paths|   
                                    
alpha_r = - -----------------
                                   |max_w_paths|  
 




