type-name = restricted-name
subtype-name = restricted-name

restricted-name = 1*127restricted-name-chars
restricted-name-chars = ALPHA / DIGIT / "!" /
                               "#" / "$" / "&" / "." /
                               "+" / "-" / "^" / "_"

parameter-name = restricted-name

