targetNamespace="urn:ietf:params:xml:ns:conference-policy"
elementFormDefault="qualified">
xmlns="urn:ietf:params:xml:ns:conference-settings"
schemaLocation="http://www.w3.org/2001/xml.xsd"/>

targetNamespace="urn:ietf:params:xml:ns:conference-pcl"
elementFormDefault="qualified">
content="text/html;charset=iso-8859-1"/>
