a=recvonly attribute.  Media descriptions associated to other media
a=group:LS 1 6
a=group:LS 2 7
a=group:LS 3 8

m=video 10002 RTP/AVP 96 97
a=sendonly
a=rtpmap:96 H264
a=rtpmap:97 H265
a=content: main
a=mid:1
a=clue-attributes:
a=clue-capture{1:camera-left,2:full-scene,
     3:composed-scene,4:speaker}

m=video 10003 RTP/AVP 96 97
a=sendonly
a=rtpmap:96 H264
a=rtpmap:97 H265
a=content: main
a=mid:2
a=clue-attributes:
a=clue-capture{1:camera-center,2:full-scene,
     3:composed-scene,4:speaker}

m=video 10004 RTP/AVP 96 97
a=sendonly
a=rtpmap:96 H264
a=rtpmap:97 H265
a=content: main
a=mid:3
a=clue-attributes:
a=clue-capture{1:camera-right,2:full-scene,
     3:composed-scene,4:speaker}

m=video 10006 RTP/AVP 96
a=sendonly
a=rtpmap:96 H264





a=content: slides
a=mid:5
a=clue-attributes

m=audio 10000 RTP/AVP 96
a=sendonly
a=rtpmap:96 PCMU
a=mid:6
a=clue-attributes:
a=clue-capture{1:mic-left,2:speaker}

m=audio 10001 RTP/AVP 96
a=sendonly
a=rtpmap:96 PCMU
a=mid:7
a=clue-attributes:
a=clue-capture{1:mic-center,2:speaker}

m=audio 10002 RTP/AVP 96
a=sendonly
a=rtpmap:96 PCMU
a=mid:8
a=clue-attributes:
a=clue-capture{1:mic-right,2:speaker}





























a=group:LS 1 6

m=video 10002 RTP/AVP 96
a=recvonly
a=rtpmap:96 H264
a=content: main
a=mid:1
a=clue-attributes:
a=clue-capture{1:full-scene}

m=video 10006 RTP/AVP 96
a=inactive
a=rtpmap:96 H264
a=content: slides
a=mid:5
a=clue-attributes

m=audio 10000 RTP/AVP 96
a=recvonly
a=rtpmap:96 PCMU
a=mid:6
a=clue-attributes:
a=clue-capture{1:speaker}

m=video 10002 RTP/AVP 96 97
a=sendonly
a=rtpmap:96 H264
a=rtpmap:97 H265
a=content: main
a=mid:1





a=clue-attributes:
a=clue-capture{1:camera-left,2:full-scene,
     3:composed-scene,4:speaker}

m=video 10003 RTP/AVP 96 97
a=sendonly
a=rtpmap:96 H264
a=rtpmap:97 H265
a=content: main
a=mid:2
a=clue-attributes:
a=clue-capture{1:camera-center,2:full-scene,
     3:composed-scene,4:speaker}

m=video 10004 RTP/AVP 96 97
a=sendonly
a=rtpmap:96 H264
a=rtpmap:97 H265
a=content: main
a=mid:3
a=clue-attributes:
a=clue-capture{1:camera-right,2:full-scene,
     3:composed-scene,4:speaker}

m=video 10006 RTP/AVP 96
a=sendonly
a=rtpmap:96 H264
a=content: slides
a=mid:5
a=clue-attributes

m=audio 10000 RTP/AVP 96
a=sendonly
a=rtpmap:96 PCMU
a=mid:6
a=clue-attributes:
a=clue-capture{1:mic-left,2:speaker}

m=audio 10001 RTP/AVP 96
a=sendonly
a=rtpmap:96 PCMU
a=mid:7
a=clue-attributes:
a=clue-capture{1:mic-center,2:speaker}

m=audio 10002 RTP/AVP 96
a=sendonly
a=rtpmap:96 PCMU





a=mid:8
a=clue-attributes:
a=clue-capture{1:mic-right,2:speaker}

m=video 10002 RTP/AVP 96
a=recvonly
a=rtpmap:96 H264
a=content: main
a=mid:1
a=clue-attributes:

m=video 10003 RTP/AVP 96
a=recvonly
a=rtpmap:96 H264
a=content: main
a=mid:2
a=clue-attributes:

m=video 10004 RTP/AVP 96
a=recvonly
a=rtpmap:96 H264
a=content: main
a=mid:3
a=clue-attributes:

m=video 10006 RTP/AVP 96
a=inactive
a=rtpmap:96 H264
a=content: slides
a=mid:5
a=clue-attributes

m=audio 10000 RTP/AVP 96
a=recvonly
a=rtpmap:96 PCMU
a=mid:6
a=clue-attributes:

m=audio 10001 RTP/AVP 96
a=recvonly
a=rtpmap:96 PCMU
a=mid:7
a=clue-attributes:

m=audio 10002 RTP/AVP 96
a=recvonly
a=rtpmap:96 PCMU
a=mid:8
a=clue-attributes:








a=recvonly attribute.  Encoding options are represented by the <fmt>
m=video 10002 RTP/AVP 96 97
a=sendonly
a=rtpmap:96 H264
a=rtpmap:97 H265
a=content: main
a=mid:1
a=clue-attributes
a=clue-capture{1:camera-left,2:full-scene,
     3:composed-scene,4:speaker}

m=video 10003 RTP/AVP 96 97
a=sendonly
a=rtpmap:96 H264
a=rtpmap:97 H265
a=content: main
a=mid:2





a=clue-attributes:
a=clue-capture{1:camera-center,2:full-scene,
     3:composed-scene,4:speaker}

m=video 10004 RTP/AVP 96 97
a=sendonly
a=rtpmap:96 H264
a=rtpmap:97 H265
a=content: main
a=mid:3
a=clue-attributes:
a=clue-capture{1:camera-right,2:full-scene,
     3:composed-scene,4:speaker}

m=video 10006 RTP/AVP 96
a=sendonly
a=rtpmap:96 H264
a=content: slides
a=mid:4
a=clue-attributes
a=clue-capture{1:slides,2:presentation-camera,
     3:dvd}

m=audio 10000 RTP/AVP 96
a=sendonly
a=rtpmap:96 PCMU
a=mid:5
a=clue-attributes:
a=clue-capture{1:mic-left,2:speaker}

m=audio 10001 RTP/AVP 96
a=sendonly
a=rtpmap:96 PCMU
a=mid:6
a=clue-attributes:
a=clue-capture{1:mic-center,2:speaker}

m=audio 10002 RTP/AVP 96
a=sendonly
a=rtpmap:96 PCMU
a=mid:7
a=clue-attributes:
a=clue-capture{1:mic-right,2:speaker}

m=video 20002 RTP/AVP 96 97
a=recvonly





a=rtpmap:96 H264
a=rtpmap:97 H265
a=content: main
a=mid:8
a=clue-attributes:

m=video 20003 RTP/AVP 96 97
a=recvonly
a=rtpmap:96 H264
a=rtpmap:97 H265
a=content: main
a=mid:9
a=clue-attributes:

m=video 20004 RTP/AVP 96 97
a=recvonly
a=rtpmap:96 H264
a=rtpmap:97 H265
a=content: main
a=mid:10
a=clue-attributes:

m=video 20006 RTP/AVP 96
a=recvonly
a=rtpmap:96 H264
a=content: slides
a=mid:11
a=clue-attributes

m=audio 20000 RTP/AVP 96
a=recvonly
a=rtpmap:96 PCMU
a=mid:12
a=clue-attributes:

m=audio 20001 RTP/AVP 96
a=recvonly
a=rtpmap:96 PCMU
a=mid:13
a=clue-attributes:

m=audio 20002 RTP/AVP 96
a=recvonly
a=rtpmap:96 PCMU
a=mid:14
a=clue-attributes:

m=application 30000 CLUE
a=sendrcv


m=video 10002 RTP/AVP 96
a=recvonly
a=rtpmap:96 H264
a=content: main
a=mid:1
a=clue-attributes:

m=video 10003 RTP/AVP 96
a=recvonly
a=rtpmap:96 H264
a=content: main
a=mid:2
a=clue-attributes:

m=video 10006 RTP/AVP 96
a=recvonly
a=rtpmap:96 H264
a=content: slides
a=mid:4
a=clue-attributes

m=audio 10000 RTP/AVP 96
a=recvonly
a=rtpmap:96 PCMU
a=mid:6
a=clue-attributes:


m=video 20002 RTP/AVP 96
a=sendonly
a=rtpmap:96 H264
a=content: main
a=mid:8
a=clue-attributes:
a=clue-capture{1:main-camera,2:secondary-camera}





m=video 20006 RTP/AVP 96
a=sendonly
a=rtpmap:96 H264
a=content: slides
a=mid:11
a=clue-attributes
a=clue-capture{1:slides,2:presentation-camera}

m=audio 20000 RTP/AVP 96
a=sendonly
a=rtpmap:96 PCMU
a=mid:12
a=clue-attributes:
a=clue-capture{1:main-mic}

m=application 30000 CLUE
a=sendrcv




