v=0
o=- 25678 753849 IN IP4 192.0.2.1/24
s=
c=IN IP4 192.0.2.1/24
t=0 0
a=creq:v1
a=cmed:1 audio g729 iLBC
a=cenc:2 8000
a=cfmt:1 annexb:no
a=ctrpr:1 RTP/SAVP
m=audio 3456 RTP/AVP 0 18
a=mcap:3
a=capar:1 a=crypto:1 AES_CM_128_HMAC_SHA1_32
a=cptmap:1 1:100 2:101 3:102
a=pcfg:1 m=1,3|4,3 t=1 a=1 pt=1:100,4:101,3:102
a=pcfg:2 m=2 pt=2:103

v=0
o=- 24351 621814 IN IP4 192.0.2.2/24
s=
c=IN IP4 192.0.2.2/24
t=0 0
a=csup:v1
m=audio 4567 RTP/AVP 103
a=rtpmap:103 8000
a=acfg:2

a=cmed:<med-cap-num> <type> <subtype>*[ <subtype>]

media-capability-line = "a=cmed:" media-cap-num WSP media-type
                                    WSP media-cap *(WSP media-cap)
media-cap-num      = 1*DIGIT
media-type         = token ; MIME type (audio, video, etc.)
media-cap          = token ; MIME subtype (PCMU, G729, etc.)

a=cenc:<med-cap-num> <clock rate>[/<encoding parameters>]

a=cmed:1 iLBC
a=cenc:1 8000

a=cmed:1 L16 L16
a=cenc:1 8000
a=cenc:2 16000/2

a=cmed:1 L16/8000 L16/16000/2

a=cfmt:<med-cap-num> <list of format parameters>

a=cmed:1 audio G729 G729
a=cfmt:2 annexb:no

a=cmed:1 video H263-1998 H263-2000
a=cfmt:1 CIF=4;QCIF=2;F=1;K=1
a=cftp:2 profile=2;level=2.2
a=mcap:<med-cap-num>

a=cmed:1 audio GSM
m=audio 4567 RTP/AVP 0 18
a=mcap:6
a=pcfg:1 m=6|7
a=pcfg:2 m=1

m=<med-cap-list> *["/"<med-cap-list>]

pot-media-config = "m=" med-cap-list *("/" med-cap-list)
med-cap-list        = med-cap-num *("," med-cap-num)
med-cap-num      = 1*DIGIT      ; defined in SDP

v=0
o=- 25678 753849 IN IP4 192.0.2.1/24
s=
c=IN IP4 192.0.2.1/24
t=0 0
a=creq:v1
m=audio 3456 RTP/AVP 0 18 100
a=rtpmap:100 events
a=fmtp:100 0-15
a=pcfg:1 m=2,3/1,3

a = cptmap: 1*[<med-cap-num>:<payload-type>]
payload-type-map  = 1*(WSP <med-cap-num)":"<payload-type>)
med-cap-num         = 1*DIGIT ; from cmed: attribute
payload-type          = 1*DIGIT ; RTP payload type

v=0
o=- 25678 753849 IN IP4 192.0.2.1/24
s=
c=IN IP4 192.0.2.1/24
t=0 0
a=creq:v1
m=audio 3456 RTP/AVP 0 18
a=ctrpr:1 RTP/SAVP RTP/AVP
a=capar:1 a=crypto:1 AES_CM_128_HMAC_SHA1_80
FEC_ORDER=FEC_SRTP
a=cptmap:1 1:98 2:99
a=pcfg:5 t=1 a=1 pt=1
a=pcfg:10 t=2

act-media-config = "m=" med-cap-list
v=0
o=- 24351 621814 IN IP4 192.0.2.2/24
s=
c=IN IP4 192.0.2.2/24
t=0 0
a=csup:v1
m=audio 5432 RTP/AVP 18 100
a=rtpmap:100 events
a=fmtp:100 0-15
a=acfg:1 m=2,3

a=lcfg:<preference> ["m="<media-caps>] ["t="<transport>]
                ["a="<attributes>]

