scriptor = ALL at initialization.  Furthermore, since the

tionBuffered = NOTIFY had been accepted at initialization.
xducerList = (xducerName *(,xducerName))
toneList = (toneid *(,toneid))
keyList = (key *(,key))
key = (id, name if assigned, key name is settable or not).


indicatorList = (indicator *(,indicator))
indicator = (id, name if assigned, attributes).


softKeyList = (numberOfSoftkeys, displaySize, supportedCharSet,
                    softkey *(,softkey))

numberOfSoftkeys  = integer
displaySize       = integer ; number of characters
supportedCharSet  = Unicode character sets supported
softkey           = (nameStr, displayContent)
nameStr           = character string
displayContent    = Unicode character string


