AIF-OSCORE-GROUPCOMM = AIF_Generic<path, permissions>

path = tstr  ; Group name
permissions = uint . bits roles
roles = &(
         Requester: 1,
         Responder: 2,
         Monitor: 3,
         Verifier: 4
