v  ====            =====           =====
       A!
       o-----
              \
               ----->
            B  -----o SA(x)
             /
   SA(x)<----   C
            <======>

       D!
       o------------------
                          \
                           ----->
                        E  -----o SA(y)
                          /
   SA(y)<-----------------   F
        <=======================>

