a = %x41-5A / %61-7A  ; A-Z / a-z

ld = %x31-39          ; 1-9
d = %x30 / ld         ; 0-9

hyphen = %x2D         ; "-"

period = %x2E         ; "."

keychar = ( a / d / hyphen )
leadkeychar = ( a / d )

keystring = leadkeychar *keychar

name = keystring

numericoid = number *( period number ) ; e.g. 1.1.23.4

number = d / ( ld 1*d )

option = keystring

