entity="pres:3650n87934c@ls.example.com">
targetNamespace="urn:x-grip:ns"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
default=""/>
default=""/>
targetNamespace="urn:x-grip:gnss:gps"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

minOccurs="0" maxOccurs="32"/>
use="required"/>
minOccurs="0" maxOccurs="32"/>
minOccurs="0" maxOccurs="32"/>
minOccurs="0" maxOccurs="32"/>
minOccurs="0" maxOccurs="32"/>
