rsv_state = 0
count = 0
count = count + requested units
count = count + requested units
count = count + requested units
rsv_state = rsv_state + requested units

rsv_state = count    /* update reservation state /
count = 0            /* and reset count */
nrofsubwindows = 15      // number of subwindows in the periodlength
rfcount = 0             // count of PHR_Resource_Request
                           // and PHR_Refresh_Update messages
                           // in current subwindow

lastsum = sum from i=0 to nrofsubwindows-1 of countarray[i]

newsum = lastsum - countarray[0] + rfcount
rfcount = rfcount + units
lastsum = lastsum + units
rfcount = rfcount + units
lastsum = sum(countarray)

newsum = lastsum - countarray[0]
