qdelay_fraction_t = qdelay/qdelay_target
qdelay_fraction_avg = (1-QDELAY_WEIGHT)*qdelay_fraction_avg+
          QDELAY_WEIGHT*qdelay_fraction_t
avg_t = average(qdelay_fraction_hist)
a_t = R(qdelay_fraction_hist-avg_t,1)/
             R(qdelay_fraction_hist-avg_t,0)
qdelay_trend = min(1.0,max(0.0,a_t*qdelay_fraction_avg))
qdelay_trend_mem = max(0.99*qdelay_trend_mem, qdelay_trend)
n=N-k
n=1

in_fast_increase = false
cwnd = max(MIN_CWND,cwnd*BETA_LOSS)
cwnd = max(MIN_CWND,cwnd*BETA_ECN)
in_fast_increase = false
cwnd = cwnd+bytes_newly_acked
off_target_t = (qdelay_target - qdelay) / qdelay_target

gain_t = GAIN
cwnd_delta_t =
       gain_t * off_target_t * bytes_newly_acked * MSS / cwnd
cwnd_delta_t = 0;
cwnd = min(cwnd, max_bytes_in_flight*MAX_BYTES_IN_FLIGHT_HEAD_ROOM)
cwnd = max(cwnd, MIN_CWND)

qdelay_norm_t = qdelay / QDELAY_TARGET_LOW
qdelay_norm_var_t = VARIANCE(qdelay_norm_history(200))
qdelay_norm_avg_t = AVERAGE(qdelay_norm_history(50))
new_target_t = qdelay_norm_avg_t + sqrt(qdelay_norm_var_t)
qdelay_target = 1.5*new_target_t
qdelay_target = new_target_t
qdelay_target = max(qdelay_target*0.5,new_target_t)
qdelay_target = min(QDELAY_TARGET_HI, qdelay_target)
qdelay_target = max(QDELAY_TARGET_LO, qdelay_target)
send_wnd = cwnd+MSS-bytes_in_flight
send_wnd = cwnd-bytes_in_flight
pace_bitrate = max (RATE_PACE_MIN, cwnd* 8 / s_rtt)
t_pace = rtp_size * 8 / pace_bitrate
target_bitrate = max(BETA_R* target_bitrate, TARGET_BITRATE_MIN)
target_bitrate = max(BETA_ECN* target_bitrate, TARGET_BITRATE_MIN)
ramp_up_speed_t = min(RAMP_UP_SPEED, target_bitrate/2.0)
scale_t = (target_bitrate - target_bitrate_last_max)/
        target_bitrate_last_max
scale_t = max(0.2, min(1.0, (scale_t*4)^2))
increment_t = ramp_up_speed_t*RATE_ADJUST_INTERVAL
current_rate_t = max(rate_transmit, rate_ack)
delta_rate_t = current_rate_t*(1.0-PRE_CONGESTION_GUARD*
           queue_delay_trend)-TX_QUEUE_SIZE_FACTOR *rtp_queue_size
delta_rate_t =
          min(delta_rate_t,ramp_up_speed_t*RATE_ADJUST_INTERVAL)
rtp_queue_delay_t = rtp_queue_size/current_rate_t
rate_media_limit_t =
      max(current_rate_t, max(rate_media,rtp_rate_median))
target_bitrate = min(target_bitrate, rate_media_limit_t)
target_bitrate = min(TARGET_BITRATE_MAX,
      max(TARGET_BITRATE_MIN,target_bitrate))
PRE_CONGESTION_GUARD=0, the effect is a somewhat faster rate increase
rate_fb = min(50,max(2.5,rate_media/10000))


fb_int = 1.0/min(50,max(2.5,rate_media/10000))


media_rate = target_bitrate - rtp_plus_fec_overhead_bitrate

