txt-record    = version-param SEMI key-param [ SEMI txt-param ] 
version-param = "v=" "CIDER1" 
key-param     = key-type SEMI key-data 
key-type      = "k=" ("rsa" / hyphenated-word) 
key-data      = "p=" DQUOTE [ base64 ] DQUOTE 
    
