source     = Detected_Queries[BRP_cache_ID].source;
query_id   = Detected_Queries[BRP_cache_ID].query_id; 
prev_bcast = Detected_Queries[BRP_cache_ID].prev_bcast;
coverage   = Query_Coverage[source,query_id].init();
source     = MY_ID;             
query_id   = MY_BORDERCAST_ID++;
prev_bcast = MY_ID;
coverage   = Query_Coverage[source,query_id];

prev_bcast_int_nodes = 
                         construct_routing_zone(coverage, prev_bcast);
out_neighbors = 
                               IARP_Route_Table[query_dest].next_hop;
out_neighbors = {};

bordercast_tree = 
                         construct_bordercast_tree(coverage, prev_bcast);
out_peripheral_nodes =
                        bordercast_tree.my_downstream_peripheral_nodes();
out_neighbors = 
                                bordercast_tree.my_dowstream_neighbors();


coverage = Query_Coverage[source, query_id];

bordercast_tree = 
                   construct_bordercast_tree(coverage, prev_bcast);
prev_bcast = MY_ID;
prev_bcast_int_nodes = 
                              construct_routing_zone(prev_bcast);
