Type=PEAP. The data field of this packet will encapsulate one or more
EAP-Type=PEAP.  The data field of this packet will encapsulate one or
Type=PEAP, which includes, in the case of a new TLS session, one or more
type=33 (EAP Extensions), protected within the TLS channel. The PEAP
Result=Failure, then it will accept and process a cleartext EAP Failure.
L = Length included
M = More fragments
S = PEAP start
R = Reserved (must be zero)

R = Reserved (must be zero)

L = Length included
M = More fragments
S = PEAP start
R = Reserved (must be zero)

R = Reserved (must be zero)

L = Length included
M = More fragments
S = PEAP start
R = Reserved (must be zero)

R = Reserved (must be zero)

Type=Extensions with  Result AVP of Status=Success is answered by an EAP
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP ->

EAP-Type=X
EAP-Type=X or NAK ->

                       <- EAP-Request/
EAP-Type=X
EAP-Type=X  ->
                        <- EAP-Request/
EAP-Type=Extensions
Result=Success
EAP-Type=Extensions
Result=Success  ->

EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1 ->

EAP-Type=X
EAP-Type=X or NAK ->

                       <- EAP-Request/
EAP-Type=X
EAP-Type=X  ->
                        <- EAP-Request/
EAP-Type=Extensions
Result=Success
EAP-Type=Extensions
Result=Success  ->

EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1 ->

EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1 ->
                        <- EAP-Request/
EAP-Type=Extensions
Result=Success
EAP-Type=Extensions
Result=Success  ->

EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1 ->
                        <- EAP-Request/
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1 ->
                        <- EAP-Request/
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1 ->

EAP-Type=X
EAP-Type=X or NAK ->

                       <- EAP-Request/
EAP-Type=X
EAP-Type=X  ->
                        <- EAP-Request/
EAP-Type=Extensions
Result=Success
EAP-Type=Extensions
Result=Success  ->

EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1 ->

EAP-Type=X
EAP-Type=X or NAK ->

                       <- EAP-Request/
EAP-Type=X
EAP-Type=X  ->
                        <- EAP-Request/
EAP-Type=Extensions
Result=Failure
EAP-Type=Extensions
Result=Failure  ->

EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP,V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=Extensions
Result=Success
EAP-Type=Extensions
Result=Success  ->
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1 ->
                         <- EAP-Failure
                         (TLS session cache entry flushed)

EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=1
EAP-Type=PEAP, V=0
EAP-Type=PEAP, V=0
EAP-Type=PEAP, V=0
EAP-Type=PEAP, V=0
EAP-Type=PEAP, V=0
