n = long(0)
v = ord(s[i])
n = n<<7
n = n + (v & 0x7F)
slen = i+1
n = -1 # reached end of input without seeing end of SDNV
r = ""
flag = 0
done = False
newbits = n & 0x7F
n = n>>7
r = chr(newbits + flag) + r
flag = 0x80
done = True
tests = [(0xABC, chr(0x95) + chr(0x3C)),
              (0x1234, chr(0xA4) + chr (0x34)),
              (0x4234, chr(0x81) + chr(0x84) + chr(0x34)),
              (0x7F, chr(0x7F))]

