UID=25627;Section=1.2" TEXT {44} 
uth=submit+bar" INTERNAL 
            I: * GENURLAUTH 
uth=submit+bar:internal:91354a473744909de610943775f92038" 
            I: A0054 OK GENURLAUTH completed 
 
      M: {to S} The client connects to the submission server and starts 
th=submit+bar:internal:91354a473744909de610943775f92038 LAST 
      
      S: {to I} The submission server uses URLFETCH to fetch the message 
th=submit+bar:internal:91354a473744909de610943775f92038" 
            I: * URLFETCH " 
th=submit+bar:internal:91354a473744909de610943775f92038" {15065} 
            ...message body follows... 
            S: a002 OK URLFETCH completed 
      
