packet = command SP epochtime SP md5-signature NULL

command = *%x41-5A [*(SP option)]

option = *VCHAR

epochtime = *DIGIT

md5-signature = 32(HEXDIG)

NULL =  %x00

common-options = ("HOST" endpoint |
                     "TUNNEL" outer-endpoint SP inner-endpoint)

endpoint = IPv4address | IPv6address

command = "HEARTBEAT" SP common-options

command = "DISABLE" SP common-options

