explicit-default=recognized

xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
targetNamespace="urn:ietf:params:xml:ns:netconf:with-defaults:1.0"
elementFormDefault="qualified" attributeFormDefault="unqualified"
type="xs:boolean"/>

