FBM-Size = 20 + 8R + 1.5T
                                    
 




FwdBwEstWei = 0.9
I_FwdBwEstWei = (1.0 - FwdBwEstWei)

TargetQDelay = 50msec

WndBrFract = 1sec

TrigProbQDFractMax  = 0.8
TrigProbBrFractMin  = 1.0
 




TrigProbQMRangeMax  = 10msec
TrigProbLossRtMax   = 0.02
TrigProbECNRtMax    = 0.0

TrigStopProbQDFractMin = 1.3
TrigStopProbBrFractMin = 1.2
TrigStopProbLossRtMax    = 0.0
TrigStopProbECNRtMax     = 0.0

TrigCompQDelayMin  = 200msec
TrigCompQMRangeMi  = 100msec

TrigStopCompQDelayMax = 100msec
TrigStopCompQMRangeMax = 20msec

TrigThroQDFractMin = 1.5
TrigThroBrFractMax = 0.9

Thro2CompQIncrTime = 1sec

DfltQDFractLow = 0.5
DfltQDFractHi  = 1.1
DfltBrIncrRate  = 1.01
DfltBrDecrRate  = 0.95

CompTargetTxbwRate = 1.3
ThroTargetTxbwRate = 0.5

ProbingTime = 4sec

CompQDFractLow = 0.5
CompQDFractHi  = 1.0
CompBrIncrRate = 1.02

sent_tstmp_end_seq = get_tstmp(txed_rtps, latest_end_seq, ssrc)
end_tstmp = sent_tstmp_end_seq + fbm.ato(latest_end_seq, ssrc)
bgn_tstmp = period_end_tmstmp - fbm.monitored_time
fwd_bw = tot_rxed_size / fbm.monitored_time

esti_bw = FwdBwEstWei*esti_bw + I_FwdBwEstWei*fwd_bw
incr_start_tstmp = end_tstmp

incr_duration = end_tstmp - incr_start_tstmp;

is_increasing = true
incr_count = 0
incr_start_tstmp = 0
is_increasing = false


last_qdelay = qdelay
qd_fract = qdelay / target_qdelay
br_fract = recved_size_wnd / sent_size_wnd
target_qdelay = TargetQDelay + TargetXQDelay
target_txbw = esti_bw * CompTargetTxbwRate
status = Competing
thro_backup_target_txbw = esti_bw
target_txbw = esti_bw * ThroTargetTxbwRate
status = Throttled
prob_backup_target_txrt = esti_bw
target_txbw = esti_bw + prob_bw
prob_start_tstmp = curr_tstmp
status = Probing

target_qdelay = TargetQDelay
status = Default

status = Default
target_txnw = prob_backup_target_txbw + prob_bw

target_txbw = esti_bw
status = Default

target_txbw = thro_backup_target_txbw
status = Default

thro_backup_target_txbw = esti_bw
target_txbw = esti_bw * ThroTargetTxbwRate

















 




