initial_salt = 0xef4fb0abb47470c41befcf8031334fae485e09a0
initial_secret = HKDF-Extract(initial_salt,
                                 client_dst_connection_id)

client_initial_secret = HKDF-Expand-Label(initial_secret,
                                             "client in", "",
                                             Hash.length)
server_initial_secret = HKDF-Expand-Label(initial_secret,
                                             "server in", "",
                                             Hash.length)
mask = header_protection(hp_key, sample)

pn_length = (packet[0] & 0x03) + 1
sample_offset = 1 + len(connection_id) + 4

sample = packet[sample_offset..sample_offset+sample_length]

sample_offset = 6 + len(destination_connection_id) +
                       len(source_connection_id) +
                       len(payload_length) + 4
sample = packet[sample_offset..sample_offset+sample_length]

mask = AES-ECB(hp_key, sample)
counter = DecodeLE(sample[0..3])
nonce = DecodeLE(sample[4..7], sample[8..11], sample[12..15])
mask = ChaCha20(hp_key, counter, nonce, {0,0,0,0,0})

protected_field = field XOR PRF(hp_key, sample)

initial_secret = HKDF-Extract(initial_salt, cid)
       = 4496d3903d3f97cc5e45ac5790ddc686
         683c7c0067012bb09d900cc21832d596

key = HKDF-Expand-Label(client_initial_secret, "quic key", _, 16)
       = 98b0d7e5e7a402c67c33f350fa65ea54

iv  = HKDF-Expand-Label(client_initial_secret, "quic iv", _, 12)
       = 19e94387805eb0b46c03a788

hp  = HKDF-Expand-Label(client_initial_secret, "quic hp", _, 16)
       = 0edd982a6ac527f2eddcbb7348dea5d7

key = HKDF-Expand-Label(server_initial_secret, "quic key", _, 16)
       = 9a8be902a9bdd91d16064ca118045fb4

iv  = HKDF-Expand-Label(server_initial_secret, "quic iv", _, 12)
       = 0a82086d32205ba22241d8dc

hp  = HKDF-Expand-Label(server_initial_secret, "quic hp", _, 16)
       = 94b9452d2b3c7c7f6da7fdd8593537fd

sample = 0000f3a694c75775b4e546172ce9e047

mask = AES-ECB(hp, sample)[0..4]
        = 020dbc1958

header = c1ff000012508394c8f03e51570800449f0dbc195a

sample = c4c2a2303d297e3c519bf6b22386e3d0
mask   = 75f7ec8b62
header = c4ff00001205f067a5502a4262b5004074f7ed

