certificate_type=(RawPublicKey-Accept) -> // [1]

                         <-  server_hello,
certificate_type=(RawPublicKey-Offer), // [2]
certificate_type=(RawPublicKey-Offer, RawPublicKey-Accept) -> // [1]

                            <-  server_hello,
certificate_type=(RawPublicKey-Offer,
                                            RawPublicKey-Accept) // [2]
certificate_type=(X.509-Accept, RawPublicKey-Offer) -> // [1]

                            <-  server_hello,
certificate_type=(X.509-Offer,
                                     RawPublicKey-Accept), // [2]
