Offset = AES(K, Nonce xor L)
Checksum = ZERO
Offset = Offset xor L(ntz(i))
Checksum = Checksum xor M[i]
Offset = Offset xor L(ntz(m))
Pad = AES (K, len(M[m]) xor L(-1) xor Offset)
Checksum = Checksum xor Pad xor C[m]0*
FullTag = AES(K, Checksum xor Offset)
Tag = the taglen-bit prefix of FullTag
Offset = AES(K, Nonce xor L)
Checksum = ZERO
Offset = Offset xor L(ntz(i))
Checksum = Checksum xor M[i]
Offset = Offset xor L(ntz(m))
Pad = AES (K, len(C[m]) xor L(-1) xor Offset)
Checksum = Checksum xor Pad xor C[m]0*
FullTag = AES(K, Checksum xor Offset)
Tag = the taglen-bit prefix of FullTag
