Forwarded   = Forwarded-v
Forwarded-v = 1#forwarded-element

forwarded-element =
           [ forwarded-pair ] *( ";" [ forwarded-pair ] )

token = <Defined in
           [I-D.ietf-httpbis-p1-messaging], Section 3.2.4>
quoted-string = <Defined in
           [I-D.ietf-httpbis-p1-messaging], Section 3.2.4>

forwarded-pair = token "=" value
value          = token / quoted-string

IPv4address = <Defined in [RFC3986], Section 3.2.2>
IPv6address = <Defined in [RFC3986], Section 3.2.2>

nodename = IPv4address / "[" IPv6address "]" /
                   "unknown" / obfnode

node          = nodename [ ":" node-port ]

DIGIT = <Defined in [RFC5234], Section 3.4>
ALPHA = <Defined in [RFC5234], Section B.1>

node-port     = port / obfport
port          = 1*5DIGIT
obfport       = "_" 1*(ALPHA / DIGIT / "." / "_" / "-")

obfnode         = "_" 1*( ALPHA / DIGIT / "." / "_" / "-")

for=198.51.100.17;by=203.0.113.60;proto=http;host=example.com"
