entity="pres:someone@example.com">

        <tuple id="joi9877866786ua9">
          <status>
            <basic>open</basic>
          </status>
          <caps:servcaps>
            <caps:audio>true</caps:audio>
            <caps:description>
              Example service
            </caps:description>
            <caps:duplex>
              <caps:supported>
                <caps:full/>
              </caps:supported>
            </caps:duplex>
            <caps:message>true</caps:message>
            <caps:methods>
              <caps:supported>
                <caps:ACK/>
                <caps:BYE/>
                <caps:INVITE/>
              </caps:supported>
            </caps:methods>
            <caps:priority>
              <caps:supported>
                <caps:lowerthan maxvalue="10"/>
              </caps:supported>
            </caps:priority>
            <caps:schemes>
             <caps:supported>
              <caps:s>sip</caps:s>
             </caps:supported>
            </caps:schemes>
            <caps:video>false</caps:video>
          </caps:servcaps>
          <contact>sip:someone@example.com</contact>
        </tuple>
        <mod:device id="hgt67">
            <caps:devcaps>
              <caps:mobility>
                <caps:supported>
                  <caps:mobile/>
                </caps:supported>
              </caps:mobility>
            </caps:devcaps>
           <mod:deviceID>urn:uuid:d27459b7-8213-4395-aa77-ed859a3e5b3a</mod:deviceID>
        </mod:device>
content="text/html;charset=iso-8859-1"/>
