Location=B2.
A =B2Conformance=B2 chapter has been added.

type=3DMULTIPART/ALTERNATIVE

type=3DText/HTML

type=3DText/HTML

type=3DText/HTML

type=3DText/HTML

Type=B2, RFC 1873, December 1995.

                                                                           =
Header=B2, RFC 1806, June 1995.

                                                                           =
start-info=3D=B2linking=3Dvirtual=B2

or =B2VIRTUAL FILE=B2 be used to clarify that no real file storage is
type=3DMULTIPART/ALTERNATIVE

type=3DText/html

