P-User-Location-Info     = "P-User-Location-Info" HCOLON   
                               PServedUser-value  
                               (SEMI-visited-network-id-param) 
                               SEMI location-info-param  
                               *(COMMA location-info-param) 
            
PServedUser-value       = name-addr / addr-spec 
        
visited-network-id-param  = "visited-network-id" EQUAL   
                                         vnetwork-spec*(COMMA vnetwork-spec) 
         
location-info-param     = location-info (SEMI date-time-value) 
                          
Location-info         = cgi-3gpp / utran-cell-id-3gpp /  
                                extension-access-info 
        
extension-access-info    = gen-value 
        
cgi-3gpp             = "cgi-3gpp" EQUAL 
     
     

            for the 3GPP IP Multimedia (IM) Core Network (CN) Subsystem 
                                 June 2015 
     
     
                                         (token / quoted-string) 
        
utran-cell-id-3gpp      = "utran-cell-id-3gpp" EQUAL 
                                         (token / quoted-string) 
        
local-time-zone        = "local-time-zone" EQUAL  
                             (token / quoted-string) 
        
date-time-value        = "date-time" EQUAL date time 
        
        
