avg-neighbors = #nodes/2.  The density of the network will define the
avg-neighbors        = average number of neighbors per node
neighbor-change-rate = the number of neighbors entering or
                          leaving state 2-way per node per sec.
neighbor-life        = average number of seconds neighbors are
                          in state 2-way
adjacency-rate       = the number of adjacencies being formed
                          per node per second
LSAsOutSync          = average number LSAs different between two
                          neighbors forming an adjacency

Tes = X (current_time - T[0]) + (1-X) Tes;
Tes = Tes/avg_total;
