Options = (E-bit set)          ;Mandatory with OSPF-lite
Type = 9                ;OSPF-lite-transit
metric = 3              ;cost = 3


Type = 8                ;OSPF-lite-stub
metric = 3

                   Figure 2.1 RT101s router LSA


Type = 8                ;OSPF-lite-stub
metric = 3

Type = 8                ;OSPF-lite-stub
metric = 3

Type = 8                ;OSPF-lite-stub
metric = 3

               Figure 2.2 Extracted 32 bit host routes

Options = (E-bit)              ;Mandatory with OSPF-lite
Type = 8                ;OSPF-lite-stub
metric = 1

Type = 8                ;OSPF-lite-stub
metric = 2

Type = 8                ;OSPF-lite-stub
metric = 3

Options = (E-bit)              ;Mandatory with OSPF-lite
Type = 9                ;OSPF-lite-transit
metric = 1

Type = 8                ;OSPF-lite-stub
metric = 2

Type = 9                ;OSPF-lite-transit
metric = 3
