attributeSelection = noattrs /  
                         *( attributedescription / specialattr ) 
    
noattrs = %x31 %x2E %x31 ; "1.1" 
    
specialattr = ASTERISK 
    
ASTERISK = %x2A ; asterisk ("*") 
  
              Lightweight Directory Access Protocol Version 3 
                                      
    
