TTL_new =  ---------------.
  			      num_neighbor

   In this computation, TTL_current is the IP TTL value in the incoming 
   tracetree request packet and num_neighbor is the number of outgoing
   interfaces that the router has on the multicast tree. According to 
   this computation, the TTL_current value limits the number of routers 
   that receive a request packet. In the case of the FHR, it may use 
   either a pre-configured default value or a value received from the 
   querier.

   The remaining portion of the tree can be discovered in additional 
   rounds. Each round begins by having the querier send new query 
   messages to appropriate on-tree routers to continue topology discovery
   in a similar way.
E=1 implies that this router did not forward the request packet on its
