href="http://app.example.net/cgi-bin/prepaid? \
session=19fsjcalksd&keypress=long-pound" />
href="http://app.carrier.net/pp/12?local-operator/>
href="http://app.carrier.net/pp/12?ld-operator/>
href="http://app.carrier.net/pp/12?vpn/>
href="http://app.carrier.net/pp/12?local-number7/>
href="http://app.carrier.net/pp/12?local-number10/>
href="http://app.carrier.net/pp/12?ddd/>
href="http://app.carrier.net/pp/12?iddd/>
href="http://app.example.net/vm/sess$9awj08asd7?keep" />
             <regex value="7"
href="http://app.example.net/vm/sess$9awj08asd7?replay" />
             <regex value="3"
href="http://app.example.net/vm/sess$9awj08asd7?delete" />
           </pattern>
         </request>
       </kpml>

href="sip:" />
elementFormDefault="qualified">
