p=>  |  |  <=s                    p=>  |  |  <=s
              +------+                          +------+
              |  MN  |                          |  MN  |
              +------+                          +------+


                 (a)                               (b)



