identity-request-data = [ displayable-string ] %x00 [ IP-modes ]

displayable-string = *CHAR

IP-modes = "IPmodes=" mode-list
mode-list = mode / ( mode-list ";" mode )
mode = "pmip4-ietf"  / "pmip6-ietf"  / "mip4-ietf"   /
             "mip6-ietf"   / "dsmip6-ietf" / "pmip4-wimax" /
             "pmip6-wimax" / "mip4-wimax"  / "mip6-wimax"  /
             "mip4-3gpp2"  / "mip6-3gpp2"  / "mip4-lte"    /
             "dsmip6-lte"

