pre_vector = PRF(SecurityParameters.master_secret,  
                          "inner application preliminary vector",  
                          SecurityParameters.server_random + 
                          SecurityParameters.client_random) [0..48]; 

IA_challenge = PRF(SecurityParameters.master_secret, 
                             "inner application challenge", 
                             SecurityParameters.server_random + 
                             SecurityParameters.client_random); 

