MSK = Keying Material [0..63] 

EMSK = Keying Material [64..127] 

client_key_confirmation = TLS-PRF-32(composite_key, 
                "ttls client key confirmation", 
                <null>) 

server_key_confirmation = TLS-PRF-32(composite_key, 
                "ttls server key confirmation", 
                <null>) 




 
 
    

