val-URI       = "val:" "(" datatypeURI ")" lexicalForm
datatypeURI   = absoluteURI [ "%23" fragment ]
lexicalForm   = 1*uric

absoluteURI   = <as defined by RFC 2396>
fragment      = <as defined by RFC 2396>
uric          = <as defined by RFC 2396>

