TR1==========+---------+==========TR3
     |           |         |
     D           |         |
     |           |   DUT   |
TR2==========|         |
                 +---------+

TR1==========+---------+==========TR3
     |           |         |
     D           |         |
     |           |   DUT   |

TR2==========|         |
                 |         |
                     ...
TRn==========+---------+


