s = int socket(int domain, int type, int protocol)

optlen=size(sse_opts);
optname= SSLS_SSE; #4
s = int socket(int domain, int type, int protocol)
errno =  int setsockopt(sockfd,level,optname,
             void struct *sse_opts,optlen);

