C=Critical, R=Repeatable

payload = [+ missing-block-number]
missing-block-number = uint

             Figure 1: Structure of the Missing Blocks Payload

Time-to-Wait = NON_RECEIVE_TIMEOUT * (2 ** (Re-Request-Count - 1))

