targetNamespace="urn:ietf:params:xml:ns:ipfix-psamp-config"
xmlns="urn:ietf:params:xml:ns:ipfix-psamp-config"
elementFormDefault="qualified"
version="3.0">
minOccurs="0" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" default="both" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" default="both" />
minOccurs="0" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" default="normal" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" default="primary" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" />
minOccurs="1" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" />
description="10-out-of-100 random packet sampler">
description="UDP filter">
description="Packet cache with immediate expiration">
description="PR-SCTP exporter">
description="Count-based packet sampler">
description="Time-based packet sampler">
description="SCTP Exporter with UDP backup destination">
