SL=1;NH=ICMPv6)(ICMPv6 Echo Request).  When the node N4 receives the
NH=ICMPv6)(ICMPv6 Echo Request).

NH=ICMPv6)(ICMPv6 Echo Request).

NH=UDP) (traceroute probe).  Even though Hop Count of the packet is
NH=UDP)(Traceroute probe).

NH=UDP)(Traceroute probe) with hop-count = 1, it processes the hop
NH=UDP)(Traceroute Probe).  Please note that the hop-count is set
SL=1, HC=64, Flags.O=1; NH=UDP)(Traceroute Probe), it processes
SL=0, HC=62, Flags.O=1; NH=UDP)(Traceroute Probe), it processes
