serializationPattern="urn:schemas-microsoft-com:soap.v1">
        <SOAP:headers id="ref-0">
                <TransactionId type="int"
mustUnderstand="1">5</TransactionId>
        </SOAP:headers>
        <GetLastTradePrice id="ref-1">
                <__param0 id="ref-2">DIS</__param>
        </GetLastTradePrice>
serializationPattern="urn:schemas-microsoft-com:soap.v1">
serializationPattern="urn:schemas-microsoft-com:soap.v1">
serializationPattern="urn:schemas-microsoft-com:soap.v1">
