ligthSource=cameraFlash) it SHOULD use a default value for that
targetNamespace="urn:ietf:params:xml:ns:im-poke"
elementFormDefault="qualified"
attributeFormDefault="unqualified">
use="optional" default="false"/>
use="optional" default="false"/>
use="optional"/>
use="optional"/>
use="optional"/>
use="optional" default="false"/>
use="optional" default="false"/>
use="optional" default="false"/>
use="required"/>
content="text/html;charset=iso-8859-1"/>
