Content-Range       = 1#range-item
range-item          = range-unit SP
                         ( range-resp / unsatisfied-range )

range-resp          = incl-range "/" ( complete-length / "*" )
incl-range          = first-pos "-" last-pos
unsatisfied-range   = "*/" complete-length

complete-length     = 1*DIGIT

                 Figure 2: ABNF for extended Content-Range

content-type = video/mp4
content-range = bytes 10000-17999/18879543, bytes 24000-41999/18879543

                  Figure 3: Range-Response header example

   Implementations advertising support for the "DATA_WITH_OFFSET" frame
   as described in Section 5 MUST be able to consume this overloaded
   form of the "Content-Range" HTTP response header.

   A server MAY continue to use the method described in [HTTP-SEMANTICS]
   even if a client has expressed support for the "DATA_WITH_OFFSET"
   frame.

      *Author's Note:* Is it possibly worth splitting this out into its
      own HTTP setting value?
