iap-message       =
                          ( iap-connect-request |
                            iap-upgrade-request |
                            iap-channel-setup-request  |
                            iap-content         |
                            iap-response )
                           CRLF


iap-t-version     = "IAP/0.3"



sender-receiver   = "Sender" | "Receiver"


iap-response      = iap-t-version SP
                         3DIGIT CRLF



iap-t-via         = iap-t-version SP
                         "Via:" SP host CRLF



iap-content-type  = "Content-Type:" SP
                         "application/x-idef-alert"
                         CRLF

