pn-type=acme:acme-param;
pn-prid="ZTY4ZDJlMzODE1NmUgKi0K">
uri-parameter   =/ pn-prid / pn-type / pn-enccode / pn-enckey
pn-prid         = "pn-prid" EQUAL pvalue
pn-type         = "pn-type" EQUAL pns-provider COLON pns-param
pn-enccode      = "pn-enccode" EQUAL pvalue
pn-enckey       = "pn-enckey" EQUAL pvalue

pns-provider    = pvalue ; Colon (":") characters MUST be escaped
pns-param       = pvalue ; Colon (":") characters MUST be escaped

