rt=brski type resources.  (So, a query for rt=brski, without the
smime-type=certs-only") to retrieve all the certificates.

x = load_cert(file, "certificate file");
csc = X509_STORE_CTX_new();
i = X509_verify_cert(csc);
Ver = 1
T = 0 (CON)
Code = 0x02 (0.02 is POST)
Payload = <binary CBOR enrollstatus document>

Ver=1
T=2 (ACK)
Code = 0x44 (2.04 Changed)

Payload =
sn=8

DevID=pledge.1.2.3.4
serialNumber="serialNumber=$DevID"
OPENSSL_BIN="openssl"

CN=masa.stok.nl
CN=uuid:pledge.1.2.3.4/serialNumber=pledge.1.2.3.4
CN=registrar.stok.nl
CN=registrar.stok.nl
OU=manufacturer, CN=masa.stok.nl

OU=manufacturer, CN=masa.stok.nl
