Capsule-Protocol = sf-item
capsule-protocol = ?1

Payload = Encapsulated UDP Payload

              <--------  STREAM(44): HEADERS
                           :status = 200
capsule-protocol = ?1

Payload = Encapsulated UDP Payload

origin = https://www.example.org:443

              <--------  STREAM(44): HEADERS
                           :status = 200

