byte-range-spec = first-byte-pos "-" [ last-byte-pos ]

byte-content-range  = bytes-unit SP
                           ( byte-range-resp / unsatisfied-range )

byte-range-resp     = byte-range "/" ( complete-length / "*" )
byte-range          = first-byte-pos "-" last-byte-pos
unsatisfied-range   = "*/" complete-length

complete-length     = 1*DIGIT

