Notitification-type=1, Notification-value=1 or 2: a PCC,
Notitification-type=2, Notification-value=1 or 2 : indicates to
type=12, error-value=1, a TLV "Propagation" at value 0 and a TLV
notification-type=1, notification-value=1 as described in [RFC5440]).
