StartLine = *CRLF ( StatusLine / ReqLine)
                               ;--XPDU

UriPrms = 1*( ";" UriPrms)

            ;--XCUT 2
            ;--XTYPE 0=struct.
NotifyCompletionReason = (TimeOutToken
                                    / InterruptByEventToken
                                    / InterruptByNewSignalsDescrToken
                                    / OtherReasonToken)
                ;--XTYPE 0=bit
                ;--XVAR 2=onTimeOut, 3=onInterruptByEvent,
                ;--XVAR 4=onInterruptByNewSignalDescr, 5=otherReason

TransactionReply = ReplyToken EQUAL TransactionID LBRKT
                                   [ ImmAckRequiredToken COMMA]
                                   TransactionResult RBRKT
                      ;--XCUT 1,2,4,7,9
                      ;--XVAR 3=transactionId, 6=immAckRequired, 
                              8=transactionResult
                      ;--XTYPE 6=null

UserInfo    = 1*(%x21-3F / %x41-FF) "@"
                        ;--XCUT 4
                        ;--XTYPE 0=char*esc

AddRequest = AddToken EQUAL AmmRequest
                     ;--XCUT 1,2
                     ;--XTDEF 3
CommandRequest = ["O-"] ["W-"] Command
              ;--XVAR 2=optional, 4=wildcardReturn, 5=command
              ;--XORDER 5,4,2      
MessageBody = Token
               ;--XLEN ContentLength

CallId = ( "Call-ID" / "i" ) HCOLON Payload CRLF
                     ;--XCUT 2,3,4,6
                     ;--XNCASE 2,3
                     ;--XTDEF 5
                     ;--XDUP 3=0x20,0x09,0x3a
Host = Ipv4 / Ipv6 / HostName
                    ;--XALT 3
HostName =  1*(Alphanum / "-"/ "." )
                    ;--XTYPE 0=char

ExtHdrList = 1*(ExtHdr)
      ;--XTYPE 0=structl
      ;--XSTRL 2=0x21,0x23-27,0x2a-2b,0x2d-2e,0x30-39,0x41-5a,0x5e-7a,
         0x7c,0x7e
      ;In this case, it specifies all the character suitable for ExtHdr
         = Token
                 ;
ExtHdr = Token HCOLON 0*1Payload CRLF
                 ;--XCUT 2,4
                 ;--XVAR 1=mHdrName, 3=mHdrValue

MsgHdrList   = *{
                              0*1AcceptList
                                ViaList
                              0*1ExtHdrList
                               } CRLF





ExtHdrList = 1*(ExtHdr)
                    ;--XTYPE 0=structl
                    ;--XSTRL 2=0x41-5A,0x61-7A,0x30-39,0x2d,0x2e,0x21
                                 ,0x25, 0x2a,0x5f,0x2b,0x60,0x27,0x7e
                      ;--XNRPT 1
ExtHdr = Token HCOLON Payload CRLF
                      ;--XCUT 2,4
                      ;--XVAR 1=mHdrName, 3=mHdrValue

HCOLON  =  *( SP / HTAB ) ":" 0*1LWS
                            ;--XCUT 0
                            ;--XFENC 5=0x20
LWS = [*WSP CRLFLWS] 1*WSP
                            ;--XCUT 0

SIPMessage = StartLine MsgHdrList
                         ;--XPDU
StartLine  = *CRLF (StatusLine / ReqLine)
                     ;--XNLCMP
                     ;--XCUT 1
                     ;--XALT 4
                     ;--XCHOICE 3=SL_mStatus_chosen, 4=SL_mReq_chosen

