Tunnel_Error_Code = technology specific reason why the tunnel is not
                       installed or being removed (values tbd)

num=6). Each of these objects has a c-type defined for carrying various 
type=1) which includes a command-code field to indicate the action to 
