link-info       =  link-info-data
link-info       =/ link-info-data "," 1*info-label
link-info       =/ 1*info-label "," link-info-data
link-info-data  =  "bw=" 1*DIGIT
bandwidth       =  "kbps" / "Mbps" / "kB"
info-label      =  ALPHA / DIGIT

