Pmin = 0, Pmax = 1, Qmin = Qmax = Qclip, the averaged queue length
diffServQMinRateRel = diffServQMinRateAbs * 10,000,000/ifSpeed

diffServQMinRateRel = diffServQMinRateAbs * 10 / ifHighSpeed"
diffServQMinRateAbs = ifSpeed * diffServQMinRateRel/10,000,000

diffServQMinRateAbs = ifHighSpeed * diffServQMinRateRel / 10"
diffServQMaxRateRel = diffServQMaxRateAbs * 10,000,000/ifSpeed

diffServQMaxRateRel = diffServQMaxRateAbs * 10 / ifHighSpeed"
diffServQMaxRateAbs = ifSpeed * diffServQMaxRateRel/10,000,000

diffServQMaxRateAbs = ifHighSpeed * diffServQMaxRateRel / 10"
