name="domainStatuses"> <csvDomain:fName> field SHOULD set the
cksum="BF8E79F6">
cksum="6F2B988F">
type="eppcom:roidType" and isRequired="true".

type="eppcom:clIDType".

type="normalizedString".

type="eppcom:clIDType".

type="eppcom:clIDType".

type="eppcom:clIDType".

type="dateTime".

type="eppcom:trStatusType".

type="positiveInteger".

cksum="06DC1A7E">
cksum="02CC2504">
cksum="AD30F3D6">
cksum="E19349E0">
cksum="6BC9F9E8">
cksum="6BC9F9E8">
type="domain:statusValueType".

cksum="EB8C548E">
cksum="F54AADF6">
cksum="569D4638">
cksum="569D4638">
cksum="AA15CB43">
cksum="1B16F334">
cksum="ADB014A2">
cksum="B3E06C5C">
cksum="71170194">
cksum="10C3EDA8">
isRequired="true".

cksum="120938E3">
cksum="E3408F5E">
cksum="0BA504FC">
cksum="055696AF">
type="host:addrStringType".

cksum="17888F02">
cksum="BF5D53B0">
type="eppcom:minTokenType" and isRequired="true".

cksum="D7F106A5">
cksum="6F2B988F">
type="contact:statusValueType".
cksum="2AAF99D4">
cksum="CBEE0AB6">
type="contact:postalLineType" and isRequired="true".  An
type="contact:ccType".  An OPTIONAL "isLoc" attribute to used
type="contact:optPostalLineType".  An OPTIONAL "isLoc"
type="contact:pcType".  An OPTIONAL "isLoc" attribute to used
cksum="02CC2504">
cksum="9A47B820">
cksum="D0929632">
cksum="AF1479BD">
type="boolean".

type="boolean".

type="boolean". with type="boolean".

type="boolean".

type="boolean".

cksum="89043A90">
cksum="6F2B988F">
type="normalizedString" and isRequired="true".

type="csvRegistrar:statusValueType".

type="positiveInteger".

cksum="06DC1A7E">
cksum="307B87AE">
cksum="D462EAD0">
cksum="757B573A">
type="rdeNNDN:nameState".  See Section 5.6.1.1 for a
cksum="5EDB3FB1">
cksum="FF104E83">
element="rdeDom:registrant" />
uri="urn:ietf:params:xml:ns:rdeDomain-1.0">2</rdeHeader:count>
uri="urn:ietf:params:xml:ns:rdeHost-1.0">1</rdeHeader:count>
uri="urn:ietf:params:xml:ns:rdeContact-1.0">1</rdeHeader:count>
uri="urn:ietf:params:xml:ns:rdeRegistrar-1.0">1
uri="urn:ietf:params:xml:ns:rdeIDN-1.0">1</rdeHeader:count>
uri="urn:ietf:params:xml:ns:rdeNNDN-1.0">1</rdeHeader:count>
uri="urn:ietf:params:xml:ns:rdeEppParams-1.0">1
uri="urn:ietf:params:xml:ns:csvDomain-1.0">2</rdeHeader:count>
uri="urn:ietf:params:xml:ns:csvHost-1.0">1</rdeHeader:count>
uri="urn:ietf:params:xml:ns:csvContact-1.0">1</rdeHeader:count>
uri="urn:ietf:params:xml:ns:csvRegistrar-1.0">1
uri="urn:ietf:params:xml:ns:csvIDN-1.0">1</rdeHeader:count>
uri="urn:ietf:params:xml:ns:csvNNDN-1.0">1</rdeHeader:count>
uri="urn:ietf:params:xml:ns:rdeEppParams-1.0">1
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

schemaLocation="eppcom-1.0.xsd"/>
schemaLocation="rde-1.0.xsd"/>

abstract="true"/>
default="false"/>
default="true"/>
substitutionGroup="rdeCsv:field"/>
default="eppcom\:labelType"/>
default="eppcom\:labelType"/>
substitutionGroup="rdeCsv:field"/>
default="eppcom\:roidType"/>
substitutionGroup="rdeCsv:field"/>
default="eppcom\:clIDType"/>
type="rdeCsv:fNormalizedStringType"
substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
default="eppcom\:clIDType"/>
default="eppcom\:clIDType"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
default="dateTime"/>
default="boolean"/>
default="unsignedByte"/>
default="unsignedShort"/>
default="hexBinary"/>
substitutionGroup="rdeCsv:field"/>
default="language"/>
substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>
default="eppcom\:trStatusType"/>
default="token"/>
default="normalizedString"/>
default="positiveInteger"/>
substitutionGroup="rdeCsv:field"/>
default="token"/>
maxOccurs="unbounded"/>
default="UTF-8"/>
substitutionGroup="rdeCsv:field"/>
default="anyURI"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

type="rdeDomain:abstractContentType"
substitutionGroup="rde:content" abstract="true"/>
substitutionGroup="rdeDomain:abstractDomain"/>
type="rdeDomain:deleteType"
substitutionGroup="rde:delete"/>

type="eppcom:labelType"/>
type="eppcom:roidType"/>
type="eppcom:labelType" minOccurs="0"/>
type="IDREF" minOccurs="0"/>
type="eppcom:labelType" minOccurs="0"/>
type="domain:statusType" maxOccurs="11"/>
type="rgp:statusType" minOccurs="0"
maxOccurs="unbounded"/>
type="eppcom:clIDType" minOccurs="0"/>
type="domain:contactType"
minOccurs="0" maxOccurs="unbounded"/>
type="domain:nsType" minOccurs="0"/>
type="eppcom:clIDType"/>
type="rde:rrType"/>
type="dateTime" minOccurs="0"/>
type="dateTime" minOccurs="0"/>
type="rde:rrType" minOccurs="0"/>
type="dateTime" minOccurs="0"/>
type="secDNS:dsOrKeyType" minOccurs="0"/>
type="dateTime" minOccurs="0"/>
type="rdeDomain:transferDataType"
minOccurs="0"/>
type="eppcom:trStatusType"/>
type="rde:rrType"/>
type="dateTime"/>
type="rde:rrType"/>
type="dateTime"/>
type="dateTime" minOccurs="0"/>
type="eppcom:labelType" minOccurs="0"
maxOccurs="unbounded"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">
schemaLocation="eppcom-1.0.xsd"/>
schemaLocation="domain-1.0.xsd"/>
schemaLocation="secDNS-1.1.xsd"/>
schemaLocation="rgp-1.0.xsd"/>
schemaLocation="rde-1.0.xsd"/>
schemaLocation="rdeCsv-1.0.xsd"/>

substitutionGroup="rde:content"/>

substitutionGroup="rde:delete"/>

substitutionGroup="rdeCsv:field"/>


type="csvDomain:fRgpStatusType"
substitutionGroup="rdeCsv:field"/>
default="rgp\:statusValueType"/>
substitutionGroup="rdeCsv:field"/>

default="domain\:contactAttrType"/>
substitutionGroup="rdeCsv:field"/>
default="secDNS\:maxSigLifeType"/>
substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>
default="secDNS\:keyType"/>
substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

default="domain\:statusValueType"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

substitutionGroup="rde:content" abstract="true"/>
substitutionGroup="rde:delete"/>

type="eppcom:labelType"/>
type="eppcom:roidType"/>
type="host:statusType" maxOccurs="7"/>
type="host:addrType" minOccurs="0"
maxOccurs="unbounded"/>
type="eppcom:clIDType"/>
type="rde:rrType"/>
type="dateTime"/>
type="rde:rrType" minOccurs="0"/>
type="dateTime" minOccurs="0"/>
type="dateTime" minOccurs="0"/>
type="eppcom:labelType"/>
type="eppcom:roidType"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

schemaLocation="eppcom-1.0.xsd"/>
schemaLocation="host-1.0.xsd"/>
schemaLocation="rde-1.0.xsd"/>
schemaLocation="rdeCsv-1.0.xsd"/>

substitutionGroup="rde:content"/>

substitutionGroup="rde:delete"/>

substitutionGroup="rdeCsv:field"/>


substitutionGroup="rdeCsv:field"/>
default="host\:addrStringType"/>
substitutionGroup="rdeCsv:field"/>
default="host\:ipType"/>
substitutionGroup="rdeCsv:field"/>

default="host\:statusValueType"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

type="rdeContact:abstractContentType"
substitutionGroup="rde:content" abstract="true"/>
substitutionGroup="rdeContact:abstractContact"/>
type="rdeContact:deleteType"
substitutionGroup="rde:delete"/>

type="eppcom:clIDType"/>
type="eppcom:roidType"/>
type="contact:statusType" maxOccurs="7"/>
type="contact:postalInfoType" maxOccurs="2"/>
type="contact:e164Type" minOccurs="0"/>
type="contact:e164Type" minOccurs="0"/>
type="eppcom:minTokenType"/>
type="eppcom:clIDType"/>
type="rde:rrType"/>
type="dateTime"/>
type="rde:rrType" minOccurs="0"/>
type="dateTime" minOccurs="0"/>
type="dateTime" minOccurs="0"/>
type="rdeContact:transferDataType" minOccurs="0"/>
type="contact:discloseType" minOccurs="0"/>
type="eppcom:clIDType" minOccurs="0"
maxOccurs="unbounded"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

schemaLocation="eppcom-1.0.xsd"/>
schemaLocation="contact-1.0.xsd"/>
schemaLocation="rde-1.0.xsd"/>
schemaLocation="rdeCsv-1.0.xsd"/>

substitutionGroup="rde:content"/>
substitutionGroup="rde:delete"/>

substitutionGroup="rdeCsv:field"/>
default="eppcom\:clIDType"/>
type="rdeCsv:fBooleanType"
substitutionGroup="rdeCsv:field"/>


substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
default="contact\:e164StringType"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>
default="eppcom\:minTokenType"/>
substitutionGroup="rdeCsv:field"/>
default="contact\:postalInfoEnumType"/>
default="contact\:postalLineType"/>
default="contact\:optPostalLineType"/>
substitutionGroup="rdeCsv:field"/>


substitutionGroup="rdeCsv:field"/>


substitutionGroup="rdeCsv:field"/>
use="required"/>
substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>
default="contact\:pcType"/>
substitutionGroup="rdeCsv:field"/>
default="contact\:ccType"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
default="boolean"/>
substitutionGroup="rdeCsv:field"/>

default="contact\:statusValueType"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

type="rdeRegistrar:abstractContentType"
substitutionGroup="rde:content" abstract="true"/>
substitutionGroup="rdeRegistrar:abstractRegistrar"/>
substitutionGroup="rde:delete"/>

type="eppcom:clIDType"/>
type="rdeRegistrar:nameType"/>
type="positiveInteger" minOccurs="0"/>
type="rdeRegistrar:statusType"/>
type="rdeRegistrar:postalInfoType"
maxOccurs="2"/>
type="contact:e164Type" minOccurs="0"/>
type="contact:e164Type" minOccurs="0"/>
type="eppcom:minTokenType"/>
type="anyURI" minOccurs="0"/>
type="rdeRegistrar:whoisInfoType" minOccurs="0"/>
type="dateTime"/>
type="dateTime" minOccurs="0"/>
type="rdeRegistrar:addrType" />
type="rdeRegistrar:postalInfoEnumType"
use="required" />
type="rdeRegistrar:optPostalLineType"
minOccurs="0" maxOccurs="3" />
type="rdeRegistrar:postalLineType" />
type="rdeRegistrar:optPostalLineType"
minOccurs="0" />
type="rdeRegistrar:pcType" minOccurs="0" />
type="rdeRegistrar:ccType" />
type="eppcom:labelType" minOccurs="0"/>
type="anyURI" minOccurs="0"/>
type="eppcom:clIDType" minOccurs="0"
maxOccurs="unbounded"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

schemaLocation="eppcom-1.0.xsd"/>
schemaLocation="domain-1.0.xsd"/>
schemaLocation="contact-1.0.xsd"/>
schemaLocation="rde-1.0.xsd"/>
schemaLocation="rdeCsv-1.0.xsd"/>

substitutionGroup="rde:content"/>

substitutionGroup="rde:delete"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

default="normalizedString"/>
type="rdeCsv:fPositiveIntegerType"
substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
default="csvRegistrar\:statusType"/>
type="rdeCsv:anyURIType"
substitutionGroup="rdeCsv:field"/>


xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

substitutionGroup="rde:content"/>

xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

schemaLocation="rde-1.0.xsd"/>
schemaLocation="rdeCsv-1.0.xsd"/>

substitutionGroup="rde:content"/>

substitutionGroup="rde:delete"/>

xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

substitutionGroup="rdeEppParams:abstractEppParams"/>

type="rdeEppParams:abstractContentType"
substitutionGroup="rde:content" abstract="true"/>
maxOccurs="unbounded"/>
type="language" maxOccurs="unbounded"/>
type="anyURI" maxOccurs="unbounded"/>
type="epp:extURIType"
minOccurs="0"/>
type="epp:dcpType"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

substitutionGroup="rde:content" abstract="true"/>
substitutionGroup="rde:delete"/>

type="eppcom:labelType"/>
type="eppcom:labelType" minOccurs="0"/>
type="IDREF" minOccurs="0"/>
type="eppcom:labelType" minOccurs="0"/>
type="rdeNNDN:nameState"/>
type="dateTime"/>
type="boolean" default="true"/>
type="eppcom:labelType" minOccurs="0"
maxOccurs="unbounded"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

schemaLocation="rde-1.0.xsd"/>
schemaLocation="rdeCsv-1.0.xsd"/>
schemaLocation="rde-nndn-1.0.xsd"/>

substitutionGroup="rde:content"/>

substitutionGroup="rde:delete"/>

substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>

type="csvNNDN:fNameStateType"
substitutionGroup="rdeCsv:field"/>
default="rdeNNDN\:nameState"/>
type="rdeCsv:fBooleanType"
substitutionGroup="rdeCsv:field"/>

xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

substitutionGroup="rde:content"/>

xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

substitutionGroup="rde:content"/>

maxOccurs="unbounded"/>
uri="urn:ietf:params:xml:ns:rdeDomain-1.0">2
uri="urn:ietf:params:xml:ns:rdeHost-1.0">1
uri="urn:ietf:params:xml:ns:rdeContact-1.0">1
uri="urn:ietf:params:xml:ns:rdeRegistrar-1.0">1
uri="urn:ietf:params:xml:ns:rdeIDN-1.0">1
uri="urn:ietf:params:xml:ns:rdeNNDN-1.0">1
uri="urn:ietf:params:xml:ns:rdeEppParams-1.0">1
scope="//rde:deposit/rde:contents/rdeDomain:domain"
element="rdeDom:registrant" />
uri="urn:ietf:params:xml:ns:rdeDomain-1.0">1
uri="urn:ietf:params:xml:ns:rdeHost-1.0">1
uri="urn:ietf:params:xml:ns:rdeContact-1.0">1
uri="urn:ietf:params:xml:ns:rdeRegistrar-1.0">1
uri="urn:ietf:params:xml:ns:rdeIDN-1.0">1
uri="urn:ietf:params:xml:ns:rdeNNDN-1.0">1
uri="urn:ietf:params:xml:ns:rdeEppParams-1.0">1
type="FULL"
id="20101017001" prevId="20101010001">
cksum="E6D52D73">
cksum="70A7C17B">
cksum="EB8C548E">
cksum="546C66A5">
cksum="AA15CB43">
cksum="1B16F334">
cksum="71170194">
cksum="120938E3">
cksum="0BA504FC">
cksum="17888F02">
cksum="D7F106A5">
cksum="2AAF99D4">
cksum="02CC2504">
cksum="D0929632">
cksum="89043A90">
cksum="9CB43C2E">
cksum="D462EAD0">
cksum="01F72976">
type="FULL"
id="20101017001" prevId="20101010001">
cksum="E19349E0">
cksum="6BC9F9E8">
cksum="F54AADF6">
cksum="546C66A5">
cksum="ADB014A2">
cksum="B3E06C5C">
cksum="10C3EDA8">
cksum="E3408F5E">
cksum="055696AF">
cksum="BF5D53B0">
cksum="6F2B988F">
cksum="CBEE0AB6">
cksum="6F2B988F">
cksum="AF1479BD">
cksum="6F2B988F">
cksum="307B87AE">
cksum="757B573A">
cksum="6C253927">
cksum="E6D52D73">
cksum="70A7C17B">
cksum="EB8C548E">
cksum="546C66A5">
cksum="AA15CB43">
cksum="71170194">
cksum="120938E3">
cksum="0BA504FC">
cksum="17888F02">
cksum="D7F106A5">
cksum="2AAF99D4">
cksum="02CC2504">
cksum="D0929632">
cksum="89043A90">
cksum="9CB43C2E">
cksum="D462EAD0">
cksum="01F72976">
