NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
Name="urn:ietf:params:xml:ns:oli">
NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
Name="urn:ietf:params:xml:ns:cpc">
content="text/html;charset=iso-8859-1"/>
content="text/html;charset=iso-8859-1"/>
