rRK = prf+ (K, S), where,

K = EMSK or K = DSRK and

S = rRK Label + "\0" + NULL + length

rRKname = SHA-256-64 (NameDerivationKey, rRK Label)

NameDerivationKey = EAP Session-ID, when K used in rRK derivation is
NameDerivationKey = DSRK Name, when K used in rRK derivation is the
rIK = prf+ (K, S ) where,

K = rRK and

S = rIK Label + "\0" + cryptosuite + length

rIKname = SHA256-64(rRKname, rIK Label)

rMSK = prf+ (K, S ) where,

K = rRK and

S = rMSK label + "\0" + SEQ + length

rMSK_name = HMAC-SHA256-64 (rMSK, "rMSK Name")

Type = 1.

Type = 2.

Type = 2.

