hashparam = "HASH" "="    /
                       DQUOTE hashval "," hashname DQUOTE
hashval = *QSAFE-CHAR
hashname = *QSAFE-CHAR
groupparam   = "GROUP" "=" paramtext *("," paramtext)

loctypeparam   = "LOCTYPE" "=" param-value

assoctypeparam   = "ASSOCTYPE" "=" param-value

restypeparam   = "RESTYPE" "=" param-value

orderparam    = "ORDER" "=" integer ;Must be in the range [1..100]
labelparam     = "LABEL" "=" DQUOTE text DQUOTE

associate     = "ASSOCIATE" assocparam
                       (
                         ";" "VALUE" "=" "URI"
                         ":" uri)  /
                       (
                         ";" "VALUE" "=" "TEXT"
                         ":" text
                       )
                       CRLF

assocparam      = *(

                     ; the following are OPTIONAL
                     ; but MUST NOT occur more than once

                     (";" fmttypeparam) /
                     (";" labelparam) /
                     (";" orderparam) /
                     (";" assoctypeparam) /
                     (";" groupparam) /

                     ; the following is OPTIONAL
                     ; and MAY occur more than once

                     (";" other-param)

                     )


ASSOCTYPE=PRIMARY-CONTACT;LABEL=A contact:
ASSOCTYPE=PLANNER-CONTACT;LABEL=ClownsIsUs:
VALUE=TEXT is used to provide rich-text variants of the plain-text
VALUE=URI is used to provide a link to rich-text content which is
styleddescription = "STYLED-DESCRIPTION" styleddescparam ":"
                       (
                         ";" "VALUE" "=" "URI"
                         ":" uri)  /
                       (
                       (
                         ";" "VALUE" "=" "TEXT"
                         ":" text
                       )
                       CRLF

styleddescparam   = *(
                    ;
                    ; The following are OPTIONAL,
                    ; but MUST NOT occur more than once.
                    ;
                    (";" altrepparam) / (";" languageparam) /
                    (";" fmttypeparam) / (";" hashparam) /
                    (";" groupparam) /

                    ; the following is OPTIONAL
                    ; and MAY occur more than once

                    (";" other-param)


strucloc        = "STRUCTURED-LOCATION" struclocparam
                       (
                         ";" "VALUE" "=" "URI"
                         ":" uri)  /
                       (
                       (
                         ";" "VALUE" "=" "TEXT"
                         ":" text
                       )
                       CRLF

struclocparam   = *(

                     ; the following are OPTIONAL
                     ; but MUST NOT occur more than once

                     (";" fmttypeparam) /
                     (";" labelparam) /
                     (";" languageparam) /
                     (";" loctypeparam) /
                     (";" groupparam) /

                     ; the following is OPTIONAL
                     ; and MAY occur more than once

                     (";" other-param)

                     )
strucres       = "STRUCTURED-LOCATION" strucresparam (":" uri)  /
                       (
                         ";" "VALUE" "=" "TEXT"
                         ":" text
                       )
                       CRLF

strucresparam  = *(

                     ; the following are OPTIONAL
                     ; but MUST NOT occur more than once

                     (";" fmttypeparam) /
                     (";" labelparam) /
                     (";" languageparam) /
                     (";" restypeparam) /
                     (";" groupparam) /

                     ; the following is OPTIONAL
                     ; and MAY occur more than once

                     (";" other-param)

                     )


