OS = Outbound Stream
MIS = Maximal Inbound Stream

OS = Outbound Stream
MIS = Maximal Inbound Stream




Port = a)
            <-------------------      INIT-ACK

   COOKIE    ------------------->

             <-------------------     COOKIE-ACK 
                                              ------------->  
                                                     Communication up
   INIT      ------------------->
Port = b)
             <------------------      ABORT

Port = a)
              <----------------      COOKIE 

   COOKIE-ACK ----------------->
                                             -------------->
                                                     Communication Up
   DATA       ----------------->
OS= Outbound Stream
MIS= Minimum Inbound Stream







rwnd =0 is sent in SACK in  response to DATA  message. Data should be
a_rwnd=0 ]
                                                    <-------   Send
                <-------------             DATA [TSN=2]
                                 (one data packet in flight)
     SACK       --------------> 
rwnd =0 is sent in SACK in  response to DATA  message. Data should be
a_rwnd=0 ]                                         <-------   Send
                         Data cant be transmitted as a_rwnd=0
                         but it will be accepted from user part 

                                                    <--------   Send
    SACK         ------------->
rwnd=0 is received from endpoint A 
cwnd=Un Avk Data Size
                                                |
                                                |No data transfer
                                                |because of cwnd
                                                |
                                                |     <-------   Send
                                                |
Strt=2,End=2]
                                                     <--------   Send  
                                            (Remove 2 and 4 from out
                                            -queue and strike 3 as
                                             "1" missing   report )
                 <----------------            DATA [  TSN=3] 
 
                 <----------------            DATA [  TSN=5]

Strt=2,End=2]

