kvsep          = %x01
key            = 1*ALPHA
value          = *(VCHAR | SP | HTAB | CR | LF )
kvpair         = key "=" value kvsep
client_resp    = 1*kvpair kvsep

host=server.example.com^A
port=143^A
auth=MAC token="h480djs93hd8",timestamp="137131200",nonce="dj83hs9s",
signature="YTVjyNSujYs1WsDurFnvFi4JK6o="^A^A

yOXRDZz09AQE=
host=server.example.com^Aport=143^A
auth=BEARER "vF9dft4qmTc2Nvb3RlckBhbHRhdmlzdGEuY29tCg=="^A^A

bz0BAQ==
host=server.example.com^A
port=143^A
auth=MAC token="h480djs93hd8",timestamp="137131200",nonce="dj83hs9s",
signature="YTVjyNSujYs1WsDurFnvFi4JK6o="^A
cbdata=SG93IGJpZyBpcyBhIFRMUyBmaW5hbCBtZXNzYWdlPwo=^A^A

MBYXV0aD0BAQ==
host=server.example.com^Aport=143^Aauth=^A^A

host=server.example.com^Aport=143^Aauth=^Acbdata=^A^A

