elementFormDefault="qualified"
attributeFormDefault="unqualified">

maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
type="xs:nonNegativeInteger"
use="required"/>
use="required"/>
entity="sip:ur351f@nj.cars.gov"
state="full"
version="1" >
entity="sip:ur351f@nj.cars.gov">presence vehicleinfo</member>
entity="sip:alice@example.com">presence</member>
entity="sip:bob@example.com">presence foo</member>
entity="pres:piotr@anotherexample.com">presence </member>
entity="sip:carol@example.com">presence foobar</member>
entity="sip:ur351f@nj.cars.gov"
state="full"
version="1" >
entity="sip:ur351f@nj.cars.gov">
                                presence vehicle-info</member>
entity="sip:alice@example.com">presence</member>
entity="sip:bob@example.com">presence foo</member>
entity="pres:piotr@anotherexample.com">presence </member>
entity="sip:carol@example.com">presence foobar</member>
