NK = no key type (flags bits 0 and 1 on)
AL = algorithm byte
PR = protocols indicated by protocol byte or future assigned flags

labels= |  0  |   1  |    2   |      3   |      4   |
data = RDATA | RR(s)...

data = full response (less transaction SIG) | full query

NOCONF    =1 confidentiality use prohibited
NOAUTH    =2 authentication use prohibited
NOKEY     =3 no key present
USER      =0 (default, may be omitted)
ZONE      =1
HOST      =2 (host or other end entity)
