M =
N =
M =
N =
M =
N =
h = SHA256.new(h).digest()      return h

pointstr = ec.canon_pointstr(bighash(seed, i, ec.nbytes_point()))
            try:              p = ec.decode_point(pointstr)             
