svc=abc;pn-app-id=1234.com.sipua.application;pn-
token=abcdef1234567890

Uri-parameter = / pn-svc / pn-app-id / pn-token

pn-svc = "pn-svc" EQUAL pvalue

pn-app-id = "pn-app-id" EQUAL pvalue

pn-token = "pn-token" EQUAL pvalue

