Opcode = 16it          |Opcode = 16Bit          |
                        |                        |Length = 32Bit
Flags = 32Bit          |Flags = 32Bit
                        |
Number = 'NSID' = 16Bit| System Server to Secure IPtX DHCP Services}*
