name="cn=Bjorn Jensen, o=University of Michigan, c=US";
source="ldap";
name="cn=Bjorn Jensen, o=University of Michigan, c=US";
source="x500";
name="myvoice.au";
site="myhost.com";
access-type=ANON-FTP;
directory="pub/myname";
mode="image"

