grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Asaml2-bearer&
assertion=PHNhbWxwOl...[omitted for brevity]...ZT4

grant_type=authorization_code&
code=i1WsRn1uB1&
client_assertion_type=urn%3Aietf%3Aparams%3Aoauth
client_assertion=PHNhbW...[omitted for brevity]...ZT

grant_type=client_credentials&
client_assertion_type=urn%3Aietf%3Aparams%3Aoauth
client_assertion=PHNhbW...[omitted for brevity]...ZT

