xmlns="urn:ietf:params:xml:ns:yang:ietf-te-topology">
xmlns=
xmlns=
xmlns=
xmlns=
xmlns= "urn:ietf:params:xml:ns:yang:ietf-te-topology"
xmlns=
xmlns=
xmlns=
xmlns=
xmlns=
xmlns=
xmlns=
xmlns=
xmlns=
xmlns=
xmlns=
xmlns="urn:ietf:params:xml:ns:yang:ietf-network-topology">
xmlns="urn:ietf:params:xml:ns:yang:ietf-network-topology">
xmlns=
xmlns=
xmlns="urn:ietf:params:xml:ns:yang:ietf-network-instance">
xmlns=
