rules = [general] [per-chunk]
general = conditions
per-chunk = conditions
conditions = condition [log-operator conditions] / "(" conditions ")"
log-operator = "and" / "or"
condition = variable operator value / variable operator variable
operator = "=" / "!=" / "<" / "<=" / ">" / ">="
variable = 1ALPHA *99(ALPHA / DIGIT)
value = 1*10DIGIT / 1*10DIGIT "." DIGIT /"'" 1*10ALPHA "'"

ReqService = ["(" assignment ")"] ["," ReqService]
assignment = variable "," value
variable = 1ALPHA *99(ALPHA / DIGIT)
value = 1*10DIGIT / 1*10DIGIT "." DIGIT / "'" 1*10ALPHA "'"

master_secret = PRF(Sab, "master secret",
                       Na || Nb)
                       [0..47];

key_block = PRF(master secret,
                   "key expansion",
                   Na || Nb);

SP = [ORIGIN] [CREATION_DATE] [ECS_VERSION] [SWARM_KEY_TYPE]
        SWARM_KEYS [HANDSHAKE_SIGNATURE_TYPE] [ADCP_ALGORITHM]
ORIGIN = http_URL ; see [RFC2616]
CREATION_DATE = UTCTime ; see [RFC5280]
ECS_VERSION = OCTET
SWARM_KEY_TYPE = OCTET
SWARM_KEYS = key [SWARM_KEYS]
HANDSHAKE_SIGNATURE_TYPE = OCTET
PoA_SIGNATURE_TYPE = OCTET
ADCP_ALGORITHM = OCTET
key = *OCTET ; see Section 4.7.2.1

ECS_VERSION = 0x01
SWARM_KEY_TYPE = 0x01
SWARM_KEYS = key
HANDSHAKE_SIGNATURE_TYPE = 0x01
PoA_SIGNATURE_TYPE = 0x01
ADCP_ALGORITHM = 0x01


ECS_PROTOCOL = 0x0B
ECS_ENCRYPTED = 0x0C

ECS_SWARM_ID = 0x01
ECS_VERSION = 0x02
ECS_NONCE = 0x03
ECS_POA = 0x04
ECS_REQUESTED_SERVICE = 0x05
ECS_SHARED_SECRET = 0x06
ECS_ERROR_INFO = 0x07
ECS_SIGNATURE = 0x08

A = L || SQ || C

