Remote-Party-ID = "Remote-Party-ID" ":" [display-name]" <"addr- 
                       spec">" *(";" rpi-token) 
rpi-token =       rpi-screen | rpi-pty-type | rpi-id-type | rpi-
                       privacy | rpi-redirect | other-rpi-token | 
rpi-screen =      "screen" "=" ("no" | "yes" ) 
rpi-pty-type =    "party" "=" ( "calling" | "called" | 
                       "redirecting" | "redirected-to" | token ) 
rpi-id-type  =    "id-type" "=" ( "subscriber" | "user" |"alias" | 
                       "return" | "term"  | token ) 
rpi-privacy  =    "privacy" "=" 1#(("full" | "name" | "uri" | 
                       "off" | token ) [ "-" ( "network" | token ) ]  ) 
other-rpi-token = token ["-"] ["=" (token | quoted-string)] 
rpi-redirect =    "redirect" "=" rpi-rd-count ["," rpi-rd-reason] 
      
rpi-id-count =     1*DIGIT 
rpi-rd-reason =   "busy" | "noAnswer" | "unconditional" | token |     
                        quoted-string 
      
      
      
v=0 
o=UserA 2890844526 2890844526 IN IP4 client.here.com 
s=Session SDP 
c=IN IP4 100.101.102.103 
t=0 0 
m=audio 49170 RTP/AVP 0 
a=rtpmap:0 PCMU/8000 
 
v=0 
o=UserA 2890844526 2890844526 IN IP4 client.here.com 
s=Session SDP 
c=IN IP4 100.101.102.103 
t=0 0 
m=audio 49170 RTP/AVP 0 
a=rtpmap:0 PCMU/8000 
    
screen=yes; party=redirecting; id-type=alias;  
redirect=1,busy  
v=0 
o=UserA 2890844526 2890844526 IN IP4 client.here.com 
s=Session SDP 
c=IN IP4 100.101.102.103 
t=0 0 
m=audio 49170 RTP/AVP 0 
a=rtpmap:0 PCMU/8000 
 
party=redirected-to; id-type=subscriber; 
redirect=1,busy  
v=0 
o=UserB 2890844527 2890844527 IN IP4  
s=Session SDP 
c=IN IP4 110.111.112.114 
t=0 0 
m=audio 3456 RTP/AVP 0 
a=rtpmap:0 PCMU/8000 
 
 
v=0 
o=UserB 2890844527 2890844527 IN IP4  
s=Session SDP 
c=IN IP4 110.111.112.114 
    
t=0 0 
m=audio 3456 RTP/AVP 0 
a=rtpmap:0 PCMU/8000 
                  
 
v=0 
o=UserA 2890844526 2890844526 IN IP4 client.here.com 
s=Session SDP 
c=IN IP4 100.101.102.103 
t=0 0 
m=audio 49170 RTP/AVP 0 
a=rtpmap:0 PCMU/8000 
 
v=0 
o=UserA 2890844526 2890844526 IN IP4 client.here.com 
s=Session SDP 
    
c=IN IP4 100.101.102.103 
t=0 0 
m=audio 49170 RTP/AVP 0 
a=rtpmap:0 PCMU/8000 
 
party=redirected-to; id-type=alias; 
redirect=1,busy  
screen=yes; party=redirecting; id-type=alias; 
redirect=1,busy 
v=0 
o=UserA 2890844526 2890844526 IN IP4 client.here.com 
s=Session SDP 
c=IN IP4 100.101.102.103 
t=0 0 
m=audio 49170 RTP/AVP 0 
a=rtpmap:0 PCMU/8000 
 
party=redirected-to; id-type=subscriber; 
redirect=2,noAnswer  
party=redirecting; id-type=alias; redirect=1,busy 
party=redirecting; id-type=alias; redirect=2,noAnswer 
v=0 
o=UserA 2890844526 2890844526 IN IP4 client.here.com 
s=Session SDP 
c=IN IP4 100.101.102.103 
t=0 0 
m=audio 49170 RTP/AVP 0 
a=rtpmap:0 PCMU/8000 
  
v=0 
o=UserB 2890844527 2890844527 IN IP4  
s=Session SDP 
c=IN IP4 110.111.112.114 
t=0 0 
m=audio 3456 RTP/AVP 0 
a=rtpmap:0 PCMU/8000 
 
 
v=0 
o=UserB 2890844527 2890844527 IN IP4  
s=Session SDP 
c=IN IP4 110.111.112.114 
t=0 0 
m=audio 3456 RTP/AVP 0 
a=rtpmap:0 PCMU/8000 
 
