Type=EAP-FAST and the Start (S) bit set. The EAP-FAST/Start packet 
EAP-Type=EAP-FAST. The data field of this packet will encapsulate 
master_secret = T-PRF(PAC-Key, "PAC to master secret label hash", 
key_block  = PRF(master_secret, "key expansion", server_random + 
S-IMCK = SKS 
          0
MSK = T-PRF(S-IMCKn, "Session Key Generating Function", 
TLS_DH_anon_WITH_AES_128_CBC_SHA   = { 0x00, 0x34} 
TLS_DHE_RSA_WITH_AES_128_CBC_SHA   = { 0x00, 0x33} 
  
CipherSuite =  TLS_DH_anon_WITH_AES_128_CBC_SHA  (per [RFC 3268]) 
Random = 32 octet server generated random value (client_random) 
     
CipherSuite =  TLS_DH_anon_WITH_AES_128_CBC_SHA  (per [RFC 3268]) 

  
  
  
  
Random = 32 octet server generated random value (server_random) 
     
KeyExchangeAlgorithm = diffie_hellman 
ServerDHParams = {dh_p, dh_g, dh_Ys} 
     
p = 2q + 1 and q is prime 
     
pre_master_secret = (DH_Ys)^peer-private-DH-key mod DH_p    for the 
pre_master_secret = (DH_Yc)^server-private-DH-key mod DH_p    for 
master_secret = PRF(pre_master_secret, ômaster secretö, 
key_block = PRF(master_secret, 
                              "key expansion", 
                              server_random + 
                              client_random); 
     
Type=EAP-FAST and no data. This serves as a fragment ACK. The EAP 
L = Length included 
M = More fragments 
S = EAP-FAST start 
R = Reserved (must be zero) 
  
R = Reserved (must be zero) 
  
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 -> 
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 -> 
Binding-TLV=(Version=0,SNonce, 
Binging-TLV=(Version=0,  
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 -> 
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 -> 
Binding-TLV=(Version=0,SNonce, 
Binging-TLV=(Version=0,  
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 -> 
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 -> 
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 -> 
Binding-TLV=(Version=0,SNonce, 
Binging-TLV=(Version=0,  
EAP-Type=EAP-FAST, V=1 
  
  
  
  
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 
EAP-Type=EAP-FAST, V=1 -> 
T1 = HMAC-SHA1 (Key, S + OutputLength + 0x01) 
T2 = HMAC-SHA1 (Key, T1 + S + OutputLength + 0x02) 
T3 = HMAC-SHA1 (Key, T2 + S + OutputLength + 0x03) 
T4 = HMAC-SHA1 (Key, T3 + S + OutputLength + 0x04) 
     
Master_secret = T-PRF(PAC-Key,  
                     "PAC to master secret label hash", 
                          server_random + Client_random,  
                          48) 
     
Key_block  = PRF(Master_secret,  
                "key expansion", 
                      server_random + Client_random) 
     
IMCK = T-PRF(SKS,  
                 "Inner Methods Compound Keys",  
                 ISK,  
                 60) 
     
           Note: ISK is 32 bytes 0's. 
     
MSK = T-PRF(S-IMCKn,  
                "Session Key Generating Function", 
                 64); 
     
