n = Used to specify the frequency as 193.1THz +/- n*(channel spacing) 
WI =|     |,  WE =|     | 
              | 1 1 |       | 0 1 | 
              +-----+       +-----+ 
    
    
                    +-----------+                      +------+ 
                    |           |--------------------->|      | 
                    |           |--------------------->|  C   | 
              /|    |           |--------------------->|  o   | E1 
