targetNamespace="urn:ietf:params:xml:ns:econ1"
elementFormDefault="qualified" >

namespace="urn:ietf:params:xml:ns:iris1" />
namespace="urn:ietf:params:xml:ns:pidf:geopriv10:civilLoc" />
namespace="http://www.opengis.net/gml" />

type="civilLoc:civilAddress"/>
type="econ:serviceType" minOccurs="0"/>
default="false" />
type="econ:findEconByCivicType"
substitutionGroup="iris:query" />

ref="gml:location"/>
type="econ:serviceType" minOccurs="0"/>
default="false" />
type="econ:findEconByGeoType"
substitutionGroup="iris:query" />

name="serviceType">
base="string">
type="normalizedString" minOccurs="0" />
type="anyURI"
minOccurs="1" maxOccurs="unbounded" />
type="econ:emergencyContactType"
substitutionGroup="iris:result" />

type="iris:codeType"
substitutionGroup="iris:genericCode" />

type="iris:codeType"
substitutionGroup="iris:genericCode" />

