PSAP-URI          = "PSAP-URI " HCOLON PSAP-URI-value *(COMMA 
                                PSAP-URI-value)
PSAP-URI-value    = (absoluteURI / option-tag)
option-tag        =  string
service-id        =  string

   NOTE: we aren't sure this BNF is correct.  The goal is to get this 
         Result as a Request:

   PSAP-URI: <psap-uri; service-id=primary>, 
             <psap-uri; service-id=secondary>,
             <psap-uri; service-id=police>,
             <psap-uri; service-id=fire>

   And this result in a Response:

   PSAP-URI: <sip:psap1.colleyville.tarrant.tx.us.sos.arpa; 
service-id=primary> 


service-id=primary> 
