pn-provider=acme;
pn-param=acme-param;
pn-prid=ZTY4ZDJlMzODE1NmUgKi0K>
pns-fc          = "+sip.pns" EQUAL LDQUOT pns-list RDQUOT
pns-list        = pns *(COMMA pns)
pns             = tag-value

vapid-fc          = "+sip.vapid" EQUAL LDQUOT vapid RDQUOT
vapid             = tag-value

pns-fc          = "+sip.pnsreg" EQUAL LDQUOT reg RDQUOT
reg             = 1*DIGIT

pns-mt          = "+sip.pnsreg"
uri-parameter   =/ pn-provider / pn-param / pn-prid
pn-provider     = "pn-provider" EQUAL pvalue
pn-param        = "pn-param" EQUAL pvalue
pn-prid         = "pn-prid" EQUAL pvalue

