targetNamespace="http://www.w3.org/2001/04/xmldsig-more#"
elementFormDefault="qualified" attributeFormDefault="unqualified"
version="0.2">

type="gost:GOST3410-94-KeyValueType"/>
type="gost:GOST3410-2001-KeyValueType"/>

type="gost:GostR3410_94_PublicKeyParametersType"
minOccurs="0"/>
type="gost:GostR3410_2001_PublicKeyParametersType"
minOccurs="0"/>
type="GostR3410_94_PublicKeyParametersType"/>
type="GostR3410_2001_PublicKeyParametersType"/>
type="gost:OBJECT-IDENTIFIER"/>
type="gost:OBJECT-IDENTIFIER"/>
type="gost:OBJECT-IDENTIFIER"
minOccurs="0"/>
type="gost:OBJECT-IDENTIFIER"/>
type="gost:OBJECT-IDENTIFIER"/>
type="gost:OBJECT-IDENTIFIER"
minOccurs="0"/>
targetNamespace="http://www.w3.org/2001/04/xmldsig-more#"
elementFormDefault="qualified" attributeFormDefault="unqualified"
version="0.2">

type="gost:GostR3410_94_PublicKeyParametersType"
minOccurs="0"/>
type="gost:GostR3410_2001_PublicKeyParametersType"
minOccurs="0"/>
type="gost:OBJECT-IDENTIFIER"/>
type="gost:OBJECT-IDENTIFIER"/>
type="gost:OBJECT-IDENTIFIER"
minOccurs="0"/>
type="gost:OBJECT-IDENTIFIER"/>
type="gost:OBJECT-IDENTIFIER"/>
type="gost:OBJECT-IDENTIFIER"
minOccurs="0"/>
