template-type = slp

template-version = 1.0

template-description =
      This template is designed to enable a UA to discover the URLs
      and scopes of all DAs and SAs in a domain by using a unicast
      SrvRqst with service type as "service:slp".

template-url-syntax =
      ; No additional URL information is required. An example service
      ; URL for the SLP service is: service:slp://myda.mydomain:427

server-type = STRING L
scope = STRING L
      # The serving scopes of this server

