xmlns="urn:ietf:params:xml:ns:pidf:geopriv10:civicAddr"
CAType=XX Value="cdc=http://www.central.devon.canals.org/ns1.0"
CAType=XX value="ap="http://www.example.com/airport/5.0"
CAType=YY Value="cdc:bridge=21451338"
CAType=YY Value="cdc:pylonCount=2"
CAType=YY value="ap:airport=LAX"
CAType=YY value="ap:terminal=Tom Bradley"
CAType=YY value="ap:concourse=G"
CAType=YY value="ap:gate=36B"

        Figure 2: DHCP Example Conveying Muiptle Namespace Elements


