NAME = client-generated globally unique domain name string
            (see [TKEY])
Inception           = as appropriate - see [TKEY]
Expire              = as appropriate - see [TKEY]
Mode                = 3 (GSS-API negotiation - see [TKEY])
Key                 = output_token

NAME = key_name that identifies this context
Expire         = as appropriate - see [TSIG]
Signature      = zeroed prior to signature generation

