Ss = Sender reference point at the DWDM network element
        tributary output, this can be a set of multiple transceivers
        carrying the same client payload.
Rs = Receiver reference point at the DWDM network element
        tributary input this can be a set of multiple transceivers
        carrying the same client payload.

