response-data-nocrlf   = "*" SP (resp-cond-state / resp-cond-bye /
                  mailbox-data / message-data / capability-data)

seqnumpart = "(" number ")" 
                    ; See [IMAP4] for definition of "number"

iresponse = response-data-nocrlf SP seqnumpart

response = iresponse CRLF

