RnMD =    --- *  >  TstampRecv[i] - TstampSrc[i]
                     J[n]  /
                           ---
i = 1

GMD =  - *   >   RnMD
                                   N    /
                                        ---
n = 1

Type-P-One-to-group-Range-Mean-Delay = GRMD = max(RnMD) - min(RnMD)

Type-P-One-to-group-Max-Mean-Delay = GMMD = max(RnMD)

RnLR =  - *   >   RnLk
                                     K    /
                                          ---
k = 1

k=1
RnCLR =  -----------------------------
                              /    K         \
                              |   ---        |
                              |   \          |
                      K - Min |    >   Ln(k) |
                              |   /          |
                              |   ---        |
                              \   k=1        / N


GLR = --- *   >   Ln(k)
                                  K*N    /
                                         ---
                                        k,n = 1

Type-P-One-to-group-Range-Loss-Ratio = max(RnLR) - min(RnLR)

Type-P-One-to-group-Range-Delay-Variation = GRDV =

