Behaviour = [
       + {
conditions => [ * Condition],
directives => [ * Directive]
Behaviour = [ * (Condition/Directive) ]

rc = SUCCESS
rc = SUCCESS
rc = Process_Data($processing_step, $data)
rc = Compare $device_identity to $parameters
rc = Compare $component to $image_identifier;
rc = Check Response
rc = do_commands($sequence, $Document[$sequence]);
rc = do_commands($sequence, $Document[$sequence]);
