xmlns="urn:ietf:params:xml:ns:lost1"
serviceBoundary="value"
recursive="true">
xmlns="urn:ietf:params:xml:ns:lost1"
serviceBoundary="value"
recursive="true"
limit="20">
expires="2007-01-01T01:44:33Z"
lastUpdated="2006-11-01T01:00:00Z"
source="authoritative.example"
sourceId="7e3f40b098c711dbb6060800200c9a66">
expires="2007-01-01T01:44:33Z"
lastUpdated="2006-11-01T01:00:00Z"
source="authoritative.example"
sourceId="7e3f40b098c711dbb6060800200c9b356">
