SORT=MODSEQ extension makes the following additions to the SORT extension:

        a) extends syntax of untagged SORT responses to include mod-sequence
           (see section 3.2)

        b) adds a new MODSEQ sort criterion (see section 3.1)

capability          =/ "SORT=MODSEQ"

search-key          =/ search-modsequence
                           ;; modifies original IMAP4 search-key
                           ;;
                           ;; This change applies to all command referencing
                           ;; this non-terminal, in particular SORT.
sort-key            =/ "MODSEQ"

mailbox-data        =/ "SORT" [1*(SP nz-number) SP search-sort-mod-seq]


