av-pairs    =     av-pair *(";" av-pair)
av-pair     =     attr ["=" value] ; optional value
attr        =     token
value       =     token | quoted-string

Age=0.

set-cookie      =       "Set-Cookie2:" cookies
cookies         =       1#cookie
cookie          =       NAME "=" VALUE *(";" set-cookie-av)
NAME            =       attr
VALUE           =       value
set-cookie-av   =       "Comment" "=" value
                      |       "CommentURL" "=" <"> http_URL <">
                      |       "Discard"
                      |       "SubDomain"
                      |       "Max-Age" "=" value
                      |       "SubPath" "=" value
                      |       "Port" [ "=" <"> portlist <"> ]
                      |       "Secure"
                      |       "Version" "=" 1*DIGIT
portlist        =       1#portnum
portnum         =       1*DIGIT

NAME=VALUE  REQUIRED.  The name of the state information ("cookie")
      is NAME, and its value is VALUE.  NAMEs that begin with $ are
      reserved and MUST NOT be used by applications.  The VALUE is
      opaque to the user agent and may be anything the origin server
      chooses to send, possibly in a server-selected printable ASCII
      encoding.  "Opaque" implies that the content is of interest and
      relevance only to the origin server.  The content may, in fact, be
      readable by anyone that examines the Set-Cookie2 header field.

Comment=value  OPTIONAL.  Because cookies can be used to derive or
      store private information about a user, the value of the Comment
      attribute allows an origin server to document how it intends to
      use the cookie.  The user can inspect the information to decide
      whether to initiate or continue a session with this cookie.
      Characters in value MUST be in UTF-8 encoding.  [RFC3629]

CommentURL="http_URL"  OPTIONAL.  Because cookies can be used to
      derive or store private information about a user, the CommentURL
      attribute allows an origin server to document how it intends to
      use the cookie.  The user can inspect the information identified
      by the URL to decide whether to initiate or continue a session
      with this cookie.

Max-Age=value  OPTIONAL.  The value of the Max-Age attribute is
      delta-seconds, the lifetime of the cookie in seconds, a decimal
      non-negative integer.  To handle cached cookies correctly, a
      client SHOULD calculate the age of the cookie according to the age
      calculation rules in the HTTP/1.1 specification [RFC2616].  When
      the age is greater than delta-seconds seconds, the client SHOULD
      discard the cookie.  A value of zero means the cookie SHOULD be
      discarded immediately.

SubPath=value  OPTIONAL.  The value of the Path attribute specifies
      the subset of URLs within the default path on the origin server to
      which this cookie applies.

Version=value  REQUIRED.  The value of the Version attribute, a
      decimal integer, identifies the version of the state management
      specification to which the cookie conforms.  For this
      specification, Version=2 applies.

cookie          =  "Cookie:" cookie-version 1*((";" | ",") cookie-value)
cookie-value    =  NAME "=" VALUE ";" cookie-path ";" cookie-domain
                   [";" cookie-port] [";" cookie-origin]

cookie-version  =  "$Version" "=" value
NAME            =  attr
VALUE           =  value
cookie-path     =  "$Path" "=" value
cookie-domain   =  "$Domain" "=" value
cookie-port     =  "$Port" [ "=" <"> port_list <"> ]
cookie-origin   =  "$Origin" "=" [ <"> http_URL <"> ]


   cookie-version  The value of the cookie-version attribute MUST be the
      value from the Version attribute of the corresponding Set-Cookie2
      response header field.  Otherwise the value for cookie-version is
      0.

   name  This is the verbatim name from the original Set-Cookie or Set-
      Cookie2 header field setting the cookie item.

   cookie-value  This is a verbatim copy of the value from the original
      Set-Cookie or Set-Cookie2 header field setting the cookie item.
      Quotes MUST be included if they were originally used, and MUST NOT
      be used if the original value did not contain them.

   cookie-path  The value for the cookie-path attribute MUST be the
      value from the cookie's Path state attribute, as determined when
      the corresponding Set-Cookie2 response header field was parsed.
      If the cookie was set using a previous specification this value
      MUST be the value of the Path attribute of the corresponding
      response header field or, if the Path attribute was absent, the
      default path of the URI used to set the cookie.

   cookie-domain  The value for the cookie-domain attribute MUST be the
      value from the cookie's Domain state attribute, as determined when
      the corresponding Set-Cookie2 response header field was parsed.
      If the response header field used the SubDomain attribute the
      domain value MUST be prefixed by a ".", if the Domain attribute is
      a default domain the domain value MUST NOT be prefixed by a ".".
      If the cookie was set by host supporting a previous version this
      value MUST be the Domain attribute from the correponding header
      field, including a preceding "." if the Domain attribute was
      present; if it was not present the domain value must be the name
      of the host setting the cookie, without being prefixed with a ".".

   cookie-port  The cookie-port attribute of the Cookie request header
      field MUST be exactly the value of the Port attribute, if one was
      present, in the corresponding Set-Cookie2 response header field.
      That is, the port attribute MUST be present if the Port attribute
      was present in the Set-Cookie2 header field, and it MUST have the
      same value (the exact character sequence), if any.  Otherwise, if
      the Port attribute was absent from the Set-Cookie2 header field,
      the attribute likewise MUST be omitted from the Cookie request
      header field.

   cookie-origin  The cookie-origin attribute of the Cookie header field
      MUST be sent for all cookies that were set according to [Netscape]
      and [RFC2965], and the value MUST be at least the scheme,
      authority and default path portion (as defined for the cookie path
      attribute) of the URI that originally set the cookie.  If the URI
      is not known then the URI part of this attribute MUST be empty.
      This attribute can be used by the server receiving the cookie to
      determine if it is willing to trust the cookie, based on which
      server (and path) originally set the cookie.  The basic
      information of this attribute, except the scheme, is implied by
      the cookie-domain and cookie-path attributes when the cookie is
      set according to this specification, and the client SHOULD NOT
      send this attribute with cookies set according to this
      specification.

   Note that there is neither a Comment nor a CommentURL attribute in
   the Cookie request header field corresponding to the ones in the Set-
   Cookie2 response header field.  The user agent does not return the
   comment information to the origin server.

   The user agent applies the following rules to choose applicable
   cookie-values to send in a Cookie request header field from among all
   the cookies it has received:

   Domain Selection  The origin server's effective host name MUST
      domain-match the Domain state attribute of the cookie.

   Port Selection  There are three possible behaviors, depending on the
      Port attribute in the Set-Cookie2 response header field:

      1.  By default (no Port attribute), the cookie MAY be sent to any
          port.
      2.  If the attribute is present but has no value (e.g., Port), the
          cookie MUST only be sent to the request-port it was received
          from.

      3.  If the attribute has a port-list, the cookie MUST only be
          returned if the new request-port is one of those listed in
          port-list.

   Path Selection  The request-URI MUST path-match the Path state
      attribute of the cookie.

   Max-Age Selection  Cookies that have expired should have been
      discarded and thus are not forwarded to an origin server.

   If multiple cookies satisfy the criteria above, they are ordered in
   the Cookie header field such that those with more specific Path
   attributes precede those with less specific.  Ordering with respect
   to other attributes (e.g., Domain) is unspecified.

   Note: For backward compatibility, the separator in the Cookie header
   field is semi-colon (;) everywhere.  A server SHOULD also accept
   comma (",") as the separator between cookie-values for future
   compatibility.

   A client MAY split a Cookie header field into multiple Cookie header
   fields, but SHOULD NOT do this unless comma is used as the separator,
   and the receiving server is expected to handle a multi-header Cookie
   value.

cookie2 =       "Cookie2:" cookie-version

Customer="WILE_E_COYOTE";
                        $Domain="www.example.com"; $Path="/acme/";
Part_Number="Rocket_Launcher_0001";
                        $Domain="www.example.com"; $Path="/acme/"
Customer="WILE_E_COYOTE";
                        $Domain="www.example.com"; $Path="/acme/";
Part_Number="Rocket_Launcher_0001";
                        $Domain="www.example.com"; $Path="/acme/";
Shipping="FedEx";
                        $Domain="www.example.com"; $Path="/acme/"
SubPath="ammo"

Part_Number="Riding_Rocket_0023";
                          $Domain="www.example.com"; $Path="/acme/ammo";
Part_Number="Rocket_Launcher_0001";
                          $Domain="www.example.com"; $Path="/acme/"

session_id="1234" and sets the default domain victim.cracker.edu.

session-id="1111", with a SubDomain attribute.

