TEKi=Ki+IK    (1)
K1 = s(3, 0); K2 = s(3, 1); ... ; K8 = s(3, 7) Formally, 
Ki =s(D, i).
     
TEK2=K2+IK=s(3,1)+IK; TEK3=K3+IK=l(s(2,1))+IK; ... ;
TEK6=K6+IK=r(s(2,2))+IK, then it can get ADU2 to ADU6.    

m=3, l=1, h=1, logt=3. KS constructs rekey messages as follows, SKRx 
