dht=Bamboo1.0;overlay=chat;expires=600

link-value      = linktype-token depth-token
linktype-token  = "P" / "S" / "R" / other-token
depth-token     = 1*DIGIT

l = log_(2^b) (N)

l = [lg N] / [lg 2^b]

l = [lg (2^160)] / [lg 16]
l = 160 / 4
l = 40

dht=Bamboo1.0;overlay=chat;expires=600
