T = M[32-63]) in these examples.  For simplicity, the policy-guided
next_hop_set = set of minimum cost links to the S-TIE.originator
next_hop_cost = minimum cost link to S-TIE.originator
disaggregated_prefixes = {empty }
nodes_same_layer = { empty }
isolated_nodes = nodes_same_layer
isolated_nodes = intersection(isolated_nodes,
                                                partial_neighbors[NH].nodes)
Illegal                = 0,
AddressFamilyMinValue  = 1,
IPv4     = 2,
IPv6     = 3,
AddressFamilyMaxValue  = 4,
Illegal              =   0,
TIETypeMinValue      =   1,
NodeTIEType          =   2,
PrefixTIEType        =   3,
PGPrefixTIEType      =   4,
KeyValueTIEType      =   5,
TIETypeMaxValue      =   6,
Illegal           = 0,
RouteTypeMinValue = 1,
LocalPrefix       = 2,
SouthPGPPrefix    = 3,
NorthPGPPrefix    = 4,
NorthPrefix       = 5,
SouthPrefix       = 6,
RouteTypeMaxValue = 7
