gmplsLabelInterface           = 12,
gmplsLabelIndex               = 1,
gmplsLabelSubindex            = 0,
gmplsLabelType                = gmplsFreeformLabel(3),
gmplsLabelFreeform            = 0x123456789ABCDEF0
gmplsLabelRowStatus           = createAndGo(4)
gmplsLabelInterface           = 13,
gmplsLabelIndex               = 1,
gmplsLabelSubindex            = 0,
gmplsLabelType                = gmplsFreeformLabel(3),
gmplsLabelFreeform            = 0xFEDCBA9876543210
gmplsLabelRowStatus           = createAndGo(4)
mplsInSegmentIndex           = 0x00000015
mplsInSegmentLabel           = 0, -- incoming label in label table
mplsInSegmentNPop            = 1,
mplsInSegmentInterface       = 12, -- incoming interface
mplsInSegmentTrafficParamPtr    = 0.0,
mplsInSegmentLabelPtr           = gmplsLabelTable (12, 1, 0)
mplsInSegmentRowStatus          = createAndWait(5)
mplsOutSegmentIndex          = 0x00000012,
mplsOutSegmentInterface      = 13, -- outgoing interface
mplsOutSegmentPushTopLabel   = true(1),
mplsOutSegmentTopLabel       = 0, -- outgoing label in label table

mplsOutSegmentTrafficParamPtr   = 0.0,
mplsOutSegmentLabelPtr          = gmplsLabelTable (13, 1, 0)
mplsOutSegmentRowStatus         = createAndWait(5)
mplsInSegmentIndex           = 0x00000016

mplsInSegmentLabel           = 0, -- incoming label in label table
mplsInSegmentNPop            = 1,
mplsInSegmentInterface       = 13, -- incoming interface

mplsInSegmentTrafficParamPtr    = 0.0,
mplsInSegmentLabelPtr           = gmplsLabelTable (13, 1, 0)

mplsInSegmentRowStatus          = createAndWait(5)
mplsOutSegmentIndex          = 0x00000013,
mplsOutSegmentInterface      = 12, -- outgoing interface
mplsOutSegmentPushTopLabel   = true(1),
mplsOutSegmentTopLabel       = 0, -- outgoing label in label table

mplsOutSegmentTrafficParamPtr   = 0.0,
mplsOutSegmentLabelPtr          = gmplsLabelTable (12, 1, 0)

mplsOutSegmentRowStatus         = createAndWait(5)
gmplsInSegmentDirection          = forward (1)
gmplsOutSegmentDirection         = forward (1)
gmplsInSegmentDirection          = reverse (2)
gmplsOutSegmentDirection         = reverse (2)
mplsXCIndex                = 0x01,
mplsXCInSegmentIndex       = 0x00000015,
mplsXCOutSegmentIndex      = 0x00000012,
mplsXCLspId                = 0x0102 -- unique ID
mplsXCLabelStackIndex      = 0x00, -- only a single outgoing label
mplsXCRowStatus            = createAndGo(4)
mplsXCIndex                = 0x02,
mplsXCInSegmentIndex       = 0x00000016,
mplsXCOutSegmentIndex      = 0x00000013,
mplsXCLspId                = 0x0102 -- unique ID
mplsXCLabelStackIndex      = 0x00, -- only a single outgoing label
mplsXCRowStatus            = createAndGo(4)
mplsInSegmentRowStatus          = active(1)
mplsInSegmentRowStatus          = active(1)
mplsOutSegmentRowStatus         = active(1)
mplsOutSegmentRowStatus         = active(1)
