Type = 1: Link NLRI, contains link descriptors and link attributes

Type = 2: Node NLRI, contains node attributes

Type = 3: IPv4 Topology Prefix NLRI

Type = 4: IPv6 Topology Prefix NLRI

Protocol-ID = 0: Unknown, The source of NLRI information could not
Protocol-ID = 1: IS-IS Level 1, The NLRI information has been
Protocol-ID = 2: IS-IS Level 2, The NLRI information has been
Protocol-ID = 3: OSPF, The NLRI information has been sourced by
Protocol-ID = 4: Direct, The NLRI information has been sourced
Protocol-ID = 5: Static, The NLRI information has been sourced by
