URI = scheme ":" path-rootless [ "?" query ] [ "#" fragment ]

path-rootless = segment-nz *( "/" segment )
segment-nz    = 1*pchar
segment       = *pchar

pchar = unreserved / pct-encoded / sub-delims / ":" / "@"

scheme     = "urn"

urn-path   = NID ":" NSS

NID = ( ALPHA / DIGIT ) 1*31( ALPHA / DIGIT / "-" )

NSS   = 1*pchar   ; or equivalent:    NSS   = segment-nz

gen-delims = ":" / "/" / "?" / "#" / "[" / "]" / "@"

excluded = CTL / SP        ; control characters and space
                       / DQUOTE          ; "
                       / "#"             ; from <gen-delims>
                       / "%"             ; see above
                       / "/"             ; from <gen-delims>
                       / "<" / ">"
                       / "?"             ; from <gen-delims>
                       / "["             ; from <gen-delims>
                       / "\"
                       / "]"             ; from <gen-delims>
                       / "^"
                       / "`"
                       / "{" / "|" / "}"
                       / %x7F            ; DEL (control character)
                       / %x80-FF         ; non-ASCII

URI    = scheme ":" path-rootless [ "?" query ] [ "#" fragment ]

scheme        = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )
path-rootless = segment-nz *( "/" segment )
query         = *( pchar / "/" / "?" )
fragment      = *( pchar / "/" / "?" )

segment-nz    = 1*pchar
segment       = *pchar
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"

unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
pct-encoded   = "%" HEXDIG HEXDIG
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                     / "*" / "+" / "," / ";" / "="

scheme        = "urn"
                          ; specific, fixed (assigned) value

urn-path      =  NID ":" NSS
                          ; to be superimposed on <path-rootless>

NID           = ( ALPHA / DIGIT ) 1*31( ALPHA / DIGIT / "-" )
                         ; RFC 3406[bis] contains more specific rules

NSS           = 1*pchar
                         ; or equivalent:    NSS   = segment-nz

ALPHA         =  %x41-5A / %x61-7A   ; A-Z / a-z
DIGIT         =  %x30-39             ; 0-9
HEXDIG        =  DIGIT / "A" / "B" / "C" / "D" / "E" / "F"

NSS           = 1*pchar   ; or equivalent:   NSS   = segment-nz

NSS         = 1*URN-char

URN-char    = trans / pct-encoded
trans       = ALPHA / DIGIT / u-other
u-other     = ":" / "@"
                       ; those from RFC 3986 <gen-delims>
                       ; specifically allowed in <pchar>.
