SAFI=133 for AFI=6 and SAFI=134 for AFI=25 to make them applicable to
comp1 = next_component(a);
comp2 = next_component(b);
common = MIN(MAC Address length (comp1),
                        MAC Address length (comp2));
cmp = MAC Address compare(comp1, comp2, common);
common =
                  MIN(component_length(comp1), component_length(comp2));
cmp = memcmp(data(comp1), data(comp2), common);
