FloorRequest =   (FIXED-HEADER)
                    (TRANSACTION-ID)
                    (USER-ID)
                    [BENEFICIARY-ID]
                   *(FLOOR-ID)
                    [HUMAN-READABLE-INFO]
                    [PRIORITY]
                    [NONCE]
                    [DIGEST]

                     Figure 20: FloorRequest format


FloorRelease =   (FIXED-HEADER)
                    (TRANSACTION-ID)
                    (USER-ID)
                    (FLOOR-REQUEST-ID)
                    [NONCE]
                    [DIGEST]

                     Figure 21: FloorRelease format


FloorRequestInfoWanted =   (FIXED-HEADER)
                              (TRANSACTION-ID)
                              (USER-ID)
                              [BENEFICIARY-ID]
                              [FLOOR-REQUEST-ID]
                              [NONCE]
                              [DIGEST]

                Figure 22: FloorRequestInfoWanted format


FloorRequestInfo =     (FIXED-HEADER)
                          (TRANSACTION-ID)
                          (USER-ID)
                          [BENEFICIARY-ID]
                          [USER-DISPLAY-NAME]
                          [USER-URI]
                     1*(  (FLOOR-REQUEST-ID)
                        1*(FLOOR-ID)
                          [HUMAN-READABLE-INFO]
                          [PRIORITY]
                          (REQUEST-STATUS)     )
                          [NONCE]

                   Figure 23: FloorRequestInfo format


FloorInfoWanted =   (FIXED-HEADER)
                       (TRANSACTION-ID)
                       (USER-ID)
                      *(FLOOR-ID)
                       [NONCE]
                       [DIGEST]

                   Figure 24: FloorInfoWanted format


FloorInfo        =       (FIXED-HEADER)
                            [TRANSACTION-ID]
                            (USER-ID)
                            [FLOOR-ID]
                         *( (FLOOR-REQUEST-ID)
                            [BENEFICIARY-ID]
                            [USER-DISPLAY-NAME]
                            [USER-URI]
                           *(FLOOR-ID)
                            [HUMAN-READABLE-INFO]
                            [PRIORITY]
                            (REQUEST-STATUS)      )
                            [NONCE]

                      Figure 25: FloorInfo format


ChairAction  =   (FIXED-HEADER)
                    (TRANSACTION-ID)
                    (USER-ID)
                  1*(FLOOR-ID)
                    (FLOOR-REQUEST-ID)
                    (REQUEST-STATUS)
                    [HUMAN-READABLE-INFO]
                    [NONCE]
                    [DIGEST]

                     Figure 26: ChairAction format


ChairActionAck  =   (FIXED-HEADER)
                       (TRANSACTION-ID)
                       (USER-ID)
                       [NONCE]

                    Figure 27: ChairActionAck format


Hello         =  (FIXED-HEADER)
                    (TRANSACTION-ID)
                    (USER-ID)
                    [NONCE]
                    [DIGEST]

                        Figure 28: Hello format


HelloAck      =  (FIXED-HEADER)
                    (TRANSACTION-ID)
                    (USER-ID)
                    (SUPPORTED-TLVS)
                    [NONCE]

                       Figure 29: HelloAck format


Error              =   (FIXED-HEADER)
                          (TRANSACTION-ID)
                          (USER-ID)
                          (ERROR-CODE)
                          [NONCE]
                          [HUMAN-READABLE-INFO]


                        Figure 30: Error format


