attribute               =/ service-classification

service-classification  = "servclass" ":" [SP] app-type 

app-type                = "Broadcast video" / 
                                "Real-time Interactive" / 
                                "Multimedia Conferencing" / 
                                "Multimedia Streaming" / 
                                "VoIP" /  "Voice-Admit" / 
                                 extension-mech

extension-mech          = token


m=audio 50000 RTP/AVP 0
a=servclass real-time interactive

a=servclass (optional/mandatory) real-time interactive

a=servclass Voice-Admit (sendonly/recvonly/sendrecv)

