a=path:msrp://alice.example.com:7394/2s93i9;tcp

                          Figure 3: Example MSRP URL

a=path:msrp://alice.example.com:7394/Conf=123456~userID=654321~;tcp

                          Figure 4: Example MSRP URL

a=path:msrp://alice.example.com:7394/Conf=123456~userID=654321~priv=abcdef~;tcp

                Figure 5: Example MSRP Private Message URL

