notes-uri      = "notes:" (formDoc | formDocNew |
                          formApp1 | formApp2 | formApp3 |
                          formUI)
formDoc        = "//" [server] "/" application "/" (viewUNID | folderUNID) "/" docUNID ["?" queryDoc]
formDocNew     = "//" [server] "/" application "/" name "?OpenForm"
formApp1       = "//" [server] "/" application
formApp2       = "//" [server] "/" application "/" (viewUNID | folderUNID )
formApp3       = "//" [server] "/" application "/" name "?" queryElement ["&" parameter]
formUI         = "///ClientBookmark?" uiElement

server         = hostname
hostname       = // as specified in {{RFC2396}}

application    = (appReplicaID | appFileAndPath)
appReplicaID   = 16*HEXDIG
appFileAndPath = 1*(unreserved | escaped)(".nsf" | ".ntf")

viewUNID       = (32*HEXDIG | "0")
folderUNID     = (32*HEXDIG | "0")
docUNID        = 32*HEXDIG

name           = 1*(unreserved | escaped)
queryDoc       = ("EditDocument" | "OpenDocument")
queryElement   = ("OpenFrameset" | "OpenView")
uiElement      = ("OpenDatabases" | "OpenReplication" | "OpenWorkspace")
parameter      = ("view=" viewUNID)

unreserved     = alphanum | allowedmark
alphanum       = // as specified in {{RFC2396}}
allowedmark    = "-" | "_" | "~" | "(" | ")"
escaped        = "%" hex hex
hex            = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" |
                     "8" | "9" | "A" | "B" | "C" | "D" | "E" | "F"

appReplicaID=1234567890ABCDEF

appReplicaID=1234567890ABCDEF
viewUNID=1234567890ABCDEF1234567890ABCDEF
viewUNID=1234567890ABCDEF1234567890ABCDEF
docUNID=1234567890ABCDEF1234567890FEDCBA
docUNID=1234567890ABCDEF1234567890FEDCBA
docUNID=1234567890ABCDEF1234567890FEDCBA
docUNID=1234567890ABCDEF1234567890FEDCBA
