r=1   <----------------------<----------
R=1                                         | c=1
                                               |
a=1                                     |
R=?             lost ASPCAR (r=1)      r=1
              <----------------------<----------
       *-----|                                 | start T(ack)
                                               | c=1
                                               |
                                               |
                                               |
                                               |
                    ASPCAR (r=1)         r=1   V  T(ack) expires
r=1   <----------------------<----------
R=1                                         | c=1
                                               |
a=1                                     |
r=1x <----------------------<---------
R=1x                                       | c=1x
                                               |
                                               |
                                               |
                                               |
                                               |
                    ASPCAR (r=1y)        r=1y  V  T(ack) expires
r=1y   <----------------------<----------
R=1y                                         | c=1y
a=1x                                    |
a=1y                                      stop T(ack)
a == c
r=1  <----------------------<----------
R=1                                         | c=1
                                               |
                                               |
                                               |
                    ASPCAR (r=2)         r=2   V
r=2    <----------------------<----------
R=2                                         | c=2
a=1                                     |
a=2                                     | T(ack) continues
R=?             lost ASPCAR (r=1)      r=1
              <----------------------<----------
       *-----|                                 | start T(ack)
                                               | c=1
                                               |
                    ASPCAR (r=2)         r=2   V
r=2   <----------------------<----------
R=2                                         | c=2
                                               |
a=2                                     |
r=1  <----------------------<----------
R=1                                         | c=1
                                               |
                                               |
                                               |
                   lost ASPCAR (r=2)      r=2
              <----------------------<----------
       *-----|                                 | restart T(ack)
a=1                                     | c=2
r=2   <----------------------<----------
R=2                                         | c=2
                                               |
a=2                                     |
R=?             ASPCAR (r=1)          r=1
                 <-------------------<----------
                |                              | start T(ack)
                |                              | c=1
                |                              |
                |   ASPCAR (r=2)         r=2   V
r=2    <----------------------<----------
R=2          |                              | c=2
a=2      |                              |
r=1     |                                stop T(ack)
R=1
a=1
r=2   <----------------------<----------
R=2                                         | c=2
a=2                                     |
R=?              ASPCAR (r=1)          r=1
                 <-------------------<---------
                |                              | start T(ack)
                |                              | c=1
                |                              |
                |   ASPCAR (r=-1)        r=-1  V
r=-1   <----------------------<----------
R=-1         |                              | c=-1
a=-1     |                              |
r=1     |                                stop T(ack)
R=1
a=1
r=1  <----------------------<----------
R=1                                        | c=1
                                               |
                                               |
                                               |
                    ASPCAR (r=-1)        r=-1  V
r=-1  <----------------------<----------
R=-1                                        | c=-1
a=1                                     |
a=-1                                    | discard ack
r=-1  <----------------------<----------
R=-1                                        | c=-1
                                               |
a=-1                                    |
