Service-State-extension = "Service-State" HCOLON svc-params
                                *(SEMI svc-params)
svc-params = (svc-token / svc-extension)
svc-token = "state" EQUAL gen-value
svc-extension = token [ EQUAL gen-value ]
gen-value = token / quoted-string


