IPL=32 being advertised from two different ingress NVEs (as RT-5)
IP=IP2 and [RFC5512] BGP Encapsulation Extended Community with
ESI=0, GW IP address=IP2 (and BGP Encapsulation Extended
IP=IP3 (and BGP Encapsulation Extended Community).

ESI=0, GW IP address=IP3 (and BGP Encapsulation Extended
IP=IP23 (and BGP Encapsulation Extended Community).

ESI=0, GW IP address=IP23 (and BGP Encapsulation Extended
ESI=0, GW IP address=IP23 (and BGP Encapsulation Extended
ESI=ESI23 and the corresponding tunnel information (VNI/VSID
ESI=ESI23, GW IP address=0 (and BGP Encapsulation Extended
ESI=ESI23 and the corresponding tunnel information (VNI/VSID
ESI=23, GW IP address=0 (and BGP Encapsulation Extended
type= VXLAN.

Tunnel-type= VXLAN.

