Value = 1 ("Invalid SID") will be sent back to the PCE.  The PCE MUST
Value = 1 ("Invalid SID") will be sent back to the PCE.  The PCE MUST
Value = 1 ("Invalid SID").  If the value of Path Segment is valid,
Value = 2 ("Unable to allocate the specified label/SID").

Error-value = 1
Error-value = 2
