m = user number || timestamp || nonce || hashed querier's contact
m = user number || timestamp || nonce || hashed querier_1's
ARID = URL path/Hash(m)

m = user number || disclosure mode || expiry time || salt|| hashed
m = user_id || disclosure_mode || expiry time || salt || hashed
ARID = URL path/Encrypt(m)

salt="dmvb1p03";hash_alg="SHA1"

Sender-References = "Sender-References" HCOLON sender-ref
                       *(COMMA sender-ref)
sender-ref        = LAQUOT absoluteURI RAQUOT sender-ref-type
                       SEMI avs-params
sender-ref-type   = "type" EQUAL ( "avs" / quoted-string )
avs-params        =  salt-param SEMI hash-alg-param
salt-param        = "salt" EQUAL quoted-string
hash-alg-param    = "hash-alg" EQUAL ( "SHA1" / quoted-string )

