CSR         = ( (me->Sender-of-RT), CSR )
RCVF        = (me, RCVF)                                     ||
MinMTU      = Min(my-MTU, MinMTU)
SAN-ID      = (as received in RT)
Local-RT    = (as received in RT)

RCVF={Rac,Rca,Rcd,Rdc}
SR={2,MW}={2,3,0}, where MW=0x0300 is the 16-bit Myrinet-type assigned       ||
E=3 (0011) indicates that all the data is Little Endian 64-bit. 


