alpha = tot_cwnd * ----------------------------------
                     /     rtt_max * cwnd_i * scale_den \ 2
                     | sum -----------------------------|
                     \  i              rtt_i            /

