I_MESSAGE =
R_MESSAGE =

I_MESSAGE =
R_MESSAGE =
S_i = d_2 + (avf(Q_2) x d_1) mod n.
P = h x S_i x (Q_4 + (avf(Q_4) x Q_3)).
S_r = d_2 + (avf(Q_2) x d_1) mod n.
P = h x S_r x (Q_4 + (avf(Q_4) x Q_3)).
