foocash=29Uso+Oa/e92micHd4s3

barsys=8n7VtC2+uL341/==
HREF="http://mercenary.com/goodies">
COST="0.25usd 0.40cad">chocolate fudge

isocurrency       = alpha alpha alpha
ietfcurrency      = 4*8alpha
privatecurrency   = 2*127[ dns-label "." ]
currency          = isocurrency | ietfcurrency | privatecurrency
digits            = 1*digit
decimal           = "." | ","
number            = digits | digits decimal *digit
exponent          = "+" digits | "-" digits

cost              = number currency | number exponent currency


ianapaysys     = 4*12alpha
privatepaysys  = url
paysysname     = ianapaysys | url

paysys         = paysysname "=" *uchar


pricetag = *sp paysys *[ 1*sp cost | 1*sp paysys ] *sp |
              *sp *[ cost 1*sp | paysys 1*sp ] paysys *sp


lowalpha       = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" |
                    "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" |
                    "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" |
                    "y" | "z"
hialpha        = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" |
                    "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" |
                    "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" |
                    "Y" | "Z"
alpha          = lowalpha | hialpha
digit          = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" |
                    "8" | "9"
other          = "$" | "-" | "_" | "." | "+" | "/" | "=" | "@"
hex            = digit | "A" | "B" | "C" | "D" | "E" | "F" |
                    "a" | "b" | "c" | "d" | "e" | "f"
escape         = "%" hex hex
sp             = " "
uchar          = alpha | digit | other | extra | escape
