as_timestamp = (PTP_sec * 10^9 + PTP_nsec) modulo 2^32

a=clockdomain:ptp-version=PTP-PROTOCOL gmid=EUI-64 traceable=YES-OR-NO


a=clockdomain:ptp-version=IEEE1588v1 gmid=39-A7-94-FF-FE-07-CB-D0 traceable=yes

a=clockdomain:ptp-version=IEEE1588v2 gmid=39-A7-94-FF-FE-07-CB-D0 traceable=yes

a=clockdomain:ptp-version=802.1AS gmid=39-A7-94-FF-FE-07-CB-D0 traceable=no


a=8021qat-qos:stream-id=EUI-64


a=8021qat-qos:stream-id=00-1D-C1-97-BB-3A-01-01



