Value=TBD (Attempted LSP setup/download/label-range reservation if
Error-type=TBD (label download failure) and Error-value=TBD (Label
value=TBD (label failed to be download)and MUST include the SRP
value=10 (SRP object missing).

value=10 (SRP object missing).

Error-value = TBD :                 Attempted LSP
                                                     setup/download/
                                                     label-range
                                                     reservation if
                                                     PCECC capability
                                                     was not advertised
Error-value = TBD :                 Stateful PCE
                                                     capability was not
                                                     advertised
Error-value = TBD :                 Unknown Label
Error-value = TBD :                 LABEL object
                                                     missing
Error-value = TBD :                 Label out of range.
Error-value = TBD :                 Download of label
                                                     Failed.
Error-value = TBD :                 Processing label
                                                     update Failed
                                                     during
                                                     synchronization.
Error-value = TBD :                 Internal PCE Error
                                                     during
                                                     synchronization.
