media-field =         "m=" media space port ["/" integer]
                          space proto 1*(space fmt) CRLF

setup-attr           =  "a=setup:" role
role                 =  "active" / "passive" / "actpass"
                                 / "holdconn"

connection-attr        = "a=connection:" conn-value
conn-value             = "new" / "existing"


m=image 54111 TCP t38
c=IN IP4 192.0.2.2
a=setup:passive
a=connection:new

m=image 9 TCP t38
c=IN IP4 192.0.2.1
a=setup:active
a=connection:new

m=image 54111 TCP t38
c=IN IP4 192.0.2.2
a=setup:actpass
a=connection:new

m=image 54321 TCP t38
c=IN IP4 192.0.2.1
a=setup:passive
a=connection:new

m=image 54321 TCP t38
c=IN IP4 192.0.2.1
a=setup:passive
a=connection:existing

m=image 9 TCP t38
c=IN IP4 192.0.2.2
a=setup:active
a=connection:existing

m=image 54111 TCP t38
c=IN IP4 192.0.2.2
a=setup:actpass
a=connection:existing

m=image 9 TCP t38
c=IN IP4 192.0.2.3
a=setup:active
a=connection:new

