resource   = nonnegint ":" *comment dictionary ";"

nonnegint  = 1*digit

digit      = %x30-39

comment    = "//" *( %x00-09 / %x0B-FF ) %x0A

dictionary = nonnegint "%" line-end *( string "=" value line-end )

line-end   = %x0A *" "

string     = nonnegint ":" *%x00-FF %x0A

value      = ( string  / dictionary / sequence / 
                     isequence / fsequence )

sequence   = nonnegint "@" %x0A *( value line-end )

isequence  = nonnegint "i" %x0A *( int line-end )

fsequence  = nonnegint "f" %x0A *( float line-end )

int        = "0" / ( *1"-" %x31-39 *digit )
 
float      = "0" / ( *1"-" ( "0" / %x31-39 *digit ) "." 1*digit )


dsd-i      = num "*" num %x69  ; %x69 is ascii lowercase 'i'

num        = "" / ( %x31-39 *digit )

dsd-f      = num "*" num %x66  ; %x66 is ascii lowercase 'f'

dsd-s      = num "*" num %x73  ; %x73 is ascii lowercase 's'

dsd-a       = num "*" num "@" *%x00-FF

size-spec   = num "*" num
keys-spec   = dsd-s

