ifIndex                        = 2,
teLinkAddressType              = unknown(0),
teLinkLocalIpAddr              = ''H,
teLinkRemoteIpAddr             = ''H,
teLinkMetric                   = 5,
teLinkProtectionType           = dedicated1For1(4),
teLinkWorkingPriority          = 7,
teLinkResourceClass            = 3,
teLinkIncomingIfId             = 0,
teLinkOutgoingIfId             = 2,
teLinkRowStatus                = createAndGo(4),
teLinkStorageType              = nonVolatile(3)
ifStackHigherLayer             = 0,
ifStackLowerLayer              = 2,
ifStackStatus                  = createAndGo(4)
ifIndex                        = 3,
teLinkAddressType              = unknown(0),
teLinkLocalIpAddr              = ''H,
teLinkRemoteIpAddr             = ''H,
teLinkMetric                   = 5,
teLinkProtectionType           = unprotected(2),
teLinkWorkingPriority          = 7,
teLinkResourceClass            = 3,
teLinkIncomingIfId             = 0,
teLinkOutgoingIfId             = 3,
teLinkRowStatus                = createAndGo(4),
teLinkStorageType              = nonVolatile(3)
ifStackHigherLayer             = 2,
ifStackLowerLayer              = 3,
ifStackStatus                  = createAndGo(4)
ifIndex                        = 4,
teLinkAddressType              = unknown(0),
teLinkLocalIpAddr              = ''H,
teLinkRemoteIpAddr             = ''H,
teLinkMetric                   = 5,
teLinkProtectionType           = unprotected(2),
teLinkWorkingPriority          = 7,
teLinkResourceClass            = 3,
teLinkIncomingIfId             = 0,
teLinkOutgoingIfId             = 4,
teLinkRowStatus                = createAndGo(4),
teLinkStorageType              = nonVolatile(3)
ifStackHigherLayer             = 2,
ifStackLowerLayer              = 4,
ifStackStatus                  = createAndGo(4)
ifIndex                        = 3,
teLinkSrlg                     = 10,
teLinkSrlgRowStatus            = createAndGo(4),
teLinkSrlgStorageType          = nonVolatile(3)
ifIndex                        = 4,
teLinkSrlg                     = 50,
teLinkSrlgRowStatus            = createAndGo(4),
teLinkSrlgStorageType          = nonVolatile(3)
ifIndex                          = 5,
componentLinkPreferredProtection = primary(1),
componentLinkRowStatus           = createAndGo(4),
componentLinkStorageType         = nonVolatile(3)
ifStackHigherLayer             = 3,
ifStackLowerLayer              = 5,
ifStackStatus                  = createAndGo(4)
ifIndex                          = 6,
componentLinkPreferredProtection = secondary(2),
componentLinkRowStatus           = createAndGo(4)
componentLinkStorageType         = nonVolatile(3)
ifStackHigherLayer             = 4,
ifStackLowerLayer              = 6,
ifStackStatus                  = createAndGo(4)
