i = 1..Num Addrs     by the sending ILNPv4 node.

i = 1..Num Addrs     relative to other valid Locator[i]
                               values. The Preference numbers here are
                               identical, both in syntax and semantics,
                               to the Preference values for L32 records
                               as specified by [ILNP-DNS].

