mailbox="mailat:john.doe@somewhere.com"
timestamp="OMA-EMN-dateformat"> </emn>
    
mailbox="mailat:joe@foo.com"  
timestamp="2004-02-20T06:40:00Z"> 
mailbox="mailat:joe@foo.com"  
 


view="INBOX" 
event="New Message" 
timestamp="2004-02-20T06:40:00Z" 
sender="Mike Smith &lt;mike@foo.com&gt;" 
datetime="Thu, 15 May 2006 19:51:21 -0700" 
sequence-id="1" 
uid="157" 
subject="Re: our meeting" 
format = "WAKEUP" / "EXTENDED" 
    
UDP=EXTENDED" 
          
format = "WAKEUP" / "EXTENDED" 
    
    
