Data  =>(     uCDN    )<=   Logging
          //   `-.       _,-'   \\  Data
          ||        `-'-'-'      ||
CR = %x0D ; carriage return

ALPHA = %x41-5A / %x61-7A ; A-Z / a-z

DIGIT = %x30-39 ; 0-9

DQUOTE = %x22 ; " (Double Quote)

CRLF = CR LF ; Internet standard newline
HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F"

HTAB = %x09 ; horizontal tab

LF = %x0A ; linefeed

OCTET = %x00-FF ; 8 bits of data

host = as specified in section 3.2.2 of [RFC3986].

IPv4address = as specified in section 3.2.2 of [RFC3986].

IPv6address = as specified in section 3.2.2 of [RFC3986].



ADDRESS = IPv4address / IPv6address

ALPHANUM = ALPHA / DIGIT

DATE = 4DIGIT "-" 2DIGIT "-" 2DIGIT

         Dates are encoded as "full-date" specified in [RFC3339].

DEC = 1*DIGIT ["." *DIGIT]

NAMEFORMAT = ALPHANUM *(ALPHANUM / "_" / "-")

QSTRING = DQUOTE *NDQUOTE DQUOTE

NDQUOTE = <any OCTET excluding DQUOTE> / 2DQUOTE ; whereby a
NHTABSTRING = *NHTAB

NHTAB = <any OCTET excluding HTAB, CR and LF>

TIME = 2DIGIT ":" 2DIGIT ":" 2DIGIT ["." *DIGIT]

         Times are encoded as "partial-time" specified in [RFC3339].
DIRLINE = "#" directive CRLF

DIRGROUP = 1*DIRLINE

RECLINE = CDNILOGREC CRLF

RECGROUP = *RECLINE

CDNILOGFILE = 1*(DIRGROUP RECGROUP)

directive = DIRNAME ":" HTAB DIRVAL

DIRNAME = NAMEFORMAT
DIRNAME = <any CDNI Logging Directive name registered in the CDNI
DIRVAL = <directive value, as specified by the document identified
CDNILOGREC = FIEVAL *(HTAB FIEVAL)

FIEVAL = <CDNI Logging field value corresponding to the CDNI
rel="self" type="application/atom+xml" />
rel="current" type="application/atom+xml" />
rel="prev-archive" type="application/atom+xml" />
type="application/cdni.LoggingFile" />
type="application/cdni.LoggingFile" />
