mdn-request-header = "Disposition-notification-to" ":" address

original-recipient-header =
          "Original-Recipient" ":" address-type ";" generic-address

disposition-notification-content = reporting-ua-field CRLF
          [ mdn-gateway-field CRLF ]
          [ original-recipient-field CRLF ]
          final-recipient-field CRLF
          [ original-message-id-field CRLF ]
          disposition-field CRLF
          *( extension-field CRLF)


address-type = atom

ua-name-type = atom

mta-name-type = atom

reporting-ua-field = "Reporting-UA" ":" ua-name-type ";" ua-name

ua-name = *text

mdn-gateway-field = "MDN-Gateway" ":" mta-name-type ";" mta-name

original-recipient-field =
          "Original-Recipient" ":" address-type ";" generic-address

generic-address = *text

final-recipient-field =
          "Final-Recipient" ":" address-type ";" generic-address

original-message-id-field = "Original-Message-ID" ":"
          "<" addr-spec ">"

disposition-field = "Disposition" ":" disposition-value

disposition-value =
          "displayed" / "printed" / "forwarded" / "deleted" /
          "obsoleted" / "expired" / "terminated" / "denied"

mdn-request-header = "Disposition-notification-to" ":" address

original-recipient-header =
     "Original-Recipient" ":" address-type ";" generic-address

disposition-notification-content = reporting-ua-field CRLF
     [ mdn-gateway-field CRLF ]
     [ original-recipient-field CRLF ]
     final-recipient-field CRLF
     [message-id-field CRLF]
     disposition-field CRLF
     *( extension-field CRLF)

address-type = atom

ua-name-type = atom

mta-name-type = atom

reporting-ua-field = "Reporting-UA" ":" ua-name-type ";" ua-name

ua-name = *text

mdn-gateway-field = "MDN-Gateway" ":" mta-name-type ";" mta-name
original-recipient-field =
     "Original-Recipient" ":" address-type ";" generic-address

generic-address = *text

final-recipient-field =
     "Final-Recipient" ":" address-type ";" generic-address

disposition-field = "Disposition" ":" disposition-value

disposition-value =
     "displayed" / "printed" / "forwarded" / "deleted" /
     "obsoleted" / "expired" / "terminated" / "denied"

original-message-id-field = "Original-Message-ID" ":" "<" addr-spec ">"

extension-field = extension-field-name ":" *text

extension-field-name = atom


boundary="RAA14128.773615765/mega.edu"

