ACCESSIBLE-param = "VALUE=boolean" / any-param
ACCESSIBLE-value = boolean


ACCESSIBILITYINFO-param = "VALUE=" ("text" / "uri") /
                              any-param
ACCESSIBILITYINFO-value = URI / text


CAPACITY-param = "VALUE=integer" / any-param
CAPACITY-value = integer
INVENTORY-param = "VALUE=" ("text" / "uri") / any-param
INVENTORY-value = uri / text


LOCATIONTYPE-param = "VALUE=text" / any-param
LOCATIONTYPE-value = text


RESTRICTED-param = "VALUE=boolean" / any-param
RESTRICTED-value = boolean


RESTRICTEDACCESSINFO-param = "VALUE=" ("text" / "uri") /
                                any-param
RESTRICTEDACCESSINFO-value = URI / text


NOCOST-param = "VALUE=boolean" / any-param
NOCOST-value = boolean


COSTINFO-param = "VALUE=" ("text" / "uri") / any-param
COSTINFO-value = uri / text


