challenge  = "<" 1*DIGIT "." 1*DIGIT "@" hostname ">"

digest     = 32(DIGIT / %x61-66)
                  ; A hexadecimal string using only lower-case
                  ; letters

hostname   = 1*(ALPHA / DIGIT) *("." / "-" / ALPHA / DIGIT)

response   = user SP digest

user       = 1*OCTET
