SKEYSEED = prf(Ni | Nr, SS1 | SS2 | ...| SSN)

KEYMAT = prf+(SK_d, SS1 | SS2 | ... | SSN | Ni | Nr)

SKEYSEED = prf(SK_d (old), SS1 | SS2 | ... | SSN | Ni | Nr)

InitiatorSignedOctets = RealMessage1 | PayloadData1 |
                    PayloadData2 | ... | PayloadDataN | 
                    NonceRData | MACedIDForI

ResponderSignedOctets = RealMessage2 | PayloadData1 | 
                    PayloadData2 | ... | PayloadDataN | 
                    NonceIData | MACedIDForR

Cookie = <VersionIDofSecret> | Hash(KEi(#TBA) | <secret>)

Cookie = <VersionIDofSecret> | Hash(Ni | IPi | SPIi | 
                                          KEi(#TBA) | <secret>)

