master_secret = PRF(pre_master_secret, "master secret",
                       ClientHello.random + ServerHello.random)
                       [0..47];

session_hash = Hash(handshake_messages)

master_secret = PRF(pre_master_secret, "extended master secret",
                           session_hash)
                           [0..47];

master_secret =
             MD5(pre_master_secret + SHA('A' + pre_master_secret +
                 session_hash)) +
             MD5(pre_master_secret + SHA('BB' + pre_master_secret +
                 session_hash)) +
             MD5(pre_master_secret + SHA('CCC' + pre_master_secret +
                 session_hash));

