gX=gZ.id(B1).xxx         gY=gZ.id(B2).yyy
                                      _:_                   _:_
                                     | X |                 | Y |
                                     |___|                 |___|

