fixed="current"/> 
        </xs:appinfo> 
    

maxOccurs="unbounded"/> 
minOccurs="0" /> 
minOccurs="0" maxOccurs="unbounded" /> 
version="3.1"> 
use="required" fixed="Container"/> 
fixed="LivingRoom"/> 
        </xs:appinfo> 
    

maxOccurs="unbounded"/> 
     <xs:element name="Description" type="Description" minOccurs="0"/> 
     <xs:element name="RevisionHistory" type="RevisionType" 
maxOccurs="unbounded"/> 
    </xs:sequence> 
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"> 
    <edit-config> 
     <target> 
      <running/> 
     </target> 
     <config xmlns="urn:ietf:params:xml:ns:netmod:data:book:1.0"> 
      <book value="Container"> 
       <bookTitle value="NetMod for Dummies: Part1"/> 
       <ISBN value="0596002923"/> 
       <Author value="NetMod Experts"/> 
       <PublicationYear value="2003"/> 
       <LastIssueDate value="2003-10-15"/> 
       <AverageReview value="0"/> 
      </book> 
     </config> 
    </edit-config> 
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"> 
     <ok/> 
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"> 
    <edit-config> 
     <target> 
      <running/> 
     </target> 
      <config xmlns="urn:ietf:params:xml:ns:netmod:data:book:1.0" 
operation="replace"> 
      <book value="Container"> 
       <bookTitle value="NetMod for Dummies: Part2"/> 
       <ISBN value="0596002924"/> 
       <Author value="NetMod Experts"/> 
       <PublicationYear value="2003"/> 
       <LastIssueDate value="2003-10-15"/> 
       <AverageReview value="0"/> 
      </book> 
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"> 
     <ok/> 
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"> 
    <edit-config> 
     <target> 
      <Path>//bk:book[bk:ISBN/@bk:value="0596002923"]</Path>    
     </target> 
      <config xmlns="urn:ietf:params:xml:ns:netmod:data:book:1.0" 
operation="delete"/> 
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"> 
     <ok/> 
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"> 
    <edit-config> 
     <target> 
      <running/> 
     </target> 
      <config xmlns="urn:ietf:params:xml:ns:netmod:data:book:1.0" 
operation="create"> 
      <book value="Container"> 
       <bookTitle value="NetMod for Dummies: Part3"/> 
       <ISBN value="0596002925"/> 
       <Author value="NetMod Experts"/> 
       <PublicationYear value="2003"/> 
       <LastIssueDate value="2003-10-15"/> 
       <AverageReview value="0"/> 
      </book> 
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"> 
     <ok/> 
