sig-a-tag-k = "rsa" / "rsafp" / "eddsa"
             / x-sig-a-tag-k

k=    The public key (base64; REQUIRED).  White space is ignored in
         this value and MUST be ignored when reassembling the original
         key.

         ABNF:

sig-k-tag       = %x6b [FWS] "=" [FWS] sig-k-tag-data
sig-k-tag-data  = base64string

key-k-tag-type  = "rsa" / "rsafp" / "eddsa"
             / x-key-k-tag-type
