Account=alice@example.com
UDF=MAMU-5QXP-TWCD-7PKI-S4FC-IB76-XASH

Account = alice@example.com
Account=groupw@example.com
UDF=MBND-NF5R-BEOZ-EHDY-PXM3-XTDU-HK5T

Account=main
UDF=MAMU-5QXP-TWCD-7PKI-S4FC-IB76-XASH

