PktTsbpdTime = TsbpdTimeBase + PKT_TIMESTAMP + TsbpdDelay + Drift

TsbpdTimeBase = T_NOW - HSREQ_TIMESTAMP

TsbpdTimeBase = TsbpdTimeBase + MAX_TIMESTAMP + 1

pos = 0;  /* Current receiver buffer position */
i = 0;    /* Position of the next available in the receiver buffer
                packet relatively to the current buffer position pos */

i = next_avail();
PktTsbpdTime = delivery_time(i);

pos = i + 1;
RTT = RTT * 0.875 + rtt * 0.125

RTTVar = RTTVar * 0.75 + abs(RTT - rtt) * 0.25

IV = MSB(112, Salt): Most significant 112 bits of the salt.

SEK  = PRNG(KLen)
Salt = PRNG(128)
KEK = PBKDF2(passphrase, LSB(64,Salt), Iter, Klen)

Wrap = AESkw(KEK, SEK)

EncryptedPayload = AES_CTR_Encrypt(SEK, IV, UnencryptedPayload)

IV = (MSB(112, Salt) << 2) XOR (PktSeqNo)

KEK = PBKDF2(passphrase, LSB(64,Salt), Iter, KLen)

SEK = AESkuw(KEK, Wrap)

DecryptedPayload = AES_CTR_Encrypt(SEK, IV, EncryptedPayload)

IV = (MSB(112, Salt) << 2) XOR (PktSeqNo)

key1=value1,key2=value2...
