I_MESSAGE = HDR, T, CERTi, [IDr], [SP], SIGNi   -->

R_MESSAGE = HDR, T, RAND, IDr|CERTr, {SP}, KEMAC, PKE, SIGNr


                       Figure 1: MIKEY RSA_R mode

KEMAC = E(encr_key, IDr || {TGK}) || MAC The first payload (IDr) in
