CN-ID = a Relative Distinguished Name (RDN) in the certificate
DNS-ID = a subjectAltName entry of type dNSName

SRV-ID = a subjectAltName entry of type otherName whose name form
URI-ID = a subjectAltName entry of type uniformResourceIdentifier
