G = guanine, and T = thymine, given that they current
V = b^2(h)



UvN  =  {Xv1 U Xv2 U ... U XvQ}  =  (1v1 + 1v2 + ... + 1vQ),
I = {X, X, X ... X}, and X = 1, I = (1v1 + 1v2 + 1v3 +  ...  + 1vQ).


    Hence, the definition of a Cardinal Number is given by:


   Cardinal Number: The Cardinal Number is the Multiplicative
                    Identity Element for all X| X E I, which
                    represents the Element of the Unary Set
                    that is used to determine the Cardinality
                    of every Set from the Sum or Union of the
                    Multiplicative Identity Element for
                    every E X of the Set I: iff X^Q = X.
X = XvN = X^Q remains valid, and;



X = XvU there is a XvN | XvN = X^Q, which also True for all
XvN = (A U B U C U ... U N), then XvN = XvU,
X = XvU = (X U Y), equation 25;

X = X, which means, by definition; X n (Y U Y) = X (Y + Y).





Q = N, and N > 2.
IPv4 = 32 Bit Length   (Bit-Mapped Displacement)
IPv6 = 128 Bit Length   (Bit-Mapped Displacement)
A = B                      A' /=  B'
                                            Not Equal to
