UP = User Profile
   NOTE:        For the simplicity only one Call Control function is
   showed within each network. However, one network may include more
   than one call control function with a reference point similar to the
   C2 reference point.
            Figure 14. Reference points for the Scenario 2.



