Permission-Upload   =  "Permission-Upload" HCOLON perm-up-spec
perm-up-spec        =  ( name-addr / addr-spec )
                           *( SEMI generic-param )

Trigger-Consent     =  "Trigger-Consent" HCOLON trigger-cons-spec
trigger-cons-spec   =  ( name-addr / addr-spec )
                           *( SEMI generic-param )

