M = Mandatory. This bit is used to provide an  accounting  agent  with
M = 0 indicates that the accounting agent may ignore the attribute.

M =  1  indicates  that  the  accounting  agent  not  supporting  this
