FCC         = ":fcc" string *FCC-OPTS
                   ; per Section 2.6.2 of RFC5228,
                   ; the tagged arguments in FCC may appear in any order

FCC-OPTS    = CREATE / IMAP-FLAGS / SPECIAL-USE
                   ; each option MUST NOT appear more than once

CREATE      = ":create"
IMAP-FLAGS  = ":flags" string-list
SPECIAL-USE = ":specialuse" string

