line = continuation id SP verb [SP params] LF

continuation = "+" / "-" / "."

id = 1*digit

digit = %x30-39 ; 0-9

verb = 1*alpha

alpha = %x41-5A / %x61-7A   ; A-Z / a-z

params = 1*(%20-%7e)

LF = %x0A

SP = %x20

to=, the SendStatus could omit the address.


