ERO={}).

     +---------------------------------------------------------------+
     | TUNNEL          | LSP                                         |
     +-----------------+---------------------------------------------+
     | PLSP-ID=100     | LSP-ID=0, D-flag=1, OPER=DOWN, ERO={}       |
     +---------------------------------------------------------------+

                        Figure 1: Content of LSP DB

ERO={A} from that PCUpd.  PCC sends PCRpt(R-FLAG=0, D-flag=1, OPER-
FLAG=UP, PLSP-ID=100, LSP-ID=0, ERO={A}).
     +---------------------------------------------------------------+
     | TUNNEL          | LSP                                         |
     +-----------------+---------------------------------------------+
     | PLSP-ID=100     | LSP-ID=0, D-flag=1, OPER=UP, ERO={A}        |
     +---------------------------------------------------------------+

                        Figure 2: Content of LSP DB

FLAG=UP).

     +---------------------------------------------------------------+
     | TUNNEL          | LSP                                         |
     +-----------------+---------------------------------------------+
     | PLSP-ID=100     | LSP-ID=2, ERO={A}, OPER=UP                  |
     |                 | LSP-ID=3, ERO={B}, OPER=UP                  |
     +---------------------------------------------------------------+

                        Figure 4: Content of LSP DB
ID=2).

     +---------------------------------------------------------------+
     | TUNNEL          | LSP                                         |
     +-----------------+---------------------------------------------+
     | PLSP-ID=100     | LSP-ID=3, ERO={B}, OPER=UP                  |
     +---------------------------------------------------------------+

                        Figure 5: Content of LSP DB

LSP-ID=3).
     +---------------------------------------------------------------+
     | TUNNEL          | LSP                                         |
     +-----------------+---------------------------------------------+
     | PLSP-ID=100     | LSP-ID=2, OPER=UP                           |
     +---------------------------------------------------------------+

                        Figure 8: Content of LSP DB

LSP-ID=1, ASSO_PARAM=A, ASSO_R_FLAG=0).

     +---------------------------------------------------------------+
     | ASSO            | LSP                                         |
     +-----------------+---------------------------------------------+
     | ASSO_PARAM=A    | PLSP-ID=100, LSP-ID=1                       |
     +---------------------------------------------------------------+

                      Figure 9: Content of PCE ASSO DB

LSP-ID=1, ASSO_PARAM=A, ASSO_R_FLAG=0).

     +---------------------------------------------------------------+
     | ASSO            | LSP                                         |
     +-----------------+---------------------------------------------+
     | ASSO_PARAM=A    | PLSP-ID=100, LSP-ID=1                       |
     |                 | PLSP-ID=200, LSP-ID=1                       |
     +---------------------------------------------------------------+

                     Figure 10: Content of PCE ASSO DB
PLSP-ID=200, LSP-ID=1).

     +---------------------------------------------------------------+
     | ASSO            | LSP                                         |
     +-----------------+---------------------------------------------+
     | ASSO_PARAM=A    | PLSP-ID=100, LSP-ID=1                       |
     +---------------------------------------------------------------+

                     Figure 12: Content of PCE ASSO DB

ID=1, ASSO_PARAM=A, ASSO_R_FLAG=1).  The PCE ASSO DB is now empty.

     +---------------------------------------------------------------+
     | ASSO            | LSP                                         |
     +-----------------+---------------------------------------------+
     | ASSO_PARAM=A    |                                             |
     +---------------------------------------------------------------+

                     Figure 13: Content of PCE ASSO DB

LSP-ID=1, ASSO_PARAM=A, ASSO_R_FLAG=0).

     +---------------------------------------------------------------+
     | ASSO            | LSP                                         |
     +-----------------+---------------------------------------------+
     | ASSO_PARAM=A    | PLSP-ID=100, LSP-ID=1                       |
     +---------------------------------------------------------------+

                     Figure 14: Content of PCE ASSO DB

ID=1).

     +---------------------------------------------------------------+
     | ASSO            | LSP                                         |
     +-----------------+---------------------------------------------+
     | ASSO_PARAM=B    | PLSP-ID=100, LSP-ID=2                       |
     +---------------------------------------------------------------+

                     Figure 16: Content of PCE ASSO DB

