L-LSP     =     Lambda-LSP
WB-LSP    =     WaveBand-LSP
F-LSP     =     Fiber-LSP

WXC       =     Wavelength Cross-Connect
WBXC      =     WaveBand Cross-Connect
FXC       =     Fiber Cross-Connect

LSC       =     Lambda Switch Capabale
WBSC      =     WaveBand Switch Capable
FSC       =     Fiber Switch Capable

MG-OXC    =     Multi-Granularity Cross-Connect

