host           =     <IPv4address> | <hostname> 
    
IPv4address    =     1*<digit> "." 1*<digit> "." 1*<digit> "."  
                        1*<digit>   
    
hostname       =     *(<domainlabel> "." ) <toplabel> [ "." ] 
    
domainlabel    =     *<alphanum> 
    
toplabel       =     *<alpha> 
    
alphanum       =     <alpha> | <digit> 
    
alpha          =     <lowalpha> | <upalpha> 
    
upalpha        =     "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" |  
                        "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | 
                        "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | 
                        "Y" | "Z" 
                         
lowalpha       =     "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" |  
                        "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | 
                        "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" |  
                        "y" | "z" 
    
digit          =     "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" |  
                        "8" | "9" 
    
              Figure 1: Example BNF description of a protocol 
    
BNF_rule = ...      Defines a new BNF rule in terms of existing BNF 
                       rules 

alphanum       =     <alpha> | <digit> 
    
digit          =     "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" |  
                        "8" | "9" 
    
hello_message  =     "Hello " <name> 
    
name           =     "Tom" | "Dick" | "Harry" | "Sally" 
    
               Figure 2: Simple protocol described using BNF 
                                      
and_rule       =     <rule_1> <rule_2> ... <rule_n> 
    
or_rule        =     <rule_1> | <rule_2> | ... | <rule_n> 
    
text_rule      =     "string" 
    
optional_rule  =     [<rule>] 
    
list_rule      =     x*y (<rule>) 
    
hostname       =     *(<domainlabel> "." ) <toplabel> [ "." ] 
    
hostname       =     <dummy_rule_1> <toplabel> <dummy_rule_2> 
    
dummy_rule_1   =     *<dummy_rule_3> 
    
dummy_rule_2   =     [<dummy_rule_4>] 
    
dummy_rule_3   =     <domainlabel> <dummy_rule_4> 
    
dummy_rule_4   =     "." 
    
host         =       <IPv4address> | <hostname> 
    
name         =      "Tom" 
    
hello_message  =     <rule_1> <name> 
    
rule_1         =     "Hello " 
    
name           =     <rule_2> | <rule_3> | <rule_4> | <rule_5> 
    
rule_2         =     "Tom" 
    
rule_3         =     "Dick" 
    
rule_4         =     "Harry" 
    
rule_5         =     "Sally" 
    
name           =     "Tom" | "Dick" | "Harry" | "Sally" 
    
