pattern = re.compile(r"^([^\s\.#]+\.)*([^\s\.#]+)$")
pattern = re.compile(r"^(([^\s\.#]+\.)|\.)*([^\s\.#]+)?$")
pattern = re.compile(r"^([0-9a-z_]+\.)*([0-9a-z_]+)$")
pattern = re.compile(r"^(([0-9a-z_]+\.)|\.)*([0-9a-z_]+)?$")
PY3 = sys.version_info >= (3,)
unicode = str

data_in = os.urandom(16)
encoded = json.dumps('\0' + base64.b64encode(data_in).
                                             decode('ascii'))

decoded = json.loads(encoded)
data_out = base64.b64decode(decoded[1:])
data_out = decoded

data_out = decoded;
