id-sha-256=X48E9qOokqqrvdts8nOJRJN3OWDUoyWxBf7kbu9DBPE=

CwGAZiwiAeyJoZWxsbyI6ICJ3b3JsZCJ9Aw==

identity = lambda x: x

json_bytes = json.dumps(item).encode()
content_encoded = content_coding(json_bytes)
checksum = algorithm(content_encoded)
item = {"hello": "world"}

