A=1 B=2 C=3      |   <END>A=1\[5081B=2\[5131C=3\[51a1<END>


crc = crc_update(crc, p, 1 );
crc=crc_finalize(crc);
           send_char( ESC );
           send_char( ESC_CRC );
           for(int i=0;i<4;i++, crc <<= 4 )
               send_char( hextoasc(crc) );
       }

       /* tell the receiver that we're done sending the packet
        */
       send_char(END);
c = recv_char();

c = recv_char();
 




c = END;
c = ESC;
cs=0;
crc = crc_init();
crc = crc_update(crc,&c,1);
Poly=0x8005, XorIn=0, ReflectIn=True, XorOut=0, ReflectOut=True from
ret = data & 0x01;
ret = (ret << 1) | (data & 0x01);
c = t1_crc_reflect(*d++, 8);
bit = crc & 0x8000;
crc = (crc << 1) | ((c >> (7 - i)) & 0x01);
bit = crc & 0x8000;
crc = t1_crc_reflect(crc, 16);
