timely-parameter = "TIMELY=" interval
interval         = 1*9DIGIT

retry-count-field = "Retry-Count" ":" 1*3DIGIT

ENVID=EE271828 RET=HDRS
ORCPT=rfc822;Robinton@Harper.org
ENVID=EE271828 RET=HDRS
ORCPT=rfc822;Robinton@Harper.org
report-type=delivery-status
report-type=delivery-status
report-type=delivery-status
ENVID=EE271828 RET=HDRS
ORCPT=rfc822;Sebell@Harper.org
report-type=delivery-status
ENVID=EE271828 RET=HDRS
ORCPT=rfc822;Nicat@Miners.org
report-type=delivery-status
