capability       =/ notify

action           =/ notify / denotify

priority         = :low / :medium / :high /

notify           = "notify" WSP priority WSP string WSP string-list
                              ;; <priority> <message> <headers-list>

denotify         = "denotify"
