fields =/ "Form-Sub:" FWS "v=1" *(FWS ";" FWS fsarg) CRLF

fsarg = "ip4=" ip4redacted
ip4redacted = IPv4 address with parts optionally replaced by "x"

fsarg =/ "ip6=" ip6redacted
ip6redacted = IPv6 address with parts optionally replaced by "x"

fsarg =/ "ip=none"

