Values=          (inheritance [owner] [aclinheritance] *ACE
Parent=          acl

Values=          Principal
Parent=          acl
Values=          ("Dynamic" | "Static" | "None" | Extension)
Values=          ("Dynamic" | "None" | Extension)
Values=          *cdata

Values=          Principal Allow Deny
Values=          Prop ACL
