AP = Access Provider        * AP *
                                    ******
                                      | Port 587
                                  +---+----+
                                  |  MUA.r |
                                  +--------+
                                   HOTSPOT

             Figure 1: Example of Port 587 Usage Via Internet
