op="request">).

targetNamespace="urn:ietf:params:xml:ns:fee-0.9"
elementFormDefault="qualified">

maxOccurs="unbounded" />
minOccurs="0" />
minOccurs="0" />
default="urn:ietf:params:xml:ns:domain-1.0" />
type="NMTOKEN" default="name" />
maxOccurs="unbounded" />
minOccurs="0" maxOccurs="1" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="unbounded" />
default="urn:ietf:params:xml:ns:domain-1.0" />
minOccurs="0" />
maxOccurs="unbounded" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" />
maxOccurs="unbounded" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" />
minOccurs="0" />
