InitiatorSignedOctets = RealMessage1 | AUX_I | NonceRData | MACedIDForI
AUX_I = ICV_INIT_1 | ICV_INIT_2 | ICV_INIT_3 ...

ResponderSignedOctets = RealMessage2 | AUX_R | NonceIData | MACedIDForR
AUX_R = ICV_RESP_1 | ICV_RESP_2 | ICV_RESP_3 ...

   ICV_INIT_1, ICV_INIT_2, ICV_INIT_3, etc. represent the content of the
   Integrity Checksum Data field from the Encrypted payloads (or
   Encrypted Fragment payloads) from all the IKE_AUX messages sent by
   the initiator in an order of increasing MessageIDs (and increasing
   Fragment Numbers for the same Message ID).  ICV_RESP_1 | ICV_RESP_2 |
   ICV_RESP_3 etc. are defined similarly for the messages sent by the
   responder.

