timeStamp='14 May 2000 13:32:00 -0800'>
lastUpdate='14 May 2000 13:02:00 -0800'>
actions='core:data presence:subscribe' />
timeStamp='14 May 2000 13:32:00 -0800'> ... </set>
timeStamp='14 May 2000 13:53:00 -0800'> ... </set>
lastUpdate='14 May 2000 13:02:00 -0800'>
actions='core:data presence:subscribe presence:watch' />
lastUpdate='14 May 2000 13:20:00 -0800'>
actions='core:data' />
