from='http-service.example.org'
to='pubsub.example.org'
id='publish1'>
xmlns='http://purl.org/atom/ns#draft-ietf-atompub-format-01'>
             <title>Atom-Powered Robots Run Amuck</title>
             <link rel='alternate'
type='text/html'
href='http://example.org/2003/12/13/atom03'/>
to='alice@example.net'>
xmlns='http://purl.org/atom/ns#draft-ietf-atompub-format-01'>
             <title>Atom-Powered Robots Run Amuck</title>
             <link rel='alternate'
type='text/html'
href='http://example.org/2003/12/13/atom03'/>
from='http-service.example.org'
to='pubsub.example.org'
id='publish2'>
xmlns='http://purl.org/atom/ns#draft-ietf-atompub-format-01'>
             <title>Atom-Powered Robots Run Amok</title>
             <link rel='alternate'
type='text/html'
href='http://example.org/2003/12/13/atom03'/>
to='alice@example.net'>
xmlns='http://purl.org/atom/ns#draft-ietf-atompub-format-01'>
             <title>Atom-Powered Robots Run Amok</title>
             <link rel='alternate'
type='text/html'
href='http://example.org/2003/12/13/atom03'/>
from='http-service.example.org'
to='pubsub.example.org'
id='delete1'>
to='alice@example.net'>
