A = X2+Z2
AA = A^2
B = X2 - Z2
BB = B^2
E = AA - BB
C = X3 + Z3
D = X3 - Z3
DA = D*A
CB = C*B
X5 = Z1*(DA+CB)^2
Z5 = X1*(DA-CB)^2
X4 = AA*BB
Z4 = E*(BB+a24*E)

A = Z1*Z2
B = A^2
C = X1*X2
D = Y1*Y2
E = d*C*D
F = B-E
G = B+E
X3 = A*F*((X1+Y1)*(X2+Y2)-C-D) 
Y3 = A*G*(D-a*C)
Z3 = F * G

y=Y/Z, and to convert affine to projective one takes (x,y,1).

