operation=add name

listtype="search 'other'"
operation=list

operation=bind


operation=bind
user=UserName
password=Password
version=SWTPversion
timezone=Timezone
operation=bindserver
name=Name
password=Password
version=SWTPversion
timezone=Timezone
currentdate=date

operation=unbind

name=value pair, and the messageID.  The message starts with the first
