xmlns="urn:ietf:params:xml:ns:pidf"
entity="pres:alice@example.com">
xmlns="urn:ietf:params:xml:ns:pidf"
entity="pres:alice@example.com">
targetNamespace="urn:ietf:params:xml:ns:pidf:dynamic"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

type="dyn:directionType"/>
type="xs:double"/>
type="dyn:directionType"/>
type="xs:double"/>
minOccurs="0" maxOccurs="unbounded"/>
North = [ -1 * sin(latitude) * cos(longitude),
                -1 *  sin(latitude) * sin(longitude),
                cos(latitude) ]

Up = [ cos(latitude) * cos(longitude),
             cos(latitude) * sin(longitude),
             sin(latitude) ]


