uuid-uri       = "uuid:" uuid [qualifiers]
uuid           = 8hex "-" 4hex "-" 4hex "-" 4hex "-" 12hex
qualifiers     = [";" name = value]*
hex            = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" |
                    "8" | "9" | "a" | "b" | "c" | "d" | "e" | "f" |
                    "A" | "B" | "C" | "D" | "E" | "F"

