CypherSuiteLng = 2, CypherSuite is the cypher suite used in
            groupcast extended RBridge Channel data messages for the
            corresponding KeyID2. This is a DTLS [RFC6347] cypher suite.

CypherSuiteLng = variable, CypherSuite is an IKEv2 crypto
            algorithm "proposal" [RFC7296].

