persistent   = ""
               The persistent state is the default for all elements and
               does not require a "marker".  Persistent elements must
               be recreated in every object/directory subset defined by
               a schema.

transient   = "~"
               Transient elements may be added or removed freely;
               regardless of schema.
static      = "@"
               "persistent" elements that reference an identical
               location/value; regardless of object instance.

constant   = "$"
              An element that cannot be moved, translated, or resolved
              to another path.

link       = "="
              Identifies the UOL as a linked reference.  For example, 
              a variable within formula or data cell.

comment    = "!"
              Identifies the UOL as a references to a "comment" value.
              The comment provides specific details regarding the 
              attribute described by the UOL.

result = "//..obj1/dir/..obj2/field_2#name1.name2"
result = "//..obj1/dir/..obj2/..obj3/field_3#name1.name2.name3"

result = "//..obj1/dir/field_2#name1"

result = "//..obj1/dir/..obj3/field_3#name1.name3"

result = "//..obj1/dir/dir_2/field_4#name1"

