name="xxxyyy" /> and place it at the top level below the "rules"
tag="arabic-indic-digits" />
tag="extended-arabic-indic-digits" />
comment="non-empty label of preferred code points">
match="preferred" />
comment="filter out by blocked code point" />
only-variants="s-preferred both-preferred"
comment="only allocate if s-referred variant,
only-variants="t-preferred both-preferred"
comment="only allocate if t-preferred variant,
any-variant="s-preferred t-preferred"
comment="filter out any remaining variant code point" />
xmlns="http://relaxng.org/ns/structure/1.0">
