Depth = 1 or infinity locks the targets of the direct references in the 
Ref-Target = "Ref-Target" ":" Coded-url

Ref-Type = "Ref-Type" ":" ("DAV:direct" | "DAV:redirect") 

Ref-Integrity = "Ref-Integrity" ":" ("DAV:weak")

Re-Direct = "Re-Direct" ":"

Hide-Target = "Hide-Target" ":"

Resource-Type = "Resource-Type" ":" ["DAV:collection" | "DAV:reference" 
                                     |""]

Ordered = "Ordered" ":" ("DAV:unordered" | "DAV:custom" | Coded-url)


Position = "Position" ":" ("First" | "Last" | 
                           (("Before" | "After") Coded-url))

DAV-Collections = "DAV-Collections" ":" 1#collection-capability
collection-capability = "DAV:basicref" | "DAV:directref" | 
