value = 4 (Unsupported parameter).

Options = 1: repeat every day;
Options = 2: repeat every week;

Options = 3: repeat every month;

Options = 4: repeat every year;

Options = 5: repeat every Repeat-time-length.

type=19 (Invalid Operation) and error-value TBD6 (Attempted LSP
value="Unacceptable parameters" in the LSP object (with scheduled
