pad  = Shortest string to bring confounder
                             and plaintext to a length that's a
                             multiple of M
H1 = HMAC(Ki, conf | associated data |
                                plaintext | pad)
ciphertext = C1 | H1[1..h]
conf = P1[1..c]
signdata = conf | associated data | P1[c+1..]
Ke = KDF-CMAC(base-key, usage | 0xAA)

Ke = KDF-CMAC(base-key, usage | 0xAA)

Ke = KDF-HMAC-SHA256(base-key, usage | 0xAA)
