update_flag = 1. The parameter MIN_UPDATE_INTERVAL determines the
length = (LEN(1) * 256) + LEN(0)

TYPE = 5 thru 7 are RESERVED for future use.



TYPE = 11 thru 15 are reserved for future use.



N = LEN / 4

N = LEN / 5

N = LEN / 5

length = 1 + (N * 5) + # padding octets

length = 4 + 2 + 2 + (NNBR * 8)

length = 4 + 2 + (NNBR * 8)

TYPE = 20 thru 31 are RESERVED for future use.
N = (LEN / 4) - 1

REMAINDER = LEN - ((N+1) * 4) -1 M = REMAINDER / 6

N = (LEN / 4) - 1

N = (LEN / 4)

length = 1 + (N * 4)

length = 4 + 4 + (NNBR * 4)

length = 4 + 2 + (NNBR * 4)

TYPE = 37 thru 47 are RESERVED for future use.


length = 4 + 2 + 2 + (NNBR * 6)

length = 4 + 2 + 2 + (NNBR * 6) +2

length = 4 + 4 + (NNBR * 4)

length = 4 + 2 + (NNBR * 4)

TYPE = 50 thru 63 are RESERVED for future use.


