type="asn1:VisibleString"/>
name="GSER-EncodingInstructionNotation"
identifier="1.3.6.1.4.1.21472.1.0.2"
schemaIdentity=
           "http://xmled.info/id/ASN.1/GSER-EncodingInstructionNotation"
targetNamespace="http://xmled.info/ns/ASN.1"
extensibilityImplied="true">

identifier="1.3.6.1.4.1.21472.1.0.1"
schemaIdentity=
                "http://xmled.info/id/ASN.1/AbstractSyntaxNotation-X"
namespace="http://xmled.info/ns/ASN.1"/>

type="gser:GSER-ChoiceOfStringsInstruction"/>
