MAC=0005:64FF:F988     |Box100-1|
                                        @:4::1:1   _,,.-0---2----+
MAC=0005:64FF:FD00             @:4::3:1\    .'                    ```'--.,,
       |              MAC=0005:64FF:F9C8 \_,'                       -`      '
       |                                ,'.                        |         |
       |                             _.`  \                         .       .
       |                           ,'      \                         `''-''`
       |                         .`         \                       CERNET 2
       |                      ,-`            \
    +--0-----+           /---`-\          +---0----+
    |Box300-1|2-----------     ----------2|Box300-2|
    1--------+@:5::3:3   |SW3-C|  @:5::3:2+--------1,
   /       192.168.3.3   |     |  192.168.3.2        '.
  -                      \-----/                       `'



          Figure 6: Tsinghua University Test Network AS300 Detail
