Error-value=12: LSP-DB-VERSION TLV missing
Error-value=2:  LSP Database version mismatch.
Error-value=3:  The LSP-DB-VERSION TLV Missing when
                                 state synchronization avoidance is
                                 enabled.
Error-value=4:  Attempt to trigger a synchronization
                                 when the TRIGGERED-SYNC capability has
                                 not been advertised.
Error-value=5:  No sufficient LSP change information
                                 for incremental LSP state
                                 synchronization.






Error-value=6:  Received an invalid LSP DB Version
                                 Number

