pinning_secret = HKDF(xSS + xES, "pinning secret", L)
pinning_protection_key = HKDF(resumption_protection_key,
                                 "pinning protection", L)

proof = HMAC(original_pinning_secret, "pinning proof" + crlen +
           client.random + srlen + server.random +
           Hash(server_public_key))

CN=example.com" -key "example.com.key" -out "example.com.csr";"

