Variants        = 1#variant-item
variant-item    = field-name *( OWS ";" OWS available-value )
available-value = token

Variant-Key      =  available-values
available-values = available-value *( ";" available-value )

