P-Served-User            = "P-Served-User" HCOLON PServedUser-value
                                           [SEMI sessioncase-param]
                                           [SEMI registration-state-param]
                                           *( SEMI generic-param )
PServedUser-value        = name-addr / addr-spec
sessioncase-param        = "sescase" EQUAL "orig" / "term"
registration-state-param = "regstate" EQUAL "unreg" / "reg"

   EQUAL, HCOLON, name-addr, addr-spec and generic-param are defined in
   RFC 3261 [2].

   The following is an example of a P-Served-User header field:
   P-Served-User: <sip:captain@buzz.com> ; sescase=orig; regstate=reg


