DefToneString = "(" DefToneElement ["*" RepeatCount ] ")" 
      [","/"+"/"X" DefToneString] 
    
RepeatCount = %d1-32767 / %d0 
      NOTE: repeatcount of 0 indicates infinite repeating. 
    
DefToneElement = ToneName ["," ToneDuration [ "," ToneAmplitude ]] 
    
ToneName = (Package id, Tone id) / "#"FreqValue  / 
FreqValue = %d0-4000; in Hertz 
AnnouncementParameterList = AnnouncementID ["," SubstitutionString] 
AnnouncementID = 1*VCHAR; Unique identifier for an audio 
SubstitutionString = """1*VCHAR"""; a string to be inserted into an 
ToneDuration = %d1-32767 / %d0 ; In Milliseconds 
ToneAmplitude = "-"%d32-1 / %d0; In dBm0 
 
