sig-a-tag-k =/ "ed25519"

key-k-tag-type  =/ "ed25519"

d=football.example.com; i=@football.example.com;
q=dns/txt; s=brisbane; t=1518460054; h=from : to :
bh=4bLNXImK9drULnmePzZNEBleUanJCX5PIsDIFoH4KTQ=;
b=9/dsDChY0YMTtD5Eyw3wx7x22BlSJP7M5ECbJ7GWrR45nXlTCGb8l0YB
d=football.example.com; i=@football.example.com;
q=dns/txt; s=test; t=1527915362; h=from : to : subject :
bh=4bLNXImK9drULnmePzZNEBleUanJCX5PIsDIFoH4KTQ=;
b=icKcLSEZYXJ95flvWE8FT6hl5iqd8MC/LEKYH0QjsqYy6MO/4pgVNCZH
p= and k= text.
