xmlns="urn:ietf:params:xml:ns:yang:ietf-zerotouch-information">
xmlns="urn:ietf:params:xml:ns:yang:ietf-zerotouch-information">
xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
device=123456 HTTP/1.1
xmlns="urn:ietf:params:xml:ns:yang:ietf-zerotouch-bootstrap-server">
device=123456/notification HTTP/1.1
xmlns="urn:ietf:params:xml:ns:yang:ietf-zerotouch-bootstrap-server">
