Tcur = "A"       (i.e., for some reason, the instance has reverted to
                   the value already in the client's cache).  The server
                   must return a 304 (Not Modified) response, as
                   required by the HTTP/1.1 specification for
                   ``If-None-Match''.

Tcur = "B"       (i.e., the instance has not changed again).  The
                   HTTP/1.1 specification for ``If-None-Match'', in this
                   case, is that the header field is ignored (by a
                   server that does not understand delta encoding).
                   Therefore, this is equivalent to the client's
                   previous request, except that the Range selection is
                   applied after content-coding.  So the (delta-aware)
                   server again computes the delta between the "A"
                   instance and the "B" instance (or uses a cached
                   computation of the delta), then applies the Range
                   selection, and returns a 227 (Range of Delta)
                   response, with an entity body containing bytes 900 to
                   999 of the result of the vcdiff encoding.

Tcur = "C"       (i.e., the instance has changed again).  In this
                   case, the HTTP/1.1 specification for
                   ``If-None-Match'' again means that this is equivalent
                   to an unconditional request for the current instance.
                   The specification for ``If-Range'' requires the
                   server to return the entire current entity.  However,
                   a delta-aware server can construct the delta between
                   the "A" instance described by the ``If-None-Match''
                   field and the current ("C") instance, and return a
                   226 (Delta) response.

content-coding = token | delta-content-coding
delta-content-coding = token

transfer-coding = token | delta-transfer-coding
delta-transfer-coding = token
Delta-Base = "Delta-Base" ":" entity-tag

DCluster = "DCluster" ":" #( <"> uri-prefix <">)
uri-prefix = scheme ":" "//" host [ ":" port ] [ abs_path ]
               | abs_path
               | rel_path

DTemplate = "DTemplate" ":"
                        #( <"> dt-uri <"> [ "/" dt-param])
dt-uri = absoluteURI | abs_path
dt-param = "etag" "=" entity-tag

