total_cycles = message_size * cycles_per_bit + cycles_per_message 
    
total_cycles = cycles_per_message + message_size * cycles_per_bit 
    


memory_address = (memory_address_of_instruction + delta) modulo 2^16 
    
parameter_1 = parameter_2 then it jumps to the address specified by 
parameter_value = (instruction_address - label_address) modulo 2^16 
    
