x = x_{l-1}256^{l-1} + x_{l-2}256^{l-2} +... + x_1 256 + x_0

X = X_1 X_2 ... X_l.

EM = EME-OAEP-ENCODE (M, P, k-1)

c = RSAEP ((n, e), m)

c = OS2IP (C).

m = RSADP (K, c)

M = EME-OAEP-DECODE (EM, P)

EM = EME-PKCS1-V1_5-ENCODE (M, k-1)

c = OS2IP (C).
EM = EMSA-PKCS1-V1_5-ENCODE (M, k-1)

s = OS2IP (S)

m = RSAVP1 ((n, e), s)
		
DB = pHash' || PS || 01 || M

EM = 02 || PS || 00 || M

H = Hash(M).

T = T || Hash (Z || C)

