v=0
o=- 53655765 2353687637 IN IP4 as.com
s=-
c=IN IP4 as.com
t=0 0
m=application 5757 TCP/SCFW
a=setup:active
a=connection:new
a=ctrl-package:msc-ivr-basic/1.0
a=ctrl-package:msc-conf-audio/1.0



v=0
o=- 53655765 2353687638 IN IP4 ms.org
s=MediaCtrl
c=IN IP4 ms.org
t=0 0
m=application 7575 TCP/SCFW *
a=connection:new
a=setup:passive
a=ctrl-package:msc-ivr-basic/1.0
a=ctrl-package:msc-conf-audio/1.0
a=ctrl-package:msc-ivr-vxml/1.0


id2="1536067209~913cd14c">
type="audio/wav"/>
reason="Dialog started" dialogid="05ded7b"/>


size="161644" type="audio/wav" \
recording="http://www.ms.org/recording-05ded7b.wav"/>
type="audio/wav"/>
reason="Dialog started" dialogid="6faf4e0"/>


duration="10000" iterations="1"/>
id2="00c09fc35b07~d5d85047">
type="audio/wav"/>
type="audio/wav"/>
type="audio/wav"/>
dialogid="6jwwf5r"/>


type="audio/wav"/>
dialogid="1aa30g5"/>


conferenceid="1cc1a27"/>


id2="1cc1a27">
id2="1cc1a27">
id2="1cc1a27">
direction="recvonly"/>
type="audio/wav"/>
dialogid="2fe9bf0"/>


type="audio/wav"/>
dialogid="15b3128"/>


size="67500" termmode="dtmf" \
recording="http://www.ms.org/recordings/recording-15b3128.wav"/>

           <dialogexit/>
        </event>


id2="1cc1a27">
type="audio/wav"/>
type="audio/wav"/>
dialogid="0aa23bc"/>


