S_main_addr == given Address

S_main_addr == given Address

S_time = current time + NODE_STATE_HOLD_TIME
S_main_addr == Originator Address

S_last_hello_time    = current time

S_last_hello_seq_num = HELLO message sequence number
S_main_addr == Originator Address

S_last_tc_time    = current time

S_last_tc_seq_num = TC message sequence number


S_main_addr = given address, AND

D_addr          = Originator Address

D_seq_num       = Message Sequence Number

D_retransmitted = true

D_time          = current time + DUP_HOLD_TIME

D_content_id    = computed message content identifier
D_addr    == Originator Address, AND

D_seq_num == Message Sequence Number

D_content_id == computed message content identifier

D_addr    == Originator Address, AND

D_seq_num == Message Sequence Number

S_main_addr == Originator Address, AND

D_addr    == Originator Address, AND

D_seq_num == Message Sequence Number

D_addr       == Originator Address, AND

D_seq_num    == Message Sequence Number, AND

D_content_id == computed message content identifier (see
D_addr    == Originator Address, AND

D_seq_num == Message Sequence Number, AND

N_neighbor_main_addr == 2-hop neighbor address, AND

N_neighbor_main_addr == 2-hop neighbor address, AND

N_2hop_addr == Originator address

S_main_addr == address, AND

N_neighbor_main_addr == S_main_addr

N_neighbor_main_addr == S_main_addr

N_status == SYM


HELLO_WITH_STATE_MESSAGE = 130

TC_WITH_STATE_MESSAGE = 131

