HELD-URI = "held" ":" "//" [ location-id "@" ] host [ ":" port ]
             [ path-absolute ] [ uri-extensions ]

location-id = token

uri-extensions = "?" extension *(COMMA extension)

extension = generic-param

generic-param =  token [ EQUAL gen-value ]

gen-value    =  token / host / quoted-string

token =  1*(alphanum / "-" / "." / "!" / "%" / "*"
                        / "_" / "+" / "`" / "'" / "~" )


targetNamespace="urn:ietf:params:xml:ns:geopriv:held"
elementFormDefault="qualified"
attributeFormDefault="unqualified">
maxOccurs="unbounded"/>
use="required"/>
use="optional" default="false"/>
use="optional"/>
use="required"/>
use="optional"/>
type="held:returnLocationType"
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
type="held:locationResponseType"/>


type="held:locationTypeType"
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
type="held:locationRequestType"/>

entity="pres:3650n87934c@ls.example.com">
srsName="urn:ogc:def:crs:EPSG::4326">
code="locationUnknown"
message="Unable to determine location"/>

code="locationUnknown"
message="Location not available"/>
entity="pres:ae3be8585902e2253ce2@10.102.23.9">
srsName="urn:ogc:def:crs:EPSG::4326">
