type="gplo:LocationObjectType"/>

minOccurs="0"/>
minOccurs="0"/>
type="gplo:TargetIdentifierType"/>
use="optional"/>
type="gplo:DeviceIdentifierType"/>
use="optional"/>
type="gplo:RuleMakerIdentifierType"/>
ref="gplo:RuleMakerIdentifierAttribute"/>
use="optional"/>
targetNamespace="urn:ietf:geopriv:lo:0.0.4"
elementFormDefault="qualified"
attributeFormDefault="unqualified"
version="0.0.4">

minOccurs="0"/>
minOccurs="0"/>
type="gplo:TargetIdentifierType"/>
type="gplo:DeviceIdentifierType"/>
type="gplo:RuleMakerIdentifierType"/>
type="gplo:LocationRecipientType"/>

type="gplo:LocationRecipientIdentifierType"/>
ref="gplo:LocationRecipientIdentifierAttribute"/>
type="gplo:LocationRecipientCredentialType"/>

type="xs:string"/>
type="gplo:ApplicableRuleType"/>
type="gplo:ApplicableRuleType"
minOccurs="1"/>
type="gplo:LimitedRuleType"
minOccurs="1"/>
type="gplo:LocationInformationType"
minOccurs="0"
maxOccurs="unbounded"/>
type="gplo:LocationRepresentationType"
minOccurs="0"
maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="1"/>
minOccurs="1"/>
minOccurs="0"/>
type="gplo:LatLonAltPrecisionType"
minOccurs="0"/>
type="gplo:LatDegIntMinIntSecIntType"/>
type="gplo:LatDegMinSecDecType"/>
type="gplo:LatDegIntMinSecDecType"/>
type="gplo:LonDegIntMinIntSecIntType"/>
type="gplo:LonDegMinSecDecType"/>
type="gplo:LonDegIntMinSecDecType"/>
xmlns="urn:ietf:geopriv:lo:0.0.4"
IdentifierType="NonAnonymous"
CastType="MultiCast">
