tn=12125550000 and endTn=12125560000 means all the TNs from
minOccurs="0"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs=" unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
type="spppb:SourceIdentSchemeType"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
type="spppb:RteGrpOfferKeyType"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
type="spppb:RteGrpOfferKeyType" minOccurs="0"
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
        <clientTransId>txid-5555</clientTransId>
        <rqst xmlns:ns1="urn:ietf:params:xml:ns:sppp:base:1"
          xsi:type="ns1:AddDestGrpRqstType">
          <destGrp>
            <ns1:rantId>iana-en:222</ns1:rantId>
            <ns1:rarId>iana-en:222</ns1:rarId>
            <dgName>DEST_GRP_SSP2_1</dgName>
          </destGrp>
        </rqst>
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
        <clientTransId>tx_7777</clientTransId>
        <serverTransId>tx_id_12346</serverTransId>
        <overallResult>
          <code>1000</code>
          <msg>success</msg>
        </overallResult>
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
xmlns="urn:ietf:params:xml:ns:sppp:base:1">
xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="urn:ietf:params:xml:ns:sppp:base:1"
elementFormDefault="qualified" xml:lang="EN">
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
type="spppb:SourceIdentSchemeType"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
type="spppb:RteGrpOfferKeyType" />
type="spppb:RteGrpOfferKeyType"/>
type="spppb:RteGrpOfferKeyType"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
type="spppb:RteGrpOfferKeyType" minOccurs="0"
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
type="spppb:RqstObjResultCodeType" minOccurs="0"
maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0" maxOccurs=" unbounded"/>
minOccurs="0"/>
