L = Length included. 
M = More fragments 
S = EAP-TLS start, set in an EAP-TLS Start message. 
R = Reserved 
   
EAP-Type=EAP-TLS 
EAP-Type=EAP-TLS 
EAP-Type=EAP-TLS 
EAP-Type=EAP-TLS 
EAP-Type=EAP-TLS 
EAP-Type=EAP-TLS -> 
                             <- EAP-Success 
   
