RG=M and was ACK'd on a send to RG=M

                                  Figure 8



                    SYNFROM  SYNACKTO  ACKFROM   SELECT
                    W        W         X         W
                    ------------------------------------
                    W
                    X        W         X         W
                    ------------------------------------
                    W        W
                    X        X         Y         ??

                                  Table 1

