x=1 implies that a mobile network has only one SIP-NMS.

x=n implies that a mobile network has more than one SIP-NMS.

y=1 implies that a SIP-NMS has only one E-face.

y=n implies that a SIP-NMS has more than one E-face.

