uri-parameter =/ iotl-param
iotl-param    = iotl-tag "=" iotl-value ["." iotl-value]
iotl-tag      = "iotl"
iotl-value    = "homea-homeb" / "homeb-visitedb" / "visiteda-homea"
                   / "homea-visiteda" / "visiteda-homeb" / other-iotl
other-iotl    = 1*iotl-char
iotl-char     = alphanum / "-"
