signed_data = RRSIG_RDATA | RR(1) | RR(2)...  where

            "|" denotes concatenation

            RRSIG_RDATA is the wire format of the RRSIG RDATA fields
               with the Signature field excluded and the Signer's Name
               in canonical form.

            RR(i) = name | class | type | OrigTTL | RDATA length | RDATA

               name is calculated according to the function below

               class is the RRset's class

               type is the RRset type and all RRs in the class

               OrigTTL is the value from the RRSIG Original TTL field

               All names in the RDATA field are in canonical form

               The set of all RR(i) is sorted into canonical order.

            To calculate the name:
               let rrsig_labels = the value of the RRSIG Labels field

               let fqdn = RRset's fully qualified domain name in
                               canonical form

               let fqdn_labels = RRset's fully qualified domain name in
                               canonical form

               if rrsig_labels = fqdn_labels,
name = fqdn

name = "*." | the leftmost rrsig_label labels of the
                                fqdn
lnX6XA3eeDlQlOTuPe0B91MCuow= )
cfnJlZyJcfwY0ETo4P2gntVMERZuJQ==
iHQEOrm7yXIHwnrre1iuzMZn1jY= )
FxfIqrcIL24dO4Ytdz2ifqvJmuM= )
vOHmndDhRTDwVCg179qlrEIsOgE= )
IKZXg2219TD4UqJuRATLhxZj2fU= )
AAwDzum3fUKzVM274T9O8ggeXgE= )
IKZXg2219TD4UqJuRATLhxZj2fU= )

iHQEOrm7yXIHwnrre1iuzMZn1jY= )

FxfIqrcIL24dO4Ytdz2ifqvJmuM= )

vOHmndDhRTDwVCg179qlrEIsOgE= )

