I = I - (2^N - 1)
I = I / 128
I = 1337 - (2^5 - 1) = 1306.



         I (1306) is greater than or equal to 128, the while loop body
         executes:
            I % 128 == 26

            26 + 128 == 154

            154 is encoded in 8 bits as: 10011010

            I is set to 10 (1306 / 128 == 10)

            I is no longer greater than or equal to 128, the while loop
            terminates.

         I, now 10, is encoded on 8 bits as: 00001010

LOWERALPHA = %x61-7A
header-char = "!" / "#" / "$" / "%" / "&" / "'" /
                   "*" / "+" / "-" / "." / "^" / "_" /
                   "`" / "|" / "~" / DIGIT / LOWERALPHA
header-name = [":"] 1*header-char

