xmlns="urn:ietf:params:xml:ns:common-policy"
targetNamespace="urn:ietf:params:xml:ns:saml-condition"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

schemaLocation="common-policy.xsd"/>

maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>

minOccurs="0" maxOccurs="unbounded"/>

minOccurs="0" maxOccurs="unbounded"/>

targetNamespace="urn:ietf:params:xml:ns:common-policy"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

minOccurs="0" maxOccurs="unbounded"/>
type="xs:string" use="required"/>
minOccurs="0" maxOccurs="unbounded">
type="xs:string" use="required"/>
minOccurs="0" maxOccurs="unbounded">
type="xs:string" use="required"/>
minOccurs="0" maxOccurs="unbounded">
type="xs:string" use="required"/>
minOccurs="0" maxOccurs="unbounded">
type="xs:string" use="required"/>
minOccurs="0" maxOccurs="unbounded">
type="xs:string" use="required"/>
minOccurs="0" maxOccurs="unbounded"/>

minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded" />
