pn-provider=acme;
pn-param=acme-param;
pn-prid="ZTY4ZDJlMzODE1NmUgKi0K">
pns-list        = pns *(COMMA pns)
pns             = pvalue

uri-parameter   =/ pn-provider / pn-param / pn-prid / pn-enccode /
                        pn-enckey
pn-provider     = "pn-provider" EQUAL pvalue
pn-param        = "pn-param" EQUAL pvalue
pn-prid         = "pn-prid" EQUAL pvalue
pn-enccode      = "pn-enccode" EQUAL pvalue
pn-enckey       = "pn-enckey" EQUAL pvalue

