manufacturer-endorsement-claim = (
manufacturer-endorsement => bytes,
version-endorsement-claim = (
version-endorsement => bytes,
model-endorsement-claim = (
model-endorsement => bytes,
field-upgradable-claim = (
field-upgradable => bool,
secret-origination-claim = (
secret-origination => internal / external
internal = 0
external = 1

common-criteria-claim =(
common-criteria => [ any-uri,
                          hash,
                        ]
any-uri = text

hash = [ hash-alg-id: int,
            hash-value: bytes,
          ]

