in-reply-to =
       element thr:in-reply-to {
         atomCommonAttributes,
         ref,
         href?,
         source?,
         type?,
         ( undefinedContent )
       }

ref = attribute ref { atomURI }
href = attribute href { atomURI }
type = attribute type { atomMediaType }
source = attribute source { atomURI }


type="application/xhtml+xml"
href="http://www.example.org/entries/1" />
ref="tag:example.org,2005:1"
type="application/xhtml+xml"
href="http://www.example.org/entries/1"/>
ref="tag:example.org,2005:1,0"
type="application/xhtml+xml"
href="http://www.example.org/entries/1"
source="http://www.example.org/myfeed" />
rel="related"
type="application/xhtml+xml"
href="http://www.example.org/entries/1" />
type="application/atom+xml"
href="http://www.example.org/mycommentsfeed.xml"
total = element thr:total { xsd:nonNegativeInteger }

