REQUEST =
     INTERNAL_ADDRESS(0.0.0.0),
     INTERNAL_NETMASK(0.0.0.0),
     INTERNAL_DNS(0.0.0.0)
REPLY =
     INTERNAL_ADDRESS(192.168.219.202),
     INTERNAL_NETMASK(255.255.255.0),
     INTERNAL_DNS(291.168.219.4)

REQUEST = APPLICATION_VERSION("")
REPLY = APPLICATION_VERSION("foobar v1.3beta, (c) Foo Bar Inc.")


