type=TBD3 for SRv6.

Error-value=TBD4 (SRv6 capability was not advertised) and

Error-value = TBD4 :                 SRv6 capability was
                                                     not advertised

