Strm=0,Seq=1 & user data]--\
Frag=0]      --------\  /        [TSN=init TSN_Z +1,
                            \/          Strm=0,Seq=2 & user data 2]
                     <------/\          
                              \
                               \------>

N = min(cwnd, rwnd) - fsize. The sender shall then update its
ssthresh = max(fsize/2, 2)
cwnd = ssthresh/2

cwnd = 1, which assures that no more than one DATA chunk will be in
