SFC-ID=1 | Balancer |--|  Proxy   |--|   wall   |--|  NAT44   |
             | SF-ID=1  |  | SF-ID=2  |  | SF-ID=3  |  |  SF-ID=4 |
             +----------+  +----------+  +----------+  +----------+

             +----------+  +----------+  +----------+
             |          |  | Header   |  |   Fire   |
SFC-ID=2 |   DPI    |--| enrichm. |--|   wall   |
             | SF-ID=6  |  | SF-ID=5  |  | SF-ID=3  |
             +----------+  +----------+  +----------+

                 Figure 1: Service Function Chain examples

