requestId="10"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="10"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
entity="sip:McuConf1@company.com"
xmlns="urn:ietf:params:xml:ns:conference-info">
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
entity="sip:McuConf1@company.com"
xmlns="urn:ietf:params:xml:ns:conference-info">
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
entity="sip:McuConf1@company.com"
xmlns="urn:ietf:params:xml:ns:conference-info">
             <conference-description>
              <subject>Spec Review</subject>
             </conference-description>
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:McuConf1@company.com"/>
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"/>
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
entity="sip:McuConf1@company.com"
xmlns="urn:ietf:params:xml:ns:conference-info">
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"/>
xmlns="urn:ietf:params:xml:ns:conference-info">
            <display-text>Bob Hoskins</display-text>
            <roles>
            <entry>presenter</entry>
            </roles>
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"/>
             <user entity="sip:bob@example.com"
xmlns="urn:ietf:params:xml:ns:conference-info">
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"
userEntity="sip:bob@example.com"/>
xmlns="urn:ietf:params:xml:ns:conference-info">
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"
userEntity="sip:bob@example.com"/>
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"
userEntity="sip:bob@example.com"/>
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
xmlns="urn:ietf:params:xml:ns:conference-info">
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"
userEntity="sip:bob@example.com"/>
             <endpoint entity="sip:bob@pc4.example.com"
xmlns="urn:ietf:params:xml:ns:conference-info">
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"
userEntity="sip:bob@example.com"/>
             <endpoint entity="sip:bob@pc4.example.com"
xmlns="urn:ietf:params:xml:ns:conference-info">
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"
userEntity="sip:bob@example.com"
endpointEntity="sip:bob@pc33.example.com"/>
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"
userEntity="sip:bob@example.com"
endpointEntity="sip:bob@pc33.example.com"/>
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"
userEntity="sip:bob@example.com"/>
             <endpoint entity="sip:bob@pc4.example.com"
xmlns="urn:ietf:params:xml:ns:conference-info">
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"
userEntity="sip:bob@example.com"
endpointEntity="sip:bob@pc33.example.com"/>
xmlns="urn:ietf:params:xml:ns:conference-info">
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"
userEntity="sip:bob@example.com"
endpointEntity="sip:bob@pc33.example.com"/>
xmlns="urn:ietf:params:xml:ns:conference-info">
                              <type>audio</type>
                              <status>recvonly</status>
                      </media>
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"
userEntity="sip:bob@example.com"
endpointEntity="sip:bob@pc33.example.com"
mediaId="1"/>
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
requestId="1"
from="https://company.com:444/Client"
to="https://Mcu55.company.com:444/MCU"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"
userEntity="sip:bob@example.com"
endpointEntity="sip:bob@pc33.example.com"
mediaId="1"/>
requestId="1"
from= "https://Mcu55.company.com:444/MCU"
to= "https://company.com:444/Client"
code="success"
xmlns="urn:ietf:params:xml:ns:cccp"
confEntity="sip:conf233@example.com"
userEntity="sip:bob@example.com"
endpointEntity="sip:bob@pc33.example.com"/>
xmlns="urn:ietf:params:xml:ns:conference-info">
                              <type>audio</type>
                              <status>recvonly</status>
                      </media>
targetNamespace="urn:ietf:params:xml:ns:cccp"
elementFormDefault="qualified"
attributeFormDefault="unqualified"
namespace="urn:ietf:params:xml:ns:conference-info"
schemaLocation="ci.xsd"/>

namespace="urn:ietf:params:xml:ns:conference-info-separator"
schemaLocation="ci-separator.xsd"/>

type="tns:cancel-type"/>
type="tns:ping-type"/>
type="tns:add-conference-type"/>
type="tns:add-conference-type"/>
type="tns:get-conference-type"/>
type="tns:delete-conference-type"/>
type="tns:add-user-type"/>
type="tns:add-user-type"/>
type="tns:modify-user-roles-type"/>
type="tns:get-user-type"/>
type="tns:delete-user-type"/>
type="tns:add-endpoint-type"/>
type="tns:add-endpoint-type"/>
type="tns:get-endpoint-type"/>
type="tns:delete-endpoint-type"/>
type="tns:add-endpoint-media-type"/>
type="tns:add-endpoint-media-type"/>
type="tns:get-endpoint-media-type"/>
type="tns:delete-endpoint-media-type"/>
minOccurs="0"
maxOccurs="unbounded"/>
type="xs:string" use="required"/>
use="optional"/>
type="tns:cancel-response-type"/>
type="tns:ping-response-type"/>
type="tns:add-conference-response-type"/>
type="tns:add-conference-response-type"/>
type="tns:get-conference-response-type"/>
type="tns:delete-conference-response-type"/>
type="tns:add-user-response-type"/>
type="tns:add-user-response-type"/>
type="tns:modify-user-roles-response-type"/>
type="tns:get-user-response-type"/>
type="tns:delete-user-response-type"/>
type="tns:add-endpoint-response-type"/>
type="tns:add-endpoint-response-type"/>
type="tns:get-endpoint-response-type"/>
type="tns:delete-endpoint-response-type"/>
type="tns:add-endpoint-media-response-type"/>
type="tns:add-endpoint-media-response-type"/>
type="tns:get-endpoint-media-response-type"/>
type="tns:delete-endpoint-media-response-type"/>
minOccurs="0"
maxOccurs="unbounded"/>
type="xs:string" use="required"/>
type="xs:anyURI" use="required"/>
type="xs:anyURI" use="required"/>
type="xs:anyURI" use="optional"/>
type="tns:response-code-type" use="required"/>
type="tns:reason-code-type" use="optional"/>
type="xs:string" use="optional"/>
type="xs:nonNegativeInteger" use="optional"/>
type="xs:nonNegativeInteger" use="optional"/>
processContents="lax"/>
processContents="lax"/>
processContents="lax"/>
processContents="lax"/>
minOccurs="0" maxOccurs="unbounded"/>
processContents="lax"/>
type="xs:string" minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
type="tns:cancel-reason-code-type" use="optional"/>
minOccurs="0" maxOccurs="unbounded"/>
type="tns:server-status-type" minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
type="tns:add-conference-reason-code-type" use="optional"/>
type="tns:conference-keys-type"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
type="tns:get-conference-reason-code-type" use="optional"/>
type="tns:conference-keys-type"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
type="tns:delete-conference-reason-code-type"
use="optional"/>
type="tns:conference-keys-type"/>
minOccurs="0" maxOccurs="unbounded"/>
type="tns:conference-keys-type" minOccurs="0"/>
maxOccurs="unbounded"/>
type="tns:add-user-reason-code-type" use="optional"/>
type="tns:user-keys-type"/>
minOccurs="0" maxOccurs="unbounded"/>
type="tns:conference-keys-type" minOccurs="0"/>
maxOccurs="unbounded"/>
type="tns:get-user-reason-code-type" use="optional"/>
type="tns:user-keys-type"/>
minOccurs="0" maxOccurs="unbounded"/>
type="tns:conference-keys-type" minOccurs="0"/>
maxOccurs="unbounded"/>
type="tns:get-user-reason-code-type" use="optional"/>
processContents="lax"/>
type="tns:user-keys-type"/>
maxOccurs="unbounded"/>
type="tns:conference-keys-type" minOccurs="0"/>
maxOccurs="unbounded"/>
type="tns:delete-user-reason-code-type" use="optional"/>
type="tns:user-keys-type"/>
maxOccurs="unbounded"/>
type="tns:user-keys-type" minOccurs="0"/>
maxOccurs="unbounded"/>
type="tns:add-user-reason-code-type" use="optional"/>
type="tns:endpoint-keys-type"/>
minOccurs="0" maxOccurs="unbounded"/>
type="tns:user-keys-type" minOccurs="0"/>
maxOccurs="unbounded"/>
type="tns:get-endpoint-reason-code-type" use="optional"/>
type="tns:endpoint-keys-type"/>
minOccurs="0" maxOccurs="unbounded"/>
type="tns:user-keys-type" minOccurs="0"/>
maxOccurs="unbounded"/>
type="tns:delete-endpoint-reason-code-type"
use="optional"/>
type="tns:endpoint-keys-type"/>
minOccurs="0" maxOccurs="unbounded"/>
type="tns:endpoint-keys-type" minOccurs="0"/>
maxOccurs="unbounded"/>
type="tns:add-endpoint-media-reason-code-type"
use="optional"/>
type="tns:media-keys-type"/>
minOccurs="0" maxOccurs="unbounded"/>
type="tns:endpoint-keys-type" minOccurs="0"/>
maxOccurs="unbounded"/>
type="tns:get-media-reason-code-type" use="optional"/>
type="tns:media-keys-type"/>
minOccurs="0" maxOccurs="unbounded"/>
type="tns:endpoint-keys-type" minOccurs="0"/>
maxOccurs="unbounded"/>
type="tns:get-media-reason-code-type" use="optional"/>
type="tns:server-description-type"
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
use="optional"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
content="text/html;charset=iso-8859-1"/>
