dkim=pass (whitelisted) header.i=@example.com
dnswl=pass dns.zone=list.dnswl.example dns.sec=na
client-ip=2001:db8::2:1;
envelope-from="sender@example.com";
helo=mail.fwd.example;
receiver=mta.example.org;
spf=pass smtp.mailfrom=example.net dns.sec=y;
dkim=pass header.i=@example.org header.b=jIvx30NG dns.s=tlsrpt

