from  = context.createSipAddress("Bell <sip:bell@nowhere.com");
to    = context.createSipAddress("Watson <sip:tom@example.com");
trans = context.createSipTransaction(from, to);
req   = trans.createRequest("INVITE");
SipAddress     = (name-addr | addr-spec) *(";" addr-params)
name-addr      = [display-name] "<" addr-spec ">"
addr-spec      = SIP-URL | URI
display-name   = *token | quoted-string

t = (SIP-date | delta-seconds)

statusCode = Integer.parseInt(
                                getInitParameter("status-code"));
reasonPhrase = getInitParameter("reason-phrase");
statusCode = SC_INTERNAL_SERVER_ERROR;
