uri-parameter = transport-param / user-param / method-param / ttl-param
                 / maddr-param / lr-param / iotl-param / other-param
iotl-param    = iotl-tag "=" iotl-value
iotl-tag      = "iotl"
iotl-value    = "homeA-homeB" / "homeB-visitedB" / "visitedA-homeA"
                 / "homeA-visitedA" /" visitedA-homeB" / gen-value

