rt=g.light) to infer which resources are present below the group
MIN_TOKEN_REUSE_TIME = (NON_LIFETIME + MAX_LATENCY +
                           MAX_SERVER_RESPONSE_DELAY)
MAX_SERVER_RESPONSE_DELAY = 250 seconds is a reasonable guideline.
