reserveconfmedia="no"/>
prompturl="http://prompts.example.net/us_EN/welcome.au"/>
            </request>
          </MediaServerControl>

             Figure 8: Full Conference Audio Command - Play
        <?xml version="1.0" encoding="utf-8"?>
          <MediaServerControl version="1.0">
            <request>
              <playrecord
recurl="file://archive.example.net/conferences/archives/011208.au"
beep="no"
initsilence="infinite"
endsilence="infinite" />
            </request>
reclength="1420374"/>
numlisteners="1382">
prompturl="http://prompts.example.net/us_EN/SayName.g711"
recurl="file://nfs.example.net/names/greet-joij34923119.wav"
recencoding="msgsm"
initsilence="15s"
endsilence="2s"
duration="8s">
url="http://prompts.example.net/pin_number.wav"/>
elementFormDefault="qualified">
minOccurs="0"/>
minOccurs="0"/>
type="activetalkersType"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
use="required"/>
default="yes"/>
default="6s"/>
default="#"/>
default="*"/>
default="*"/>
use="required"/>
default="01234567890*#"/>
type="activetalkersType"/>
use="required"/>
use="required"/>
