command-auth =/ view
                      ; command-auth is in [IMAP]

option-extension =/ "VIEW"
                      ; option-extension is in [LISTEXT]

view        = "VIEW" SP "CREATE" mailbox SP mailbox 1*(SP
                      search-key)

view-extended-item = "VIEW" SP "(" mailbox SP nstring ")"
                      ; see the open issues section


