xmlns="urn:ietf:params:xml:ns:forces:lfbmodel:1.0"
targetNamespace="urn:ietf:params:xml:ns:forces:lfbmodel:1.0"
elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xsd:annotation>
    <xsd:documentation xml:lang="en">
        Schema for Defining LFB Classes and associated types (frames,
        data types for LFB attributes, and metadata).
        </xsd:documentation>
  </xsd:annotation>
  <xsd:element name="description" type="xsd:string"/>
  <xsd:element name="synopsis" type="xsd:string"/>
  <!-- Document root element: LFBLibrary -->
  <xsd:element name="LFBLibrary">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="description" minOccurs="0"/>
        <xsd:element name="load" type="loadType" minOccurs="0"
maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0">
        <!-- Extension -->
        <xsd:key name="SpecialValue">
          <xsd:selector xpath="specialValue"/>
          <xsd:field xpath="@value"/>
        </xsd:key>
        <!-- /Extension -->
maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="contentKeyField" type="xsd:string"
maxOccurs="unbounded"/>
use="required"/>
minOccurs="0"/>
use="required"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
use="required"/>
maxOccurs="unbounded"/>
default="0"/>
maxOccurs="unbounded"/>
default="required">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="required"/>
              <xsd:enumeration value="optional"/>
            </xsd:restriction>
          </xsd:simpleType>
use="optional"/>
maxOccurs="unbounded"/>
default="0"/>
maxOccurs="unbounded"/>
type="metadataOutputChoiceType"/>
default="unconditional">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="unconditional"/>
              <xsd:enumeration value="conditional"/>
            </xsd:restriction>
          </xsd:simpleType>
minOccurs="0"/>
default="read-write">
            <xsd:simpleType>
              <xsd:list itemType="accessModeType"/>
            </xsd:simpleType>
use="required"/>
use="required"/>
minOccurs="0"/>
use="required"/>
substitutionGroup="eventCondition"/>
substitutionGroup="eventCondition"/>
substitutionGroup="eventPathPart"/>
substitutionGroup="eventPathPart"/>
maxOccurs="unbounded"/>
