xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
file="ietf-netconf-with-system@2021-05-14.yang"
file="ietf-system-datastore@2021-05-14.yang"
