I=10: Interval Duration - the reported value applies to the
I=11: Cumulative Duration - the reported value applies to the
I=01: Sampled Value - this value MUST NOT be used for this
I=00: Reserved.

V=10 - Frame freeze
V=11 - Other Loss Concealment Method
V=01&00 - Reserved

Type=10.

xr-format =/ xr-vlc-block

xr-vlc-block = "vlc"

