capability         =/ "X-DRAFT-I05-SEARCHRES"
                        ;; capability is defined in [IMAP4]

sequence-set       =/ seq-last-command
                        ;; extends sequence-set to allow for
                        ;; "result of the last command" indicator.

seq-last-command   = "$"

search-return-opt  = "SAVE"
                        ;; conforms to generic search-return-opt
                        ;; syntax defined in [IMAPABNF]



