version="1.00" lang="en-US"
attributeFormDefault="unqualified"
elementFormDefault="qualified"
targetNamespace="iodef-extension1.xsd"
namespace="urn:ietf:params:xml:ns:iodef-1.0"
schemaLocation="draft-ietf-inch-iodef-09.xsd"/>

version="1.00" lang="en-US"
xmlns="http://www.iana.org/iodef"
xmlns="urn:ietf:params:xml:ns:iodef-1.0"
xmlns="urn:ietf:params:xml:ns:iodef-1.0"
xmlns="urn:ietf:params:xml:ns:iodef-1.0"
xmlns="urn:ietf:params:xml:ns:iodef-1.0"
targetNamespace="urn:ietf:params:xml:ns:iodef-1.0"
elementFormDefault="qualified" attributeFormDefault="unqualified">

namespace="http://www.w3.org/2000/09/xmldsig#"
schemaLocation=
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
type="xs:string" fixed="1.00"/>
type="xs:language" use="required"/>
type="xs:string"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
type="xs:string" use="optional"/>
type="xs:language"/>
type="iodef:restriction-type" default="private"/>
type="xs:string" use="required"/>
maxOccurs="unbounded"/>
type="iodef:restriction-type"/>
maxOccurs="unbounded"/>
type="iodef:restriction-type"/>
type="iodef:ExtensionType"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
type="xs:string" use="optional"/>
type="xs:string" use="optional"/>
type="iodef:restriction-type"/>
type="iodef:MLStringType"/>
type="xs:string" use="optional"/>
type="iodef:MLStringType"/>
type="xs:string"/>
type="xs:string"/>
type="xs:string"/>
type="xs:dateTime"/>
type="xs:dateTime"/>
type="xs:dateTime"/>
type="xs:dateTime"/>
type="xs:dateTime"/>
type="iodef:TimezoneType"/>
maxOccurs="unbounded"/>
type="iodef:restriction-type" default="default"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
type="iodef:restriction-type"/>
type="iodef:action-type" default="other"/>
type="xs:string" use="optional"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
type="iodef:restriction-type" default="default"/>
type="iodef:severity-type"/>
type="iodef:action-type" default="other"/>
type="xs:string" use="optional"/>
minOccurs="0" maxOccurs="unbounded"/>
type="iodef:restriction-type"/>
type="iodef:MLStringType"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
type="iodef:restriction-type"/>
type="iodef:severity-type"/>
use="optional" default="unknown">
type="iodef:severity-type"/>
use="required">
type="xs:string" use="optional"/>
type="iodef:duration-type"/>
type="xs:string" use="optional"/>
type="iodef:severity-type"/>
type="xs:string"/>
use="required">
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
type="iodef:restriction-type" default="default"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
type="iodef:restriction-type"/>
type="xs:string"/>
type="xs:string" use="optional"/>
default="unknown">
type="iodef:MLStringType" minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
default="ipv4-addr">
type="xs:string" use="optional"/>
type="xs:string"/>
type="xs:integer"/>
type="iodef:MLStringType"/>
use="required">
type="xs:string" use="optional"/>
type="xs:integer"/>
type="iodef:PortlistType"/>
type="xs:integer" minOccurs="0"/>
type="xs:integer" minOccurs="0"/>
type="xs:integer" minOccurs="0"/>
type="xs:integer" use="required"/>
type="xs:integer" use="required"/>
minOccurs="0"/>
type="xs:string" default="0"/>
type="xs:string" default="0"/>
type="xs:string"/>
type="xs:string"/>
type="xs:string"/>
type="xs:string"/>
type="xs:string"/>
type="iodef:SoftwareType"/>
type="iodef:SoftwareType"/>
type="xs:string" use="optional"/>
type="xs:string" use="optional"/>
type="iodef:duration-type"/>
maxOccurs="unbounded"/>
type="iodef:restriction-type"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
type="iodef:restriction-type"/>
use="required">
type="xs:string" use="optional"/>
type="xs:integer" use="optional"/>
use="optional" default="line">
type="xs:string" use="optional"/>
type="xs:integer" use="optional"/>
type="iodef:ExtensionType"/>
type="iodef:MLStringType"/>
type="xs:string"/>
minOccurs="0" maxOccurs="unbounded"/>
type="iodef:dtype-type" use="required"/>
type="xs:string" use="optional"/>
type="xs:string"/>
type="xs:string"/>
type="iodef:restriction-type"/>
