credentials      =  "Jpop" jpop-response
jpop-response    =  at-response "," s-response
at-response      =  "at" "=" access-token; As specified by [POPKD]
s-response       =  "s" "=" jws-on-nonce; Created in the step 3.
access-token     =  quoted-string
jws-on-nonce     =  quoted-string

challenge        =  "Jpop" jpop-challenge
jpop-challenge   =  "nonce" "=" nonce-value
nonce-value      =  quoted-string

