hash-nss   = [media-type] ":" [hash-scheme] ":" hash-value
hash-scheme = "md5" / "sha1"
hash-value  = 1*(ALPHA / DIGIT / ".")

         The following are comments and restrictions not captured by the
         above grammar.

         A <media-type> is any MIME media type [RFC2046] which is
         registered in the appropriate IANA registry [IANA-MT]. The
         <media-type> specification defaults to "application/octet-
         stream".

         The <hash-scheme> specification defaults to "sha1".

         A <hash-value> is a non-empty sequence characters encoding a
         sequence of bits which must be a valid hash for the specified
         hash-scheme.  The encoding depends on the <hash-scheme>.  If
         <hash-scheme> is "md5", then <hash-value> is the base16
         encoding [RFC3548] of the 32 octets of the MD5 hash value of
         the resource (most significant octet first) so that the <hash-
         value> consists of 32 HEXDIG.  If <hash-scheme> is "sha1", then
         <hash-value> is the base32 encoding [RFC3548] of the 50 octet
         of the SHA1 hash value of the resource (most significant octet
         first) so that the <hash-value> consists of 20 BASE32DIG.

         Examples:

           urn:hash::md5:5307d294b6ccd9854f2deed8c1628b72

           urn:hash::sha1:7660c8efbe7f656ce7612636c83a138c085bad3f

           urn:hash:message/rfc822:md5:5307d294b6ccd9854f2deed8c1628b72

