xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

schemaLocation="eppcom.xsd"/>

maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
use="required"/>
use="optional"/>
use="required"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
use="required"/>
use="optional" default="0"/>
use="optional" default="en"/>
use="optional"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

use="optional"/>
