real              =  zero
real              =/ negative-infinity
real              =/ negative-zero
real              =/ positive-zero
real              =/ positive-infinity
real              =/ signaling-nan
real              =/ quiet-nan
real              =/ realnumber

negative-infinity =  %x2D.49.6E.66.69,6E.69.74.79   ; "-Infinity"
negative-zero     =  %x2D.5A.65.72.6F               ; "-Zero"
zero              =  %x30.2E.30                     ; "0.0"
positive-zero     =  %x2B.5A.65.72.6F               ; "+Zero"
positive-infinity =  %x2B.49.6E.66.69,6E.69.74.79   ; "+Infinity"
signaling-nan       =  %4E.61.4E.53                   ; "NaNS"
quiet-nan         =  %4E.61.4E.51                   ; "NaNQ"

realnumber        =  mantissa exponent

mantissa          =  ( positive-number [ "." *decimal-digit ])
mantissa          =/ ( "0." *("0") positive-number )

exponent          =  "E" ( "0" / ( [ "-" ] positive-number ) )

positive-number   =  non-zero-digit *decimal-digit

decimal-digit       =  %x30-39
non-zero-digit    =  %x31-39
value           =  type / array / map / selector / variant

type            =  "undef"
type            =/ "string"
type            =/ "bool"
type            =/ "int"
type            =/ "real"
type            =/ "date"
type            =/ "uri"
type            =/ "uuid"
type            =/ "binary"
array           =  "[" s value-list s "]"
array           =/ "[" s value-list s "..." s "]"

map             =  "{" s member-list s "}"
map             =/ "{" s "$" s ":" s value s "}"

value-list      = value [ s "," [ s value-list ] ]

member-list     = member [ s "," [ s member-list ] ]
member          = name s ":" s value

selector        =  quote name quote
selector        =/ "true" / "false"
selector        =/ 1*digit

variant         = "&" name


definitions     = *( s / variant-def / resource-def )

variant-def     = "&" name s "=" s value

resource-def    = res-name s res-request s res-response
res-name        = "%%" s name
res-request     = "->" s value
res-response    = "<-" s value


s               = *( tab / newline / sp / comment )
comment         = ";" *char newline
newline         = lf / cr / (cr lf)

tab             = %x0009
lf              = %x000A
cr              = %x000D
sp              = %x0020
quote           = %x0022
digit           = %x0030-0039
char            = %x09 / %x20-D7FF / %xE000-FFFD / %x10000-10FFFF

name            = name_start *name_continue
name_start      = id_start    / "_"
name_continue   = id_continue / "_" / "/"
id_start        = %x0041-005A / %x0061-007A ; ALPHA
id_continue     = id_start / %x0030-0039    ; DIGIT
