MULPDU = EMSS - (6 + 4 * Ceiling(EMSS / 512) + EMSS mod 4)

MULPDU = EMSS - (6 + EMSS mod 4)

BufferSizeTCP = K * bandwidth [octets/Second] * Delay [Seconds].

BufferSizeNAF = K1* EMSS * number_of_connections + K2 * EMSS

BufferSizeAF = K2 * EMSS
