Resource-Priority  = "Resource-Priority" HCOLON
                        r-value *(COMMA r-value)
r-value            = namespace "." r-priority
namespace          = token-nodot
r-priority         = token-nodot
token-nodot        = 1*( alphanum / "-"  / "!" / "%" / "*"
                               / "_" / "+" / "`" / "'" / "~" )

Accept-Resource-Priority = "Accept-Resource-Priority" HCOLON
                              [r-value *(COMMA r-value)]
Namespace      = the name of the namespace
Levels         = the number of priority-values within the namespace
Operation      = Expected operational behavior of this namespace
Reference      = Document reference for this namespace


