transport  =  "tcp" / "dc" / 1*ALPHANUM


label="chat":

a=webrtc-DataChannel:5000 stream=2;label="chat"; subprotocol="MSRP"


m=application 54111 DTLS/SCTP 5000
c=IN IP4 79.97.215.79
a=sctpmap:5000 webrtc-datachannel 16
a=webrtc-DataChannel:5000 stream=1;label="chat"; subprotocol="MSRP"
a=wdcsa:5000:1 accept-types:message/cpim text/plain
a=wdcsa:5000:1 path:msrps://bob.example.com:54111/si438dsaodes;dc
a=webrtc-DataChannel:5000 stream=2;label="file transfer"; \
subprotocol="MSRP"
a=wdcsa:5000:2 sendonly
a=wdcsa:5000:2 accept-types:message/cpim
a=wdcsa:5000:2 accept-wrapped-types:*
a=wdcsa:5000:2 path:msrps://bob.example.com:54111/jshA7we;dc
a=wdcsa:5000:2 file-selector:name:"My cool picture.jpg" \
        type:image/jpeg size:32349 hash:sha-1: \
        72:24:5F:E8:65:3D:DA:F3:71:36:2F:86:D4:71:91:3E:E4:A2:CE:2E
a=wdcsa:5000:2 file-transfer-id:vBnG916bdberum2fFEABR1FR3ExZMUrd
a=wdcsa:5000:2 file-disposition:attachment
a=wdcsa:5000:2 file-date:creation:"Mon, 15 May 2006 15:01:31 +0300"
a=wdcsa:5000:2 file-icon:cid:id2@bob.example.com
a=wdcsa:5000:2 file-range:1-32349


