a=fmtp:<format> <list of values> 


m=audio 12345 RTP/AVP 100 
a=rtpmap:100 telephone-event/8000 
a=fmtp:100 0-15,66,70 


Hz = "0", 2225 Hz = "1"; characters are US ASCII framed by one 
B=1, the state number is 2 (binary 10); if all four bits are used, 
A=0, B=1, C=0, D=1, then the state number is 10 (binary 1010).  


