Object = (S, D).  The ERO corresponds to the one PCE(1) as received
TYPE = TBD1 and ERO = {BNe(i), PKS(i), BNo(i), ..., BNe(n), PKS(n),
TYPE= TBD2 and End-Points Object = {BN(n), D} in order to inform the
LSP-TYPE = TBD1, RRO = {[LK(i+1), SL(i+1)]} and PLSP-ID(i+1), it
End-Points = {BNe(n), D}. Then, PCE(n) retrieves the ERO from the
TYPE = TBD2, it sends to its Parent PCE a PCRpt containing the RRO
TYPE = TBD1, ERO = {PKS(i), [LK(i+1), SL(i+1)]} and End-Points =
Error-Type = 21 (Traffic engineering path setup error) and Error-
Value = TBD4 (No Mandatory Stitching Label is present in the RRO).
