L         = length(route);
min_dist  = INF;
new_route = NULL;

node = route(j);
route_tail = route(j+1:L);
IARP_path = IARP_Routing_Table(node).route;
new_route = IARP_path + route_tail;
new_route = IARP_path + route_tail;
min_dist  = hop_count(new_route);
source    = MY_ID
query_id  = MY_QUERY_ID++;
type      = ROUTE_REQUEST;
route     = NULL;
node_ptr  = 0;

type  = ROUTE_REPLY;

route_tail = route(current_hop_ptr : length(route)): 
next_hop = route(node_ptr);

