rel="impl-info"

anchor="/sensors/temp";rel="describedby"

anchor="/sensors/temp";rel="describedby"

rt="temperature-c";if="sensor";
anchor="coap://local-proxy-old.example.com:5683/",
anchor="coap://local-proxy-old.example.com:5683/sensors/temp";
rel="describedby"

rt="temperature-c";if="sensor";
anchor="coap://new.example.com:5684/",
anchor="coap://new.example.com:5684/sensors/temp";
rel="describedby"

        Figure 16: Example lookup after a change to the base address

anchor="coap://[2001:db8:3::123]:61616"

                    Figure 18: Example a resource lookup

anchor="coap://[2001:db8:3::124]",
anchor="coap://[2001:db8:3::124]",
anchor="coap://[2001:db8:3::124]"

              Figure 19: Example an observing resource lookup

anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616"

anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616",
anchor="coap://[2001:db8:3::123]:61616"

              Figure 20: Examples of paginated resource lookup

anchor="coap://sensor1.example.com",
if="sensor"; anchor="coap://sensor1.example.com",
if="sensor"; anchor="coap://sensor1.example.com",
anchor="coap://sensor1.example.com/sensors/temp",
anchor="coap://sensor1.example.com/sensors/temp",
anchor="coap://sensor2.example.com",
if="sensor"; anchor="coap://sensor2.example.com",
if="sensor"; anchor="coap://sensor2.example.com",
anchor="coap://sensor2.example.com/sensors/temp",
anchor="coap://sensor2.example.com/sensors/temp"

et="oic.d.sensor";ct="40";rt="core.rd-ep",
et="oic.d.sensor";ct="40";d="floor-3";rt="core.rd-ep"

                   Figure 22: Examples of endpoint lookup

L = used at lookup, A = expressed in target attribute

base="coap://[ff05::1]";rt="core.rd-ep"

ep= and removed the h= and ins= parameters.

ep= parameter to be present.

base="coap://[ff05::1]",
base="coap://[ff35:30:2001:db8::1]";rt="core.rd-ep"

                    Figure 28: Example lookup of groups

et="core.rd-group";anchor="coap://[ff35:30:2001:db8::1]",
et="core.rd-group";
anchor="coap://[ff35:30:2001:db8::1]"

            Figure 29: Example lookup of resources inside groups

rel="describedby"

          Figure 31: Extended example of direct resource discovery

anchor="coap://[2001:db8:f0::1]"

anchor="coap://[2001:db8:f0::1]",
anchor="coap://[2001:db8:f0::1]",
anchor="coap://[2001:db8:f0::1]/sensors/temp";rel=alternate,
anchor="coap://[2001:db8:f0::1]/sensors/temp";rel="describedby"

anchor="coap+tcp://simple-host1.example.com"

