targetNamespace="urn:ietf:params:xml:ns:cpxmlsec"
elementFormDefault="qualified"
version="0.4">

type="cpxmlsec:ObjectIdentifierType"/>

type="cpxmlsec:KeyValueType"/>

type="cpxmlsec:PublicKeyParametersType"
minOccurs="0"/>
type="cpxmlsec:ObjectIdentifierType"/>
type="cpxmlsec:ObjectIdentifierType"/>
type="cpxmlsec:ObjectIdentifierType"
minOccurs="0"/>
type="cpxmlsec:ObjectIdentifierType" />

type="sp:QNameAssertionType"/>

targetNamespace="urn:ietf:params:xml:ns:cpxmlsec"
elementFormDefault="qualified"
version="0.4">

schemaLocation=
value="urn:oid:(([0-1]\.[1-3]?\d)|(2\.\d+))(\.\d+)*" />
type="cpxmlsec:ObjectIdentifierType" />

type="cpxmlsec:PublicKeyParametersType"
minOccurs="0"/>
type="cpxmlsec:ObjectIdentifierType" />
type="cpxmlsec:ObjectIdentifierType" />
type="cpxmlsec:ObjectIdentifierType"
minOccurs="0" />





type="cpxmlsec:ObjectIdentifierType" />

type="sp:QNameAssertionType"/>

