Type=9:  DDT Transfer request, this four bit value identifies the
      packet type (other LISP packet types are defined in the respective
      Internet Drafts).

Type=11:  DDT Transfer Data Message, this four bit value identifies
      the packet type (other LISP packet types are defined in the
      respective Internet Drafts).

