AD1 = (
       LOC_S:           tstr,
       CC:              bstr,
       CIPHERTEXT_RQ:   bstr
plaintext = (
       ID:              bstr
    )

external_aad = (
       CC:              bstr
    )

AD2 = (
       Voucher:        bstr
external_aad = bstr .cbor external_aad_arr
external_aad_arr = [
       voucher_type:  int,
       PK_A:          bstr,
       G_X:           bstr,
       CC:            bstr,
       ID:            bstr
Voucher_Request = [
       PK_A:            bstr,
       G_X:             bstr,
       CC:              bstr,
       CIPHERTEXT_RQ:   bstr
Voucher_Response = [
       CERT_PK_D:      bstr,
       Voucher:        bstr
