K = MD4(UNICODE(password)) 
         
T = 1 for TS-ENC-TS in the AS-Request 
T = 8 for the AS-Reply  
T = 7 for the Authenticator in the TGS-Request 
T = 8 for the TGS-Reply  
T = 2 for the Server Ticket in the AP-Request 
T = 11 for the Authenticator in the AP-Request 
T = 12 for the Server returned AP-Reply 
T = 15 in the generation of checksum for the MIC token 
T = 0 in the generation of sequence number for the MIC token  
T = 13 in the generation of checksum for the WRAP token 
T = 0 in the generation of sequence number for the WRAP token  
T = 0 in the generation of encrypted data for the WRAPPED token 
    
Ksign = HMAC(K, "signaturekey")  //includes zero octet at end 
tmp = MD5(concat(T, data)) 
CHKSUM = HMAC(Ksign, tmp) 
    
    
T = the message type, encoded as a little-endian four byte integer. 
 
edata_len = 16 + 8 + data_len; 
data_len = edata_len - 16 - 8; 
T = 15; 
T = 0; 
T = 13; 
PAD = 1; 
T = 0; 
T = 0; 
edata_len = 8 + msg_len + 1; // conf + msg_len + pad 
