blogPrivate = element blog:private { 'yes' | 'no' }

blogNotify = element blog:notify {
       element blogEndpoint *,
       undefinedContent
blogEndpoint = element blog:endpoint {
       attribute type { IRI },
       ( IRI )
blogEnable = element blog:enable {
       element blogComments ?,
       element blogTrackbacks ?,
       element blogPingbacks ?,
       element blogCommentsNotify ?,
       element blogTrackbacksNotify ?,
       element blogPingbacksNotify ?,
       element blogTextEncoding *,
       element blogPlugin *,
       undefinedContent
blogComments = element blog:comments {
       attribute until { dateTime }?,
       ('yes','no','moderated','registered')
blogTrackbacks = element blog:trackbacks {
       attribute until { dateTime }?,
       ('yes','no','moderated','registered')
blogPingbacks = element blog:pingbacks {
       attribute until { dateTime }?,
       ('yes','no','moderated','registered')
blogCommentsNotify =
       element blog:comments-notify { 'yes' | 'no' }

blogTrackbacksNotify =
       element blog:trackbacks-notify { 'yes' | 'no' }

blogPingbacksNotify =
       element blog:pingbacks-notify { 'yes' | 'no' }

blogTextEncoding = element blog:text-encoding {
       attribute id { IRI },
       undefinedContent
blogPlugin = element blog:plugin {
       attribute id { IRI },
       undefinedContent
blogScheduled = element blog:scheduled { atomDateConstruct }

type="http://www.movabletype.org/trackback/"> \
type="http://www.technorati.com/developers/ping/"> \
until="2005-12-12T00:00:00Z">moderated</blog:comments>
until="2005-12-12T00:00:00Z">moderated</blog:trackbacks>
