type = 1 or	4), the	Link State ID is always	the described
Options = (T-bit|E-bit)	 ;TOS-capable
Type =	2		 ;connects to transit network
Type =	3		 ;connects to stub network
Options = (T-bit|E-bit)	 ;TOS-capable
Type =	1		 ;connects to router
Options = (T-bit|E-bit)     ;TOS-capable
Type =	1	      ;connects	to router
TOS = 8      ;maximize	throughput
metric	= 1   ;traffic preferred


Options = (T-bit|E-bit)	 ;TOS-capable
Options = (T-bit|E-bit)     ;TOS-capable
TOS = 0
metric	= 4

Options = (T-bit|E-bit)     ;TOS-capable
TOS = 0
metric	= 14


Options = (T-bit|E-bit)     ;TOS-capable
TOS = 0
metric	= 2
Options = (T-bit|E-bit)	   ;TOS-capable
TOS = 0
metric	= 1
