URI-parameter = opaque-param / (token ["=" token])
opaque-param  = "opaque" EQUAL token


c=IN IP4 192.168.0.100
m=message 12454 TCP/MSRP *
a=path:msrp://msrp.invalid.com:7394/jshA7weztas;tcp;opaque=f7jey483rydfhkyerky3

c=IN IP4 border.altanta.example.com
m=message 22454 TCP/MSRP *
a=path:msrp://msrp.invalid.com:7394/jshA7weztas;tcp;opaque=f7jey483rydfhkyerky3

c=IN IP4 bob.altanta.example.com
m=message 34313 TCP/MSRP *
a=path:msrp://msrp.invalid.com:7394/kjhd37s2s20w2a;tcp;opaque=a6ghr7yv6egw33r

c=IN IP4 border.altanta.example.com
m=message 27784 TCP/MSRP *
a=path:msrp://msrp.invalid.com:7394/kjhd37s2s20w2a;tcp;opaque=a6ghr7yv6egw33r

