relating=<relating-domain name>
related=<related-domain name or URL>
rdbd-tag=<rdbd-tag value>
key-tag=<key-tag>
sig-alg=<sig-alg>


relating=my.example
related=my-way.example
rdbd-tag=1
key-tag=38501
sig-alg=8
TkQgUFVCTElDIEtFWS0tLS0tCg== )
NxFkcA== )
related=my-way.example
rdbd-tag=1
key-tag=35988
sig-alg=15
st=struct.pack('!HBB', int(flags), int(protocol), int(algorithm))
cnt = 0
s = struct.unpack('B', st[idx:idx+1])[0]
parser=argparse.ArgumentParser(description='Ed25519 signing')
dest='secret', help='secret key')
dest='relating', help='relating domain')
dest='related', help='related domain')
dest='negative', help='negative assertion')
args=parser.parse_args()

secret=args.secret.encode('utf-8')
b64pubkey=binascii.b2a_base64(pubkey).rstrip().decode("utf-8")
keyid=calc_keyid("0","3","15",b64pubkey)
rdbdtag="1"
rdbdtag="0"

tbs="relating="+args.relating+"\nrelated="+\
             args.related+"\nrdbd-tag="+rdbdtag+\
             "\nkey-tag="+str(keyid)+"\nsig-alg=15\n"
msg=tbs.encode('utf-8')
signature = Ed25519.sign(privkey, pubkey, msg)
