c = m^e mod n

c = z^e mod n.

z = RandomInteger (0, n-1)
Z = IntegerToString (z, nLen)

c = z^e mod n
C = IntegerToString (c, nLen)

KEK = KDF (Z, kekLen)

WK = Wrap (KEK, K)

EK = C || WK
c = StringToInteger (C)
z = c^d mod n

Z = IntegerToString (z, nLen)

KEK = KDF (Z, kekLen)

K = Unwrap (KEK, WK)
