y=size of the transmitted bits


             Figure 7: Compression and Decompression Functions

FCN=31 (i.e.  FCN=2^N-1 for N=5, or equivalently, all FCN bits set to
W=0 |   |  | FCN-
FCN=max value |  ++==+========+
                        +> |            |
MIC_bit==1 &             | |   | |  +--+Attemp++           |
Recv_window==window &    | |   | +-------------------------+
Lcl_Bitmap==recv_Bitmap &| |   |   all missing frag sent
                no more frag| |   |   ~~~~~~~~~~~~~~~~~~~~~~
    ~~~~~~~~~~~~~~~~~~~~~~~~| |   |   Set Retrans_Timer
          Stop Retrans_Timer| |   |
    +=============+         | |   |
    |     END     +<--------+ |   | Attemp > MAX_ACK_REQUESTS
    +=============+           |   | ~~~~~~~~~~~~~~~~~~
                 All-1 Window |   v Send Abort
                 ~~~~~~~~~~~~ | +=+===========+
MIC_bit ==0 & +>|    ERROR    |
Lcl_Bitmap==recv_Bitmap  +=============+



          Figure 37: Sender State Machine for the ACK-Always Mode
Inactivity_Timer = expires
W=0 |   |  |  send Window + frag(FCN)
FCN=max value |  ++=============+
                             +> |              |
                                |     SEND     |
Local_Bitmap==Recv_Bitmap|   |
Inactivity_Timer = expires
