elementFormDefault="qualified"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema">


           <xs:element name="media_control">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="vc_primitive"
type="vc_primitive"
minOccurs="0"
maxOccurs="unbounded" />
type="xs:string"
minOccurs="0"
maxOccurs="unbounded" />
type="xsd:string"
minOccurs="0"
maxOccurs="unbounded" />
