Identity = "Identity" HCOLON signed-identity-digest
signed-identity-digest = LDQUOT 32LHEX RDQUOT

Identity-Reliance = "Identity-Reliance" HCOLON signed-identity-reliance-digest
signed-identity-reliance-digest = LDQUOT 32LHEX RDQUOT

Identity-Info = "Identity-Info" HCOLON ident-info
                    *( SEMI ident-info-params )
ident-info = LAQUOT absoluteURI RAQUOT
ident-info-params = ident-info-alg / ident-info-extension
ident-info-alg = "alg" EQUAL token
ident-info-extension = generic-param

digest-string = addr-spec / tn-spec "|" addr-spec / tn-spec "|"
                   Method "|" SIP-date "|" [ signed-identity-reliance-digest ]

