maxOccurs="unbounded"/>
                Location Object Authorization Policies     August 2003


maxOccurs="unbounded">
maxOccurs="unbounded" />
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="element-name"
type="xs:string"/>
type="gp:permission-statements-type">
minOccurs="0" />
from="2003-09-04T09:00:00" until="2003-09-05T18:00:00">

minOccurs="0"   maxOccurs="unbounded"/>
type="gp:recurrence-type" minOccurs="0"
maxOccurs="unbounded"/>
type="xs:anyURI " minOccurs="0"
maxOccurs="1"/>
minOccurs="0"  maxOccurs="1"/>
