s = g^xAxB            s = g^xAxB
h = hash(s|nA|nB)     h = hash(s|nA|nB)
s = g^xAxB            s = g^xAxB
h_a = hash(s|nA) -->
                                 <-- nB
h = hash(s|nA|nB)     h = hash(s|nA|nB)
