master_secret = PRF(pre_master_secret, "master secret",
                             ClientHello.random + ServerHello.random)
                             [0..47];

master_secret = PRF(pre_master_secret, "extended master secret",
                           session_hash)
                           [0..47];
