t0 = TSD*(N - log_{1/P}((1-P)/(1-P^N)*(SR_P/BCR_P-1)). 
t0 = TSD*(N - log_{1/P}((1-P)/(1-P^N)*(SR_P/BCR_P))) and use the
Z = Z*(1-Delta)^(G*Y) + X/(Y+1)*(1-(1-Delta)^(Y+1))

X = X*(1-G)

Y = Y*(1-G)

Z1 = Z*(1-Delta)^Y + X/(Y+1)*(1-(1-Delta)^(Y+1))

Z2 = Z*(1-Delta)^(Y+1) + (X+W+1)/(Y+2)*(1-(1-Delta)^(Y+2))

LOSSP = 1/max{Z1,Z2,1}


X = X + W

W = 0

Y = Y + 1
W = 0

X = 1/a

Y = 0

Z = 1/a



sigma = (0.003637*N+0.07683)*min{NWC,0.56*N}+0.3573.

PSN = 2^16-1.



PSN = 2^32-1.



