sprop-max-don-diff = max{AbsDON(i) - 
m=video 49170 RTP/AVP 98 
a=rtpmap:98 H264/90000 
a=fmtp:98 profile-level-id=42A01E; sprop-parameter-
sets=Z0IACpZTBYmI,aMljiA== 
    
    
m=video 49170 RTP/AVP 100 99 98 
a=rtpmap:98 H264/90000 
a=fmtp:98 profile-level-id=42A01E; packetization-mode=0;  
sprop-parameter-sets=Z0IACpZTBYmI,aMljiA== 
a=rtpmap:99 H264/90000 
a=fmtp:99 profile-level-id=42A01E; packetization-mode=1;  
sprop-parameter-sets=Z0IACpZTBYmI,aMljiA== 
a=rtpmap:100 H264/90000 


 
 
a=fmtp:100 profile-level-id=42A01E; packetization-mode=2;  
sprop-parameter-sets=Z0IACpZTBYmI,aMljiA==;  
sprop-interleaving-depth=45; sprop-deint-buf-req=64000; 
sprop-init-buf-time=102478; deint-buf-cap=128000 
    
m=video 49170 RTP/AVP 100 99 97 
a=rtpmap:97 H264/90000 
a=fmtp:97 profile-level-id=42A01E; packetization-mode=0;  
sprop-parameter-sets=Z0IACpZTBYmI,aMljiA==,As0DEWlsIOp==, 
a=rtpmap:99 H264/90000 
a=fmtp:99 profile-level-id=42A01E; packetization-mode=1;  
sprop-parameter-sets=Z0IACpZTBYmI,aMljiA==,As0DEWlsIOp==, 
a=rtpmap:100 H264/90000 
a=fmtp:100 profile-level-id=42A01E; packetization-mode=2;  
sprop-parameter-sets=Z0IACpZTBYmI,aMljiA==,As0DEWlsIOp==, 
sprop-deint-buf-req=86000; sprop-init-buf-time=156320; 
deint-buf-cap=128000; max-rcmd-nalu-size=3980 
    
k=1) codes can be used. 
