in-reply-react = "In-Reply-React:" emoji *(lwsp emoji) CRLF

emoji = {character from Unicode Emoji List}

emoji-core = thumbs-up / thumbs-down / grinning-face / frowning-face / crying-face

thumbs-up = {U+1F44D}
thumbs-down = {U+1F44E}
grinning-face = {U+1F600}
frowning-face = {U+2639}
crying-face = {U+1F622}

   An emoji character is taken from [Emoji-List].

   The emoji(s) express a recipient's summary reaction to the specific
   message referenced by the accompanying In-Reply-To header field.
   [Mail-Fmt].

   Fully interoperable email uses 7-bit ASCII, although some email
   handling paths directly support 8-bit ASCII.  Emoji characters are
   drawn from the space outside of 7-bit ASCII.  For email handling
   paths that are 8-bit clean, the an emoji character does not need
   special encoding.  If the path from author to recipients is not known
   to be 8-bit clean, The emoji character SHOULD be encoded using
   [MIMEencode].

   For recipient MUAs that do not support this mechanism, the header
   field might not be displayed to the recipient.  To ensure that the
   reaction is presented to the recipient, the the responding MUA MAY
   automatically include a second copy of the header field in the
   message body.  This might be as the first line of the body or as the
   first mime-part.  [MIME] By making the text be the full header field,
   it also allows MUAs that do support the mechanism to identify this
   redundant information and possibly remove it from display.
