Client1 =>-|B|-=>-|R|-=>-|S|-=>-|D|-=> Client3
                  +-+    +-+    +-+    +-+
                            \
                             \     +-+
                              \-=>-|E|-=> Client4
                                   +-+

                        Figure 7: Example Network Topology

Client1---=>---|B|-------=>-------|R|-------=>-------|S|---------=>-=--------|D|----=>----Client3
                 +-+                +-+                +-+                     +-+ +==========+
                         +------------+ \                                          |(C-MC Pkt)|
                         |{S=R , D=E}|   \     +-+                                 +==========+
                         +------------+   \-=>-|E|-----=>------ Client4
                         |[BitStr=001]|        +-+  +==========+
                         +============+             |(C-MC Pkt)|
                         | (C-MC Pkt) |             +==========+
                         +============+

                     Figure 15: Brief of RBS BitString coversion


