m=<media> <port> <proto> <fmt> ...

m=application 54111 DTLS/SCTP 0 1 2
a=streams=3
a=datachannel:0 RTCWeb label=xxxx;options="dictionary string"
a=datachannel:1 RTCWeb label=xxxx;options="dictionary string"
a=datachannel:2 RTCWeb label=xxxx;options="dictionary string"



streams-attr        =  "a=streams=" streamsnumbers
streamsnumbers      =  1*DIGIT



datachannel-attr        =  "a=datachannel:" datachannel-number
datachannel-number      =  1*DIGIT
m=application 54111 SCTP 0 1 2
c=IN IP4 192.0.2.2
a=setup:actpass
a=connection:new
a=streams=3
a=datachannel:0 RTCWeb label=xxxx;options="dictionary string"
a=datachannel:1 RTCWeb label=xxxx;options="dictionary string"
a=datachannel:2 RTCWeb label=xxxx;options="dictionary string"

                                 Figure 1

m=image 54321 SCTP 0 1 2
c=IN IP4 192.0.2.1
a=setup:passive
a=connection:new
a=streams=3
a=datachannel:0 RTCWeb label=xxxx;options="dictionary string"
a=datachannel:1 RTCWeb label=xxxx;options="dictionary string"
a=datachannel:2 RTCWeb label=xxxx;options="dictionary string"

                                 Figure 2

m=application 54321 SCTP *
c=IN IP4 192.0.2.1
a=setup:passive
a=connection:existing

                                 Figure 3

m=application 9 SCTP *
c=IN IP4 192.0.2.2
a=setup:active
a=connection:existing

                                 Figure 4

m=image 54111 SCTP/DTLS 0
c=IN IP4 192.0.2.2
a=setup:actpass
a=connection:new
a=fingerprint:SHA-1 \
             4A:AD:B9:B1:3F:82:18:3B:54:02:12:DF:3E:5D:49:6B:19:E5:7C:AB
a=fmtp:datachannel streams=1
a=datachannel:0 t38 label=xxxx;options="dictionary string"


                                 Figure 5


