group-member = userid-entry-ref / groupid-entry-ref

groupid-entry-ref = "groupid." entry-name
                        # entry-name refers to an entry in the
                          "/groupid" dataset

userid-entry-ref =  "userid." entry-name
                        # entry-name refers to an entry in the
                         "/userid" dataset


     Note that there are no restrictions on the membership of a group.
     A group may include itself as a member.   Elimination of recursive
     references to groups MUST be performed by the agent responsible for
     calculating group membership attributes like that defined in
     section 3.2.2, or by agents that use group information in rights
     calculations.


