provenance="/reg/1234"
d=facility23.eu.example.com
d=facility23.eu.example.com

d="facility23.eu.example.com";con="coap://[2001:db8:23::1]"

d=facility23.eu.example.com
con="coap://[2001:db8:23::1]";lt-remaining=90000

d=facility23.eu.example.com

d="facility23.eu.example.com";con="coap://[2001:db8:23::1]"

con="coap://[2001:db8:23::1]";lt-remaining=90000

d="facility23.eu.example.com";con="coap://[2001:db8:23::1]"

anchor="coap://[2001:db8:23::1]/sensors/temp";
provenance="coap://[2001:db8:23:2]/reg/11",
con="coap://[2001:db8:1:2::3]:10123";
at="coap+tcp://[2001:db8:1:2::3]:10123"

