DNWithString  = StringTag ':' Count ':' String ':' DN
	
OctetTag = 'S' | 's'
	
Count = positive decimal number, counting number of bytes in 
String = <normally encoded (i.e. UTF8 for V3) string>  
DN = <normal string encoding of a DN> 

DC=foobar,DC=Com is

