ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3">
atomSecCredentials =
       element atomsec:credentials {
           atomCommonAttributes*,
           attribute use { "content" | "transport" } ?,
           (extensionElement*)
       }

ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3">
URI="#SecurityToken-df8e8299-0d67-4eaf-bf5e-21c4dc6342ad"/>
Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-1_5"/>
ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3SubjectKeyIdentifier">
Type="http://www.w3.org/2001/04/xmlenc#Element">
