ICW_A = min(ICWE_A,ICWE_B)         ICW_B = min(ICWE_A,ICWE_B)
     |                                     |
    ...                                   ...

i = rand() % COUNT;
j = rand() % COUNT;

iw = node_iw[i];
iw = node_iw[j] < node_iw[i] ? node_iw[j] : node_iw[i];
mincap = backbone_capacity[i][j];
loss = iw > mincap ? iw - mincap : 0;

headroom = iw < mincap ? mincap - iw : 0;

iws = loss = headroom = 0;
