connectivity =     (  Interoperability )
                      (   Resilience        )
                      (   Reliability       )
                      (   Robustness        )
                       (  Autonomy         )
                        ( Simplicity      )

