CBID = SHA1_128 ( PK )

CGA = NetworkPrefix | SHA1_64 ( PK )

CGA_1 => CBID : OSGW

CGA_2 => CBID : OSGW



CGA_n => CBID : OSGW



CBID = SHA1_128 ( X509{PK} )
CGA = NetworkPrefix | SHA1_64 ( X509Cert{PK} | NetworkPrefix)

tunnel=::0->::0)

tunnel=::0->::0)

Alice_CGA =>GW_i_CBID : OSGW

Bob_CGA =>GW_r_CBID : OSGW

tunnel=GW_i->GW_r)

tunnel=GW_i->GW_r)
