n = number of leaf nodes = ceil(|D| / B)
k = number of (encoded) hash values fitting in a block of size B
H = sequence of hash valued pointers of M
data = lookup(p)
M = lookup(p)
offset_i = \sum_{i = 1}^{i - 1} P_i.size

offset = 0
i = floor(P / L)
o = P mod L
M = (manifest
         (hashgroup((metadata(SizePerPtr=4096)) (dataptr=h1))
         (hashgroup((metadata(SizePerPtr=1500)) (dataptr=h2))
         ...
       )

