Identifier = 1234
              * CPE get-ID in Port-range, allocate  *
              * Mapping Table, eg:  1234<--->129    * 
                    ------------------------------>
                    ICMP Echo 
Identifier = 129
                                                ------------------>
                                                ICMP Echo
Identifier = 129            
Identifier = 129
Identifier = 129      
Identifier = 1234

