DIALOG-URL        = sip-ind dialog-ind "@" hostport
                      dialog-parameters

sip-ind           = "sip:" / "sips:"
dialog-ind        = "dialog"

dialog-parameters = [ init-parameters ]
                      [ vxml-parameters ]
                      [ uri-parameters ]

init-parameters   = init-param [ init-parameters ]

init-param        = ";" (dialog-param /
                           maxage-param /
                           maxstale-param /
                           method-param /
                           postbody-param)

dialog-param      = "voicexml=" vxml-url ; vxml-url follows the URI
                                           ; syntax defined in [RFC3986]
maxage-param      = "maxage=" 1*DIGIT

maxstale-param    = "maxstale=" 1*DIGIT

method-param      = "method=" ("get" / "post")

postbody-param    = "postbody=" token

vxml-parameters   = vxml-param [ vxml-parameters ]

vxml-param        = ";" vxml-keyword "=" vxml-value

vxml-keyword      = token

vxml-value        =  false /
                       null /
                       true /
                       object /
                       array /
                       number /
                       string ; see RFC4627


   Parameters of the Request-URI in subsequent re-INVITEs are ignored.
   One consequence of this is that the VoiceXML Media Server cannot be
   instructed by the Application Server to change the executing VoiceXML
   Application after a VoiceXML Session has been started.
   Incorrectly formed requests MUST be rejected with the appropriate 4xx
   class response.  If one of the init-parameters is repeated, then the
   request MUST be rejected with a 400 Bad Request response.

   Note: Special characters in Request-URI parameter values need to be
   URL-encoded as required by the SIP URI syntax, for example '?' (%3f),
   '=' (%3d), and ';' (%3b).  The VoiceXML Media Server MUST therefore
   unescape Request-URI parameter values before making use of them or
   exposing them to running VoiceXML applications.  It is important that
   the VoiceXML Media Server only unescape the parameter values once
   since the desired VoiceXML URI value could itself be URL encoded, for
   example.  When a postbody is included, its entire content including
   any line breaks (represented by a CR LF pair) is encoded as a single
   parameter value following the above rules (such that the line breaks
   would be replaced by '%0D%0A', for example).

   As an example, the following SIP Request-URI identifies the use of
   VoiceXML media services, with
   'http://appserver.example.com/promptcollect.vxml' as the initial
   VoiceXML document, to be fetched with max-age/max-stale values of
   3600s/0s respectively:

       sip:dialog@mediaserver.example.com; \
voicexml=http://appserver.example.com/promptcollect.vxml; \
maxage=3600;maxstale=0

voicexml=http://as1.example.com/da.vxml

userAuthorized = true
pin = 1234
errors = 0
id=1234&pin=9999&__reason=exit
