P-Alerting-Mode        = "P-Alerting-Mode" HCOLON alerting-type
alerting-type          = "Manual" / "Auto" / "MAO"

P-Answer-State          = "P-Answer-State" HCOLON answer-type
answer-type             = "Confirmed" / "Unconfirmed"

