number_of_hashes = 20, filter_size_m = 4086)
membership_test = allocate _tablesize_of (filter_size_m);
                                          // table size for m

        for (i= 0; i < size_number_of_elements_n(array_of_EIDs_n); ++i){
                // for each n elements
         for (k= 0; k < number_of_hashes; ++k) {
                // for each hashes set a bit in the membership test
            (membership_test [hash_function((uint8_t )k+1, EID(i))]= 1);

          }

        }
