webbundle = [
     ; 🌐📦 in UTF-8.
     magic: h'F0 9F 8C 90 F0 9F 93 A6',
     version: bytes .size 4,
     primary-url: whatwg-url,
     section-lengths: bytes
       .cbor [* (section-name: tstr, length: uint) ],
     sections: [* any ],
     length: bytes .size 8,  ; Big-endian number of bytes in the bundle.
responses = [*response]

whatwg-url = tstr
section-lengths = [* (section-name: tstr, length: uint) ],

index = {* whatwg-url => [ variants-value, +location-in-responses ] }
variants-value = bstr
location-in-responses = (offset: uint, length: uint)

manifest = whatwg-url

signatures = [
     authorities: [*authority],
     vouched-subsets: [*{
       authority: index-in-authorities,
       sig: bstr,
       signed: bstr  ; Expected to hold a signed-subset item.
     }],
authority = augmented-certificate
index-in-authorities = uint

signed-subset = {
     validity-url: whatwg-url,
     auth-sha256: bstr,
     date: uint,
     expires: uint,
     subset-hashes: {+
whatwg-url => [variants-value, +resource-integrity]
resource-integrity = (
     header-sha256: bstr,
     payload-integrity-header: tstr
critical = [*tstr]

response = [headers: bstr .cbor headers, payload: bstr]

headers = {* bstr => bstr}

