QTYPE=PTR QNAME=\[x2001000103010001020855fffe012345/128].ip6.int.

            Answer:
            \[x200100/24].ip6.int. DNAME alpha-registry.tld.

QTYPE=PTR QNAME=\[x0103010001020855fffe012345/104].alpha-registry.tld.

            Answer:
            \[x0102/15].alpha-registry.tld. DNAME nla-space.med-isp.example.

QTYPE=PTR QNAME=\[x80800081042affff0091a28/89].
                                        nla-space.med-isp.example.

            Answer:
            \[x808/9].nla-space.med-isp.example. DNAME sla.example.org.

QTYPE=PTR QNAME=\[x0001020855fffe012345].sla.example.org.

            Answer:
            \[x0001020855fffe012345].sla.example.org. PTR www.example.org.

