value=TBD4 (Native IP object missing).  If there are more than one of
value=TBD5(Only one of the BPI, EPR or PPA object can be included in
value=TBD4 ( Native IP object missing).  If there are more than one
value=TBD5(Only one of the BPI, EPR or PPA object can be included in
value=TBD7, Peer AS not match; or Error-Value=TBD8, Peer IP can't be
value=TBD9, Local IP is in use; Error-value=TBD10, Remote IP is in
value=TBD12, Explicit Peer Route Error) that defined in Section 11.

Error-value=TBD18, BPI/PPR address family mismatch) should be
