tn-spec = [ "#" / "*" ] 1*DIGIT

Identity = "Identity" HCOLON signed-identity-digest SEMI ident-info *( SEMI ident-info-params )
signed-identity-digest = LDQUOT *base64-char RDQUOT
ident-info = LAQUOT absoluteURI RAQUOT
ident-info-params = ident-info-alg / ident-spec / canonical-str
ident-info-alg = "alg" EQUAL token
ident-spec = "spec" EQUAL token
canonical-str = "canon" EQUAL *base64-char
ident-info-extension = generic-param

base64-char = ALPHA / DIGIT / "/" / "+"


pPqOg1uXndzHbG7mR6Rl9BnUhHufVRbp51Mn3w0gfUs="; \
info=<https://biloxi.example.org/biloxi.cer>;alg=RS256

