Pointer = 20) [RFC0792].  This limitation is acceptable because
DF=0).


Type = 11 and Code = 0 (Destination unreachable, Net
PSID_length = Ki.  A CE mapping rule rule that assigns IPv4
PSID_length = L - 32.

