Load-Status       = "Load-Status" HCOLON loadStatus
loadStatus        = 0-100 [ SEMI validMS ] SEMI originatorURI
validMS           = "valid" EQUAL delta-ms
originatorURI     = "next-hop" EQUAL absoluteURI
delta-ms          = 1*DIGIT

