xmlns="urn:ietf:params:xml:ns:iris-lw1"
length="1280">

registryType="dreg1"
entityClass="contact-handle"
entityName="mak21" />
xmlns="urn:ietf:params:xml:ns:iris-lw1"
xmlns="urn:ietf:params:xml:ns:iris-lw1"
length="1280">

xmlns="urn:ietf:params:xml:ns:iris-lw1"
xmlns="urn:ietf:params:xml:ns:iris-lw1"
xmlns="urn:ietf:params:xml:ns:dreg1"
authority="com" registryType="dreg1"
entityClass="domain-handle" entityName="tcs-com-1" >
authority="com" registryType="dreg1"
entityClass="host-handle" entityName="research7" />
authority="com" registryType="dreg1"
entityClass="host-handle" entityName="nsol184" />





authority="com" registryType="dreg1"
entityClass="service-definition" entityName="notice" />
xmlns="urn:ietf:params:xml:ns:iris-lw1"
xmlns="urn:ietf:params:xml:ns:iris-lw1"
targetNamespace="urn:ietf:params:xml:ns:iris-lw1"
elementFormDefault="qualified" >

