internal_sockaddr = ...;
requested_external_sockaddr = 0;
external_address = 0;
internal_sockaddr = ...;
requested_external_sockaddr = 0;
MAP4=0:   create a mapping between an internal target address and
              external IPv4 address (e.g., NAT44, NAT64, or firewall)

MAP6=1:   create a mapping between an internal target address and
              external IPv6 address (e.g., NAT46, NAT66, or firewall)

lifetime=0) on reboot protects itself against this resource
PEER4=2:  Set or query lifetime for flow from IPv4 address to a
               remote peer's IPv4 address.

PEER6=3:  Set or query lifetime for flow from IPv6 address to a
               remote peer's IPv6 address.

