TMO        = timeout expires
REQ = Receive Application Request      scm = send PT_CMD
RCM = Receive PT_CMD                   snt = send PT_NTFN
RNT = Receive PT_NTFN                  fsc = fwd to Session Control
RSP = Receive Session Response         sak = send PT_ACK
RAK = Receive PT_ACK                   sdt = send PT_DATA
RDT = Receive PT_DATA                  sto = start timers
TMO = Ack Timeout                      ind = send Appl Indication
cnf = send Appl Confirm

LOS           = Loss of signal assumed when DEREG_REQ abandoned

ORR = Outgoing Registration Request    srr = send FUN_REG_REQ
ODR = Outgoing Deregistration Request  sdr = send FUN_DEREG_REQ
OAR = Outgoing Application Request     sar = send FUN_<other>
IRR = Incoming FUN_REG_REQ             au  = authenticate subscriber
IDR = Incoming FUN_DEREG_REQ           up  = update registr. status
IAR = Incoming FUN_<other>             spk = send Positive Ack
IAK = Incoming Ack                     snk = send Negative Ack
TMO = Inactivity Timeout               it  = start INACTIVITY_TIMER

F1  = Function ID of FUN_REG_REQ
F0  = Function ID of FUN_DEREG_REQ
