P-Served-User            = "P-Served-User" HCOLON PServedUser-value
                              *(SEMI served-user-param)
served-user-param        = sessioncase-param
                              / registration-state-param
                              / generic-param
PServedUser-value        = name-addr / addr-spec
sessioncase-param        = "sescase" EQUAL ("orig"/"term")/ orig-cdiv
registration-state-param = "regstate" EQUAL ("unreg" / "reg")
orig-cdiv                = "orig-cdiv"


