m=audio <port number> RTP/AVP <payload type>

c=IN IP4 <IP number>

a=rtpmap: <payload number> <mime-type>/<srate>[/<audio-channels>]

m=audio 5004 RTP/AVP 96
c=IN IP4 169.229.60.64
a=rtpmap: 96 mwpp/44100

a=fmpt: <payload number> streamtype=5; mode=mwpp;

m=audio 5004 RTP/AVP 61
c=IN IP4 169.229.60.64
a=rtpmap: 61 mpeg4-generic/44100
a=fmpt: 61 streamtype=5; mode=mwpp; config="e4"; profile-level-id=76;

a=fmpt: <payload number> <param1>=<value1>; <param2>=<value2>; ...

m=audio 5004 RTP/AVP 96
c=IN IP4 169.229.60.64
a=rtpmap: 96 mwpp/44100
a=fmpt: 96 recj=0;




m=audio 5004 RTP/AVP 96
c=IN IP4 169.229.60.64
a=rtpmap: 96 mwpp/44100
a=fmpt: 96 chnever=WTA;chmay=14,15,N;chmust=12,W;

m=audio 5004 RTP/AVP 96
c=IN IP4 169.229.60.64
a=rtpmap: 96 mwpp/44100
a=fmpt: 96 tsmode=async;linerate=320000;octpos=first;

m=audio 5004 RTP/AVP 96
c=IN IP4 169.229.60.64
a=rtpmap: 96 mwpp/44100
a=fmpt: 96 tsmode=buffer;linerate=320000;octpos=last;mperiod=44;

m=audio 5004 RTP/AVP 96
c=IN IP4 169.229.60.64
a=rtpmap: 96 mwpp/44100
a=fmpt: 96 maxptime=500;

m=audio 5004 RTP/AVP 61
c=IN IP4 169.229.60.64
a=rtpmap: 61 mpeg4-generic/44100
a=fmpt: 61 streamtype=5; mode=mwpp; config="e4"; profile-level-id=76;
a=fmpt: 61 midiport=12;zerosync=1726
m=audio 5006 RTP/AVP 62
c=IN IP4 169.229.60.64
a=rtpmap: 62 mpeg4-generic/44100
a=fmpt: 62 streamtype=5; mode=mwpp; config=""; profile-level-id=76;
a=fmpt: 62 midiport=12;zerosync=726

m=audio 5004 RTP/AVP 61
c=IN IP4 169.229.60.64
a=rtpmap: 61 mpeg4-generic/44100
a=fmpt: 61 streamtype=5; mode=mwpp; config=""; profile-level-id=74;
a=fmpt: 61 midiport=5;zerosync=0;
m=audio 5006 RTP/AVP 62
c=IN IP4 169.229.60.64
a=rtpmap: 62 mpeg4-generic/44100
a=fmpt: 62 streamtype=5; mode=mwpp; config=""; profile-level-id=74;
a=fmpt: 62 midiport=6;zerosync=0;

m=audio 5004 RTP/AVP 61
c=IN IP4 169.229.60.64
a=rtpmap: 61 mpeg4-generic/44100
a=fmpt: 61 streamtype=5; mode=mwpp; config=""; profile-level-id=76;
a=fmpt: 61 render=sasc; inline="e4"; compr=none;

m=audio 5004 RTP/AVP 61
c=IN IP4 169.229.60.64
a=rtpmap: 61 mpeg4-generic/44100
a=fmpt: 61 streamtype=5; mode=mwpp; config=""; profile-level-id=76;
a=fmpt: 61 render=sasc; url="http://www.berkeley.edu/oski.sasc";
a=fmpt: 61 cid="xjflsoeiurvpa09itnvlduihgnvet98pa3w9utnuighbuk";

