C=0 indicates the Congestion Control Information (CCI) field is
C=1 indicates the CCI field is 64-bits in length.


T = 0 indicates that the Sender Current Time (SCT) field is not
T = 1 indicates that the SCT field is present.
R = 0 indicates that the Expected Residual Time (ERT) field is not
R = 1 indicates that the ERT field is present.
EXT_NOP=0     No-Operation extension.
	      The information present in this extension field must be
	      ignored by receivers.


EXT_AUTH=1    Packet authentication extension
	      Information used to authenticate the sender of the packet.
	      If present, the format of this Header Extension and its
	      processing must be communicated out-of-band as part of the
	      session description.
	      It is recommended that senders provide some form of packet
	      authentication.  If EXT_AUTH is present, whatever packet
	      authentication checks that can be performed immediately
	      upon reception of the packet must be performed before
	      accepting the packet and performing any congestion
	      control-related action on it.
	      Some packet authentication schemes impose a delay of
	      several seconds between when a packet is received and when
	      the packet is fully authenticated.  Any congestion control
	      related action that is appropriate must not be postponed
	      by any such full packet authentication.


