Spam              = "Spam" HCOLON spam-value
                       ; examples:
                       ;  Spam: 1; To: Bob <sip:bob@biloxi.com>;
                       ;  From: Alice <sip:alice@atlanta.com>;
                       ;   tag=1928301774;
                       ;  Call-ID: a84b4c76e66710@pc33.atlanta.com
                       ;  ...
spam-value        = 1 *(SEMI spam-params)
spam-params       = To / From / Call-ID /
                       Call-start-val / Call-end-val /
                       Caller-sign-val / Callee-sign-val /
                       Caller-media-val / Callee-media-val /
                       Via / Route / Record-Route /
                       Alert-Info / ...
Call-start-val    = "Call-start" EQUAL date
Call-end-val      = "Call-end" EQUAL date
Caller-sign-val   = "Caller-sign" EQUAL hostport
Callee-sign-val   = "Callee-sign" EQUAL hostport
Caller-media-val  = "Caller-media" EQUAL hostport
Callee-media-val  = "Callee-media" EQUAL hostport

                  Figure 1: ABNF

