group="IpHeader"
dataTypeSemantics="identifier"
fieldId="60" applicability="all" status="current">
group="IpHeader"
dataTypeSemantics="identifier"
fieldId="8" applicability="all" status="current">
group="IpHeader"
dataTypeSemantics="identifier"
fieldId="27" applicability="all" status="current">
group="IpHeader"
fieldId="9" applicability="option" status="current">
group="IpHeader"
fieldId="29" applicability="option" status="current">
group="IpHeader"
fieldId="44" applicability="data" status="current">
group="IpHeader"
fieldId="169" applicability="data" status="current">
group="IpHeader"
dataTypeSemantics="identifier"
fieldId="12" applicability="all" status="current">
group="IpHeader"
dataTypeSemantics="identifier"
fieldId="28" applicability="all" status="current">
group="IpHeader"
fieldId="13" applicability="option" status="current">
group="IpHeader"
fieldId="30" applicability="option" status="current">
group="IpHeader"
fieldId="45" applicability="data" status="current">
group="IpHeader"
fieldId="168" applicability="data" status="current">
group="IpHeader"
dataTypeSemantics="identifier"
fieldId="5" applicability="all" status="current">
group="IpHeader"
dataTypeSemantics="identifier"
fieldId="137" applicability="data" status="current">
group="IpHeader"
dataTypeSemantics="identifier"
fieldId="55" applicability="all" status="current">
group="IpHeader"
dataTypeSemantics="identifier"
fieldId="138" applicability="data" status="current">
group="IpHeader"
dataTypeSemantics="identifier"
fieldId="31" applicability="all" status="current">
group="IpHeader"
dataTypeSemantics="identifier"
fieldId="54" applicability="data" status="current">
group="IpHeader"
dataTypeSemantics="identifier"
fieldId="4" applicability="all" status="current">
group="IpHeader"
dataTypeSemantics="identifier"
fieldId="88" applicability="all" status="current">
group="transportHeader"
dataTypeSemantics="identifier"
fieldId="7" applicability="all" status="current">
group="transportHeader"
dataTypeSemantics="identifier"
fieldId="11" applicability="all" status="current">
group="transportHeader"
dataTypeSemantics="identifier"
fieldId="32" applicability="all" status="current">
group="transportHeader"
dataTypeSemantics="identifier"
fieldId="139" applicability="all" status="current">
group="transportHeader"
dataTypeSemantics="identifier"
fieldId="33" applicability="all" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="56" applicability="data" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="57" applicability="data" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="58" applicability="data" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="59" applicability="data" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="80" applicability="data" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="81" applicability="data" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="146" applicability="data" status="current">
group="subIpHeader"
fieldId="147" applicability="data" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="70" applicability="all" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="71" applicability="all" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="72" applicability="all" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="73" applicability="all" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="74" applicability="all" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="75" applicability="all" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="76" applicability="all" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="77" applicability="all" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="78" applicability="all" status="current">
group="subIpHeader"
dataTypeSemantics="identifier"
fieldId="79" applicability="all" status="current">
group="derived"
dataTypeSemantics="identifier"
fieldId="15" applicability="data" status="current">
group="derived"
dataTypeSemantics="identifier"
fieldId="62" applicability="data" status="current">
group="derived"
dataTypeSemantics="identifier"
fieldId="162" applicability="all" status="current">
group="derived"
dataTypeSemantics="identifier"
fieldId="16" applicability="all" status="current">
group="derived"
dataTypeSemantics="identifier"
fieldId="17" applicability="all" status="current">
group="derived"
dataTypeSemantics="identifier"
fieldId="128" applicability="all" status="current">
group="derived"
dataTypeSemantics="identifier"
fieldId="129" applicability="all" status="current">
group="derived"
dataTypeSemantics="identifier"
fieldId="18" applicability="all" status="current">
group="derived"
dataTypeSemantics="identifier"
fieldId="63" applicability="all" status="current">
group="derived"
dataTypeSemantics="identifier"
fieldId="46" applicability="data" status="current">
group="derived"
dataTypeSemantics="identifier"
fieldId="47" applicability="data" status="current">
group="derived"
dataTypeSemantics="identifier"
fieldId="140" applicability="data" status="current">
dataTypeSemantics="identifier"
group="config"
fieldId="130" applicability="all" status="current">
dataTypeSemantics="identifier"
group="config"
fieldId="131" applicability="all" status="current">
group="minMax"
fieldId="25" applicability="all" status="current">
group="minMax"
fieldId="26" applicability="all" status="current">
group="minMax"
fieldId="52" applicability="data" status="current">
group="minMax"
fieldId="53" applicability="data" status="current">
dataTypeSemantics="flags"
group="minMax"
fieldId="64" applicability="all" status="current">
dataTypeSemantics="flags"
group="minMax"
fieldId="6" applicability="all" status="current">
group="timestamp"
fieldId="150" applicability="data" status="current">
group="timestamp"
fieldId="151" applicability="data" status="current">
group="timestamp"
fieldId="152" applicability="data" status="current">
group="timestamp"
fieldId="153" applicability="data" status="current">
group="timestamp"
fieldId="154" applicability="data" status="current">
group="timestamp"
fieldId="155" applicability="data" status="current">
group="timestamp"
fieldId="156" applicability="data" status="current">
group="timestamp"
fieldId="157" applicability="data" status="current">
group="timestamp"
fieldId="158" applicability="data" status="current">
group="timestamp"
fieldId="159" applicability="data" status="current">
group="timestamp"
fieldId="160" applicability="data" status="current">
group="timestamp"
fieldId="22" applicability="data" status="current">
group="timestamp"
fieldId="21" applicability="data" status="current">
group="misc"
fieldId="36" applicability="all" status="current">
group="misc"
fieldId="37" applicability="all" status="current">
group="misc"
dataTypeSemantics="identifier"
fieldId="136" applicability="data" status="current">
group="misc"
fieldId="161" applicability="data" status="current">
group="misc"
fieldId="162" applicability="data" status="current">
dataTypeSemantics="deltaCounter"
group="flowCounter"
fieldId="1" applicability="data" status="current">
dataTypeSemantics="deltaCounter"
group="flowCounter"
fieldId="23" applicability="data" status="current">
dataTypeSemantics="totalCounter"
group="flowCounter"
fieldId="85" applicability="all" status="current">
dataTypeSemantics="totalCounter"
group="flowCounter"
fieldId="170" applicability="all" status="current">
dataTypeSemantics="deltaCounter"
group="flowCounter"
fieldId="2" applicability="data" status="current">
dataTypeSemantics="deltaCounter"
group="flowCounter"
fieldId="24" applicability="data" status="current">
dataTypeSemantics="totalCounter"
group="flowCounter"
fieldId="86" applicability="all" status="current">
dataTypeSemantics="totalCounter"
group="flowCounter"
fieldId="171" applicability="all" status="current">
dataTypeSemantics="deltaCounter"
group="flowCounter"
fieldId="132" applicability="data" status="current">
dataTypeSemantics="deltaCounter"
group="flowCounter"
fieldId="133" applicability="data" status="current">
dataTypeSemantics="totalCounter"
group="flowCounter"
fieldId="134" applicability="data" status="current">
dataTypeSemantics="totalCounter"
group="flowCounter"
fieldId="135" applicability="data" status="current">
dataTypeSemantics="deltaCounter"
group="flowCounter"
fieldId="19" applicability="data" status="current">
dataTypeSemantics="deltaCounter"
group="flowCounter"
fieldId="20" applicability="data" status="current">
dataTypeSemantics="totalCounter"
group="processCounter"
fieldId="41" applicability="data" status="current">
dataTypeSemantics="totalCounter"
group="processCounter"
fieldId="40" applicability="data" status="current">
group="processCounter"
dataTypeSemantics="totalCounter"
fieldId="42" applicability="data" status="current">
dataTypeSemantics="totalCounter"
group="processCounter"
fieldId="3" applicability="data" status="current">
dataTypeSemantics="totalCounter"
group="processCounter"
fieldId="163" applicability="data" status="current">
dataTypeSemantics="totalCounter"
group="processCounter"
fieldId="164" applicability="data" status="current">
dataTypeSemantics="totalCounter"
group="processCounter"
fieldId="165" applicability="data" status="current">
dataTypeSemantics="totalCounter"
group="processCounter"
fieldId="166" applicability="data" status="current">
dataTypeSemantics="totalCounter"
group="processCounter"
fieldId="167" applicability="data" status="current">
dataTypeSemantics="flags"
group="processCounter"
fieldId="172" applicability="all" status="current">
group="scope"
dataTypeSemantics="identifier"
fieldId="141" applicability="option" status="current">
group="scope"
dataTypeSemantics="identifier"
fieldId="142" applicability="option" status="current">
group="scope"
dataTypeSemantics="identifier"
fieldId="10" applicability="all" status="current">
group="scope"
dataTypeSemantics="identifier"
fieldId="14" applicability="all" status="current">
group="scope"
dataTypeSemantics="identifier"
fieldId="143" applicability="option" status="current">
group="scope"
dataTypeSemantics="identifier"
fieldId="144" applicability="option" status="current">
group="scope"
dataTypeSemantics="identifier"
fieldId="148" applicability="option" status="current">
group="scope"
dataTypeSemantics="identifier"
fieldId="145" applicability="option" status="current">
group="scope"
dataTypeSemantics="identifier"
fieldId="149" applicability="option" status="current">
targetNamespace="http://www.ietf.org/ipfix"
xmlns="http://www.w3.org/2001/XMLSchema"
name="item" type="string">
name="paragraph" type="string">
name="list" type="ipfix:descriptionList">
type="ipfix:text">
type="ipfix:text">
type="string">
type="ipfix:text">
name="enumeratedRange" type="ipfix:enumRange">
type="ipfix:range">
use="required">
type="ipfix:dataTypeSemantics" use="optional">
use="required">
use="optional">
type="ipfix:applicability" use="required">
use="required">
use="required">
