bit_location = sequence_number&BITMAP_LOC_MASK;
index = (sequence_number>>REDUNDANT_BIT_SHIFTS)&BITMAP_INDEX_MASK;

index = (sequence_number>>REDUNDANT_BIT_SHIFTS);

index_cur = ipsa->replaywin_lastseq>>REDUNDANT_BIT_SHIFTS;
diff = index - index_cur;
diff = BITMAP_LEN;
bit_location = sequence_number&BITMAP_LOC_MASK;

