collation-char  = ALPHA / DIGIT / "-" / ";" / "=" / "."

collation-id    = collation-prefix ";" collation-core-name
                       *collation-arg

collation-scope = Language-tag / "vnd-" hostname

collation-core-name = ALPHA *( ALPHA / DIGIT / "-" )

collation-arg   = ";" ALPHA *( ALPHA / DIGIT ) "="
                       1*( ALPHA / DIGIT / "." )

vendor-tag      =  "vnd-" hostname

collation-wild  =  ("*" / (ALPHA ["*"])) *(collation-char ["*"])
                         ; MUST NOT exceed 254 characters total

collation-selected =  ["+" / "-"] collation-id

collation-order =  ["+" / "-"] collation-wild

collation-uri   =  "http://www.iana.org/assignments/collation/"
                        collation-id ".xml"

collation-auri  =  ( "http://www.iana.org/assignments/collation/"
                        collation-order ".xml" ) / other-uri

other-uri       =  <absoluteURI>
                     ;  excluding the IANA collation namespace.

