name = definition
     The name of a rule is simply the name itself (without any enclosing
     "<" and ">") and is separated from its definition by the equal "="
     character.  Whitespace is only significant in that indentation of
     continuation lines is used to indicate a rule definition that spans
     more than one line.  Certain basic rules are in uppercase, such as
     SP, LWS, HT, CRLF, DIGIT, ALPHA, etc.  Angle brackets are used
     within definitions whenever their presence will facilitate
     discerning the use of rule names.

OCTET          = <any 8-bit sequence of data>
CHAR           = <any US-ASCII character (octets 0 - 127)>
UPALPHA        = <any US-ASCII uppercase letter "A".."Z">
LOALPHA        = <any US-ASCII lowercase letter "a".."z">
ALPHA          = UPALPHA | LOALPHA
DIGIT          = <any US-ASCII digit "0".."9">
CTL            = <any US-ASCII control character
                              (octets 0 - 31) and DEL (127)>
CR             = <US-ASCII CR, carriage return (13)>
LF             = <US-ASCII LF, linefeed (10)>
SP             = <US-ASCII SP, space (32)>
HT             = <US-ASCII HT, horizontal-tab (9)>
TEXT           = <any OCTET except CTLs>
quoted-pair    = "\" CHAR


error-response        = "ERROR: " error-message

error-message         = <any TEXT>


send_stations-response = *( station-definition CR )

station-definition     = station-name ":"
                                 station-frequency ":"
                                 station-band

station-name           = <any TEXT excluding ":"
                                  except as quoted-pair>

station-frequency      = *DIGIT "." *DIGIT  ; MUST be at least
                                                    ; one DIGIT in the
                                                    ; station-frequency

station-band           = 1*( [ ALPHA | DIGIT ] )

HOST=Remote client
VERSION=1.0
REQUEST=send_stations

send_queue-response    = *( job-definition CR )

job-definition         = job-number ":"
                                  start-time ":"
                                  duration ":"
                                  station-name ":"
                                  notify-address ":"
                                  status

job-number             = 1*( DIGIT )

start-time             = 1*( DIGIT )

duration               = 1*( DIGIT )

notify-address         = <RFC822-formatted mail address>
                                              ; any ":" in this
                                              ; field MUST be escaped
                                              ; as a quoted-pair

job-status             = numeric-job-status
                                  [ ( " " job-status-comment ) ]

job-status-character   = 3*( DIGIT )

job-status-comment     = <any TEXT excluding ":"
                                   except as quoted-pair>

HOST=Remote client
VERSION=1.0
REQUEST=send_queue

queue_update-data      = queue_update-pair
                                  *( ":" queue_update_pair )

queue_update-pair      = job-number ":"
                                  queue_update-status

queue_update-status    = ( "OK"
                                  | ( "ERROR " reason )
                                  | ( "COMPLETE " [file] )
                                  | ( "STREAM " url )
                                  )

reason                 = <any TEXT excluding ":"
                                   except as quoted-pair>

file                   = <any TEXT excluding ":"
                                   except as quoted-pair>

url                    = <a valid URL, with any ":"
                                   as quoted-pair>

queue_update-response   = "OK"

HOST=Remote client
VERSION=1.0
REQUEST=queue_update
DATA=1:OK:3:ERROR Job 2 already scheduled at that time

receivers-data        = 1*( DIGIT )

receivers-response    = "OK"

HOST=Remote client
VERSION=1.0
REQUEST=receivers
DATA=1

next_check-data       = 1*( DIGIT )

next_check-response   = "OK"

HOST=Remote client
VERSION=1.0
REQUEST=next_check
DATA=918216000

