targetNamespace="http://www.ibr.cs.tu-bs.de/chat-message"
xmlns="http://www.ibr.cs.tu-bs.de/chat-message"
elementFormDefault="qualified"
attributeFormDefault="unqualified"
minOccurs="0" maxOccurs="unbounded"/>
       </xsd:sequence>
     </xsd:complexType>

     <xsd:complexType name="GetPeersMessage">
       <xsd:annotation>
         <xsd:documentation>
           A peer may send a "getpeers" message to request a list of
           other peer addresses in order to extend its own list of
           potential connection peers.
         </xsd:documentation>
       </xsd:annotation>
       <xsd:sequence>
         <xsd:element name="node"      type="PeerAddressType"/>
         <xsd:element name="sender"    type="UserIDType"/>
         <xsd:element name="messageid" type="MessageIDType"/>
         <xsd:element name="timestamp" type="xsd:dateTime"/>
       </xsd:sequence>
     </xsd:complexType>

     <xsd:complexType name="PeersMessage">
       <xsd:annotation>
         <xsd:documentation>
           A node can make other nodes aware of a list of peer addresses
minOccurs="0" maxOccurs="unbounded"/>
       </xsd:sequence>
     </xsd:complexType>

     <xsd:complexType name="GetCertificateMessage">
       <xsd:annotation>
         <xsd:documentation>
           A peer may send a "getcertificate" message to request a
           certificate for a given user ID.
         </xsd:documentation>
       </xsd:annotation>
       <xsd:sequence>
         <xsd:element name="node"      type="PeerAddressType"/>
         <xsd:element name="sender"    type="UserIDType"/>
         <xsd:element name="messageid" type="MessageIDType"/>
         <xsd:element name="timestamp" type="xsd:dateTime"/>
         <xsd:element name="user"      type="UserIDType"/>
       </xsd:sequence>
     </xsd:complexType>

     <xsd:complexType name="CertificateMessage">
       <xsd:annotation>
         <xsd:documentation>
           A peer can send a certificate encapsulated in
default="false"/>
   	    </xsd:extension>
   	  </xsd:simpleContent>
