NDMP_CONFIG_GET_HOST_INFO    = 0x100,
NDMP_SCSI_OPEN               = 0x200,
NDMP_TAPE_OPEN               = 0x300,
NDMP_DATA_GET_STATE          = 0x400,
NDMP_NOTIFY_RESVD1           = 0x500,
NDMP_LOG_LOG                 = 0x600,
NDMP_FH_ADD_UNIX_PATH        = 0x700,
NDMP_CONNECT_OPEN            = 0x900,
NDMP_MOVER_GET_STATE         = 0xA00,
NDMP_RESERVED               = 0xFF00
