av-pairs    =     av-pair *(";" av-pair)
av-pair     =     attr ["=" value]
attr        =     token
value       =     token | quoted-string








set-cookie      =       "Set-Cookie:" cookies
cookies         =       1#cookie
cookie          =       NAME "=" VALUE *(";" set-cookie-av)
NAME            =       attr
VALUE           =       value
set-cookie-av   =       "Comment" "=" value
                          |       "CommentURL" "=" <"> http_URL <">
                          |       "Discard"
                          |       "Domain" "=" value
                          |       "Max-Age" "=" value
                          |       "Path" "=" value
                          |       "Port" [ "=" <"> portlist <"> ]
                          |       "Secure"
                          |       "Version" "=" 1*DIGIT
                          |       "ICD" "=" value
portlist        =       1#portnum
portnum         =       1*DIGIT

cookie         =  "Cookie:" cookie-version 1*((";" | ",") cookie
                         -value)
cookie-value   =  NAME "=" VALUE [";" path] [";" domain] [";"
                         port]
cookie-version =  "$Version" "=" value
NAME           =  attr
VALUE          =  value
path           =  "$Path" "=" value
domain         =  "$Domain" "=" value
port           =  "$Port" ["=" <"> value <">]
ICD            =  "$ICD" "=" value

server_sessionID=4jZmb5HFoXHe2xU6jKlqPkDD4GEdmUuZnlkROI9wXvIRQFFO
server_sessionID=4jZmb5HFoXHe2xU6jKlqPkDD4GEdmUuZnlkROI9wXvIRQFFO
