USE_METRICS = 1, this link metric is advertised in topology updates
RID = net_rid, and net_expire is the time at which the tuple expires
rt_dest = RID(u),
rt_if_id = nbr_if(p(u)),
rt_next = nbr_if_addr(p(u)), obtained from the
              neighbor table for rt_if_id,
rt_dist = d(u).
next_ia_time = current_time + IA_INTERVAl.
next_ha_time = current_time + HA_INTERVAl.
next_npa_time = current_time + NPA_INTERVAL.
if_addr = addr_m,
if_rid = u,
if_expire = current_time + IA_HOLD_TIME.
h_addr = addr_m,
h_rid = u,
h_expire = current_time + HA_HOLD_TIME.
net_prefix = prefix_m,
net_length = length_m,
net_rid = u,
net_expire = current_time + NPA_HOLD_TIME.
