grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Asaml2-bearer&
assertion=PHNhbWxwOl...[omitted for brevity]...ZT4

grant_type=authorization_code&
code=vAZEIHjQTHuGgaSvyW9hO0RpusLzkvTOww3trZBxZpo&
client_assertion_type=urn%3Aietf%3Aparams%3Aoauth
client_assertion=PHNhbW...[omitted for brevity]...ZT

ID="ef1xsbZxPV2oqjd7HTLRLIBlBb7"
Version="2.0"
xmlns="urn:oasis:names:tc:SAML:2.0:assertion">
Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">
Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
NotOnOrAfter="2010-10-01T20:12:34.619Z"
Recipient="https://authz.example.net/token.oauth2"/>
grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Asaml2-
