Peer-Info = Peer-ID
               [Address-Info]
               [Uptime]
               [Certificate]
               [Connections]
               [Node-Resource-Utilization]
               [ext]

Resource-Object = Resource-ID
               [Peer-Info]
               [Owner]
               [Signature]
               Value
               [ext]

T1=2^i*T0                  V              Transport Err. or
     tx_Msg              +------------+       Timer T2 fires
                  +------|            |       Inform App.
                  |      | Trans_Msg  |----------------->+
                  +----->|            |                  |
                         +------------+                  |
                           |   | ACK received /          |
T1=2^i*T0                  V              Transport Err. or
     tx_Msg              +------------+       Timer T2 fires
                  +------|            |       Inform App.
                  |      | Trans_Msg  |----------------->+
                  +----->|            |                  |
                         +------------+                  |
                               |                         |
                               | ACK received            |
                               | stop Timer T1, T2       |
                               V                         |
                         +------------+                  |
                         |            |                  |
                         | Terminated |----------------->|
                         |            |                  |
                         +------------+                  |
                                                         |
                         +-----------+                   |
                         |           |                   |
                         |  Failure  |<------------------+
                         |           |
                         +-----------+

P2PP-Msg = Enroll / Authenticate / Bootstrap /
              Join / Leave / KeepAlive /
              LookupPeer / ExchangeTable / Query
              Replicate / Transfer /
              Publish / LookupObject / RemoveObject /
              Tunnel / Connect
              Invite /
              GetDiagnostics

Enroll = Common-header
            [Request-Options]
            Peer-Info
            Certificate-Sign-Request
            Password


Authenticate = Common-header
            [Request-Options]
            Peer-Info
            Certificate-Sign-Request
            Password
Bootstrap = Common-header
             Peer-Info


P2P-options = Hash-algorithm
              Hash-algorithm-length
              DHT-algorithm
              OverlayID-length
              Overlay-ID

Join = Common-header
        [Request-Options]
        Peer-Info
Routing-table = Num-entries
                 [Peer-Info]*

Neighbor-peers = Num-entries
                  [Peer-Info]*

Leave = Common-header
         Peer-Info
         [Peer-Info]*
         [Resource-object]*

KeepAlive = Common-header
              Peer-Info
              Expires


LookupPeer = Common-Header
              [Request-Options]
              Peer-Info
              PLookup


ExchangeTable = Common-Header
                 Peer-Info
                 Request-Options


Query = Common-Header
         Peer-Info


Replicate = Common-header
               Peer-Info
               [Resource-Object]*
               [Ext]

Transfer = Common-header
            Peer-Info
            [Resource-object]+
            [Ext]

PublishObject = Common-header
           [Request-Options]
           Peer-Info
           Resource-Object


LookupObject = Common-header
          [Request-Options]
          Peer-Info
          RLookup
RemoveObject = Common-header
          [Request-Options]
          Peer-Info
          Resource-Object

Tunnel = Common-header
          [Request-Options]
          Peer-Info
          Resource-Object

Connect = Common-header
          [Request-Options]
          Peer-Info

Invite = Common-header
          Peer-Info

AB=00 "(Mandatory)":  If the object is not understood, the entire
      message containing it MUST be rejected with an "Object Type Error"
      message with sub code 1 ("Unrecognized Object").

AB=01 "(Ignore)":  If the object is not understood, it MUST be
      deleted and the rest of the message processed as usual.

