GP_KEY = {

GATE_PASS = Signature | GP_KEY.Index | Secret

Secret = encrypt(GP_KEY.ek, {Trust Anchor IP | Trust Anchor ID |
Signature = prf(GP_KEY.ak | GP_KEY.Index | Secret)

ACCESS_TOKEN = prf(encrypt(GP_SECRET, GATE_PASS | Client's Identity))

ACCESS_TOKEN = prf(encrypt(GP_SECRET, GATE_PASS | Client's Identity





