xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:yang:ietf-subscribed-notifications"/>
xmlns="urn:ietf:params:xml:ns:yang:ietf-subscribed-notifications">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:yang:ietf-subscribed-notifications">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:yang:ietf-subscribed-notifications"
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:yang:ietf-yang-push">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:yang:ietf-subscribed-notifications">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:yang:ietf-subscribed-notifications">
xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
xmlns="urn:ietf:params:xml:ns:yang:ietf-subscribed-notifications">
xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
xmlns="urn:ietf:params:xml:ns:yang:ietf-subscribed-notifications">
xmlns="urn:ietf:params:xml:ns:yang:ietf-vrrp">
xmlns="urn:ietf:params:xml:ns:yang:ietf-subscribed-notifications">
xmlns="urn:ietf:params:xml:ns:yang:ietf-subscribed-notifications">
xmlns="urn:ietf:params:xml:ns:yang:ietf-vrrp"/>
