start = COSE_Untagged_Message / COSE_Tagged_Message / COSE_Key / COSE_KeySet

signature = Sign(message content, key)

valid = Verification(message content, key, signature)


tag = MAC_Create(message content, key)

valid = MAC_Verify(message content, key, tag)


ciphertext = Encrypt(message content, key, additional data)

