id='ne91v36s'
to='juliet@example.com/t3hr0zny'
type='set'>
action='session-initiate'
initiator='romeo@example.net/v3rsch1kk3l1jk'
sid='a73sjjvkla37jfea'>
media='audio'
name='this-is-the-audio-content'
senders='both'>
clockrate='16000'
id='103'
name='L16'/>
id='hu2s61f4'
from='romeo@example.net/v3rsch1kk3l1jk'
type='set'>
action='session-initiate'
initiator='juliet@example.com/t3hr0zny'
sid='a73sjjvkla37jfea'>
media='audio'
name='this-is-the-audio-content'>
id='hu2s61f4'
to='romeo@example.net/v3rsch1kk3l1jk'
type='result'/>

v=0
o=alice 2890844526 2890844526 IN IP4 client.example.com
s=-
c=IN IP4 192.0.2.101
t=0 0
m=audio 49172 RTP/AVP 0
a=rtpmap:96 SPEEX/16000
a=rtpmap:97 SPEEX/8000
a=rtpmap:18 G729

id='ol3ba71g'
to='juliet@example.com/t3hr0zny'
type='set'>
action='session-info'
initiator='juliet@example.com/t3hr0zny'
sid='a73sjjvkla37jfea'>
id='ol3ba71g'
to='romeo@example.net/v3rsch1kk3l1jk'
type='result'/>

v=0
o=romeo 2890844527 2890844527 IN IP4 client.example.net
s=-
c=IN IP4 192.0.2.201
t=0 0
m=audio 3456 RTP/AVP 0
a=rtpmap:97 SPEEX/8000
a=rtpmap:18 G729/8000

id='pd1bf839'
to='juliet@example.com/t3hr0zny'
type='set'>
action='session-accept'
initiator='juliet@example.com/t3hr0zny'
responder='romeo@example.net/v3rsch1kk3l1jk'
sid='a73sjjvkla37jfea'>
media='audio'
name='this-is-the-audio-content'>
id='pd1bf839'
to='juliet@example.com/t3hr0zny'
type='result'/>

id='rv301b47'
to='juliet@example.com/t3hr0zny'
type='set'>
action='session-terminate'
initiator='juliet@example.com/t3hr0zny'
reasoncode='no-error'
sid='a73sjjvkla37jfea'/>
id='rv301b47'
to='juliet@example.com/t3hr0zny'
type='result'/>


