Disposition-Notification =
             "Disposition-Notification" ": " [(notify-req *(COMMA notify-req))]
notify-req = ("negative-delivery" / "positive-delivery" / "read" / Token) *(SEMI disp-notif-params)
disp-notify-params = "aggregate" / generic-param

Message-ID = "Message-ID" ": " Token

Original-To = "Original-To" ": "  [ Formal-name ] "<" URI ">"

Really-From = "Really-From" ": "  [ Formal-name ] "<" URI ">"

Really-From = "Really-To" ": "  [ Formal-name ] "<" URI ">"



