cu = coap-URI   ; from [I-D.ietf-core-coap], Section 6.1
su = coaps-URI  ; from [I-D.ietf-core-coap], Section 6.2
tu = cu / su


s  = "coap" / "coaps" ; from [I-D.ietf-core-coap], Sections 6.1 and 6.2
hp = host [":" port]  ; from [RFC3986] Sections 3.2.2 and 3.2.3
p  = path-abempty     ; from [RFC3986] Section 3.3.
q  = [ "?" query ]    ; from [RFC3986] Section 3.4


