L = Length included; 
M = More fragments; 
S = EAP-SSC Start; 
E = EAP-SSC End; 
D = EAP-SSC Digest; 
C = EAP-SSC Ciphered payload; 
X = EAP-SSC Sequence of X509 Certificate(s); 
R = Reserved. 

Type=EAP-SSC-Type and no data. This serves as a fragment 
Z = r2 XOR D(r1 | s), 
SK = D(r1 | r2 | s). 

SK = D(r1 | r2 |s)                           SK = D(r1 | r2 | s)  
SK = D(r1 | r2)                                 SK = D(r1 | r2)  
U = (r2 ** K1public) MOD Modulo1  
V = (D0 ** K2private) MOD Modulo2 

D0 = D(Code | Identifier | Length | EAP-Type | Sub-Type | Flags | 
D2=D(M2 | D1 | SK) 
             Modification from EAPOL 
             format to EAPOR format 
D1 = D(M1,SK);  
