p_C = ( p_CL / k )^2                  (1)

p_C = (p')^2.                         (2)

p_CL = k*p'.                          (3)

p_L = max(p'_L, p_CL),                (4)

U=1):

U=1).  Comparing it with the maximum out of two is the same as the
U=1 has been used in experiments so far, but results might be even
r_C = 1.22 / (R_C * p_C^0.5)          (5)
r_L = 2 / (R_L * p_CL)                (6)

r_c = r_L
p_C = ( p_CL / k )^2                  (1)

R_C  = (R_max + b*R_max) / 2
          = R_max * (1+b)/2

R_reno = 0.75 * (R_b + target);     R_creno = 0.85 * (R_b + target).
                                                                    (8)

k_reno = 1.64*0.75*(R_b+target)/R_b
          = 1.23*(1 + target/R_b);     k_creno = 1.39 * (1 + target/R_b)

k_reno = 1.23 * (1 + 15/25)        k_creno  = 1.39 * (1 + 15/25)
          = 1.97                               = 2.22
          ~= 2                                 ~= 2                  (9)

