start = udpcl-ext-map

udpcl-ext-map = $udpcl-ext-map .within udpcl-ext-map-structure
udpcl-ext-map-structure = {
       * ext-key => any
ext-key = (int .size 2) .ne 0
                   Figure 4: Extension Map structure CDDL

time-duration = uint

                        Figure 7: Sender Listen CDDL

nodeid = tstr

                       Figure 8: Sender Node ID CDDL

