namestring    = assigned-name
                      [ "?" q-string ]
                      [ "??" r-string ]
                      [ "#" f-string ]
assigned-name = "urn" ":" NID ":" NSS
NID           = (alphanum) 0*30(ldh) (alphanum)
ldh           = alphanum / "-"
NSS           = pchar *(pchar / "/")
q-string      = pchar *( pchar / "/" / "?" )
r-string      = pchar *( pchar / "/" / "?" )
f-string      = fragment

InformalNamespaceName = "urn-" Number
Number                = DigitNonZero 0*Digit
DigitNonZero          = "1"/ "2" / "3" / "4"/ "5"
                             / "6" / "7" / "8" / "9"
Digit                 = "0" / DigitNonZero

