i=i_0+2*i_1+(2^2)*i_2+...+(2^15)*i_{15}.  

 
 
    

H_v = |                    | 
                      | H_{v-1}  - H_{v-1} | 
                      +--                --+ 

X=(x_0,...,x_{v-1})<Y=(y_0,...,y_{v-1}) 

                              if and only if 

L = {u_0,...,u_{K-1}}, with u_0 <...<u_{K-1} 

Psi = XOR{prod(Psi_i,theat^i): i=0,1...,15} and 

I = XOR{prod(I_i,theat^i): i=0,1...,15} 

