fileURI       = "file" ":" ( auth-file / local-file )

auth-file     = "//" ( host-file / nohost-file )

host-file     = hostpart path-absolute
                                     ;   file://<host>/<path>
                                     ;   file://localhost/<path>

nohost-file   = path-abs       ; begins with "/"
                    / path-abs-win   ; begins with drive-letter
                                     ;   file:///<path>
                                     ;   file:////<bad-UNC-path>
                                     ;   file://c:/<path> *

local-file    = path-absolute  ;   file:/<path>
                    / path-abs-win   ;   file:c:/<path>
hostpart      = "localhost" / host

path-abs      = 1*( "/" segment )

path-abs-win  = drive-letter path-absolute
drive-letter  = ALPHA [ drive-marker ]
drive-marker  = ":" / "|"

UNC        = "\\" hostname "\" sharename *( "\" objectname )
hostname   = <NetBIOS name, FQDN, or IP address of a server>
sharename  = <name of a share or resource to be accessed>
objectname = <the name of an object>

