tag="arabic-indic-digits" />
tag="extended-arabic-indic-digits" />
match="preferred" />

comment="non-empty lablel of preferred code points">
match="preferred" />
xmlns="http://relaxng.org/ns/structure/1.0">
