targetNamespace="urn:ietf:params:xml:ns:clue-info"
xmlns="urn:ietf:params:xml:ns:clue-info"
elementFormDefault="qualified"
attributeFormDefault="unqualified"
version="1.0">

schemaLocation=
  "http://www.iana.org/assignments/xml-registry/schema/vcard-4.0.xsd"/>


maxOccurs="unbounded"/>
type="tns:spatialInformationType"/>
fixed="true"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
        <xs:element name="mobility" type="mobilityType" minOccurs="0" />
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
type="xs:boolean"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0">
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
type="tns:spatialInformationType"/>
fixed="true"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
type="xs:boolean"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
targetNamespace="urn:ietf:params:xml:ns:clue-info-ext"
xmlns="urn:ietf:params:xml:ns:clue-info-ext"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

schemaLocation=
   "http://www.iana.org/assignments/xml-registry/schema/vcard-4.0.xsd"/>

schemaLocation="clue-data-model-schema.xsd"/>

clueInfoID="NapoliRoom">
       <mediaCaptures>
           <mediaCapture
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:type="audioCaptureType"
captureID="AC0"
mediaType="audio">
               <captureSceneIDREF>CS1</captureSceneIDREF>
               <nonSpatiallyDefinable>true</nonSpatiallyDefinable>
               <individual>true</individual>
               <encGroupIDREF>EG1</encGroupIDREF>
               <ns3:newAudioFeature>newAudioFeatureValue
               </ns3:newAudioFeature>
captureID="OMC0"
mediaType="other media type">
               <captureSceneIDREF>CS1</captureSceneIDREF>
               <nonSpatiallyDefinable>true</nonSpatiallyDefinable>
               <encGroupIDREF>EG1</encGroupIDREF>
               <ns3:otherMediaCaptureTypeFeature>OtherValue
               </ns3:otherMediaCaptureTypeFeature>
content="text/html;charset=iso-8859-1"/>
clueInfoID="NapoliRoom">
