beta = VRF_hash(SK, alpha)

pi = VRF_prove(SK, alpha)

beta = VRF_proof2hash(pi)

y = g^x - VRF public key, an EC point

y = g^x - VRF public key

ctr=1) on average.  See also [Icart09].

suite = a single octet specifying ECVRF ciphersuite.

p = 2^255-19, the size of the finite field F, a prime, for
A = 486662, Montgomery curve constant for Curve25519

cofactor = 8 , the cofactor for Curve25519

e = v ^ ((p-1)/2) mod p

finalu = (e*u + (e-1) * (A/2)) mod p

str = str || EC2OSP(p_i)

cofactor = 8.

