return-option =/ status-option

status-option = "STATUS" SP "(" status-att *(SP status-att) ")"
                       ;; This ABNF production complies with
                       ;; <option-extension> syntax.


