HTTP2-Settings    = token68

cache-control = max-age=60, private\0must-revalidate
content-type = text/html

host = example.org
accept = image/jpeg

etag = "xyzzy"
expires = Thu, 23 Jan ...

host = example.org
content-length = 123

content-length = 123

content-length = 123
foo = bar

