Source == "Trading" or Destination == "Trading" --> DSCP <- 6;
Source == "E-Mail" or Destination == "E-Mail" --> DSCP <- 4;
Source == "FTP" or Destination == "FTP" --> DSCP <- 2.

Source == "Trading" or Destination == "Trading" --> DSCP <- 6;
Source == "E-Mail" or Destination == "E-Mail" --> DSCP <- 2;
Source == "FTP" or Destination == "FTP" --> drop;

Source == "Trading" or Destination == "Trading" --> DSCP <- 6;
Source == "E-Mail" or Destination == "E-Mail" --> drop;
Source == "FTP" or Destination == "FTP" --> drop.

