header = header-name ":" spaces "Mutual" spaces fields
header-name = "WWW-Authenticate" | "Optional-WWW-Authenticate"
                       | "Authorization" | "Authentication-info"
spaces = 1*(SP | HT | CR LF 1*(SP | HT))+
fields = field 0*("," spaces fields)
field = key "=" value
key = extensive-token
extensive-token = token | extension-token
extension-token = token "@" token
token = 1*("0"..."9" | "A"..."Z" | "a"..."z"
                        | "-" | "_" | ".")
value = extensive-token | integer | hex-integer
                     | hex-fixed-number
                     | base64-fixed-number | string
integer = "0" | ("1"..."9") 0*("0"..."9")
hex-integer = "0" |
                       ("1"..."9" | "A"..."F" | "a"..."f")
                       0*("0"..."9" | "A"..."F" | "a"..."f")
hex-fixed-number = 1*("0"..."9" | "A"..."F" | "a"..."f")
base64-fixed-number = string
string = <"> *(<TEXT except <"> and "\"> | "\\" |
                             "\" <"> | "\,")* <">

stale=0

stale=1

realm=xxxx, wa=xxxx

time=x, path=xxxx

pi = H(VS(algorithm) | VS(auth-domain) | VS(realm) | VS(username) |
o_A = H(hex(04) | GEtoOS_x(w_A) | GEtoOS_x(W_B) | GEtoOS_x(z) |
o_B = H(hex(03) | GEtoOS_x(w_A) | GEtoOS_x(W_B) | GEtoOS_x(z) |
realm=xxxx, stale=0

