stat = find-tag(input, tag-file, input-std, tag-rec)
	
stat=idn-XY-normalize(input, input-std, tag-rec, input-list, err-report)

stat=idn-XY-decompose(input, USASCII, tag-rec, input-list, err-report)

stat=idn-XY-present(output-list, output-string, err-report)

stat=idn-XY-fitting(output-list, output-name, err-report)

flag = find-tag(input, tag-file, input-std, tag-rec);
tag = get-tag(tag-rec);

output-std = UCS;
output-std = USASCII;
output-std = USASCII;
stat=idn-XY-normalize(input, input-std, tag-rec, input-list, err-report)*/

stat=idn-zh-fitting(output-list, idn-name, err-report);
stat=idn-kr-fitting(output-list, idn-name, err-report);
stat=idn-XY-fitting(output-list, idn-name, err-report);
