Link-Template  = "Link-Template" ":" #templated-link
templated-link = "<" URI-Template ">" *( ";" parameter )

rel="https://example.org/rel/widget";
var-base="https://example.org/vars/"

rel="https://example.org/rel/widget";
var-base="/vars/"

