VALID_DATA = 0, /* the data located by this extent is valid for  
                        reading and writing. */ 

INVALID_DATA = 1,  /* the location is valid; the data is invalid. 
                           It could be overwritten by the valid data.  
                           It is a newly (pre-) allocated extent. There 
                           is physical space. */ 

NONE_DATA = 2,  /* the location is invalid. It is a hole in the  
                        file. There is no physical space. */ 

