PW-TTL=2): this could be done either via administrative
C=0                  C=1
c=1), following the procedures defined in section 6.2 of [RFC 4447],
c=1), as if it has received c=1 from T-PE1. It can also send a T-LDP
PW-TTL=1: these packets should be processed by S-PE1 and not
