AIF-MQTT = AIF-Generic<topic_filter, permissions>
topic_filter = tstr
permissions = [+permission]
permission = "pub"/"sub"

                       Figure 5: AIF-MQTT data model

   Topic filters are implemented according to Section 4.7 of MQTT v5.0 -
   the OASIS Standard [MQTT-OASIS-Standard-v5] and includes special
   wildcard characters.  The multi-level wildcard, '#', matches any
   number of levels within a topic, and the single-level wildcard, '+',
   matches one topic level.

   An example scope field may contain:

Rsvd=Reserved, len.=length, Proto.=Protocol)

