sucvID = hmac-sha-1-128(sha1(imprint), sha1(PK))
sucvHID = hmac-sha-1-64(sha1(imprint), sha1(PK))

skeymat = prf(hash (g^{xy} mod p), N1 | imprint)

skey_sucv = prf(skeymat, g^{xy} mod p | N1 | imprint | 0)

skeymat_espauth = prf(skeymat, skey_sucv | g^{xy} | N1 |
                                        imprint | 1)

sucvHID = prf64(hash(public), k')

