srtp-crypto-suite-ext = "ARIA_128_CTR_HMAC_SHA1_80"/
                                   "ARIA_128_CTR_HMAC_SHA1_32"/
                                   "ARIA_192_CTR_HMAC_SHA1_80"/
                                   "ARIA_192_CTR_HMAC_SHA1_32"/
                                   "ARIA_256_CTR_HMAC_SHA1_80"/
                                   "ARIA_256_CTR_HMAC_SHA1_32"/
                                   "AEAD_ARIA_128_GCM"        /
                                   "AEAD_ARIA_256_GCM"        /
                                   "AEAD_ARIA_128_GCM_8"      /
                                   srtp-crypto-suite-ext

