presence-doc    = "<presence>" content "</presence>"
content         = *(element / char-data / reference)
element         = empty-tag / start-tag content end-tag
empty-tag       = "<" name "/>"
start-tag       = "<" name ">"
end-tag         = "</" name ">"
name            = (Letter / "_" / ":") *NameChar
char-data       = 1*DataChar
                          ; "]]>" may not appear, for compatibility
                          ; with SGML.
reference       = char-ref / entity-ref
char-ref        = "&#" 1*ASCIIDigit ';' /
                          "&#x" 1*ASCIIHexDigit
                          ; Must refer to a valid Char
entity-ref      = "&lt;" / "&gt;" / "&amp;" / "&apos;" /
                          "&quot;"

NameChar        = Letter / Digit / "." / "-" / "_" / ":" /
                          CombiningChar / Extender
DataChar        = %x9 / %xA / %xD / %x20-25 / %x27-3B /
                          %x3D-D7FF / %xE000-FFFD / %x10000-310FFFF
                          ; Most valid Unicode characters
Char            = DataChar / "&" / "<"
ASCIIDigit      = %x30-39
                          ; [0-9]
ASCIIHexDigit   = %x30-39 / %x41-46 / %x61-66
                          ; [0-9A-Fa-f]

