PXC = Photonic CrossConnect        TNE = Transport Network Element 
TX = Transmit                      RX = Receive 
    
               FIGURE 1: PXC to TNE Reference Configuration 
    
Type = REG-REQ  
 
Type = REG-COMPLETE  
 
Type = KEEP-ALIVE-REQ  
    
Type = KEEP-ALIVE_RES 
    
Type = MON-REQ  
    
Type = DEFECT-NOTIFICATION  
    
Type = STATUS-REQ  
    
Type = STATUS-RESP  
    
Type = CONFIG-UPDATE  
    
