dtnURI = "dtn:" ("none" / nontrivialSSP)

nontrivialSSP = dtnURIelt *("!" dtnURIelt)

dtnURIelt = [opname] ":" URI ; URI as defined in RFC 3986 [*]

opname = "push" / "pop" / "next" / "flood" / "exec"/ "find"

