C4=QoS
C3=Transport Aggregation, C4=Transport Core, C5=Cloud Edge,
C6=Cloud Core)
C2=Non-technical (without technical feedback) , see Section 4.2
C4=QoS C5=Storage C6=Compute
C2=Non-technical (without technical feedback), see Section 4.2
C4=QoS
C2=Non-technical (without technical feedback), see Section 4.2
