rel="self"/>
rel="alternate"/>
rel="edit"/>

href="http://www.example.org/csirt/RID/InvestigationRequests">
         <atom:title type="text">Investigation Requests</atom:title>
         <accept>application/atom+xml; type=entry</accept>
rel="self"/>

rel="self"/>          <!-- by convention -->
rel="alternate"/>     <!-- required by Atom spec -->
rel="related"/>       <!-- link to a related DDOS resource
label="need to know" />
label="tactics, techniques, and procedures"/>
