CQ_MIN_SIZE = SUM(MaxPostedOnEachRQ)  
                        + SUM(MaxPostedOnEachS-RQ) 
                        + SUM(MaxPostedOnEachSQ) 

CQ_MIN_SIZE = SUM(SizeOfEachRQ)  
                                  + SUM(SizeOfEachS-RQ) 
                                  + SUM(SizeOfEachSQ)  

