search     = "BEGIN:VQUERY" CRLF
         [expand] [maxresults] [maxsize] querycomp
         "END:VQUERY" CRLF

expand     = "EXPAND" ":" ( "TRUE" / "FALSE")
        # If not specified, the default is EXPAND:FALSE .

comp-name = "VEVENT" / "VTODO" / "VJOURNAL" / VTIMEZONE"
            / "VALARM" / "VFREEBUSY" / "VCAR" / iana-name
            /  x-name

maxresults = integer

maxsize    = integer

querycomp  = ( query ) / ( queryname query ) / queryname

queryname  = "QUERYNAME:" text

query      = "QUERY:" ( query-min / query-92 )
   #
   # NOTE: query-min MUST be implemented in CSs.
   #
   #    query-92 is ONLY used if CAPABILITY returns SQL-92
   #    as the QUERYLEVEL value or if QUERYLEVEL is not
        specified.

query-min  = capselect-min capfrom-min capwhere-min

capselect-min = "SELECT" capmin-cols "FROM" capmin-comps
                  "WHERE" capmin-cmp

capmin-col    = # Any property name found in any of the
                  components.

capmin-cols = ( capmin-col / capmin-col "," capmin-cols )
capmin-comps = ( comp-name / comp-name ","
                  compmin-comps )

capmin-cmp   = ( colname cmpmin-oper colvalue
colname      = ( # Any valid component property name.
cmpmin-oper      = ( " = "  / " != " / " < " / " > " / "
capmin-logical   = ( " AND " / " OR " )

query-92         = capselect-92 capfrom-92 capwhere-92
capselect-92     = # Any valid [SQL] string that goes
capfrom-92       = # Like capmin-comps except embedded
capwhere-92      = # Any valid [SQL] string that goes
caporderby-92    = # Any valid [SQL] string that goes
component=VEVENT
  C:
  C: BEGIN:VCALENDAR
  # etc
  C: END:VCALENDAR
  C: .
  # after 10 seconds...
  S: .
  S: 2.0.2
  S: .
  S: .
  C: CONTINUE:10
  S: 2.0
  S: .
  S: Content-type:text/calendar;
Method=RESPONSE;Component=VDATA;
  S: Optinfo=VERSION:2.1
  S:
  S: BEGIN:VCALENDAR

  S: VERSION:2.1
  S: CALID:cap://cal.example.com/relcal2
  # etc.
  S: END:VCALENDAR
  S: .


OPTINFO="CMDID:abcde"
  # This 2.0 is the transport reply status and ends with a
OPTINFO="CMDID:abcde"
  S:
  S: BEGIN:VCALENDAR
  S: VERSION:2.1
  S: CMDID:abcde
  S: METHOD:RESPONSE
  S: BEGIN:VEVENT
  S: TARGET::cap://cal.example.com/relcal1
  S: REQUEST-STATUS:2.9
  S: END:VEVENT
  S: BEGIN:VEVENT
  S: REQUEST-STATUS:2.9
  S: REQUEST-STATUS:2.10
  S: END:VEVENT
  S: END:VCALENDAR
  S: .

  The responce returns the calendar (CALID) and UID of the
component=VCOMMAND
  C: Content-Transfer-Encoding:7bit
  C:

component=VCOMMAND
  S:
  S: BEGIN:VCALENDAR
  S: METHOD:RESPONSE
  S: BEGIN:VEVENT
  S: REQUEST-STATUS:2.0
  S: END:VEVENT
  S: END:VCALENDAR
  S: .

component=VCOMMAND
  C: Content-Transfer-Encoding:7bit
  C:
  C: BEGIN:VCALENDAR
  C: BEGIN:VCOMMAND
  C: METHOD:DELETE
  C: TARGET:cap://cal.foo.com/MrBill
  C: END:VCOMMAND
  C: END:VCALENDAR
  C: .
  S: 2.0
  S: .


Component=VCOMMAND
  C:
  C: BEGIN:VCALENDAR
  C: VERSION:2.1
  C: METHOD:MODIFY
  C: TARGET:relcal2
  C: BEGIN:VCOMMAND
  C: BEGIN:VQUERY
  C: QUERY:SELECT UID FROM VEVENT WHERE UID = 'abcd12345'
  C: END:VQUERY
  C: BEGIN:VEVENT
  C: DTSTART:19990421T160000Z
  C: DTEND:19990421T163000Z
  C: LOCATION:Joe's Diner
  C: END:VEVENT

  C: BEGIN:VEVENT
  C: DTSTART:19990421T160000Z
  C: DTEND:19990421T163000Z
  C: END:VEVENT
  C: END:VCOMMAND
  C: END:VCALENDAR
  C: .
  S: 2.0 cap://cal.example.com/relcal2

Component=VCOMMAND
  C:
  C: BEGIN:VCALENDAR
  C: VERSION:2.1
  C: METHOD:MODIFY
  C: TARGET:relcal2
  C: BEGIN:VCOMMAND
  C: BEGIN:VEVENT
  C: LOCATION:Building 6
  C: END:VEVENT
  C: BEGIN:VEVENT
  C: LOCATION:New office lobby
  C: END:VEVENT
  C: END:VCOMMAND
  C: END:VCALENDAR
  C: .
  S: 2.0 cap://cal.example.com/relcal2


Component=VQUERY
  C:
  C: BEGIN:VCALENDAR
  C: VERSION:2.1
  C: METHOD:READ
  C: CMDID:xyz12345
  C: TARGET:relcal2
  C: TARGET:cap://bobo.ex.com/relcal3
  C: BEGIN:VQUERY
  C: QUERY:SELECT DTSTART,DTEND,SUMMARY,UID
    FROM VEVENT
    WHERE DTEND >= '19990310T080000Z'
    AND DTSTART <= '19990310T190000Z'
    AND METHOD = 'CREATE'
  C: END:VQUERY
  C: END:VCALENDAR
  C: .
  S: 2.0 cap://cal.example.com/relcal2
  S: Content-type:text/calendar; Method=RESPONSE;
Optinfo=VERSION:2.1
  S: Content-Transfer-Encoding: 7bit
  S:
  S: BEGIN:VCALENDAR
  S: VERSION:2.1
  S: METHOD:RESPONSE
  S: BEGIN:VEVENT

  S: DTSTART:19990310T090000Z
  S: DTEND:19990310T100000Z
  S: UID:abcxyz12345
  S: SUMMARY:Meet with   Sir Elton
  S: END:VEVENT
  S: BEGIN:VEVENT
  S: DTSTART:19990310T130000Z
  S: DTEND:19990310T133000Z
  S: UID:abcxyz8999
  S: SUMMARY:Meet with   brave brave Sir     Robin
  S: END:VEVENT
  S: END:VCALENDAR
  S: .
  S: 2.0 cap://bobo.ex.com/relcal3
  S: Content-type:text/calendar;
Method=RESPONSE;Component=VDATA;
  S: Optinfo=VERSION:2.1
  S: Content-Transfer-Encoding: 7bit
  S:
  S: BEGIN:VCALENDAR
  S: VERSION:2.1
  S: METHOD:RESPONSE
  S: BEGIN:VDATA
  S: BEGIN:VEVENT
  S: DTSTART:19990310T140000Z
  S: DTEND:19990310T150000Z
  S: UID:123456asdf
  S: SUMMARY:Summer Budget
  S: END:VEVENT
  S: END:VDATA
  S: END:VCALENDAR
  S: .

Method=RESPONSE;Component=VDATA;
  S: Optinfo=VERSION:2.1
  S: Content-Transfer-Encoding: 7bit
  S:
  S: BEGIN:VCALENDAR
  S: VERSION:2.1
  S: BEGIN:VDATA
  S: BEGIN:VEVENT
  S: RESPONSE-CODE:3.8
  S: END:VEVENT


  S: END:VDATA
  S: END:VCALENDAR
  S: .

Method=RESPONSE;Component=VDATA;
  S: Optinfo=VERSION:2.1
  S: Content-Transfer-Encoding: 7bit
  S:
  S: BEGIN:VCALENDAR
  S: VERSION:2.1
  S: BEGIN:VDATA
  S: END:VDATA
  S: END:VCALENDAR
  S: .

  Find alarms within a range of time for booked (METHOD =
Component=VQUERY
  C:
  C: BEGIN:VCALENDAR
  C: VERSION:2.1
  C: METHOD:READ
  C: CMDID:xyz12345
  C: TARGET:relcal2
  C: TARGET:cap://bobo.ex.com/relcal3
  C: BEGIN:VQUERY
  C: QUERY:SELECT DTSTART,DTEND,SUMMARY,UID, VALARM.*
   FROM VEVENT,VTODO
   WHERE VALARM.TRIGGER >= '19990310T080000Z'
   AND VALARM.TRIGGER <= '19990310T190000Z'
   AND METHOD = 'CREATE'
  C: END:VQUERY
  C: END:VCALENDAR
  C: .
  S: 2.0 cap://bobo.ex.com/relcal3
  S: Content-type:text/calendar; Method=RESPONSE;
  S: Optinfo=VERSION:2.1
  S: Content-Transfer-Encoding: 7bit
  S:
  S: BEGIN:VCALENDAR
  S: VERSION:2.1
  S: METHOD:RESPONSE
  S: CMDID:xyz12345
  S: TARGET:cap://bobo.ex.com/relcal3
  S: BEGIN:VEVENT
  S: DTSTART:19990310T130000Z
  S: DTEND:19990310T133000Z

  S: UID:abcxyz8999
  S: SUMMARY:Meet with brave brave Sir Robin
  S: BEGIN:VALARM
  S: TRIGGER:19990310T132500Z
  S: SUMMARY:Almost time..
  S: ACTION:DISPLAY
  S: END:VALARM
  S: END:VEVENT
  S: END:VCALENDAR
  S: .
  S: 2.0 cap://bobo.ex.com/relcal2
  S: Content-type:text/calendar; Method=RESPONSE;
  S: Optinfo=VERSION:2.1
  S: Content-Transfer-Encoding: 7bit
  S:
  S: BEGIN:VCALENDAR
  S: VERSION:2.1
  S: METHOD:RESPONSE
  S: CMDID:xyz12345
  S: TARGET:cap://bobo.ex.com/relcal2
  S: BEGIN:VEVENT
  S: REQUEST-STATUS:2.0
  S: END:VEVENT
  S: END:VCALENDAR
  S: .


Component=VQUERY
  C:
  C: BEGIN:VCALENDAR
  C: VERSION:2.1
  C: METHOD:READ
  C: CMDID:xyz12345
  C: TARGET:relcal2
  C: BEGIN:VQUERY
  C: QUERY:SELECT * WHERE FROM VEVENT METHOD != 'CREATE'
  C: END:VQUERY
  C: END:VCALENDAR
  C: .

METHOD = 'CREATE'
  END:VQUERY
  END:VCALENDAR

  We assume that the event is not already in their relcal2
Component=VQUERY
  C:
  C: BEGIN:VCALENDAR
  C: VERSION:2.1
  C: METHOD:READ
  C: CMDID:xyz12345


  C: TARGET:cap://cal.example.com/opaqueid99
  C: BEGIN:VQUERY
  C: QUERY:SELECT DTSTART,DTEND,SUMMARY, UID FROM VEVENT
    WHERE DTEND >= '19990714T080000Z'
    AND DTSTART <= '19990715T080000Z'
  C: END:VQUERY
  C: END:VCALENDAR
  C: .
  # this response code means that the transport successfully
  # delivered the data.
  S: 2.0 ; got the request OK ; really
  S: .
  S: Content-type:text/calendar; Method=RESPONSE;
Optinfo=VERSION:2.1
  S: Content-Transfer-Encoding: 7bit
  S:
  S: BEGIN:VCALENDAR
  S: VERSION:2.1
  S: METHOD:RESPONSE
  S: TARGET:cap://cal.example.com/opaqueid99
  S: CMDID:xyz12345
  S: RESPONSE-STATUS:2.0
  S: BEGIN:VEVENT
  S: DTSTART:19990714T200000Z
  S: DTEND:19990714T210000Z
  S: UID:000444888929922
  S: SUMMARY:Blah bla
  S: END:VEVENT
  S: BEGIN:VEVENT
  S: UID:0034848098038888989443
  S: SUMMARY:meeting
  S: DTEND:19990714T233000Z
  S: DTSTART:19990714T223000Z
  S: END:VEVENT
  S: END:VCALENDAR
  S: .


Component=VQUERY
  C:
  C: BEGIN:VCALENDAR
  C: VERSION:2.1
  C: METHOD:READ
  C: CMDID:xyz12346
  C: TARGET:cap://cal.example.com/opaqueid101
  C: TARGET:opaqueid103
  C: BEGIN:VQUERY
  C: VSCOPE:VEVENT


  C: QUERY:SELECT DTSTART,DTEND,SUMMARY,UID FROM VEVENT
  C: WHERE DTEND >= 19990714T080000Z AND DTSTART <=
Component=VQUERY


  C:
  C: BEGIN:VCALENDAR
  C: VERSION:2.1
  C: METHOD:READ
  C: CMDID:xyz12346
  C: TARGET:cap://cal.example.com/opaqueid101
  C: TARGET:opaqueid103
  C: BEGIN:VQUERY
  C: QUERY:SELECT DTSTART,DTEND,SUMMARY,UID FROM VEVENT
    WHERE DTEND >= '19990714T080000Z' AND DTSTART <=
transp   = "TRANSP" tranparam ":" transvalue CRLF

tranparam   = *(";" xparam)

transvalue   = "OPAQUE" ;Blocks or opaque on busy time
carrights    = [princ] (carref / cardef) CRLF

princ      = "UPN" "=" (text / all / "OWNER" / "NONOWNER"
carref      = ";" "CARREF" "=" text *("," text)

cardef      = action object *("," action object)

action      = ";" "ACTION" "=" act-type *("," act-type)

act-type     = ("CREATE" / "MODIFY" / "DELETE" / "READ" /
object      = ";" "OBJECT" "=" (csprop *("," csprop)
csprop     = csprop2 / all / iana-name

csprop2     = <any calendar store property defined in
propvalue    = propvalue2 / all / self / iana-name

propvalue2   = <any value appropriate for the named
calprop     = calprop2 / all / iana-name

calprop2    = <any calendar property name defined in
component    = component2 / all / iana-name

component2   = <any calendar component defined in [iCAL]
compprop    = compprop2 / all / iana-name

compprop2    = <any component property name defined in
compparam    = compparm2 / all / iana-name

compparm2    = <any component parameter name defined in
compvalue    = ";" "VALUE" "=" ((component2 *(","
paramvalue   = paramvalue2 / all / iana-name

paramvalue2   = <any value appropriate for the named
all       = "*"

self      = "SELF"  ; Only valid for ATTENDEE value.
           ; When OBJECT=ATTENDEE;VALUE=SELF.

iana-name    = <A name registered with IANA>

UPN="foo@host.com";ACTION=READ;OBJECT=DTSTART,DTEND


aclc   =  "BEGIN" ":" "VCAR" CRLF
         carprop
         "END" ":" "VCAR" CRLF

carprop =   carid 1*(grant / deny)

grant      = "GRANT" rightsparam ":" carrights CRLF
rightsparam   = *(";" xparam)


DENY   = "DENY" rightsparam ":" carrights CRLF
rightsparam   = *(";" xparam)

CARID = "CARID" textparam ":" text CRLF

rstatus  = "REQUEST-STATUS" rstatparam ":"
    statcode [";" statdesc [";" extdata]]

rstatparam  = *(
   ; the following is optional,
   ; but MUST NOT occur more than once

     (";" languageparm) /


   ; the following is optional,
   ; and MAY occur more than once

   (";" xparam)

   )

statcode  = 1*DIGIT *("." 1*DIGIT)
   ;Hierarchical, numeric return status code

statdesc  = text
   ;An optional textual status description, content is
   ;decided by the implementor. May be empty.

extdata  = text
   ;Textual exception data. For example, the offending
