start = metalinkMetalink

metalinkCommonAttributes =
      attribute xml:base { metalinkUri }?,
      attribute xml:lang { metalinkLanguageTag }?,
      undefinedAttribute*

metalinkTextConstruct =
      metalinkCommonAttributes,
      text

metalinkDateConstruct =
      metalinkCommonAttributes,
      xsd:dateTime

metalinkMetalink =
      element metalink:metalink {
         metalinkCommonAttributes,
         (metalinkPublished?
          & metalinkOrigin?
          & metalinkGenerator?
          & metalinkUpdated?
          & extensionElement*),
         metalinkFiles
      }

metalinkFiles =
      element metalink:files {
         metalinkCommonAttributes,
         (metalinkIdentity?
          & metalinkVersion?
          & metalinkDescription?
          & metalinkOS?
          & metalinkLogo?
          & metalinkLanguage?
          & metalinkPublisher?
          & metalinkCopyright?
          & metalinkLicense?
          & extensionElement*)
         metalinkFile
      }

metalinkFile =
      element metalink:file {
         metalinkCommonAttributes,
         attribute name { metalinkTextConstruct },
         (metalinkVerification?
          & metalinkIdentity?
          & metalinkVersion?
          & metalinkDescription?
          & metalinkSize?
          & metalinkOS?
          & metalinkLogo?
          & metalinkLanguage?
          & metalinkPublisher?
          & metalinkCopyright?
          & metalinkLicense?
          & extensionElement*)
         metalinkResources
      }

metalinkResources =
      element metalink:resources {
         metalinkCommonAttributes,
         extensionElement*
         metalinkURL*
      }

metalinkVerification =
      element metalink:verification {
         metalinkCommonAttributes,
        (metalinkHash*
         & metalinkPieces*
         & metalinkSignature
         & extensionElement*)
      }

metalinkPieces =
      element metalink:pieces {
         attribute length { metalinkTextConstruct },
         attribute type { "crc32" | "md4" | "md5" | "sha1" |
         "sha256" | "sha384" | "sha512" |  "rmd160" | "tiger" },
         hash+





      }+,

metalinkCopyright =
      element metalink:copyright {
      metalinkTextConstruct
      }

metalinkDescription =
      element metalink:description {
      metalinkTextConstruct
      }

metalinkGenerator = element metalink:generator {
      metalinkCommonAttributes,
      attribute uri { metalinkUri }?,
      attribute version { text }?,
      text
metalinkHash =
      element metalink:hash {
      attribute piece { xsd:integer }?,
      attribute type { "crc32" | "md4" | "md5" | "sha1" |
          "sha256" | "sha384" | "sha512" |  "rmd160" | "tiger" },
      text
      }

metalinkIdentity =
      element metalink:identity {
      metalinkTextConstruct
      }








metalinkLanguage =
      element metalink:language {
      metalinkTextConstruct
      }

metalinkLicense =
      element metalink:license {
      metalinkCommonAttributes,
      attribute uri { metalinkUri }?,
      attribute name { metalinkTextConstruct }?,
      }

metalinkLogo = element metalink:logo {
      metalinkCommonAttributes,
      (metalinkUri)
metalinkOrigin = element metalink:origin {
      metalinkCommonAttributes,
      (metalinkUri)
metalinkOS =
      element metalink:os {
      metalinkTextConstruct
      }

metalinkPublished =
      element metalink:published {
      metalinkDateConstruct
      }

metalinkPublisher =
      element metalink:publisher {
      metalinkCommonAttributes,
      attribute uri { metalinkUri }?,
      attribute name { metalinkTextConstruct }?,
metalinkSignature =
      element metalink:signature {
      attribute type { "pgp" },
      metalinkTextConstruct
      }

metalinkSize =
      element metalink:size {
      metalinkTextConstruct
      }

metalinkType =
      element metalink:type {
      "static" | "dynamic"
      }







metalinkUpdated =
      element metalink:updated {
      metalinkDateConstruct
      }

metalinkURL =
      element metalink:url {
         metalinkCommonAttributes,
         attribute location { xsd:string {
minLength = "2"  maxLength="2"}
metalinkVersion =
      element metalink:version {
      metalinkTextConstruct
      }


simpleExtensionElement =
      element * - metalink:* {
         text
      }

structuredExtensionElement =
      element * - metalink:* {
         (attribute * { text }+,
            (text|anyElement)*)
       | (attribute * { text }*,
          (text?, anyElement+, (text|anyElement)*))
      }

metalinkCommonAttributes =
         attribute xml:base { metalinkUri }?,
         attribute xml:lang { metalinkLanguageTag }?,
         undefinedAttribute*

metalinkTextConstruct =
         metalinkCommonAttributes,
         text

metalinkDateConstruct =
         metalinkCommonAttributes,
         xsd:dateTime







start =
     element metalink {
       attribute version { "3.0" },
       element generator {
         attribute uri { metalinkUri }?,
         attribute version { text }?,
         metalinkTextConstruct
       }
       element origin { metalinkUri }?,
       element type { "static" | "dynamic"  }?,
       element published { metalinkDateConstruct }?,
       element updated { metalinkDateConstruct }?,
       element files {
         element file {
           attribute name { metalinkTextConstruct },
           element identity { metalinkTextConstruct }?,
           element version { metalinkTextConstruct }?,
           element size { xsd:integer }?,
           element description { metalinkTextConstruct }?,
           element license {
             attribute uri { metalinkUri }?,
             attribute name { metalinkTextConstruct }?,
           }?,
           element logo { metalinkUri }?,
           element publisher {
             attribute uri { metalinkUri }?,
             attribute name { metalinkTextConstruct }?,
           }?,
           element language { metalinkTextConstruct }?,
           element copyright { metalinkTextConstruct }?,
           element license { metalinkTextConstruct }?,
           element os { metalinkTextConstruct }?,
           element verification {
             hash+,
             element pieces {
               attribute length { metalinkTextConstruct },
               attribute type { "crc32" | "md4" | "md5" | "sha1" |
               "sha256" | "sha384" | "sha512" |  "rmd160" | "tiger" },
               hash+
             }+,
             element signature {
              attribute type { "pgp" },
              text
              }
           }?,
           element resources {
             element url {
               attribute location { xsd:string {





minLength = "2"  maxLength="2"}
hash =
     element hash {
       attribute piece { metalinkTextConstruct }?,
       attribute type { "crc32" | "md4" | "md5" | "sha1" |
       "sha256" | "sha384" | "sha512" |  "rmd160" | "tiger" },
       text
     }

metalinkLanguageTag = xsd:string {
pattern = "[A-Za-z]{1,8}(-[A-Za-z0-9]{1,8})*"
metalinkUri = text

simpleExtensionElement =
      element * - metalink:* {
         text
      }

structuredExtensionElement =
      element * - metalink:* {
         (attribute * { text }+,
            (text|anyElement)*)
       | (attribute * { text }*,
          (text?, anyElement+, (text|anyElement)*))
      }

extensionElement =





      simpleExtensionElement | structuredExtensionElement

undefinedAttribute =
     attribute * - (xml:base | xml:lang | local:*) { text }

undefinedContent = (text|anyForeignElement)*

anyElement =
      element * {
         (attribute * { text }
          | text
          | anyElement)*
      }

anyForeignElement =
      element * - metalink:* {
         (attribute * { text }
          | text
          | anyElement)*
