PLSP-ID=X3(Symbolic Path Name=Class A)             PLSP-ID=X3(Symbolic Path Name=Class A)
PLSP-ID=X3                                         PLSP-ID=X3
PLSP-ID=X1(Symbolic Path Name=Class A)       |     |    +--------^---------+           |
PLSP-ID=X1                                    |                  +v-+                   |   |
PLSP-ID=X7(Symbolic Path Name=Class A)          |                                         |   |
PLSP-ID=X7                             <----------------------------------------------------+
PLSP-ID=X1(Symbolic Path Name=Class A)       |          +----^---^---^-----+           |
PLSP-ID=X1                                    |               |  +v-+ |                 |
PLSP-ID=X2(Symbolic Path Name=Class A)         |          +v-+ |       |  +v-+           |
PLSP-ID=X2(Symbolic Path Name=Class A) <----------------------+       |
PLSP-ID=X4(Symbolic Path Name=Class A)
PLSP-ID=X4(Symbolic Path Name=Class A)
PLSP-ID=X7(Symbolic Path Name=Class A)       |          +----^---^---^-----+           |
PLSP-ID=X7                                    |               |  +v-+ |                 |
PLSP-ID=X2(Symbolic Path Name=Class A)         |          +v-+ |       |  +v-+           |
PLSP-ID=X2(Symbolic Path Name=Class A) <----------------------+       |
PLSP-ID=X4(Symbolic Path Name=Class A)
PLSP-ID=X4(Symbolic Path Name=Class A)
PLSP-ID=X7(Symbolic Path Name=Class A)
PLSP-ID=X7                                 |
PLSP-ID=X1(Symbolic Path Name=Class A)        |          +------------------+           |   |
PLSP-ID=X1                                    |                  +--+                   |
