T = SET
T = SET
T = DEL
           |
           +- T = Path-data
                |
                + -- flags
                + -- IDCount
                + -- IDs
                |
                +- T = Path-data
                   |
                   + -- flags
                   + -- IDCount
                   + -- IDs
                   |
                   +- T = Path-data
                      |
                      + -- flags
                      + -- IDCount
                      + -- IDs
                      + -- T = KEYINFO-TLV
                      |    + -- KEY_ID
                      |    + -- KEY_DATA
                      +- T = Path-data
                           |
                           + -- flags
                           + -- IDCount
                           + -- IDs


                    Figure 21: Sample operation layout

Type = "REPORT" - this type of operation is for FE to
Type = "SET" - this operation is to set LFB components

Type = "SET-PROP" - this operation is to set LFB component
Type = "DEL" - this operation to delete some LFB
Type = "COMMIT" - this operation is sent to the FE to
Type = "TRCOMP" - this operation is sent to the FE to mark
Type = "SET-RESPONSE" - this operation is for the response
Type = "SET-PROP-RESPONSE" - this operation is for the
Type = "DEL-RESPONSE" - this operation is for the response
Type = "COMMIT-RESPONSE" - this operation is sent to the
Type = "GET" - this operation is to request to get LFB
Type = "GET-PROP" - this operation is to request to get
Type = "GET-RESPONSE" - this operation is to response to
Type = "GET-PROP-RESPONSE" - this operation is to response
MessageType = 'EventNotification'.  The ACK flag in the header
Type = "REPORT" - this type of operation is for FE to
provides="FEPO">
ComponentID = 10 (i.e index 10 from z[]), lengthof(all below)
               ComponentIDof(a), lengthof(a), valueof(a)
               ComponentIDof(b), lengthof(b), valueof(b)
ComponentID = 15 (index 15 from z[]), lengthof(all below)
               ComponentIDof(a), lengthof(a), valueof(a)
               ComponentIDof(c), lengthof(c), valueof(c)

OPER = GET-TLV
           PATH-DATA-TLV: IDCount = 1, IDs = 1
OPER = GET-RESPONSE-TLV
           PATH-DATA-TLV:
flags=0, IDCount = 1, IDs = 1
OPER = SET-TLV
           PATH-DATA-TLV:
flags = 0,  IDCount = 1, IDs = 2
OPER = SET-RESPONSE-TLV
           PATH-DATA-TLV:
flags = 0,  IDCount = 1, IDs = 2
OPER = GET-TLV
           PATH-DATA-TLV:
IDCount = 1, IDs = 4
OPER = GET-RESPONSE-TLV
           PATH-DATA-TLV:
flags = 0, IDCount = 1, IDs = 4
OPER = SET-TLV
           PATH-DATA-TLV:
flags = 0 , IDCount = 1, IDs=4
flags = 0, IDCount = 1, IDs = 0
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 4
flags = 0, IDCount = 1, IDs = 5
OPER = SET-RESPONSE-TLV
           PATH-DATA-TLV:
flags = 0 , IDCount = 1, IDs=4
flags = 0, IDCount = 1, IDs = 0
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 4
flags = 0, IDCount = 1, IDs = 5
OPER = SET-TLV
           PATH-DATA-TLV:
flags =  0 , IDCount = 1, IDs=4
flags = 0, IDCount = 1, IDs = 0
flags = 0, IDCount = 1, IDs = 2
OPER = SET-TLV
           PATH-DATA-TLV:
flags =  0 , IDCount = 1, IDs=4
flags = 0, IDCount = 1, IDs = 0
flags = 0, IDCount = 1, IDs = 2
OPER = GET-TLV
           PATH-DATA-TLV:
IDCount = 2, IDs=4.0

OPER = GET-RESPONSE-TLV
           PATH-DATA-TLV:
IDCount = 2, IDs=4.0
                    FULLDATA-TLV containing valueof(j1), valueof(j2)

OPER = GET-TLV
           PATH-DATA-TLV:
flags = 0, IDCount = 1, IDs=4
flags = 0, IDCount = 1, IDs = 0
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 4
flags = 0, IDCount = 1, IDs = 5


OPER = GET-RESPONSE-TLV
           PATH-DATA-TLV:
flags = 0, IDCount = 1, IDs=4
flags = 0, IDCount = 1, IDs = 0
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 4
flags = 0, IDCount = 1, IDs = 5
OPER = SET-TLV
           PATH-DATA-TLV:
flags = 0, IDCount = 2, IDs=4.5
OPER = SET-RESPONSE-TLV
           PATH-DATA-TLV:
flags = 0, IDCount = 1, IDs=4.5
OPER = GET-TLV
           PATH-DATA-TLV:
flags = 0, IDCount = 1, IDs=3

OPER = GET-RESPONSE-TLV
           PATH-DATA-TLV
flags = 0, IDCount = 1, IDs=3
OPER = GET-TLV
           PATH-DATA-TLV:
flags = F_SELKEY  IDCount = 1, IDs=6
KEYINFO-TLV = KeyID=1, KEY_DATA=100

OPER = GET-RESPONSE-TLV
           PATH-DATA-TLV:
flags = 0, IDCount = 1, IDs=6.10
OPER = DEL-TLV
           PATH-DATA-TLV:
flags = F_SELKEY  IDCount = 1, IDs=4
OPER = DELETE-RESPONSE-TLV
           PATH-DATA-TLV:
flags = 0  IDCount = 2, IDs=4.15
OPER = GET-TLV
           PATH-DATA-TLV:
flags = 0 IDCount = 1, IDs=5

OPER = GET-RESPONSE-TLV
       PATH-DATA-TLV:
flags = 0  IDCount = 1, IDs=5
              FULLDATA-TLV, Length = XXXX
               index, someidv, TLV: T=FULLDATA-TLV, L = 4+strlen(namev),
V = valueof(v)
V = valueof(v)
V = valueof(v)
V = valueof(v)
OPER = SET-TLV
           Path-TLV:
flags = 0, IDCount = 2,  IDs=4.20
OPER = SET-TLV
           PATH-DATA-TLV:
flags = F_SELKEY, IDCount = 1, IDs=3
KEYINFO-TLV = KeyID=1 KEY_DATA=10
flags = 0  IDCount = 1, IDs=2
OPER = SET-RESPONSE-TLV
           PATH-DATA-TLV
flags = 0 IDCount = 3, IDs=4.20
OPER = SET-RESPONSE-TLV
           PATH-DATA-TLV
flags = 0 IDCount = 2, IDs=3.16
flags = 0  IDCount = 1, IDs = 2
PER = SET-TLV
       PATH-DATA-TLV
flags = 0, IDCount = 1, IDs = 6
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 5
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 7
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 9
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
OPER = SET-RESPONSE-TLV
       PATH-DATA-TLV
flags = 0, IDCount = 1, IDs = 6
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 5
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 7
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
flags = 0, IDCount = 1, IDs = 9
flags = 0, IDCount = 1, IDs = 1
flags = 0, IDCount = 1, IDs = 2
flags = 0, IDCount = 1, IDs = 3
operation = GET-TLV
           PATH-DATA-TLV
flags = 0  IDCount = 5, IDs=7.10.2.4.1

operation = GET-RESPONSE-TLV
           PATH-DATA-TLV
flags = 0  IDCount = 5, IDs=7.10.2.4.1
operation = GET-TLV
           PATH-DATA-TLV
flag = F_SELKEY, IDCount=3, IDS = 7.10.2
IDCount = 1, IDS = 2 //select x2

operation = GET-RESPONSE-TLV
           PATH-DATA-TLV
flag = 0, IDCount=5, IDS = 7.10.2.11
flags = 0  IDCount = 1, IDS = 2
operation = SET-TLV
           PATH-DATA-TLV
flags = 0  IDCount = 2, IDs=6.10
flags = 0, IDCount = 1, IDs=1
V = {111}
flags = 0  IDCount = 2, IDs=2.20
flags = 0, IDCount = 1, IDs=1
V = {222}
flags = 0, IDCount = 3, IDs=2.30.1
V = {333}
operation = SET-RESPONSE-TLV
           PATH-DATA-TLV
flags = 0  IDCount = 2, IDs=6.10
flags = 0, IDCount = 1, IDs=1
flags = 0  IDCount = 2, IDs=2.20
flags = 0, IDCount = 1, IDs=1
flags = 0, IDCount = 3, IDs=2.30.1
operation = SET-TLV
           PATH-DATA-TLV :
flags = 0, IDCount = 3, IDs=6.10.1
V = {111}
flags = 0, IDCount = 5, IDs=6.10.1.20.1
V = {222}
flags = 0, IDCount = 7, IDs=6.10.1.20.1.30.1
V = {333}
operation = SET-TLV
           PATH-DATA-TLV :
flags = 0, IDCount = 3, IDs=6.10.1
flags = 0, IDCount = 5, IDs=6.10.1.20.1
flags = 0, IDCount = 7, IDs=6.10.1.20.1.30.1
operation = GET-TLV
           PATH-DATA-TLV
flags = 0  IDCount = 0

operation = GET-RESPONSE-TLV
           PATH-DATA-TLV
flags = 0  IDCount = 0
