MAC = hex(H(Message||[<time>]||<shared key>))


HMAC = hex(H(K' ^ pad2 || H(K' ^ pad1 ||[<time>]|| Message)))
pad1 = the byte 0x36 repeated enough times to fill out a
                   hash input block. (I.e. 64 times for both MD5 and SHA-1)
pad2 = the byte 0x5c repeated enough times to fill out a
                   hash input block.
recv-optional=pkcs-7,MOSS

recv-required=RSA


orig-required=PKCS-7
orig-required=X.509
orig-optional=Inband,RSA
orig-optional=encrypt
recv-optional=PKCS-7, MOSS
recv-optional=X.509
recv-optional=RSA,Inband
recv-optional=RSA-MD5
recv-optional=DES-CBC
recv-optional=DES-ECB
recv-required=encrypt;
recv-optional=sign, auth


orig-required=pkcs-7; recv-optional=pkcs-7,MOSS


AAAAA==
CRYPTOPTS="Key-Assign: Inband,alice1,reply,des-ecb;020406080a0c0e0f;
AAAAAAAAAAA=
YmV0YQpBY2NlcHQ6ICouKgoKAAA=
