conf-capability-string   = namespace-uri [ parameter-list ]
parameter-list      = "?" parameter *( "&" parameter )
parameter           = package-parameter /
                              revision-parameter /
                              profile-parameter
package-parameter   = "package=" package-name
revision-parameter  = "revision=" revision-date
profile-parameter   = "profile=" profile-name

package=ietf-routing-pkg&revision=2013-09-16&profile=ipv4
package-stmt     = optsep package-keyword sep identifier-arg-str
                         optsep
                         "{" stmtsep
                             module-header-stmts
                             meta-stmts
                             revision-stmts
                             package-classify-stmts
                             package-body-stmts
                         "}" optsep

package-classify-stmts = [category-stmt]

category-stmt = category-keyword sep identifier-arg-str optsep
                       (";" /
                       "{" stmtsep
                           *(subcategory-stmt stmtsep)
                       "}")

subcategory-stmt = subcategory-keyword sep string stmtend

package-body-stmts  = *(profile-stmt stmtsep)

profile-stmt =    profile-keyword sep identifier-arg-str optsep
                         (";" /
                          "{" stmtsep
                              ;; these stmts can appear in any order
                              [status-stmt stmtsep]
                              [description-stmt stmtsep]
                              [reference-stmt stmtsep]
                              *(include-profile-stmt stmtsep)
                              *(require-package-stmt stmtsep)
                              *(require-capability-stmt stmtsep)
                              *(require-module-stmt stmtsep)
                          "}")

include-profile-stmt = include-profile-keyword sep
                              identifier-arg-str stmtend

require-module-stmt = require-module-keyword sep
                         identifier-arg-str optsep
                         (";" /
                          "{" stmtsep
                              ;; these stmts can appear in any order
                              [min-revision-stmt stmtsep]
                              [max-revision-stmt stmtsep]
                              [require-conformance-stmt stmtsep]
                              [description-stmt stmtsep]
                              [reference-stmt stmtsep]
                              *(require-feature-stmt stmtsep)
                              *(require-object-stmt stmtsep)
                          "}")

require-object-stmt = require-object-keyword sep
                         require-object-arg-str optsep
                         (";" /
                          "{" stmtsep
                              ;; these stmts can appear in any order
                              [description-stmt stmtsep]
                              [reference-stmt stmtsep]
                          "}")

require-object-arg-str = < a string that matches the rule
                                 require-object-arg >

require-object-arg   = pkg-absolute-schema-nodeid

require-package-stmt = require-package-keyword sep
                         identifier-arg-str optsep
                         (";" /
                          "{" stmtsep
                              ;; these stmts can appear in any order
                              [min-revision-stmt stmtsep]
                              [max-revision-stmt stmtsep]
                              [require-profile-stmt stmtsep]
                              [description-stmt stmtsep]
                              [reference-stmt stmtsep]
                          "}")

require-profile-stmt = require-profile-keyword sep
                         identifier-arg-str stmtend

require-capability-stmt = require-capability-keyword sep
                         uri-str optsep
                         (";" /
                          "{" stmtsep
                              ;; these stmts can appear in any order
                              [description-stmt stmtsep]
                              [reference-stmt stmtsep]
                          "}")

min-revision-stmt = min-revision-keyword sep date-arg-str stmtend
max-revision-stmt = max-revision-keyword sep date-arg-str stmtend

require-feature-stmt = require-feature-keyword sep
                         identifier-arg-str optsep
                         (";" /
                          "{" stmtsep
                              ;; these stmts can appear in any order
                              [description-stmt stmtsep]
                              [reference-stmt stmtsep]
                          "}")

require-conformance-stmt = require-conformance-keyword sep
                          require-conformance-arg-str stmtend

require-conformance-arg-str =
                            < a string that matches the rule
                             require-conformance-arg >

require-conformance-arg = full-keyword /
                                 augment-keyword /
                                 import-keyword /
                                 ad-hoc-keyword

pkg-schema-nodeid   = pkg-absolute-schema-nodeid /
                             pkg-descendant-schema-nodeid

pkg-absolute-schema-nodeid = 1*("/" pkg-node-identifier)

pkg-descendant-schema-nodeid =
                             pkg-node-identifier
                             pkg-absolute-schema-nodeid

pkg-node-identifier = identifier

ad-hoc-keyword              = 'ad-hoc'
augment-keyword             = 'augment'
category-keyword            = 'category'
conformance-keyword         = 'conformance'
full-keyword                = 'full'
include-profile-keyword     = 'include-profile'
max-revision-keyword        = 'max-revision'
min-revision-keyword        = 'min-revision'
package-keyword             = 'package'
profile-keyword             = 'profile'
require-capability-keyword  = 'require-capability'
require-module-keyword      = 'require-module'
require-feature-keyword     = 'require-feature'
require-package-keyword     = 'require-package'
require-profile-keyword     = 'require-profile'
subcategory-keyword         = 'subcategory'

