template-type=naming-directory:nisplus

template-version=0.0

template-description=
  This is a concrete type; the abstract type for this service
  is naming-directory (described in [4]). This type is used by
  NIS+ servers to advertise their services and NIS+ clients
  which wish to discover NIS+ servers.

template-url-syntax=
url-path      = "nisplus://" addr "/" directory
addr          = ipv4-addr
directory     = string "."  / string "." directory
ipv4-addr     = 1*3DIGIT 3( "." 1*3DIGIT )
string        = ISO Latin 1 character set except the
                  character '/' (slash). The initial character
                  may not be a terminal character or the
                  characters '@' (at), '+' (plus), or (`-')
                  hyphen

security= string M
  # security mechanisms supported by this server
key= string M
  # the stringified public key(s) and other keying material for
  # this server.

