xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">
  
type="token"/>
type="maint:listDataType"/>
type="maint:maintDataType"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>       
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>       
minOccurs="0"/>
minOccurs="0"/>       
minOccurs="0"/>
minOccurs="0"/>       
minOccurs="0"/> 
maxOccurs="unbounded"/>
use="required"/>
use="optional"/>        
maxOccurs="unbounded"/>
