connection_referral = "*" SPACE "BYE" SPACE
      <referral_response_code> (text / text_mime2)

login_auth_mailbox_referral = "*" SPACE "NO" SPACE
      <referral_response_code> (text / text_mime2)

referral_response_code = "[" "REFERRAL" SPACE <url> "]"

text = 1*text_char

text_char = <any CHAR except CR and LF>

text_mime2 = "=?" <charset> "?" <encoding> "?" <encoded-text? "?="
      ; <charset>, <encoding>, <encoded-text> syntax as
      ; defined in [RFC-2047]

url = <any url as defined in [rfc-1738]>


