CApub = g^x mod p   (where g and p are the established DH
                            parameters and x is the CA's private
                            DH component)
Epub = DH public value = g^y mod p


K = SHA1(DER-encoded-subjectName | Kec | DER-encoded-issuerName)

