template-type=service:printer:raw-tcp:

template-version=0.0

template-description=
     The printer:raw-tcp: URL describes a transparent bidirectional
     communication channel for printing. Print data, status, messages,
     etc is written or read by opening a TCP connection to the port in 
     the service URL. How data is formatted and sent across the
     connection is decided by the printing client and the print service
     and is not defined in this document.

template-url-syntax=
url-path     = ;

concrete-protocols = STRING L M
abstract-protocol = STRING L O
device-id= STRING L O
