xmlns="urn:ietf:params:xml:ns:iodef-1.0"
targetNamespace="iodef-sci.xsd"
namespace="urn:ietf:params:xml:ns:iodef-1.0"
schemaLocation="urn:ietf:params:xml:schema:iodef-1.0"/>

  <xsd:element name="Scoring">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Score" type="xsd:string"/>
      </xsd:sequence>
      <xsd:attribute name="Version" type="xsd:string" use="required" default="1.00"/>
      <xsd:attribute name="SpecificationID" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="AttackPattern">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Record" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="Reference" type="iodef:Reference" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="PlatformID" type="iodef-sci:PlatformID" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="Version" type="xsd:string" use="required" default="1.00"/>
      <xsd:attribute name="SpecificationID" type="xsd:string" use="required"/>
      <xsd:attribute name="AttackPatternID" type="xsd:string" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Vulnerability">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Record" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="Reference" type="iodef:Reference" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="PlatformID" type="iodef-sci:PlatformID" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="Scoring" type="iodef-sci:Scoring" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="Version" type="xsd:string" use="required" default="1.00"/>
      <xsd:attribute name="SpecificationID" type="xsd:string" use="required"/>
      <xsd:attribute name="VulnerabilityID" type="xsd:string" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Weakness">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Record" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="Reference" type="iodef:Reference" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="PlatformID" type="iodef-sci:PlatformID" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="Scoring" type="iodef-sci:Scoring" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="Version" type="xsd:string" use="required" default="1.00"/>
      <xsd:attribute name="SpecificationID" type="xsd:string" use="required"/>
      <xsd:attribute name="WeaknessID" type="xsd:string" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="PlatformID">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="ID" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="Version" type="xsd:string" use="required" default="1.00"/>
      <xsd:attribute name="SpecificationID" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="EventReport">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:choice>
          <xsd:element name="Record" type="xsd:string"/>
          <xsd:element name="Reference" type="iodef:Reference"/>
        </xsd:choice>
      </xsd:sequence>
      <xsd:attribute name="Version" type="xsd:string" use="required" default="1.00"/>
      <xsd:attribute name="SpecificationID" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Remediation">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:choice>
          <xsd:element name="Record" type="xsd:string"/>
          <xsd:element name="Reference" type="iodef:Reference"/>
        </xsd:choice>
      </xsd:sequence>
      <xsd:attribute name="Version" type="xsd:string" use="required" default="1.00"/>
      <xsd:attribute name="SpecificationID" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

