elementFormDefault="qualified" attributeFormDefault="unqualified">

schemaLocation="iodef_schema.xsd"/>

schemaLocation="urn:ietf:params:xml:schema:iodef-1.0"/>
maxOccurs="unbounded"/>
use="required" fixed="xml"/>
minOccurs="0" maxOccurs="unbounded"/>
use="optional"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
use="optional"/>
use="optional"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
use="optional"/>
use="optional"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
use="optional"/>
use="optional"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
use="optional"/>
use="optional"/>
use="optional"/>
use="optional"/>
use="optional"/>
use="optional"/>
use="optional"/>
use="optional"/>
xmlns="urn:ietf:params:xml:ns:iodef-1.0"
AttackPatternID="CAPEC-14">
          <iodef-sci:RawData>
            <Attack_Pattern_Catalog Catalog_Name="CAPEC"
Catalog_Version="1.6" Catalog_Date="2010-12-09"
VulnerabilityID="CVE-2010-3654">
          <iodef-sci:RawData>
            <cve xsi:noNamespaceSchemaLocation=
               "http://cve.mitre.org/schema/cve/cve_1.0.xsd"
xmlns="http://cve.mitre.org/cve/downloads"
PlatformID="[CPE ID]"/>
WeaknessID="CWE-119">
          <iodef-sci:RawData>
            <Weakness_Catalog
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Catalog_Name="VIEW LIST: CWE-1000: Research Concepts"
Catalog_Version="2.1" Catalog_Date="2011-09-13"
PlatformID="[CPE ID]"/>
xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5"
