positive-digit  = "1" / "2" / "3" /
                            "4" / "5" / "6" /
                            "7" / "8" / "9"

digit           = "0" / positive-digit

non-zero-int    = positive-digit *9digit

part            = "0" / non-zero-int ; max value is 4294967295

large-community = part ":" part ":" part

