xmlns="urn:ietf:params:xml:ns:floor-info" 
elementFormDefault="qualified"> 
     
      <!-- root element --> 
      <xs:element name="floors-info"> 
         <xs:complexType> 
            <xs:sequence> 
                 <xs:element name="floor-info" type="floorType"/> 
            </xs:sequence> 
                 <xs:attribute name="conf-uri" type="xs:anyURI"/> 
         </xs:complexType> 
      </xs:element> 
      <xs:complexType name="floorType"> 
         <xs:sequence> 
            <xs:element name="resources" type="xs:string"/> 
                 <xs:element name="chairs" type="chairsType" 
minOccurs="0"/> 
                 <xs:element name="state" type="stateInfoType" 
minOccurs="1"/> 
                 <xs:any namespace="##other" processContents="lax" 
minOccurs="0" maxOccurs="unbounded"/> 
         </xs:sequence> 
         <xs:attribute name="floor-id" type="xs:int"/> 
      </xs:complexType> 
     
      <!-- chair of the floor --> 
      <xs:complexType name="chairsType"> 
         <xs:sequence> 
            <xs:element name="chair" type="chairType" 
maxOccurs="unbounded"/> 
         </xs:sequence> 
      </xs:complexType> 
       
      <xs:complexType name="chairType"> 
         <xs:attribute name="uri" type="xs:anyURI"/> 
      </xs:complexType> 
     
      <!-- state if the floor --> 
      <xs:complexType name="stateInfoType"> 
         <xs:sequence> 
   
            <xs:element name="floorstate" type="floorstateType" 
maxOccurs="unbounded"/> 
         </xs:sequence> 
      </xs:complexType> 
     
      <xs:complexType name="floorstateType"> 
         <xs:sequence> 
            <xs:element name="users" type="userType"/> 
            <xs:element name="floor-action" type="actionType"/> 
            <xs:element name="action-time" type="xs:dateTime" 
minOccurs="0" /> 
            <xs:element name="expiration" type="xs:dateTime" 
minOccurs="0" /> 
         </xs:sequence> 
         <xs:attribute name="transaction-id" type="xs:int" 
use="required"/> 
      </xs:complexType> 
          
      <xs:simpleType name="actionType"> 
         <xs:restriction base="xs:string"> 
            <xs:enumeration value="requsted"/> 
            <xs:enumeration value="accepted"/> 
            <xs:enumeration value="granted"/> 
            <xs:enumeration value="released"/> 
            <xs:enumeration value="withdrawed"/> 
         </xs:restriction> 
      </xs:simpleType> 
      
      <!-- user of the floor --> 
      <xs:complexType name="userType"> 
         <xs:attribute name="uri" type="xs:anyURI"/> 
      </xs:complexType> 
     
