type="md:RADIUSIDPDescriptorType"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
type="md:RADIUSRPDescriptorType"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
entityID="https://IdentityProvider.com/SAML">
entityID="https://RelyingParty.com/SAML">
