over_time = (CurrentTime - TS.SndMax_time) - TS2_PASADF_MAXADV;
Measured_RTT = ((GetIntTS1() + TS.SndOff)
                                        - RSEG.TSecr + TS1_GRANULARITY);
Measured_RTT = ((GetIntTS2() + TS.SndOff)
                                        - RSEG.TSecr + TS2_GRANULARITY);
idle_time = GetTime() - TS.RcvMin_time;
idle_time = GetTime() - TS.RcvMin_time;
mean_ts = (TS.RcvMin + time2ts(idle_time));
Measured_RTT = ((GetIntTS1() + TS.SndOff)
                                        - RSEG.TSecr + TS1_GRANULARITY);
Measured_RTT = ((GetIntTS2() + TS.SndOff)
                                        - RSEG.TSecr + TS2_GRANULARITY);
b_ts = TS2_SLID_BTS(DS.TgtTS, DS.PrbTS);
b_ts = TS2_SLID_BTS(SH.TgtTS, SH.PrbTS);
b_ts = TS2_SLID_BTS(TS.UNA.TgtTS, TS.UNA.PrbTS);
b_ts = TS2_SLID_BTS(TS.NXT.TgtTS, TS.NXT.PrbTS);
b_ts = TS2_SLID_BTS(TS.MAX.TgtTS, TS.MAX.PrbTS);
over_time = ((GetTime() - TS.SndMax_time)
                             - TS2_PASADF_MAXADV);
Measured_RTT = GetTS() - RSEG.TSecr + TS_GRANULARITY;
option-length=2) is to negotiate the enabling of a feature, it could
