OU=Clepsydre Demonstration Service/CN=Time Stamping Authority
       SerialNumber: 01780a1eca8823
       MessageDigest:
         Algorithm: sha1
         Data     : 75B685AF6F89467DE80715251E45978FCD1FA566
       Asserted Time:
         Generalized Time: 17-Apr-2000 19:16:17 (Apr 17 17:16:17 2000 GMT)
OU=Clepsydre Demonstration Service, CN=Time Stamping Authority
           Validity
               Not Before: Jan 25 16:19:38 2000 GMT
               Not After : Jan 20 16:19:38 2020 GMT
           Subject: C=FR, O=EdelWeb S.A.,
OU=Clepsydre Demonstration Service, CN=Time Stamping Authority
           Subject Public Key Info:
               Public Key Algorithm: rsaEncryption
               RSA Public Key: (2048 bit)
                   Modulus (2048 bit):
                       00:fa:c3:17:ae:eb:b7:9d:eb:ab:bd:05:7e:39:43:
                       6d:04:45:58:74:05:a5:cc:f3:6c:2f:8c:8e:77:7e:
                       c2:9f:12:11:5c:7d:db:be:23:28:9a:90:d2:ab:c6:
                       a2:ba:bd:a3:7e:99:a6:99:21:a5:d8:90:b9:cf:a7:
                       23:4e:a0:56:a0:c1:0a:46:89:8e:3c:91:67:37:fd:
                       9b:ab:49:17:fc:4a:a5:f2:e4:4c:6e:e3:6a:1c:92:
                       97:04:6f:7f:0c:5c:fb:74:cb:95:7e:4c:c3:58:12:
                       e8:a9:d6:f0:dd:12:44:15:e7:8b:2e:af:51:c0:0c:
                       5f:a8:65:fc:47:a1:c9:98:1f:d4:e1:ea:bc:1c:1a:
                       27:bb:8b:56:f1:12:55:10:f4:8e:d8:9f:19:9c:1e:
                       81:f7:db:63:dd:88:37:3f:71:79:5b:96:e2:5f:82:
                       d5:12:19:05:0d:e1:3d:a5:6d:66:e4:2c:1e:ed:c7:
                       4c:b8:df:aa:38:c8:15:6a:ae:25:7d:46:2a:07:f9:
                       83:77:c4:51:ee:90:dc:05:d0:c3:f0:f1:5f:e8:d4:
                       ed:5d:34:70:91:9d:9f:08:55:7d:5b:e5:8d:5f:35:
                       59:83:4e:72:19:bb:9c:88:d1:7a:fc:23:a5:84:99:
                       b4:17:8a:4d:6c:9d:d0:a6:35:80:5f:ca:fb:24:8b:
                       54:1d
