OAR======NAR              OAR     NAR
                              |                        |
                              |                        |
                            MH->                     MH->
OAR=====NAR              OAR     NAR
                        |   |                        |
                        |   |                        |
                          MH->                     MH->
