input_context_handle = 0
targ_name            = output_name from GSS_Import_Name
                            (called with SERVICE:dns@servername)
input_token          = NULL

replay_det_req_flag  = TRUE (require replay detection)
mutual_req_flag      = TRUE (require mutual authentication)

GSS_Token     = output_token from GSS_Init_sec_context

GSS_Token  = output_token from the last call
                  to GSS_Init_sec_context

Expire        = as appropriate (see [TSIG])
context_handle = output_context_handle from GSS_Init_sec_context
message        = whole outgoing message in wire format
                      including TSIG RR with GSS_Signature
                      field set to zero

context_handle = output_context_handle from GSS_Init_sec_context
per_msg_token  = GSS_Signature extracted from TSIG RR
message        = whole incoming message in wire format
                      including TSIG RR with GSS_Signature
                      field set to zero

input_context_handle = 0
input_token          = GSS_Token extracted from TSIG RR

GSS_Token     = output_token from GSS_Accept_sec_context

GSS_Token  = output_token from the last call
                  to GSS_Accept_sec_context

context_handle = output_context_handle associated with current
                      Context ID
per_msg_token  = GSS_Signature extracted from TSIG RR
message        = whole incoming message in wire format
                      including TSIG RR with GSS_Signature
                      field set to zero

Expire        = as appropriate (see [TSIG])
context_handle = output_context_handle associated with
                      Context ID from client
message        = whole outgoing message in wire format
                      including TSIG RR with GSS_Signature
                      field set to zero

