type="xs:anyURI"
use="required"/>
type="xs:positiveInteger"
use="required"/>
type="xs:unsignedLong"
use="optional"/>
type="xs:unsignedLong"
use="optional"/>
type="xs:string"
use="optional"/>
type="xs:string"
use="optional"/>
type="xs:base64Binary"
use="optional"/>
type="xs:unsignedLong"
use="optional"/>
type="xs:unsignedLong"
use="optional"/>
type="xs:unsignedLong"
use="optional"/>
type="xs:unsignedLong"
use="optional"/>
type="xs:unsignedLong"
use="optional"/>
type="xs:string"
use="required"/>
type="xs:boolean"
use="optional"/>
type="xs:string"
use="optional"/>
type="xs:string"
use="optional"/>
type="xs:unsignedLong"
use="optional"/>
type="xs:unsignedLong"
use="optional"/>
type="xs:unsignedLong"
use="optional"/>
type="xs:unsignedLong"
use="optional"/>
type="xs:unsignedLong"
use="optional"/>
Expires="2890842807">
      	<File
Content-Location="http://www.example.com/menu/tracklist.html"
TOI="1"
Content-Type="text/html"/>
Content-Location="http://www.example.com/tracks/track1.mp3"
TOI="2"
Content-Length="6100"
Content-Type="audio/mp3"
Content-Encoding="gzip"
Content-MD5="+VP5IrWploFkZWc11iLDdA=="
Some-Private-Extension-Tag="abc123"/>
