V = Version

P = Padding bit

X = Extension bit

M = Marker bit

RTP-UDP-IP-CO          =    packet-crc-co3(90.8%) |
                               packet-crc-co7(9.2%)
RTP-UDP-IP-DYN         =    INFERRED-IP-CHECKSUM(IPv4-header-dyn)
                               UDP-header-dyn
                               RTP-header-dyn
                               packet-crc-dyn

RTP-UDP-IP-IR          =    INFERRED-IP-CHECKSUM(IPv4-header-ir)
                               UDP-header-ir
                               RTP-header-ir
                               packet-crc-dyn

packet-crc-co3         =    INFERRED-IP-CHECKSUM(IPv4-header-co3)
                               UDP-header-co
                               RTP-header-co-sta
                               RTP-header-co3
                               CRC(3,100%)

packet-crc-co7         =    INFERRED-IP-CHECKSUM(IPv4-header-co7)
                               UDP-header-co
                               RTP-header-co-sta
                               RTP-header-co7
                               CRC(7,100%)

packet-crc-dyn         =    CRC(8,100%)


IPv4-header-co3        =    version
                               header-len
                               tos-co3
                               length
                               ip-id-nbo
                               ip-id
                               nbo-flag-co
                               rf-flag
                               df-flag-co
                               mf-flag
                               offset
                               ttl-co3
                               protocol
                               ip-chksum
                               src-address-co
                               dst-address-co

IPv4-header-co7        =    version
                               header-len
                               tos-co7
                               length
                               ip-id-nbo
                               ip-id
                               nbo-flag-co
                               rf-flag
                               df-flag-co
                               mf-flag
                               offset
                               ttl-co7
                               protocol
                               ip-chksum
                               src-address-co
                               dst-address-co

IPv4-header-dyn        =    version
                               header-len
                               tos-dyn
                               length
                               ip-id-nbo
                               ip-id
                               nbo-flag-dyn
                               rf-flag
                               df-flag-dyn
                               mf-flag
                               offset
                               ttl-dyn
                               protocol
                               ip-chksum
                               src-address-co
                               dst-address-co

IPv4-header-ir         =    version
                               header-len
                               tos-dyn
                               length
                               ip-id-nbo
                               ip-id
                               nbo-flag-dyn
                               rf-flag
                               df-flag-dyn
                               mf-flag
                               offset
                               ttl-dyn
                               protocol
                               ip-chksum
                               src-address-ir
                               dst-address-ir

version                =    VALUE(4,4,100%)
header-len             =    VALUE(4,5,100%)

tos-co3                =    STATIC(100%)

tos-co7                =    STATIC(98.91%) | IRREGULAR(8,1.09%)

tos-dyn                =    IRREGULAR(8,100%)

length                 =    INFERRED-SIZE(16,-16)

ip-id-nbo              =    NBO(16)

ip-id                  =    STACK-TO-CONTROL(16)

nbo-flag-co            =    STATIC(100%)

nbo-flag-dyn           =    IRREGULAR(1,100%)

rf-flag                =    VALUE(1,0,100%)

df-flag-co             =    STATIC(100%)

df-flag-dyn            =    IRREGULAR(1,100%)

mf-flag                =    VALUE(1,0,100%)

offset                 =    VALUE(13,0,100%)

ttl-co3                =    STATIC(100%)

ttl-co7                =    STATIC(98.91%) | IRREGULAR(8,1.09%)

ttl-dyn                =    IRREGULAR(8,100%)

protocol               =    VALUE(8,17,100%)

ip-chksum              =    VALUE(16,0,100%)

src-address-co         =    STATIC(100%)

src-address-ir         =    IRREGULAR(32,100%)

dst-address-co         =    STATIC(100%)

dst-address-ir         =    IRREGULAR(32,100%)

UDP-header-co          =    source-port-co
                               dest-port-co
                               udp-size
                               udp-checksum-co

UDP-header-dyn         =    source-port-co
                               dest-port-co
                               udp-size
                               udp-checksum-ir

UDP-header-ir          =    source-port-ir
                               dest-port-ir
                               udp-size
                               udp-checksum-ir

source-port-co         =    STATIC(100%)

source-port-ir         =    IRREGULAR(16,100%)

dest-port-co           =    STATIC(100%)

dest-port-ir           =    IRREGULAR(16,100%)

udp-size               =    INFERRED-SIZE(16,-32)

udp-checksum-co        =    FORMAT(no-checksum,with-checksum)

                               ; FORMAT index
                               STATIC(100%)


udp-checksum-ir        =    FORMAT(no-checksum,with-checksum)

                               ; FORMAT index
                               IRREGULAR(1,100%)


no-checksum            =    VALUE(16,0,100%)

with-checksum          =    IRREGULAR(16,100%)

RTP-header-co-sta      =    rtp-version
                               rtp-padding-co
                               rtp-extension-co
                               rtp-csrc-count
                               rtp-marker
                               rtp-payload-co
                               rtp-sn
                               ip-id-encoding
RTP-header-co3         =    ip-id-offset-co3
                               rtp-ts-co3
                               rtp-ssrc-co
                               rtp-csrc-co3
                               msn-co3

RTP-header-co7         =    ip-id-offset-co7
                               rtp-ts-co7
                               rtp-ssrc-co
                               rtp-csrc-co7
                               msn-co7

RTP-header-dyn         =    rtp-version
                               rtp-padding-dyn
                               rtp-extension-dyn
                               rtp-csrc-count
                               rtp-marker
                               rtp-payload-dyn
                               rtp-sn
                               ip-id-encoding
                               ip-id-offset-dyn
                               rtp-ts-dyn
                               rtp-ssrc-co
                               rtp-csrc-dyn
                               msn-dyn

RTP-header-ir          =    rtp-version
                               rtp-padding-dyn
                               rtp-extension-dyn
                               rtp-csrc-count
                               rtp-marker
                               rtp-payload-dyn
                               rtp-sn
                               ip-id-encoding
                               ip-id-offset-dyn
                               rtp-ts-dyn
                               rtp-ssrc-ir
                               rtp-csrc-dyn
                               msn-dyn

rtp-version            =    VALUE(2,2,100%)

rtp-padding-co         =    STATIC(100%)

rtp-padding-dyn        =    IRREGULAR(1,100%)

rtp-extension-co       =    STATIC(100%)
rtp-extension-dyn      =    IRREGULAR(1,100%)

rtp-csrc-count         =    STACK-TO-CONTROL(4)

rtp-marker             =    STACK-TO-CONTROL(1)

rtp-payload-co         =    STATIC(100%)

rtp-payload-dyn        =    IRREGULAR(7,100%)

rtp-sn                 =    ; store the SN as the MSN
                               SET-MSN(16)

ip-id-encoding         =    ; expose the IP-ID
                               STACK-ROTATE(3,1)

                               ; retrieve the IP-ID
                               STACK-FROM-CONTROL(16)

                               ; put MSN on control stack
                               STACK-PUSH-MSN(16)

                               ; do the offset encoding
                               INFERRED-OFFSET(16)

                               ; remove the MSN
                               STACK-POP-MSN(16)


rtp-ts-co3             =    ts-stride
                               ts-scale-co
                               ts-offset-co3
                               get-msn
                               ts-scaled
                               move-msn
                               ts-scaled-offset-co3

rtp-ts-co7             =    ts-stride
                               ts-scale-co
                               ts-offset-co7
                               get-msn
                               ts-scaled
                               move-msn
                               ts-scaled-offset-co7

rtp-ts-dyn             =    ts-stride
                               ts-scale-dyn
                               ts-offset-dyn
                               get-msn
                               ts-scaled
                               move-msn
                               ts-scaled-offset-dyn

ip-id-offset-co3       =    FORMAT(non-random-ip-id-co3,random-ip-id)

                               ; FORMAT index
                               STATIC(100%)


ip-id-offset-co7       =    FORMAT(non-random-ip-id-co7,random-ip-id)

                               ; FORMAT index
                               STATIC(100%)


ip-id-offset-dyn       =    FORMAT(non-random-ip-id-dyn,random-ip-id)

                               ; FORMAT index
                               IRREGULAR(1,100%)


non-random-ip-id-co3   =    STATIC(70.71%) | LSB(5,0,29.29%)

non-random-ip-id-co7   =    STATIC(63.1%) | LSB(5,0,26.14%) |
                               LSB(9,0,10.76%)

non-random-ip-id-dyn   =    IRREGULAR(16,100%)

random-ip-id           =    IRREGULAR(16,100%)

ts-stride              =    SCALE(32)

ts-scale-co            =    STATIC(100%)

ts-scale-dyn           =    IRREGULAR(32,100%)

ts-offset-co3          =    STATIC(100%)

ts-offset-co7          =    STATIC(98.92%) | IRREGULAR(32, 1.08%)

ts-offset-dyn          =    IRREGULAR(32,100%)

get-msn                =    STACK-PUSH-MSN(32)

ts-scaled              =    INFERRED-OFFSET(32)
move-msn               =    STACK-POP-MSN(32)

ts-scaled-offset-co3   =    ; get marker bit
                               STACK-FROM-CONTROL(1)

                               no-marker-co3(88.31%) |
                               marker-set-co3(11.69%)


ts-scaled-offset-co7   =    ; get marker bit
                               STACK-FROM-CONTROL(1)

                               no-marker-co7(52.67%) |
                               marker-set-co7(47.33%)


ts-scaled-offset-dyn   =    ; get marker bit
                               STACK-FROM-CONTROL(1)

                               no-marker-dyn(90%) |
                               marker-set-dyn(10%)


no-marker-co3          =    VALUE(1,0,100%)

                               STATIC(100%)


no-marker-co7          =    VALUE(1,0,100%)

                               STATIC(100%)


no-marker-dyn          =    VALUE(1,0,100%)

                               IRREGULAR (32,100%)


marker-set-co3         =    IRREGULAR(1,100%)

                               LSB(6,15,100%)


marker-set-co7         =    IRREGULAR(1,100%)

                               LSB(6,15,14.73%) | LSB(8,63,78.45%) |
                               LSB(12,1023,6.82%)
marker-set-dyn         =    IRREGULAR(1,100%)

                               IRREGULAR(32,100%)


rtp-ssrc-co            =    STATIC (100%)

rtp-ssrc-ir            =    IRREGULAR (32,100%)

rtp-csrc-co3           =    LIST(4,1,32,0,0,
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3),
                               OPTIONAL(csrc-entry-co3)
                               )

                               ; order msbs
                               ;
                               STATIC(100%)

                               ; order lsbs
                               ;
                               STATIC(100%)

                               ; presence
                               ;
                               STATIC(100%)


rtp-csrc-co7           =    LIST(4,1,32,0,0,
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7),
                               OPTIONAL(csrc-entry-co7)
                               )

                               ; order msbs
                               ;
                               STATIC(100%)

                               ; order lsbs
                               ;
                               STATIC(100%)

                               ; presence
                               ;
                               STATIC(89.24%) | IRREGULAR(16,10.76%)


rtp-csrc-dyn           =    LIST(4,1,32,0,0,
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn),
                               OPTIONAL(csrc-entry-dyn)
                               )
                               ; order msbs
                               ;
                               IRREGULAR(32,100%)

                               ; order lsbs
                               ;
                               IRREGULAR(32,100%)

                               ; presence
                               ;
                               IRREGULAR(16,100%)


csrc-entry-co3         =    STATIC(100%)

csrc-entry-co7         =    STATIC(98.91%) | U(IRREGULAR(32,1.09%))

csrc-entry-dyn         =    U(IRREGULAR(32,100%))

msn-co3                =    MSN-LSB(4,-1,91.84%) |
                               MSN-LSB(8,-1,8.16%)

msn-co7                =    MSN-LSB(4,-1,72.07%) |
                               MSN-LSB(8,-1,6.41%) |
                               MSN-LSB(12,-1,21.52%)

msn-dyn                =    MSN-IRREGULAR(16,100%)


