id = 1
algorithm = urn:example:algorithm:psk
name = Our Shared Key Name

id = 1
algorithm = urn:example:algorithm:multistep
init-param-1 = foo

init-param-A = bar

authority = example.org
id = 1
authority = example.org

