informative_response_payload = {
   1 => bstr,  ; phantom request (transport-independent information)
   2 => bstr,  ; latest notification (transport-independent information)
   3 => array  ; transport-specific information
tp_info = [
   tp_id : 1,     ; UDP as transport protocol
   token : bstr,  ; Token of phantom request and multicast notifications
   srv_addr : #6.260(bstr),  ; Src. address of multicast notifications
   srv_port : uint,          ; Src. port of multicast notifications
   cli_addr : #6.260(bstr),  ; Dst. address of multicast notifications
   ? cli_port : uint         ; Dst. port of multicast notifications
C = Critical, U = Unsafe, N = NoCacheKey, R = Repeatable

               Figure 1: Multicast-Response-Feedback-Divider

MAX_CONFIRMATION_WAIT = MAX_RTT + MAX_CLIENT_REQUEST_DELAY

DEFAULT_LEISURE = 5 seconds, thus shortening MAX_CONFIRMATION_WAIT to
C = Critical, U = Unsafe, N = NoCacheKey, R = Repeatable
opt = new Option(MRFD);
opt = new Option(MRFD);
