pat-type="UnAuthReq"
late-type=tic"
pat-type="AuthReq";
AuthHash=Hash(verifier+nonce), #optional for GET
AAD=AuthHash, payload)
AuthHash=Hash(verifier+nonce) is valid or not.  If Tk and AuthHash
pat-type="AuthReq";
cose-type="encrypt0";
cose-type="encrypt0";
