EAP-Type=PEAP
EAP-Type=PEAP
EAP-Type=PEAP
EAP-Type=PEAP
EAP-Type=PEAP
EAP-Type=PEAP ->

		             RADIUS Access-Challenge/
                             <- EAP-Request/
                              Identity
EAP-Type=EAP-GTC

EAP-Type=EAP-GTC
