Config   ==> .         v           .
State   ==> | ................... |
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
      <get-config>
         <source>
           <emphemeral-datastore/>
         </source>
         <filter type="subtree">
           <top xmlns="http://example.com/schema/1.0/thermostat/config">
           <desired-temp>
            </top>
         </filter>
      </get-config>
temp=68                                  temp=65
temp=68   desired-temp                   temp=65
temp = 68
temp=68    temp=68        temp=68       temp=67
temp=68    temp=68        temp=68        temp=68
temp=68    temp=70        temp=68        temp=68
temp=68    temp=70        temp=70       temp=69
temp=68    temp=70        temp=70       temp=70
temp=68    temp=68        temp=70       temp=70
temp=68    temp=68        temp=68        temp=68
temp=70).  In step 10, I2RS Client 1 removes its ephemeral state and
temp=68                                  temp=65
temp=68   desired-temp                   temp=65
temp = 68
temp=68    temp=68        temp=68       temp=67
temp=68    temp=68        temp=68        temp=68
temp=68    temp=70        temp=68        temp=68
temp=68    temp=70        temp=70       temp=69
temp=68    temp=72        temp=70       temp=70
temp=68    temp=72        temp=72       temp=72
temp=68    temp=70        temp=70        temp=70
temp=68    temp=68        temp=68        temp=68
xmlns="urn:ietf:params:xml:ns:base:1.0">
nexthop=
nexthop=    nexthop=
nexthop=    nexthop=      nexthop=        nexthop=
nexthop=    nexthop=      nexthop=        nexthop=
nexthop=    nexthop=      nexthop=        nexthop=
nexthop=    nexthop=      nexthop=        nexthop=
nexthop=    nexthop=      nexthop=        nexthop=
