I=10: Interval Duration - the reported value applies to the
I=11: Cumulative Duration - the reported value applies to the
I=01: Sampled Value - the reported value is a sampled
xr-format =/ xr-bgl-block

xr-bgl-block = "brst-gap-loss"

