next_hop = R2

interface = link(R1-R2)

metric_type = Deterministic Delay

total_metric = 70 us

total_metric_variation = 20 us

next_hop = R2

interface = link(R1-R2)

metric_type = Deterministic Delay

total_metric = 85 us

total_metric_variation = 30 us

next_hop = R2

interface = link(R1-R2)

metric_type = Deterministic Delay

total_metric = 85 us

total_metric_variation = 0

