ICV = (Version | Header Length | protocol | Identification |
              Source Address | Destination Address)
           = (4 | 120 | 51 | 0 | eee.fff.ggg.hhh | aaa.bbb.ccc.ddd)
ICV = (Version | Header Length | protocol | Identification |
              Source Address | Destination Address)
           = (4 | 120 | 51 | 0 | eee.fff.ggg.hhh | aaa.bbb.ccc.ddd)
