id=https%3A%2F%2Fdrinks-unhosted.5apps.com&response_type=token

client_id=https%3A%2F%2Fdrinks-unhosted.5apps.com&redirect_uri=\
charset=UTF-8","Content-Length":106}}}

    If the GET URL would have been a non-existing document like
    "/storage/michiel/myfavoritedrinks/x", the response would have a 404
    Not Found status, and no ETag header:

        HTTP/1.1 404 Not Found
        Access-Control-Allow-Origin: https://drinks-unhosted.5apps.com

