statusInformation =             -- success or errorIndication
    registerContextEngineID(
        contextEngineID         -- take responsibility for this one
        pduType                 -- the pduType(s) to be registered
        )

statusInformation =             -- success or errorIndication
    registerContextEngineID(
        contextEngineID         -- take responsibility for this one
        pduType                 -- the pduType(s) to be registered
        )

statusInformation =             -- success or errorIndication
    isAccessAllowed(
        securityModel           -- Security Model in use
        securityName            -- principal who wants to access
        LoS                     -- Level of Security
        viewType                -- read, write, or notify view
        contextName             -- context containing variableName
        variableName            -- OID for the managed object
        )
