dnsurl          = "dns:" [ "//" hostport "/" ] dnsname ["?" dnsquery]
                                ; See RFC 2396 for "hostport"  definition

dnsname         = *pchar
                                ; See RFC 2396 for "pchar" definition

dnsquery        = dnsqueryelement [";" dnsquery]

dnsqueryelement = ( "CLASS=" dnsclassval ) | ( "TYPE=" dnstypeval ) |
                     ( 1*alphanum "=" 1*alphanum )

dnsclassval     = 1*digit / "IN" / "CH" / ...
                                ; Any standard DNS class expressed as
                                ; mnemonic or as decimal integer

dnstypeval      = 1*digit / "A" / "NS" / "MD" / ...
                                ; Any standard DNS type expressed as
                                ; mnemonic or as decimal integer

