pstndatauri  = "pstndata:" datatype ["/" telephone-   
datatype     = "cnam" 
                          ; Other datatypes can be defined by adding  
                          ; alternative values. 
content      = [ mediatype ] [ ":base64" ] "," data 
mediatype    = [ type "/" subtype ] *( ";" parameter ) 
data         = *urlchar 
parameter    = attribute "=" value  
           
            
                   
pstndatauri  = "pstndata:" datatype ["/" telephone-   
datatype     = "cnam" 
                          ; Other datatypes can be defined by adding             
                          ; alternative values. 
content      = [ mediatype ] [ ":base64" ] "," data 
mediatype    = [ type "/" subtype ] *( ";" parameter ) 
data         = *urlchar 
parameter    = attribute "=" value  
                
