Format=Flowed provides for space-stuffing.
    
paragraph     = 1*flowed-line fixed-line
fixed-line    = fixed / sig-sep
fixed         = [quote] [stuffing] *text-char non-sp CRLF
flowed-line   = flow-qt / flow-unqt
flow-qt       = quote [stuffing] *text-char 1*SP CRLF
flow-unqt     = [stuffing] *text-char 1*SP CRLF
non-empty     = *text-char non-sp
non-sp        = %01-09 / %0B / %0C / %0E-19 / %21-7F
	                   ; any 7-bit US-ASCII character, excluding 
	                     NUL, CR, LF, and SP
quote         = 1*">"
sig-sep       = [quote] "--" SP CRLF
stuffing      = [SP] ; space-stuffed, added on generation if
	                       needed, deleted on reception
text-char     = non-sp / SP
    
    
    
Format=Flowed had not been used.
    
