HASH_i = hash(Initiator's Key Exchange Start Payload |
HASH = hash(Initiator's Key Exchange Start Payload |
K1 = hash(0x2 | KEY | HASH)
K2 = hash(KEY | HASH | K1)
K3 = hash(KEY | HASH | K1 | K2)  ...

K1 = hash(0x3 | KEY | HASH)
K2 = hash(KEY | HASH | K1)
K3 = hash(KEY | HASH | K1 | K2)  ...

auth_hash = hash(HASH | Key Exchange Start Payload);
signature = sign(auth_hash);

