rel=avatar%20\
resource=acct%3Acarol%40example.com HTTP/1.1
q=http%3A%2F%2Fexample.com%2Fxy"
resource=acct%3Aalice%40example.com HTTP/1.1
type="application/xrd+xml"
template="https://example.com/lrdd/?uri={uri}"/>
href="http://www.example.com/~bob/bob.jpg"/>
href="http://www.example.com/~bob/"/>
href="http://blogs.example.com/bob/"/>
