from='http-service.example.org'
to='pubsub.example.org'
id='publish1'>
type='text/html'
href='http://example.org/2003/12/13/atom03'/>
to='alice@example.net'>
type='text/html'
href='http://example.org/2003/12/13/atom03'/>
from='http-service.example.org'
to='pubsub.example.org'
id='publish2'>
type='text/html'
href='http://example.org/2003/12/13/atom03'/>
to='alice@example.net'>
type='text/html'
href='http://example.org/2003/12/13/atom03'/>
from='http-service.example.org'
to='pubsub.example.org'
id='delete1'>
to='alice@example.net'>
to='alice@example.net'>
type='text/html'
href='http://example.org/2003/12/13/atom03'/>
