Payload = Encapsulated UDP Payload

              <--------  STREAM(44): HEADERS
                           :status = 200

Payload = Encapsulated UDP Payload
Payload = Encapsulated UDP Payload

              <--------  STREAM(44): HEADERS
                           :status = 200

Payload = Encapsulated UDP Payload


Payload = Encapsulated UDP Payload With Timestamp

Payload = Encapsulated IP Packet

Payload = Encapsulated IP Packet

Payload = Compressed IP Packet

Origin = https://www.example.org:443

