G=1, R=0) and the node constraint is power (C=1, O=0, A=00, G=0,
R=0).  Note that in this example, the link quality is a global
R=1) containing multiple sub-objects.

E=0x02 the node is powered by a scavenger.

value=4)

value=5)

