uri=ipp://mycompany.com/myprinter?drv-id=ModelY.gz<
os-type=windows-95< cpu-type=x86-32<
document-format=application/postscript<
natural-language=en< compression=gzip<
file-type=printer-driver<
client-file-name=CompanyX-ModelY-driver.gz<
policy=manufacturer-recommended<

uri=ftp://mycompany.com/root/drivers/win95/CompanyX/ModelY.gz<
os-type=windows-95< cpu-type=x86-32<
document-format=application/postscript,application/vnd.hp-PCL<
natural-language=en,fr< compression=gzip<
file-type=printer-driver<
client-file-name=Company T Model Z driver.gz<
policy=manufacturer-recommended<

os-type=windows-95< cpu-type=x86-32<
document-format=application-postscript< natural-language=en,de<

uri-scheme=ipp< os-type=windows-95< cpu-type=x86-32<
document-format=application-postscript< natural-language=en,de<

os-type=windows-95< cpu-type=x86-32<
document-format=application-postscript<
natural-language=en,de<

uri=ipp://mycompany.com/myprinter?drv-id=ModelY.gz<
os-type=windows-95< cpu-type=x86-32<
document-format=application/postscript<
natural-language=en< compression=gzip<
file-type=printer-driver<
client-file-name=CompanyX-ModelY-driver.gz<
policy=manufacturer-recommended<
digital-signature=smime<

uri=ftp://mycompany.com/root/drivers/win95/CompanyX/ModelY.gz<
os-type=windows-95< cpu-type=x86-32<
document-format=application/postscript,application/vnd.hp-PCL<
natural-language=en,fr< compression=gzip<
file-type=printer-driver<
client-file-name=CompanyX-ModelY-driver.gz<
policy=manufacturer-recommended<
digital-signature=smime<


uri-scheme=ipp< os-type=windows-95< cpu-type=x86-32<
document-format=application-postscript<
natural-language=en,de<

uri=ipp://mycompany.com/myprinter?drv-id=ModelY.gz<
os-type=windows-95< cpu-type=x86-32<
document-format=application/postscript<
natural-language=en< compression=gzip<
file-type=printer-driver<
client-file-name=CompanyX-ModelY-driver.gz<
policy=manufacturer-recommended<
digital-signature=smime<

