requested-method-list = 1#method-desc
method-desc = method-name *(";" method-param)
method-name = token
method-param = token ["=" (token | quoted-string)]

method-agreement = method-desc

method="deflate; c2s_max_window_bits;
s2c_max_window_bits=10"

method="deflate; s2c_max_window_bits=10, deflate"

method=deflate

RSV1=1, RSV2=0, RSV3=0, opcode=text, MASK=0, Payload length=7).
RSV1=1, RSV2=0, RSV3=0, opcode=text, MASK=0, Payload length=7).  Note
