owd_mem = max(owd_mem*0.5 + owd*0.5, owd_mem*0.9 + owd*0.1)

owd_fraction = owd/owd_target

owd_target_hi=0.4s.  The OWD fraction is sampled every 50ms and the
a = R(owd_fraction_hist,1)/R(owd_fraction_hist,0)

owd_trend = max(0.0,min(1.0,a*owd_fraction))

owd_trend_ewma=max(owd_trend, owd_trend_ewma*(1.0-alpha)+
alpha = (t_now-t_cwnd_update_prev) / 5000.0

owd_fraction_avg = 0.9* owd_fraction_avg + 0.1* owd_fraction

off_target = (owd_target - owd) / owd_target

cwnd = max(min_cwnd,cwnd*0.8) where min_cwnd = 2*mss

cwnd = cwnd + bytes_newly_acked

gain = gain_up*(1.0 + max(0.0, 1.0 - owd_trend/ 0.2))

t_delta = 0.1*min(200.0, max(20.0, 50.0e6/max_paced_bitrate)
cwnd = min(cwnd, max_bytes_in_flight*max_bytes_in_flight_head_room)

cwnd = max(cwnd, min_cwnd)

owd_target = min(owd_target_hi,
owd_target = 0.5*owd_target+
x_cwnd=1.0+bytes_in_flight_slack*max(0.0,
max_paced_bitrate = max (50000, cwnd* 8 / s_rtt)

t_pace = rtp_size * 8 / max_paced_bitrate

N_a = 1.0/frame_period

age_d = (age_avg(n) - age_avg(n-1))/frame_period

frame_skip_intensity = min(1.0, (age_vec(n)-frame_period)/(2*
target_bitrate = max(0.9* target_bitrate, target_bitrate_min)

target_bitrate_i = target_bitrate * 0.95

target_bitrate_restore_point = target_bitrate

t_last_rate_change = t_now

max_owd_fraction = max(max_owd_fraction, owd_fraction_avg)

alpha = min(0.5, max(0.0, 0.9*age_d))

target_bitrate = max(target_bitrate_min, target_bitrate*(1.0-alpha))
do_restore = max_owd_fraction < 0.4 && owd_trend_ewma < 0.2

target_bitrate = max(target_bitrate, target_bitrate_restore_point)

increment =
target_bitrate = min(target_bitrate_max, target_bitrate+increment))

increment_max = target_bitrate*0.2

gain = max(0.2,min(1.0, abs((target_bitrate - target_bitrate_i)/
ramp_up_time = ramp_up_time_fast+(ramp_up_time_slow-
increment = min(target_bitrate_max*gain*rate_change_interval
target_bitrate = min(target_bitrate_max, target_bitrate +increment)

