alpha-lc      = %x61-7A   ;  a-z
SvcParamKey   = 1*63(alpha-lc / DIGIT / "-")
SvcParam      = SvcParamKey ["=" SvcParamValue]
SvcParamValue = char-string
value         = *OCTET

alpn="bar" port="8004" echconfig="..." )

echconfig="111..." ipv6hint=2001:db8::1 port=1234 )
                                  SVCB 2 svc2.example.net. (
echconfig="222..." ipv6hint=2001:db8::2 port=1234 )
alpn-id = 1*255OCTET

echconfig=... key65333=ex1 key65444=ex2 mandatory=key65444,echconfig
non-special = %x21 / %x23-27 / %x2A-3A / %x3C-5B / %x5D-7E
non-digit   = %x21-2F / %x3A-7E
dec-octet   = ( "0" / "1" ) 2DIGIT /
                 "2" ( ( %x30-34 DIGIT ) / ( "5" %x30-35 ) )
escaped     = "\" ( non-digit / dec-octet )
contiguous  = 1*( non-special / escaped )
quoted      = DQUOTE *( contiguous / ( ["\"] WSP ) ) DQUOTE
char-string = contiguous / quoted

item            = 1*OCTET
item-allowed    = %x00-2B / %x2D-5B / %x5D-FF
escaped-item    = 1*(item-allowed / "\," / "\\")
comma-separated = [escaped-item *("," escaped-item)]

