impreciseeventc     = "BEGIN" ":" "VIMPRECISEEVENT" CRLF
                                impreciseeventprop *freebusyc
                                *availabilityc
                                "END" ":" "VIMPRECISEEVENT" CRLF

impreciseeventprop  = *(

                              ; the following are REQUIRED,
                              ; but MUST NOT occur more than once
                              dtstamp / uid /

                              ; the following are OPTIONAL,
                              ; but MUST NOT occur more than once

                              class / created / description / duration /
                              geo / last-mod / location / organizer /
                              priority / rank / seq / status / summary /
                              transp / url /

                              ; the following is OPTIONAL,
                              ; but SHOULD NOT occur more than once

                              rrule /

                              ; the following are OPTIONAL,
                              ; and MAY occur more than once

                              attach / attendee / categories / comment /
                              contact / rstatus / related / resources /
                              x-prop / iana-prop

                              )

alternativeeventsc     = "BEGIN" ":" "VALTERNATIVEEVENTS" CRLF
                                alternativeeventsprop *eventc
                                *impreciseeventc
                                "END" ":" "VALTERNATIVEEVENTS" CRLF

alternativeeventsprop  = *(

                              ; the following are REQUIRED,
                              ; but MUST NOT occur more than once

                              dtstamp / uid /

                              ; the following are OPTIONAL,
                              ; but MUST NOT occur more than once

                              class / created / description / geo /
                              last-mod / location / organizer /
                              priority / seq / status / summary /
                              transp / url /

                              ; the following are OPTIONAL,
                              ; and MAY occur more than once

                              attach / attendee / categories / comment /
                              contact / rstatus / related / resources /
                              x-prop / iana-prop

                              )

rank       = "RANK" rankparam ":" integer CRLF

rankparam  = *(";" other-param)

rankpparam  = "RANK" "=" integer

