dependency-attribute = "a=dependency:mandatory=" pointers
pointers = pointer *( "," pointer)

pointer = token

token = 1*(token-char)

token-char = %x21 / %x23-27 / %x2A-2B / %x2D-2E / %x30-39

a=dependency:mandatory=1,3;optional=2
v=0

c=IN IP4 1.2.3.4

m=audio 1234 RTP/AVP ...

a=label:1

m=video 2346 RTP/AVP ...

a=label:2

a=dependency:mandatory=1;optional=3

m=message 3456 TCP/MSRP ...

i=subtitles for audio

a=label:3

a=dependency:mandatory=2

