Cache-Status   = sh-list

fwd           = sh-token
fwd-res       = sh-token
fwd-stored    = sh-boolean
res-fresh     = sh-integer
cache-fresh   = sh-integer
collapse-hit  = sh-boolean
collapse-wait = sh-integer
key           = sh-string

collapse-hit=?0; collapse-wait=240

