mac-uri = "mac:" 12*12HEXDIG

ip-uri = "ip:" ipv4 / ipv6
ipv4 = "IPv4+" IPv4-Address
IPv4-Address = 1*3DIGIT "." 1*3DIGIT "." 1*3DIGIT "." 1*3DIGIT
ipv6 = "IPv6+" hexpart [ ":" IPv4-Address ]
hexpart =  hexseq / hexseq "::" [ hexseq ] / "::" [ hexseq ]
hexseq  =  hex4 *( ":" hex4)
hex4    =  1*4HEXDIG
xmlns="urn:ietf:params:xml:ns:geopriv:held" responseTime="8">
targetNamespace="urn:ietf:params:xml:ns:geopriv:held:id"
elementFormDefault="qualified" attributeFormDefault="unqualified">

     <!-- typedURI definition -->

     <xs:complexType name="typedURI">
       <xs:simpleContent>
         <xs:extension base="xs:anyURI">
           <xs:attribute name="type" type="xs:token"
use="optional"/>
use="required"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
type="aor">sip:callee@example.com</uri>

responseTime="8">
responseTime="8">
