entity="pres:someone@example.com">
      <tuple id="joi9877866786ua9">
        <status>
   	  <basic>open</basic>
   	    <ext:prescaps>
   	      <ext:video negated="false"/>
   	      <ext:audio negated="false">
   	        <ext:type>audio/gsm</ext:type>
   	        <ext:type>audio/amr-wb</ext:type>
   	      </ext:audio>
   	      <ext:text negated="true"/>
   	      <ext:mobile>true</ext:mobile>
   	      <ext:methods>
   	        <ext:method>INVITE</ext:method>
   	        <ext:method>MESSAGE</ext:method>
   	        <ext:method>ACK</ext:method>
   	        <ext:method>BYE</ext:method>
   	        <ext:method>CANCEL</ext:method>
   	        <ext:method negated="true">REFER</ext:method>
   	      </ext:methods>
   	      <ext:string name="myString" negated="false">myvalue
   	      </ext:string>
   	    </ext:prescaps>
   	  </status>
   	  <contact>sip:someone@example.com</contact>
        </tuple>
targetNamespace="urn:ietf:params:xml:ns:simple-prescaps-ext"
elementFormDefault="qualified"
attributeFormDefault="unqualified">
schemaLocation="http://www.w3.org/2001/xml.xsd"/>

minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
maxOccurs="4"/>
minOccurs="0"/>
minOccurs="0"
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
default="false"/>
maxOccurs="unbounded"/>
default="false"/>
maxOccurs="unbounded"/>
default="false"/>
maxOccurs="unbounded"/>
default="false"/>
maxOccurs="unbounded"/>
default="false"/>
maxOccurs="unbounded"/>
default="false"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
use="required"/>
default="false"/>
use="required"/>
default="false"/>
use="required"/>
use="required"/>
default="false"/>
content="text/html;charset=iso-8859-1"/>
