B-HIT = sha1(HIT || N), with N a random value and || the 
KI-Auth-key = g(r1, r2, EPC-Code) 
    
f= sha1(r1 || r2 || EPC-Code), where || is the concatenation 
KI-Auth-key = g(r1, r2, EPC-Code) 
    
EPC = 0123456789abcdefcdab 
    
K = HMAC-SHA1(r1 | r2, EPC-Code) 
    
Y = f(r1, r2, EPC-Code) = HMAC-SHA1(K, CT1 | "Type 0001 key") 
    
K = HMAC-SHA1(r1 | r2, EPC-Code) 
    
Y = HMAC-SHA1(K, CT2 | "Type 0001 key") 
    
Y = f(r1, r2, EPC-Code) = H1 | H2 | Hi | Hn 
    
Hi = HMAC-SHA1(r1 | r2, Ki | CT1 ) 
Hi = HMAC-SHA1(r1 | r2, Ki | CT2 ) 
    
    
K = HMAC-SHA1(r1 | r2, EPC-Code) 
    
Y = HMAC-SHA1(K, CT1 | "Type 0002 key") 
    
