CSR      = ( (me->Sender-of-RT), CSR )
Q        = Q + q(me->Sender-of-RT)
RCVF     = (me, RCVF)
SN       = SN[RCVF]++
MinMTU   = Min(my-MTU, MinMTU)
SAN-ID   = (as received in RT)
Local-RT = (as received in RT)

RCVF={ac,ca,cd,dc}
E=3 (0011) indicates that all the data is Little Endian 64-bit. 


