plain-string   = DQUOTE *( %x20-21 / %x23-5B / %x5D-7E ) DQUOTE

headers="request-line host date digest content-length",
signature="Base64(RSA-SHA256(signing string))"

headers="request-line host date digest content-length",
signature="Base64(RSA-SHA256(signing string))"

headers="request-line host date digest content-length",
signature="Base64(HMAC-SHA1(signing string))"

signature="ATp0r26dbMIxOopqw0OfABDT7CKMIoENumuruOtarj8n/97Q3htH
headers="request-line host date", signature="KcLSABBj/m3v2Dhxi
headers="request-line host date content-type digest content-length",
signature="jgSqYK0yKclIHfF9zdApVEbDp5eqj8C4i4X76pE+XHoxugXv7q
