codecs      = "Codecs" *SP "=" *SP value

value       = id / DQUOTE *SP id *(*SP "," *SP id) *SP DQUOTE

id          = cpid [ "." oti ]
     
cpid        = 4 (idchar / idchar-spec)

oti         = "0x" 2HEXDIG

idchar      = <any (US-ASCII) CHAR except SPACE, CTLs,
                  "$", or tspecials>


idchar-spec = "$" 2DIGIT

tspecials   =  "(" / ")" / "<" / ">" / "@" /
                   "," / ";" / ":" / "\" / <">
                   "/" / "[" / "]" / "?" / "="
    
