type="svg"><xi:include href=...")

src="http://www.example.com/...">")

spacing="normal" indicates a single blank line, while
spacing="compact" indicates no space between.

spacing="normal" indicates a single blank line, while
spacing="compact" indicates no space between.

allowed-chars = "." | "," | "&" | "<" | ">" | "|"

allowed-chars = "." | "," | "&amp;" | "&lt;" | "&gt;" | "|"
spacing="normal" indicates a single blank line, while
spacing="compact" indicates no space between.

nrfc =
     element rfc {
       attribute number { text }?,
       [ a:defaultValue = "" ] attribute obsoletes { text }?,
       [ a:defaultValue = "" ] attribute updates { text }?,
       attribute category { "std" | "bcp" | "info" | "exp" | "historic"
nlink =
     element link {
       attribute href { text },
       attribute rel { text }?
     }
nfront =
     element front {
       title,
       author+,
       date?,
       area*,
       workgroup*,
       keyword*,
       abstract?,
       note*,
       boilerplate?
     }
ntitle =
     element title {
       attribute abbrev { text }?,
       attribute ascii { text }?,
       text
     }
nauthor =
     element author {
       attribute initials { text }?,
       attribute asciiInitials { text }?,
       attribute surname { text }?,
       attribute asciiSurname { text }?,
       attribute fullname { text }?,
       attribute role { "editor" }?,
       [ a:defaultValue = "en" ] attribute xml:lang { text }?,
       attribute asciiFullname { text }?,
       organization?,
       address?
     }
norganization =
     element organization {
       attribute abbrev { text }?,
       attribute ascii { text }?,
       text,
       [ a:defaultValue = "en" ] attribute xml:lang { text }?
     }
naddress = element address { postal?, phone?, facsimile?, email?,
npostal =
     element postal {
       [ a:defaultValue = "en" ] attribute xml:lang { text }?,
       ((city | code | country | region | street)* | postalLine+)
     }
nstreet =
     element street {
       attribute ascii { text }?,
       text
     }
ncity =
     element city {
       attribute ascii { text }?,
       text
     }
nregion =
     element region {
       attribute ascii { text }?,
       text
     }
ncode =
     element code {
       attribute ascii { text }?,
       text
     }
ncountry = element country { text }
npostalLine =
     element postalLine {
       attribute ascii { text }?,
       text
     }
nphone = element phone { text }
nfacsimile = element facsimile { text }
nemail =
     element email {
       attribute ascii { text }?,
       text
     }
nuri = element uri { text }
ndate =
     element date {
       attribute day { text }?,
       attribute month { text }?,
       attribute year { text }?,
       empty
     }
narea = element area { text }
nworkgroup = element workgroup { text }
nkeyword = element keyword { text }
nabstract =
     element abstract {
       attribute pn { text }?,
       t+
     }
nnote =
     element note {
       attribute title { text }?,
       name,
       attribute pn { text }?,
       [ a:defaultValue = "no" ] attribute removeInRFC { "yes" | "no"
nboilerplate = element boilerplate { section+ }
nmiddle = element middle { section+ }
nsection =
     element section {
       attribute anchor { xsd:ID }?,
       attribute title { text }?,
       [ a:defaultValue = "yes" ] attribute numbered { "yes" | "no" }?,
       [ a:defaultValue = "default" ]
       attribute toc { "include" | "exclude" | "default" }?,
       [ a:defaultValue = "no" ] attribute removeInRFC { "yes" | "no"
nname =
     element name {
       attribute slugifiedName { text }?,
       (text | cref | eref | tt | xref)*
     }
nt =
     element t {
       attribute anchor { xsd:ID }?,
       attribute hangText { text }?,
       attribute pn { text }?,
       (text
        | b
        | bcp14
        | cref
        | em
        | eref
        | i
        | iref
        | \list
        | ol
        | spanx
        | strong
        | sub
        | sup
        | tt
        | vspace
        | xref)*
     }
naside =
     element aside {
       attribute anchor { xsd:ID }?,
       attribute pn { text }?,
       (artwork | dl | figure | iref | \list | ol | t | table | ul)*
     }
nblockquote =
     element blockquote {
       attribute anchor { xsd:ID }?,
       attribute pn { text }?,
       attribute cite { text }?,
       attribute quotedFrom { text }?,
       (text
        | artwork
        | b
        | bcp14
        | em
        | figure
        | i
        | sourcecode
        | strong
        | sub
        | sup
        | t
        | tt)*
     }
nol =
     element ol {
       [ a:defaultValue = "1" ] attribute style { text }?,
       [ a:defaultValue = "1" ] attribute start { text }?,
       attribute group { text }?,
       [ a:defaultValue = "normal" ]
       attribute spacing { "normal" | "compact" }?,
       li+
     }
nul =
     element ul {
       [ a:defaultValue = "normal" ]
       attribute spacing { "normal" | "compact" }?,
       [ a:defaultValue = "false" ] attribute empty { "false" | "true"
nli =
     element li {
       attribute anchor { xsd:ID }?,
       attribute pn { text }?,
       (t+
        | (text
           | b
           | bcp14
           | cref
           | em
           | eref
           | i
           | iref
           | strong
           | sub
           | sup
           | tt
           | xref)+)
     }
ndl =
     element dl {
       [ a:defaultValue = "normal" ]
       attribute spacing { "normal" | "compact" }?,
       [ a:defaultValue = "true" ] attribute hanging { "false" | "true"
ndt =
     element dt {
       attribute anchor { xsd:ID }?,
       attribute pn { text }?,
       (text
        | b
        | bcp14
        | cref
        | em
        | eref
        | i
        | iref
        | strong
        | sub
        | sup
        | tt
        | xref)*
     }
ndd =
     element dd {
       t+
       | (text
          | b
          | bcp14
          | cref
          | em
          | eref
          | i
          | iref
          | strong
          | sub
          | sup
          | tt
          | xref)+
     }
nxref =
     element xref {
       attribute target { xsd:IDREF },
       [ a:defaultValue = "false" ] attribute pageno { "true" | "false"
neref =
     element eref {
       attribute target { text },
       text
     }
niref =
     element iref {
       attribute item { text },
       [ a:defaultValue = "" ] attribute subitem { text }?,
       [ a:defaultValue = "false" ]
       attribute primary { "true" | "false" }?,
       empty
     }
ncref =
     element cref {
       attribute anchor { xsd:ID }?,
       attribute source { text }?,
       [ a:defaultValue = "true" ] attribute display { "true" | "false"
ntt =
     element tt {
       (text
        | b
        | bcp14
        | cref
        | em
        | eref
        | i
        | iref
        | strong
        | sub
        | sup
        | xref)*
     }
nb =
     element b {
       (text
        | bcp14
        | cref
        | em
        | eref
        | i
        | iref
        | sub
        | sup
        | tt
        | xref)*
     }
nstrong =
     element strong {
       (text
        | bcp14
        | cref
        | em
        | eref
        | i
        | iref
        | sub
        | sup
        | tt
        | xref)*
     }
ni =
     element i {
       (text
        | b
        | bcp14
        | cref
        | eref
        | iref
        | strong
        | sub
        | sup
        | tt
        | xref)*
     }
nem =
     element em {
       (text
        | b
        | bcp14
        | cref
        | eref
        | iref
        | strong
        | sub
        | sup
        | tt
        | xref)*
     }
nsub =
     element sub {
       (text
        | b
        | bcp14
        | cref
        | em
        | eref
        | i
        | iref
        | strong
        | tt
        | xref)*
     }
nsup =
     element sup {
       (text
        | b
        | bcp14
        | cref
        | em
        | eref
        | i
        | iref
        | strong
        | tt
        | xref)*
     }
nspanx =
     element spanx {
       [ a:defaultValue = "preserve" ]
       attribute xml:space { "default" | "preserve" }?,
       [ a:defaultValue = "emph" ] attribute style { text }?,
       text
     }
nvspace =
     element vspace {
       [ a:defaultValue = "0" ] attribute blankLines { text }?,
       empty
     }
nfigure =
     element figure {
       attribute anchor { xsd:ID }?,
       [ a:defaultValue = "" ] attribute title { text }?,
       [ a:defaultValue = "false" ]
       attribute suppress-title { "true" | "false" }?,
       attribute src { text }?,
       [ a:defaultValue = "left" ]
       attribute align { "left" | "center" | "right" }?,
       [ a:defaultValue = "" ] attribute alt { text }?,
       [ a:defaultValue = "" ] attribute width { text }?,
       [ a:defaultValue = "" ] attribute height { text }?,
       attribute pn { text }?,
       name?,
       iref*,
       preamble?,
       (artwork | sourcecode)+,
       postamble?
     }
ntable =
     element table {
       attribute anchor { xsd:ID }?,
       attribute pn { text }?,
       name?,
       iref*,
       thead?,
       tbody+,
       tfoot?
     }
npreamble =
     element preamble {
       (text
        | b
        | bcp14
        | cref
        | em
        | eref
        | i
        | iref
        | spanx
        | strong
        | sub
        | sup
        | tt
        | xref)*
     }
nartwork =
     element artwork {
       attribute xml:space { text }?,
       [ a:defaultValue = "" ] attribute name { text }?,
       [ a:defaultValue = "" ] attribute type { text }?,
       attribute src { text }?,
       [ a:defaultValue = "left" ]
       attribute align { "left" | "center" | "right" }?,
       [ a:defaultValue = "" ] attribute alt { text }?,
       [ a:defaultValue = "" ] attribute width { text }?,
       [ a:defaultValue = "" ] attribute height { text }?,
       [ a:defaultValue = "en" ] attribute xml:lang { text }?,
       attribute anchor { xsd:ID }?,
       attribute pn { text }?,
       text*
     }
nsourcecode =
     element sourcecode {
       [ a:defaultValue = "" ] attribute name { text }?,
       [ a:defaultValue = "" ] attribute type { text }?,
       attribute src { text }?,
       attribute anchor { xsd:ID }?,
       attribute pn { text }?,
       text
     }
nthead = element thead { tr+ }
ntbody = element tbody { tr+ }
ntfoot = element tfoot { tr+ }
ntr =
     element tr {
       [ a:defaultValue = "0" ] attribute border { text }?,
       (td, th)+
     }
ntd =
     element td {
       [ a:defaultValue = "0" ] attribute border { text }?,
       [ a:defaultValue = "0" ] attribute colspan { text }?,
       [ a:defaultValue = "0" ] attribute rowspan { text }?,
       [ a:defaultValue = "left" ]
       attribute align { "left" | "center" | "right" }?,
       (t+
        | (text
           | artwork
           | b
           | bcp14
           | br
           | cref
           | dl
           | em
           | eref
           | figure
           | i
           | iref
           | ol
           | sourcecode
           | strong
           | sub
           | sup
           | tt
           | ul
           | xref)+)
     }
nth =
     element th {
       [ a:defaultValue = "0" ] attribute border { text }?,
       [ a:defaultValue = "0" ] attribute colspan { text }?,
       [ a:defaultValue = "0" ] attribute rowspan { text }?,
       [ a:defaultValue = "left" ]
       attribute align { "left" | "center" | "right" }?,
       (t+
        | (text
           | artwork
           | b
           | bcp14
           | br
           | cref
           | dl
           | em
           | eref
           | figure
           | i
           | iref
           | ol
           | sourcecode
           | strong
           | sub
           | sup
           | tt
           | ul
           | xref)+)
     }
npostamble =
     element postamble {
       (text
        | b
        | bcp14
        | cref
        | em
        | eref
        | i
        | iref
        | spanx
        | strong
        | sub
        | sup
        | tt
        | xref)*
     }
ntexttable =
     element texttable {
       attribute anchor { xsd:ID }?,
       [ a:defaultValue = "" ] attribute title { text }?,
       [ a:defaultValue = "false" ]
       attribute suppress-title { "true" | "false" }?,
       [ a:defaultValue = "center" ]
       attribute align { "left" | "center" | "right" }?,
       [ a:defaultValue = "full" ]
       attribute style { "all" | "none" | "headers" | "full" }?,
       name?,
       preamble?,
       ttcol+,
       c*,
       postamble?
     }
nttcol =
     element ttcol {
       attribute width { text }?,
       [ a:defaultValue = "left" ]
       attribute align { "left" | "center" | "right" }?,
       (cref | eref | iref | xref | text)*
     }
nc =
     element c {
       (text
        | b
        | bcp14
        | cref
        | em
        | eref
        | i
        | iref
        | spanx
        | strong
        | sub
        | sup
        | tt
        | xref)*
     }
nbcp14 = element bcp14 { text }
nbr = element br { empty }
nback = element back { displayreference*, references*, section* }
ndisplayreference =
     element displayreference {
       attribute target { xsd:IDREF },
       attribute to { text }
     }
nreferences =
     element references {
       attribute anchor { xsd:ID },
       name,
       (reference | referencegroup)*
     }
nreference =
     element reference {
       attribute anchor { xsd:ID },
       attribute target { text }?,
       front,
       (annotation | format | refcontent | seriesInfo)*
     }
nreferencegroup =
     element referencegroup {
       attribute anchor { xsd:ID },
       reference+
     }
nseriesInfo =
     element seriesInfo {
       attribute name { text },
       attribute value { text },
       attribute asciiname { text }?,
       attribute asciivalue { text }?,
       empty
     }
nformat =
     element format {
       attribute target { text }?,
       attribute type { text },
       attribute octets { text }?,
       empty
     }
nannotation =
     element annotation {
       attribute ascii { text }?,
       (text
        | b
        | bcp14
        | cref
        | em
        | eref
        | i
        | iref
        | spanx
        | strong
        | sub
        | sup
        | tt
        | xref)*
     }
nrefcontent =
     element refcontent {
       attribute ascii { text }?,
       (text | b | bcp14 | em | i | strong | sub | sup | tt)*
     }
nstart = rfc
rfc =
       element rfc {
         attribute number { text }?,
         [ a:defaultValue = "" ] attribute obsoletes { text }?,
         [ a:defaultValue = "" ] attribute updates { text }?,
         attribute category { "std" | "bcp" | "info" | "exp" |
front =
       element front {
title =
       element title {
         attribute abbrev { text }?,
author =
       element author {
         attribute initials { text }?,
organization =
       element organization {
         attribute abbrev { text }?,
address = element address { postal?, phone?, facsimile?, email?,
country = element country { text }
phone = element phone { text }
facsimile = element facsimile { text }
uri = element uri { text }
date =
       element date {
         attribute day { text }?,
         attribute month { text }?,
         attribute year { text }?,
         empty
       }
area = element area { text }
workgroup = element workgroup { text }
keyword = element keyword { text }
note =
       element note {
middle = element middle { section+ }
section =
       element section {
         attribute anchor { xsd:ID }?,
t =
       element t {
         attribute anchor { xsd:ID }?,
         attribute hangText { text }?,
xref =
       element xref {
         attribute target { xsd:IDREF },
         [ a:defaultValue = "false" ] attribute pageno { "true" |
eref =
       element eref {
         attribute target { text },
         text
       }
iref =
       element iref {
         attribute item { text },
         [ a:defaultValue = "" ] attribute subitem { text }?,
         [ a:defaultValue = "false" ]
         attribute primary { "true" | "false" }?,
         empty
       }
cref =
       element cref {
         attribute anchor { xsd:ID }?,
         attribute source { text }?,
spanx =
       element spanx {
         [ a:defaultValue = "preserve" ]
         attribute xml:space { "default" | "preserve" }?,
         [ a:defaultValue = "emph" ] attribute style { text }?,
         text
       }
vspace =
       element vspace {
         [ a:defaultValue = "0" ] attribute blankLines { text }?,
         empty
       }
figure =
       element figure {
         attribute anchor { xsd:ID }?,
         [ a:defaultValue = "" ] attribute title { text }?,
         [ a:defaultValue = "false" ]
         attribute suppress-title { "true" | "false" }?,
         attribute src { text }?,
         [ a:defaultValue = "left" ]
         attribute align { "left" | "center" | "right" }?,
         [ a:defaultValue = "" ] attribute alt { text }?,
         [ a:defaultValue = "" ] attribute width { text }?,
         [ a:defaultValue = "" ] attribute height { text }?,
preamble =
artwork =
       element artwork {
postamble =
texttable =
       element texttable {
         attribute anchor { xsd:ID }?,
         [ a:defaultValue = "" ] attribute title { text }?,
         [ a:defaultValue = "false" ]
         attribute suppress-title { "true" | "false" }?,
         [ a:defaultValue = "center" ]
         attribute align { "left" | "center" | "right" }?,
         [ a:defaultValue = "full" ]
         attribute style { "all" | "none" | "headers" | "full" }?,
ttcol =
       element ttcol {
         attribute width { text }?,
         [ a:defaultValue = "left" ]
         attribute align { "left" | "center" | "right" }?,
references =
       element references {
reference =
       element reference {
         attribute anchor { xsd:ID },
         attribute target { text }?,
         front,
seriesInfo =
       element seriesInfo {
         attribute name { text },
         attribute value { text },
format =
       element format {
         attribute target { text }?,
         attribute type { text },
         attribute octets { text }?,
         empty
       }
annotation =
start = rfc


