Language-Tag = Primary-tag *( "-" Subtag )
Primary-tag = 1*8ALPHA
Subtag = 1*8ALPHA

language-range  = ( ( 1*8ALPHA *( "-" 1*8ALPHA )
Language-Header = "Content-Language" ":" 1#Language-tag

differences=content-language
boundary="limit"
