VOLUME_SIMPLE = 0,      /* volume maps to a single LU */ 

VOLUME_SLICE  = 1,      /* volume is a slice of another volume */ 

VOLUME_CONCAT = 2,      /* volume is a concatenation of multiple 
                                 volumes */ 

VOLUME_STRIPE = 3       /* volume is striped across multiple 
                                 volumes */ 

READ_WRITE_DATA  = 0, /* the data located by this extent is valid 
                              for reading and writing. */ 

READ_DATA = 1,        /* the data located by this extent is valid 
                              for reading only; it may not be written. 
                              */ 

INVALID_DATA = 2,     /* the location is valid; the data is 
                              invalid. It is a newly (pre-) allocated 
                              extent. There is physical space on the 
                              volume. */ 

NONE_DATA = 3,        /* the location is invalid. It is a hole in 
                              the file. There is no physical space on 
                              the volume. */ 

