Z = T - P
j = 1
v = 1
PL = bl[T-1]
WI = T - 1
WI = WI - 1
r = Rand() % K
r = Rand() % K
r = Rand() % CDF[MAX_DEG]
d = DegreeSampler(j)
B = (b[idx[0]], b[idx[i]], ..., b[idx[d-1]])
X = B * G
Xr = [I_M; X]
q = 2, let H[j] be the matrix over GF(256) formed by embedding each
