asterisk = %x2A ; "*"
dash = %x2D ; "-"
dot = %x2E ; "."
underscore = %x5F ; "_"
ANY = asterisk dot ; "*."
dns-char = ALPHA / DIGIT / dash
id-prefix = ALPHA / DIGIT
label = id-prefix [*61dns-char id-prefix]
sldn = label dot label
base-char = (dns-char / underscore)
domain = *(label dot) sldn
            ; not to exceed 238 characters
            ; excluding "_ssp._domainkey."
tpa-label = base32( sha-1( lcase(signing-domain)))
               ; 32 base-char characters

              +--------+------------------------------------+
              |   Tag  | Function                           |
              +--------+------------------------------------+
              | scope= | Authorization Scope List (as-list) |
              |  tpa=  | Authorized Domains List (ad-list)  |
              +--------+------------------------------------+

                               TPA-SSP Tags

scope= Authorization Scope List (Optional).  This tag defines a list
scope = "F" / "F-i" / "O" / "O-i" / "M" / "M-i" / "NO-TPA"
as-list = "scope" [FWS] "=" [FWS] scope 0*([FWS] ":" [FWS] scope)

tpa= Authorized Signing Domain list (Optional).  This tag repeats all
ad = [ANY] domain
ad-list = "tpa" [FWS] "=" [FWS] ad 0*([FWS] ":" [FWS] ad)




