JSONPath = root *(step)
root = "$"

step = ".." name ; nested descendants
        / "." name ; child (dot notation)
        / "[" value-expression *("," value-expression) "]"
           ; child[ren] (bracket notation)
        / "[" value-expression *2(":" value-expression) "]"  ; (slice)
value-expression = *DIGIT / name
                    / script-expression / filter-expression
name = "'" text "'"
        / "*" ; wildcard
script-expression = "(" script ")"
filter-expression = "?(" script ")"
script = <To be defined in the course of standardization>
text = <any text, restrictions to be defined>
DIGIT = %x30-39

                   Figure 2: ABNF definition for JSONPath

res1 = jsonPath(o, "$..author").toJSONString(),
res2 = jsonPath(o, "$..author",
                       {resultType:"PATH"}).toJSONString();

