value=4 (MONITORING Object missing).  Other objects are optional.
Error-type=6 (Mandatory Object missing) and Error-value=4 (MONITORING
value=19)

value=1)
value=21)

value=1)

Type=5 and Error-value=3 (To be Confirmed by IANA).


value=2 (capability not supported).  According to the procedure
