target='https://www.rfc-editor.org/info/rfc2119'>
target='https://www.rfc-editor.org/info/rfc7991'>
target='https://www.rfc-editor.org/info/rfc8174'>
target='https://github.com/riboseinc/rnp/'>
value="draft-ribose-asciirfc-04"/>
target="http://www.ietf.org/internet-drafts/draft-ribose-asciirfc-04.txt"/>
target='http://www.ietf.org/internet-drafts/draft-ribose-cfrg-sm4-08.txt'
target='https://www.rfc-editor.org/info/rfc7253'>
submissionType="IETF" prepTime="2018-03-23T14:59:43Z" version="3">
stream="IETF" value="draft-asciirfc-minimal-01"/>
value="draft-asciirfc-minimal-01"/>
initials="J. S.">
initials="T.">
numbered="false"><name>Introduction</name><t>AsciiRFC
target="I-D.ribose-asciirfc"/>.</dd>
target="operators"/>.</li>
target="I-D.ribose-cfrg-sm4"/>,
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.7991.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.8174.xml"
parse="text"/>
target="https://github.com/riboseinc/rnp/">
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml3//reference.I-D.draft-ribose-asciirfc-04.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml3//reference.I-D.draft-ribose-cfrg-sm4-08.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.7253.xml"
parse="text"/>
numbered="false"><name>Example
docName="draft-asciirfc-minimal-01">
initials="J. S.">
initials="T.">
style="verb">asciidoctor-rfc</spanx> Ruby gem.</t>
title="Introduction"><t>AsciiRFC <xref
target="I-D.ribose-asciirfc"/> is an extremely simple way to
style="strong">MUST</spanx>", "<spanx style="strong">MUST
style="strong">REQUIRED</spanx>", "<spanx
style="strong">SHALL</spanx>",
style="strong">SHOULD</spanx>", "<spanx
style="strong">SHOULD NOT</spanx>", "<spanx
style="strong">RECOMMENDED</spanx>",
style="strong">MAY</spanx>", and "<spanx
style="strong">OPTIONAL</spanx>" in this
target="operators"/>.</t>
target="I-D.ribose-cfrg-sm4"/>,
target="https://github.com/riboseinc/rnp/">
updates="8140" sortRefs="true" tocInclude="true"
submissionType="independent" prepTime="2018-03-23T14:59:47Z"
version="3">
stream="independent" value="draft-camelot-holy-grenade-00"/>
surname="Pendragon" initials="A.">
updates="8140" sortRefs="true" tocInclude="true"
submissionType="independent" prepTime="2018-03-23T14:59:47Z"
version="3">
stream="independent" value="draft-camelot-holy-grenade-00"/>
surname="Pendragon" initials="A.">
submissionType="independent" prepTime="2018-03-23T14:59:52Z"
version="3">
stream="independent" value="draft-divination-cfapi-00"/>
value="draft-divination-cfapi-00"/>
initials="G.">
updates="8140" sortRefs="true" tocInclude="true"
submissionType="independent" prepTime="2018-03-23T14:59:47Z"
version="3">
stream="independent" value="draft-camelot-holy-grenade-00"/>
surname="Pendragon" initials="A.">
version="3">
stream="IETF" value="draft-camelot-holy-grenade-00" />
surname="Pendragon"
initials="A.">
version="3">
stream="IETF" value="draft-camelot-holy-grenade-00" />
surname="Pendragon"
initials="A.">
target="RFC2119"/> <xref target="RFC8174"/>
numbered="true"><name>Introduction</name><t><xref
target="RFC8140"/> refers to the intended move of RFC formatting to
MWMWMMWMW======MWMMCANTWSEEMAMTHINGMMWMWMWMWMWMWMBETMMW` . `
MWMWMMWMW======MWMMCANTWSEEMAMTHINGMMWMWMWMWMWMWMBETMMW` . `
target="sovereign-orb"/>.</dd>
target="projectile-cow"/></li>
target="trojan-rabbit"/></li>
target="killer_rabbit_caerbannog"/>.
numbered="true"><name>The Killer Rabbit of
displayFormat="of" target="RFC8140">Ze Vompyre</relref>,
item="Cave of Caerbannog"/> was
target="hand-grenade-figure"/>)
leveloffset=_offset_,
lines=_ranges_,
indent=_depth_
target="https://www.rfc-editor.org/info/rfc2119">
target="https://www.rfc-editor.org/info/rfc2635">
target="https://www.rfc-editor.org/info/rfc7990">
target="https://www.rfc-editor.org/info/rfc8140">
target='https://www.rfc-editor.org/info/rfc8174'>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2635.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.7990.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.8140.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.8174.xml"
parse="text"/>
target='id'>words</xref>"]"

target='id'>words</xref>"]"

section='2.4' target='id'}/>"]"

text="<relref relative='section2_4' displayFormat='comma'
section='2.4' target='id'/>"]"

target='https://www.rfc-editor.org/info/rfc2119'>
target='https://www.rfc-editor.org/info/rfc7991'>
target='https://www.rfc-editor.org/info/rfc8174'>
target='https://github.com/riboseinc/rnp/'>
value="draft-ribose-asciirfc-04"/>
target="http://www.ietf.org/internet-drafts/draft-ribose-asciirfc-04.txt"/>
target='http://www.ietf.org/internet-drafts/draft-ribose-cfrg-sm4-08.txt'
target='https://www.rfc-editor.org/info/rfc7253'>
submissionType="IETF" prepTime="2018-03-23T14:59:43Z" version="3">
stream="IETF" value="draft-asciirfc-minimal-01"/>
value="draft-asciirfc-minimal-01"/>
initials="J. S.">
initials="T.">
numbered="false"><name>Introduction</name><t>AsciiRFC
target="I-D.ribose-asciirfc"/>.</dd>
target="operators"/>.</li>
target="I-D.ribose-cfrg-sm4"/>,
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.7991.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.8174.xml"
parse="text"/>
target="https://github.com/riboseinc/rnp/">
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml3//reference.I-D.draft-ribose-asciirfc-04.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml3//reference.I-D.draft-ribose-cfrg-sm4-08.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.7253.xml"
parse="text"/>
numbered="false"><name>Example
MWMWMMWMW======MWMMCANTWSEEMAMTHINGMMWMWMWMWMWMWMBETMMW` . `
target="https://www.rfc-editor.org/info/rfc2119">
target="https://www.rfc-editor.org/info/rfc2635">
target="https://www.rfc-editor.org/info/rfc7990">
target="https://www.rfc-editor.org/info/rfc8140">
target='https://www.rfc-editor.org/info/rfc8174'>
updates="8140" sortRefs="true" tocInclude="true"
submissionType="independent" prepTime="2018-03-23T14:59:47Z"
version="3">
stream="independent" value="draft-camelot-holy-grenade-00"/>
surname="Pendragon" initials="A.">
target="RFC2119"/> <xref target="RFC8174"/>
numbered="true"><name>Introduction</name><t><xref
target="RFC8140"/> refers to the intended move of RFC formatting to
target="RFC8140"/>
numbered="true"><name>The French-occupied castle</name>
target="projectile-cow"/></li>
target="trojan-rabbit"/></li>
target="killer_rabbit_caerbannog"/>.
numbered="true"><name>The Killer Rabbit of
displayFormat="of" target="RFC8140">Ze Vompyre</relref>,
MWMWMMWMW======MWMMCANTWSEEMAMTHINGMMWMWMWMWMWMWMBETMMW` . `
numbered="true"><name>Holy Hand Grenade of Antioch</name>
type="binary-art" width="124"/>
item="Cave of Caerbannog"/> was
target="hand-grenade-figure"/>)
target="sovereign-orb"/>.</dd>
numbered="true"><name>Dramatis
numbered="true"><name>Past the Killer
numbered="true"><name>Security
target="killer-bunny"/>) out.</t>

href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2635.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.7990.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.8140.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.8174.xml"
parse="text"/>
target='https://www.rfc-editor.org/info/rfc2119'>
target='https://www.rfc-editor.org/info/rfc5785'>
fullname='M. Nottingham'>
fullname='E. Hammer-Lahav'>
target='https://www.rfc-editor.org/info/rfc7230'>
role='editor'>
role='editor'>
target='https://www.rfc-editor.org/info/rfc7234'>
role='editor'>
role='editor'>
role='editor'>
target='https://www.rfc-editor.org/info/rfc7807'>
fullname='M. Nottingham'>
target='https://www.rfc-editor.org/info/rfc8174'>
target='https://www.rfc-editor.org/info/rfc8259'>
role='editor'>
target='https://www.iso.org/en/standard/70907.html'>
target='https://www.rfc-editor.org/info/rfc3339'>
target='https://www.rfc-editor.org/info/rfc5246'>
submissionType="independent" prepTime="2018-03-23T14:59:52Z"
version="3">
stream="independent" value="draft-divination-cfapi-00"/>
value="draft-divination-cfapi-00"/>
initials="G.">
numbered="false"><name>Introduction</name><t>Fortune-telling,
numbered="false"><name>Conventions Used in This
target="RFC2119"/> <xref target="RFC8174"/>
numbered="false"><name>Fortune Heuristics Service Well-Known
target="iana"/>).</t>
target="service-discovery"/>.</t>
numbered="false"><name>Well-Known URI
target="RFC7234"/>) in the redirect response to set
numbered="false"><name>New HTTP Methods: SEEK and
numbered="false"><name>Defined Data Types: Date-Time
target="RFC3339"/>, with the addition that reduced
target="ISO.8601-1.2018"/> are
numbered="false"><name>Root of Fortune Path URI
numbered="false"><name>Fortune Heuristics Service
numbered="false"><name>Service Specification
numbered="false"><name>Service Specification
numbered="false"><name>Fortune Heuristics Report Request and
numbered="false"><name>Fortune Heuristics Report
numbered="false"><name>Fortune Heuristics Report
numbered="false"><name>Report Interval
numbered="false"><name>Report Events
numbered="false"><name>Report Generation
numbered="false"><name>Well-Known URI
target="RFC5785"/>.</t>
numbered="false"><name>"fortune" Well-Known URI
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.5785.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.7230.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.7234.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.7807.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.8174.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.8259.xml"
parse="text"/>
target="https://www.iso.org/en/standard/70907.html">
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.3339.xml"
parse="text"/>
href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.5246.xml"
parse="text"/>
numbered="false"><name>Acknowledgements</name><t>The
