certstring = (certspec / multispec) [ "|" certattrs ]

                         Figure 1: certstring ABNF

certspec         = certspec-hash / certspec-content / certspec-el /
                      certspec-path

hexOctet         = 2HEXDIG

certspec-hash    = "SHA-1"   ":" 20hexOctet /
                      "SHA-256" ":" 32hexOctet /
                      "SHA-384" ":" 48hexOctet /
                      "SHA-512" ":" 64hexOctet /
                      certspec-other-hash

certspec-other-hash = certspec-hash-type ":" certspec-hash-value
certspec-hash-type = scheme
certspec-hash-value = 16*hexOctet

certspec-content = ("HEX" / "BASE16") ":" 1*hexOctet /
                      "BASE64"  ":" base64string

base64char       = ALPHA / DIGIT / "+" / "/"
base64string     = 1*(4base64char)
                      [ 3base64char "=" / 2base64char "==" ]
certspec-el   = "ISSUERSN" ":" distinguishedName ";" serialNumber /
                   "SKI"      ":" 1*(hexOctet)

serialNumber     = 1*hexOctet

certspec-path    = certspec-uri / certspec-filepath

certspec-uri     = "URI:" URI-reference / URI-Template

certspec-filepath = ("/" / "\" / [A-Z] ":" /
                       ("." / "..") ("/" / "\") / "~" / "%" / "$")
                       *filepathchar

filepathchar      = %x01-29 / %x2B-3B / "=" / %x40-5B /
                       %x5D-7B / %x7D-7F / quoted-fpc / BEYONDASCII

quoted-fpc       = "\" ("*" / "<" / ">" / "?" / "\" / "|")

multispec = 1*("<" certspec ">")

                         Figure 3: multispec ABNF

certattrs = certattr ["," certattrs]
certattr  = certattrType ["=" certattrValues]
certattrType = descr / numericoid
certattrValues = certattrValue ["+" certAttrValues]
certattrValue = hexstring / string /
                   basic-xer-string / asn1-value-string
basic-xer-string = "<" <balanced tags> ">"
asn1-value-string = %x22 <balanced quotation marks> %x22

                         Figure 4: certattrs ABNF

