From=20because some mail transport agents will insert a greater-
smime-type=enveloped-data
gtaMXpRwZRNYAgDsiSf8Z9P43LrY4OxUk660cu1lXeCSFOSOpOJ7FuVyU=
name=smime.p7m
name=smime.p7m
micalg=sha-256;
boundary="----=_NextBoundry____Fri,_06_Sep_2002_00:25:21";
protocol="application/pkcs7-signature"

name=smime.p7z
eNoLycgsVgCi4vzcVIXixNyCnFSF5Py8ktS8Ej0AlCkKVA==

