Class-Num = 2

C-Type = 00000001b   // Indicates incoming interface
Length = 36 (4 + 32)

              0             1             2            3
C-Type = 00001000b   // Indicates incoming interface
Length = 8 (4 + 4)

              0             1             2            3
C-Type = 00001001b   // Indicates incoming interface
Length = 40 (4 + 4 + 32)

              0             1             2            3
C-Type = 00001101b   // Indicates incoming interface
Length = 44 (4 + 4 + 4 + 32)

              0             1             2            3
C-Type = 00001100b   // Indicates incoming interface
Length = 12 (4 + 4 + 4)

              0             1             2            3
C-Type = 00000101b   // Indicates incoming interface
Length = 40 (4 + 4 + 32)

              0             1             2            3
C-Type = 00001011b   // Indicates incoming interface
Length = 56 (4 + 4 + 16 + 32)

              0             1             2            3
C-Type = 00001010b   // Indicates incoming interface
Length = 24 (4 + 4 + 16)

              0             1             2            3
C-Type = 00000011b   // Indicates incoming interface
Length = 52 (4 + 16 + 32)

              0             1             2            3
