xmlns="urn:oma:params:xml:ns:poc:poc-settings"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

schemaLocation="http://www.w3.org/2001/xml.xsd"/>
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
use="required" />
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
use="required" />
minOccurs="0" maxOccurs="unbounded"/>
use="required"/>
minOccurs="0" maxOccurs="unbounded"/>
