m=<media> <port> <proto> <fmt> ...






m=image 54111 SCTP *
c=IN IP4 192.0.2.2
a=setup:actpass
a=connection:new

                                 Figure 1

m=image 54321 SCTP *
c=IN IP4 192.0.2.1
a=setup:passive
a=connection:new

                                 Figure 2

m=application 54321 SCTP *
c=IN IP4 192.0.2.1
a=setup:passive
a=connection:new

                                 Figure 3






m=application 9 SCTP *
c=IN IP4 192.0.2.2
a=setup:active
a=connection:new

                                 Figure 4

m=image 54111 SCTP/DTLS t38
c=IN IP4 192.0.2.2
a=setup:actpass
a=connection:new
a=fingerprint:SHA-1 \
             4A:AD:B9:B1:3F:82:18:3B:54:02:12:DF:3E:5D:49:6B:19:E5:7C:AB

                                 Figure 5


