Latitude = 0x04dcc1fc8,

Latitude = 0001001101110011000001111111001000


Longitude = 0xf65ecf031,

Longitude = 1101100101111011001111000000110001

targetNamespace="urn:ietf:params:xml:ns:geopriv-policy"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

namespace="urn:ietf:params:xml:ns:common-policy" />

namespace="urn:ietf:params:xml:ns:pidf:geopriv10:civilLoc" />

substitutionGroup="cp:condition"/>
substitutionGroup="cp:condition">
minOccurs="3" maxOccurs="unbounded">
type="xs:string"
minOccurs="1"
maxOccurs="1" />
type="xs:string"
minOccurs="1"
maxOccurs="1"/>
type="xs:string"
minOccurs="0"
maxOccurs="1"/>
substitutionGroup="cp:transformation">
substitutionGroup="cp:transformation"/>
substitutionGroup="cp:transformation"/>
substitutionGroup="cp:transformation"/>
substitutionGroup="cp:transformation"/>
substitutionGroup="cp:transformation"/>
substitutionGroup="cp:transformation"/>
substitutionGroup="cp:transformation"/>

