future-release-integer = %x31-39 *8DIGIT
                                  ; integer in the range 1-999999999
                                  ; measured in seconds

max-future-release-interval = future-release-integer

max-future-release-date-time = date-time

line = "250-FUTURERELEASE" SP max-future-delivery-interval
                                    SP max-future-delivery-date-time

future-release-interval = future-release-integer

future-release-date-time = Internet-style-date-time-UTC

hold-for-param = "HOLDFOR=" future-release-interval
         
hold-until-param = "HOLDUNTIL=" future-release-date-time

hold-param = hold-for-param / hold-until-param

orig-hold-param-value = ("for;" future-release-interval) /
                                 ("until;" future-release-date-time)
                            ; this is the value of the HOLD parm from
                            ; the MAIL command of the original message

future-release-request-field = "Future-Release-Request:"
                                        orig-hold-param-value

