elementFormDefault="qualified" attributeFormDefault="unqualified">
new-etag="7hahsd" previous-etag="7hahsd"/>
new-etag="ffds66a" previous-etag="xkkkaisu">
      <add-element parent="resource-lists/list[@name=&quot;l1&quot;]"
position="1"><![CDATA[<entry uri="sip:new-worker@example.com"/>]
content="text/html;charset=iso-8859-1"/>
