y = H(x)
       The binary string x is given to a function H which produces an
       output y.

y = g^x mod p

       the generator taken to the x-th power modulus the prime returns
       an element in the group.

Y = x*G

       the base point G is multiplied x-times to produce another point
       on the curve, Y.

i = 1
K = PRF(key, label, i)
i = i + 1
K = K | PRF(key, K | label | i)
pws = H(peer-ID | server-ID | password)

PWE = pws * G

pws = H(peer-ID | server-ID | password)

pwe = g^pws mod p

MK = H(ks | F(Element_S+Element_P) | (Scalar_S+Scalar_P) mod r)

MK = H(kp | F(Element_P+Element_S) | (Scalar_P+Scalar_S) mod r)


MK = H(ks | (Element_S + Element_P) mod r |
            (Scalar_S + Scalar_P) mod r)

MK = H(kp | (Element_P + Element_S) mod r |
            (Scalar_P + Scalar_S) mod r)


Method-ID = H(Ciphersuite | Scalar_P | Scalar_S)

Session-ID = Type-Code | Method-ID

