cycle-clock-offset = (clock1 mod (cycle-time * cycles) )
tcqf = ietf-detnet-tcqf
iif = pak.context.iif
oif = pak.context.oif = forward_process(pak)

cycle = pak.context.tcqf_cycle =
         map_cycle(cycle,
           tcqf.tcqf-if-config[oif].tcqf-iif-cycle-map[[iif])

cycle = 1
cc =  tcqf.tcqf-config.cycle-time *
           tcqf.tcqf-config.cycle-time
o =   tcqf.tcqf-config.cycle-clock-offset
nextcyclestart = floor(tnow / cc) * cc + cc + o

cycle = (cycle + 1) mod tcqf.tcqf-config.cycles + 1
CT  = cycle-time
C   = cycles
CC  = CT * C
O1  = cycle-clock-offset router R1, interface towards R2
O2  = cycle-clock-offset router R2, output interface of interest
A = ( ceil( ( O1' - O2 ) / CT) + C + 1) mod CC
