Identity-Info       = "Identity-Info" HCOLON ident-uri-info /
                       ( ident-info-params *( SEMI ident-info-params ) )
ident-uri-info      = ident-info *( SEMI ident-info-params )

   where ident-uri-info is the definition of Identity-Info from RFC 4474
   and ident-info-params is used as the only element of Identity-Info
   only when used for a security mechanism such as shared secret where
   no certificates must be identified or retrieved.

   Messages using shared secrets must contain an "alg" parameter.  This
   specification defines the value "hmac-sha1" for the "alg" parameter.
   Messages MUST additionally contain the token "dSIP" as an ident-info-
   extension to indicate the type of processing required to validate the
   message.  Therefore, the Identity-Info header will be

   Identity-Info: alg=hmac-sha1;dSIP

