Client-Cookie = MAC_Algorithm(
            Client IP Address | Server IP Address, Client Secret )

Hash = SipHash2.4(
          Client Cookie | Version | Reserved | Timestamp | Client-IP,
          Server Secret )

