PSK = KDF(Root Key Material, key label | "\0" | Ni | Nr | IDi | length)


   Where:

   o  KDF is the default key derivation function based on HMAC-SHA-256
      as specified in Section 3.1.2 of [RFC5295].

   o  Root Key Material is the key available to the protocol leveraging
      this Diameter application, e.g., the long term shared secret that
      would be provisioned to be used for IKEV2, or the Extended Master
      Session Key (EMSK) as the result of prior EAP authentication etc.
      Selection of this value is left up to the protocol leveraging this
      Diameter application.

   o  Key label is set to 'psk4ikev2@ietf.org'.

   o  | denotes concatenation

   o  "\0" is a NULL octet (0x00 in hex)

   o  length is a 2-octet unsigned integer in network byte order

   When applications using this protocol define their own PSK generation
   algorithm it is strongly RECOMMENDED that the nonces Ni and Nr are
   used in the computation.  It is also RECOMMENDED that IDi be used.
   IDr SHOULD NOT be used in the PSK generation algorithm.  Applications
   that want to use IDr in the computation should take into
   consideration that the IDr asserted by the IKEv2 peer may not be the
   same as the IDr returned by the IKEv2 responder.  This mismatch will
   result in different PSKs being generated.  The HAAA returns the PSK
   to the IKEv2 Server using the Key AVP as specified in
   [I-D.ietf-dime-local-keytran].

   Once the IKEv2 Server receives the PSK from the HAAA, the IKEv2
   Server verifies the IKE_AUTH message received from the IKEv2 Peer.
   If the verification of AUTH is successful, the IKEv2 Server sends the
   IKE message back to the IKEv2 Peer.

