Destination=Client.net, and copies all of the blocks from the
L=00, 01, or 10, and 32 octets when L=11).  When truncating, the
c=    Challenge value.  A base-64 encoded 64-bit number.  This
         attribute is MANDATORY in keys of type keyAgreement that will
         be used for receiving incoming connections.

k=    Key type.  This is a string value (NOT an OID) taken from
         Section 2.1.1.1 of RFC 5480 [4].  Can be one of the following:

         secp256r1

u=    Intended key usage.  A public key may be used either for key
         agreement or digital signatures, but not both.  The usage of a
         key is indicated with the "u=" attribute.  Can be one of the
         following:

         keyAgreement      The key will be used in a Diffie-Hellman
                           computation for generating shared secret
                           material.

         digitalSignature  The key will be used to compute the public
                           key signatures using the ECDSA algorithm as
                           specified for the public key signature block
                           type (see Section 3.1.7).

h=    Hash algorithm.  When u=keyAgreement, this indicates the type
         of signature that must be used in the Fragment Signature field
         of incoming packets.

         sha1/4          HMAC-SHA-1 truncated to 4 octets (equivalent to
L=00).

p=    Public Key value.  A base-64 encoded representation of the
         bytestring formed by concatenating the value of X with one byte
         indicating whether Y is irrelevant, positive, negative, or
         explicit followed by the value of Y in case it is given
         explicitly.  The one byte can take on the following values:





         0   Y is not given explicitly, and the value of Y is
             irrelevant.

         1   Y is not given explicitly but is positive and can be
             calculated from X.

         2   Y is not given explicitly but is negative and can be
             calculated from X.

         3   Y follows explicitly.

np=   Next preferred public key selector.  This is a string of DNS
         labels separated by periods (".") that indicates a selector
         that may be tried next in case the current TXT record is
         unsatisfactory.  This attribute is OPTIONAL.

