interval = AckWindow / MessageRate  
         
HeartbeatPeriod = 2 * interval  
         
HighestAllowed = seqnum + senderWindow  
         
interval = AckWindow / MessageRate  
        
TRACKTimeout = 2 * interval  

  
  
  
         
ConfirmationStatus = AllsendersAcknowlege  
ConfimationStatus = FailuresExceedMaximumListSize  
ConfirmationStatus = ListOfFailures  
ConfirmationStatus = SomesendersAcknowledge  
       
LocalDallyTime = TRACKSendTime - HeartbeatReceiveTime.  
         
RTT_average = RTT_measurement * alpha + RTT_average (1-alpha)  
         
     
