xmlns="urn:ietf:params:xml:ns:netmod:notifications">
xmlns="urn:ietf:params:xml:ns:netmod:notifications"/>
xmlns="urn:ietf:params:xml:ns:netconf:state">333</sessionId>
xmlns="urn:ietf:params:xml:ns:netconf:state">SSH</transport>
xmlns="urn:ietf:params:xml:ns:netconf:state"
xmlns="urn:ietf:params:xml:ns:netconf:state"
xmlns="urn:ietf:params:xml:ns:netconf:state"
xmlns="urn:ietf:params:xml:ns:netconf:state"
xmlns="urn:ietf:params:xml:ns:netmod:notifications"
targetNamespace="urn:ietf:params:xml:ns:netmod:notifications"
schemaLocation=
schemaLocation="../../netconf_monitoring/monitoring.xsd"/>

maxOccurs="unbounded"/>
type="eventClassInstanceType" abstract="true"/>

type="configurationChangeType"
substitutionGroup="eventClassInstance"/>

substitutionGroup="eventClassInstance"/>

substitutionGroup="eventClassInstance"/>





substitutionGroup="eventClassInstance"/>
substitutionGroup="eventClassInstance"/>

substitutionGroup="eventClassInstance"/>
substitutionGroup="eventClassInstance"/>

substitutionGroup="eventClassInstance"/>

substitutionGroup="eventClassInstance"/>

substitutionGroup="eventClassInstance"/>


type="eventIdentifier"/>
type="EventClassType">
type="monitor:ManagementSession"/>
type="ConfigurationChangeNotificationType"
substitutionGroup="ncEvent:notificationContent">
type="InventoryActionType"/>
type="monitor:ManagementSession"/>
type="TrendIndicationType"
minOccurs="0"/>
minOccurs="0"/>
type="NameValuePairType"
maxOccurs="unbounded"/>
type="HeartbeatNotificationType"
substitutionGroup="ncEvent:notificationContent">
