pk11-URI            = "pkcs11" ":" pk11-path *1("?" pk11-query)
pk11-path           = *1(pk11-pattr *(";" pk11-pattr))
pk11-pattr          = pk11-token / pk11-manuf / pk11-serial /
                         pk11-model / pk11-lib-manuf /
                         pk11-lib-ver / pk11-lib-desc /
                         pk11-object / pk11-type / pk11-id /
                         pk11-x-pattr
pk11-qattr          = pk11-pin-source / pk11-x-qattr
pk11-query          = *1(pk11-qattr *("&" pk11-qattr))
pk11-res-avail =      ":" / "[" / "]" / "@" / "!" / "$" /
                         "'" / "(" / ")" / "*" / "+" / "," / "="
pk11-path-res-avail = pk11-res-avail / "&"
pk11-query-res-avail = pk11-res-avail / "/" / "?"
pk11-pchar          = unreserved / pk11-path-res-avail / pct-encoded
pk11-qchar          = unreserved / pk11-query-res-avail / pct-encoded
pk11-token          = "token" "=" *pk11-pchar
pk11-manuf          = "manufacturer" "=" *pk11-pchar
pk11-serial         = "serial" "=" *pk11-pchar
pk11-model          = "model" "=" *pk11-pchar
pk11-lib-manuf      = "library-manufacturer" "=" *pk11-pchar
pk11-lib-desc       = "library-description" "=" *pk11-pchar
pk11-lib-ver        = "library-version" "=" 1*DIGIT *1("." 1*DIGIT)
pk11-object         = "object" "=" *pk11-pchar
pk11-type           = "type" "=" *1("public" / "private" / "cert" /
                         "secret-key" / "data")
pk11-id             = "id" "=" *pk11-pchar
pk11-pin-source     = "pin-source" "=" *pk11-qchar
pk11-x-attr-nm-char = ALPHA / DIGIT / "-" / "_"
pk11-x-pattr         = "x-" 1*pk11-x-attr-nm-char "=" *pk11-pchar
pk11-x-qattr         = "x-" 1*pk11-x-attr-nm-char "=" *pk11-qchar
manufacturer=Snake%20Oil,%20Inc.;
model=1.0;
object=my-certificate;
type=cert;
id=%69%95%3E%5C%F4%BD%EC%91;
serial=
manufacturer=Snake%20Oil,%20Inc.
library-description=Soft%20Token%20Library;
library-version=1.23


library-version=3;
id=%01%02%03%Ba%dd%Ca%fe%04%05%06
object=my-certificate;
type=cert
object=my-certificate;
type=cert


object=my-certificate;
type=cert;
x-vend-aaa=value-a
x-vend-bbb=value-b


