value = 1.  This report contains a string with the "name" of the
grtt = 1.0e03;
grtt = 1.0e-06;
loss_fraction = "loss" / 65535.0

block_id = "offset" / ("block_size" * "segment_size");

receiver_rtt = current_time - "grtt_response"

current_estimate = 0.25 * current_estimate + 0.75 * peak;
current_estimate = 0.75 * current_estimate + 0.25 * peak;

B = ---------------------------------------------------------
              RTT*sqrt(2bp/3) + T0*min(1,3*sqrt(3bp/8))*p*pow(1+32p, 2)

B   = Resulting predicted rate in units of bytes per second,

PacketSize = Nominal transmitted packet size.

RTT = Estimate of round trip packet delay in seconds,

p   = Estimate of packet loss fraction,

T0  = Applicable TCP retransmission timeout,

b   = Number of packets acknowledged by a TCP ACK.

rtt_current = currentTime - "grtt_response"

err = rtt_current - rtt_smoothed;
new_rate = old_rate + (1.0 *"segment_size")

new_rate = old_rate * 0.75

