goodput = r (3 + 6f - f^2) / (4 (1+f))

dropping_ = false;
r = dodequeue(now);
dropping_ = false;
drop_next_ = control_law(drop_next_, count_);
r = dodequeue(now);
dropping_ = true;

delta = count_ - lastcount_;
count_ = 1;
count_ = delta;

drop_next_ = control_law(now, count_);
lastcount_ = count_;
first_above_time_ = 0;
first_above_time_ = 0;
first_above_time_ = now + INTERVAL;
