passwordvalue   = schemeprefix hashedpasswd
schemeprefix    = "{" scheme "}"
scheme          = "crypt" / "md5" / "sha" / "ssha" / altscheme
altscheme       = "x-" keystring
hashedpasswd    = hashed password

ipServiceProtocol=tcp, ... and cn=domain+ipServiceProtocol=udp, ...)
ou=people,dc=...                      posixAccount
                                             shadowAcount
ou=group,dc=...                       posixGroup
ou=services,dc=...                    ipService
ou=protocols,dc=...                   ipProtocol
ou=rpc,dc=...                         oncRpc
ou=hosts,dc=...                       ipHost
ou=ethers,dc=...                      ieee802Device
                                             bootableDevice
ou=networks,dc=...                    ipNetwork
ou=netgroup,dc=...                    nisNetgroup
nisMapName=...,dc=...                 nisObject
automountMapName=...,dc=...           automountMap
