xmlns="urn:ietf:params:xml:ns:kalua:1"
      <ns-uri>http://www.example.com/profile</ns-prefix>
      <ns-prefix>pr/<ns-prefix>
      <release>1.0</release>

      <class name="profile">
         <attribute name="name">
            <type>kalua:string</type>
         </attribute>
         <attribute name="name">
            <type>string</type>
         </attribute>
         <key>
            <member>name</member>
         </key>
      </class>

xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
      <get-config>
         <source>
            <running/>
         </source>
      </get-config>
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
      <get-config>
         <source>
            <running/>
         </source>
      </get-config>
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
name="import"
type="kalua:importType" minOccurs="0"
maxOccurs="unbounded"/>
maxOccurs="unbounded">
                              <xsd:element
name="typedef"
type="kalua:typedefType"
minOccurs="0"
maxOccurs="unbounded"/>
name="attribute-group"
type="kalua:AttributeGroup"
minOccurs="0"
maxOccurs="unbounded"/>
type="kalua:Class"
minOccurs="0"
maxOccurs="unbounded"/>
name="relationship"
type="kalua:Relationship"
minOccurs="0"
maxOccurs="unbounded"/>
name="annotation-type"
type="kalua:annotation-typeType"
minOccurs="0"
maxOccurs="unbounded"/>
ref="kalua:NamedElementAttributes"/>
maxOccurs="unbounded"/>

type="xsd:boolean" default="true"/>
type="xsd:boolean" default="true"/>
type="xsd:string" minOccurs="0"/>
type="xsd:string" minOccurs="0"/>
type="kalua:AttributeGroup" minOccurs="0"
maxOccurs="unbounded"/>

ref="kalua:ConstrainableElementProperties"/>
            </xsd:sequence>
      </xsd:complexType>
type="xsd:nonNegativeInteger" default="0"/>
default="true"/>
minOccurs="0"/>
ref="kalua:ConstrainableElementProperties"/>
type="kalua:restrictionType"/>
type="kalua:enum-literalType"
maxOccurs="unbounded"/>
type="kalua:enum-literalType" maxOccurs="unbounded"/>

ref="kalua:simpleTypeDefinition"
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
id="minExclusive"/>
id="minInclusive"/>
id="maxExclusive"/>
id="maxInclusive"/>
type="xs:positiveInteger"
use="required"/>
id="fractionDigits"/>
type="kalua:numFacet" id="minLength"/>
type="kalua:numFacet" id="maxLength"/>
type="kalua:typedefType"
minOccurs="0" maxOccurs="unbounded"/>

type="kalua:ModelElementReference"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded">
type="xsd:string"/>
type="xsd:string"/>
maxOccurs="unbounded"/>

type="kalua:ModelElementReference"
minOccurs="0">
ref="kalua:NamedElementAttributes"/>
id="Site"
presentation="Site">
type="kalua:Relationship" ="0" maxOccurs="unbounded"/>

type="kalua:ModelElementReference"
minOccurs="0"/>
base="xsd:string">
name="language"
type="xsd:normalizedString"/>
                                                  </xsd:extension>
                                             </xsd:simpleContent>
type="xsd:nonNegativeInteger" default="0" minOccurs="0"/>
default="unbounded" minOccurs="0">
                <xsd:simpleType>
                      <xsd:union memberTypes="xsd:nonNegativeInteger">
                            <xsd:simpleType>
                                  <xsd:restriction base="xsd:string">
                                        <xsd:enumeration
value="unbounded"/>
name="e"
type="kalua:annotation-propertyType"
minOccurs="0" maxOccurs="unbounded"/>
name="annotation-property-type"
type="kalua:annotation-property-typeType"
minOccurs="0" maxOccurs="unbounded"/>
name="annotable-type"
type="kalua:annotable-typeType"
maxOccurs="unbounded"/>
targetNamespace="urn:ietf:params:xml:ns:kalua:1" version="0.2">
    <xsd:simpleType name="nameType">
       <xsd:restriction base="xsd:normalizedString">
       <xsd:pattern value="[a-zA-Z][_A-Za-z0-9]*"/>
       <!--xsd:maxLength value="30"/-->
    </xsd:restriction>
    </xsd:simpleType>
    <xsd:attributeGroup name="NamedElementAttributes">
       <xsd:attribute name="name" type="kalua:nameType" use="required"/>
    </xsd:attributeGroup>
    <xsd:group name="ModelElementProperties">
       <xsd:sequence>
          <xsd:element name="description"
type="xsd:string" minOccurs="0"/>
type="kalua:annotationType" minOccurs="0"
maxOccurs="unbounded"/>
maxOccurs="unbounded">
             <xsd:complexType>
                <xsd:sequence>
                   <xsd:group ref="kalua:ModelElementProperties"/>
                   <xsd:element name="expression"
type="xsd:string"/>
minOccurs="0" maxOccurs="unbounded">
             <xsd:complexType>
                <xsd:sequence>
                   <xsd:group ref="kalua:ModelElementProperties"/>
                </xsd:sequence>
                <xsd:attribute name="attribute-group"
type="kalua:ModelElementReference"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded">
             <xsd:annotation>
                <xsd:documentation>
maxOccurs="unbounded"/>
value="[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*"/>
type="kalua:importType" minOccurs="0"
maxOccurs="unbounded"/>
maxOccurs="unbounded">
                   <xsd:element name="typedef"
type="kalua:typedefType"
minOccurs="0" maxOccurs="unbounded"/>
type="kalua:AttributeGroup"
minOccurs="0" maxOccurs="unbounded"/>
type="kalua:Class"
minOccurs="0" maxOccurs="unbounded"/>
type="kalua:Relationship"
minOccurs="0" maxOccurs="unbounded"/>
type="kalua:annotation-typeType"
minOccurs="0" maxOccurs="unbounded"/>
type="kalua:augmentType"
minOccurs="0" maxOccurs="unbounded"/-->
ref="kalua:NamedElementAttributes"/>
ref="kalua:ModelElementProperties"/>
ref="kalua:simpleTypeDefinition"/>
name="unit" type="xsd:string"
minOccurs="0"/>
ref="kalua:ConstrainableElementProperties"/>
ref="kalua:ConstrainableElementProperties"/>
ref="kalua:ConstrainableElementProperties"/>
type="xsd:nonNegativeInteger"
default="0"/>
default="unbounded">
                   <xsd:simpleType>
                      <xsd:union
memberTypes="xsd:nonNegativeInteger">
                         <xsd:simpleType>
                            <xsd:restriction
base="xsd:string">
                               <xsd:enumeration
value="unbounded"/>
type="xsd:boolean" default="true"/>
type="xsd:NCName"/>
default="read-create" minOccurs="0">
             <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                   <xsd:enumeration value="not-accessible"/>
                   <xsd:enumeration value="accessible-for-notify"/>
                   <xsd:enumeration value="read-only"/>
                   <xsd:enumeration value="read-write"/>
                   <xsd:enumeration value="read-create"/>
                </xsd:restriction>
             </xsd:simpleType>
type="kalua:ModelElementReference"
minOccurs="0">
             <xsd:annotation>
                <xsd:documentation>
type="cmb:InitializationKind"/-->
type="xsd:boolean"/-->
type="xsd:string" minOccurs="0"/>
type="xsd:string" minOccurs="0"/>
type="kalua:ModelElementReference"
minOccurs="0"/>
base="xsd:string">
                                        <xsd:attribute
name="language"
type="xsd:normalizedString"/>
                                     </xsd:extension>
                                  </xsd:simpleContent>
type="kalua:ModelElementReference"/>
type="xsd:nonNegativeInteger"
default="0" minOccurs="0"/>
default="unbounded" minOccurs="0">
             <xsd:simpleType>
                <xsd:union memberTypes="xsd:nonNegativeInteger">
                   <xsd:simpleType>
                      <xsd:restriction base="xsd:string">
                         <xsd:enumeration value="unbounded"/>
                      </xsd:restriction>
                   </xsd:simpleType>
                </xsd:union>
             </xsd:simpleType>
type="kalua:annotation-property-typeType"
minOccurs="0" maxOccurs="unbounded"/>
type="kalua:annotable-typeType"
maxOccurs="unbounded"/>
ref="kalua:NamedElementAttributes"/>
type="xsd:boolean" default="true"/>
ref="kalua:NamedElementAttributes"/>
type="kalua:annotation-propertyType"
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
type="kalua:ModelElementReference"/>
minOccurs="0"/>
ref="kalua:NamedElementAttributes"/>
type="kalua:facet" id="minExclusive"/>
type="kalua:facet" id="minInclusive"/>
type="kalua:facet" id="maxExclusive"/>
type="kalua:facet" id="maxInclusive"/>
id="totalDigits">
             <xsd:complexType>
                <xsd:complexContent>
                   <xsd:restriction base="kalua:numFacet">
                      <xsd:attribute name="value"
type="xs:positiveInteger"
use="required"/>
type="kalua:numFacet" id="fractionDigits"/>
type="kalua:numFacet" id="length"/>
type="kalua:numFacet" id="minLength"/>
type="kalua:numFacet" id="maxLength"/>
type="kalua:facet" id="pattern"/>
type="kalua:ModelElementReference"/>
type="kalua:restrictionType"/>
type="kalua:unionType"/>
type="kalua:enumType"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
type="kalua:enum-literalType"
maxOccurs="unbounded"/>
type="xsd:QName" use="optional"/>
type="xs:nonNegativeInteger" use="required"/>
name="ethernet_csmacd">
               <presentation>ethernet-csmacd
               </presentation>
name="iso88023_csmacd">
               <presentation>iso88023-csmacd
               </presentation>
name="iso88024_tokenBus">
               <presentation>iso88024-tokenBus
               </presentation>
name="iso88025_tokenRing">
               <presentation>iso88025-tokenRing
               </presentation>
name="iso88026_man">
               <presentation>iso88026-man
               </presentation>
name="frame_relay">
               <presentation>frame-relay
               </presentation>
name="up"/>
name="down"/>
name="testing"/>
name="up"/>
name="down"/>
name="testing"/>
name="forwarding">
name="not_forwarding">
                  <presentation>not-forwarding
                  </presentation>
                  <description>
                  NOT acting as a gateway
                  </description>
name="up" value="1"/>
name="down" value="2"/>
name="testing" value="3"/>
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
            <eventTime>2007-07-08T00:01:00Z</eventTime>
            <rfc1213:linkDown>
               <ifIndex>1</ifIndex>
               <ifAdminStatus>
               <ifAdminStatus>1</ifAdminStatus>
                  <ifIndex>1</ifIndex>
               </ifAdminStatus>
               <ifOperStatus>
                  <ifOperStatus>2</ifOperStatus>
                  <ifIndex>1</ifIndex>
               </ifOperStatus>
            </rfc1213:linkDown>
