Tag = TBD1;
Name = "Current Time ";
Meaning = "Rough Current time" ;
Reference = "[This-document]";


Value = TBD2;
Description = "OPTION_CURRENT_TIME";
Reference= "[This-document]";
Type = TBD3
Description = "Current time option"
Reference = "[This document]"


