xmlns="urn:ietf:params:xml:ns:netconf:partial-lock:1.0"
message-id="135">
        <partial-lock>
            <select xmlns:rte="http://example.com/ns/route">
                /rte:routing/rte:virtualRouter[rte:routerName='router1']
            </select>
            <select xmlns:if="http://example.com/ns/interface">
                /if:interfaces/if:interface[if:id='eth1']
            </select>
         </partial-lock>
xmlns="urn:ietf:params:xml:ns:netconf:partial-lock:1.0"
message-id="135">
        <lock-id>127</lock-id>
        <locked-node xmlns:rte="http://example.com/ns/route">
            /rte:routing/rte:virtualRouter[rte:routerName='router1']
        </locked-node>
        <locked-node xmlns:if="http://example.com/ns/interface">
            /if:interfaces/if:interface[if:id='eth1']
        </locked-node>
message-id="136">
          <partial-unlock>
            <lock-id>127</lock-id>
          </partial-unlock>
xmlns="urn:ietf:params:xml:ns:netconf:partial-lock:1.0"
targetNamespace="urn:ietf:params:xml:ns:netconf:partial-lock:1.0"
elementFormDefault="qualified" attributeFormDefault="unqualified">

schemaLocation="urn:ietf:params:xml:ns:netconf:base:1.0"/>

maxOccurs="unbounded">
substitutionGroup="nc:rpcOperation"/>

substitutionGroup="nc:rpcOperation"/>

maxOccurs="unbounded">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:netconf:partial-lock:1.0"
message-id="102">
xmlns="urn:ietf:params:xml:ns:netconf:partial-lock:1.0"
message-id="102">
       <lock-id>1</lock-id>
       <locked-node xmlns:usr="http://example.com/users">
           /usr:top/usr:users
       </locked-node>
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
xmlns="urn:ietf:params:xml:ns:netconf:partial-lock:1.0"
message-id="104">
xmlns="urn:ietf:params:xml:ns:netconf:partial-lock:1.0"
message-id="104">
       <lock-id>2</lock-id>
       <locked-node xmlns:usr="http://example.com/users">
           /usr:top/usr:users/user[usr:name="Joe"]"
       </locked-node>
message-id="105">
