Res = 0x00 - Ignore this field on receipt and follow the
Res = 0x01 - Result code indicating that no response is
Res = 0x02 - Result code indicating that a response to the
Res = 0x03 - Set by receiver to indicate successful
Res = 0x4 - Set by receiver in the Response message if one
NA = 0,

NA = 0,

