URI           = scheme ":" app-specific [ "#" fragment ]

scheme        = "app"

app-specific  = "//" app-authority [ path-absolute ] [ "?" query ]

app-authority = uuid | ni | name | authority
uuid          = "uuid," UUID
ni            = "ni," alg-val
name          = "name," reg-name
