c= TN  RFC2543  +1-201-406-4090

c= TN  RFC2543  12014064090

c= TN X-mytype.mydomain.com  A*8-HELEN

media-field =         "m=" media space port ["/" integer]
                         space proto 1*(space fmt) CRLF
c= TN RFC2543 +1-201-406-4090
m= text 1  fax plain
a=fmtp:plain  uri:ftp://ftp.isi.edu/in-notes/rfc2468.txt
c= TN RFC2543 +1-201-406-4090
m= text 1  fax plain
a=fmtp:plain 
c= TN RFC2543 +1-201-406-4090
m= text 1  fax plain
a=fmtp:plain  opr:APPL.123.456

c= TN RFC2543 +1-201-406-4090
m= text 1  fax plain
a=fmtp:plain  uri:http://www.sun.com/index.html opr:

c= TN RFC2543 +1-201-406-4090
m= text 1  fax -

c= TN RFC2543 +1-201-406-4090
m= text 1  fax plain
a=fmtp:plain  spr:<Content-ID>

a=phone-context: <phone-context-ident>
phone-context-ident     =  network-prefix / private-prefix
network-prefix          =  intl-network-prefix / local-network-prefix
intl-network-prefix     =  "+" 1*DIGIT
local-network-prefix    =  1*DIGIT
excldigandplus          =  (0x21-0x2d,0x2f,0x40-0x7d))
private-prefix          =  1*excldigandplus 0*uric

c= TN   RFC2543  1-800-765-4321
a=phone-context:+972

c= TN   RFC2543  1-800-765-4321
a=phone-context:+1

c=TN RFC2543  123
a=phone-context:+97252

c= TN  RFC2543  321
a=phone-context:X-acme.com-23
c= TN  RFC2543 7-23-321

a=clir:<"true" | "false">

a=Q763-nature:  - indicates the "nature of address indicator".
                    The value MAY be any number between 0 and 127.
                    The following values are specified:

                "1" a subscriber number
                "2" unknown
                "3" a nationally significant number
                "4" an internationally significant number

a=Q763-plan:    - indicates the numbering plan to which the address
                    belongs. The value MAY be any number between 0 and
                    7. The following values are specified:

                "1" Telephone numbering plan (ITU-T E.164)
                "3" Data numbering plan (ITU-T X.121)
                "4" Telex numbering plan (ITU-T F.69)

a=Q763-INN      - indicates if routing to the Internal Network Number
                    is allowed. The value MUST be ONE of:

                "0" routing to internal network number allowed
                "1" routing to internal network number not
                              allowed

a=require:<attribute-list>

c= TN RFC2543 +1-201-406-4090
m= text 1 pager plain
a=fmtp:plain spr:17@mymessage.acme.com

c=...
i=3 pages of 5 sent
t=...

v=0
i=3 of 5 pages sent OK
c=TN  RFC2543  +12014064090
m=image 1 fax tif
a=fmtp:tif uri:http://tifsRus.com/yyyyyy.tif

v=0
o=- 2353687637 2353687637 IN IP4 128.3.4.5
s=R2C
i=Ironing Board Promotion
e=anon-1827631872@chinet.net
t=2353687637 0
m=audio 1  voice -
c=TN  RFC2543  +1-201-406-4090

v=0
o=- 2353687640 2353687640 IN IP4 128.3.4.5
s=marketing
e=john.jones.3@chinet.net
c= TN RFC2543  +1-201-406-4090
t=2353687640 0
m=audio 1  voice -

v=0
o=- 2353687660 2353687660 IN IP4 128.3.4.5
s=faxback
e=john.jones.3@chinet.net
t=2353687660 0
m=application 1 fax URI
c=TN  RFC2543  1-201-406-4091
a=fmtp:URI uri:http://localstore/Products/IroningBoards/2344.html

v=0
o=- 2353687660 2353687660 IN IP4 128.3.4.5
s=faxback
e=john.jones.3@chinet.net
t=2353687660 0
m=application 1 voice URI
c=TN  RFC2543  1-201-406-4090
a=fmtp:URI uri:http://localstore/Products/IroningBoards/2344.html
v=0
o=- 2353687680 2353687680 IN IP4 128.3.4.5
s=R2F
e=scott.petrack@chinet.net
t=2353687680 0
m=text 1 pager plain
c= TN  RFC2543  +972-9-956-1867
a=fmtp:plain spr:2@53655768
      

v=0
o=- 2353687700 2353687700 IN IP4 128.3.4.5
s=faxserver
e=scott.petrack@chinet.net
t=2353687700 0
m=image  1 fax  tif gif
c= TN  RFC2543  +972-9-956-1867
a=fmtp:tif  uri:http://petrack/images/tif/picture1.tif
a=fmtp:gif  uri:http://petrack/images/gif/picture1.gif
v=0
o=- 2353687720 2353687720 IN IP4 128.3.4.5
s=R2HC
e=scott.petrack@chinet.net

c= TN  RFC2543  +1-201-406-4091
t=2353687720 0
m=text  1  voice  plain
a=fmtp:plain   spr:2@53655768
m=text  1 voice plain
a=fmtp:plain  uri:http://www.your.com/texts/stuff.doc

v=0
o=- 2353687740 2353687740 IN IP4 128.3.4.5
s=R2FB
i=ISDN Price List
e=hank.wangford@newts.demon.co.uk
t=2353687740 0
m=text 1  fax -
c=TN  RFC2543  +44-1794-8331010

v=0
o=- 2353687760 2353687760 IN IP4 128.3.4.5
s=R2C
i=ISDN pre-sales query
e=hank.wangford@newts.demon.co.uk
c=TN  RFC2543  +44-1794-8331013
t=2353687760 0
m=audio 1  voice -

v=0
o=- 2353687780 2353687780 IN IP4 128.3.4.5
s=R2FB
i=Your documents
e=colin.masterton@sales.hh.bt.co.uk
t=2353687780 0
m=application 1  fax octet-stream
c=TN  RFC2543  +44-1794-8331010
a=fmtp:octet-stream uri:http://www.bt.co.uk/imgs/pipr.gif opr:
        spr:2@53655768
v=0
o=- 2353687800 2353687800 IN IP4 128.3.4.5
s=R2FB
i=NFL Final Scores
e=fred.football.fan@skynet.com
c=TN  RFC2543 +44-1794-8331013
t=2353687800 0
m=audio 1 voice x-pay
a=fmtp:x-pay opr:mci.com/md5:<crypto signature>

phone-context=+1
v=0
o=- 2353687820 2353687820 IN IP4 128.3.4.5
s=R2FB
i=NFL Final Scores
e=fred.football.fan@skynet.com
c=TN  RFC2543 +44-1794-8331010
t=2353687820 0
m=text 1 fax x-pay
a=fmtp:x-pay opr:mci.com/md5:<crypto signature>

phone-context=+1
v=0
o=- 2353687840 2353687840 IN IP4 128.3.4.5
s=R2FB
i=NFL Final Scores
e=fred.football.fan@skynet.com
c=TN  RFC2543 +44-1794-8331015
t=2353687840 0
m=text 1 pager x-pay
a=fmtp:x-pay opr:mci.com/md5:<crypto signature>

v=0
o=- 2353687860 2353687860 IN IP4 128.3.4.5
s=BillsRUs
i=Joe Pendleton's Phone Bill
e=agent.mulder@fbi.gov
c=TN  RFC2543  +1-202-833-1010
t=2353687860 0
m=text 1  fax x-files-id
a=fmtp:x-files-id opr:fbi.gov/jdcn-123@45:3des;base64,<signature>

connection-field    = ["c=" nettype space addrtype space
                        connection-address CRLF]
nettype = ("IN"/"TN")
addrtype = (INAddrType / TNAddrType)
INAddrType = ("IP4"/"IP6")
TNAddrType = ("RFC2543"/OtherAddrType)

OtherAddrType = (<X-Token>)
addr = (<FQDN> / <unicast-address> / TNAddr)
TNAddr = (RFC2543Addr/OtherAddr)
RFC2543Addr = (INPAddr/LDPAddr)

INPAddr = "+" <POS-DIGIT> 0*(("-" <DIGIT>)/<DIGIT>)
LDPAddr = <DIGIT> 0*(("-" <DIGIT>)/<DIGIT>)

OtherAddr = 1*<uric>
media-field = "m=" media <space> port <space> proto
                   1*(<space> fmt) <CRLF>
media = ("application"/"audio"/"image"/"text")
port = ("0" / "1")
proto = (INProto/TNProto)
INProto = 1* (<alpha-numeric>)
TNProto = ("voice"/"fax"/"pager")
fmt = (<subtype> / "-")
attribute-fields = *("a=" attribute-list <CRLF>)
attribute-list = 1(PINT-attribute / <attribute>)
PINT-attribute = (clir-attribute / q763-nature-attribute /
                   q763plan-attribute / q763-INN-attribute /
                   phone-context-attribute / tsp-attribute /
                   pint-fmtp-attribute / strict-attribute)

clir-attribute = clir-tag ":" ("true" / "false")

clir-tag = "clir"

q763-nature-attribute = Q763-nature-tag ":" q763-natures

q763-nature-tag = "Q763-nature"

q763-natures = ("1" / "2" / "3" / "4")

q763-plan-attribute = Q763-plan-tag ":" q763-plans

q763-plan-tag = "Q763-plan"

q763-plans = ("1" / "2" / "3" / "4" / "5" / "6" / "7")
q763-INN-attribute = Q763-INN-tag ":" q763-INNs

q763-INN-tag = "Q763-INN"

q763-INNs = ("0" / "1")

phone-context-attribute = phone-context-tag ":" phone-context-ident

phone-context-tag = "phone-context"

phone-context-ident = network-prefix / private-prefix

network-prefix = intl-network-prefix / local-network-prefix

intl-network-prefix = "+" 1*<DIGIT>

local-network-prefix = 1*<DIGIT>

private-prefix = 1*excldigandplus 0*<uric>

excldigandplus = (0x21-0x2d,0x2f,0x40-0x7d))
tsp-attribute = tsp-tag "=" provider-domainname

tsp-tag = "tsp"

provider-domainname = <domain>
pint-fmtp-attribute = "fmtp:" <subtype> <space> resolution
                      *(<space> resolution)
                      (<space> ";" 1(<attribute>) *(<space>
resolution = (uri-ref / opaque-ref / sub-part-ref)

uri-ref = uri-tag ":" <URI-Reference>
uritag = "uri"

opaque-ref = opr-tag ":" 0*<uric>

opr-tag = "opr"
sub-part-ref = spr-tag ":" <Content-ID>
spr-tag = "spr"

strict-attribute = "require:" att-tag-list

att-tag-list = 1(PINT-att-tag-list / <att-field> /
                    pint-fmtp-tag-list)
                  *(","
                    (PINT-att-tag-list / <att-field> /
                      pint-fmtp-tag-list)
                   )
PINT-att-tag-list = (phone-context-tag / clir-tag /
                       q763-nature-tag / q763-plan-tag /
                       q763-INN-tag)

pint-fmtp-tag-list = (uri-tag / opr-tag / spr-tag)

clir-parameter = clir-tag "=" ("true" / "false")

q763-nature-parameter = Q763-nature-tag "=" Q763-natures

q763plan-parameter = Q763-plan-tag "=" q763plans

q763-INN-parameter = Q763-INN-tag "=" q763-INNs

tsp-parameter = tsp-tag "=" provider-domainname

phone-context-parameter = phone-context-tag "=" phone-context-ident

SIP-param = ( <transport-param> / <user-param> / <method-param> /
                <ttl-param> / <maddr-param> / <other-param> )
PINT-param = ( clir-parameter / q763-nature-parameter /
                q763plan-parameter / q763-INN-parameter/
                tsp-parameter / phone-context-parameter )

URL-parameter = (SIP-param / PINT-param)
Require-header = "require:" 1(required-extensions)
                             *("," required-extensions)
required-extensions = ("org.ietf.sip.subscribe" /
                       "org.ietf.sdp.require")
