DUM = Duplicate delivery of a PUBLISH message;

QoS = PUBLISH quality of service;

RETAIN = PUBLISH retain flag.

     +------------------------------------------------------------+
     |   Bit  |  7  |  6  |  5  |  4  |    3   |  2  |  1  |   0  |
     +------------------------------------------------------------+
     | byte 1 |   Message Type  (3)   |DUM flag| QoS level |RETAIN|
     +------------------------------------------------------------+
     |        |  0  |  0  |  1  |  1  |    X   |  X  |  X  |   X  |
     +------------------------------------------------------------+
     | byte 2 |                Remaining Length                   |
     +------------------------------------------------------------+
                                    
               Figure 7.8 - PUBLISH message fixed header

