NS-MOP = RPL Non-storing Mode of Operation

S-MOP = RPL Storing Mode of Operation
Low=<5 per day, High=>5 per day; SM=Storing MOP, NSM=Non-Storing MOP

                       Table 2: RPL State variables

