AFI=25 for L2VPN).  Such modification is fully backwards compatible
AFI=25 for L2VPN).  Such modification is fully backwards compatible
comp1 = next_component(a);
comp2 = next_component(b);
common = MIN(MAC Address length (comp1),
                        MAC Address length (comp2));
cmp = MAC Address compare(comp1, comp2, common);
common =
                  MIN(component_length(comp1), component_length(comp2));
cmp = memcmp(data(comp1), data(comp2), common);
