charset=hexvalue=hexvalue): 
    
      S: <wait for connection on TCP port 25> 
      C: <open connection to server> 
      S: 220 mail.neteka.com -- Server SMTP (NeBOX v3.0) 
      C: EHLO mail.toronto.edu 
      S: 250-mail.neteka.com 
      S: 250-8BITMIME 
      S: 250 IMAX 
      C: MAIL FROM:<(UTF-8=E4=E8=AD=E6=96=87)@toronto.edu> CHARSET=UTF-8 
      S: 250 Address Ok. 
      C: RCPT TO:<edmon@neteka.com> 
      S: 250 edmon@neteka.com OK 
      C: DATA 
      ... 
    
