PktTsbpdTime = TsbpdTimeBase + PKT_TIMESTAMP + TsbpdDelay + Drift

TsbpdTimeBase = T_NOW - HSREQ_TIMESTAMP

TsbpdTimeBase = TsbpdTimeBase + MAX_TIMESTAMP + 1

pos = 0;  /* Current receiver buffer position */
i = 0;    /* Position of the next available in the receiver buffer
                packet relatively to the current buffer position pos */

i = next_avail();
PktTsbpdTime = delivery_time(i);

pos = i + 1;
