Ru = MD5(Pu + Z + Nu + Ns + Nr + Cu + Cs + Ts + Pu) 
     
Rs = MD5(Ps + Z + Nu + Ns + Nr + Cu + Cs + Ts + Ru + Ps) 
     
Ru = MD5(Kus + Z + Ns + Nu + Nr + Cs + Cu + Kus) 
     
Rs = MD5(Kus + Z + Nu + Ns + Nr + Cu + Cs + Kus) 
     
