EID = <roaming-EID>, RLOC-records:
RLOC = (RLE: xTR-A, xTR-B)
RLOC = (RLE: xTR-B, xTR-C, xTR-D, xTR-E)
RLOC = (RLE: xTR-E, xTR-F)

EID = <roaming-EID>, RLOC-records:
RLOC = (RLE: xTR-A, xTR-B, xTR-C, (RLE: xTR-X, xTR-Y, xTR-Z),
                  (RLE: xTR-I, xTR-J, xTR-K), xTR-D, xTR-E)

EID = <eid1>, RLOC-records:
RLOC = (afi=<dist-name>: "am-train-to-paris")
EID = <eid2>, RLOC-records:
RLOC = (afi=<dist-name>: "am-train-to-paris")
EID = <eid3>, RLOC-records:
RLOC = (afi=<dist-name>: "am-train-to-paris")

EID = "am-train-to-paris", RLOC-records:
RLOC = (afi=lcaf/RLE-type: xTR-A, xTR-B, xTR-C)

EID = "am-train-to-paris-passengers", RLOC-records:
RLOC = (afi=lcaf/afi-list-type: <eid1>, <eid2>, <eid3>)

