targetNamespace="urn:ietf:params:xml:ns:fee-0.7"
elementFormDefault="qualified">

maxOccurs="unbounded" />
minOccurs="0" />
minOccurs="0" />
maxOccurs="unbounded" />
minOccurs="0" maxOccurs="1" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" maxOccurs="1" />
maxOccurs="unbounded" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" />
maxOccurs="unbounded" />
minOccurs="0" maxOccurs="unbounded" />
maxOccurs="unbounded" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" />
minOccurs="0" />
minOccurs="0" />

maxOccurs="unbounded" />
minOccurs="0" maxOccurs="unbounded" />
minOccurs="0" />
minOccurs="0" />
maxOccurs="unbounded" />
minOccurs="0" />
minOccurs="0" />
default="1" />
