PT=PSFB and FMT=ICR.

PT=PSFB and FMT=ICN.

R=0: the media sender applies the image change successfully.

R=1: The values of the ICR message are invalid.

R=2: The media sender does not support the image change.

R=3: Reserved.

