destination='im:barney@example.com'
transID='1' />
target='pres:fred@example.com'
duration='86400' transID='2' />

target='pres:fred@example.com'
transID='1234'>
status='open' />
target='pres:fred@example.com'
transID='3' />
