entity-header  =  Content-Disposition   ; defined in RFC 3261
                  /  Content-Encoding      ; defined in RFC 3261
                  /  Content-Language      ; defined in RFC 3261
                  /  Content-Length        ; defined in RFC 3261
                  /  Content-Type          ; defined in RFC 3261
                  /  Event                 ; defined in RFC 3265
                  /  extension-header      ; defined in RFC 3261

Success             =/ "204"  ;  No Notification

         ; Success is defined in RFC3261.

message-header      =/ Suppress-If-Match

         ; message-header is defined in RFC3261.

Suppress-If-Match   =  "Suppress-If-Match" ":" entity-tag / "*"

         ; entity-tag is defined in RFC3903.
