P = 1482 bytes 
    
Class = 19 C_Type = 3 
    
Class= 19  C_type = 4 
    
Class = 19 C_Type = 5 
    
Class = SESSION, LSP_LAYER2_TUNNEL_IPV4 C-Type = 3 
    
Class = SESSION, LSP_LAYER2_TUNNEL_IPV6 C-Type = 4 
    

