VRID=1  +-----------+      +-----------+
H  =  Host computer
MR  =  Master Router
BR  =  Backup Router
                            *  =  IP Address
VRID=1  +-----------+      +-----------+  VRID=2
H  =  Host computer
MR  =  Master Router
BR  =  Backup Router
                            *  =  IP Address
