C-NUM = 193, C-Type = 4 (TBD by IANA)

        0                   1                   2                   3
        0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |                        LSR's Router ID                        |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |                    Interface ID (32 bits)                     |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |    Actions    |                Reserved                       |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       ~                           TLVs                                ~
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

      LSR's Router ID

         Unchanged from the definition in [RFC3477].

      Interface ID

         Unchanged from the definition in [RFC3477].

      Actions

        This field specifies how the LSP that is being set up is to be
        treated.

        The field has meaning only on a Path message. On a Resv message
        the field SHOULD be set to reflect the value received on the




        corresponding Path message, and MUST be ignored on receipt.

        The field is composed of bit flags as follows:

         -+-+-+-+-+-+-+-
        | | | |H|B|R|T|P|
         -+-+-+-+-+-+-+-

        P-flag (Private)
          0 means that the LSP is to be advertised as a link according
            to the settings of the other flags.
          1 means the LSP is to form a private link and is not to be
            advertised in the IGP, but is to be used according to the
            settings of the other flags.

        T-flag (TE link)
          0 means that the LSP is to be used as a TE link.
          1 means that the LSP is not to be used as a TE link. It may
            still be used as an IP link providing a routing adjacency as
            defined by the R-flag.

        R-flag (routing adjacency)
          0 means that the link is not to be used as a routing
            adjacency.
          1 means that the link is to be used to form a routing
            adjacency.

        B-flag (bundle)
          0 means that the LSP will not form part of a link bundle.
          1 means that the LSP will form part of a bundle. See Section
            3.3 for more details.

        H-flag (hierarchy/stitching)
          The use of an LSP as an H-LSP or as an S-LSP is usually
          implicit from the network technologies of the networks and the
          LSP, but this is not always the case (for example, in PSC
          networks).
          0 means LSP to be used as a hierarchical LSP.
          1 means LSP to be used as a stitching segment.

        Other bits are reserved for future use. They MUST be set to zero
        on transmission and SHOULD be ignored on receipt.

        Note that all defined bit flags have meaning at the same time.
        An LSP that is to form an FA would carry the Actions field set
        to 0x00. That is:
P=0 (advertised)
T=0 (TE link)




R=0 (not a routing adjacency)
B=0 (not a bundle)
H=0 (hierarchical LSP)

C-NUM = 193, C-Type = 2 (TBD by IANA)

        0                   1                   2                   3
        0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |               IPv4 Interface Address                          |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |    Actions    |                Reserved                       |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       ~                           TLVs                                ~
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

      IPv4 Interface Address

         The address assigned to the interface the sender applies to
         this LSP.

      Actions

        See Section 3.1.2.

     Reserved

        See Section 3.1.2.

     TLVs

        See Section 3.1.2.

C-NUM = 193, C-Type = 3 (TBD by IANA)

        0                   1                   2                   3
        0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |               IPv6 Interface Address (128 bits)               |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |               IPv6 Interface Address (continued)              |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |               IPv6 Interface Address (continued)              |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |               IPv6 Interface Address (continued)              |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |    Actions    |                Reserved                       |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       ~                           TLVs                                ~
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

      IPv6 Interface Address

         The address assigned to the interface the sender applies to
         this LSP.

      Actions

        See Section 3.1.2.

     Reserved

        See Section 3.1.2.

     TLVs

        See Section 3.1.2.

