Confidential-Access-Level = "Confidential-Access-Level" HCOLON
                                  local-access-level SEMI
                                  reflected-access-level
local-access-level        = (access-level SEMI access-mode)
reflected-access-level    = ("ref" EQUAL access-level SEMI
                                  reflected-mode)
access-level              = (1*2DIGIT ; 0 to 99)
access-mode               = ("mode" EQUAL mode-param)
reflected-mode            = ("rmode" EQUAL mode-param)
mode-param                = (fixed / variable)

