token = store[issuer.id].pop()
req = Redeem(token, info)

                                  req
                           ------------------>

                                  if (dsIdx.includes(req.data)) {
                                    raise ERR_DOUBLE_SPEND
                                  }
resp = Verify(pkS, skS, req)
