pub3=<loc-core>/<crypted>/<attributes>@example.com

local-part       = tag-type "=" loc-core
                            *( "/" [tag-val-tag "="] tag-val )

tag-type         = 1*( DIGIT / ALPHA / "-" )
                            ; specific, registered validation scheme

loc-core         = {original local-part value}

tag-val-tag      = {label for specific value}

tag-val          = 1*( DIGIT / ALPHA / "-" )
                            ; the validation data


tag-type       = "prvs"
                           ; simple private signature

tag-val        =  K DDD SSSSSS

K              =  1DIGIT
                           ; key number, to allow key rotation

DDD            =  3DIGIT
                           ; day number, low three digits of
                           ; the number of days since 1970
                  			; when the address will expire

SSSSSS         =  6HEXDIG
                           ; hex of the first three bytes of the
                           ; SHA-1 HMAC of <hash-source> and a key

hash-source    =  K DDD <orig-mailfrom>

orig-mailfrom  =  {original RFC2821.MailFrom address}


