P_addr == Originator Address

P_network_addr == Network Address

P_prefix_length == Prefix Length

P_time = current time + validity time

P_gateway_addr = Originator Address

P_network_addr = Network Address

P_prefix_length = Prefix Length

P_time = current time + validity time


I_iface_addr == Secondary Address, AND

I_main_addr == Originator Address,

I_time = current time + validity time.

I_iface_addr = Secondary Address,

I_main_addr = Originator Address,

I_time = current time + validity time.


PA_INTERVAL           = 5 seconds

MID_INTERVAL          = 5 seconds

PA_HOLD_TIME          = 3 x PA_INTERVAL

MID_HOLD_TIME         = 3 x MID_INTERVAL
