I==1.  Set to a monotonically-incrementing 32-bit value for each
V==1.  Covers the leading 128 bytes of the packet beginning with
DF==0, the ITE should set DF=1 and re-calculate the IPv4 header
MTU==0 and length 1450, it can set PMTU=1400, etc.)

USE_DF=FALSE).  The ITE may instead enable stateful MTU determination
DF=1 in the outer IP header.  The ITE can then cache the size of the
USE_TRAIL=FALSE to determine whether the path still requires a
DF=1 and re-calculate the IPv4 header checksum while transcribing the
