qop=auth-int, it also provides integrity protection of the response.
A2 = ":" digest-uri-value

A2 = ":" digest-uri-value ":" H(entity-body)

request-digest = <"> < KD ( unq(username-value)

      ":" unq(realm-value)

      ":" unq(nonce-value)

      ":" nc-value

      ":" unq(cnonce-value)

      ":" unq(qop-value)
      ":" H(A2) ) > <">


A2 = Method ":" digest-uri-value

A2 = Method ":" digest-uri-value ":" H(entity-body)

nonce="ea9c8e88df84f1cec4341ae6cbe5a359",
opaque="", stale=FALSE, algorithm=rsa-sha1
nonce="ea9c8e88df84f1cec4341ae6cbe5a359", opaque="", qop=auth,
uri="sips:ss2.biloxi.example.com", algorithm=rsa-sha1,
cnonce="ea9c8e88df84f1cec4341ae6cbe5a359",
response="dfe56131d1958046689d83306477ecc"
response-digest="dfe56131d1958046689d83306477ecc",
cnonce="ea9c8e88df84f1cec4341ae6cbe5a359"
