authentication = data origin authentication combined with
                            connectionless message integrity - a typical
                            IPSec service
optional =       security services to be employed only if it is
                            explicit required by security policy.

