entity="pres:someone@example.com">

     <tuple id="joi9877866786ua9">
       <status>
         <basic>open</basic>
       </status>
       <sc:servcaps>
         <sc:audio>true</sc:audio>
         <sc:video>false</sc:video>
         <sc:message>true</sc:message>
         <sc:duplex>
           <sc:supported>
             <sc:full/>
           </sc:supported>
         </sc:duplex>
         <sc:description>
           Example service
         </sc:description>
         <sc:priority>
           <sc:supported>
             <sc:lowerthan maxvalue="10"/>
           </sc:supported>
         </sc:priority>
         <sc:methods>
           <sc:supported>
             <sc:INVITE/>
             <sc:ACK/>
             <sc:BYE/>
           </sc:supported>
         </sc:methods>
         <sc:scehems>
          <sc:supported>
           <sc:s>sip</sc:s>
          </sc:supported>
         </sc:scehems>
       </sc:servcaps>
       <contact>sip:someone@example.com</contact>
     </tuple>
     <dev:device id="jv3095qj1jv8a">
       <dev:status>
         <dc:devcaps>
           <dc:mobility>
             <dc:supported>
               <dc:mobile/>
             </dc:supported>
           </dc:mobility>
         </dc:devcaps>
       </dev:status>
     </dev:device>
elementFormDefault="qualified"
attributeFormDefault="unqualified">

    <!-- This import brings in the XML language
        attribute xml:lang-->
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
schemaLocation="http://www.w3.org/2001/xml.xsd"/>

minOccurs="0"/>
type="tns:applicationtype" minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
type="tns:descriptiontype" minOccurs="0"/>
type="tns:event-packagestype" minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded" minOccurs="1"/>
maxOccurs="unbounded" minOccurs="1"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
elementFormDefault="qualified"
attributeFormDefault="unqualified">

    <!-- This import brings in the XML language
        attribute xml:lang-->
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
schemaLocation="http://www.w3.org/2001/xml.xsd"/>

minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
content="text/html;charset=iso-8859-1"/>
content="text/html;charset=iso-8859-1"/>
