function => NBR for the flow
capacity      => network
capacity    => network
x = 4.5 - ln(MBR(i,j)/NBR(i))/ln(2)   

alpha = 5/K_n                                                (4)

M_rt  = the number of cells in the rt-buffer
K_rt  = the number of buffer places in the rt-buffer
M_nrt = the number of cells in the nrt-buffer
K_nrt = the number of buffer places in the nrt-buffer

x = (x_rt + x_nrt)           (a)
x = sqrt(x_rt^2 + x_nrt^2)   (b)                             (5)
x = max(x_rt, x_nrt)         (c)
x_rt = M_rt/K_rt
x_nrt = M_nrt/K_nrt

