utilization = ---------
                                    UA + PA

UA = M * d^(L-1)

PA = M * d^(L-1) * h

utilization = -----------
                                  (1+h)^(L-1)

L=3.  Note that in our analysis the lower level represents the level
