href="http://example.com/entries">
       <service name="Photos" class="media feed"
href="http://example.com/photos"/>
href="http://example.com/drafts"/>
start = app

app = element app {
     anyAttribute*,
     (service* & anyElement*)
service = element service {
     (nameAtt | classAtt | hrefAtt), anyAttribute*,
     (service* & anyElement*)
nameAtt = attribute name { text }
hrefAtt = attribute href { text }
classAtt = attribute class { text }

anyElement = element * { (anyAttribute | text | anyElement)* }
anyAttribute = attribute * { text }
