n = pq .

EB = 00 || BT || PS || 00 || D .           (1)

x =  SUM  2^(8(k-i)) EBi .              (2)
i = 1

y = x^c mod n,  0 <= y < n .
y =  SUM  2^(8(k-i)) EDi .              (3)
i = 1

x = y^c mod n,  0 <= x < n .

