RESTRICTEDACCESS-param = ; no parameter allowed
RESTRICTEDACCESS-value = boolean

ADMISSIONINFO-param = "VALUE=uri" / any-param
ADMISSIONINFO-value = uri

ACCESSIBILITYINFO-param = "VALUE=uri" / any-param
ACCESSIBILITYINFO-value = uri

CAPACITY-param = "VALUE=integer" / any-param
CAPACITY-value = integer

INVENTORYLIST-param = "VALUE=text" / any-param
INVENTORYLIST-value = text

INVENTORYURL-param = "VALUE=uri" / any-param
INVENTORYURL-value = uri
RESOURCEOWNER-param = "VALUE=uri" / any-param
RESOURCEOWNER-value = uri

RESOURCEMANAGER-param = "VALUE=uri" / any-param
RESOURCEMANAGER-value = uri

MULTIBOOK-param = "VALUE=integer" / any-param
MULTIBOOK-value = integer

MAXINSTANCES-param = "VALUE=integer" / any-param
MAXINSTANCES-value = integer

BOOKINGWINDOWSTART-param = "VALUE=text" / any-param
BOOKINGWINDOWSTART-value = text

BookingWindowEnd = BwE,
BOOKINGWINDOWEND-param = "VALUE=text" / any-param
BOOKINGWINDOWEND-value = text
AUTOSCHEDULE-param = "VALUE=boolean" / any-param
AUTOSCHEDULE-value = "TRUE" / "FALSE"

APPROVALINFO-param = "VALUE=uri" / any-param
APPROVALINFO-value = uri

SCHEDADMIN-param = "VALUE=uri" / any-param
SCHEDADMIN-value = uri

NOCOST-param = ; no parameter allowed
NOCOST-value = boolean

COSTINFO-param = "VALUE=uri" / any-param
COSTINFO-value = uri
