VRK = prf+ (K, S), where,

K = EMSK and

S = VRK Label

VRK_name = NDF-64( EAP Session-ID, VRK Label )

VMSK = prf+ (K, S), where,

K = VRK and

S = Server ID || Domain Name

VMSK_name = NDF-64( EAP Session-ID, Server ID || Domain Name )

rRK = prf+ (K, S), where,

K = VMSK and

S = rRK Label

