M = (Length_of_ACK_Info_Entry - 8) / 2.

Announced_Multicast_Group=240.1.2.4,
Dests=(Cnt=4,Dest_ID=(M1,M2,M3,M4)))

Total_PDUs=2,
Dests=(Cnt=4,LDES=0,Dest_ID=((M1,100),(M2,78),(M3,11),(M4,15))))

Data="First_N_octets_of_message")

Data="Remaining_octets_of_message")

ACK_Info=(M0,9876,0)))

ACK_Info=(M0,9876,1,0)))
Total_PDUs=2,
Dests=(Cnt=3,LDES=0,Dest_ID=((M2,78),(M3,11),(M4,15))))

Data="First_N_octets_of_message")

ACK_Info=(M0,9876,0)))

ACK_Info=(M0,9876,0)))

Total_PDUs=2, Dests=( Cnt=1,LDES=0,Dest_ID=((M4,15))))

Data="First_N_octets_of_message")

Data="Remaining_octets_of_message")

Total_PDUs=2, Dests=(Cnt=0,LDES=0,Dest_ID=()))

ctmp = len - offset - 1 ;
pls = buffer + len;
c0 = c1 = 0;
hpp = buffer;

cl0 = c0;
cl1 = c1;
