rtcweb-media-constraint = media-type "-" constraint-type "-" constraint
media-type              = "audio" / "video"
constraint-type         = "min" / "max" / "enum"
constraint              = ALPHA 0*constraint-char
constraint-char         = ALPHA / DIGIT / "-"


   Constraint names are case-sensitive.

   A registration request MUST include the following information:

   o  The constraint name to be registered
   o  Name and Email address of a contact person for the registration
   o  Organization or individuals having the change control
   o  Reference(s) to the specification(s) defining the constraint

