type = disposition-notification.

MDN-request-header = "Disposition-notification-to" ":"
                         mail-address

Disposition-notification-options =
         "Disposition-Notification-Options" ":"
         disposition-notification-parameters

disposition-notification-parameters =
                       parameter *(";" parameter)
parameter = attribute "=" importance ", " 1#value"

importance = "required" | "optional"

signed-receipt-protocol=optional, <protocol symbol>;
signed-receipt-micalg=optional, <micalg1>, <micalg2>,...;

signed-receipt-protocol=optional, pkcs7-signature;
signed-receipt-micalg=optional, sha1, md5

micalg=sha1; protocol="application/pkcs7-signature"

oTB0NZQ0xPTkUxDDAKBgNVBAsTA04vQTEQMA4GA1UEBxMHU=

protocol = "application/pkcs7-signature" see the "S/MIME
