lang=<lang-code>  OPTIONAL, but MAY occur multiple times.

tzid=<identifier>  OPTIONAL, and MAY occur multiple times.  MUST
         NOT be present if the "changedsince" parameter is present.  The
         value of the "dtstamp" member in the response applies to the
         entire set of data, rather than the subset requested with the
         "tzid" query parameter, and allows the client to determine if
         it needs to refresh its full set of time zone data.

format=<media-type>  OPTIONAL, but MUST occur only once.

lang=<lang-code>  OPTIONAL, but MAY occur multiple times.

tzid=<identifier>  REQUIRED, and MUST occur only once.

truncate=<date-time,date-time>  OPTIONAL, and MUST occur only
         once.  See Section 5.9 for details.

tzid=<identifier>  REQUIRED, but MUST occur only once.

lang=<lang-code>  OPTIONAL, but MAY occur multiple times.

start=<date-time>:  REQUIRED, but MUST occur only once.  Specifies
         the inclusive UTC date-time value for the start of the period
         of interest.

end=<date-time>:  OPTIONAL, but MUST occur only once.  If present,
         specifies the exclusive UTC date-time value for the end of the
         period of interest.  If "end" is omitted, the value is the
         "start" parameter value plus 10 years.  Note that this is the
         exclusive end value - i.e., it represents the date just after
         the range of interest. e.g., if a client wants the expanded
         date just for the year 2014, it would use a start value of
         "2014-01-01T00:00:00Z" and an end value of
         "2015-01-01T00:00:00Z".  An error occurs if the end value is
         less than or equal to the start value.

pattern=<text>  REQUIRED, but MUST occur only once.

lang=<lang-code>  OPTIONAL, but MAY occur multiple times.

tzuntil      = "TZUNTIL" tzuntilparam ":" date-time CRLF

tzuntilparam = *(";" other-param)

tzid-alias-of    = "TZID-ALIAS-OF" tzidaliasofparam ":"
                           [tzidprefix] text CRLF

tzidaliasofparam = *(";" other-param)

