answer="not-invited|not-answered|rejected|attempting|accepted">
                attendee_as_name_or_email</ATTENDEE>...
delay="+-seconds">UID_(sub)task UID_(sub)task</GLUE>...
o  = - set only these tags;

SPAM=YES JUNK OWNER=RAI.

