m=audio 49170 RTP/AVP 0
a=humintlang-send:en
a=humintlang-recv:en

m=video 51372 RTP/AVP 31 32
a=humintlang-send:ase*
a=humintlang-recv:ase*

m=audio 49250 RTP/AVP 20
a=humintlang-send:es*
a=humintlang-recv:es*
a=humintlang-send:eu*
a=humintlang-recv:eu*
a=humintlang-send:en*
a=humintlang-recv:en*

m=audio 49250 RTP/AVP 20
a=humintlang-send:es
a=humintlang-recv:es

m=audio 49250 RTP/AVP 20
a=humintlang-send:it
a=humintlang-recv:it

m=text 45020 RTP/AVP 103 104
a=humintlang-send:gr
a=humintlang-recv:gr

m=video 51372 RTP/AVP 31 32
a=humintlang-send:aed*

m=text 45020 RTP/AVP 103 104
a=humintlang-send:sp
a=humintlang-send:pt*

m=audio 49250 RTP/AVP 20
a=humintlang-recv:sp
a=humintlang-recv:pt*

m=text 45020 RTP/AVP 103 104
a=humintlang-recv:sp

m=audio 49250 RTP/AVP 20
a=humintlang-send:sp

m=text 45020 RTP/AVP 103 104
a=humintlang-send:en
a=humintlang-send:sp

m=audio 49250 RTP/AVP 20
a=humintlang-recv:en
a=humintlang-recv:sp*

m=video 51372 RTP/AVP 31 32

m=text 45020 RTP/AVP 103 104
a=humintlang-recv:sp

m=audio 49250 RTP/AVP 20
a=humintlang-send:sp

m=video 51372 RTP/AVP 31 32
humintlang-value =  Language-Tag [ asterisk ]

                          ; Language-Tag as defined in BCP 47

asterisk         =  "*"



