RLOC=IP_A //                  \\ RLOC=IP_B
                            +---+--+              +-+--+--+
                      .--.-.|xTR A |'.-.         .| xTR B |.-.
EID=            EID=<IID1,MAC_W>         EID=
