authPasswordValue = w scheme s [authInfo] s authValue w
scheme = <an IA5 string of uppercase letters, numbers,
             and "-", "_", and "/">
authInfo = schemeSpecificValue
authValue = schemeSpecfiicValue
schemeSpecificValue = <an IA5 printable string
                          not containing "$" or " ">
s = w sep w
w = *sp
sep = "$" ; an IA5 dollar sign (36)
sp = " "     ; an IA5 space (20)

