strict="false">
xmlns="urn:ietf:params:xml:ns:simple-filter"
entity="pres:user@example.com">
code="lowQuality">
targetNamespace="urn:ietf:params:xml:ns:geopriv:lq"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

source="urn:ietf:params:xml:schema:geopriv:lq">
minOccurs="0" maxOccurs="unbounded"/>
default="false"/>
default="95"/>
