stack = <1023,2099,1018>.  Label 1023 corresponds to the node-SID
stack = <1018>.  Label 1018 corresponds to the node-SID label for
label=3154 corresponds to FEC 10.0.0.31/32, so it swaps the label
FEC=10.0.0.85, and forwards the packet to next-hop R84.  The packet
