Pmin=0, meaning with average queue length below Qmin, there will be no
diffServQMinRateRel = diffServQMinRateAbs * 10,000,000/ifSpeed

diffServQMinRateRel = diffServQMinRateAbs * 10 / ifHighSpeed"
diffServQMinRateAbs = ifSpeed * diffServQMinRateRel/10,000,000

diffServQMinRateAbs = ifHighSpeed * diffServQMinRateRel / 10"
diffServQMaxRateRel = diffServQMaxRateAbs * 10,000,000/ifSpeed

diffServQMaxRateRel = diffServQMaxRateAbs * 10 / ifHighSpeed"
diffServQMaxRateAbs = ifSpeed * diffServQMaxRateRel/10,000,000

diffServQMaxRateAbs = ifHighSpeed * diffServQMaxRateRel / 10"
