tagURI = "tag:" authorityName "," date ":" specific [ "#" fragment ]

authorityName = ( web-host / addr-spec )
web-host = ( host / userinfo-host-post )
userinfo-host-port = [ userinfo "@" ] host ":" port

