GCType=0    (8 bytes)       (4 bytes)

        +--------+--------+--------+--------
        |     Key Type    |      Key ...
        +--------+--------+--------+--------



GCType=1    (8 bytes)       (4 bytes)

        +--------+--------+--------+--------
        |     Key Type    |      Key ...
        +--------+--------+--------+--------



GCType=2    (8 bytes)       (4 bytes)       (8 bytes)


GCType=3    (8 bytes)       (4 bytes)

        +----- ... -----+--------+--------
        |     Nonce     |      Token ...
        +----- ... -----+--------+--------
            (8 bytes)        (optional)


GCType=4    (8 bytes)       (4 bytes)       (variable)


GCType=5    (8 bytes)       (4 bytes)       (variable)


