authority="example.com" registryType="dreg1"
entityClass="iris"
entityName="id" >
authority="example.com" registryType="dreg1"
entityClass="iris" entityName="limits">
authority="example.com" registryType="dreg1"
entityClass="local"
entityName="notice" >
entityName="one" and a child element <bar>two</bar>, the server is to
xmlns="urn:ietf:params:xml:ns:iris1"
authority="iana.org" registryType="dreg1"
entityClass="iris"
entityName="id" >
authority="iana.org" registryType="dreg1"
entityClass="local"
entityName="notice">
authority="example.com" registryType="dreg1"
entityClass="iris"
entityName="id"/>
authority="iana.org" registryType="dreg1"
entityClass="iris" entityName="id"/>
authority="iana.org" registryType="dreg1"
entityClass="local"
entityName="notice" >
targetNamespace="urn:ietf:params:xml:ns:iris1"
elementFormDefault="qualified" >

name="control"
type="iris:controlType"
minOccurs="0"
maxOccurs="1" />
name="searchSet"
type="iris:searchSetType"
minOccurs="1"
maxOccurs="unbounded" />
name="reaction"
type="iris:reactionType"
minOccurs="0"
maxOccurs="1" />
name="resultSet"
type="iris:resultSetType"
minOccurs="1"
maxOccurs="unbounded" />
name="bags"
type="iris:bagsType"
minOccurs="0"
maxOccurs="1" />
name="searchSetType" >
name="bag"
type="iris:bagType"
minOccurs="0"
maxOccurs="1" />
name="lookupEntity"
type="iris:lookupEntityType" />
ref="iris:query" />
name="resultSetType" >
name="answer"
minOccurs="1"
maxOccurs="1">
ref="iris:result"
minOccurs="0"
maxOccurs="unbounded" />
ref="iris:entity"
minOccurs="0"
maxOccurs="unbounded" />
ref="iris:searchContinuation"
minOccurs="0"
maxOccurs="unbounded" />
name="additional"
minOccurs="0"
maxOccurs="1">
ref="iris:result"
minOccurs="1"
maxOccurs="unbounded" />
minOccurs="0"
maxOccurs="1" >
name="insufficientResources"
type="iris:codeType" />
name="invalidName"
type="iris:codeType" />
name="invalidSearch"
type="iris:codeType" />
name="queryNotSupported"
type="iris:codeType" />
name="limitExceeded"
type="iris:codeType" />
name="nameNotFound"
type="iris:codeType" />
name="permissionDenied"
type="iris:codeType" />
name="bagUnrecognized"
type="iris:codeType" />
name="bagUnacceptable"
type="iris:codeType" />
name="bagRefused"
type="iris:codeType" />
ref="iris:genericCode"/>
name="controlType">
namespace="##any"
processContents="skip"
minOccurs="1"
maxOccurs="1" />
name="reactionType">
namespace="##any"
processContents="skip"
minOccurs="1"
maxOccurs="1" />
name="queryType" />

name="query"
type="iris:queryType"
abstract="true" />

name="lookupEntityType" >
name="registryType"
type="anyURI"
use="required" />
name="entityClass"
type="token"
use="required" />
name="entityName"
type="token"
use="required" />
name="resultType">
name="authority"
use="required"
type="token" />
name="resolution"
type="token" />
name="registryType"
use="required"
type="anyURI" />
name="entityClass"
use="required"
type="token" />
name="entityName"
use="required"
type="token" />
name="temporaryReference"
default="false"
type="boolean" />
name="result"
type="iris:resultType"
abstract="true" />

name="codeType">
minOccurs="0"
maxOccurs="unbounded">
name="explanation">
base="string">
use="required"
name="language"
type="language" />
name="genericCode"
type="iris:codeType"
abstract="true" />

name="entityType">
name="displayName"
minOccurs="0"
maxOccurs="unbounded">
base="string">
name="language"
use="required"
type="language" />
name="authority"
use="required"
type="token" />
name="resolution"
type="token" />
name="registryType"
use="required"
type="anyURI" />
name="entityClass"
use="required"
type="token" />
name="entityName"
use="required"
type="token" />
name="referentType"
use="required"
form="qualified"
type="iris:referentTypeType" />
name="temporaryReference"
default="false"
type="boolean" />
name="bagRef"
type="IDREF" />
name="entity"
type="iris:entityType" />

name="referentTypeType">
memberTypes="QName iris:anyLiteralType" />
name="anyLiteralType">
base="string">
value="ANY" />
name="searchContinuationType">
name="bagRef"
type="IDREF" />
name="authority"
type="token"
use="required" />
name="resolution"
type="token" />
name="searchContinuation"
type="iris:searchContinuationType" />

name="bagsType">
name="bag"
minOccurs="1"
maxOccurs="unbounded">
base="iris:bagType">
use="required"
name="id"
type="ID" />
name="bagType">
namespace="##any"
processContents="skip"
minOccurs="1"
maxOccurs="1" />
name="seeAlso"
type="iris:entityType" />

name="serviceIdentificationType">
base="iris:resultType">
name="authorities"
minOccurs="1"
maxOccurs="1">
name="authority"
type="token"
minOccurs="1"
maxOccurs="unbounded" />
name="operatorName"
type="string"
minOccurs="0"
maxOccurs="1" />
name="eMail"
type="string"
minOccurs="0"
maxOccurs="unbounded" />
name="phone"
type="string"
minOccurs="0"
maxOccurs="unbounded" />
ref="iris:seeAlso"
minOccurs="0"
maxOccurs="unbounded" />
name="serviceIdentification"
type="iris:serviceIdentificationType"
substitutionGroup="iris:result" />

name="limitsType">
base="iris:resultType">
name="totalQueries"
minOccurs="0"
maxOccurs="1" >
ref="iris:timeLimitsGroup"
minOccurs="1"
maxOccurs="4" />
name="totalResults"
minOccurs="0"
maxOccurs="1" >
ref="iris:timeLimitsGroup"
minOccurs="1"
maxOccurs="4" />
name="totalSessions"
minOccurs="0"
maxOccurs="1" >
ref="iris:timeLimitsGroup"
minOccurs="1"
maxOccurs="4" />
name="otherRestrictions"
minOccurs="0"
maxOccurs="1">
name="description"
minOccurs="0"
maxOccurs="unbounded">
base="string">
name="language"
type="language"
use="required" />
ref="iris:seeAlso"
minOccurs="0"
maxOccurs="unbounded" />
name="limits"
type="iris:limitsType"
substitutionGroup="iris:result" />

name="timeLimitsGroup">
name="perSecond"
type="nonNegativeInteger" />
name="perMinute"
type="nonNegativeInteger" />
name="perHour"
type="nonNegativeInteger" />
name="perDay"
type="nonNegativeInteger" />
name="simpleEntityType">
base="iris:resultType">
name="property"
minOccurs="1"
maxOccurs="unbounded">
base="string">
name="name"
type="string"
use="required" />
name="language"
type="language"
use="required" />
name="uri"
type="anyURI" />
name="simpleEntity"
type="iris:simpleEntityType"
substitutionGroup="iris:result" />

name="onlyCheckPermissions" >
name="standardReaction" >
name="controlAccepted">
name="controlDenied">
name="controlDisabled">
name="controlUnrecognized">
name="serializedReferralType">
name="authority"
use="required"
type="token" />
name="resolution"
type="token" />
name="registryType"
type="anyURI"
use="required" />
name="entityClass"
type="token"
use="required" />
name="entityName"
type="token"
use="required" />
ref="iris:searchContinuation" />
ref="iris:entity" />
name="serialization">
minOccurs="1"
maxOccurs="unbounded">
ref="iris:result" />
name="serializedReferral"
type="iris:serializedReferralType" />
iris-uri           = scheme ":" registry-urn "/"
                          [ resolution-method ] "/" authority
                          [ "/" entity-class "/" entity-name ]
scheme             = "iris"
authority          = // as specified by RFC2396
registry-urn       = // as specified by IRIS
resolution-method  = *(unreserved | escaped)
entity-class       = *(unreserved | escaped)
entity-name        = *(unreserved | escaped)
unreserved         = // as specified by RFC2396
escaped            = // as specified by RFC2396

