S = Size of LSA storm, i.e., the number of LSAs in it.  Also, it is
L = Link adjacency of the node under consideration.

t1 = Time to send or receive one IGP packet over an interface (the
t2 = Time to do one SPF calculation. For large networks, this time
t2 = 200 ms.

Hi = Hello interval (the gap between successive Hello messages on
Si = Minimum interval between successive SPF calculations.

ro = Rate at which non-IGP work comes to the node (e.g., forwarding
T = Total work brought in to the node during the LSA storm.  For
T = 2*S*L*t1      (1)

T2 = Time period over which the work comes. Due to differences in
T2 = A + B*T    (2)

A = 10 ms and B = 0.1.

D = Maximum delay experienced by a Hello packet during the LSA
D = T - T2 + max(1,2*T2/Hi)*t1 + max(1,T2/Si)*t2 + ro*T2     (3)

Dmax = Maximum allowed value of D, i.e., if D exceeds this value
Dmax = 3*Hi     (4)

