ANNOTATION = KEY EQUALS VALUE
KEY = ITEM
VALUE = ITEM
ITEM = BLANK DQUOTE STR DQUOTE BLANK
BLANK = 0*EMPTY
EMPTY = SPACE / HTAB
HTAB = %x09 ; horizontal tab
STR = 0*UTF8

fedfsFsnUuid=f81d4fae-7dec-11d0-a765-00a0c91e6bf6,o=fedfs
fedfsFsnUuid=f81d4fae-7dec-11d0-a765-00a0c91e6bf6,o=fedfs
fedfsFsnUuid=f81d4fae-7dec-11d0-a765-00a0c91e6bf6,o=fedfs
nce_list = empty
nce = prepend the fedfsNcePrefix value to $BAR
fsnUuid=f81d4fae-7dec-11d0-a765-00a0c91e6bf6,o=fedfs
fsnUuid=f81d4fae-7dec-11d0-a765-00a0c91e6bf6,o=fedfs
