targetNamespace="urn:net:alaxala:oan:onapi:commons:netmod:1.1"
minOccurs="0">
maxOccurs="unbounded" minOccurs="0">
maxOccurs="unbounded" minOccurs="0">
maxOccurs="unbounded" minOccurs="0">
maxOccurs="unbounded" minOccurs="0">
maxOccurs="unbounded" minOccurs="0">
maxOccurs="1" minOccurs="0">
maxOccurs="1" minOccurs="0">
maxOccurs="1" minOccurs="0">
type="nm1_0:MacAddress" maxOccurs="1" minOccurs="0">
maxOccurs="1" minOccurs="0">
minOccurs="0">
maxOccurs="1" minOccurs="1">
maxOccurs="1" minOccurs="0">
type="nm1_0:IPV4Address" maxOccurs="1" minOccurs="0">
maxOccurs="1" minOccurs="0">
maxOccurs="1" minOccurs="0">
maxOccurs="1" minOccurs="0">
maxOccurs="1" minOccurs="0">
maxOccurs="1" minOccurs="0">
maxOccurs="1" minOccurs="0">
minOccurs="0">
maxOccurs="1" minOccurs="0">
type="nm1_0:IPV6Address" maxOccurs="1" minOccurs="0">
minOccurs="0">
type="nm1_1:FlowLayer3v6ExtendedType">
maxOccurs="unbounded" minOccurs="0">
minOccurs="0">
maxOccurs="unbounded" minOccurs="0">
