alternative=clm
                                 Figure 2

TYPE = number for this IPv4 option

LENGTH = total length of the option in bytes

A = anonymity bit: if this bit is set the destination addresses for
U = unicast transformation bit: if this bit is set a router is
RES = Reserved.

P = port bit: if this bit is set the packet will contain a (encoded)
D = DSCP bit: if this bit is set the packet will contain a (encoded)
BITMAP = every destination has a corresponding bit in the bitmap to
VERSION = CLM version number

LENGTH = length in bytes of the CLM header.

CHECKSUM = it is not clear yet whether a checksum is needed (ffs).
index=routing_table_root;     /* routing table entry point */
skip=0;                       /* flag used to skip over irrelevant
                                  * parts of the compound address */
len=LEN(meta);              /* number of non-meta symbols that
                                  * follow */
skip=stack_pointer;   /* skip to end of this suffix */
skip=0;                   /* we've skipped the list_element */
index=stack_pointer;      /* take the index on top of the stack */
X       = unused
sym     = meta symbol
             00 = open bracket
             01 = close bracket
             10 = comma
             11 = close bracket followed by comma

length  = number of bits of the address_fragment (symbol) following this
             meta symbol.



                               References


