version="1" state="partial">
duration-registered="3210">
version="1" state="partial">
duration-registered="190">
version="1" state="partial">
duration-registered="282">
event-param =/ batch-param

batch-param = "batch" EQUAL 1*DIGIT
