port="5353" ux="Legacy Resolver" )
port="5353" esniconfig="..."
ux="Preferred Example's Choice" )
port="5353" esniconfig="..." ux= )
port="5353" esniconfig="..." ux= )
port="5353" ux="Legacy Resolver" )
port="5353" esniconfig="..."
ux="Preferred Example's Choice" )

port="5353" esniconfig="..." ux= )
port="5353" esniconfig="..."
ux="Testing QUIC")
