my_subnet_flag =1; remote_subnet_flag=1;

my_subnet_flag =  ~(my_subnet_flag)

M=my_subnet_flag

rem_subnet_flag=M-bit of the present packet.

high_out_old = Sequence Number of the Last Byte
                          in the retransmission queue.

cwnd=cwnd+INIT_WINDOW;

cwnd=INIT_WINDOW + 2;
SS_THRESH =INFINITE;

cwnd = 0; /* Don't send any new data */

