INTSERV=0, // the IntServ Model
DIFFSERV=1 // the DiffServ Model
ENDOFLIST   =0, // End of List Identifier
CONSTBW     =1, // Constant Data Transfer Rate
AVBW        =2, // Average Data Transfer Rate
MAXBW       =3, // Maximum Data Transfer Rate
MINDELAY    =4, // Minimum Delay Requirement
AVDELAY     =5, // Average Delay Requirement
BUFFREQ     =6  // Buffer Requirement
