m=video 20002 RTP/AVP 96
c=IN IP4 an1.example.net
a=rtpmap:96 MP4V_ES/90000
a=framerate:5
b=AS:200


m=video 40002 RTP/AVP 96
c=IN IP4 cn.example.net
a=rtpmap:96 MP4V_ES/90000
a=framerate:5
b=AS:200


m=video 40002 RTP/AVP 96 97
c=IN IP4 cn.example.net
a=rtpmap:96 MP4V_ES/90000
a=framerate:5
b=AS:200
a=rtpmap:97 MP4V_ES/90000
a=framerate:15
b=AS:600


m=video 50002 RTP/AVP 97
c=IN IP4 an2.example.net
a=rtpmap:97 MP4V_ES/90000
a=framerate:15
b=AS:600
m=video 20004 RTP/AVP 96
c=IN IP4 an1.example.net
a=rtpmap:96 MP4V_ES/90000
a=framerate:5
b=AS:200
m=video 50002 RTP/AVP 97
c=IN IP4 an2.example.net
a=rtpmap:97 MP4V_ES/90000
a=framerate:15
b=AS:600
m=video 40004 RTP/AVP 97
c=IN IP4 cn.example.net
a=rtpmap:97 MP4V_ES/90000
a=framerate:15
b=AS:600

m=video 30000 RTP/AVP 96
c=IN IP4 hoas.example.com
a=rtpmap:96 MP4V_ES/90000
a=framerate:5
b=AS:200
m=video 30002 RTP/AVP 97
c=IN IP4 hoas.example.com
a=rtpmap:97 MP4V_ES/90000
a=framerate:15
b=AS:600
m=video 30004 RTP/AVP 97
c=IN IP4 hoas.example.com
a=rtpmap:97 MP4V_ES/90000
a=framerate:15
b=AS:600


m=video 30002 RTP/AVP 97
c=IN IP4 hoas.example.com
a=rtpmap:97 MP4V_ES/90000
a=framerate:15
b=AS:600
m=video 30004 RTP/AVP 97
c=IN IP4 hoas.example.com
a=rtpmap:97 MP4V_ES/90000
a=framerate:15
b=AS:600


m=video 50004 RTP/AVP 97
c=IN IP4 an2.example.net
a=rtpmap:97 MP4V_ES/90000
a=framerate: 15
b=AS:600
m=video 40004 RTP/AVP 97
c=IN IP4 cn.example.net
a=rtpmap:97 MP4V_ES/90000
a=framerate: 15
b=AS:600


a=bicast
m=video 30002 RTP/AVP 97
c=IN IP4 an1.example.net
a=rtpmap:97 MP4V_ES/90000
a=framerate:15
b=AS:600
m=video 30004 RTP/AVP 96
c=IN IP4 an2.example.net
a=rtpmap:96 MP4V_ES/90000
a=framerate:5
b=AS:200


a=group:BC 1 2
m=video 30002 RTP/AVP 97
c=IN IP4 an1.example.net
a=rtpmap:97 MP4V_ES/90000
a=framerate:15
b=AS:600
a=mid:1
m=video 30004 RTP/AVP 96
c=IN IP4 an2.example.net
a=rtpmap:96 MP4V_ES/90000
a=framerate:5
b=AS:200
a=mid:2


m=video 30006 RTP/AVP 97
c=IN IP4 hoas.example.net
a=fmtp:97 MP4V_ES/90000
a=framerate:15
b=AS:600
m=video 40006 RTP/AVP 97
c=IN IP4 hoas.example.net
a=fmtp:97 MP4V_ES/90000
a=framerate:15
b=AS:600
m=video 50006 RTP/AVP 96
a=fmtp:96 MP4V_ES/90000
a=framerate:5
b=AS:200


c=IN IP4 an2.example.net
