uri-sip-sigcomp-id = "sigcomp-id=" 1*paramchar

via-sip-sigcomp-id = "sigcomp-id" EQUAL
                      LDQUOT *( qdtext / quoted-pair ) RDQUOT

sigcomp-id=urn:uuid:0C67446E-F1A1-11D9-94D3-000A95A0E128

sigcomp-id=urn:uuid:2e5fdc76-00be-4314-8202-1116fa82a473>;
q=1.0; expires=3600;
