b0 = Transmit
b1 = Receive

b2 = Shared

b3 = Timekeeping

b4-b7 = Reserved

status = SUCCESS; otherwise, confirm to upper layer with status =
status = SUCCESS; otherwise, confirm to upper layer with status =
status = FAIL.

status = FAIL.

status = FAIL.
LinkType=ADVERTISING, indicates that the cell MAY be used to send an
