Type-P-Finite-One-way-Delay-Mean =
                                    N
                                   ---
                              1    \
MeanDelay = - *   >   (FiniteDelay [n])
                              N    /
                                   ---
n = 1

Type-P-Finite-Composite-One-way-Delay-Mean =
                                     S
                                    ---
                                    \
CompMeanDelay =   >   (MeanDelay [s])
                                    /
                                    ---
s = 1
Type-P-Finite-One-way-Delay-Minimum =
               = MinDelay = (FiniteDelay [j])

               such that for some index, j, where 1<= j <= N
               FiniteDelay[j] <= FiniteDelay[n] for all n


Type-P-Finite-Composite-One-way-Delay-Minimum =
                                      S
                                     ---
                                     \
CompMinDelay =    >  (MinDelay [s])
                                     /
                                     ---
s = 1

Type-P-One-way-Packet-Loss-Empirical-Probability =
                                       M
                                      ---
                                 1    \
Ep = - *   >  (L[m])
                                 M    /
                                      ---
m = 1

Type-P-Composite-One-way-Packet-Loss-Empirical-Probability =
CompEp = 1 - {(1 - Ep1) x (1 - Ep2) x (1 - Ep3) x ... x (1 - EpS)}

Type-P-One-way-pdv-refmin-Mean = MeanPDV =
                                   N
                                  ---
                             1    \
                             - *   >   (PDV[n])
                             N    /
                                  ---
n = 1

Type-P-One-way-pdv-refmin-Variance = VarPDV =
                               N
                              ---
                        1     \                      2
                     -------   >   (PDV[n] - MeanPDV)
                     (N - 1)  /
                              ---
n = 1

Type-P-One-way-pdv-refmin-Skewness = SkewPDV =
                         N
                        ---                        3
                        \     /                  \
                         >   |  PDV[n]- MeanPDV  |
                        /     \                 /
                        ---
n = 1
Type-P-Composite-One-way-pdv-refmin-quantile-a =
                          /  /
     P(X + Y + Z <= a) = |  | P(X <= a-y-z) * P(Y = y) * P(Z = z) dy dz
                        /  /
                        z  y
