L = ln(R) + 1

N = exp(1.2 * L / (2*T_maxBackoff/GRTT))

T_maxBackoff = K * GRTT where K >= 1

T_aggregation = T_maxBackoff + (1*GRTT) = (K+1)*GRTT
T_holdoff = T_aggregation + (1*GRTT) = (K+2)*GRTT

current_estimate = 0.25 * current_estimate + 0.75 * peak;
current_estimate = 0.75 * current_estimate + 0.25 * peak;

grtt = 1.0e03;
grtt = 1.0e-06;
