range-value    = exp-char-set exp-char-count  
    
exp-char-set   = digit-char-set / any-char-set 
digit-char-set = "[" dsc-begin "-" dsc-end "]" 
dsc-begin      = DIGIT 
dsc-end        = DIGIT 
any-char-set   = "." 
    
exp-char-count = "{" exp-min "," exp-max "}" 
exp-min        = DIGIT 
exp-max        = DIGIT 
    
version="23" state="full"> 
             
type="e164">+12345678901</user>  
               
range="[0-9]{4}">+1781555</user>  
               
range="[0-9]{4,10}"  
context="pbx.ssp.example.com"></user> 
             
