C   = size of compressed application message, depending on R.
B   = size of bytecode (note: two copies - one as part of SigComp
         message and one in UDVM memory)
R   = size of ring buffer in UDVM memory
S   = any additional state uploaded other than that created from the
         content of the ring buffer at the end of decompression. Similar
         to B, two copies of S are needed
