a=dcmap:4 subprotocol="BFCP"



m=application 21212 <L4>/DTLS/SCTP webrtc-datachannel
c=IN IP4 11.9.19.65
a=max-message-size:1000 ; NOTE 1
a=sctp-port 5000
a=dcmap:1 label="floor control";subprotocol="BFCP"
a=dcsa:1 floorctrl:s-only ; "floor control server only"
a=dcsa:1 confid:4321          ; NOTE 2
a=dcsa:1 userid:1234          ; NOTE 3
a=dcsa:1 floorid: 1 mstrm:3 7 ; NOTE 4

