auid="resource-lists"
etag="opd19dm"
last-modified="2004-06-09T08:07:11.000+03:00"
size="109"
id="dj2kdlkd">
auid="resource-lists"
etag="9c9byuu"
last-modified="2004-06-06T11:44:23.000+03:00"
size="234"
id="39dnlcma">
auid="rules"
etag="zsaeiw7"
id="ab319dndjo"/>
xmlns="urn:ietf:params:xml:ns:xcap-directory"
elementFormDefault="qualified"
attributeFormDefault="unqualified">

namespace="urn:ietf:params:xml:ns:xcap-must-understand"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
use="optional"/>
use="optional"/>
auid="resource-lists"
last-modified="2002-12-08T11:44:23.000+03:00"
size="312"
etag="39csk2"
id="1029238193">
auid="rules"
etag="38s812"
id="789282894"/>
content="text/html;charset=iso-8859-1"/>
