rtcp-attribute = "a=multicast-rtcp:" port CRLF

v=0
o=ali 1122334455 1122334466 IN IP4 ssm.example.com
s='multicast-rtcp' Example
t=0 0
a=rtcp-unicast:rsi
m=video 41000 RTP/AVPF 98
i=Multicast Stream
c=IN IP4 233.252.0.2/255
a=source-filter:incl IN IP4 233.252.0.2 198.51.100.1
a=rtpmap:98 MP2T/90000
a=multicast-rtcp:42000
a=rtcp:43000 IN IP4 192.0.2.1
a=mid:1

