start = tatomEntry

transitional-entry =
       element t:entry {
         atomCommonAttributes,
         (atomAuthor*
          & atomCategory*
          & atomContent?
          & atomContributor*
          & atomId?
          & atomLink*
          & atomPublished?
          & atomRights?
          & atomSummary?
          & atomTitle?
          & atomUpdated?
          & extensionElement*
         )
       }

