WWW-Authenticate    = "WWW-Authenticate" ":" "Digest"
                              digest-challenge

digest-challenge    = 1#( realm | [ domain ] | nonce |
                          [ digest-opaque ] |[ stale ] | [ algorithm ] )

realm               = "realm" "=" realm-value
realm-value         = quoted-string
domain              = "domain" "=" <"> 1#URI <">
nonce               = "nonce" "=" nonce-value
nonce-value         = quoted-string
opaque              = "opaque" "=" quoted-string
stale               = "stale" "=" ( "true" | "false" )
algorithm           = "algorithm" "=" ( "MD5" | token )

Authorization       = "Authorization" ":" "Digest" digest-response

digest-response     = 1#( username | realm | nonce | digest-uri |
                              response | [ digest ] | [ algorithm ] |
                              opaque )

username            = "username" "=" username-value
username-value      = quoted-string
digest-uri          = "uri" "=" digest-uri-value
digest-uri-value    = request-uri         ; As specified by HTTP/1.1
response            = "response" "=" response-digest
digest             = "digest" "=" entity-digest

response-digest     = <"> *LHEX <">
entity-digest      = <"> *LHEX <">
LHEX                = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" |
                           "8" | "9" | "a" | "b" | "c" | "d" | "e" | "f"


response-digest     =
          <"> < KD ( H(A1), unquoted nonce-value ":" H(A2) > <">

A1             = unquoted username-value ":" unquoted realm-value 
                                                ":" password
password       = < user's password >
A2             = Method ":" digest-uri-value



username="Mufasa", realm="myhost@testrealm.com" 

entity-digest = <"> KD (H(A1), unquoted nonce-value ":" Method ":" 
                               date ":" entity-info ":" H(entity-body)) <">
           ; format is <"> *LHEX <">

date = = rfc1123-date            ; see section 3.3.1 of [2]
entity-info = H(
              digest-uri-value ":"
              media-type ":"         ; Content-type, see section 3.7 of [2]
              *DIGIT ":"             ; Content length, see 10.12 of [2]
              content-coding ":"     ; Content-encoding, see 3.5 of [2]
              last-modified ":"      ; last modified date, see 10.25 of [2]
              expires                ; expiration date; see 10.19 of [2]
              )

last-modified   = rfc1123-date  ; see section 3.3.1 of [2]
expires         = rfc1123-date


AuthenticationInfo = "Authentication-info" ":" 
                                      1#( digest | nextnonce )

nextnonce      = "nextnonce" "=" nonce-value

digest = "digest" "=" entity-digest



nonce="dcd98b7102dd2f0e8b11d0f600bfb0c093",
opaque="5ccc069c403ebaf9f0171e9517f40e41"

realm="testrealm@host.com",
nonce="dcd98b7102dd2f0e8b11d0f600bfb0c093",
uri="/dir/index.html",
response="e966c932a9242554e42c8ee200cec7f6",
opaque="5ccc069c403ebaf9f0171e9517f40e41"



Proxy-Authentication     = "Proxy-Authentication" ":" "Digest"
                                   digest-challenge

Proxy-Authorization      = "Proxy-Authorization" ":"
                                   digest-response

Proxy-Authentication-info = "Proxy-Authentication-info" ":" nextnonce

