Ext-VTag=0

Ext-VTag=0


Ext-VTtag = 0


Ext-VTtag = 0


Int-VTag = 1234

Int-VTag = 1234


Ext-VTag = 5678

                                         COOKIE ECHO
                      192.0.2.1:1 -----------------------> 203.0.113.1:2
Ext-VTag = 5678


                                          COOKIE ACK
Int-VTag = 1234

Int-VTag = 1234


Ext-VTag = 0


Ext-VTag = 0


Int-VTag = 1234


Int-VTag = 1234


ExtVTag = 5678

                                      COOKIE ECHO
                   192.0.2.1:1 --------------------------> 203.0.113.1:2
Ext-VTag = 5678


                                        COOKIE ACK
Int-VTag = 1234

Int-VTag = 1234


Ext-VTag = 0


ExtVTag = 0


Int-VTag = 1234


Int-VTag = 1234


Ext-VTag = 5678

                                           COOKIE ECHO
                           192.0.2.1:1 ------------------> 203.0.113.1:2
Ext-VTag = 5678


                                           COOKIE ACK
Int-VTag = 1234

Int-VTag = 1234


Ext-VTag = 5678


Ext-VTag = 5678

Int-VTag = 1234

Int-VTag = 1234


Ext-VTag = 5678


Ext-VTag = 5678


Ext-VTag = 5678

Ext-VTag = 5678


Int-VTag = 1234

Int-VTag = 1234

               DATA
Ext-VTag = 5678
                                           DATA
                        192.0.2.2:1 -------------------> 203.0.113.129:2
Ext-VTag = 5678


Ext-VTag = 0


Ext-VTag = 0


Ext-VTag = 0

Ext-VTag = 0


Ext-VTag = 0


Ext-VTag = 5678


                       INIT ACK[Initiate-Tag = 1234]
                  192.0.2.1:1 ----------------> 203.0.113.1:2
Ext-VTag = 5678

                                                NAT B updates entry:

Ext-VTag = 5678


Ext-VTag = 1234

Ext-VTag = 1234

Ext-VTag = 1234

Ext-VTag = 5678

                                 COOKIE ACK
                  192.0.2.1:1 ----------------> 203.0.113.1:2
Ext-VTag = 5678

                                                       COOKIE ACK
                                              192.0.2.1:1 --> 10.1.0.1:2
Ext-VTag = 5678


