dataTypeSemantics="identifier"
fieldType="1024" applicability="data" status="current">
fieldType="1025" applicability="data" status="current">
dataTypeSemantics="identifier"
fieldType="1026" applicability="option" status="current">
dataTypeSemantics="identifier"
fieldType="1027" applicability="option" status="current">
fieldType="1028" applicability="option" status="current">
fieldType="1029" applicability="option" status="current">
fieldType="1030" applicability="option" status="current">
fieldType="1031" applicability="option" status="current">
fieldType="1032" applicability="option" status="current">
fieldType="1033" applicability="option" status="current">
fieldType="1034" applicability="data" status="current">
dataTypeSemantics="identifier"
fieldType="1035" applicability="option" status="current">
