ENCODER_FEC_SCHEME = REED_SOLOMON
DECODER_FEC_SCHEME = RLC_GF256
ENCODER_SYMBOL_SIZE = 500
DECODER_SYMBOL_SIZE = 200

ENCODER_FEC_SCHEME = RLC_GF256
DECODER_FEC_SCHEME = REED_SOLOMON
ENCODER_SYMBOL_SIZE = 200
DECODER_SYMBOL_SIZE = 500

