RCODE=0 (No Error), then the initiator sends out one more query for
QNAME=www.example.com, QTYPE=A

QNAME=www.example.com, QTYPE=HIP

QNAME=www.example.com, QTYPE=A

QNAME=www.example.com, QTYPE=HIP

QNAME=rvs.example.com, QTYPE=A


              [A? HIP?        ]
              [www.example.com]

              [A?             ]
              [RVS.example.com]                     +-----+
         +----------------------------------------->|     |
         |                                          | DNS |
         | +----------------------------------------|     |
         | |  [A? HIP?                       ]      +-----+
         | |  [www.example.com               ]
         | |  [HIP HIT-R HI-R rvs.example.com]
         | |
         | |  [A?             ]
         | |  [rvs.example.com]
         | |  [A IP-RVS       ]
         | |
         | |                +-----+
         | | +------I1----->| RVS |-----I1------+
         | | |              +-----+             |
         | | |                                  |
         | | |                                  |
         | v |                                  v
        +-----+                              +-----+
        |     |<---------------R1------------|     |
        |  I  |----------------I2----------->|  R  |
        |     |<---------------R2------------|     |
        +-----+                              +-----+




QNAME=www.example.com, QTYPE=A

QNAME=www.example.com, QTYPE=HIP

QNAME=rvs.example.com, QTYPE=A


              [A? HIP?        ]
              [www.example.com]

              [A?             ]
              [RVS.example.com]                     +-----+
         +----------------------------------------->|     |
         |                                          | DNS |
         | +----------------------------------------|     |
         | |  [A? HIP?                       ]      +-----+
         | |  [www.example.com               ]
         | |  [A IP-R                        ]
         | |  [HIP HIT-R HI-R rvs.example.com]
         | |
         | |  [A?             ]
         | |  [rvs.example.com]
         | |  [A IP-RVS       ]
         | |
         | |                +-----+
         | | +------I1----->| RVS |-----I1------+
         | | |              +-----+             |
         | | |                                  |
         | | |                                  |
         | v |                                  v
        +-----+                              +-----+
        |     |----------------I1----------->|     |
        |     |<---------------R1------------|     |
        |  I  |----------------I2----------->|  R  |
        |     |<---------------R2------------|     |
        +-----+                              +-----+
UIMoId== )

UIMoId==
UIMoId==
