DSCP=0, 1 to encode DSCP=1, etc. 
     
provides="this_library"> 
       
location="http://www.petrimeat.com/forces/1.0/lfbmodel/lpm.xml"/> 
     
     
xmlns="http://ietf.org/forces/1.0/lfbmodel" 
targetNamespace="http://ietf.org/forces/1.0/lfbmodel" 
attributeFormDefault="unqualified" 
elementFormDefault="qualified"> 
maxOccurs="unbounded"/> 
minOccurs="0"/> 
minOccurs="0"/> 
minOccurs="0"/> 
minOccurs="0"/> 
type="rangeRestrictionType minOccurs="0"/> 
minOccurs="0"/> 
use="required"/> 
            <xsd:attribute name="max" type="xsd:integer" 
use="required"/> 
          </xsd:complexType> 
        </xsd:element> 



  
  
  
      </xsd:sequence> 
default="variable-size"> 
use="optional"/> 
minOccurs="0"/> 
minOccurs="0"/> 
minOccurs="0"/> 
minOccurs="0"/> 
type="LFBCapabilitiesType" minOccurs="0"/> 
maxOccurs="unbounded"/> 
default="no"/> 
maxOccurs="unbounded"/> 
type="metadataInputChoiceType"/> 
default="required"> 
use="optional"/> 
maxOccurs="unbounded"/> 
default="no"/> 



  
  
  
maxOccurs="unbounded"/> 
type="metadataOutputChoiceType"/> 
default="unconditional"> 
minOccurs="0"/> 
default="read-write"> 
minOccurs="0" maxOccurs="1"/> 
minOccurs="0" maxOccurs="1"/> 
minOccurs="0" maxOccurs="1"/> 
minOccurs="1" maxOccurs="unbounded"/> 
type="SupportedAttributesType"  



  
  
  
minOccurs="0" maxOccurs="1"/> 
type="xsd:nonNegativeInteger" minOccurs="0" maxOccurs="1"/> 
maxOccurs="unbounded"> 
type="xsd:nonNegativeInteger" 
minOccurs="0" maxOccurs="1"/> 
type="xsd:nonNegativeInteger" 
minOccurs="0" maxOccurs="1"/> 
type="LFBAdjacencyLimitType" 
minOccurs="0" maxOccurs="unbounded"/> 
type="LFBAdjacencyLimitType" 
minOccurs="0" maxOccurs="unbounded"/> 
minOccurs="0" maxOccurs="1"/> 
minOccurs="0" maxOccurs="unbounded"/> 
minOccurs="0" maxOccurs="unbounded"> 
maxOccurs="unbounded"> 
minOccurs="0" maxOccurs="1"/> 
maxOccurs="1"> 
type="FEConfiguredNeighborType"  
minOccurs="0" maxOccurs="unbounded"/> 
type="xsd:nonNegativeInteger"/> 
type="xsd:nonNegativeInteger"/> 
minOccurs="0" maxOccurs="1"/> 



  
  
  
minOccurs="0" maxOccurs="1"/> 
