submissiontype="IETF" preptime="2017-11-18T01:52:35Z" version="3">
     <front>
         <title abbrev="IP Datagrams on Avian Carriers">
             A Standard for the Transmission of IP
             Datagrams on Avian Carriers
         </title>
         <seriesinfo name="Internet-Draft" status="informational"
stream="IETF" value="internet-draft-avian-transmission-00" />
value="internet-draft-avian-transmission-00"/>
result = []
result = []
target="crossreference" />
target="crossreference">
         text
displayformat="parens" target="crossreference" />
displayformat="bare" target="crossreference">
         text
leveloffset=_offset_,
lines=_ranges_,
indent=_depth_
target='https://tools.ietf.org/html/rfc7253'>
target='https://tools.ietf.org/html/rfc7253'>
