MAX_JITTER_INT = ((MaxVSize+MPOD)*8/TIDC + (MaxVSize+MPOU)*8/TIUC) 
    
MaxVSize = [(MAX_JITTER_INT * TIDC * TIUC / 8) - (MPOD * TIUC) - 
OVx_V = <video packet rate> * MPOx * 8 
OVx_V = (BW_V/((MaxVSize+MPOx)*8)) * MPOx * 8 
    
OVx_V = (MIN_VIDEO_BW/((MaxVSize+MPOx)*8)) * MPOx * 8 
       
OVx_A = (1000/MaxPTime) * MPOx * 8 
       
OVx_A = (MPOx * 8) / MaxPTime 
    
VideoBW = min (VideoBW(D), VideoBW(U)) 
    
MaxVSize = ((MAX_JITTER_INT * TIDC * TIUC / 8) - (MPOD * TIUC) - 
MaxPTime = MAX_AUDIOLENMS = 120 ms 
    
VideoBW = 16 Kbit/s 
    
MaxVSize = ((MAX_JITTER_INT * TIDC * TIUC / 8) - (MPOD * TIUC) - 
MaxPTime = 80 ms 
    
VideoBW = 21 Kbit/s 
    
