priority-value = "emergency" | "urgent" | "normal"
                                      | "non-urgent"

MLPP-Enabled        = "MLPP-Enabled" ":" MLPP-priority-value

MLPP-priority-value = "Flash Override" | "Flash" 
                      | "immediate" | "Priority" | "Routine"


