oscore-gid="feedca570000";app-gp="group1"

oscore-gid="feedca570000";app-gp="group1",
oscore-gid="ech0ech00000";app-gp="group2",
oscore-gid="abcdef120000";app-gp="group3";app-gp="group4"

oscore-gid="feedca570000";app-gp="group1";
anchor="coap://[2001:db8::ab]"

base="coap://[ff35:30:2001:db8::23]"

oscore-gid=feedca570000
oscore-gid="feedca570000";app-gp="group1";
anchor="coap://[2001:db8::ab]"

oscore-gid="feedca570000";app-gp="group1";
anchor="coap://[2001:db8::ab]",
oscore-gid="ech0ech00000";app-gp="group2";
anchor="coap://[2001:db8::ab]",
oscore-gid="abcdef120000";app-gp="group3";app-gp="group4";
anchor="coap://[2001:db8::cd]"

