H1 = A host on Network 1
N1 = Network 1
I1 = The inside interface on G1
G1 = Gateway 1
O1 = The outside interface on G1
O2 = The outside interface on G2
G2 = Gateway 2
I2 = The inside interface on G2
N2 = Network 2
H2 = A host on Network 2

