service-override-extension = "Service-Override" HCOLON svc-params
                                *(SEMI svc-params)
svc-params = (svc-token / svc-extension)
svc-token = "service" EQUAL  ( "skip" / "continue" / gen-value )
svc-extension = token [ EQUAL gen-value ]
gen-value = token / quoted-string


