PLSP-ID=X1(Symbolic Path Name=Class A)               PLSP-ID=X1(Symbolic Path Name=Class A)
PLSP-ID=X1                                           PLSP-ID=X1
PLSP-ID=X1(Symbolic Path Name=Class A)  |    |     |    +--------^---------+    |      |    |     PLSP-ID=X7(Symbolic Path Name=Class A)
PLSP-ID=X1                             | |    |                  +v-+                   |    | |     PLSP-ID=X7
PLSP-ID=X1(Symbolic Path Name=Class A)  |    |          +----^---^---^-----+           |    |     PLSP-ID=X7(Symbolic Path Name=Class A)
PLSP-ID=X1                             | |    |               |  +v-+ |                 |    | |      PLSP-ID=X7
PLSP-ID=X2(Symbolic Path Name=Class A)          PLSP-ID=X4(Symbolic Path Name=Class A)
PLSP-ID=X2(Symbolic Path Name=Class A)          PLSP-ID=X4(Symbolic Path Name=Class A)
