capability      =/ transit_capa
                          ; transit_capa falls under "X" prefix

transit_capa    = "X-DRAFT-" ownership revision "-" atom
                          ; MUST NOT be used with SASL capabilities
                          ; starting with "AUTH="

ownership       = "I" / "W"
                          ; "I" means that the draft is an individual
                          ; submission; "W" means a WG document

revision        = 2DIGIT
                          ; 2 digit draft revision number


