SA=Lb). Recall that Lb is the address S1 assigned on output
SA=Lb) to (DA=Eb, SA=Ld) and forwards the frame to destination
Metric = null;
Bandwidth = b;
Metric = 1;
Bandwidth = b;
Metric = n;
Bandwidth = b;
Metric = n;
Bandwidth = b;
