Notify = Notify message


     Figure 4: Reservation Failure With Sender Notification via Notify

   For local failures on the Receiver Proxy node, if a similar failure
   on an RSVP midpoint would cause the generation of a ResvErr (for
   example, CAC failure), the Receiver Proxy MUST generate a Notify
   towards the sender.  The Receiver Proxy MAY additionally generate a
   Notify upon local failures which would not ordinarily cause
   generation of a ResvErr message, such as described in Appendix B of
   [RFC2205].
