W = (p/Low_P)^S Low_Window,

S = (log High_Window - log Low_Window)/(log High_P - log Low_P).

W = 0.12/p^0.835.                                    (1)

Low_Window = 38, High_Window = 83,000, High_P = 10^-7, and
High_Decrease = 0.1.  These are also the default values in the NS
W = 0.038/p.

