PUSI=0            ULE 
                                     End 
                                     Indicator 
 
PUSI=1     |              ^ 
                       |              | 
                       +--------------+ 
    
PP=0      Length          
PUSI=1     *   * 
              ***** 
                                          SNDU 
PP=17           CRC for A     Length 
PUSI=1     *                       * 
              ************************* 
    
                                 End     Stuffing 
                    CRC for A Indicator   Bytes 
PUSI=0 
    
    
    
    
    
    
  
 
 
PP=0      Length     CRC for A 
PUSI=1     *   * 
               ***** 
                       SNDU                  Unused 
PP=0      Length       CRC for B  byte 
PUSI=1    *    * 
              ****** 
                       SNDU                       SNDU 
PP=0      Length      CRC for C      Length 
PUSI=1    *    * 
              ******           Unused 
                                byte 
PUSI=0 
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
  
 
 
PP=0      Length 
PUSI=1    *    * 
              ****** 
    
PUSI=0 
    
    
PUSI=0 
    
                                           SNDU 
PP=181         CRC for A      Length 
PUSI=1    *                       * 
              ************************* 
    
PUSI=0 
    
                                    End          Stuffing 
                                 Indicator        Bytes 
PUSI=0 
    
    
    
    
    
    
    
    
  
 
 
PP=0      Length 
PUSI=1     *   *  +      + 
               *****  ++++++++ 
                       + 
                       +++++++++++++++++ 
                                       +   SNDU 
PP=17           CRC for A  +  Length 
PUSI=1     *                      *  +       + 
               ************************  +++++++++ 
                                          + 
PP=0      Length          
PUSI=1     *   * 
              ***** 
    
    
                                           End        Stuffing 
                                         Indicator     bytes 
                -----+------+-   -+-----+---------+- -+------+ 
            ... 0x80 | 0x34 | ... | C51 |0xFF|0xFF|   | 0xFF | 
                -*---+------+-   -+-----+---------+- -+------+ 
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
  
 
 
