service_field = [ [protocol]*("+" rs)]
protocol      = "RCDS" / "HTTP"
rs            = "N2L" / "N2Ls" / "N2R" / "N2Rs" / "N2C"

rewrite_flag = false;
records = lookup(type=NAPTR, key); // get all NAPTR RRs for 'key'

newkey = rewrite(URN, naptr[j].pattern);
services = naptr[j].services;
srvs = any SRV RRs returned as additional info
key = newkey;
rewriteflag = true;
srvs = lookup(type=SRV, key);
