master_secret = KDF-Extract(master_secret,[seed]);

key_stream = KDF-Expand (master_secret, info, L);
key_stream = KDF (master_secret, label, context, L);

ObjectTemplate = { ObjectType, ObjectLength, ObjectMode,
master_secret = KSG-Extract(master_secret[,seed]);

L = 0

info = label || [separator ||] user_context;

info = info || object_count;

info = info || encodeTemplate(ObjectTemplate[i]);
key_stream = KSG-Expand (master_secret, info, L);

offset = 0;

