parameter               = / imsi / mcc / mnc
imsi                    = ";imsi=" imsi-digits
mcc                     = ";mcc=" 3(DIGIT)
mnc                     = ";mnc=" (2(DIGIT) / 3(DIGIT))
imsi-digits             = (upto) 15(DIGIT) ; ed.note, fix this

