Type = value of the EAP Method type

Type = 0xFE || Vendor-Id || Vendor-Type

Key_Material = TLS-Exporter("EXPORTER_EAP_TLS_Key_Material",
                                   Type, 128)
Method-Id    = TLS-Exporter("EXPORTER_EAP_TLS_Method-Id",
                                   Type, 64)
Session-Id   = Type || Method-Id
MSK          = Key_Material(0, 63)
EMSK         = Key_Material(64, 127)

IMSK = TLS-Exporter("TEAPbindkey@ietf.org", EMSK, 32)

session_key_seed = TLS-Exporter("EXPORTER: session key seed",
                                      Type, 40)

MSK  = TLS-Exporter("EXPORTER: Session Key Generating Function",
                           S-IMCK[j], 64)

EMSK = TLS-Exporter("EXPORTER: Extended Session Key Generating Function",
                           S-IMCK[j], 64)

CMK = CMK[j]

Compound-MAC = MAC( CMK, BUFFER )

EAP-TTLS_challenge = TLS-Exporter("ttls challenge",, n)

