slp-url        = "slp://" [domain-name] "/" query
domain-name    = hostname from Section 3.2.2 of RFC 2396 [2]
query          = query-id "?" [scope] "?" filter ["?" ext-list]
query-id       = "SrvRqst" / "SrvTypeRqst" / "AttrRqst"
scope          = scope-list from Section 6.4.1 of RFC 2608 [1]
filter         = srv-filter / srvtype-filter / attr-filter
srv-filter     = "type=" service-type [";pred=" predicate]
                      [";spi=" spi-str]
service-type   = service type defined in Section 4 of RFC 2608
predicate      = predicate from Section 8.1 of RFC 2608
spi-str        = SPI defined in Section 9.2 of RFC 2608
srvtype-filter = "na=" nalenstr
nalenstr       = "0" / "-1" / nastr
nastr          = naming-auth from Section 2.1 of RFC 2609 [5]
attr-filter    = "url=" url [";tag=" tag-list] [";spi=" spi-str]
url            = URL defined in Section 4 of RFC 2608
tag-list       = tag-list from Section 10.3 of RFC 2608
ext-list       = extension / extension ";" ext-list
extension      = attr-ext / select-ext / sort-ext
attr-ext       = "ext=attr"
select-ext     = "ext=select;" max-num
max-num        = intval from Section 5 of RFC 2608
sort-ext       = "ext=sort;" sort-key-list
sort-key-list  = sort-key-list from Section 3 of [8]

