acl2_command    = myrights | "ACL" SPACE acl2_subcommand

acl2_subcommand = replaceacl | deleteacl | updateacl | getacl | listrights

acl_data        = "ACLINFO" SPACE mailbox *(SPACE identifier SPACE rights)

always_granted  = rights

deleteacl       = "DELETE" SPACE mbox_or_pat SPACE identifier

getacl          = "GET" SPACE mbox_or_pat

identifier      = astring
                      ;; UTF-8

listrights      = "LIST" SPACE mbox_or_pat SPACE identifier

listrights_data = "RIGHTS-INFO" SPACE mailbox SPACE identifier
                           SPACE always_granted *(SPACE rights)

mod_rights      = quoted
                      ;; +rights to add, -rights to remove

myrights        = "MYRIGHTS" SPACE mailbox

myrights_data   = "MYRIGHTS" SPACE mailbox SPACE rights

myrights_rspcod = "MYRIGHTS" SPACE rights

replaceacl      = "SET" SPACE mbox_or_pat *(SPACE identifier SPACE rights)

resp-text-code  =/ myrights_data

rights          = quoted
                     ;; MUST NOT contain leading "+" or "-"

updateacl       = "STORE" SPACE mbox_or_pat SPACE identifier SPACE mod_rights

mbox_or_pat     = mailbox / patterns

patterns        = "(" list-mailbox *(list-mailbox) ")"

partialfail_rsp = "ACLFAILED" [SPACE "[" resp-text-code "]" ] SPACE mailbox
                     ;; May contain optional failure reason


SETACL          => ACL STORE
DELETEACL       => ACL DELETE
REPLACEACL      => ACL SET
GETACL          => ACL GET
LISTRIGHTS      => ACL LIST

ACL             => ACLINFO
LISTRIGHTS      => RIGHTS-INFO

