Event       =  "Event" ":" event-type
                    *(( ";" parameter-name
                    ["=" ( token | quoted-string ) ] )
event-type  =  token


Allow-Events =  "Allow-Events" ":" 1#event-type


Success  = "200"  ;  OK
             |  "202"  ;  Accepted


Client-Error = "400"  ; Bad Request
                  ...
                  | "489"  ; Bad Event


