m=audio 49170 RTP/AVP 0 8 3
c=IN IP4 192.0.2.5
m=video 9 RTP/AVP 34
c=SIP SIPURI sip:anna@example2.net


c=<nettype> <addrtype> <connection-address>

v=0
o=jdoe 2890844526 2890842807 IN IP4 192.0.2.5
s=
t=0 0
c=IN IP4 192.0.2.5
a=creq:ccap-v0
m=audio 49170 RTP/AVP 0 8 3
m=video 49174 RTP/AVP 34
a=ccap:1 SIP SIPS sips:anne@example.com

v=0
o=jdoe 2890844526 2890842807 IN IP4 192.0.2.5
s=
t=0 0
c=IN IP4 192.0.2.5
a=creq:ccap-v0
m=audio 49170 RTP/AVP 0 8 3
m=video 49174 RTP/AVP 34
c=SIP SIPS sips:anne@example.com

connection-field   =  [%x63 "=" nettype SP addrtype SP
URI-address       =  SIP-URI/SIPS-URI

