parameter     = attribute LWSP "=" LWSP value

attribute     = token
value         = token / quoted-string

quoted-string = <quoted-string, defined in [RFC2616], Section 2.2>
token         = <token, defined in [RFC2616], Section 2.2>

parameter     = reg-parameter / ext-parameter

reg-parameter = parmname LWSP "=" LWSP value

ext-parameter = parmname "*" LWSP "=" LWSP ext-value

parmname      = 1*attr-char

ext-value     = charset  "'" [ language ] "'" value-chars
                   ; like RFC 2231's <extended-initial-value>
                   ; (see [RFC2231], Section 7)

charset       = "UTF-8" / "ISO-8859-1" / mime-charset

mime-charset  = 1*mime-charsetc
mime-charsetc = ALPHA / DIGIT
                   / "!" / "#" / "$" / "%" / "&"
                   / "+" / "-" / "^" / "_" / "`"
                   / "{" / "}" / "~"
                   ; as <mime-charset> in Section 2.3 of [RFC2978]
                   ; except that the single quote is not included
                   ; SHOULD be registered in the IANA charset registry

language      = <Language-Tag, defined in [RFC5646], Section 2.1>

value-chars   = *( pct-encoded / attr-char )

pct-encoded   = "%" HEXDIG HEXDIG
                   ; see [RFC3986], Section 2.1

attr-char     = ALPHA / DIGIT
                   / "!" / "#" / "$" / "&" / "+" / "-" / "."
                   / "^" / "_" / "`" / "|" / "~"
                   ; token except ( "*" / "'" / "%" )

foo-header  = "foo" LWSP ":" LWSP token ";" LWSP title-param
title-param = "title" LWSP "=" LWSP value
                 / "title*" LWSP "=" LWSP ext-value
ext-value   = <see RFC 5987, Section 3.2>







      Note: The Parameter Value Continuation feature defined in Section
      3 of [RFC2231] makes it impossible to have multiple instances of
      extended parameters with identical parmname components, as the
      processing of continuations would become ambiguous.  Thus,
      specifications using this extension are advised to disallow this
      case for compatibility with RFC 2231.

