cookie = MSB_<b> (HMAC(server seed, KIV)),

cookie = MSB_<b> (HMAC(server seed, H(certificate of client))).

K_i = F(K_{i+1}).

d = ceil( 2*B / L) + 1,
t_i = R + D_t,

x = floor((t_i - T_1) / L) + 1,
T_i =< s_i, and

