A1-------A2-------A3-------A4-------A5===============A6----------A7
                 \               /          \   SID:310(Ay)   \          /
                  \ 10        10/            \                 \10      /10
                   \           /              \                 \      /
             SID:80 \A8-----A9/SID:90          \  40             \    /
                    /         \                 +-----+           \  /
                   /10         \10                     \           \/
ID = 2 and may include the path of R1-R6-R7-R4 for a FEC Prefix
ID = 3 does include the node R9 for the FEC prefix advertised by R4.
