keydata = keydef | comment | blank

keydef = algorithm ":" key-hash ":" service ":" host ":" port rfu CRLF

comment = "#" *(WSP / VCHAR) CRLF

blank = *(WSP) CRLF

algorithm = *(ALPHA / DIGIT)

key-hash = *(HEXDIG)

service = *(ALPHA)

host = <<<wherever this is specified>>>

port = *(DIGIT) / ""

rfu = "" / ":" *(WSP / VCHAR)

