H  =  Host computer
MR  =  Master Router
BR  =  Backup Router
                            *  =  IP Address 
VIP  =  default gateway for hosts (Virtual IP)
H  =  Host computer
MR  =  Master Router
BR  =  Backup Router
                            *  =  IP Address 
VIP  =  default gateway for hosts (Virtual IP)
