Policy-Id        = "Policy-Id" HCOLON absoluteURI
                        *(COMMA absoluteURI)

Policy-Contact   = "Policy-Contact" HCOLON policyURI
                        *(COMMA policyURI)
policyURI        = absoluteURI [ SEMI "non-cacheable" ]
profile-types      =  "device" / "user" / "application" /
                            "local" / "policy"

document="session-id/48ei48rj474k";
vendor="vendor.example.com";model="Z100";version="1.2.3";
network-user="alice@example.com"
