sms-url              = scheme ":" scheme-specific-part
scheme               = "sms"
scheme-specific-part = subscriber-id [";via=" message-centre-id]
                             ["," scheme-specific-part]
subscriber-id        = ["+"] phone-number
message-centre-id    = ["+"] phone-number
phone-number         = 1*phonedigit
phonedigit           = digit / "-" / "."
digit                = "0" / "1" / "2" / "3" / "4" / "5" /
                             "6" / "7" / "8" / "9"

