D_i = [d_0 + d_1 +...+ d_(N_i-1)] / N_i

AD = [ad_0 + ad_1 +...+ ad_(M-1)] / M

PL_i = [p_(i,0) + p_(i,1) +...+ p_(i,K-1)] - [p_(o,0) + p_(o,1) +...+
ip_dst=0.0.0.0/0, port_src=/, port_dst=/, type=tcp, outlines a flow
