type = service:sysman

version = 0.0

language = en

description = 
        The 'service:sysman' abstract service type organizes information
        from various services, protocols, and schemas that relate to
        systems management. Systems management, as used in this
        document, relates to the monitoring, diagnosing, service and
        support of desktop and host computers.
    
url-syntax =
url-path   = hosturl / dmiurl / cimurl / snmpurl
hosturl    = url as defined in "Host Service Type" (below)
dmiurl     = url as defined in "DMI Service Type" (below)
cimurl     = url as defined in  "CIM Service Type" (below)
snmpurl    = url as defined in "SNMP Service Type" (below)

type = service:sysman:host

version = 0.0

language = en

description =
    The "host" concrete service type provides information
    immediately relevant to the management of a desktop or host
    computer.
url-path        =  ([machine-name] os-name os-vendor
                            os-majorverion [os-minorversion] 
                            [os-revision] mac-address [contact])
machine-name    =  ";machine-name =" 1*alpha-num
os-name         =  ";os-name =" 1*alpha-num
os-vendor       =  ";os-vendor =" 1*alpha-num
os-majorversion =  ";os-major =" 1*DIGIT
os-minorversion =  ";os-minor =" 1*alpha-num
os-revision     =  ";os-revision =" 1*alpha-num
mac-address     =  ";mac-address =" 12HEXDIG
owner           =  ";owner =" 1*CHAR
machine-uuid    =  ";uuid =" as defined in [3]
                            ;uuid is a 128-bit value, represented 
                            ;as a string, that provides a unique
                            ;id to hardware that supports this
                            ;this feature
        
machine-name = string O L 
os-name = string L
os-vendor = string L
os-majorversion = integer L 
os-minorversion = string O L
os-revision = string O L
mac-address = string M L
owner = string O
machine-uuid = string O L
contact="Michael Day" <michael_day@ccm.ut.intel.com>

type = service:sysman:dmi

version = 0.0

language = en
description =
    The "dmi" concrete service type provides information the
    availibility of Desktop Management Interface services on the
    computer. For information on the desktop management interface,
    see http://www.dmtf.org

url-path        =  (provider vendor provider-major
                            provider-minor [remote-interface]
                            [access-point] [security-level])
provider-vendor  = ";vendor = " 1*alpha-num
provider-major   = ";major =" 1*DIGIT
provider-minor   = ";minor ="  1*alpha-num
remote-interface = ";remote=" 1*ALPHA" 
access-point     = ";access-point =" 1*safe-char 
security-level   = ";security =" 1*safe-char
provider-vendor = string L
provider-major = integer X
provider-minor = string L
remote-interface = string L O
access-point = string L O
security-level = string L O
contact="Michael Day" <michael_day@ccm.ut.intel.com>

type = service:sysman:cim
version = 0.0
language = en
description =
    The "cim" concrete service type provides information the
    availibility of Common Information Model services on the computer.
    For more information see http://www.dmtf.org

url-path        =  (cim-major cim-minor cim-revision om-vendor 
                            om-major om-minor om-revision 
                            [remote-interface] [access-point])
cim-major       = ";cim-major =" 1*DIGIT
cim-minor       = ";cim-minor =" 1*DIGIT
cim-revision    = ";cim-revision =" 1*alpha-num
om-vendor       = ";om-vendor =" 1*alpha-num
om-major        = ";om-major =" 1*DIGIT
om-minor        = ";om-minor =" 1*DIGIT
om-revision     = ";om-revision =" 1*alpha-num
remote-interface= ";remote =" 1*alpha-num
access-point    = ";access-point =" 1*safe-char
cim-major = integer X 
cim-minor = integer X
cim-revision = string L X
om-vendor = string L X
om-major = integer X
om-minor = integer X
om-revision = string L 
remote-interface = string L O
access-point = string L O
contact="Michael Day" <michael_day@ccm.ut.intel.com>

type=service:sysman:snmp
version=0.0
lang=en

description=
     The 'service:sysman:SNMP:' URL provides information about the SNMP 
     manageability of a given host.  Namely, if this URL exists for a 
     host (denoted by the <addr-spec> in the URL,) the host supports 
     SNMP.  The path contains an enumeration of the MIB groups that are 
     supported by the host.  The OID "1.3.6.1." is assumed as a prefix 
     to each of the OID terms below.

url-syntax=
url-path     = ( [port-list] [comm-string] [oid-list])
                       ; None of the attributes listed in the URL path
                       ; are required.  They MAY be included.
port-list    = ";ports=" port-list
ports        = port / port "," ports
                       ; See the Service URL <port> production rule.
                       ; This field is defined as an attribute, below.
comm-string  = ";read-community-string=" 1*uchar
                       ; See the Service URL <uchar> production rule.
                       ; This field is defined as an attribute, below.
oid-list     = ";oids=" oids
                       ; This field is defined as an attribute, below.
oids         = oid / oid "," oids
oid          = DIGIT [ "." (DIGIT ".") DIGIT]
ports=integer M L
read-community-string=string L O
oid=string M L O
contact="Erik Guttman" <Erik.Guttman@sun.com>

alpha-num    = ALPHA / DIGIT / "-" / "."
safe-char    =  as defined in [2]
DIGIT        =  as defined in [7]
ALPHA        =  as defined in [7]
HEXDIG       =  as defined in [7]
CHAR         =  as defined in [7]
