Cipher=CCMP))]
                                            <-------------------------->
Cipher=CCMP))]
                                                      <---------------->

Q=1:   The WTP marks the priority field in the 802.1Q header to
      either the default, or the station specific 802.1p policy.

Q=0:   The WTP marks the priority field in the 802.1Q header to the
      value found in User Priority field of the QoS Control field of the
      IEEE 802.11 header.  If the QoS Control field is not present in
      the IEEE 802.11 header, then the behavior described under 'Q=1' is
      used.

O=1:   This option is invalid when tunneling is not enabled for
      station data frames.

O=0:   This option is invalid when tunneling is not enabled for
      station data frames.

I=1:   The WTP sets the DSCP field in the station's packet to either
      the default policy, or the station specific policy if one exists.

I=0:   The WTP MUST NOT modify the DSCP field in the station's
      packet.

O=1:   The WTP sets the DSCP field in the tunnel header to either the
      default policy, or the station specific policy if one exists.

O=0:   The WTP sets the DSCP field in the tunnel header to the value
      found in the inner packet's DSCP field.  If encryption services
      are provided by the AC (see Section 6.15), the packet is
      encrypted, therefore the WTP cannot access the inner DSCP field,
      in which case it uses the behavior described when the 'O' bit is
      set.  This occurs also if the inner packet is not IPv4 or IPv6,
      and thus does not have a DSCP field.

I=1:   The WTP sets the DSCP field in the station's packet to either
      the default policy, or the station specific policy if one exists.
      If encryption services are provided by the AC (see Section 6.15),
      the packet is encrypted, therefore the WTP cannot access the inner
      DSCP field, in which case it uses the behavior described when the
      'I' bit is not set.  This occurs also if the inner packet is not
      IPv4 or IPv6, and thus does not have a DSCP field.

I=0:   The WTP MUST NOT modify the DSCP field in the station's
      packet.

