AUTH=addr-spec

         Arguments:
             an addr-spec containing the identity which submitted the
             message to the delivery system.  The length of the addr-
             spec is limited to 129 characters, per [RFC821].  To comply
             with the restrictions imposed on ESMTP parameters, the
             addr-spec may not conatain space, `=', or control
             characters.


         Discussion:
             The optional AUTH parameter to the MAIL FROM command allows
             cooperating agents in a trusted environment to communicate
             the authentication of individual messages.

             If the server trusts the authenticated identity of the
             client to assert that the message was originally submitted
             by the supplied addr-spec, then the server SHOULD supply
             the same addr-spec in an AUTH parameter when relaying the
             message to any server which supports the AUTH extension.

             If the server does not sufficiently trust the authenticated
             identity of the client, or if the client is not
             authenticated, then the server MUST behave as if no AUTH
             parameter was supplied.  The server MAY, however, place the
             value of the AUTH parameter in a comment in the inserted
             Received: header and/or write it to a log file.

             A server MAY treat expansion of a mailing list as a new
             submission, setting the AUTH parameter to the mailing list
             address or mailing list administration address when
             relaying the message to list subscribers.
