o=e164, ed=0, ed=0, ed=1, ed=6, ed=1, ed=3, ed=1, ed=2,ed=3,\
ed=4, ed=5, ed=6, ed=7

o=BigCo                                          o=e164
                     |                                                  |
cn=John Smith   cn=Joe Bloggs   cn=…   ou=BigCo Priv Numbering Plan     |
                                                   |           -------------
                                                   …           |           |
ed=0       ed=4
                                                               |           |
ed=1       ed=4
                                                               |           |
ed=6       ed=7    ed=2
                                                       |           |       |
ed=1       ed=0    ed=5
                                                       |           |       |
ed=3       ed=9    ed=5
                                                       |           |       |
ed=7       ed=1    ed=6
                                                       |           |       |
ed=6       ed=2    ed=3
                                                       |        /          |
DN= o=BigCo, ou=BigCo Priv Numbering Plan <---     ed=3           |
ed=4               |
ed=5                   |
ed=6                        |
ed=7                             |
DN= o=BigCo, cn=John Smith <---     DN= o=BigCo, cn=Joe Bloggs <-
           (Pointer to WP entry)                  (Pointer to WP entry)
  
                            o: organizationName
                            ou: organizationalUnitName
                            cn: commonName
                            ed: e164Digit
                            DN: Distinguished Name
                            
ed=4, ed=3, ed=2, ed=1, ed=5, ed=6, ed=7, ed=3, ed=1, ed=6, ed=1, ed=0,\
ed=0, o=e164
  
ed=5, ed=5, ed=5, ed=4, ed=3, ed=2, ed=1, ed=5, ed=6, ed=7, ed=3,\
ed=1, ed=6, ed=1, ed=0, ed=0, o=e164
  
