CNT="xxx" HB="xxx" SIGN="xxx"]
CNT="7" HB="K6wzcombEvKJ+UTMcn9bPryAeaU= zrkDcIeaDluypaPCY8WWzwHpPok=
zgrWOdpx16ADc7UmckyIFY53icE= XfopJ+S8/hODapiBBCgVQaLqBKg=
SIGN="AKBbX4J7QkrwuwdbV7Taujk2lvOf8gCgC62We1QYfnrNHz7FzAvdySuMyfM="]

INDEX="xxx" FLEN="xxx" FRAG="xxx" SIGN="xxx"]

INDEX="1" FLEN="587" FRAG="2009-05-03T14:00:39.519005+02:00 K BACsLMZ
RC1B82Sub152zOqIcAWsgd4myCCiZbWBsuJ8P0gtarFIpleNacCc6OV3i2Rg=="
SIGN="AKAQEUiQptgpd0lKcXbuggGXH/dCdQCgdysrTBLUlbeGAQ4vwrnLOqSL7+c="]

certInitialRepeat = number of times each Certificate Block should
certResendDelay = maximum time delay in seconds until resending
certResendCount = maximum number of other syslog messages to send
sigMaxDelay = generate a new Signature Block if this many seconds
sigNumberResends = number of times a Signature Block is resent.
sigResendDelay = send the next retransmission when this many
sigResendCount = send the next retransmission when this many other
