pinning_protection_key = HKDF-Expand(resumption_protection_key,
                                 "pinning protection", L)

pinning_proof_secret=Derive-Secret(Handshake Secret, "pinning proof 1",
              ClientHello...ServerHello)

proof = HMAC(original_pinning_secret, "pinning proof 2" +
              pinning_proof_secret + Hash(server_public_key))

   where HMAC [RFC2104] uses the Hash algorithm that was negotiated in
   the handshake, and the same hash is also used over the server's
   public key.  The original_pinning_secret value refers to the secret
   value extracted from the ticket sent by the client, to distinguish it
   from a new pinning secret value that is possibly computed in the
   current exchange.  The server_public_key value is the DER
   representation of the public key, specifically the
   SubjectPublicKeyInfo structure as-is.

CN=example.com" -key "example.com.key" -out "example.com.csr";"

