Spatial-Location-payload = *(Location-Content Delimiter)

Location-Content = Coordinate-Location | Descriptive-Location | Any-
Coordinate-Location = <any coordinate-centered location>

                         ; e.g., those defined in [1, 3-7], while the
                         ; common spatial location data set [1] is
                         ; recommended to be when there is no other
                         ; mutually understood/preferred location format
                         ; between the involved parties

Descriptive-Location = <any description-based location>

                         ; e.g., a descriptive location define in [2]

Any-Other-Location = <any other location information>

Delimiter = <any character or string serving as a delimiter between
                elements>

                         ; e.g., when using XML-based coding, it
                         ; "is" a pair of corresponding element
                         ; tags
type="this:OrientationType"/>
         <xsd:element name="hardware" type="this:HardwareType"
minOccurs="0"/>
       </xsd:sequence>
