v = f*s                               (1)
 
f = v/s                               (2)


s = x2 - x1 +- 2E                      (3)

f = v/(x2 - x1 +- 2E)                  (4)

Dtr = v*t(itho)                       (5)

t =(B/h)                           (7)                    

v =(2r/t)                          (8)                 
       			
