addPeriod =
autoRenewPeriod =
clientDeleteProhibited =
clientHold =
clientRenewProhibited =
clientTransferProhibited =
clientUpdateProhibited =
inactive = inactive
linked = associated
ok = active
pendingCreate = pending create
pendingDelete = pending delete
pendingRenew = pending renew
pendingRestore =
pendingTransfer = pending transfer
pendingUpdate = pending update
redemptionPeriod =
renewPeriod =
serverDeleteProhibited =
serverRenewProhibited =
serverTransferProhibited =
serverUpdateProhibited =
serverHold =
transferPeriod =

addPeriod = add period;  This grace period is provided after the
       initial registration of the object.  If the object is deleted by
       the client during this period, the server provides a credit to
       the client for the cost of the registration.
autoRenewPeriod = auto renew period;  This grace period is provided
       after an object registration period expires and is extended
       (renewed) automatically by the server.  If the object is deleted
       by the client during this period, the server provides a credit to
       the client for the cost of the auto renewal.
clientDeleteProhibited = client delete prohibited;  The client
       requested that requests to delete the object MUST be rejected.
clientHold = client hold;  The client requested that the DNS
       delegation information MUST NOT be published for the object.
clientRenewProhibited = client renew prohibited;  The client
       requested that requests to renew the object MUST be rejected.
clientTransferProhibited = client transfer prohibited;  The client
       requested that requests to transfer the object MUST be rejected.
clientUpdateProhibited = client update prohibited;  The client
       requested that requests to update the object (other than to
       remove this status) MUST be rejected.
pendingRestore = pending restore;  An object is in the process of
       being restored after being in the redemption period state.
redemptionPeriod = redemption period;  A delete has been received,
       but the object has not yet been purged because an opportunity
       exists to restore the object and abort the deletion process.
renewPeriod = renew period;  This grace period is provided after an
       object registration period is explicitly extended (renewed) by
       the client.  If the object is deleted by the client during this
       period, the server provides a credit to the client for the cost
       of the renewal.
serverDeleteProhibited = server delete prohibited;  The server set
       the status so that requests to delete the object MUST be
       rejected.
serverRenewProhibited = server renew prohibited;  The server set the
       status so that requests to renew the object MUST be rejected.
serverTransferProhibited = server transfer prohibited;  The server
       set the status so that requests to transfer the object MUST be
       rejected.
serverUpdateProhibited = server update prohibited;  The server set
       the status so that requests to update the object (other than to
       remove this status) MUST be rejected.
serverHold = server hold;  The server set the status so that DNS
       delegation information MUST NOT be published for the object.
transferPeriod = transfer period;  This grace period is provided
       after the successful transfer of object registration sponsorship
       from one client to another client.  If the object is deleted by
       the client during this period, the server provides a credit to
       the client for the cost of the transfer.

addPeriod = add period
autoRenewPeriod = auto renew period
clientDeleteProhibited = client delete prohibited
clientHold = client hold
clientRenewProhibited = client renew prohibited
clientTransferProhibited = client transfer prohibited
clientUpdateProhibited = client update prohibited
inactive = inactive
linked = associated
ok = active
pendingCreate = pending create
pendingDelete = pending delete
pendingRenew = pending renew
pendingRestore = pending restore
pendingTransfer = pending transfer
pendingUpdate = pending update
redemptionPeriod = redemption period
renewPeriod = renew period
serverDeleteProhibited = server delete prohibited
serverRenewProhibited = server renew prohibited
serverTransferProhibited = server transfer prohibited
serverUpdateProhibited = server update prohibited
serverHold = server hold
transferPeriod = transfer period

