binchar = <Any character valid in the base64 or quoted-printable
binary       = *binchar              ;A base64 or quoted-printable
time-hour       = 2DIGIT        ;00-23
time-minute     = 2DIGIT        ;00-59
utc-offset      = ("+" / "-") time-hour ":" time-minute

decimal = degrees + minutes/60 + seconds/3600.

CR         =  <ASCII CR, carriage return>  ; (15, 13.)
LF         =  <ASCII LF, linefeed>         ; (12,10.)
CRLF       =  CR LF
SPACE      =  <ASCII SP, space>            ; (40,32.)
HTAB       =  <ASCII HT, horizontal-tab>        ; (11,9.)

word         = <any printable 7bit us-ascii except []=:., >

groups       = groups "." word
                 / word

vcard_entity = 1*(vcard)

vcard        = "BEGIN" ":" "VCARD" 1*CRLF
                 items *CRLF
                 "END" ":" "VCARD" 1*CRLF

items        = items *CRLF item
                 / item
        ; these may be "folded"

item         = [groups "."] name
                  [params] ":" value CRLF
                / [groups "."] "ADR"
                  [params] ":" addressparts CRLF
                / [groups "."] "ORG"
                  [params] ":" orgparts CRLF
                / [groups "."] "N"
                  [params] ":" nameparts CRLF
                / [groups "."] "AGENT"
                  [params] ":" vcard CRLF
        ; these may be "folded"

name         = "LOGO" / "PHOTO" / "LABEL" / "FN" / "TITLE"
                / "SOUND" / "VERSION" / "TEL" / "EMAIL" / "TZ"
                / "GEO" / "NOTE" / "SOURCE" / "NAME" / "PROFILE"
                / "URL" / "BDAY" / "ROLE" / "REV" / "UID" / "KEY"
                / "MAILER" / "CATEGORIES" / "CLASS" / "PRODID"
                /"X-" word
        ; these may be "folded"

value        = 7bit / quoted-printable / base64

quoted-printable = <MIME RFC 2045 quoted-printable text>

base64       = <MIME RFC 2045 base64 text>
        ; the end of the text is marked with two CRLF sequences
                      vCard MIME Directory Profile


        ; this results in one blank line before the start of the next
        ; property

params       = ";" paramlist

paramlist    = paramlist ";" param
                / param

param        = "TYPE" "=" ptypeval
                / "VALUE" "=" pvalueval
                / "ENCODING" "=" pencodingval
                / "LANGUAGE" "=" langval
                / "X-" word "=" word
                / knowntype / ianatype

ptypeval     = knowntype / "X-" word

pvalueval    = "URL" / "TEXT" / "DATE" / "TIME" / "DATE-TIME"
                / "INTEGER" / "BOOLEAN" / "FLOAT" / "BINARY" /
                / "VCARD" / "PHONE-NUMBER" / "UTC-OFFSET" / "X-" word

pencodingval = "7BIT" / "8BIT" / "QUOTED-PRINTABLE" / "BASE64"
                / "X-" word

langval      = <a language string as defined in RFC 1766>

addressparts = 0*6(strnosemi ";") strnosemi
        ; PO Box, Extended Addr, Street, Locality, Region, Postal Code,
        ; Country Name

orgparts     = *(strnosemi ";") strnosemi
        ; First is Organization Name, remainder are Organization Units.

nameparts    = 0*4(strnosemi ";") strnosemi
        ; Family, Given, Middle, Prefix, Suffix.
        ; Example:Public;John;Q.;Reverend Dr.;III, Esq.

strnosemi    = *(*nonsemi ("\;" / "\" CRLF)) *nonsemi
        ; To include a semicolon in this string, it must be escaped
        ; with a "\" character.

nonsemi      = <any non-control ASCII except ";">

knowntype    = "DOM" / "INTL" / "POSTAL" / "PARCEL" / "HOME" / "WORK"
                / "PREF" / "VOICE" / "FAX" / "MSG" / "CELL" / "PAGER"
                / "BBS" / "MODEM" / "CAR" / "ISDN" / "VIDEO" / "PCS"
                / "INTERNET" / "X400" / "X509" / "PGP"

ianatype     = <Any IANA registered value>
                      vCard MIME Directory Profile


