Plane ====>       |                           |       ====> Plane
                |     +---+     Component Link 1      +---+     |
                |     |   |===========================|   |     |
                |     |   |~~~~~~ CTG Connections ~~~~|   |     |
              ~~|~~>~~|   |===========================|   |~~>~~|~~
              ~~|~~>~~| C |    Component Link 2       | C |~~>~~|~~
