ID=example:keys:123&OUC=example.com/content.mov&DS=r:CFB03EDB
ge=RVQ9MTIwOTQyMjk3NiZhbXA7Q0tJPTMxMSZhbXA7Q0lQPTkwQzkxMzk3Nz
NTkzYTk3YWNiOTcyMjAyMTIwZGM0ODJiZGRhZg==").  Note: this is
ISigningPackage=RVQ9MTIwOTQyMjk3NiZhbXA7Q0tJPTMxMSZhbXA7Q0lQP
jYTMwZTMwMzU2NTkzYTk3YWNiOTcyMjAyMTIwZGM0ODJiZGRhZg==/content
I=311&CIP=90C913977933FC650E7186361A93D6C3&KID=example:keys:123&M
D=1ecb1446a6431352aab0fb6e0dca30e30356593a97acb972202120dc482bdda
