v=0 
c=IN IP4 47.1.1.1 
m=audio 1000 RTP/AVP 0 
           
Transaction = 1 { 
Context = $ { 
Add = $ { 
TerminationState = { 
                         mb/inrealm = *, 
                         mb/srcaddr = "192.5.5.5", 
                         mb/srcport = *, 
                         mb/egrealm = "public", 
                         mb/destaddr = "47.1.1.1", 
                         mb/destport = 1000, 
                         mb/protoid = "UDP", 
                         mb/rtp = TRUE, 
 
                                     
                         mb/action = Allow 
                       }, 
Events = 100 { 
                         mb/rule-expiry = 300 
Add = $ { 
TerminationState = { 
                         mb/inrealm = "private", 
                         mb/srcaddr = "192.5.5.5", 
                         mb/srcport = *, 
                         mb/egrealm = *, 
                         mb/destaddr = "47.1.1.1", 
                         mb/destport = 1000, 
                         mb/protoid = "UDP", 
                         mb/rtp = TRUE, 
                         mb/action = Allow 
                       }, 
Events = 100 { 
                         mb/rule-expiry = 300 
Reply = 1 { 
Context = 50 { 
Add = T1,            
Add = T2  
v=0 
c=IN IP4 192.5.5.5 
m=audio 2000 RTP/AVP 0 
      
Transaction = 2 { 
Context = 50 { 
Add = $ { 
TerminationState = { 
                         mb/inrealm = *, 
                         mb/srcaddr = "47.1.1.1", 
                         mb/srcport = *, 
                         mb/egrealm = "private", 
                         mb/destaddr = "192.5.5.5", 
                         mb/destport = 2000, 
                         mb/protoid = "UDP", 
                         mb/rtp = TRUE, 
                         mb/action = Allow 
                       }, 
Events = 100 { 
                         mb/rule-expiry = 300                     
Add = $ { 
TerminationState = { 
                         mb/inrealm = "public", 
                         mb/srcaddr = "47.1.1.1", 
                         mb/srcport = *, 
                         mb/egrealm = *, 
                         mb/destaddr = "192.5.5.5", 
                         mb/destport = 2000, 
                         mb/protoid = "UDP", 
                         mb/rtp = TRUE, 
                         mb/action = Allow 
Events = 100 { 
                         Mb/rule-expiry = 300                     
Reply = 2 { 
Context = 50 { 
Add = T3,  
Add = T4  
Transaction = 3 { 
Context = 50 { 
Subtract = ALL 
