Type=45

            Option
      Type  Length  MP_OPT        Meaning
      ----  ------  -------       -----
       45     7     0 =MP_CONFIRM Confirm reception and processing of
                                  an MP_OPT option
       45     7     1 =MP_JOIN    Join path to an existing MP-DCCP flow
       45     3     2 =MP_FAST_CLOSE Close MP-DCCP flow
       45     var   3 =MP_KEY     Exchange key material for MP_HMAC
       45     7     4 =MP_SEQ     Multipath Sequence Number
       45     23    5 =MP_HMAC    HMA Code for authentication
       45     12    6 =MP_RTT     Transmit RTT values
       45     TBD   7 =MP_ADDADDR    TBD
       45     TBD   8 =MP_REMOVEADDR TBD
       45     TBD   9 =MP_PRIO       TBD

                       Figure 5: MP_OPT Option Types

Type=45           MP_OPT=0

Type=45  Length=11 MP_OPT=1
Type=45  Length=3 MP_OPT=2

Type=45           MP_OPT=3

Type=45  Length=7 MP_OPT=4

Type=45  Length=23 MP_OPT=5

Type=45  Length=12 MP_OPT=6

