Filter="intersect">
MsgDestination="RIDSystem">
MsgDestination="RIDSystem">
MsgDestination="SourceOfIncident">
MsgDestination="RIDSystem">
Justification="Authentication"/>
type="admin"/>
MsgDestination="RIDSystem">
targetNamespace="urn:ietf:params:xml:ns:iodef-rid-2.0"
elementFormDefault="qualified" attributeFormDefault="unqualified">
type="xs:language" use="required"/>
type="xs:string" use="optional"/>
type="xs:string" use="optional"/>
maxOccurs="unbounded"/>
use="optional"/>
type="xs:string" use="optional"/>
type="xs:string" use="optional"/>
maxOccurs="1"/>
maxOccurs="1"/>
maxOccurs="unbounded"/>
type="xs:string" use="optional"/>
type="xs:string" use="optional"/>
type="iodef:ExtensionType"/>
type="xs:anyURI"/>
type="iodef:ExtensionType"/>
