OU=Sipit Test Certificate Authority
OU=Sipit Test Certificate Authority
OU=Sipit Test Certificate Authority
OU=Sipit Test Certificate Authority
CN=b.example.com
OU=Sipit Test Certificate Authority
C=US
ST=California
L=San Jose
O=sipit
CN=b.example.com
C=US
ST=California
L=San Jose
O=sipit
OU=Sipit Test Certificate Authority
branch=z9hG4bK-c87542-240491824-1-c87542-
branch=z9hG4bK-c87542-240491824-1-c87542-;received=127.0.0.1
OU=Sipit Test Certificate Authority
CN=alice@a.example.com
OU=Sipit Test Certificate Authority
OU=Sipit Test Certificate Authority
CN=bob@b.example.com
OU=Sipit Test Certificate Authority
micalg=sha1;protocol=application/pkcs7-signature
rport=5070;received=127.0.0.1
rport=5070;received=127.0.0.1
micalg=sha1;protocol=application/pkcs7-signature
rport=5070;received=127.0.0.1
CONF=${OPENSSLDIR:=/usr/local/ssl}/openssl.cnf
subjectAltName=\${ENV::ALTNAME}
basicConstraints=CA:FALSE
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid,issuer:always
DAYS=1095
DAYS=$2
ADDR=$1

ALTNAME="$TYPE:${ADDR}"
LGeuw10rfJ0=
NWU4ZWY2MzItLQ==

pwqyKeskUIz9kzQ5bA0KLS03NWIzZDczYjRlMjRkM2Y2LS0=

