termstartparam  = "termstart" "=" (date-time / date)

termendparam  = "termend" "=" (date / date-time)

optimeparam  = "OPTIME" "=" (period-explicit / period-start)
period-explicit = time "/" time
period-start = time "/" dur-value

oprulesparam  =  (";" "BYDAY" "=" bywdaylist )          /
                   ( ";" "BYMONTHDAY" "=" bymodaylist )    /
                   ( ";" "BYYEARDAY" "=" byyrdaylist )


labelparam  = "LABEL" "=" text

ERMEND=20001230:Biljett Direkt
Personroleparam  = "ROLE" "=" text
      ; It is RECOMMENDED that the text value be
      ; chosen from a list, as described in
samplerolelist = (
thingroleparam  = "ROLE" "=" text
      ; It is RECOMMENDED that the text value be
      ; chosen from a list, as described in
samplerolelist2 =
thinksroleparam  = "ROLE" "=" text
      ; It is RECOMMENDED that the text value be
      ; chosen from a list, as described in
samplerolelist3 =
eventprop  = *(

       ; the following are optional,
       ; but MUST NOT occur more than once

categories = "CATEGORIES" catparam ":" text *(("."/",") text)
                     CRLF


       ; It is RECOMMENDED, when feasible, that the
       ; text value be chosen from a list,
       ; as described in
catparam   = *(

                   ; the following is optional,
                   ; but MUST NOT occur more than once

                   (";" languageparam ) /
                   ; the following is optional,
                   ; and MAY occur more than once

                   (";" xparam)

                   )

       )

title = "TITLE" titleparam ":" text CRLF

       ; It is RECOMMENDED, when feasible, that the
       ; text value be chosen from a list,
       ; as described in
titleparam  = *(
       ; the following is optional,
       ; but MUST NOT occur more than once
       (";" languageparam ) /

       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
       )

persons = "PERSONS" personsparam ":" text CRLF

      ; It is RECOMMENDED that the text value be
      ; chosen from a list, as described in
personsparam  = *(
      ; the following is optional,
      ; but MUST NOT occur more than once
      (";" languageparam ) /(";" personroleparam ) /

      ; the following is optional,
      ; and MAY occur more than once
      (";" xparam)
      )

thinks = "THINKS" thinksparam ":" text CRLF

      ; It is RECOMMENDED that the text value be
      ; chosen from a list, as described in
thinksparam  = *(
       ; the following is optional,
       ; but MUST NOT occur more than once

       (";" languageparam ) /(";" thinksroleparam ) /

       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
       )

things = "THINGS" thingsparam ":"
      text CRLF

      ; It is RECOMMENDED that the text value be
      ; chosen from a list, as described in
thingsparam  = *(
      ; the following is optional,
      ; but MUST NOT occur more than once
      (";" languageparam ) /(";" thingroleparam ) /


      ; the following is optional,
      ; and MAY occur more than once
      (";" xparam)
      )

partrel = "PARTREL" partrelparam ":" text CRLF

partrelparam  = *(
       ; the following is optional,
       ; but MUST NOT occur more than once

       (";" languageparam ) / (";" cnparam ) / (";" reltypeparam) /


       ; the following is optional,
       ; and MAY occur more than once

       (";" xparam)
       )

langue = "LANGUE" langueparam ":" language CRLF

langueparam  = *(
       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
       )

LANGUE = <Text identifying a language, as defined in

orientation = "ORIENTATION" orientationparam ":" text CRLF
      ; It is RECOMMENDED that the text value be
      ; chosen from a list, as described in
orientationparam  = *(
       ; the following is optional,
       ; but MUST NOT occur more than once
       (";" orienttypeparam ) /

       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
       )

orienttypeparam = *(";" "ORIENTTYPE" "=" text)
      ; It is RECOMMENDED that the text value be
      ; chosen from a list, as described in
whurl   = "WHURL" whurlparam ":" uri CRLF

whurlparam   = *(
       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
       )

skuid   = "SKUID" skuidparam ":" text CRLF

skuidparam   = *(
       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
       )
venue = "VENUE" venueparam ":" venuetype CRLF

venueparam  = *(
       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
       )

venuetype  =
       "Internet"/
       "Radio"/
       "TV" /
       "Outdoors"/
       "Indoors"/
       "Travel-transit"

directions = "DIRECTIONS" directionsparam ":" text CRLF

directionsparam  = *(
       ; the following is optional,
       ; but MUST NOT occur more than once
       (";" languageparam ) / (";" altrepparam ) /
       (";" travelbyparam) / (";" geo-path) /

       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
       )

travelbyparam = "TRAVELBY" "=" ("walk" / "bicycle" / "boat" /
    "car" / "rail" / "air" / "public_transportation" /
    "frequency" / "uri" )


      ; Implementers who do not intend to have a complex GUI for
      ; various types of directions could concatenate all DIRECTIONS
      ; fields which have a TRAVELBY parameter into one DIRECTIONS field
      ; without a TRAVELBY parameter

geo-path = "GEO-PATH" "=" 1*(float "," float ",")(float "," float)
    ; machine readable directions
    ; coordinate pair sequence approaching destination

placename = "PLACENAME" placeparam ":" text CRLF

      ; It is RECOMMENDED that the text value be
      ; chosen from a list, as described in
placeparam = *(
       ; the following is optional,
       ; but MUST NOT occur more than once
       (";" languageparam ) /
       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
    )

requirements = "REQUIRED" requireparam ":" text CRLF

      ; It is RECOMMENDED that the text value be
      ; chosen from a list, as described in
requireparam = *(
       ; the following is optional,
       ; but MUST NOT occur more than once
       (";" languageparam ) / (";" altrepparam )

       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
       )

Recommended = "RECOMMENDED" recommendedparam ":" text CRLF

      ; It is RECOMMENDED that the text value be
      ; chosen from a list, as described in
recommendedparam = *(
       ; the following is optional,
       ; but MUST NOT occur more than once
       (";" languageparam ) / (";" altrepparam )

       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
PROHIBITED = "PROHIBITED" prohibitedparam ":" text CRLF

      ; It is RECOMMENDED that the text value be
      ; chosen from a list, as described in
prohibitedparam = *(
       ; the following is optional,
       ; but MUST NOT occur more than once
       (";" languageparam ) / (";" altrepparam )

       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
       )

price = "PRICE" priceparam ":" price CRLF

priceparam = *(
       ; the following is optional,
       ; but MUST NOT occur more than once
       (";" languageparam ) / (";" altrepparam ) /
       (";" pricelabelparam) /
         (";" currencyparam)

       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
    )


pricelabelparam = *(";" "LABEL" "=" text)

      ; The text value COULD be
      ; chosen from a list, as described in
price = float

currencyparam =
      "CURRENCY" "=" <currency code as defined in
bookings = "BOOKINGS" bookingsparam ":" text CRLF

bookingsparam  = *(
       ; the following is optional,
       ; but MUST NOT occur more than once
       (";" languageparam ) / (";" altrepparam ) /

       (";" termstartparam) / (";" termendparam) /
       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
       )



handicap-facilities = "HANDICAP-FACILITIES"
     labelparam ":" boolean CRLF


      ; It is RECOMMENDED that the text value be
      ; chosen from a list, as described in
payment-method = "PAYMENT-METHOD"
     paymentparam ":" text CRLF

      ; It is RECOMMENDED that the text value be
      ; chosen from a list, as described in
paymentparam  =  *(
       ; the following is optional,
       ; but MUST NOT occur more than once
       (";" altrepparam )

       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
       )
promo = "PROMO" promoparam ":" uri CRLF

promoparam  = *(
       ; the following is optional,
       ; but MUST NOT occur more than once
       (";" languageparam ) /

       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
       )

control = "CONTROL" controlparam ":"
controlparam  = *(
       ; the following is optional,
       ; but MUST NOT occur more than once
       (";" languageparam ) / (";" cnparam ) / (";" roleparam)



       ; It is highly RECOMMENDED that SKICal objects actually
       ; use the cnparam since some applications will not
       ; bother to read the altrep'ed vCard.

       ; the following is optional,
       ; and MAY occur more than once

       (";" xparam)
       )
publisher = "PUBLISHER" publisherparam ":" mailto CRLF

publisherparam  = *(
       ; the following is optional,
       ; and MAY occur more than once
       (";" xparam)
       )

