attribute              =/ fingerprint-attribute

fingerprint-attribute  =  "fingerprint" ":" hash-func SP fingerprint

hash-func              =  "sha-1" / "md5" / "md2" / token
                             ; New hash functions must be registered
                             ; with IANA.
                             ; TODO: figure out what IANA registry
                             ; this should reference.

fingerprint            =  2UHEX *(":" 2UHEX)
                             ; Each byte in upper-case hex, separated
                             ; by colons.

UHEX                   =  DIGIT / %x41-46 ; A-F uppercase

v=0
o=me 2890844526 2890842807 IN IP4 10.1.1.2
s=Call me using TCP
t=3034423619 3042462419
c=IN IP4 10.1.1.2
m=image 54111 TLS t38
a=direction:passive
a=fingerprint:MD5 48:AA:D8:BA:36:7C:6D:70:7F:81:BB:BA:ED:6D:B8:C7

     Figure 2: Example SDP description offering a TLS media stream


