Registration_state = TRYING;
        /* HLR_list is list of HLRs MH is currently assigned to. */
        /* MH.IP is this mobile host∆s permanent IP address. */
        /* The second argument of query_TS specifies known HLRs */
        /* and third argument specifies total number of HLRs */
        /* desired. */

HLR_list = query_TS(MH.IP, HLR_list, r);
Pending_HLR = HLR_List;
Retries = 0;
Registration_state = SUCCESS;
Registration_state = PARTIAL_SUCCESS;
Pending_HLR = query_TS(MH.IP, HLR_List, Pending_HLR, r);
Pending_HLR = null;
HLR_list = query_TS(MH.IP, Pending_HLR, r);
Phase = 0;
Pending_HLR = select(HLR_list);
Retries = 0;
Pending_HLR = retrypolicy(Phase, Retries, r);
m = retrypolicy(Phase, Retries, r);   
HLR_list = query_TS(MH.IP, Pending_HLR, m);
Pending_HLR = null;
