Location-Checksum-MD5 = "Location-Checksum-MD5: " md5-checksum

Location-Checksum-SHA1 = "Location-Checksum-SHA1: " sha1-checksum

Location-Checksum-SHA256 = "Location-Checksum-SHA256: "
Location-Checksum-SHA512 = "Location-Checksum-SHA512: "
