Timeout            = "Timeout" ":" timeout-value
timeout-value      = 1*DIGIT

Connection-Timeout = "Connection-Timeout" ":" timeout-value
                        ; timeout-value from Timeout header

