z = MD5(sec1|saddr|sport|haddr|daddr|dport|sec1)
              + (MN-SEQ|CN-SEQ)
              + (counter << 27)
              + (MD5(sec2|counter|saddr|sport|haddr|daddr|dport|sec2)
                 % (1 << 27))

