generic-message              = start-line
                                  *message-header
                                  CRLF
                                  [ message body ]

start-line                   = Request-Line |
                                  Status-Line

message-header               = ( general-header
                                  | request-header
                                  | response-header
                                  | entity header )


Request-Line = Method SP Request-URI SP SIP-Version CRLF
Statue-Line = SIP-Version SP Status-Code SP Reason-Phrase CRLF
From = ( "From" | "f" ) ":" ( name-addr | addr-spec)
     *( ";" addr-params )
name-addr    = [display name] "<" addr-spec ">"
addr-spec    = SIP-URL|URI
display-name = *token|quoted-string
addr-params  = tag-param
tag-param    = "tag=" UUID
UUID         = 1*( hex | "-" )

To   = ( "To" | "t" ) ":" ( name-addr | addr-spec)
     *( ";" addr-params )
addr-params  = tag-param|alternate-param
alternate-param = instance "(" total ")"     ;instance <= total
instance     = 1*digit
total        = 1*digit

Record-Route =  "Record-Route" ":" 1# name-addr

Route                = "Route" ":" 1# name-addr|wildcard-addr

Wildcard-addr        = "*@" *("*" | domainlabel ".") ("*" | toplabel
No-Loop      = "noloop"

b= <Data rate> <Peak rate> <Burst rate>


i=<m> of <n>

f=<value>

r=<value>

s=<SIP-URL>
e=<SIP-URL>
c=<total data rate> <peak rate> <max burst>
f=<available data rate> <peak rate> <max burst>
l=<time (ms)>
r=<resource class>

n=<number of domains in list>
d=<domain.name>

d=london.sip.co.uk
d=harlow.sip.co.uk
d=cambridge.sip.co.uk

v=1
o=croydon 56348948 20159786 IN IP4 47.25.3.106
s=new session
b=8 32 64
f=6

