Liberty-NSS        =   1*(subStChar) 0*(":" 1*(subStChar))
subStChar       =   trans / "%" HEXDIG HEXDIG
trans           =   ALPHA / DIGIT / other / reserved
other           =   "(" / ")" / "+" / "," / "-" / "." /
                         "=" / "@" / ";" / "$" /
                         "_" / "!" / "*" / "'"
reserved        =   "%" / "/" / "?" / "#"

          The exclusion of the colon from the list of "other" characters
         means that the colon can only occur as a delimiter between
         string tokens.  Note that this ABNF rule set guarantees that
         any valid Liberty NSS is also a valid RFC2141 NSS.

         For example:

            urn:liberty:schemas:authctx:2002:05
            urn:liberty:schemas:core:2002:12


