dataTypeSemantics="identifier" elementId="301" status="current"
group="identifiers">
dataTypeSemantics="identifier" elementId="302" status="current"
group="identifiers">
dataTypeSemantics="identifier" elementId="303" status="current"
group="identifiers">





dataTypeSemantics="identifier" elementId="304" status="current"
group="sampling configuration">
dataTypeSemantics="quantity" elementId="305" status="current"
group="sampling configuration">
dataTypeSemantics="quantity" elementId="306" status="current"
group="sampling configuration">
dataTypeSemantics="quantity" elementId="307" status="current"
group="sampling configuration">
dataTypeSemantics="quantity" elementId="308" status="current"
group="sampling configuration">
dataTypeSemantics="quantity" elementId="309" status="current"
group="sampling configuration">
dataTypeSemantics="quantity" elementId="310" status="current"
group="sampling configuration">
dataTypeSemantics="quantity" elementId="311" status="current"
group="sampling configuration">
dataTypeSemantics="quantity" elementId="313" status="current"
group="packet data">
dataTypeSemantics="quantity" elementId="314" status="current"
group="packet data">
dataTypeSemantics="quantity" elementId="316" status="current"
group="packet data">
dataTypeSemantics="quantity" elementId="317" status="current"
group="packet data">
dataTypeSemantics="totalCounter" elementId="318" status="current"
group="statistics">
dataTypeSemantics="totalCounter" elementId="319" status="current"
group="statistics">
dataTypeSemantics="quantity" elementId="320" status="current"
group="statistics">
dataTypeSemantics="quantity" elementId="321" status="current"
group="statistics">
dataTypeSemantics="quantity" elementId="322" status="current"
group="timestamps">
dataType="dateTimeMilliseconds" dataTypeSemantics="quantity"
elementId="323" status="current" group="timestamps">
dataType="dateTimeMicroseconds" dataTypeSemantics="quantity"
elementId="324" status="current" group="timestamps">
dataType="dateTimeNanoseconds" dataTypeSemantics="quantity"
elementId="325" status="current" group="timestamps">
dataTypeSemantics="quantity" elementId="326" status="current"
group="hash configuration">
dataTypeSemantics="quantity" elementId="327" status="current"
group="hash configuration">
dataTypeSemantics="quantity" elementId="328" status="current"
group="hash configuration">
dataTypeSemantics="quantity" elementId="329" status="current"
group="hash configuration">
dataTypeSemantics="quantity" elementId="330" status="current"





group="hash configuration">
dataTypeSemantics="quantity" elementId="331" status="current"
group="hash configuration">
dataTypeSemantics="quantity" elementId="332" status="current"
group="hash configuration">
dataTypeSemantics="quantity" elementId="333" status="current"
group="hash configuration">
dataTypeSemantics="quantity" elementId="334" status="current"
group="hash configuration">
dataTypeSemantics="quantity" elementId="336" status="current"
group="statistics">
dataTypeSemantics="quantity" elementId="337" status="current"
group="statistics">
dataTypeSemantics="quantity" elementId="338" status="current"
group="statistics">
