a=fmtp:<dynamic payload type> <parameter 
m=video 49170 RTP/AVP 98 
a=rtpmap:98 vc1/90000 
a=fmtp:98 profile=0;level=2;width=352;height=288;framerate=15000; 
bitrate=384000;buffer=2000;config=4e291800 
    
