HB-URI     = "held+beep" ":" hier-part [ "?" query ]
hier-part  = "//" authority path-abempty / path-absolute
                    / path-rootless / path-empty
authority  =  host ":" port

                      Figure 4: The "held+beep:" URI

Request-URI-Header = "Request-URI" ":" Request-URI
                        ; Request-URI from RFC 2616

                     Figure 5: The Request-URI Header

