Data  =>(     uCDN    )<=   Logging
          //   `-.       _,-'   \\  Data
          ||        `-'-'-'      ||
CR = %x0D ; carriage return

DIGIT = %x30-39 ; 0-9

DQUOTE = %x22 ; " (Double Quote)

CRLF = CR LF ; Internet standard newline

HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F"

HTAB = %x09 ; horizontal tab

LF = %x0A ; linefeed

OCTET = %x00-FF ; 8 bits of data

host = as specified in section 3.2.2 of [RFC3986].

IPv4address = as specified in section 3.2.2 of [RFC3986].

IPv6address = as specified in section 3.2.2 of [RFC3986].

ADDRESS = IPv4address / IPv6address

DATE = 4DIGIT "-" 2DIGIT "-" 2DIGIT

         Dates are recorded in the format YYYY-MM-DD where YYYY, MM and
         DD stand for the numeric year, month and day respectively.  All
         dates are specified in Universal Time Coordinated (UTC).

DEC = 1*DIGIT ["." *DIGIT]

QSTRING = DQUOTE *NDQUOTE DQUOTE ; where
NDQUOTE = <any OCTET excluding DQUOTE> / 2DQUOTE ; whereby a
NHTABSTRING = *NHTAB ; where

NHTAB = <any OCTET excluding HTAB>

TIME = 2DIGIT ":" 2DIGIT ":" 2DIGIT ["." *DIGIT]

         Times are recorded in the form HH:MM:SS or HH:MM:SS.S where HH
         is the hour in 24 hour format, MM is minutes and SS is seconds.
         All times are specified in Universal Time Coordinated (UTC).

DIRLINE = "#" directive CRLF

DIRGROUP = 1*DIRLINE

RECLINE = <CDNI Logging Record> CRLF

RECGROUP = *RECLINE

directive = DIRNAME ":" HTAB DIRVAL

DIRNAME = any CDNI Logging Directive name registered in the CDNI
DIRVAL = <directive value as specified below for each directive
FIEVAL = <CDNI Logging Field value>

rel="self" type="application/atom+xml" />
rel="current" type="application/atom+xml" />
rel="prev-archive" type="application/atom+xml" />
type="application/cdni.LoggingFile" />
type="application/cdni.LoggingFile" />
