ILL=L for the interleave group that starts at audio frame n.  We also
ILL=L, ILP=0,
ILL=L, ILP=1,
ILL=L, ILP=L,
m=audio 49120 RTP/AVP 98
a=rtpmap:98 AMR-WB+/96000
a=fmtp:98 interleaving=30
a=maxptime:100

