cksum="1924040625 268">
cksum="2670296305 91797970">
cksum="2670296305 91797970">
cksum="2670296305 91797970">
type="eppcom:roidType".

type="eppcom:clIDType".
type="eppcom:statusType".

type="eppcom:clIDType".

type="eppcom:clIDType".

type="eppcom:clIDType".

type="eppcom:clIDType".

type="datetime".

type="eppcom:trStatusType".

type="positiveInteger".

type="normalizedString".

type="boolean".

cksum="2670296305 91797970">
cksum="2670296305 91797970">
cksum="2670296305 91797970">
cksum="2670296305 91797970">
cksum="2670296305 91797970">
cksum="2670296305 91797970">
cksum="2670296305 91797970">
cksum="2670296305 91797970">
cksum="1410255126 216">
cksum="2670296305 91797970">
type="eppcom:minTokenType".

cksum="1410255126 216">
cksum="1410255126 216">
type="contact:postalLineType".  An OPTIONAL "isLoc" attribute
type="contact:optPostalLineType".  An OPTIONAL "isLoc"
type="contact:pcType".  An OPTIONAL "isLoc" attribute to used
type="contact:ccType".  An OPTIONAL "isLoc" attribute to used
cksum="2670296305 91797970">
cksum="2670296305 91797970">
cksum="2670296305 91797970">
cksum="2670296305 91797970">
type="boolean".

type="boolean".

type="boolean". with type="boolean".

type="boolean".

type="boolean".

cksum="2670296305 91797970">
cksum="2670296305 91797970">
type="normalizedString".

type="positiveInteger".

type="csvRegistrar:statusValueType".

type="anyURI".

cksum="1924040625 268">
cksum="1924040625 268">
cksum="1924040625 268">
type="csvRegistrar:contactTypeType", which is an enumerated
cksum="2186160075 371">
cksum="2186160075 371">
cksum="2670296305 91797970">
cksum="1924040625 268">
cksum="1924040625 268">
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

schemaLocation="eppcom-1.0.xsd"/>
schemaLocation="rde-1.0.xsd"/>

substitutionGroup="rde:content"/>


minOccurs="0"/>
substitutionGroup="rde:delete"/>

minOccurs="0"/>
abstract="true"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
default="eppcom\:labelType"/>
substitutionGroup="rdeCsv:field"/>
default="eppcom\:roidType"/>
substitutionGroup="rdeCsv:field"/>
default="eppcom\:clIDType"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
default="eppcom\:clIDType"/>
default="true"/>
default=","/>
substitutionGroup="rdeCsv:field"/>
default="eppcom\:statusType"/>
default="true"/>
default=","/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
default="eppcom\:clIDType"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
default="datetime"/>
default="boolean"/>
default="unsignedbyte"/>
default="unsignedShort"/>
default="hexBinary"/>
substitutionGroup="rdeCsv:field"/>
default="language"/>
substitutionGroup="rdeCsv:field"/>
default="eppcom\:trStatusType"/>
default="token"/>
default="positiveInteger"/>
substitutionGroup="rdeCsv:field"/>
default="normalizedString"/>
substitutionGroup="rdeCsv:field"/>
default="token"/>
maxOccurs="unbounded"/>
default="UTF-8"/>
substitutionGroup="rdeCsv:field"/>
default="anyURI"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">
schemaLocation="eppcom-1.0.xsd"/>
schemaLocation="domain-1.0.xsd"/>
schemaLocation="secDNS-1.1.xsd"/>
schemaLocation="rgp-1.0.xsd"/>
schemaLocation="rde-1.0.xsd"/>
schemaLocation="rdeCsv-1.0.xsd"/>

substitutionGroup="rde:contents"/>

type="csvDomain:fRgpStatusesType"
substitutionGroup="rdeCsv:field"/>
default="rgp\:statusType"/>
default="true"/>
default=","/>
substitutionGroup="rdeCsv:field"/>
default="eppcom\:labelType"/>
default="true"/>
default=","/>
substitutionGroup="rdeCsv:field"/>
default="secDNS\:maxSigLifeType"/>
substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>
default="secDNS\:keyType"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">
schemaLocation="eppcom-1.0.xsd"/>
schemaLocation="host-1.0.xsd"/>
schemaLocation="rde-1.0.xsd"/>
schemaLocation="rdeCsv-1.0.xsd"/>

substitutionGroup="rde:contents"/>

substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
default="host\:addrStringType"/>
default="true"/>
default=","/>
substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

schemaLocation="eppcom-1.0.xsd"/>
schemaLocation="contact-1.0.xsd"/>
schemaLocation="rde-1.0.xsd"/>
schemaLocation="rdeCsv-1.0.xsd"/>

substitutionGroup="rde:contents"/>

substitutionGroup="rdeCsv:field"/>
default="eppcom\:clIDType"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
default="contact\:e164StringType"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>
default="eppcom\:minTokenType"/>
substitutionGroup="rdeCsv:field"/>
default="contact\:postalInfoEnumType"/>
default="contact\:postalLineType"/>
default="contact\:optPostalLineType"/>
substitutionGroup="rdeCsv:field"/>


substitutionGroup="rdeCsv:field"/>


substitutionGroup="rdeCsv:field"/>
use="required"/>
substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>
default="contact\:pcType"/>
substitutionGroup="rdeCsv:field"/>
default="contact\:ccType"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
default="boolean"/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

schemaLocation="eppcom-1.0.xsd"/>
schemaLocation="domain-1.0.xsd"/>
schemaLocation="contact-1.0.xsd"/>
schemaLocation="rde-1.0.xsd"/>
schemaLocation="rdeCsv-1.0.xsd"/>

substitutionGroup="rde:contents"/>

substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>

default="normalizedString"/>
type="rdeCsv:fPositiveIntegerType"
substitutionGroup="rdeCsv:field"/>

substitutionGroup="rdeCsv:field"/>
substitutionGroup="rdeCsv:field"/>
default="csvRegistrar\:statusType"/>
substitutionGroup="rdeCsv:field"/>

type="csvRegistrar:contactTypesType"
substitutionGroup="rdeCsv:field"/>
default="csvRegistrar\:contactTypeType"/>
default="true"/>
default=","/>
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

schemaLocation="rde-1.0.xsd"/>

substitutionGroup="rde:contents"/>

