Resource-ID = h(coap://overlay-1.com/proxy-1/.well-known/core?ep=9996172)
KEY =    9996172,
VALUE = {<./temperature-1>;ct=41;rt="TemperatureC";if="sensor", <./temperature-2>;ct=41;rt="LightLux";if="sensor",}

   Note that the Resource-ID stored in the overlay is calculated as hash
   over the URI (i.e. h(URI)), for instance SHA-1.

   This action informs any other node performing a lookup for the
   previous URI "coap://overlay-1.com/proxy-1/.well-known/
   core?ep=9996172" that the Node-ID value for peer is "9996172".

Resource-ID = h(coap://overlay-1.com/proxy-1/.well-known/core?ep=9996172)
KEY =    9996172,
VALUE = {<./temperature-1>;ct=41;rt="TemperatureC";if="sensor",
 ? ? ?     ?<./temperature-2>;ct=41;rt="LightLux";if="sensor",}


   The obtained KEY is the Node-ID of the peer that is responsible of
   this KEY/VALUE pair.  The VALUE is the set of resource descriptions
   that are necessary to read data from the endpoints.

        Req: GET coap://overlay-1.com/proxy-1/.well-known/core?ep=9996172

