PMnUN2IiaLHJv8nKZ7cPRSJReF3pUYDPTHRyCsp58qeaPLjXQquje5bUpKSk=}

zdR93eX5B9ZKBQg1HHWCsHbqQtmNLQ==|)))

qQtmNLSkpKQ==}

ybmFsLmFjbWUuY29tL2FjY291bnRpbmcvKSkpKQ==}
s1 = i2
d1 = "t"
a = the intersection of a1 and a2
v = the intersection of v1 and v2

