sms-email = ["/"] sms-address ["/"] "@" mta-I-sms

mta-I-sms = domain

sms-address = sms-mbox [ via-qualifier ] [ net-qualifier ]
                        [1*( qualif-type1) ]

sms-mbox = "SMS=" gstn-phone

via-qualifier = "VIA=" message-centre-id

message-centre-id = gstn-phone

value             = message-centre-id
message-centre-id = gstn-phone
net-qualifier = "NET=" network-type
network-type = "GSM" / other-type
other-type   = string

value        = network-type
network-type = "GSM" / other-type
other-type   = string

SMS=+448957375644@smsgateway.org

SMS=+44-5869-318945@smsservice.org

SMS=07044573897@smsservice.org

SMS=07044573897/VIA=+358-50-123-1234@smsservice.org

SMS=+44-8934-349856/VIA=+358-50-123-1234/NET=GSM@smsgateway.org


sms-email = ["/"] sms-address ["/"] "@" mta-I-sms

mta-I-sms = domain

sms-address = sms-mbox [ via-qualifier ] [ net-qualifier ]
                        [1*( qualif-type1) ]

sms-mbox = "SMS=" gstn-phone

via-qualifier = "VIA=" message-centre-id

net-qualifier = "NET=" network-type

message-centre-id = gstn-phone

network-type = "GSM" / other-type

other-type   = string

qualif-type1 = "/" keyword "=" string

keyword = 1*( DIGIT / ALPHA / "-" )

string = PCHAR

gstn-phone = ( global-phone / local-phone )

global-phone = "+" 1*( DIGIT / written-sep )
local-phone = [ exit-code ] [ dial-number ]

exit-code = phone-string

dial-number = phone-string

phone-string = 1*( DTMF / pause / tonewait / written-sep )

DTMF = ( DIGIT / "#" / "*" / "A" / "B" / "C" / "D" )

written-sep = ( "-" / "." )

pause = "p"

tonewait = "w"



value               = message-centre-id
message-centre-id  = gstn-phone

value        = network-type
network-type = "GSM" / other-type
other-type   = string

