capability_cmd =  tag SP "CAPABILITY"  
lemonadeprovision_cmd = tag SP "LEMONADEPROVISION" SP device-id 
lemonadegetpref_cmd =tag SP "LEMONADEGETPREFS" SP "("  
                        lemonade_pref_list ")" 
lemonade_pref_list = lemonade_pref [SP lemonade_pref_list] 
lemonade_pref = (LEMONADE_OUTBAND_ADDRESS /  
                 LEMONADE_OUTBAND_CHANNEL / LEMONADE_INBAND_NEW_FORMAT / 
                 LEMONADE_INBAND_PUSH)  
pref-pair = "(" lemonade-pref SP lemonade-pref-val [pref-pair] ")"    
lemonadesetpref_cmd =   tag SP "LEMONADESETPREF" SP 
         (("LEMONADE_OUTBAND_ADDRESS" SP device_address) /    
          ("LEMONADE_OUTBAND_CHANNEL" SP ("SMS"/"JMS"/"WAP_PUSH"/ 
         "MMS"/"NONE")) /  
          ("LEMONADE_INBAND_NEW_FORMAT" SP fetch_criteria) / 
          ("LEMONADE_INBAND_PUSH" SP ("ON" / "OFF"))  
        
lemonadezip_cmd = tag SP "LEMONADEZIP" SP command  
lemonadedeliver_cmd =tag SP "LEMONADEDELIVER" SP  
                  ("N" / ("R"/"F") SP folder SP uid SP ("Y" / "N"))     
                  [SP "SAVETO="  folder]  
                  SP  "{" number ["+"] "}"   
                  internet_msg 
lemonadeconvert_cmd = tag SP "LEMONADECONVERT" message-sequence-
lemonadeuidconvert_cmd =tag SP "UID" SP "LEMONADECONVERT" uid SP 
lemonadepsearch_cmd = tag SP "LEMONADEPSEARCH" [SP "CHARSET" SP 
