elementFormDefault="qualified"
xmlns="urn:ietf:params:xml:ns:rlmi"
name="Buddy List" fullState="true">
start="<nXYxAE@pres.example.com>";boundary="50UBfW7LSCVLtggUPe5z"
name="Buddy List at COM" fullState="true">
entity="sip:bob@example.com">
entity="sip:dave@example.com">
micalc="pgp-md5";boundary="l3WMZaaL8NpQWGnQ4mlU"
start="<Cvjpeo@example.org>";boundary="tuLLl3lDyPZX0GMr2YOo"

name="Buddy List at ORG" fullState="true">
entity="sip:joe@example.org">
entity="sip:mark@example.org">
start="<2BEI83@pres.example.com>";boundary="TfZxoxgAvLqgj4wRWPDL"
name="Buddy List at COM" fullState="false">
micalc="pgp-md5";boundary="l3WMZaaL8NpQWGnQ4mlU"

start="<Cvjpeo@example.org>";boundary="tuLLl3lDyPZX0GMr2YOo"

name="Buddy List at ORG" fullState="true">
entity="sip:joe@example.org">
entity="sip:mark@example.org">
content="text/html;charset=utf-8"/>
