accept = application/oblivious-dns-message
cache-control = no-cache, no-store
content-type = application/oblivious-dns-message
content-length = 106

content-type = application/oblivious-dns-message
content-length = 154

aad = 0x01 || key_id
ct = context.Seal(aad, Q_plain)
Q_encrypted = enc || ct
aad = 0x01 || key_id
aad = 0x02 || 0x0000
R_encrypted = Seal(Q_plain.response_key, 0^Nn, aad, R_plain)
aad = 0x02 || 0x0000
R_plain = Open(response_key, 0^Nn, aad, R_encrypted)
