value = (byte[0] << 8*(n-1)) | (byte[1] << 8*(n-2)) |
               ... | byte[n-1];

L_S = length in bytes of secret;
L_S1 = L_S2 = ceil(L_S / 2);
key_block = PRF(SecurityParameters.master_secret,
                          "key expansion",
                          SecurityParameters.server_random +
                          SecurityParameters.client_random);

master_secret = PRF(pre_master_secret, "master secret",
                           ClientHello.random + ServerHello.random)
RSA = none
