UE    = User Equipment
RAN   = Radio access network
SGSN  = Serving GPRS Support Node
GGSN  = Gateway GPRS Support Node
HSS   = Home Subscriber Server (holds subscriber profile)
GTP   = GPRS Tunneling Protocol

           Figure 1: Third Generation GPRS Mobile Access Network

UE   = User Equipment
RAN  = Radio Access Network
SGW  = Serving Gateway
PGW  = Packet Data Network (PDN) Gateway
MME  = Mobility Management Entity
PCRF = Policy and Charging Rules Function
HSS  = Home Subscriber Server

