NK = no key type flags (bits 0 and 1 on)
AL = algorithm byte
PR = protocols indicated by protocol byte or future assigned flags

labels= |  0  |   1  |    2   |      3   |      4   |
data = RDATA | RR(s)...

hash = MD5 ( data )

signature = ( 01 | FF* | 00 | prefix | hash ) ** e (mod n)

data = full response (less transaction SIG) | full query

USER      =0
ZONE      =1
HOST      =2 (host or other end entity)
