version="1"
state="full"
targetNamespace="urn:ietf:params:xml:ns:cpim-plidf"
schemaLocation="TBD"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
use="required"/>
content="text/html;charset=iso-8859-1"/>
