bitmask = 0x000000ff

bitmask = 0x0000000f

MRTT = 200*(scope/63)^2 milliseconds

RTT = t2 - t1 - delay

MRTT = ALPHA*MRTT + (1 - ALPHA)*RTT

MRTT = MRTT + ((RTT - MRTT) >> 3)

population = number of responders/probability.

