secondaries = A, C, D}. An RBridge, aware of this grouping, attached
Frame-VLAN = Determine Frame VLAN per Section 4.1.3;
Frame-priority = Determine Frame Priority per Section 4.1.3;
Frame-protocol = Extract Frame Ethertype / NSAP;

AF = Appointed Forwarder status of RBn for Frame-VLAN for
           receiving port;

returnValue = Execute 5.2.4.1;
returnValue = Execute 5.2.4.2;
returnValue = True;
returnValue = False;
returnValue = True;
Ethertype = VLAN Tag;
