if      = IfIndex
IpVer   = vrrpOperationsIpVersion
VrId    = vrrpOperationsVrId
State   = vrrpOperationsState
Prior   = vrrpOpeartionsPriority
AddrType= vrrpOperationsIpAddrType
IpAddr  = vrrpOperationsMasterIpAddr

Intf = I1                    Intf = I2
VRID = 1      |   VRID=2       VRID=2      |    VRID = 1
                     |                            |
