type=value

attribute          = (att-field ":" att-value) / att-field
att-field          = token
att-value          = byte-string

extension-config-list = ["+"] ext-cap-name "="
                                  ext-cap-list
ext-cap-name          = 1*(ALPHA / DIGIT)
ext-cap-list          = 1*VCHAR  ; defined in RFC5234

sel-extension-config = ext-cap-name "=" 1*VCHAR

b=<bwtype>:<bandwidth>

att-field       = "bcap"
att-value       = bw-cap-num 1*WSP bwtype ":" bandwidth
bw-cap-num      = 1*10(DIGIT)   ; defined in RFC5234

extension-config-list  = bandwidth-config-list
bandwidth-config-list  = ["+"] "b=" bw-cap-list *(BAR bw-cap-list)
bw-cap-list            = bw-cap-num *("," bw-cap-num)
bw-cap-num             = 1*10(DIGIT)   ; defined in RFC5234

       Figure 1: Syntax of the bandwidth parameter in lcfg and pcfg
                                attributes

ext-cap-name = "b"

sel-extension-config = sel-bandwidth-config
sel-bandwidth-config = "b=" bw-cap-list  ; bw-cap-list as above.

      Figure 2: Syntax of the bandwidth parameter in acfg attributes

a=icap:1 Document Camera

att-field       = "icap"
att-value       = mtitle-cap-num 1*WSP text
                               ; text is defined in RFC4566
mtitle-cap-num    = 1*10(DIGIT)   ; defined in RFC5234

ext-cap-name = "i"

ext-cap-list = mtitle-cap-list

extension-config-list = mtitle-config-list
mtitle-config-list    = ["+"] "i=" mtitle-cap-list
mtitle-cap-list       = mtitle-cap-num *(BAR mtitle-cap-num); BAR defined in RFC5939
mtitle-cap-num        = 1*10(DIGIT) ; defined in RFC5234

   Figure 3: Syntax of the media title capability parameter in lcfg and
                              pcfg attributes

   Each potential capability configuration contains a single media title
   capability attribute number where 'mtitle-cap-num' is the media title
   capability number defined explicitly earlier in this document, and
   hence must be between 1 and 2^31-1 (both included).  The media title
   capability allows the expression of only a single capability in each
   alternative, since no more than a single media title field is
   permitted per media block.  Nevertheless, it is still allowed to
   express alternative potential media title configurations separated by
   a vertical bar ("|").

   For sake of consistency, we allow the configuration attribute to be
   prefixed with the plus ("+") sign, indicating that the extension is
   mandatory and MUST be supported in order to be used.

