cn=http,cn=www.example.com,cn=inetResources,dc=example,dc=com 
      
cn=http,cn=www.example.com,cn=inetResources, 
dc=example,dc=com 
dc=com" if the defaults are used. 
      
cn=inetResources,dc=example,dc=com". 
      
dc=com" as the search base, and the global query defaults 
