destination = home agent)
destination = care-of address)
destination = home agent)
destination = home address)
destination = home agent)
destination = correspondent node)
destination = care-of address)
destination = home address)
destination = home agent)
destination = care-of address)
destination = home agent)
destination = correspondent node)
destination = care-of address)
destination = home address)
proto = MH
proto = MH
source = home_address_1 & destination = home_agent_1 &
proto = MH
source = home_agent_1 & destination = home_address_1 &
proto = MH

proto = MH
proto = MH
source = home_agent_1 & destination = home_address_1 &
proto = MH
source = home_address_1 & destination = home_agent_1 &
proto = MH

source = home_address_1 & destination = any &
proto = MH
source = any & destination = home_address_1 &
proto = MH
source = home_address_1 & destination = any & proto = MH
source = any & destination = home_address_1 & proto = MH

source = any & destination = home_address_1 &
proto = MH
source = home_address_1 & destination = any &
proto = MH
source = any & destination = home_address_1 & proto = MH
source = home_address_1 & destination = any & proto = MH

proto = ICMPv6
proto = ICMPv6
source = home_address_1 & destination = home_agent_1 &
proto = ICMPv6
source = home_agent_1 & destination = home_address_1 &
proto = ICMPv6

proto = ICMPv6
proto = ICMPv6
source = home_agent_1 & destination = home_address_1 &
proto = ICMPv6
source = home_address_1 & destination = home_agent_1 &
proto = ICMPv6


source = home_address_1 & destination = any &
proto = X
source = any & destination = home_address_1 &
proto = X
source = home_address_1 & destination = any & proto = X
source = any & destination = home_address_1 & proto = X

source = any & destination = home_address_1 &
proto = X
source = home_address_1 & destination = any &
proto = X
source = any & destination = home_address_1 & proto = X
source = home_address_1 & destination = any & proto = X

proto = MH
proto = MH
proto = MH
proto = MH
source = home_address_1 & destination = any &
proto = MH
source = any & destination = home_address_1 &
proto = MH
source = any & destination = home_address_1 &
proto = MH
source = home_address_1 & destination = any &
proto = MH
proto = ICMPv6
proto = ICMPv6
proto = ICMPv6
proto = ICMPv6
source = home_address_1 & destination = any &
proto = X
source = any & destination = home_address_1 &
proto = X
source = any & destination = home_address_1 &
proto = X
source = home_address_1 & destination = any &
proto = X
destination = home agent)
destination = home agent)
destination = home agent)
destination = home agent)
destination = home agent)
destination = home agent)
destination = home agent)
destination = home address)
destination = home address)
destination = home address)
destination = care-of address)
destination = care-of address)
destination = home address)
destination = home address)
destination = correspondent node)
destination = home agent)
destination = correspondent node)
destination = home agent)
destination = correspondent node)
destination = correspondent node)
destination = home address)
destination = care-of address)
destination = home address)
destination = care-of address)
destination = home address)
destination = home address)
destination = home agent)
destination = home agent)
destination = care-of address)
destination = home agent)
destination = care-of address)
