payto-URI = "payto" "://" method account [ "?" params ]
params = param *( "&" param )
param = (generic-param / method-specific-param) "=" *pchar
generic-param = "amount" / "recipient-name" / "sender-name" /
                  "message" / "instruction"
method-specific-param = *pchar
method = <authority, see [RFC3986], Section 3.2>
account = <path-abempty, see [RFC3986], Section 3.3>
pchar = <pchar, see [RFC3986], Appendix A.>
amount = [ currency ":" ] unit [ "." fraction ]
currency = 1*ALPHA
unit = 1*(DIGIT / ",")
fraction = 1*(DIGIT / ",")
amount = [ currency ":" ] unit [ "." fraction ]
currency = 1*ALPHA
unit = 1*(DIGIT / ",")
fraction = 1*(DIGIT / ",")


