P = Plaintext (to be encrypted and authenticated)
A = Associated Data (to be authenticated only)
X = neither encrypted nor authenticated





P = Plaintext (to be encrypted and authenticated)
A = Associated Data (to be authenticated only)
X = neither encrypted nor authenticated

A = Associated Data (to be authenticated only)
X = neither encrypted nor authenticated

srtp-crypto-suite-ext = "AEAD_AES_128_GCM"    /
                              "AEAD_AES_256_GCM"    /
                              "AEAD_AES_128_GCM_8"  /
                              "AEAD_AES_256_GCM_8"  /
                              "AEAD_AES_128_GCM_12" /
                              "AEAD_AES_256_GCM_12" /
                              "AEAD_AES_128_CCM"    /
                              "AEAD_AES_256_CCM"    /
                              srtp-crypto-suite-ext
   
