REQUEST-ID=a 
REQUEST-ID=a 
number-path=0xFFFF, the N bit must be set to 1. 
    
bit=1 in the NB-PATH object of the request), then the 
number-path=M. The PCE will also include a PATH-
REQUEST-ID=a 
Suggested-value=y 
    
REQUEST-ID=a 
REQUEST-ID=a, L bit=1 
REQUEST-ID=d, L bit=1 
REQUEST-ID=b 
Suggested-value=y∆ 
REQUEST-ID=c 
Suggested-value=z∆ 
Path_correlation=0x02 (Node diversely routed paths) 
REQUEST_ID=a 
REQUEST_ID=a 
REQUEST_ID=a 
L=0x00 the subobject identifies a link address the computed path must 
L=0x01 the subobject identifies a node address the computed path must 
L=0x02 the subobject identifies an Autonomous System the computed     
L=0x03 the subobject identifies a SRLG the computed path must avoid. 
    
