VID = VLAN ID                   802.1ad       +---------+ 
C-VID = Customer VID                          | B-VID   | 
S-VID = Service VID                           +---------+ 
I-SID = Service ID                            |B-Src MAC| 
B-VID = Backbone VID                          +---------+ 
