xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    S:   <config xmlns="http://example.com/schema/1.2/config">
    S:     <users>
    S:       <user><name>root</name><type>superuser</type></user>
    S:       <user><name>fred</name><type>admin</type></user>
    S:       <user><name>barney</name><type>admin</type></user>
    S:     </users>
    S:   </config>
    S: </rpc-reply>
    S: ]]>]]>
