ALPHA = 0.125 // RFC 6298
BETA = 0.25 // RFC 6298
W_STRONG = 0.5
W_WEAK = 0.25

RTTVAR_strong = (1 - BETA) * RTTVAR_strong
                     + BETA * (RTT_strong - RTT);
RTT_strong  = (1 - ALPHA) * RTT_strong + ALPHA * RTT;
E_strong = RTT_strong  + 4 * RTTVAR_strong;
RTO = W_STRONG * E_strong + (1 - W_STRONG) * RTO;
RTTVAR_weak = (1 - BETA) * RTTVAR_weak
                   + BETA * (RTT_weak - RTT);
RTT_weak  = (1 - ALPHA) * RTT_weak + ALPHA * RTT;
E_weak = RTT_weak  + 1 * RTTVAR_weak;
RTO = W_WEAK * E_weak + (1 - W_WEAK) * RTO
RTO = 2 * RTO;
lastUpdatedTime = getCurrentTime();
RTO = 1s + 0.5 * RTO;
lastUpdatedTime = getCurrentTime();
RTO = RTO * 3;
RTO = RTO * 1.5;
RTO = RTO * 2;
E_strong_ = R' + G,

E_weak_ = RW' + max(G, RW'/2) = 3 * R'
