L_g = a * T_new / (t * C_g) + (1- a) * L'_g, where 0 < a <= 1  (1) 

V_n =  a*(t_n - mean(t_n))^2 + (1- a)*V_n-1, where 0 < a <= 1  (3) 

M_g = W * H_g + L_g         (4) 

M_g = H * V_n               (5) 

M_g = L_g * V_n             (6) 

