Delay = C*(1+a/16)* 2^b  [in milliseconds]

N_neighbor_main_addr == main address of
                                       L_neighbor_iface_addr

N_neighbor_main_addr == main address of
                                       L_neighbor_iface_addr

N_neighbor_main_addr = main address of
                                      L_neighbor_iface_addr
                                      (from the link tuple)

Delay = C*(1+a/16)* 2^b  [in milliseconds]

C = 1/16 seconds (equal to 0.0625 seconds). 


Delay = C*(1+a/16)* 2^b  [in milliseconds]

