dataType="basicList" 
group="structured-data" 
dataTypeSemantics="List" 
elementId="XXX" applicability="all" status="current"> 
dataType="subTemplateList" 
group="structured-data" 
dataTypeSemantics="List" 
elementId="XXX" applicability="all" status="current"> 
dataType="subTemplateMultiList" 
group="structured-data" 
dataTypeSemantics="List" 
elementId="XXX" applicability="all" status="current"> 
minOccurs="1" maxOccurs="unbounded"> 
use="required"/> 
              </complexType> 
            </element> 
          </sequence> 
        </complexType> 
       
        <element name="structuredDataTypeSemantics" 
type="structuredDataTypeSemantics"> 
