Originator = "Originator" ":" absoluteURI

Recipient = "Recipient" ":" 1#absoluteURI

end="20040902T235959Z">
end="20041121T235959Z">
caseless="no">20041121-FEEBDAED@foo.org</C:text-match>
caseless="yes">mailto:jsmith@foo.org</C:text-match>
