b=MSR: <bandwidth-value> ; see [7] for ABNF definition.

MSR-bandwidth-def = "b" "=" "MSR" ":" bandwidth-value CRLF

bandwidth-value = 1*DIGIT

m=video 34564 RTP/AVP 96
a=rtpmap:96 h263-1998/90000
a=fmtp:96 profile=0; level=45;
b=TIAS:128000
a=maxprate:20
a=recvonly
m=video 46236 RTP/AVP 96
a=rtpmap:96 h263-1998/90000
a=fmtp:96 profile=0;level=45;
a=sendonly

m=video 34564 RTP/AVP 96
a=rtpmap:96 h263-1998/90000
a=fmtp:96 profile=0; level=45;
b=TIAS:128000
a=maxprate:20
a=recvonly


m=video 46236 RTP/AVP 96
a=rtpmap:96 h263-1998/90000
a=fmtp:96 profile=0;level=45;
b=MSR:64000
a=sendonly
br-last-hop = MSR + (MSPR * PPO)

SB = (Actual MSR + Actual packet rate * PPO over the receiver's
m=video <>
b=TIAS:128000 (bps)
b=RB:140800   (bps)
a=PPO:40  (bytes)
b=MSR:64000 (bps)
m=video <>
b=TIAS:64000 (bps)
b=RB:76800   (bps)
a=PPO:40  (bytes)
b=MSR:64000 (bps)
b=SB:72000; MSPR:25
m=video <>
b=TIAS:256000  (bps, supported by the decoder)
b=ERB:190000   (bps, signaled by the access network)
b=RB:140000    (bps, signaled by the access network)
a=PPO:40  (bytes)
b=ESB:100000 (bps, signaled by the access network)
b=SB:72000; MSPR:25


m=video <>
b=ERB:84000 (bps)
b=RB:72000   (bps)
a=PPO:40  (bytes)
b=ESB:190000  (bps)
b=SB:140000; MSPR:25
b=MSR:128000 (bps)
