targetNamespace="urn:iana:xmlns:domdir1"
elementFormDefault="qualified" >

type="domdir:handleType" />
type="domdir:domainNameType" />
type="domdir:lookupDomainType"
substitutionGroup="xdap:query" />

type="domdir:domainNameType"
minOccurs="0" maxOccurs="1" />
type="domdir:listSponsorsType"
substitutionGroup="xdap:query" />

type="domdir:domainNameType"
minOccurs="0" maxOccurs="1" />
minOccurs="1" maxOccurs="1">
minOccurs="0" maxOccurs="1">
type="domdir:findDomainByHolderType"
substitutionGroup="xdap:query" />

type="domdir:domainNameType"
minOccurs="0" maxOccurs="1" />
minOccurs="1" maxOccurs="1" >
minOccurs="0" maxOccurs="1" >
type="domdir:findDomainByNameType"
substitutionGroup="xdap:query" />

type="domdir:handleType" />
type="domdir:lookupContactType"
substitutionGroup="xdap:query" />

minOccurs="1" maxOccurs="1" >
minOccurs="0" maxOccurs="1" >
type="token"
minOccurs="0" maxOccurs="1" />
type="domdir:findContactsType"
substitutionGroup="xdap:query" />

type="domdir:handleType" />
type="domdir:domainNameType" />
type="domdir:dotQuadIPv4Type" />
type="domdir:textIPv6AddressType" />
type="domdir:lookupHostType"
substitutionGroup="xdap:query" />

type="domdir:domainNameType" />
type="domdir:findHostsByDomainType"
substitutionGroup="xdap:query" />

type="domdir:domainNameType" />
type="anyURI"
minOccurs="0" maxOccurs="1" />
type="anyURI"
minOccurs="0" maxOccurs="unbounded" />
type="domdir:contactInfoType"
minOccurs="0" maxOccurs="1" />
minOccurs="0" maxOccurs="unbounded" >
type="anyURI" />
type="token" />
type="domdir:domainType"
substitutionGroup="xdap:result" />

type="xdap:searchContinuationType"
minOccurs="0" maxOccurs="unbounded" />
type="domdir:sponsorsType"
substitutionGroup="xdap:result" />

type="domdir:domainType"
minOccurs="0" maxOccurs="unbounded" />
type="domdir:domainsType"
substitutionGroup="xdap:result" />

type="domdir:handleType"
minOccurs="0" maxOccurs="1" />
type="domdir:domainNameType" />
minOccurs="1" maxOccurs="unbounded" >
type="domdir:dotQuadIPv4Type" />
type="anyURI"
minOccurs="0" maxOccurs="1" />
type="domdir:textIPv6AddressType" />
type="anyURI"
minOccurs="0" maxOccurs="1" />
type="anyURI" />
type="domdir:hostInfoType"
substitutionGroup="xdap:result" />

type="domdir:hostInfoType"
minOccurs="0" maxOccurs="unbounded" />
type="domdir:hostsType"
substitutionGroup="xdap:result" />

type="domdir:handleType" />
type="normalizedString" />
type="normalizedString"
minOccurs="0" maxOccurs="1" />
type="string"
minOccurs="0" maxOccurs="1" />
type="string"
minOccurs="0" maxOccurs="1" />
type="string"
minOccurs="0" maxOccurs="1" />
type="string"
minOccurs="0" maxOccurs="1" />
type="normalizedString"
minOccurs="0" maxOccurs="1" />
type="token"
minOccurs="0" maxOccurs="1" />
type="normalizedString"
minOccurs="0" maxOccurs="1" />
type="normalizedString"
minOccurs="0" maxOccurs="1" />
type="domdir:contactInfoType"
substitutionGroup="xdap:result" />

type="domdir:contactInfoType"
minOccurs="0" maxOccurs="unbounded" />
type="domdir:contactsType"
substitutionGroup="xdap:result" />

type="anyURI" />
type="anyURI" />
type="domdir:hostOrDomainType"
substitutionGroup="xdap:result" />

value="([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]\.)*([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])?" />
xmlns="urn:iana:xmlns:domdir1"
