finput=open(input_file, "r")
alllines=finput.readlines()
foutput = 0
output_file = dst_file
foutput = open(output_file, 'a')
bc = textwrap.fill(eachline,73)
tmplines = bc.split('\n')
tmplen = len(tmplines)
i = 0
finput=open(input_file, "r")
alllines=finput.readlines()
foutput = 0
output_file = dst_file
foutput = open(output_file, 'a')
eachline = eachline.strip('\\\n')
finput=open(input_file, "r")
alllines=finput.readlines()
foutput = 0
flag_add = 0
pos = 0
output_file = dst_file
foutput = open(output_file, 'a')
pos = eachline.rstrip('\\\n').rfind('\\',0,width)
bc = textwrap.fill(eachline,pos-1)
bc = textwrap.fill(eachline,73)
tmplines = bc.split('\n')
tmplen = len(tmplines)
flag_add = 0
i = 0
flag_add = 1
finput=open(input_file, "r")
alllines=finput.readlines()
foutput = 0
flag_del = 0
flag_enter = 0
output_file = dst_file
foutput = open(output_file, 'a')
eachline = eachline[2:]
flag_del = 1
eachline = eachline.strip('\\\n')
flag_del = 0
