NameFormat="urn:oasis:names:tc:SAML:2.0:profiles:attribute:uri"
Name="http://sxip.net/contact/internet/email">
targetNamespace="urn:ietf:params:dix:protocol"
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="unqualified"
attributeFormDefault="unqualified"
blockDefault="substitution"
version="1.0">

namespace="urn:oasis:names:tc:SAML:2.0:assertion"
schemaLocation="http://docs.oasis-open.org/security/
                       saml/v2.0/saml-schema-assertion-2.0.xsd"/>

RefreshURL="http://example-verified-email.com/renew">

IssueInstant="2003-04-17T00:46:02Z" Version="2.0"
xmlns="urn:oasis:names:tc:SAML:2.0:assertion">
Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
Algorithm=
              "http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
            <ds:Transform
Algorithm=
PrefixList="#default saml ds xs xsi"
xmlns=
Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
Format=
              "urn:oasis:names:tc:SAML:1.1:nameid-format:entity">
NotOnOrAfter="2003-04-17T00:51:02Z">
NameFormat=
Name="http://sxip.net/contact/internet/email">
