salt_0 = LURK exchange
key_request = h_c, h_s, a_c, a_s
handshake_context = ClientHello ... EncryptedExtensions
ephemeral = dhe_secret
key_request = h_c, h_s
handshake_context = ClientHello ... ServerHello
ephemeral = dhe_secret
handshake_context=client Finished  -------->
                                            NewSessionTicketResponse
                                              session_id
                                              cookie
                                 <---------   tickets
handshake_context=client Finished
key_request=binder_key
handshake_context=""
key_request=binder_key
handshake_context=ClientHello
key_request = h_c, h_s, a_c, a_s
handshake_context = ServerHello ... EncryptedExtensions
ephemeral = dhe_secret          -------->
                                            HandshakeAndAppResponse
                                              session_id
                                              cookie
                                              secret_response
                                                keys
                                      <---------

key_request=e_s
handshake_context=ClientHello
handshake_context = EncryptedExtensions ...
                   later of server Finished/EndOfEarlyData
handshake_context=CertificateRequest
app_n=N
                                            PostHandshakeResponse
                                              session_id
                                              cookie
                                 <---------   certificate_verify

