RLOC=IP_A //                  \\ RLOC=IP_B
                            +---+--+              +-+--+--+
                      .--.-.|xTR A |'.-.         .| xTR B |.-.
EID=            EID=<IID1,MAC_W>         EID=
EID=<IID1, IP_W> with the RLOC(s) associated with LISP site A (IP_A),
RLOC=IP_B as an additional locator for end system W with priority set
RLOC=IP_A. xTR A will also add an entry in its forwarding table that
RLOC=IP_B.

