nonce_claim = (
nonce => bstr .size (8..64)
ueid_claim = (
origination_claim = (
oemid_claim = (
security_level_type = (
security_level_claim = (
boot_state_type = [
secure_boot_enabled=> bool,
debug_disabled=> bool,
debug_disabled_since_boot=> bool,
debug_permanent_disable=> bool,
debug_full_permanent_disable=> bool
boot_state_claim = (
location_type = {
latitude => number,
longitude => number,
altitude => number,
accuracy => number,
altitude_accuracy => number,
heading => number,
speed => number
location_claim = (
age_claim = (
uptime_claim = (
nested_eat_claim = (
submod_name_type = (
submods_type = [ * submod_claims ]

submod_claims = {
       submod_name_type,
       * generic_claim_type
submods_claim = (
string_or_uri = #6.32(tstr) / tstr; See JSON section below for JSON encoding of string_or_uri

cwt_claim = (
       issuer_claim //
       subject_claim //
       audience_claim //
       expiration_claim //
       not_before_claim //
       issued_at_calim //
       cwt_id_claim
issuer_claim = (
subject_claim = (
audience_claim = (
expiration_claim = (
not_before_claim = (
issued_at_calim = (
cwt_id_claim = (
issuer = 1
subject = 2
audience = 3
expiration = 4
not_before = 5
issued_at = 6
cwt_id = 7

ueid = "ueid"
origination = "origination"
oemid = "oemid"
security_level = "security_level"
boot_state = "boot_state"
location = "location"
age = "age"
uptime = "uptime"
nested_eat = "nested_eat"
submods = "submods"

latitude = "lat""
longitude = "long""
altitude = "alt"
accuracy = "accry"
altitude_accuracy = "alt_accry"
heading = "heading"
speed = "speed"

ueid = 8
origination = 9
oemid = 10
security_level = 11
boot_state = 12
location = 13
age = 14
uptime = 15
nested_eat = 16
submods = 17
submod_name = 18
nonce = 19

latitude = 1
longitude = 2
altitude = 3
accuracy = 4
altitude_accuracy = 5
heading = 6
speed = 7

eat_claims = {  ; the top-level payload that is signed using COSE or JOSE
        * claim
claim = (
    ueid_claim //
    origination_claim //
    oemid_claim //
    security_level_claim //
    boot_state_claim //
    location_claim //
    age_claim //
    uptime_claim //
    nested_eat_claim //
    cwt_claim //
    generic_claim_type //
    )

   TODO: copy the rest of the CDDL here (wait until the CDDL is more
   settled so as to avoid copying multiple times)

