FT = Feedback Target
co=located.

                       Figure 1. System Architecture.

x=0; [min, min+(max-min)/NDB]
att-value  = "reflection"
 
                  RTCP with Unicast Feedback

           / "rsi" *(SP rsi-rule)

rsi-rule   = processing ":" rtcp-type
          
processing = "aggr" / "forward" / "term" / token ;keep it extensible

rtcp-type  = 3*3DIGIT    ;the RTCP type (192, 193, 202--208)


a=ssrc:314159 cname:iptv-sender@example.com 
 
                  RTCP with Unicast Feedback


xrange = Max Distribution Value(MaDV) - Min Distribution Value(MnDV)
xrange = MaDV - MnDV
x = MnDV;

y = (ydata[i] * factor);
