a=fmtp:<number> <port> <network type> <addresss type> <connection
m=audio 49170 RTP/AVP 0 78
c=IN IP4 224.2.17.12/127
a=rtpmap:78 RTX/8000
a=fmtp:78 49172 IN IP4 224.2.17.12/127

m=video 49170/2 RTP/AVP 78
a=rtpmap:78 layer-MP4V-ES/90000
a=fmtp:98ààà   MPEG-4 payload format specific options



