A = (a_(n1-1), a_(n1-2), ..., a_0), and B = (b_(n2-1),
T1 = HMAC_256 (K, S),
T2 = HMAC_256 (K, T1 | S),
T3 = HMAC_256 (K, T2 | S),
T4 = HMAC_256 (K, T3 | S),
T1 = HMAC_512 (K, S),
T2 = HMAC_512 (K, T1 | S),
T3 = HMAC_512 (K, T2 | S),
T4 = HMAC_512 (K, T3 | S),
a = s^2 - 3*t^2,
b = 2*t^3 - t*s^2,

s = (e - d) / 4,
t = (e + d) / 6,

label = (0x26 | 0xBD | 0xB8 | 0x78).

