CONTEXT=SORT extensions [RFC5267] where only a position of the new
capability          =/ "ETHREAD" / "INCTHREAD"
        ;; <capability> from [RFC3501]
    
modifier-ethread    = "THREAD"
    
modifier-incthread  = "INCTHREAD"
    
thread-return-opt   = modifier-thread / modifier-incthread
        ;; Similar to <search-return-opt> from [RFC4466]
    
ret-data-thread     = "THREAD" [SP "(" 1*thread-list ")" ]
        ;; <thread-list> from [RFC5256]
    
ret-data-incthread  = "INCTHREAD" SP "(" uid SP thread-list ")"
        ;; <uid> from [RFC3501]
        ;; <thread-list> from [RFC5256]
    
search-return-data  =/ ret-data-thread / ret-data-incthread
        ;; <search-return-data> from [RFC4466]
    
thread              =/ "UID" SP "THREAD" [thread-return-opts]
                           SP thread-alg SP search-criteria
        ;; <thread> and <thread-alg> from [RFC5256]
        ;; <search-criteria> from [RFC3501] as amended by
        ;;   [I-D.ietf-morg-inthread]
        ;;
        ;; The thread-return-opts MUST contain exactly one of
        ;;   modifier-thread or modifier-incthread
    
thread-return-opts  = SP "RETURN" SP "(" [thread-return-opt
                          *(SP thread-return-opt)] ")"
        ;; similar to the <search-return-opts> from [RFC4466]
    

