list-id = list-label "." list-id-namespace

list-label = dot-atom-text

list-id-namespace = domain-name / unmanaged-list-id-namespace

unmanaged-list-id-namespace    = "localhost"

domain-name = dot-atom-text

list-id-header = "List-ID:" [quoted-string] "<" list-id ">" CRLF

    where quoted-string and CRLF are as defined in [DRUMS].

    Examples:

    List-Id: "List Header Mailing List" <list-header.nisto.com>
    List-Id: <commonspace-users.list-ids.within.com>
    List-Id: "Lena's Personal Joke List"
             <lenas-jokes.da39efc25c530ad145d41b86f7420c3b.021999.localhost>
    List-Id: "An internal CMU List" <0Jks9449.cmu.edu>
    List-Id: <da39efc25c530ad145d41b86f7420c3b.051998.localhost>

