PrivateInstanceName = <nonce>|<proof>
proof = hash(<nonce>|<key>)

proof = first 48 bits of HASH(<nonce>|<pairing key>)

nonce = 20 bit rounded time stamp of the \
       respective next time interval padded to \
       24 bits with four zeroes
nonce = first 24 bits of binary.

