schema="https://example.com/my-hyper-schema#"


schema="https://example.com/alice https://example.com/bob"


schema="https://example.com/qiang https://example.com/li",
schema="https://example.com/kumar"


rel="profile"

