tmTransport = snmpSSHDomain

tmAddress = an snmpSSHAddress

tmRequestedSecurityLevel = ["noAuthNoPriv" | "authNoPriv" |
tmTransportSecurityLevel = "authPriv"

tmSecurityName = the principal name [to be] authenticated by SSH.
tmSameSecurity = true or false, depending on whether the Security
sshtmTransportAddress = transport address

sshtmLCDTmSecurityName = calculated tmSecurityName

sshtmLCDPrincipal=the SSH principal

sshtmLCDSessionID=the SSH session identifier

sshtmStorageType=volatile

sshtmRowStatus=createAndGo

tmTransportDomain = snmpSSHDomain

tmTransportAddress = sshtmLCDTransportAddress

tmSecurityLevel = "authPriv"

tmSecurityName = sshtmLCDTmSecurityName

tmSessionID = an implementation-dependent value that can be used
statusInformation =
statusInformation =
statusInformation =
sshtmLCDTransportAddress = tmTransportAddress

sshtmLCDTmSecurityName = tmSecurityName

statusInformation =
sshtmLCDTransportAddress=(desired value),
sshtmLCDTmSecurityName=(desired value),
sshtmLCDPrincipal=(desired value),
sshtmLCDSessionID=sValue,
sshtmLCDStorageType=(desired value),
sshtmLCDStatus=createAndGo)
