parameter = "content" "=" value


value = DQUOTE role-list DQUOTE
role-list = role / role-list "," role
role = session-description /
                   telephony-signalling /
                   payment-information
session-description = "sd"
telephony-signalling = "ts"
payment-information = "pi"

