MAC_z = MAC([cai_z, fields(cai_z), attributes, cai_n, timestamp],
MAC_n = MAC([serial, cai_n, fields(cai_n)], GK_n_x)
Token =
      [cai_z, cai_n, GK_z-kid, CxID, attributes_conveyed,
         (MAC_z xor MAC_n_x)]

Grant_x = [GK0-kid, cai_1, cai_2, fields(cai_1), GKx]

token = [GK0-kid, cai_1, cai_2, MAC([serial, cai_2,
