Send-Event           =  "Send-Event" HCOLON 1*(invite-event-package 
                           *( SEMI invite-event-param )) 
Recv-Event           =  "Send-Event" HCOLON 1*(invite-event-package 
                           *( SEMI invite-event-param )) 
invite-event-package =  token-nodot 
token-nodot          =  1*( alphanum / "-"  / "!" / "%" / "*" 
                               / "_" / "+" / "`" / "'" / "~" ) 
Invite-event-param   =  generic-param / ( "id" EQUAL token ) 
    
    
