User-Name = x.example.com!h.example.com!username@z.example.com
Destination-Realm = z.example.com

User-Name = h.example.com!username@x.example.com
Destination-Realm = x.example.com

User-Name = username@h.example.com
Destination-Realm = h.example.com

