Epoch=0 that look like they come from the server could result in a





external_address = NUL;
external_address = NUL;
external_address = NUL;
PIN44=0:  create a forwarding pinhole between an internal IPv4
             address and public IPv4 address (e.g., NAT44 or firewall)









PIN46=1:  create a forwarding pinhole between an internal IPv4
             address and public IPv6 address (e.g., NAT46 or firewall)

PIN64=2:  create a forwarding pinhole between an internal IPv6
             address and public IPv4 address (e.g., NAT64 or firewall)

PIN66=3:  create a forwarding pinhole between an internal IPv6
             address and public IPv6 address (e.g., NPTv6 or firewall)

PEER4=4:  Set or query lifetime for flow from IPv4 address to a
           remote peer's IPv4 address.

PEER6=5:  Set or query lifetime for flow from IPv6 address to a
           remote peer's IPv6 address.

