authres = 1*( "AUTHRES" "=" version ":"
                                  authserv-id ":"
                                  methodspec ":"
                                  propspec )
              ; relays a single unit of authentication results
              ; information

