Type-P-One-Way-Loss-Period-Total = maximum value of the first
Type-P-One-Way-Loss-Noticeable-Rate = 3/5 ((number of noticeable
Type-P-One-Way-Loss-Period-Total = 4

Type-P-One-Way-Loss-Period-Lengths =

         {<1,1>,<2,1>,<3,1>,<4,2>}

Type-P-One-Way-Inter-Loss-Period-Lengths =

         {<1,0>,<2,3>,<3,2>,<4,2>}


