tmsLCDTransport = transportDomainSSH
tmsLCDAddress = a TransportAddressSSH
tmsLCDSecurityLevel = "authPriv"
tmsLCDSecurityName = the principal name authenticated by SSH.  How
tmsLCDEngineID = if known, the value of the remote engine's
tmsLCDSecurityModel = a security model.  The SSH Transport Model
transportDomain = transportDomainSSH
transportAddress = a TransportAddressSSH
tmsSecurityLevel = "authPriv"
tmsSecurityName = the principal name authenticated by SSH.  How
statusInformation =
statusInformation =
statusInformation =
statusInformation =
sshtmUserStatus=createAndWait)
