service-descriptor = service-part "." protocol-part
                         [ "." name-part [ ":" alt-port ] ]

service-part       = *( 1*DIGIT [ "-" ] ) ALPHA
                         *( [ "-" ] ALNUM )   ; Maximum 15 characters

protocol-part      = "tcp" / "udp" / "sctp" / "dccp" / "ip"

name-part          = label *( "." label )
label              = ALNUM *( [ "-" ] ALNUM )

alt-port           = 1*DIGIT              ; Values of 0-65535

ALNUM              = ALPHA / DIGIT
ALPHA              = %x41-5A / %x61-7A    ; A-Z / a-z [RFC5234]
DIGIT              = %x30-39              ; 0-9       [RFC5234]
