lastRoundMinRTT = currentRoundMinRTT

currentRoundMinRTT = infinity

rttSampleCount = 0

cwnd = cwnd + min (N, L * SMSS)

currentRoundMinRTT = min(currentRoundMinRTT, currRTT)

RttThresh = clamp(MIN_RTT_THRESH, lastRoundMinRTT / 8,
cssBaselineMinRtt = currentRoundMinRTT

cwnd = cwnd + (min (N, L * SMSS) / CSS_GROWTH_DIVISOR)

currentRoundMinRTT = min(currentRoundMinRTT, currRTT)

cssBaselineMinRtt = infinity

ssthresh = cwnd

ssthresh = cwnd
LOW_CWND = 16

MIN_RTT_THRESH = 4 msec

MAX_RTT_THRESH = 16 msec

N_RTT_SAMPLE = 8

CSS_GROWTH_DIVISOR = 4

CSS_ROUNDS = 5

