elementFormDefault="qualified" 
attributeFormDefault="unqualified"> 
        <xs:import namespace="urn:ietf:params:xml:ns:iodef-1.0" 
schemaLocation=" 
type="thraud:FraudEventPaymentType"/> 
        <xs:element name="FraudEventTransfer" 
type="thraud:FraudEventTransferType"/> 
        <xs:element name="FraudEventIdentity" 
type="thraud:FraudEventIdentityType"/> 
        <xs:element name="FraudEventOther" 
type="thraud:FraudEventOtherType"/> 
        <xs:complexType name="FraudEventPaymentType"> 
         <xs:sequence> 
          <xs:element name="PayeeName" type="iodef:MLStringType" 
minOccurs="0"/> 
          <xs:element name="PostalAddress" type="iodef:MLStringType" 
minOccurs="0"/> 
          <xs:element name="PayeeAmount" type="thraud:AmountType" 
minOccurs="0"/> 
         </xs:sequence> 
        </xs:complexType> 
        <xs:complexType name="FraudEventTransferType"> 
        <xs:sequence> 
          <xs:element name="BankID" type="thraud:BankIDType" 
minOccurs="0"/> 
          <xs:element name="AccountID" type="xs:string" minOccurs="0"/> 
          <xs:element name="AccountType" type="iodef:MLStringType" 
minOccurs="0"/> 
          <xs:element name="TransferAmount" type="thraud:AmountType" 
minOccurs="0"/> 
         </xs:sequence> 
        </xs:complexType> 
        <xs:complexType name="FraudEventIdentityType"> 
         <xs:sequence maxOccurs="unbounded"> 
          <xs:element name="IdentityComponent" 
type="iodef:ExtensionType"/> 
         </xs:sequence> 
        </xs:complexType> 
        <xs:complexType name="FraudEventOtherType"> 
         <xs:sequence> 
          <xs:element name="OtherEventType" type="xs:anyURI"/> 

        
        
        
                     Sharing Transaction Fraud Data     February 2009 
        
          <xs:element name="PayeeName" type="iodef:MLStringType" 
minOccurs="0"/> 
          <xs:element name="PostalAddress" type="iodef:MLStringType" 
minOccurs="0"/> 
          <xs:element name="BankID" type="thraud:BankIDType" 
minOccurs="0"/> 
          <xs:element name="AccountID" type="xs:string" minOccurs="0"/> 
          <xs:element name="AccountType" type="iodef:MLStringType" 
minOccurs="0"/> 
          <xs:element name="PayeeAmount" type="thraud:AmountType" 
minOccurs="0"/> 
          <xs:element name="OtherEventDescription" 
type="iodef:MLStringType" minOccurs="0"/> 
         </xs:sequence> 
        </xs:complexType> 
        <xs:complexType name="AmountType"> 
         <xs:simpleContent> 
          <xs:extension base="xs:decimal"> 
           <xs:attribute name="currency" type="xs:string"/> 
          </xs:extension> 
         </xs:simpleContent> 
        </xs:complexType> 
        <xs:complexType name="BankIDType"> 
         <xs:simpleContent> 
          <xs:extension base="xs:string"> 
           <xs:attribute name="namespace" type="xs:anyURI" 
use="required"/> 
          </xs:extension> 
         </xs:simpleContent> 
        </xs:complexType> 
        <xs:element name="UserId" type="xs:string"/> 
namespace="http://www.openauthentication.org/thraud/resources/ba
