Invalidated-By = "Invalidated-By" ":" Channel-URI
Channel-URI = wcip-channel | wcips-channel
wcip-channel = "wcip:" "//" host ":" port "/" channel-name
wcips-channel = "wcips:" "//" host ":" port "/" channel-name
channel-name = token

Channel-Object = "Channel-Object" ":" 1#Object-info
Object-info = Object-name | Fresh-guarantee
Object-name = "name" "=" quoted-string
Fresh-guarantee = "fresh" "=" delta-seconds

Registration = wcip-method SP channel-URI SP WCIP-Version CRLF
wcip-method  = "POST"
WCIP-Version = "WCIP" "/" 1*DIGIT "." 1*DIGIT

Channel = "Channel" ":" 1#Channel-info
Channel-info = registration-lifetime
                        | heartbeat-interval
                        | no-target
                        | message-syntax
                        | seqence-number
registration-lifetime = "life" "=" delta-seconds
heartbeat-interval = "heartbeat" "=" delta-seconds
no-target = "no-target"
message-syntax = "syntax" "=" Syntax-name
sequence-number = "seqno" "=" 1*DIGIT
Syntax-name = "ObjectList"
                        | token         ; extension syntaxes

url="http://www.amazon.com/"
last-modified="Wed, 15 Nov 2000 04:52:01 GMT"

url="http://www.ebay.com/"
last-modified="Thur, 16 Nov 2000 03:18:07 GMT"
etag="yzxzyx"
url="http://www.cnn.com/allpolitics"
last-modified="Fri, 17 Nov 2000 08:22:17 GMT"
url="http://www.amazon.com/"
last-modified="Wed, 15 Nov 2000 04:52:01 GMT"
url="http://www.ebay.com/"
last-modified="Thur, 16 Nov 2000 07:18:07 GMT"
etag="yzxzxx"
url="http://www.cnn.com/allpolitics"
last-modified="Fri, 17 Nov 2000 08:22:17 GMT"
url="http://www.amazon.com/"
last-modified="Wed, 15 Nov 2000 07:52:01 GMT"
etag="yzxzxx"
url="http://www.ebay.com/"
last-modified="Thur, 16 Nov 2000 07:18:07 GMT"
etag="yzxzxx"
