SRC = mobile node; DEST = AAAv6 Attendant; NxtHDR = 58 (ICMPv6)

SRC = AAAv6 Attendant; DEST = mobile node; NxtHDR = 58 (ICMPv6)

SRC = mobile node; DEST = AAAv6 Attendant; NxtHDR = 58 (ICMPv6)

SRC = AAAv6 Attendant; DEST = mobile node; NxtHDR = 58 (ICMPv6)
SRC = mobile node; DEST = AAAv6 Attendant; NxtHDR = 58 (ICMPv6)
SRC = AAAv6 Attendant; DEST = mobile node; NxtHDR = 58 (ICMPv6)

