Caller=user1@realmB     ^                   ^     Callee:user2@reamlA
                           |                   |
                   UAR/UAA |                   |
                   LIR/LIA |                   | MAR/MAA
                           |    +--------+     | SAR/SAA
                           +--->|Diameter|<----+
                                |   SL   |
                                |Vendor C|
                                +--------+

      Legend:
              SIP UA's         - SIP User Agents making/receiving calls
              SIP server 1     - Vendor A acting as SIP proxy for reamlA
              Diameter server  - Vendor B acting as SIP auth server
              Diameter SL      - Vendor C acting as location server
              SIP server 2     - Vendor D acting as SIP proxy for realmB

