fs = ft-min(val/(rng/ft)+1,ft).  The divisions here are exact integer
i=-d


i=1


k=1                               k=-d


k=1                               k=-d


g_ana = 0.94 - 0.02*C, and
g_syn = 0.94 + 0.02*C,


b_ana = F_ana * [0.25, 0.5, 0.25], and
b_syn = F_syn * [0.25, 0.5, 0.25].


c_tilt = 0.4, and as
c_tilt = 0.04 + 0.06 * C


predGain = ( | | 1 - (r_k)^2 )^(-0.5),
k=1


LSF_q = argmin { (LSF - c)' * W * (LSF - c) + mu * rate },
                 c in C


M = \  Ms,
                                     /_
s=1


T = | | Ms
s=1


RD = u * (b - cb_i)' * W_ltp * (b - cb_i) + r_i,


y0 = round_towards_zero( (K-1) * R / sum(abs(R)))

J = -R^T*y / ||y||
b = 2*[0,1,2,3,4,5,6,7,8,10,12,14,16,20,24,28,34,40,48,60,78,100];
d = diff(b);

T = 50-.7*[1:21];

N = 10 .^ ((10-0.6*[1:21])/10);

e=x-y;

e = e - min(1, max(-1, e));

X=(abs(specgram(x(1:2:end),480))+abs(specgram(x(2:2:end),480)))/2;
E=(abs(specgram(e(1:2:end),480))+abs(specgram(e(2:2:end),480)))/2;
X=abs(specgram(x,480));
E=abs(specgram(e,480));
Xb = filter(1, [1, -.1], Xb);
Xb = filter(1, [1, -.3], Xb')';
T0 = ones(length(Eb), 1)*(10.^((T)/10));

NMR = (Xb./Eb)';

tmp = Eb(:);
thresh = sort(tmp)(round(.90*length(tmp)));
weight = Eb'>thresh;

err = -100;
M = (T0./NMR) .* weight;

err = 10*log10(sum(sum(M)) / sum(sum(weight)));

