I=10: Interval Duration - the reported value applies to the
I=11: Cumulative Duration - the reported value applies to the
I=01: Sampled Value - the reported value is a sampled
mean = Sum of Burst Durations / Number of Bursts

var = ( Sum of Squares of Burst Durations - Number of Bursts *
I=10: Interval Duration - the reported value applies to the
I=11: Cumulative Duration - the reported value applies to the
I=01: Sampled Value - the reported value is a sampled
xr-format = / burst-gap-loss-stat
                        / burst-gap-discard-stat
                        / frame-impairment-stat
Burst-gap-loss-stat ="burst gap loss summary statistics"
Burst-gap-discard-stat="burst gap discard summary statistics"
Frame-impairment-stat="frame impairment summary statistics"

