CT=CT1, setup priority = 0, holding priority = 0,
CT=CT0, setup priority = 0, holding priority = 0,
CT=CT0, setup priority = 0, holding priority = 1.
CT=CT1, setup priority = 0, holding priority = 0,
CT=CT0, setup priority = 0, holding priority = 0,
CT=CT0, setup priority = 0, holding priority = 1.
CT=CT1, setup priority = 0, holding priority = 0,
CT=CT0, setup priority = 0, holding priority = 0,
CT=CT0, setup priority = 0, holding priority = 1.

CT=CT1, setup priority = 0, holding priority = 0,
CT=CT0, setup priority = 0, holding priority = 0,
CT=CT0, setup priority = 0, holding priority = 1.
