nameddest=name           action is to open to specified destination
                            (which includes a view)

                                Figure 1

page=pagenum             action is to open the specified page

                                Figure 2

zoom=scale,left,top      action is to set the "scale" and scrolling
                            factors. "left" and "top" are measured from
                            the top left corner of the page independent
                            of the size of the page. The pair "left" and
                            "top" are optional but both must appear if
                            present.

                                Figure 3
view=keyword,position    action is to set the view to show some
                            specified portion of the page or its
                            bounding box. The keywords are defined by
                            Table 8.2 of the PDF Reference, version 1.5.
                            The "position" value is required for some of
                            the keywords and not allow for others. See
                            Table 8.2

                                Figure 4

viewrect=left,top,wd,ht  The view rectangle the is mapped into the
                            viewing window is position as for the zoom
                            parameter, but an explicit width and height
                            are given instead of a scale percentage.

                                Figure 5

highlight=lt,rt,top,btm  Highlight a rectangle on the chosen page
                            where lt,rt,top and btm are the coordinates
                            of the sides of the rectangle measured from
                            the top left corner of the page.

                                Figure 6

