T = Transitivity bit. This bit can take two values:
         Value 0: The community is transitive across ASes
         Value 1: The community is non-transitive across ASes This field
Struct = Structure field. This field is split into two sub-fields:

        0
        0 1 2 3 4 5 6 7
       +-+-+-+-+-+-+-+-+
       |T|L|  Struct.  |
       +-+-+-+-+-+-+-+-+

Type = Type field. This field is split into two sub-fields:

            1                   2
        8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
       |L|            Type             |
       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

