tlsrpt-record     = tlsrpt-version *WSP field-delim *WSP tlsrpt-rua
                        [field-delim [tlsrpt-extensions]]

field-delim       = %x3B                                    ; ";"

tlsrpt-version    = %x76 *WSP "=" *WSP %x54 %x4C %x53 %x52
                        %x50 %x54 %x76 %x31                ; "v=TSRPTv1"

tlsrpt-rua        = %x72 %x75 %x61 *WSP "=" *WSP tlsrpt-uri ; "rua=..."

tlsrpt-uri        = URI
                      ; "URI" is imported from [@!RFC3986]; commas (ASCII
                      ; 0x2C) and exclamation points (ASCII 0x21)
                      ; MUST be encoded; the numeric portion MUST fit
                      ; within an unsigned 64-bit integer

tlsrpt-extensions = tlsrpt-extension *(field-delim tlsrpt-extension)
                        [field-delim]
                      ; extension fields

tlsrpt-extension  = tlsrpt-ext-name *WSP "=" *WSP tlsrpt-ext-value

tlsrpt-ext-name   = (ALPHA / DIGIT) *31(ALPHA / DIGIT / "_" / "-" / ".")

tlsrpt-ext-value  = 1*(%x21-3A / %x3C / %x3E-7E)       ; chars excluding
                                                     ; "=", ";", SP, and
                                                     ; control chars

rua=https://reporting.example.com/v1/tlsrpt"

filename = sender "!" policy-domain "!" begin-timestamp
                 "!" end-timestamp [ "!" unique-id ] "." extension

unique-id = 1*(ALPHA / DIGIT)

sender = domain        ; imported from [@!RFC5322]

policy-domain   = domain

begin-timestamp = 1*DIGIT
                       ; seconds since 00:00:00 UTC January 1, 1970
                       ; indicating start of the time range contained
                       ; in the report

end-timestamp = 1*DIGIT
                       ; seconds since 00:00:00 UTC January 1, 1970
                       ; indicating end of the time range contained
                       ; in the report

extension = "json" / "json.gz"

tlsrpt-subject = %x52.65.70.6f.72.74 1*FWS       ; "Report"
                      %x44.6f.6d.61.69.6e.3a 1*FWS    ; "Domain:"
                      domain-name 1*FWS               ; from RFC 6376
                      %x53.75.62.6d.69.74.74.65.72.3a ; "Submitter:"
                      1*FWS domain-name 1*FWS
                      %x52.65.70.6f.72.74.2d.49.44.3a ; "Report-ID:"
                      msg-id                          ; from RFC 5322

boundary="----=_NextPart_000_024E_01CC9B0A.AFE54C00"
filename="mail.sender.example!example.com!
                        1013662812!1013749130.gz"

rua=https://reporting.example.com/v1/tlsrpt"

