QS-cwnd = (R * T) / (MSS + H)                                (3)

RTT=0.2 seconds, and MSS=1500 bytes, K would be set to 216, and the
K=40,000 and an eight-bit Rate Request field, the request range
util_bw = bandwidth * utilization;
util_bw = util_bw + recent_qs_approvals;
approved = (qs_thresh * bandwidth) - util_bw;
approved = rate_request;
approved = round_down (approved);
