flood-message = [M_FLOOD, session-id, initiator, ttl,
                            +[objective, (locator-option / [])]]

objective = ["AN_ACP", objective-flags, loop-count,
                                                  objective-value]

objective-flags = ; as in the GRASP specification
loop-count = 1    ; limit to link-local operation
objective-value = text ; name of the (list of) secure
                                  ; channel negotiation protocol(s)

Zone = zero is the default addressing scheme in an autonomic domain.
