delivery-status-content =
          per-message-fields 1*( CRLF per-recipient-fields )

xtext = *( xchar / hexchar / linear-white-space / comment )

xchar = any ASCII CHAR between "!" (33) and "~" (126) inclusive,
          except for "+", "\" and "(".

hexchar = ASCII "+" immediately followed by two upper case
          hexadecimal digits

address-type = atom

diagnostic-type = atom

MTA-name-type = atom

per-message-fields =
          [ original-envelope-id-field CRLF ]
          reporting-mta-field CRLF
          [ received-from-mta-field CRLF ]
          [ arrival-date-field CRLF ]
          *( extension-field CRLF )


original-envelope-id-field =
          "Original-Envelope-Id" ":" envelope-id

envelope-id = xtext

reporting-mta-field =
          "Reporting-MTA" ":" mta-name-type ";" mta-name

mta-name = xtext

received-from-mta-field =
          "Received-From-MTA" ":" mta-name-type ";" mta-name

arrival-date-field = "Arrival-Date" ":" date-time

per-recipient-fields =
          [ original-recipient-field CRLF ]
          final-recipient-field CRLF
          action-field CRLF
          status-field CRLF
          [ remote-mta-field CRLF ]
          [ diagnostic-code-field CRLF ]
          [ last-attempt-date-field CRLF ]
          [ expiry-date-field CRLF ]
          *( extension-field CRLF )


original-recipient-field =
          "Original-Recipient" ":" address-type ";" generic-address
generic-address = xtext

final-recipient-field =
          "Final-Recipient" ":" address-type ";" generic-address

action-field = "Action" ":" action-value

action-value = "failure" / "delayed" / "delivered" / "relayed"

status-field = "Status" ":" status-code

status-code = DIGIT "." 1*DIGIT "." 1*DIGIT

remote-mta-field = "Remote-MTA" ":" mta-name-type ";" mta-name

diagnostic-code-field = "Diagnostic-Code" ":" diagnostic-type ";"
          xtext

last-attempt-date-field = "Last-Attempt-Date" ":" date-time

expiry-date-field = "Expiry-Date" ":" date-time

extension-field = extension-field-name ":" xtext

extension-field-name = atom


action-field = "Action" ":" action-value

action-value = "failure" / "delayed" / "delivered" / "relayed"

address-type = atom

arrival-date-field = "Arrival-Date" ":" date-time

delivery-status-content =
     per-message-fields 1*( CRLF per-recipient-fields )

diagnostic-code-field = "Diagnostic-Code" ":" diagnostic-type ";" xtext

envelope-id = xtext

expiry-date-field = "Expiry-Date" ":" date-time

extension-field = extension-field-name ":" xtext

extension-field-name = atom

final-recipient-field =
     "Final-Recipient" ":" address-type ";" generic-address

generic-address = xtext

hexchar = ASCII "+" immediately followed by two upper
     case hexadecimal digits

last-attempt-date-field = "Last-Attempt-Date" ":" date-time

mta-name = xtext

mta-name-type = atom

original-envelope-id-field =
     "Original-Envelope-Id" ":" envelope-id

original-recipient-field =
     "Original-Recipient" ":" address-type ";" generic-address

per-message-fields =
per-recipient-fields =
     [ original-recipient-field CRLF ]
     final-recipient-field CRLF
     action-field CRLF
     status-field CRLF
     [ remote-mta-field CRLF ]
     [ diagnostic-code-field CRLF ]
     [ last-attempt-date-field CRLF ]
     [ expiry-date-field CRLF ]
     *( extension-field CRLF )

received-from-mta-field =
     "Received-From-MTA" ":" mta-name-type ";" mta-name

remote-mta-field = "Remote-MTA" ":" mta-name-type ";" mta-name

reporting-mta-field =
     "Reporting-MTA" ":" mta-name-type ";" mta-name

status-code = DIGIT "." 1*DIGIT "." 1*DIGIT

status-field = "Status" ":" status-code

diagnostic-type = atom

xchar = any ASCII CHAR between "!" (33) and "~" (126) inclusive,
     except for "+", "\" and "(".

xtext = *( xchar / hexchar / linear-white-space / comment )
boundary="RAA14128.773615765/CS.UTK.EDU"


boundary="JAA13167.773673707/CS.UTK.EDU"


boundary="[;84229080704991/122306@SYS30]"

boundary=foobar

boundary=foobar

