Ipub = Dprp + TTLkey

Ipub = Dprp + Ingc

Ingc = min(TTLsoa, SOAmin)

Trdy = Tpub + Ipub

Tret = Tact + Lzsk

Iret = Dsgn + Dprp + TTLsig

Iret = Lsig + Dskw

Tdea = Tret + Iret

Trdy = Tpub + Ipub

Ipub = max(IpubC, IpubP)

IpubC = DprpC + TTLkeyC

IpubP = Dreg + DprpP + TTLds

Ipub = IpubC

TrdyS = TpubS + Ipub

Tret = Tact + Lksk

Trem = Tret + Iret

IpubC = DprpC + TTLkeyC

IpubC = DprpC + IngcC

