CN = Correspondent Node
H = Host
L_1 = global Locator value
L_L = local Locator value
SBR = Site Border Router

L_pp = Locator prefix part (assigned IPv6 prefix)
L_ss = Locator subnet selector (locally managed subnet ID)

L_pp = Locator prefix (assigned IPv4 prefix)
L_ss = Locator subnet selector (locally managed subnet ID)

CN = Correspondent Node
H = Host
L_1 = global Locator value 1
L_2 = global Locator value 2
L_L = local Locator value
SBR = Site Border Router
sbrN = interface N on SBR

CP     = coordination protocol
L_1    = global Locator value 1
L_2    = global Locator value 2
SBR_A  = Site Border Router A
SBR_B  = Site Border Router P

H = host
L_1 = global Locator value 1
L_2 = global Locator value 2
L_L = local Locator value
raN = radio interface N
SBR = Site Border Router

HN = host N
L_1 = global Locator value 1
L_2 = global Locator value 2
L_L = local Locator value
SBR = Site Border Router
sbrN = interface N on sbr

srcI=I_1, sbr1                                        --- (3a)
srcI=I_2, sbr2                                        --- (3b)
srcI=I_3, sbr1                                        --- (3c)

srcI=I_3, sbr2                                        --- (4)

CN = correspondent node
HN = host N
LN = global Locator value N
L_L = local Locator value
SBR = Site Border Router
sbrN = interface N on sbr

srcI=I_2, L2                                          --- (5a)
srcI=I_3, L3                                          --- (5b)
dstI=I_CN, L6                                         --- (5c)
srcI=I_1 dstI=I_CN, L1                                --- (5d)

CN = Correspondent Node
V = Virtual machine image
Hx = Host x
L_1 = global Locator value
L_L = local Locator value
SBR = Site Border Router

CN = Correspondent Node
V = Virtual machine image
Hx = Host x
L_y = global Locator value y
L_Lz = local Locator value z
SBR = Site Border Router
LRR = Locator Re-writing Relay

