port = min_ephemeral + random() % (max_ephemeral - min_ephemeral)

                                 Figure 1

next_ephemeral_port = 1024;  /*initialization, could be random */

port = next_ephemeral_port;
next_ephemeral_port = min_ephemeral_port;
next_ephemeral_port = 1024;  /*initialization, could be random */

offset = F(local_IP, remote_IP, remote_port, secret_key);
port = min_ephemeral +
                  (next_ephemeral_port + offset)
                      % (max_ephemeral - min_ephemeral);
