UUI         = "User-to-User" HCOLON uui-data *(SEMI uui-param)
uui-data    = token
uui-param   = enc-param | cont-param | app-param | generic-param
enc-param   = "encoding="("hex" | token)
cont-param  = "content=" token
app-param   = "app=" token
