T1 = prf(K, S | 0x01)
T2 = prf(K, T1 | S | 0x02)
T3 = prf(K, T2 | S | 0x03)
T4 = prf(K, T3 | S | 0x04)

Y_S = g^x mod N,

DHComponent_S = E(prf+(password, "EAP-EKE Password"), Y_S),

Y_P = g^y mod N

DHComponent_P = E(prf+(password, "EAP-EKE Password"), Y_P)

SharedSecret = prf(0+, g^(x*y) mod N)

Ke = prf+(SharedSecret, "EAP-EKE Ke" | ID_S | ID_P)

Ki = prf+(SharedSecret, "EAP-EKE Ki" | ID_S | ID_P)

Commit_P = E(Ke, Nonce_P),

Confirm_S = E(Ke, Nonce_P | Nonce_S),

Ka = prf+(SharedSecret, "EAP-EKE Ka" | ID_S | ID_P | Nonce_P |
Auth_S = prf(Ka, "EAP-EKE server" | EAP-EKE-ID/Request | EAP-EKE-
Confirm_P = E(Ke, Nonce_S)

Auth_P = prf(Ka, "EAP-EKE peer" | EAP-EKE-ID/Request | EAP-EKE-ID/
MSK = prf+(SharedSecret, "EAP-EKE MSK" | ID_S | ID_P | Nonce_P |
EMSK = prf+(SharedSecret, "EAP-EKE EMSK" | ID_S | ID_P | Nonce_P |
