filter=BBR.BtlBwFilter,
value=rs.delivery_rate,
time=BBR.round_count,
window_length=BtlBwFilterLen)

next_send_time = Now() + packet.size / pacing_rate
nominal_bandwidth = InitialCwnd / (SRTT ? SRTT : 1ms)
rate = pacing_gain * BBR.BtlBw
quanta = 3*BBR.send_quantum
estimated_bdp = BBR.BtlBw * BBR.RTprop
cwnd = 1

cwnd = packets_in_flight + max(packets_delivered, 1)
cwnd = max(cwnd - packets_lost, 1)
cwnd = max(cwnd, packets_in_flight + packets_delivered)

cwnd = max(cwnd, BBR.prior_cwnd)

cwnd = min(cwnd, BBRMinPipeCwnd)

cwnd = min(cwnd + packets_delivered, BBR.target_cwnd)
cwnd = cwnd + packets_delivered
cwnd = max(cwnd, BBRMinPipeCwnd)
pacing_gain_cycle = [5/4, 3/4, 1, 1, 1, 1, 1, 1]
is_full_length = (Now() - BBR.cycle_stamp) > BBR.RTprop
