K = [IDa],T, E(encr_key,k_p)
A = MAC(auth_key,K)

                               K, A
                    --------------------- >
V=MAC(k_v,IDa||IDb||T),[IDb]
I=(IDa|Cert_A)
K=E(PK_b,k_p)
     || T
     [|| I]
     [|| H(Cert_B)]
S=Sign(SK_a,H(K))

                              K,S
                    ---------------------->

V=MAC(k_v,IDa||IDb||T),[IDb]
I = (IDa|Cert_A)
K = g**x || T [|| I]
S = Sign (SK_a,H(K))
                              K,S             I' = (IDb|Cert_B)
                    ---------------------->   K' = g**y || T [|| I']
                                              S' = Sign (SK_b,H(K'))
                             K',S'
                    <----------------------

k_p= g**(xy)                               k_p=g**(xy)


A_0 = seed,
A_i = HMAC (s, A_(i-1)).


maxsize = Min (A, e*x) * block_size

a=keymgmt-prot:<protocol>
a=keymgmt-data:<data>

a=keymgmt-prot:MIKEY

a=keymgmt-data:<base64 encoded data>


version = 1

R = 0  ==> no response expected
R = 1  ==> response expected

