D=2001:db8:0:b020::41, regardless of the state of uplink to ISP-B.

D=::/0) .  If all of the routers in the site support SADR, then the
D=2001:db8:0:1234::101), the packet will only be sent out the link
D=::/0, with the route origination dependent on the state of the
D=2001:db8:0:6666::61).  The routed network has two potential ways of
D=2001:db8:0:6666::/64).  From a forwarding point of view, the use of
D=2001:db8:0:5555/64      NH=R7
D=::/0                    NH=R7

D=2001:db8:0:6666/64      NH=SERb2
D=::/0                    NH=SERb1

D=2001:db8:0:a010::/64    NH=R2
D=2001:db8:0:b010::/64    NH=R2
D=2001:db8:0:a020::/64    NH=R5
D=2001:db8:0:b020::/64    NH=R5
D=2001:db8:0:5555::/64    NH=R7
D=2001:db8:0:6666::/64    NH=SERb2
D=::/0                    NH=SERb1

                Figure 5: Forwarding Entries Computed at R8

D=2001:db8:0:b010::/64, D=2001:db8:0:a020::/64, and
D=2001:db8:0:b020::/64) are not an exact match for any of the
D=2001:db8:0:a010::/64    NH=R2
D=2001:db8:0:b010::/64    NH=R2
D=2001:db8:0:a020::/64    NH=R5
D=2001:db8:0:b020::/64    NH=R5
D=2001:db8:0:5555::/64    NH=R7
D=2001:db8:0:6666::/64    NH=SERb2
D=::/0                    NH=R7

D=2001:db8:0:a010::/64    NH=R2
D=2001:db8:0:b010::/64    NH=R2
D=2001:db8:0:a020::/64    NH=R5
D=2001:db8:0:b020::/64    NH=R5
D=2001:db8:0:5555::/64    NH=R7
D=2001:db8:0:6666::/64    NH=SERb2
D=::/0                    NH=SERb1

D=2001:db8:0:a010::/64    NH=R2
D=2001:db8:0:b010::/64    NH=R2
D=2001:db8:0:a020::/64    NH=R5
D=2001:db8:0:b020::/64    NH=R5
D=2001:db8:0:5555::/64    NH=R7
D=2001:db8:0:6666::/64    NH=SERb2
D=::/0                    NH=SERb1

            Figure 6: Complete Forwarding Tables Computed at R8

D=2001:db8:0:5555/64, it will be sent to R7 in the direction of SERa.
D=2001:db8:0:a010::/64    NH=R8
D=2001:db8:0:b010::/64    NH=R8
D=2001:db8:0:a020::/64    NH=R3
D=2001:db8:0:b020::/64    NH=R3
D=2001:db8:0:5555::/64    NH=R8
D=2001:db8:0:6666::/64    NH=SERb2
D=::/0                    NH=R8

    Figure 8: Forwarding Table For R5, Which Doesn't Understand Source-
                           Prefix-Scoped Routes

S=2001:db8:0:a010::31 or S=2001:db8:0:b010::31 as the source address
S=2001:db8:0:a000::/52 and another scoped to S=2001:db8:0:b000::/52.
D=2001:db8:0:1234::101, it would be routed through SER-b1 and out the
D=2001:db8:0:1234::/64) and have SERb1 monitor the presence of that
D=2001:db8:0:1234::101 out its uplink to ISP-B.

D=2001:db8:0:1234::/64 and respond with an ICMPv6 Destination
S=2001:db8:0:b010::31 and have them delivered to H501.  For this
S=2001:db8:0:b010::31 in order to reach H61 at D=2001:db8:0:6666::61.

D=2001:db8:0:6666::61, which is not desirable.

D=::/0) disappearance) by withdrawing itself as a default router.  R3
D=2001:db8:0:5678::501).  When the uplink from SERb1 to ISP-B fails,
S=2001:db8:0:b010::31 for H31) to reach hosts on the Internet is
