xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

schemaLocation="eppcom-1.0.xsd"/>
schemaLocation="epp-1.0.xsd"/>

minOccurs="0" maxOccurs="unbounded"/>
default="v4"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="7"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
use="required"/>
maxOccurs="7"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
use="required"/>
default="en"/>
use="required"/>
target="RFC3339"/> MUST be used to represent date-time values as XML
target="RFC0952"/> as updated by <xref target="RFC1123"/>.  At the
