PostURL = Protocol ://BroadcastURL Identifier
Protocol = "http" / "https"
BroadcastURL = HostName "/" PresentationPath
HostName = URI_SAFE_IDENTIFIER
PresentationPath = URI_SAFE_IDENTIFIER
ManifestPath = URI_SAFE_IDENTIFIER
Rsegmentpath = URI_SAFE_IDENTIFIER
Identifier = segment_file_name
   
fragmentedMP4stream = headerboxes fragments
headerboxes = ftyp moov
fragments = X fragment
fragment = Moof Mdat
    
