attribute =/ msid-attr
msid-attr = "msid:" identifier [ " " appdata ]
identifier = token
appdata = token
attribute =/ msid-semantic-attr
msid-semantic-attr = "msid-semantic:" token (" " identifier)*
token = <as defined in RFC 4566>
a=msid-semantic:LS xyzzy forolow


