Compliance = "Compliance" ":" ("*" | *(compliance-option))

compliance-option = compliance-namespace "="
                                option-item [ option-params ]

compliance-namespace = token

option-item = token | quoted-string

option-params = 1#( ";" option-param)

option-param = "cond" | "uncond" | token | quoted-string

Non-Compliance =  "Non-Compliance" ":" 1#non-compliance-option

proxy-host = host [ ":" port ]

non-compliance-option = compliance-option "@" proxy-host
