OHIO_DIRECTION_FORWARD                       = 0,
OHIO_DIRECTION_BACKWARD                      = 1

OHIO_TYPE_UNKNOWN                            = 0,
OHIO_TYPE_3270                               = 1,
OHIO_TYPE_5250                               = 2,
OHIO_TYPE_VT                                 = 3

OHIO_STATE_DISCONNECTED                      = 0,
OHIO_STATE_CONNECTED                         = 1

OHIO_PLANE_TEXT                              = 1,
OHIO_PLANE_COLOR                             = 2,
OHIO_PLANE_FIELD                             = 4,
OHIO_PLANE_EXTENDED                          = 8

OHIO_UPDATE_HOST                             = 0,
OHIO_UPDATE_CLIENT                           = 1,

OHIO_OWNER_UNKNOWN                          = 0,
OHIO_OWNER_APP                              = 1,
OHIO_OWNER_MYJOB                            = 1,
OHIO_OWNER_NVT                              = 2,
OHIO_OWNER_UNOWNED                          = 3,
OHIO_OWNER_SSCP                             = 4

OHIO_INPUTINHIBITED_NOTINHIBITED            = 0,
OHIO_INPUTINHIBITED_SYSTEM_WAIT             = 1,
OHIO_INPUTINHIBITED_COMMCHECK               = 2,
OHIO_INPUTINHIBITED_PROGCHECK               = 3,
OHIO_INPUTINHIBITED_MACHINECHECK            = 4,
OHIO_INPUTINHIBITED_OTHER                   = 5

