uri="http://xcap.example.com/s/presence-lists/users/bill/foo.xml"
version="Mon, 26 May 2003 19:43:31 GMT"
previous="Sun, 25 May 2003 12:22:38 GMT"
hash="TBD">
uri="http://xcap.example.com/s/presence-lists/
content="text/html;charset=iso-8859-1"/>
