objective = ["ResourceManager", objective-flags, loop-count,
objective-name = "ResourceManager"
objective-flags = uint .bits objective-flag ; as in the GRASP
loop-count = 0..255 ; as in the GRASP specification

objective-value = n-s-deployment-value ; An n-s-deployment-value is
service-information = [ source-ip-address, destination-ip-address,
resource-information = [ resource-requirement-pair 1, resource-
resource-requirement-pair = [ resourcetype, resval ]

