sess-id-param       = remote-param / logme-param / generic-param

remote-param        = "remote" EQUAL remote-uuid

logme-param         = "logme"



             Figure 7: Augmented BNF for the "logme" Parameter

