metadata-ehlo  = "METADATA"
             ; Complies with the <ehlo-line> ABNF production from RFC 5321.

bmtd-cmd       = "BMTD" SP chunk-size CR LF
chunk-size     = 1*DIGIT

bmtd-container = container-type container-specific-data

container-type = <2 octets, extensible>

container-specific-data = <remaining container data>

DIGIT = <Defined in RFC 5234>


ORCPT=rfc822;Dana@Ivory.example.net
