pwid-uri  = pwid-scheme ":" pwid-spec
pwid-spec = archive-id ":" archived-date [ content-spec ]
                 ":" archived-item

pwid-scheme = "pwid"
archive-id  = +( unreserved )

archived-date   = full-date datetime-delim full-pwid-time
datetime-delim  = "_" / "T"
full-pwid-time  = time-hour ["."] time-minute ["."] time-second "Z"
content-spec    = "_page" / "_part" / "_coll" / "_snapshot"
                       / "_rec" / "_other"

archived-item = URI / archived-item-id
archived-item-id  = +( unreserved )

