snmp_URI        = [ "udp." ] "snmp:" "//"  
                           [ user "@" ] host [ ":" port ] 
                           [ "/" [ engine ] [ ";" context ] "?" oid ] 
user            = // userName as specified by [RFC 3414] 
host            = // as specified by [RFC 2396] and [RFC 2732] 
port            = // as specified by [RFC 2396] 
engine          = "0x" hex [ (hex)*] 
                           // contextEngineID as specified by [RFC 3411] 
hex             = // Hex digit, as specified by [RFC 2396] 
context         = // contextName as specified by [RFC 3411] 
oid             = // as specified by [RFC 3061] 
       
engine          = ("-" "0x" hex [ (hex)* ] ) | 
                           ("2" "0x" enterprise-id hex-string-16 ) | 
                           ("3" "0x" enterprise-id "-" 
                            (("v4:" IPv4-address) | 
                             ("v6:" IPv6-address) | 
                             ("mac:" "0x" MAC-address) | 
                             ("txt:" text-string) | 
                             ("hex:" "0x" hex [ (hex)* ]))) 
       
