X=NATFW and all NAT(s) on the path are NATFW-aware.  This case is
IPGaNATus = GQ.[IP header].DestinationIPAddress.

identifier = X. (For other GIMPS packets the GaNAT may adopt the role
IPGaNATus = GQ.[IP header].DestinationIPAddress.

