X-TIMESTAMP-MAP=LOCAL:<cue time>,MPEGTS:<media time>
AttributeName=AttributeValue

AD-ID="XYZ123".  These attributes are OPTIONAL.
NEXT=YES attribute has an unknown duration, even if it has a PLANNED-
NAME="Bokmael",AUTOSELECT=YES,LANGUAGE="nb",
ASSOC-LANGUAGE="no",URI="nb-subtitles.m3u8"
AUTOSELECT=YES members of its Group.

GAP=YES attribute.  Instead, clients are encouraged to look for
DATERANGES=YES attribute, the client can request a Playlist Delta
RELOAD=YES attribute.

TYPE=PART, a Client with sufficient space in its download pipeline
TYPE=MAP, a Client with sufficient space in its download pipeline
DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="en", \
URI="main/english-audio.m3u8"
DEFAULT=NO,AUTOSELECT=YES,LANGUAGE="de", \
URI="main/german-audio.m3u8"
DEFAULT=NO,AUTOSELECT=NO,LANGUAGE="en", \
URI="commentary/audio-only.m3u8"
DEFAULT=YES,URI="low/main/audio-video.m3u8"
DEFAULT=NO,URI="low/centerfield/audio-video.m3u8"
DEFAULT=NO,URI="low/dugout/audio-video.m3u8"

DEFAULT=YES,URI="mid/main/audio-video.m3u8"
DEFAULT=NO,URI="mid/centerfield/audio-video.m3u8"
DEFAULT=NO,URI="mid/dugout/audio-video.m3u8"

DEFAULT=YES,URI="hi/main/audio-video.m3u8"
DEFAULT=NO,URI="hi/centerfield/audio-video.m3u8"
DEFAULT=NO,URI="hi/dugout/audio-video.m3u8"

VALUE="This is an example"
VALUE="Este es un ejemplo"

CHARACTERISTICS=
START-DATE="2014-03-05T11:15:00Z",PLANNED-DURATION=59.993, \
SCTE35-OUT=0xFC002F0000000000FF000014056FFFFFF000E011622DCAFF0 \
SCTE35-IN=0xFC002A0000000000FF00000F056FFFFFF000401162802E610 \
PATHWAY-ID="CDN-A"
URI="eng.m3u8",LANGUAGE="en",STABLE-RENDITION-ID="Audio-37262"
URI="https://b.example.com/content/videos/video12/eng.m3u8", \
LANGUAGE="en",STABLE-RENDITION-ID="Audio-37262"
STABLE-VARIANT-ID="Video-128"
STABLE-VARIANT-ID="Video-768"
STABLE-VARIANT-ID="Video-128"
STABLE-VARIANT-ID="Video-768"
START-DATE="2020-01-02T21:55:44.000Z",DURATION=15.0,
X-ASSET-URI="http://example.com/ad1.m3u8",X-RESUME-OFFSET=0,
X-RESTRICT="SKIP,JUMP",X-COM-EXAMPLE-BEACON=123
