DENY=WRITE or BOTH, terminating a period in which other clients
READ_LT         = 1,
WRITE_LT        = 2,
READW_LT        = 3,    /* blocking read */
WRITEW_LT       = 4     /* blocking write */
UNCHECKED       = 0,
GUARDED         = 1,
EXCLUSIVE       = 2
OPEN_DELEGATE_NONE      = 0,
OPEN_DELEGATE_READ      = 1,
OPEN_DELEGATE_WRITE     = 2
CLAIM_NULL              = 0,
CLAIM_PREVIOUS          = 1,
CLAIM_DELEGATE_CUR      = 2,
CLAIM_DELEGATE_PREV     = 3
UNSTABLE4       = 0,
DATA_SYNC4      = 1,
FILE_SYNC4      = 2
NF4REG          = 1,    /* Regular File */
NF4DIR          = 2,    /* Directory */
NF4BLK          = 3,    /* Special File - block device */
NF4CHR          = 4,    /* Special File - character device */
NF4LNK          = 5,    /* Symbolic Link */
NF4SOCK         = 6,    /* Special File - socket */
NF4FIFO         = 7,    /* Special File - fifo */
NF4ATTRDIR      = 8,    /* Attribute Directory */
NF4NAMEDATTR    = 9     /* Named Attribute */
NFS4_OK                 = 0,
NFS4ERR_PERM            = 1,
NFS4ERR_NOENT           = 2,
NFS4ERR_IO              = 5,
NFS4ERR_NXIO            = 6,
NFS4ERR_ACCES           = 13,
NFS4ERR_EXIST           = 17,
NFS4ERR_XDEV            = 18,
NFS4ERR_NODEV           = 19,
NFS4ERR_NOTDIR          = 20,
NFS4ERR_ISDIR           = 21,
NFS4ERR_INVAL           = 22,
NFS4ERR_FBIG            = 27,
NFS4ERR_NOSPC           = 28,
NFS4ERR_ROFS            = 30,
NFS4ERR_MLINK           = 31,
NFS4ERR_NAMETOOLONG     = 63,
NFS4ERR_NOTEMPTY        = 66,
NFS4ERR_DQUOT           = 69,
NFS4ERR_STALE           = 70,
NFS4ERR_BADHANDLE       = 10001,
NFS4ERR_NOT_SYNC        = 10002,
NFS4ERR_BAD_COOKIE      = 10003,
NFS4ERR_NOTSUPP         = 10004,
NFS4ERR_TOOSMALL        = 10005,
NFS4ERR_SERVERFAULT     = 10006,
NFS4ERR_BADTYPE         = 10007,
NFS4ERR_JUKEBOX         = 10008,
NFS4ERR_SAME            = 10009,/* nverify says attrs same */
NFS4ERR_DENIED          = 10010,/* lock unavailable */
NFS4ERR_EXPIRED         = 10011,/* lock lease expired */
NFS4ERR_LOCKED          = 10012,/* I/O failed due to lock */
NFS4ERR_GRACE           = 10013,/* in grace period */
NFS4ERR_FHEXPIRED       = 10014,/* file handle expired */
NFS4ERR_SHARE_DENIED    = 10015,/* share reserve denied */
NFS4ERR_WRONGSEC        = 10016,/* wrong security flavor */
NFS4ERR_CLID_INUSE      = 10017,/* clientid in use */
NFS4ERR_RESOURCE        = 10018,/* resource exhaustion */
NFS4ERR_MOVED           = 10019,/* filesystem relocated */
NFS4ERR_NOFILEHANDLE    = 10020 /* current FH is not set */
READ_LT         = 1,
WRITE_LT        = 2,
READW_LT        = 3,    /* blocking read */
WRITEW_LT       = 4     /* blocking write */
UNCHECKED4      = 0,
GUARDED4        = 1,
EXCLUSIVE4      = 2
OPEN4_NOCREATE  = 0,
OPEN4_CREATE    = 1
NFS_LIMIT_SIZE          = 1,
NFS_LIMIT_BLOCKS        = 2 /* experimental;
                                          subject to change*/
OPEN_DELEGATE_NONE      = 0,
OPEN_DELEGATE_READ      = 1,
OPEN_DELEGATE_WRITE     = 2
CLAIM_NULL              = 0,
CLAIM_PREVIOUS          = 1,
CLAIM_DELEGATE_CUR      = 2,
CLAIM_DELEGATE_PREV     = 3
RPC_GSS_SVC_NONE        = 1,
RPC_GSS_SVC_INTEGRITY   = 2,
RPC_GSS_SVC_PRIVACY     = 3
UNSTABLE4       = 0,
DATA_SYNC4      = 1,
FILE_SYNC4      = 2
OP_ACCESS               = 2,
OP_CLOSE                = 3,
OP_COMMIT               = 4,
OP_CREATE               = 5,
OP_DELEGPURGE           = 6,
OP_DELEGRETURN          = 7,
OP_GETATTR              = 8,
OP_GETFH                = 9,
OP_LINK                 = 10,
OP_LOCK                 = 11,
OP_LOCKT                = 12,
OP_LOCKU                = 13,
OP_LOOKUP               = 14,
OP_LOOKUPP              = 15,
OP_NVERIFY              = 16,
OP_OPEN                 = 17,
OP_OPENATTR             = 18,
OP_PUTFH                = 19,
OP_PUTPUBFH             = 20,
OP_PUTROOTFH            = 21,
OP_READ                 = 22,
OP_READDIR              = 23,
OP_READLINK             = 24,
OP_REMOVE               = 25,
OP_RENAME               = 26,
OP_RENEW                = 27,
OP_RESTOREFH            = 28,
OP_SAVEFH               = 29,
OP_SECINFO              = 30,
OP_SETATTR              = 31,
OP_SETCLIENTID          = 32,
OP_VERIFY               = 33,
OP_WRITE                = 34
OP_CB_GETATTR           = 2,
OP_CB_RECALL            = 3
