SEARCH=INTHREAD and THREAD=REFS as capabilities. This extension adds
THREAD=ORDEREDSUBJECT is defined such that every message is either a
THREAD=REFS.

THREAD=REFERENCES (see [RFC5256]) which concerns itself with the
THREAD=REFS sorts threads by the most recent INTERNALDATE in each
capability   =/ "SEARCH=INTHREAD" / "THREAD=REFS"

search-key   =/ "INTHREAD" SP search-key / "MESSAGEID" SP "<"
                        id-left "@" id-right ">" / "THREADROOT" /
                        "THREADLEAF"

thread-alg   =/ "REFS"

search-return-opt =/ "THREAD=" thread-alg


SEARCH=INTHREAD.

