Overload-Control = "Overload-Control" HCOLON 1*(*(overload-category)1(overload-drop-probability))
overload-category = "oc COMMA" EQUAL overload-category-value
overload-category-value = 1*ALPHA
overload-drop-probability = "odp" EQUAL overload-drop-probability-value
overload-drop-probability-value = 1DIGIT/2DIGIT/"100"

