type="application/atom+xml"
href="URI for Posting goes here"
title="The name of the site." />


type="application/atom+xml"
href="URI for Editing goes here"
title="Readable desc of the entry." />


rel="next" whose URI points to the next block of entries on the site.
rel="service.post", the URI of which is a PostURI.  Individual
type="application/atom+xml"
href="URI goes here"
title="The name of the site." />


title="The name of the site.">


