pk11-URI              = pk11-scheme ":" pk11-identifier
pk11-scheme           = "pkcs11"
pk11-identifier       = *1(pk11-attr *(%x3B pk11-attr))
pk11-attr             = pk11-token / pk11-manufacturer /
                             pk11-serial / pk11-model / pk11-object /
                             pk11-objecttype / pk11-passphrasedialog
pk11-semicolon        = "\" %x3B
pk11-label            = *(%x00-3A / %x3C-FF / pk11-semicolon)
pk11-token            = "token" "=" pk11-label
pk11-manufacturer     = "manufacturer" "=" pk11-label
pk11-serial           = "serial" "=" pk11-label
pk11-model            = "model" "=" pk11-label
pk11-object           = "object" "=" pk11-label
pk11-objecttype       = "objecttype" "=" ("public" / "private" /
                             "cert" / "secretkey" / "data")
pk11-passphrasedialog = "passphrasedialog" "=" "builtin" / exec
exec                  = "exec" ":" filename
filename              = 1*(%x00-3A / %x3C-FF / pk11-semicolon)

manufacturer=Snake Oil, Inc.;
serial=;
model=1.0;
object=my-certificate;
objecttype=cert;
passphrasedialog=exec:/bin/askpass.sh

manufacturer=Sun Microsystems, Inc.;
passphrasedialog=exec:/bin/askpass.sh

object=my-certificate;
objecttype=cert;
passphrasedialog=exec:/bin/askpass.sh
