TXT=191772 bytes) (Obsoletes RFC1244) (Also RFC2196)

HTML= bytes) (Obsoletes RFC1290) (Also RFC1402)

HTML= bytes) (Also RFC1302)

HTML= bytes) (Also RFC1308)

HTML= bytes) (Also RFC1355)

TXT =123008 HTML= bytes) (Obsoletes RFC1392) (Also RFC1983)

TXT =235112 HTML= bytes) (Also RFC1580)

