AFI=47, IDI=0005, DFI=80h, AA=nnn, ... ;
    
AFI=47, IDI=0005, DFI=80h, AA=mmm, ... ; and,
    
AFI=39, IDI=840, DFI=dd, ORG=xxx, ....
    
    
AFI=47, IDI=0005, DFI=80h, AA=zzz, Rsvd=0, RD=rrr.
    
    
AFI=47, IDI=0005, DFI=80h, AA=kkk
    
    
AFI=47, IDI=0005, DFI=80h, AA=kkk, (Rsvd=0), RD=jjj.
    
    
DCC=840. In this case, a regional applies for an ORG identifier from
DCC=840-based NSAPs is provided in Section A.2.
    
    
