Up   = lower layer is Up                 tlu = This-Layer-Up
Down = lower layer is Down               tld = This-Layer-Down
Open = administrative Open               tls = This-Layer-Started
Close= administrative Close              tlf = This-Layer-Finished

TO-  = Timeout with counter expired      zrc = Zero-Restart-Count

RCR- = Receive-Configure-Request (Bad)
RCA  = Receive-Configure-Ack             sca = Send-Configure-Ack
RCN  = Receive-Configure-Nak/Rej         scn = Send-Configure-Nak/Rej

RTR  = Receive-Terminate-Request         str = Send-Terminate-Request
RTA  = Receive-Terminate-Ack             sta = Send-Terminate-Ack

RUC  = Receive-Unknown-Code              scj = Send-Code-Reject
RXJ- = Receive-Code-Reject (catastrophic)
       or Receive-Protocol-Reject
RXR  = Receive-Echo-Request              ser = Send-Echo-Reply
       or Receive-Echo-Reply
       or Receive-Discard-Request
