CN=Bells, OU=Computer Science,
O=University College London, C=GB

CN=domain-nicknames,
CN=Bells, OU=Computer Science,
O=University College London, C=GB
CN=euclid, CN=domain-nicknames,
CN=Bells, OU=Computer Science,
O=University College London, C=GB


TextTableValue=bloomsbury.ac.uk


CN=Bells, OU=Computer Science,
O=University College London, C=GB

CN=MTA Bilateral Agreements,
CN=Bells, OU=Computer Science,
O=University College London, C=GB

CN=Q3T21, ADMD=Gold 400, C=GB

   There would be an entry in this table with the Relative Distinguished
   Name of the table entry being the Distinguished Name of the MTA being
   referred to.  The MTA Bilateral information would be an attribute in
   this entry.  Using a non-standard notation, the Distinguished Name of
   the table entry is:


DistinguishedNameTableValue=<CN=Q3T21, ADMD=Gold 400, C=GB>,
CN=MTA Bilateral Agreements,
CN=Bells, OU=Computer Science,
O=University College London, C=GB
O=University College London, C=GB

CN=private subtree,
O=University College London, C=GB


O=Inria, C=FR,
CN=private subtree,
O=University College London, C=GB

A=Mailnet; C=FI;
O=ISODE Consortium, C=GB
