c=                         o=Internet
                 |                             |
ipNw=       as=             dbl=           asB=
           |                            |              |
ipNd=                       ipG=           asRef=
           |                            |
ipNwIf=                     ipRef=

              Figure 1: Overall relationship of objects.

objectClass= organizationalUnit
organizationalUnitName= IP networks
description= root of IP number tree
ou=IP networks
                               |
dbl=150.0.0.0-150.100.0.0
                               |
ipG=150.80.0.0
                               |
ipG=150.80.240.0
                               |
ipRef=150.80.254.1    ipRef=150.80.254.2      ipRef=150.80.254.3

      Figure 2: Example population of IP namespace tree according
                to delegation and subnetworking.

objectClass= organizationalUnit
organizationalUnitName= AS numbers
description= root of Autonomous System number space

