URL = ftp://ftp.isi.edu/in-notes/iana/assignments/introduction
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/version-numbers
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/protocol-numbers
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/port-numbers
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/multicast-addresses
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/sun-rpc-numbers
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/ip-parameters
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/icmp-parameters
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/tcp-parameters
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/telnet-options
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/dns-parameters
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/mail-parameters
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/bootp-and-dhcp-
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/address-family-numbers
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/foobar-af-numbers
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/directory-system-names
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/publisher-id
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/ospf-authentication-
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/media-types


charset=us-ascii         ia5-text                     [RFC1494]
charset=iso-8859-x       EBP - GeneralText            [RFC1494]
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/media-types/media-
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/character-sets
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/smi-numbers
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/enterprise-numbers
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/sgmp-vendor-specific-
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/arp-parameters
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/ieee-802-numbers
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/ethernet-numbers
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/x25-type-numbers
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/public-data-network-
ZZZZ = 0000    as required

F = 0          because the address is a physical address;

ZZ = 00        and

ZZZZ = 0000    as required

F = 1          because the address is a logical address;

r = h * 256 + i

ZZ = 00        and

URL = ftp://ftp.isi.edu/in-notes/iana/assignments/milnet-parameters
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/xns-protocol-types
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/ip-xns-mapping
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/pronet80-type-numbers
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/novell-sap-numbers
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/ppp-numbers
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/machine-names
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/operating-system-names
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/terminal-type-names
URL = ftp://ftp.isi.edu/in-notes/iana/assignments/service-names
