S=user; O=org ltd.; OU1=sect1; P=org; A=rel400; C=aq;
G=john; I=w; S=doe; P=org; A=rel400; C=aq;

value="password" notation.  The double quotes around
S=nosuchuser; to do connectivity and availability
C=ch; matches only case a).
C=CH; operates MTA-B, only connected to public X.25.  A second
P=REMOTE; A=ARCOM; C=CH;.  It is therefore possible to set RELAY-MTA
C=CH;ADMD=ARCOM;PRMD=REMOTE;O=Big-Org is documented with its own
P=SWITCH; A=ARCOM; C=CH;
Internet-RFC-1006=chx400.switch.ch
IXI=20432840100520;
S=Eppenberger; O=SWITCH; P=SWITCH; A=ARCOM; C=CH;

