AUTHOR-NAME= <first m. last>
AUTHOR-LOCATION= <city, state>
SIGNATURE-SYSTEM= <name of signature system>
AUTHOR-NAME= <first m. last>
HASH-FUNCTION= <md5,sha, etc.>
TRUSTED-PARTY= <identity of T>
AUTHOR-VERIFICATION-METHOD= <how authors are verified off-line>
AUTHOR-NAME= <first m. last>
AUTHOR-ORGANIZATION= <company, school, etc.>
HASH-FUNCTION= <md5,sha, etc.>
DATE= <date>
