DomainComponent=S.Kille, DomainComponent=CS, DomainComponent=UCL,
DomainComponent=AC, DomainComponent=UK

DomainComponent=*, DomainComponent=*,
DomainComponent=MIT, DomainComponent=COM


DomainComponent=0, DomainComponent=0, DomainComponent=40,
DomainComponent=128, DomainComponent=IN-ADDR, DomainComponent=ARPA


AssociatedDomain = UCL.AC.UK


DomainComponent=UCL, DomainComponent=AC,
DomainComponent=UK


