CN=Directory Manager

CN=Postmaster

CN=Secretary

C=GB  C=FR  C=US

O=MultiNat---->O=MultiNat<----O=MultiNat

                         /    |    \
                        /     |     \
                       /      |      \

l=abc      ou=def     l=fgi

                     ---> means "alias to"

C=GB C=FR C=US

O=MultiNat   O=MultiNat   O=MultiNat

L=FR    L=GB<---L=GB     |   L=US--->L=US   L=FR
          \                      |                 /
           ------------------->L=FR<----------------

                      ---> means "alias to"

P=switch; A=arcom; C=ch;

objectClass=top & country & domainRelatedObject & friendlyCountry
country=CH
associatedDomain=ch
friendlyCountryName=CH
friendlyCountryName=Confoederatio Helvetica
friendlyCountryName=Schweiz
friendlyCountryName=Suisse
friendlyCountryName=Svizzera
friendlyCountryName=Switzerland

objectClass=top & organization & mhsUser & domainRelatedObject
description=Swiss Academic and Research Network
organizationName=SWIss TeleCommunication system for Higher
organizationName=Swiss Academic and Research Network
organizationName=SWITCH
localityName=Zuerich
localityName=Zurich
localityName={T.61}Z\c8urich
stateOrProvinceName=ZH
stateOrProvinceName=Zuerich
stateOrProvinceName=Zurich
stateOrProvinceName={T.61}Z\c8urich
postalAddress=SWITCH
                  Limmatquai 138
                  CH-8001 Zurich
postalCode=CH-8001
streetAddress=Limmatquai 138
telephoneNumber=+41 1 268 1515
facsimileTelephoneNumber=+41 1 268 1568
seeAlso=CN=Postmaster, O=SWITCH, C=CH
mhsORAddresses=S=postmaster, O=switch; P=switch; A=arcom; C=ch;
associatedDomain=switch.ch
objectClass=top & organizationalUnit
description=The SWITCH X.500 pilot project
organizationalUnitName=SWITCHdirectory
localityName=Zurich
localityName=Zuerich
localityName={T.61}Z\c8urich
stateOrProvinceName=Zurich
stateOrProvinceName=Zuerich
stateOrProvinceName=ZH
stateOrProvinceName={T.61}Z\c8urich
postalAddress=SWITCHdirectory
                  SWITCH
                  Limmatquai 138
                  CH-8001 Zurich
postalCode=CH-8001
streetAddress=Limmatquai 138
telephoneNumber=+41 1 268 1540
facsimileTelephoneNumber=+41 1 268 1568

objectClass=top & organizationalRole & mhsUser
commonName=Directory Manager
description=SWITCH Directory Managers
roleOccupant=CN=Martin Berli, O=SWITCH, C=CH
roleOccupant=CN=Thomas Lenggenhager, O=SWITCH, C=CH
localityName=Zuerich
localityName=Zurich
localityName={T.61}Z\c8urich
stateOrProvinceName=Zurich
stateOrProvinceName=Zuerich
stateOrProvinceName=ZH
stateOrProvinceName={T.61}Z\c8urich
postalAddress=SWITCHdirectory
                  SWITCH
                  Limmatquai 138
                  CH-8001 Zurich
postalCode=CH-8001
streetAddress=Limmatquai 138
telephoneNumber=+41 1 268 1540
facsimileTelephoneNumber=+41 1 268 1568
mhsORAddresses=S=switchinfo; O=switch; P=switch; A=arcom; C=ch;
objectClass=top & organizationalRole & mhsUser
commonName=Postmaster
commonName=Helpdesk
roleOccupant=CN=Christoph Graf, O=SWITCH, C=CH
roleOccupant=CN=Felix Kugler, O=SWITCH, C=CH
roleOccupant=CN=Marcel Parodi, O=SWITCH, C=CH
roleOccupant=CN=Marcel Schneider, O=SWITCH, C=CH
telephoneNumber=+41 1 268 1520
facsimileTelephoneNumber=+41 1 268 1568
mhsORAddresses=S=postmaster; O=switch; P=switch; A=arcom; C=ch;

objectClass=top & organizationalRole & quipuObject
commonName=Secretary
roleOccupant=CN=Franziska Remund, O=SWITCH, C=CH
objectClass=top & person & organizationalPerson & mhsUser &
commonName=Thomas Lenggenhager
commonName=T. Lenggenhager
surname=Lenggenhager
description=SWITCHinfo, Project Leader
localityName=Zuerich
localityName=Zurich
localityName={T.61}Z\c8urich
stateOrProvinceName=ZH
stateOrProvinceName=Zuerich
stateOrProvinceName=Zurich
stateOrProvinceName={T.61}Z\c8urich
postalAddress=SWITCH
                  Limmatquai 138
                  CH-8001 Zurich
postalCode=CH-8001
streetAddress=Limmatquai 138
telephoneNumber=+41 1 268 1540
facsimileTelephoneNumber=+41 1 268 1568
mhsORAddresses=S=lenggenhager; O=switch; P=switch; A=arcom; C=ch;
userPassword=secret
textEncodedORaddress={T.61}S=lenggenhager; O=switch; P=switch; \
A=arcom; C=ch;
rfc822mailbox=lenggenhager@switch.ch
secretary=CN=Franziska Remund, O=SWITCH, C=CH
