p=jq+1 to support the optional verification of group parameters;

cn=us,o=gov,ou=nist.  The certificate contains a DSA public key with
O=gov; C=US
OU=Dept. Arquitectura de Computadors; O=Universitat Politecnica de
