c                      = nfs://server/a/c

nfsURL        = "nfs" ":" relativeURL
relativeURL   = net_path | abs_path | rel_path
net_path      = "//" hostport [ abs_path ]
abs_path      = "/"  rel_path
rel_path      = [ path_segments ]

hostport      = host [ ":" port ]
host          = hostname | hostnumber
hostname      = *( domainlabel "." ) toplabel
domainlabel   = alphanum | alphanum *( alphanum | "-" ) alphanum
toplabel      = alpha | alpha *( alphanum | "-" ) alphanum
hostnumber    = 1*digit "." 1*digit "." 1*digit "." 1*digit
port          = *digit

url-path      = [ "/" ] path_segments
path_segments = segment *( "/" segment )
segment       = *pchar
pchar         = unreserved | escaped | ":" | "@" | "&" | "=" | "+"

reserved      = ";" | "/" | "?" | ":" | "@" | "&" | "=" | "+"
unreserved    = alpha | digit | mark
mark          = "$" | "-" | "_" | "." | "!" | "~" |
                      "*" | "'" | "(" | ")" | ","

escaped       = "%" hex hex
hex           = digit | "A" | "B" | "C" | "D" | "E" | "F" |
                              "a" | "b" | "c" | "d" | "e" | "f"

alphanum      = alpha | digit
alpha         = lowalpha | upalpha

lowalpha = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" |
                 "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" |
                 "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"
upalpha  = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" |
                 "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" |
                 "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
digit    = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" |
                 "8" | "9"
