CLP=0+1, meaning cells with CLP=0 or CLP=1.

I=1/PCR and L=CDVT.  The second, which polices cells which are in
PTI=0, of the next AAL5 PDU arrives.  The AAL5 PDU with the missing
PTI=1 cell is discarded due to re-assembly timeout and one packet is
PTI=1, of the next AAL5 PDU arrives.  The AAL5 PDU with the missing
PTI=1 cell and the next AAL5 PDU are discarded due to re-assembly
CER = Cells with payload errors / Total Cells Transmitted.

CLR = Lost Cells / Total Cells Transmitted.

CMR = Misinserted Cells / Total Cells Transmitted.

