D = Dead (Destination Host either dead or inaccessible [due to
             network partitioning or local IMP failure] from the BBN
             Terminal IMP.)

R = Refused (Destination Host returned a CLS to the initial RFC.)

T = Timed out (Destination Host did not respond in any way to the
             initial RFC, although not dead.)

H = 1/2 Open (Destination Host opened a connection but then either
             immediately closed it, or did not respond further.)

O = Open (Destination Host opened a connection and was accessible to
             users.)


