K = K1 for R=0 K=K2 for R=1

ceiling = reuse * (exp(T-hold/decay-half-life) * log(2))

decay-array-size = (Tmax/delta-t)

max-ratio = min(ceiling/reuse, exp((1 / (half-life/reuse-
scale-factor = reuse-index-array-size / (max-ratio - 1)

setfigure-of-merit =1

setfigure-of-merit =figure-of-merit *decay-array-ok [t-diff ]+ 1

setfigure-of-merit =ceiling
sett-diff =t-now -t-updated

sett-updated =t-now

