list_mailbox = <list_mailbox> as defined in [RFC-2060]

mailbox = <mailbox> as defined in [RFC-2060]

mailbox_referral = <tag> SPACE "NO" SPACE
      <referral_response_code> (text / text_mime2)
      ; See [RFC-2060] for <tag>, text and text_mime2 definition
referral_response_code = "[" "REFERRAL" 1*(SPACE <url>) "]"
      ; See [RFC-1738] for <url> definition

rlist = "RLIST" SPACE mailbox SPACE list_mailbox

rlsub = "RLSUB" SPACE mailbox SPACE list_mailbox

