realm       = [realm "."] label Expand






nai         = username / ( username "@" realm )
username    = dot-string
realm       = realm "." label

realm       = [realm "."] label

label       = let-dig * (ldh-str)

ldh-str     = *( Alpha / Digit / "-" ) let-dig

dot-string  = string / ( dot-string "." string )

string      = char / ( string char )

char        = c / ( "\" x )

let-dig     = Alpha / Digit

Alpha       = %x41-5A / %x61-7A   ; A-Z / a-z

Digit       = %x30-39  ;0-9

c           = < any one of the 128 ASCII characters, but
                  not any special or SP >

special     = "<" / ">" / "(" / ")" / "[" / "]" / "\" / "." Expand
                  / "," / ";" / ":" / "@" / %x22  / Ctl
                 ; %x22 is '"'







x           = %x00-7F
                 ; all 127 ASCII characters, no exception

special     = "<" / ">" / "(" / ")" / "[" / "]" / "\" / "."
                  / "," / ";" / ":" / "@" / %x22  / Ctl
                 ; %x22 is '"'

SP          = %x20 ; Space character

special     = "<" / ">" / "(" / ")" / "[" / "]" / "\" / "."
                  / "," / ";" / ":" / "@" / %x22  / Ctl

Ctl         = %x00-1F / %x7F
                 ; the control characters (ASCII codes 0 through 31
                 ; inclusive and 127)

fred=?#$&*+-/^smith@bigco.com
