T_last = tcpnow, T_prev = tcpnow, W_used = 0

ssthresh =  max(ssthresh, 3*cwnd/4)
win =  min(cwnd, receiver's declared max window)
cwnd =  max(win/2, MSS)
T_prev = tcpnow
W_used = 0

T_last = tcpnow

T_prev = tcpnow
W_used = 0
W_used =  max(W_used, amount of unacknowledged data)
ssthresh =  max(ssthresh, 3*cwnd/4)

win =  min(cwnd, receiver's declared max window)
cwnd = (win + W_used)/2
T_prev = tcpnow
W_used = 0

