sKEYID = prf(Ni | Nr, g^xy | CKY-I | CKY-R).

Kir = prf(0, Ni | Nr)

Kir = prf(0, sKi | sKr)

Kir = prf(0, Ni | Nr)

K1 = low 56 bits of md5(0|sKEYID)
K2 = low 56 bits of md5(1|sKEYID)
K3 = low 56 bits of md5(2|sKEYID)
sNKEYID = prf(sKEYID, Ni | Nr )

Kir = prf(sKEYID, Ni | Nr)

A = (rg^y)
B = A^x = (rg^y)^x = (r^x)(g^(xy))
C = B*r^(-x) = (r^x)(r^-(x))(g^(xy)) = g^(xy)

U=2.  For example, the field element U^2 + 1 would be represented by
B = u^18 + u^17 + u^16 + u^13 + u^12 + u^9 + u^8 + u^7 + u^3 + u^2 +
X = u^6 + u^5 + u^4 + u^3 + u + 1

Y = u^8 + u^7 + u^6 + u^3.

B = u^12 + u^11 + u^10 + u^9 + u^7 + u^6 + u^5 + u^3 + 1.

X = u^4 + u^3 and Y = u^3 + u^2 + 1.

