VPI = 0
VCI = 15.
Function = 1. Bring the port into service. All
Function = 2. Take the port out of service. Any cells
Function = 3. Cells arriving at the output port from
Function = 4. Cells arriving at the input port from
Function = 5. Both internal and external loopback are
Function = 6. All connections that arrive at the
Function = 7. For each bit that is set in the Event
Function = 8. Sets the transmit cell rate of the
CLP=1, are policed by the first policer; but only cells
CLP=1) are subject to the policing action of both policers
CLP=1) in either policer, that the policer determines to be
