Fub3IuaW5ub3NvZnQuY29tPg==
achar            = uchar / "&" / "=" / "~"
                                ; see [BASIC-URL] for "uchar" definition

auth             = ";AUTH=" ( "*" / enc-auth-type )

enc-auth-type    = enc-sasl / enc-ext

enc-ext          = "+" ("APOP" / 1*achar)
                              ;APOP or encoded extension mechanism name

enc-sasl         = 1*achar
                              ;encoded version of [SASL] "auth_type"

enc-user         = 1*achar
                              ;encoded version of [POP3] mailbox

pop-url          = "pop://" server

server           = [user-auth "@"] hostport
                              ;See [BASIC-URL] for "hostport" definition

user-auth        = enc-user [auth]

