page-length=A4
page-width=A4
encoding=1-dimensional
resolution=Coarse
page-length=A4             no bit set
page-length=B4          19              21
page-length=Unlimited   20              20

page-width=A4              no bit set
page-width=A3           18              22
page-width=B4           17              23

encoding=1-dimensional     no bit set
encoding=2-dimensional  16              8
encoding=Uncompressed   26              30

resolution=Coarse          no bit set
resolution=Fine         15              9

