AAAAA==
DN="CN=Setec Astronomy, OU=Persona Certificate,
O=&quot;RSA Data Security, Inc.&quot;, C=US"
CRYPTOPTS="SHTTP-Privacy-Enhancements: recv-refused=encrypt;
HREF="shttp://research.nsa.gov/skipjack-holes.html">
