O=Optional, R=Recommended for Origination/Receipt):

mime-parameter =  "bp-type=" ( object-identifier / 1*DIGIT=

Content-type=application/x400-bp; bp-type=6

Content-type=application/x400-bp; bp-type=2.6.1.4.5

mime-to-x400 = "Wanted-X400-Conversion" ":"
                      [ mime-from ]  [ x400-object-id ]
                      "in" x400-encoding

x400-object-id =  "to" ( object-identifier-2 / "tunnel" )
x400-encoding = "bp14" / "bp15" / "ftbp" / "ia5"
mime-from = "from" mime-type
mime-type = word

charset=us-ascii         ia5-text                     6.1
charset=ISO-8859-x       EBP - GeneralText            6.2
FALSE=, the mapping should be to message/RFC822.

g0 = 6 (should be 2, but ignore the difference)
g1 = NULL
g2 = NULL
g3 = NULL
c0 = 1 (ASCII control)
c1 = NULL
leftset = &g0 (current input set, low)
rightset = &g1 (current input set, high)
lowset = 6 (output set, low)
highset = NULL (output set, high)
charset = US-ASCII

leftset = &g0;
leftset = &g
rightset = &g1;
rightset = &g2;
rightset = &g3;
g0 = chartoid[lastchar, next character]
g1 = chartoid[lastchar, next character]
g2 = chartoid[lastchar, next character]
g3 = chartoid[lastchar, next character]
charset = idtoname[g1]
highset = g1
