TTL = NET_DIAMETER is used for each attempt.  Each time, the timeout
MinimalLifetime =    (current time + 2*NET_TRAVERSAL_TIME -
                           2*HopCount*NODE_TRAVERSAL_TIME).

TTL == 1) with the unreachable destinations, and their corresponding
TTL == 1, to be used by a neighboring receiver in determine how long
TIMEOUT_BUFFER = 0.

DELETE_PERIOD = K * max (ACTIVE_ROUTE_TIMEOUT, HELLO_INTERVAL)
                         (K = 5 is recommended).

