D = Dead (Destination Host either dead or inaccessible [due to network
    partitioning or local IMP failure] from the BBN Terminal IMP.)

F = Full (Destination Host opened a connection, informed user that all
    Network ports were in use, and immediately closed the connection.)

H = 1/2 Open (Destination Host opened a connection but then either
    immediately closed it, or did not respond any further.)

O = Open (Destination Host opened a connection and was accessible to
    users.)

R = Refused (Destination Host returned a CLS to the initial RFC.)

T = Timed out (Destination Host did not complete the ICP and open a
    connection with 60 seconds.)
