alarmModelVarbindSubtree = 0.0
alarmModelResourcePrefix = usmStats (1.3.6.1.6.3.15.1.1)

alarmModelVarbindSubtree = ifIndex (1.3.6.1.2.1.2.2.1.1)
alarmModelResourcePrefix = 0.0

alarmModelVarbindSubtree = 0.0
alarmModelResourcePrefix = 0.0

alarmModelVarbindSubtree = bgpPeerState
                                                (1.3.6.1.2.1.15.3.1.2)
alarmModelResourcePrefix = bgpPeerRemoteAddr
            (1.3.6.1.2.1.15.3.1.7)

