Content-Language = "Content-Language" ":" 1#Language-tag

Content-Language = "Content-Language" ":" [CFWS] Language-List
Language-List = Language-Tag [CFWS]
                         *("," [CFWS] Language-Tag [CFWS])

obs-content-language = "Content-Language" *WSP ":"
                              [CFWS] Language-List

Accept-Language = "Accept-Language" ":"
                             1#( language-range [ ";" "q" "=" qvalue ] )

Accept-Language = "Accept-Language:" [CFWS] language-q
                        *( "," [CFWS] language-q )
language-q = language-range [";" [CFWS] "q=" qvalue ] [CFWS]
qvalue         = ( "0" [ "." 0*3DIGIT ] )
                     / ( "1" [ "." 0*3("0") ] )
Obs-accept-language = "Accept-Language" *WSP ":" [CFWS]
           obs-language-q *( "," [CFWS] obs-language-q ) [CFWS]
obs-language-q = language-range
            [ [CFWS] ";" [CFWS] "q" [CFWS] "=" qvalue ]

