xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

schemaLocation="eppcom-1.0.xsd"/>
schemaLocation="epp-1.0.xsd"/>

minOccurs="0" maxOccurs="unbounded"/>
default="v4"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="7"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
use="required"/>
maxOccurs="7"/>
minOccurs="0" maxOccurs="unbounded"/>
minOccurs="0"/>
minOccurs="0"/>
minOccurs="0"/>
use="required"/>
default="en"/>
use="required"/>
