m=video 31394 RTP/AVP 111

a=rtpmap:111 DV/90000

a=fmtp:<format> <format-specific parameters>

a=fmtp:<payload type> encode=<DV-video encoding>

a=fmtp:<payload type> audio=<audio bundled>

v=0
o=ikob 2890844526 2890842807 IN IP4 126.16.64.4
s=POI Seminar
i=A Seminar on how to make Presentations on the Internet
u=http://www.koganei.wide.ad.jp/~ikob/POI/index.html
e=ikob@koganei.wide.ad.jp (Katsushi Kobayashi)
c=IN IP4 224.2.17.12/127
t=2873397496 2873404696
m=audio 49170 RTP/AVP 112
a=rtpmap:112 L16/32000/2
m=video 50000 RTP/AVP 113
a=rtpmap:113 DV/90000
a=fmtp:113 encode=SD-VCR/525-60 audio=none Expand





a=fmtp:113 encode=SD-VCR/525-60
a=fmtp:113 audio=none

a=fmtp:113 encode=SD-VCR/525-60 audio=none

v=0
o=ikob 2890844526 2890842807 IN IP4 126.16.64.4
s=POI Seminar
i=A Seminar on how to make Presentations on the Internet
u=http://www.koganei.wide.ad.jp/~ikob/POI/index.html
e=ikob@koganei.wide.ad.jp (Katsushi Kobayashi)
c=IN IP4 224.2.17.12/127
t=2873397496 2873404696
m=video 49170 RTP/AVP 112 113
a=rtpmap:112 DV/90000
a=fmtp:112 encode=SD-VCR/525-60 audio=bundled Expand
a=fmtp:113 encode=306M/525-60 audio=bundled






a=fmtp: 112 encode=SD-VCR/525-60
a=fmtp: 112 audio=bundled
a=fmtp: 113 encode=306M/525-60
a=fmtp: 113 audio=bundled

a=fmtp:112 encode=SD-VCR/525-60 audio=bundled
a=fmtp:113 encode=306M/525-60 audio=bundled

