xmlns="" are changed as follows.  When canonicalizing the
xmlns="" if and only if all of the conditions are met:
Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
targetNamespace="http://www.w3.org/2001/10/xml-exc-c14n#"
version="0.1" elementFormDefault="qualified">

type="ec:InclusiveNamespaces"/>
