sglist          = sgitem / sgitem "," sglist
sgitem          = scope-name ":" ip-addr
ip-addr         = ipv4-number | ipv6-number
scope-name      =  ; See RFC 2608 for the format of scope names.
ipv4-number     =  1*3DIGIT 3("." 1*3DIGIT)
ipv6-number     = ;See RFC 2373 [9] Section 2.2

