service-parms = [ [app-service] *(":" app-protocol)]
app-service   = experimental-service  / iana-registered-service
app-protocol  = experimental-protocol / iana-registered-protocol
experimental-service      = "x-" 1*30ALPHANUMSYM
experimental-protocol     = "x-" 1*30ALPHANUMSYM
iana-registered-service   = ALPHA *31ALPHANUMSYM
iana-registered-protocol  = ALPHA *31ALPHANUM
ALPHA         =  %x41-5A / %x61-7A   ; A-Z / a-z
DIGIT         =  %x30-39 ; 0-9
SYM           =  %x2B / %x2D / %x2E  ; "+" / "-" / "."
ALPHANUMSYM   =  ALPHA / DIGIT / SYM
target = [initial domain]
naptr-done = false


NAPTR-RRset = [DNSlookup of NAPTR RRs for target]
rr-done = false
cur-rr = [first NAPTR RR]


rr-done = true
target= [REPLACEMENT target of NAPTR RR]
cur-rr = [next rr in list]


naptr-done = true
port = -1


SRV-RRset = [DNSlookup of SRV RRs for target]
target = [target of first RR of SRV-RRset]
port = [port in first RR of SRV-RRset]
host = [DNSlookup of target]


