proto = getprotobyname("icmp");

s = socket(AF_INET, SOCK_RAW, proto->p_proto);

fd = socket(AF_INET6, SOCK_RAW, IPPROTO_ICMPV6);

x == -1:       use kernel default
x == -1:       use kernel default
cmsgptr = CMSG_NXTHDR(&msg, cmsgptr)) {
ptr = CMSG_DATA(cmsgptr);
ptr = CMSG_DATA(cmsgptr);
extlen = inet6_rth_space(IPV6_RTHDR_TYPE_0, 3);
cmsglen = CMSG_SPACE(extlen);
cmsgptr = malloc(cmsglen);
extptr = CMSG_DATA(cmsgptr);
extptr = inet6_rth_init(extptr, extlen, IPV6_RTHDR_TYPE_0, 3);

segments = 100;        /* Enough */
extlen = inet6_rth_space(IPV6_RTHDR_TYPE_0, segments);
cmsgspace = CMSG_SPACE(extlen);
cmsgptr = malloc(cmsgspace);
extptr = CMSG_DATA(cmsgptr);

rthdr = (struct ip6_rthdr *)extptr;
segments = inet6_rth_segments(extptr);
in6 = inet6_rth_getaddr(extptr, i);
currentlen = inet6_opt_init(NULL, 0);
currentlen = inet6_opt_append(NULL, 0, currentlen, OPT_X,
                                    12, 8, NULL);
currentlen = inet6_opt_append(NULL, 0, currentlen, OPT_Y,
                                    7, 4, NULL);
currentlen = inet6_opt_finish(NULL, 0, currentlen);
extlen = currentlen;

extbuf = malloc(extlen);
currentlen = inet6_opt_init(extbuf, extlen);
currentlen = inet6_opt_append(extbuf, extlen, currentlen,
          OPT_X, 12, 8, &databuf);
offset = 0;
value4 = 0x12345678;
offset = inet6_opt_set_val(databuf, offset,
                                 &value4, sizeof (value4));
value8 = 0x0102030405060708;
offset = inet6_opt_set_val(databuf, offset,
                                 &value8, sizeof (value8));

currentlen = inet6_opt_append(extbuf, extlen, currentlen,
          OPT_Y, 7, 4, &databuf);
offset = 0;
value1 = 0x01;
offset = inet6_opt_set_val(databuf, offset,
                                 &value1, sizeof (value1));
value2 = 0x1331;
offset = inet6_opt_set_val(databuf, offset,
                                 &value2, sizeof (value2));
value4 = 0x01020304;
offset = inet6_opt_set_val(databuf, offset,
                                 &value4, sizeof (value4));

currentlen = inet6_opt_finish(extbuf, extlen, currentlen);
ext = (struct ip6_dest *)extbuf;
currentlen = 0;
currentlen = inet6_opt_next(extbuf, extlen,
                                                  currentlen, &type,
                                                  &len, &databuf);
offset = 0;
offset =
                                  inet6_opt_get_val(databuf, offset,
                                                    &value4,
                                                    sizeof (value4));
offset =
                                  inet6_opt_get_val(databuf, offset,
                                                    &value8,
                                                    sizeof (value8));
offset = 0;
offset =
                                  inet6_opt_get_val(databuf, offset,
                                                    &value1,
                                                    sizeof (value1));
offset =
                                  inet6_opt_get_val(databuf, offset,
                                                    &value2,
                                                    sizeof (value2));
offset =
                                  inet6_opt_get_val(databuf, offset,
                                                    &value4,
                                                    sizeof (value4));
