bandwidth = 2 Mbps), the fraction of the RTCP packets from agent A1
T_dither_max = l * T_rr, with l = 0.5.  The rationale for this is
l=0.5, we think that a trade-off was found that is acceptable for
Plr    = {0.005, 0.01, 0.02, 0.03, 0.05, 0.1, 0.2}

l=0.5 given in this document seems to be reasonable for most
