xmlns="urn:ietf:params:xml:ns:resource-lists"
elementFormDefault="qualified" attributeFormDefault="unqualified">
schemaLocation="http://www.w3.org/2001/xml.xsd"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
minOccurs="0"/>
maxOccurs="unbounded"/>
xmlns="urn:ietf:params:xml:ns:rls-services"
elementFormDefault="qualified" attributeFormDefault="unqualified">
maxOccurs="unbounded"/>

maxOccurs="unbounded"/>
e=%22l1%22%5d</resource-list>
e=%22l1%22%5d</resource-list>
content="text/html;charset=iso-8859-1"/>
content="text/html;charset=iso-8859-1"/>
