auth-name=myhost1 AND auth-cred=CHAP/user1      (identity1)

auth-cred=CHAP/user2) would allow either auth-name to be used with
template-type=iscsi
template-version=1.0

template-description=
     This is an abstract service type.  The purpose of the iscsi
     service type is to encompass all of the services used to support
     the iSCSI protocol.

template-url-syntax=
url-path=  ;  Depends on the concrete service type.

template-type=iscsi:target
template-version=1.0

template-description=

     This is a concrete service type.  The iscsi:target service type is
     used to register individual target addresses to be discovered
     by others.  UAs will generally search for these by including one of
     the following:

     - the iSCSI target name
     - iSCSI initiator identifiers (iSCSI name, credential, IP address)
     - the service URL

template-url-syntax=
url-path    = hostport "/" iscsi-name [ "/" identity ]
hostport    = host [ ":" port ]
host        = hostname / hostnumber  ; DNS name or IP address
hostname    = *( domainlabel "." ) toplabel
alphanum    = ALPHA / DIGIT
domainlabel = alphanum / alphanum *[alphanum / "-"] alphanum
toplabel    = ALPHA / ALPHA *[ alphanum / "-" ] alphanum
hostnumber  = ipv4-number / ipv6-addr  ; IPv4 or IPv6 address
ipv4-number = 1*3DIGIT 3("." 1*3DIGIT)
ipv6-addr   = "[" ipv6-number "]"
ipv6-number =                              6( h16 ":" ) ls32
                   /                       "::" 5( h16 ":" ) ls32
                   / [               h16 ] "::" 4( h16 ":" ) ls32
                   / [ *1( h16 ":" ) h16 ] "::" 3( h16 ":" ) ls32
                   / [ *2( h16 ":" ) h16 ] "::" 2( h16 ":" ) ls32
                   / [ *3( h16 ":" ) h16 ] "::"    h16 ":"   ls32
                   / [ *4( h16 ":" ) h16 ] "::"              ls32
                   / [ *5( h16 ":" ) h16 ] "::"              h16
                   / [ *6( h16 ":" ) h16 ] "::"
ls32        = ( h16 ":" h16 ) / ipv4-number
                   ; least-significant 32 bits of ipv6 address
h16         = 1*4HEXDIG
port        = 1*DIGIT
iscsi-name  = iscsi-char ; iSCSI target name
identity    = iscsi-char ; optional identity string
iscsi-char  = ALPHA / DIGIT / escaped / ":" / "-" / "."
                   ; Intended to allow UTF-8 encoded strings
escaped     = 1*("\" HEXDIG HEXDIG)
iscsi-name = string
portal-group = integer
transports = string M L
mgmt-entity = string O
alias = string O
auth-name = string M X
auth-addr = string M X
auth-cred = string M X
boot-list = string M O
template-type=iscsi:sms
template-version=1.0

template-description=
     This is a concrete service type.  The iscsi:sms service type
     provides the capability for entities supporting iSCSI to discover
     appropriate management services.

template-url-syntax=
url-path   = ; The URL of the management service [RFC2608].

protocols = string M
transports = string M L
server-priority = integer
