contact-params  =/ temp-gruu / pub-gruu
temp-gruu       =  "temp-gruu" EQUAL quoted-string
pub-gruu        =  "pub-gruu" EQUAL quoted-string

uri-parameter   =/ gr-param
gr-param        = "gr" ["=" pvalue]   ; defined in RFC 3261

M = D || I_i
E = AES-ECB-Encrypt(K_e, M)
A = HMAC-SHA256-80(K_a, E)

Temp-Gruu-userpart = "tgruu." || base64(E) || base64(A)

Ac = HMAC-SHA256-80(K_a, E)

M = AES-ECB-Decrypt(K_e, E)

