scope="whole path").

RESERVE = COMMON-HEADER
                RSN [ RII ] [ REFRESH-PERIOD ] [ *BOUND-SESSION-ID ]
                [ SESSION-ID-LIST [ RSN-LIST ] ]
                [ MSG-ID / BOUND-MSG-ID ] [ INFO-SPEC ]
                [ [ PACKET-CLASSIFIER ] QSPEC ]

QUERY = COMMON-HEADER
              [ RII ] [ *BOUND-SESSION-ID ]
              [ PACKET-CLASSIFIER ] [ INFO-SPEC ] QSPEC [ QSPEC ]

RESPONSE = COMMON-HEADER
                 [ RII / RSN ] INFO-SPEC [SESSION-ID-LIST [ RSN-LIST ] ]
                 [ QSPEC ]

NOTIFY = COMMON-HEADER
               INFO-SPEC [ QSPEC ]

AB=00 ("Mandatory"): If the object is not understood, the entire
AB=01 ("Ignore"): If the object is not understood, it MUST be
AB=10 ("Forward"): If the object is not understood, it MUST be
AB=11 ("Refresh"): If the object is not understood, it should be
