L1==L2==L3--L4--L5
                  |
                  |
                 L6--L7
                       \
                        H5--H6

                Figure 7: Example of a Multi-Layer Network

