capability            =/ "FILTERS"

search-criteria       =  search-key *(SP search-key)

search-key            =/  "FILTER" SP filter-name
                         ;; New SEARCH criterion for referencing filters

filter-name           =  1*<any ATOM-CHAR except "/">
                         ;; Note that filter-name disallows UTF-8 or
                         ;; the following characters: "(", ")", "{",
                         ;; " ", "%", "*", "]".  See definition of
                         ;; ATOM-CHAR [RFC3501].

resp-text-code        =/  "UNDEFINED-FILTER" SP filter-name

