URN = "urn:" NID NSS

NID = "smpte:"

NSS = UL-NSS / other-NSS

UL-NSS = "ul:" UL

UL = QUADBYTE *(DOT QUADBYTE)

DOT = %x2E ; period

QUADBYTE = 4BYTE

BYTE = 2HEXDIG

other-NSS = 1*(DIGIT / ALPHA / "-"/":")

