TSI = Transport Service Instance

                   Figure 3: MPLS-TP PE Containing a UNI
        --------------From UNI------->            :
       -------------------------------------------:------------------
      |                     | Client Traffic Unit :                  |
      | Link-Layer-Specific | Link Decapsulation  : Service Instance |
      |    Processing       |         &           :    Transport     |
      |                     |  Service Instance   :  Encapsulation   |
      |                     |   Identification    :                  |
       -------------------------------------------:------------------
                                                  :
                                                  :
       -------------------------------------------:------------------
      |                     |                     : Service Instance |
      |                     |                     :    Transport     |
      | Link-Layer-Specific | Client Traffic Unit :  Decapsulation   |
      |    Processing       | Link Encapsulation  :        &         |
      |                     |                     : Service Instance |
      |                     |                     :  Identification  |
       -------------------------------------------:------------------
        <-------------To UNI ---------            :

       Figure 4: MPLS-TP UNI Client-Server Traffic Processing Stages

TP  = Transport Path
TSI = Transport Service Instance

                  Figure 5: MPLS-TP PE Containing an NNI
                                                   :
        --------------From NNI------->             :
       --------------------------------------------:------------------
      |                     | Service Traffic Unit :                  |
      | Link-Layer-Specific |  Link Decapsulation  : Service Instance |
      |    Processing       |          &           :  Encapsulation   |
      |                     |   Service Instance   :  Normalization   |
      |                     |    Identification    :                  |
       --------------------------------------------:------------------
                                                   :
                                                   :
       --------------------------------------------:------------------
      |                     |                      : Service Instance |
      |                     |                      :  Identification  |
      | Link-Layer-Specific | Service Traffic Unit :        &         |
      |    Processing       |  Link Encapsulation  : Service Instance |
      |                     |                      :  Encapsulation   |
      |                     |                      :  Normalization   |
       --------------------------------------------:------------------
        <-------------To NNI ---------             :

          Figure 6: MPLS-TP NNI Service Traffic Processing Stages

U ========= Y ========= D

