Session-Id = Type-Code || Method-Id

Session-Id = 0xFE || Vendor-Id || Vendor-Type || Method-Id

Session-Id = 0x17 || RAND || AUTN

Session-Id = 0x12 || RAND || NONCE_MT

Session-Id = 0x2F || RAND_P || RAND_S

Session-Id = 0x30 || RAND_S || RAND_P

