Chunked-Message = 1*chunk
                          end-of-chunks

chunk           = LF HASH chunk-size LF
                          chunk-data
chunk-size      = 1*DIGIT1 0*DIGIT
chunk-data      = 1*OCTET

end-of-chunks   = LF HASH HASH LF

DIGIT1          = %x31-39
DIGIT           = %x30-39
HASH            = %x23
LF              = %x0A
OCTET           = %x00-FF

xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
