MIPv6-HoA == MN-HoA -> MAG1
                               +------+
                               |HA/LMA|-----------------------+
                               +------+                       |
                                 //\\                         |
MIPv6-HoA == MN-HoA -> MAG_1
                     +-------+
                     |HA/LMA1|-----------------------+
                     +-------+                       |
                       //\\                       +----+
