xmlns="urn:ietf:params:xml:ns:nttdm-1.0">
targetNamespace="urn:ietf:params:xml:ns:nttdm-1.0"
elementFormDefault="qualified"
attributeFormDefault="unqualified">
type="nttdm:eTT_Short_Description"/>

type="nttdm:eTT_Impact_Assessment"/>

type="nttdm:eRelated_External_Tickets"/>
type="nttdm:eRelated_Activity"/>

type="nttdm:eNetwork_Link_Circuit"/>

maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
minOccurs="0" maxOccurs="unbounded"/>
maxOccurs="unbounded"/>
