S1 = 1 -- SYN sent

S2 = 1 -- My SYN verified

R = 1 -- SYN received

C=O) to (F=l, C=1), then the connection is closed and the TCB can
S = size of sequence number space

L = left window edge

R = L+W-1 = right window edge

x = sequence number to be tested

B = the total user receive buffers

W = the long-term or nominal window size

