sub-domain   =/  U-label
    ; extend the definition of sub-domain in RFC 5321, Section 4.1.2

atext   =/  UTF8-non-ascii
    ; extend the implicit definition of atext in
    ; RFC 5321, Section 4.1.2, which ultimately points to
    ; the actual definition in RFC 5322, Section 3.2.3

qtextSMTP  =/ UTF8-non-ascii
    ; extend the definition of qtextSMTP in RFC 5321, Section 4.1.2

esmtp-value  =/ UTF8-non-ascii
    ; extend the definition of esmtp-value in RFC 5321, Section 4.1.2

vrfy = "VRFY" SP String
     [ SP "SMTPUTF8" ] CRLF
    ; String may include Non-ASCII characters

expn = "EXPN" SP String
     [ SP "SMTPUTF8" ] CRLF
    ; String may include Non-ASCII characters

