master_secret = PRF(pre_master_secret, "master secret",
                          ClientHello.random +
                          ClientHello.additional_ms_input_1 +
                          ClientHello.additional_ms_input_2 +
                          . . .
                          ClientHello.additional_ms_input_N +
                          ServerHello.random +
                          ServerHello.additional_ms_input_1 +
                          ServerHello.additional_ms_input_2 +
                          . . .
                          ServerHello.additional_ms_input_N +
                          )[0..47];

