targetNamespace="urn:ietf:params:xml:ns:xcon-conference-info"
xmlns="urn:ietf:params:xml:ns:xcon-conference-info"
elementFormDefault="qualified">

schemaLocation="urn:ietf:params:xml:schema:patch-ops"/>
xmlns="urn:ietf:params:xml:ns:xcon-conference-info"
entity="conference123@example.com">
sel="*/users/allowed-users-list">  <target
uri="sip:john@example.com" method="refer"/>
content="text/html;charset=iso-8859-1"/>
