i = 1..Num of Locs   valid for the sending ILNPv4 node.

i = 1..Num of Locs   relative to other valid Locator[i]
                               values.  The Preference numbers here
                               are identical, both in syntax and
                               semantics, to the Preference values
                               for L32 records that are specified by
                               [RFC6742].

i = 1..Num of Locs   particular Locator may be considered
                               valid.  Normally, this is identical
                               to the DNS lifetime of the
                               corresponding L32 record, if one
                               exists.

