xml      = "XML" xmlparam ( ":" text ) /
                (
                  ";" "ENCODING" "=" "BASE64"
                  ";" "VALUE" "=" "BINARY"
                  ":" binary
                )
                CRLF

xmlparam     = *(";" other-param)

altrepparam = element altrep {
       value-uri
cnparam = element cn {
       value-text
cutypeparam = element cutype {
       element text {
           "INDIVIDUAL" |
           "GROUP" |
           "RESOURCE" |
           "ROOM" |
           "UNKNOWN"
       }
delfromparam = element delegated-from {
       value-cal-address+
deltoparam = element delegated-to {
       value-cal-address+
dirparam = element dir {
       value-uri
encodingparam = element encoding {
       element text {
           "8BIT" |
           "BASE64"
       }
fmttypeparam = element fmttype {
       value-text
fbtypeparam = element fbtype {
       element text {
           "FREE" |
           "BUSY" |
           "BUSY-UNAVAILABLE" |
           "BUSY-TENTATIVE"
       }
languageparam = element language {
       value-text
memberparam = element member {
       value-cal-address+
partstatparam = element partstat {
       type-partstat-event |
       type-partstat-todo |
       type-partstat-jour
type-partstat-event = (
       element text {
           "NEEDS-ACTION" |
           "ACCEPTED" |
           "DECLINED" |
           "TENTATIVE" |
           "DELEGATED"
       }
type-partstat-todo = (
       element text {
           "NEEDS-ACTION" |
           "ACCEPTED" |
           "DECLINED" |
           "TENTATIVE" |
           "DELEGATED" |
           "COMPLETED" |
           "IN-PROCESS"
       }
type-partstat-jour = (
       element text {
           "NEEDS-ACTION" |
           "ACCEPTED" |
           "DECLINED"
       }
rangeparam = element range {
       element text {
           "THISANDFUTURE"
       }
trigrelparam = element related {
       element text {
           "START" |
           "END"
       }
reltypeparam = element reltype {
       element text {
           "PARENT" |
           "CHILD" |
           "SIBLING"
       }
roleparam = element role {
       element text {
           "CHAIR" |
           "REQ-PARTICIPANT" |
           "OPT-PARTICIPANT" |
           "NON-PARTICIPANT"
       }
rsvpparam = element rsvp {
       value-boolean
sentbyparam = element sent-by {
       value-cal-address
tzidparam = element tzid {
       value-text
value-binary =  element binary {
       xsd:string
value-boolean = element boolean {
       xsd:boolean
value-cal-address = element cal-address {
       xsd:anyURI
pattern-date = xsd:string {
pattern = "\d\d\d\d-\d\d-\d\d"
value-date = element date {
       pattern-date
pattern-date-time = xsd:string {
pattern = "\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\dZ?"
value-date-time = element date-time {
       pattern-date-time
pattern-duration = xsd:string {
pattern = "(+|-)?P(\d+W)|(\d+D)?"
               ~ "(T(\d+H(\d+M)?(\d+S)?)|"
               ~   "(\d+M(\d+S)?)|"
               ~   "(\d+S))?"
value-duration = element duration {
       pattern-duration
value-float = element float {
       xsd:float
value-integer = element integer {
       xsd:integer
value-period = element period {
       element start {
           pattern-date-time
       },
       (
           element end {
               pattern-date-time
           } |
           element duration {
               pattern-duration
           }
       )
value-recur = element recur {
       type-freq,
       (type-until | type-count)?,
       element interval {
           xsd:positiveInteger
       }?,
       type-bysecond*,
       type-byminute*,
       type-byhour*,
       type-byday*,
       type-bymonthday*,
       type-byyearday*,
       type-byweekno*,
       type-bymonth*,
       type-bysetpos*,
       element wkst { type-weekday }?
type-freq = element freq {
       "SECONDLY" |
       "MINUTELY" |
       "HOURLY"   |
       "DAILY"    |
       "WEEKLY"   |
       "MONTHLY"  |
       "YEARLY"
type-until = element until {
       type-date |
       type-date-time
type-count = element count {
       xsd:positiveInteger
type-bysecond = element bysecond {
       xsd:positiveInteger
type-byminute = element byminute {
       xsd:positiveInteger
type-byhour = element byhour {
       xsd:positiveInteger
type-weekday = (
       "SU" |
       "MO" |
       "TU" |
       "WE" |
       "TH" |
       "FR" |
       "SA"
type-byday = element byday {
       xsd:integer?,
       type-weekday
type-bymonthday = element bymonthday {
       xsd:integer
type-byyearday = element byyearday {
       xsd:integer
type-byweekno = element byweekno {
       xsd:integer
type-bymonth = element bymonth {
       xsd:positiveInteger
type-bysetpos = element bysetpos {
       xsd:integer
value-text = element text {
       xsd:string
pattern-time = xsd:string {
pattern = "\d\d:\d\d:\d\dZ?"
value-time = element time {
       pattern-time
value-uri = element uri {
       xsd:anyURI
value-utc-offset = element utc-offset {
       xsd:string { pattern = "(+|-)\d\d:\d\d(:\d\d)?" }
value-unknown = element unknown {
       xsd:string
start = element icalendar {
       vcalendar+
vcalendar = element vcalendar {
       type-calprops,
       type-component
type-calprops = element properties {
       property-prodid &
       property-version &
       property-calscale? &
       property-method?
type-component = element components {
       (
           component-vevent |
           component-vtodo |
           component-vjournal |
           component-vfreebusy |
           component-vtimezone
       )*
component-vevent = element vevent {
       type-eventprop,
       element components {
           component-valarm+
       }?
type-eventprop = element properties {
       property-dtstamp &
       property-dtstart &
       property-uid &

       property-class? &
       property-created? &
       property-description? &
       property-geo? &
       property-last-mod? &
       property-location? &
       property-organizer? &
       property-priority? &
       property-seq? &
       property-status-event? &
       property-summary? &
       property-transp? &
       property-url? &
       property-recurid? &

       property-rrule? &

       (property-dtend | property-duration)? &

       property-attach* &
       property-attendee* &
       property-categories* &
       property-comment* &
       property-contact* &
       property-exdate* &
       property-rstatus* &
       property-related* &
       property-resources* &
       property-rdate*
component-vtodo = element vtodo {
       type-todoprop,
       element components {
           component-valarm+
       }?
type-todoprop = element properties {
       property-dtstamp &
       property-uid &

       property-class? &
       property-completed? &
       property-created? &
       property-description? &
       property-geo? &
       property-last-mod? &
       property-location? &
       property-organizer? &
       property-percent? &
       property-priority? &
       property-recurid? &
       property-seq? &
       property-status-todo? &
       property-summary? &
       property-url? &

       property-rrule? &

       (
           (property-dtstart?, property-dtend? ) |
           (property-dtstart, property-duration)?
       ) &

       property-attach* &
       property-attendee* &
       property-categories* &
       property-comment* &
       property-contact* &
       property-exdate* &
       property-rstatus* &
       property-related* &
       property-resources* &
       property-rdate*
component-vjournal = element vjournal {
       type-jourprop
type-jourprop = element properties {
       property-dtstamp &
       property-uid &

       property-class? &
       property-created? &
       property-dtstart? &
       property-last-mod? &
       property-organizer? &
       property-recurid? &
       property-seq? &
       property-status-jour? &
       property-summary? &
       property-url? &

       property-rrule? &

       property-attach* &
       property-attendee* &
       property-categories* &
       property-comment* &
       property-contact* &
       property-description? &
       property-exdate* &
       property-related* &
       property-rdate* &
       property-rstatus*
component-vfreebusy = element vfreebusy {
       type-fbprop
type-fbprop = element properties {
       property-dtstamp &
       property-uid &

       property-contact? &
       property-dtstart? &
       property-dtend? &
       property-duration? &
       property-organizer? &
       property-url? &

       property-attendee* &
       property-comment* &
       property-freebusy* &
       property-rstatus*
component-vtimezone = element vtimezone {
       element properties {
           property-tzid &

           property-last-mod? &
           property-tzuurl?
       },
       element components {
           (component-standard | component-daylight) &
           component-standard* &
           component-daylight*
       }
component-standard = element standard {
       type-tzprop
component-daylight = element daylight {
       type-tzprop
type-tzprop = element properties {
       property-dtstart &
       property-tzoffsetto &
       property-tzoffsetfrom &

       property-rrule? &

       property-comment* &
       property-rdate* &
       property-tzname*
component-valarm = element valarm {
       audioprop | dispprop | emailprop
type-audioprop = element properties {
       property-action &

       property-trigger &

       (property-duration, property-repeat)? &

       property-attach?
type-dispprop = element properties {
       property-action &
       property-description &
       property-trigger &
       property-summary &

       property-attendee+ &

       (property-duration, property-repeat)? &

       property-attach*
type-emailprop = element properties {
       property-action &
       property-description &
       property-trigger &

       (property-duration, property-repeat)?
property-calscale = element calscale {

       element parameters { empty }?,

       element text { "GREGORIAN" }
property-method = element method {

       element parameters { empty }?,

       value-text
property-prodid = element prodid {

       element parameters { empty }?,

       value-text
property-version = element version {

       element parameters { empty }?,

       element text { "2.0" }
property-attach = element attach {

       element parameters {
           fmttypeparam? &
           encodingparam?
       }?,

       value-uri | value-binary
property-categories = element categories {

       element parameters {
           languageparam? &
       }?,

       value-text+
property-class = element class {

       element parameters { empty }?,

       element text {
           "PUBLIC" |
           "PRIVATE" |
           "CONFIDENTIAL"
       }
property-comment = element comment {

       element parameters {
           altrepparam? &
           languageparam?
       }?,
       value-text
property-description = element description {

       element parameters {
           altrepparam? &
           languageparam?
       }?,

       value-text
property-geo = element geo {

       element parameters { empty }?,

       element latitude  { xsd:float },
       element longitude { xsd:float }
property-location = element location {

       element parameters {

           altrepparam? &
           languageparam?
       }?,

       value-text
property-percent = element percent-complete {

       element parameters { empty }?,

       value-integer
property-priority = element priority {

       element parameters { empty }?,

       value-integer
property-resources = element resources {

       element parameters {
           altrepparam? &
           languageparam?
       }?,

       value-text+
property-status-event = element status {

       element parameters { empty }?,

       element text {
           "TENTATIVE" |
           "CONFIRMED" |
           "CANCELLED"
       }
property-status-todo = element status {

       element parameters { empty }?,

       element text {
           "NEEDS-ACTION" |
           "COMPLETED" |
           "IN-PROCESS" |
           "CANCELLED"
       }
property-status-jour = element status {

       element parameters { empty }?,

       element text {
           "DRAFT" |
           "FINAL" |
           "CANCELLED"
       }
property-summary = element summary {

       element parameters {
           altrepparam? &
           languageparam?
       }?,

       value-text
property-completed = element completed {

       element parameters { empty }?,

       value-date-time
property-dtend = element dtend {

       element parameters {
           tzidparam?
       }?,

       value-date-time |
       value-date
property-due = element due {

       element parameters {
           tzidparam?
       }?,

       value-date-time |
       value-date
property-dtstart = element dtstart {

       element parameters {
           tzidparam?
       }?,

       value-date-time |
       value-date
property-duration = element duration {

       element parameters { empty }?,

       value-duration
property-freebusy = element freebusy {

       element parameters {
           fbtypeparam?
       }?,


       value-period+
property-transp = element transp {
       element parameters { empty }?,

       element text {
           "OPAQUE" |
           "TRANSPARENT"
       }
property-tzid = element tzid {

       element parameters { empty }?,

       value-text
property-tzname = element tzname {

       element parameters {
           languageparam?
       }?,

       value-text
property-tzoffsetfrom = element tzoffsetfrom {

       element parameters { empty }?,

       value-utc-offset
property-tzoffsetto = element tzoffsetto {

       element parameters { empty }?,

       value-utc-offset
property-tzurl = element tzurl {

       element parameters { empty }?,

       value-uri
property-attendee = element attendee {

       element parameters {
           cutypeparam? &
           memberparam? &
           roleparam? &
           partstatparam? &
           rsvpparam? &
           deltoparam? &
           delfromparam? &
           sentbyparam? &
           cnparam? &
           dirparam? &
           languageparam?
       }?,

       value-cal-address
property-contact = element contact {

       element parameters {
           altrepparam? &
           languageparam?
       }?,

       value-text
property-organizer = element organizer {
       element parameters {
           cnparam? &
           dirparam? &
           sentbyparam? &
           languageparam?
       }?,

       value-cal-address
property-recurid = element recurrence-id {

       element parameters {
           tzidparam? &
           rangeparam?
       }?,

       value-date-time |
       value-date
property-related = element related-to {

       element parameters {
           reltypeparam?
       }?,

       value-text
property-url = element url {

       element parameters { empty }?,

       value-uri
property-uid = element uid {

       element parameters { empty }?,
       value-text
property-exdate = element exdate {

       element parameters {
           tzidparam?
       }?,

       value-date-time+ |
       value-date+
property-rdate = element rdate {

       element parameters {
           tzidparam?
       }?,

       value-date-time+ |
       value-date+ |
       value-period+
property-rrule = element rrule {

       element parameters { empty }?,

       value-recur
property-action = element action {

       element parameters { empty }?,
       element text {
           "AUDIO" |
           "DISPLAY" |
           "EMAIL"
       }
property-repeat = element repeat {

       element parameters { empty }?,

       value-integer
property-trigger = element trigger {

       (
           element parameters {
               trigrelparam?
           }?,

           value-duration
       ) |
       (
           element parameters { empty }?,

           value-date-time
       )
property-created = element created {

       element parameters { empty }?,

       value-date-time
property-dtstamp = element dtstamp {
       element parameters { empty }?,

       value-date-time
property-last-mod = element last-modified {

       element parameters { empty }?,

       value-date-time
property-seq = element sequence {

       element parameters { empty }?,

       value-integer
property-rstatus = element request-status {

       element parameters {
           languageparam?
       }?,

       element code { xsd:string },
       element description { xsd:string },
       element data { xsd:string }?
