P_ewma = P_ewma_old * (1 - alpha) + P * alpha  (Eq. 4)

K = (I_aed / time unit).  This can then be used to calculate gamma as
gamma = K'th-root( A ).

FAV_new = FAV_old + ( 1 - FAV_old ) * P  (Eq. 7)

FAV_new = FAV_old + P  (Eq. 8)

P_first_threshold = P_encounter_first * gamma ^ ((P2 * P4 * P5)/P1)

gamma =
Decay_typ = gamma ^ ((P2 * P3)/P1)

