I = I - (2^N - 1)
I = I / 128
M = 0
B = next octet
I = I + (B & 127) * 2^M
M = M + 7
I = 1337 - (2^5 - 1) = 1306.

         I (1306) is greater than or equal to 128, so the while loop
         body executes:

            I % 128 == 26

            26 + 128 == 154

            154 is encoded in 8 bits as: 10011010

            I is set to 10 (1306 / 128 == 10)
            I is no longer greater than or equal to 128, so the while
            loop terminates.

         I, now 10, is encoded in 8 bits as: 00001010.

max-age=3600; version=1
max-age=3600; version=1
