Session-Id = teap_type || tls-unique

tls-unique = tls-unique from the Phase 1 outer tunnel at the
IMSK = First 32 octets of TLS-PRF(EMSK, "TEAPbindkey@ietf.org" |
CMK = CMK[j]
Compound-MAC = MAC( CMK, BUFFER )

MSK  = TLS-PRF(S-IMCK[j], "Session Key Generating Function", 64)
EMSK = TLS-PRF(S-IMCK[j],
           "Extended Session Key Generating Function", 64)

S-IMCK = session_key_seed.

EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1 ->
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1 ->
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1 ->

                              <- EAP-Request/
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1 ->
                              <- EAP-Request/
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=Y]

EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1 ->
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1
EAP-Type=TEAP, V=1 ->
TLV=Channel-Binding TLV)->

                                <- Channel-Binding TLV (Response),
                                Result TLV (Success),

