x = 4 bits.  Actual buffer size value is (2^(x + 4)) * 1K.
x = 4 bits.  Actual buffer size value is (2^(x + 4)) * 1K.
Type = x'FE'

      This type number has the two high-order bits turned on to enable
      processing to quickly distinguish it from an LLC message.

Length = 44

      The length of inline data that does not require the posting of a
      receive buffer.

