key_stream = ""
block_counter = 1
first_key_block = AES_ENC( data=IV||block_counter,
key=Encryption_key )
block_counter = block_counter + 1
key_block = AES_ENC( data=IV||block_counter,
key=Encryption_key )
key_stream = key_stream||key_block
key_stream = truncate( key_stream, Plaintext_len )
P = Plaintext (to be encrypted and authenticated)
A = Associated Data (to be authenticated only)

C = Ciphertext (encrypted and authenticated)
A = Associated Data (authenticated only)
R = neither encrypted nor authenticated, added
                    after Authenticated Encryption completed

P = Plaintext (to be encrypted and authenticated)
A = Associated Data (to be authenticated only)
R = neither encrypted nor authenticated, added after
                    encryption

A = Associated Data (to be authenticated only)
R = neither encrypted nor authenticated, added after
                    encryption

srtp-crypto-suite-ext = "AEAD_AES_128_GCM"    /
                              "AEAD_AES_256_GCM"    /
                              srtp-crypto-suite-ext
SRTP_AEAD_AES_128_GCM    = {0x00, 0x07}
SRTP_AEAD_AES_256_GCM    = {0x00, 0x08}

