server_certificate_type=(RawPublicKey) // (1)
                         ->
                         <- server_hello,
server_certificate_type=RawPublicKey, // (2)
client_certificate_type=(RawPublicKey) // (1)
server_certificate_type=(RawPublicKey) // (1)
                         ->
                         <-  server_hello,
server_certificate_type=RawPublicKey // (2)
client_certificate_type=RawPublicKey // (5)
server_certificate_type=(RawPublicKey, X.509, OpenPGP)
client_certificate_type=(RawPublicKey) // (1)
                         ->
                         <-  server_hello,
server_certificate_type=X.509 // (2)
client_certificate_type=RawPublicKey // (4)
