mplsOamIdMegIndex                 = 1,
mplsOamIdMegName                  = "MEG1",
mplsOamIdMegOperatorType          = ipCompatible (1),
mplsOamIdMegServicePointerType    = lsp (1),
mplsOamIdMegMpLocation            = perNode (1),
mplsOamIdMegRowStatus             = createAndGo (4),
mplsOamIdMeIndex                  = 1,

mplsOamIdMeMpIndex                = 1,
mplsOamIdMeName                   = "ME1",
mplsOamIdMeMpIfIndex              = 0,
mplsOamIdMeSourceMepIndex         = 0,
mplsOamIdMeSinkMepIndex           = 0,
mplsOamIdMeMpType                 = mep (1),
mplsOamIdMeMepDirection           = down (2),
mplsOamIdMeServicePointer         = mplsTunnelName.1.1.10.20,
mplsOamIdMeRowStatus              = createAndGo (4)
