contentType = signedData { pkcs-7 2 },
eContentType = data { pkcs-7 1 },
contentType = envelopedData { pkcs-7 3 },
contentType = data { pkcs-7 1 },
POSTREQUEST = "POST" SP SCEPPATH "?operation=" OPERATION
                 SP HTTP-version CRLF

GETREQUEST = "GET" SP SCEPPATH "?operation=" OPERATION
                "&message=" MESSAGE SP HTTP-version CRLF

message=MIAGCSqGSIb3DQEHA6CAMIACAQAxgDCBzAIBADB2MG \
