Error-type=20 (LSP State Synchronization Error) and error-value 1
Error-type=19 (Invalid Operation) and error-value 1 (Attempted LSP
Error-type=6 (Mandatory Object missing) and Error-value 8 (LSP object
Error-type=6 (Mandatory Object missing) and Error-value=10 (SRP
Error-type=6 (Mandatory Object missing) and Error-value=9 (ERO object
