sess-id-param       =/ logme-param

logme-param         = "logme"

            Figure 12: Augmented BNF for the "logme" Parameter
a=crypto:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX

