value=7 (Unsupported endpoint type in END-POINTS Generalized Endpoint
value=2 (Unrecognized object type) or with Error-Type=4 (Not
Error-Type=17 (P2MP END-POINTS Error) and Error-value=4 (The PCE
Error-value=29 (Wrong LABEL-SET TLV present with O and L bits set).

Error-Type=10 (Reception of an invalid object) and Error-value=28
NCC=0, NVC=2, MT=1.  The PCE can respond with a maximum of 5 paths,
