YY = the last two decimal digits of the current year
MM = the two decimal digits of the current month
DD = the two decimal digits of the current day
HHMMSSLLL = the decimal digits of the current time,
            expressed in hours (HH), minutes (MM), seconds (SS), and
            milliseconds (LLL)

