auth=false;                               
QTYPE=A, and QCLASS=IN, and had the following resource records:

            ISIF.ARPA     CNAME   IN     F.ISI.ARPA         
            F.ISI.ARPA    A       IN     10.2.0.52          

TYPE=* in RRs is prohibited.  If it were to be allowed, the
CLASS=* is also prohibited.  Similar effects can be achieved using
QCLASS=*, and allowing both QCLASS=* and CLASS=* leads to
QCLASS=IN, QNAME=F.ISI.ARPA, it would begin processing (using the
QNAME=A.ISI.ARPA, QTYPE=A, and QCLASS=IN.  The authority search
                                  Domain Names - Concepts and Facilities


QNAME=UCI.CSNET, QTYPE=MAILA, and QCLASS=IN.  The name server
QTYPE=MAILA, and QCLASS=CS, the name server would return:

            UCI.CSNET     MD      CS     UCI.CSNET          
            UCI.CSNET     A       CS     714-555-0000       

QCLASS=IN and a RR for ISI.ARPA.  This request asks for completion
