r_1 = p, r_2 = q, and additional factors if any

i = 3, ... , u

x = x_(xLen-1) 256^(xLen-1) + x_(xLen-2) 256^(xLen-2) + ...
X = X_1 X_2 ... X_xLen.

DB = lHash || PS || 0x01 || M.

EM = 0x00 || maskedSeed || maskedDB.

m = OS2IP (EM).

c = RSAEP ((n, e), m).

C = I2OSP (c, k).
DB = |  lHash   |  PS  |01|   M   |
                                +----------+------+--+-------+
                                               |
EM =  |00|maskedSeed|          maskedDB          |
                  +--+----------+----------------------------+
c = OS2IP (C).
m = RSADP (K, c).

EM = I2OSP (m, k).

EM = Y || maskedSeed || maskedDB.

DB = lHash' || PS || 0x01 || M.

EM = 0x00 || 0x02 || PS || 0x00 || M.

m = OS2IP (EM).

c = RSAEP ((n, e), m).

C = I2OSP (c, k).

c = OS2IP (C).

m = RSADP ((n, d), c).

EM = I2OSP (m, k).

EM = 0x00 || 0x02 || PS || 0x00 || M.

EM = EMSA-PSS-ENCODE (M, modBits - 1).

m = OS2IP (EM).

s = RSASP1 (K, m).

S = I2OSP (s, k).

s = OS2IP (S).

m = RSAVP1 ((n, e), s).

EM = I2OSP (m, emLen).

Result = EMSA-PSS-VERIFY (M, EM, modBits - 1).

EM = EMSA-PKCS1-V1_5-ENCODE (M, k).

m = OS2IP (EM).

s = RSASP1 (K, m).

S = I2OSP (s, k).

s = OS2IP (S).

m = RSAVP1 ((n, e), s).

EM = I2OSP (m, k).

DB =  |Padding2|   salt   |   Hash
                  +--------+----------+     |
                            |               |
                            V               |
                           xor <--- MGF <---|
                            |               |
                            |               |
                            V               V
                  +-------------------+----------+--+
EM =  |    maskedDB       |     H    |bc|
                  +-------------------+----------+--+
H = Hash(M).

EM = 0x00 || 0x01 || PS || 0x00 || T.

C = I2OSP (counter, 4) .

T = T || Hash(mgfSeed || C) .

