AFI = x:  x can be any AFI value from [AFN].

AFI = x:  x can be any AFI value from [AFN].

AFI = x:  x can be any AFI value from [AFN].

AFI = x:  x can be any AFI value from [AFN].

AFI = x:  x can be any AFI value from [AFN].  When a specific address
      family has a multicast address semantic, this field must be either
      a group address or a broadcast address.

AFI = x:  x can be any AFI value from [AFN].  When a specific AFI has
      its own encoding of a multicast address, this field must be either
      a group address or a broadcast address.

AFI = x:  x can be any AFI value from [AFN].  This is the locator
      address that owns the encoded security key.

AFI = x:  x can be any AFI value from [AFN].

AFI = y:  y can be any AFI value from [AFN].  When a specific address
      family has a multicast address semantic, this field must be either
      a group address or a broadcast address.

AFI = x:  x can be any AFI value from [AFN].  A specific AFI has its
      own encoding of either a unicast or multicast locator address.
      For efficiency reasons, all RTR/ETR entries for the same level
      should be combined by a Map-Server to avoid searching through the
      entire multilevel list of locator entries in a Map-Reply message.

AFI = x:  x can be any AFI value from [AFN].

AFI = x:  x can be any AFI value from [AFN].

AFI = x:  x can be any AFI value from [AFN].  A specific AFI has its
      own encoding of either a unicast or multicast locator address.
      All RTR/ETR entries for the same level should be combined by a
      Map-Server to avoid searching through the entire multilevel list
      of locator entries in a Map-Reply message.

AFI = x:  x is the "Address as Key" AFI that can have any value from
      [AFN].  A specific AFI has its own encoding of either a unicast or
      a multicast locator address.  All RTR/ETR entries for the same
      level should be combined by a Map-Server to avoid searching
      through the entire multilevel list of locator entries in a Map-
      Reply message.

AFI = y:  y is the "Address of Value" AFI that can have any value
      from [AFN].  A specific AFI has its own encoding of either a
      unicast or a multicast locator address.  All RTR/ETR entries for
      the same level should be combined by a Map-Server to avoid
      searching through the entire multilevel list of locator entries in
      a Map-Reply message.

