e=0 :  Normal block.  Contains a (presumably valid)
                         check field CHECK.

e=1 :  Block contains no check field CHECK.

e=2 :  Abort channel, initiated by transmitter.
                         Channels is not closed, transmission restarts
                         on job-related boundary.

t=1:  Output to remote operator console.
                    2:  Input from remote operator console.
                    3:  Input from card reader.
                    4:  Output to printer.
                    5:  Output to card punch.
d=0     : Space k lines after printing; 0 < k < 3
                                                               =   =
                               is allowed

d=2     : Immediately space k lines.

d=1, k=1: Skip to top of new page after printing.

d=3, k=1: Immediately skip to top of new page.

