I=1, K=1

                 Figure 10: The Most Compressed RPI-6LoRH

I=1, K=0

                   Figure 11: Eliding the RPLInstanceID

I=0, K=1

                     Figure 12: Compressing SenderRank
I=0, K=0

