part-content    = emoji *(WSP emoji) CRLF

emoji           = emoji-sequence
emoji-sequence  = { defined in [Emoji-Seq] }

base-emojis     = thumbs-up / thumbs-down / grinning-face /
                     frowning-face / crying-face
                     ; Basic set of emojis, drawn from [Emoji-Seq]

