Error-Type = 26 (Association Error) and Error-value = 1 (Association
Type = 26 (Association Error) and Error-value = 14 (Association group
Error-value = 15 (Tunnel mismatch in the association group).

value = 16 (Path Setup Type not supported).

Error-value = 17 (Bidirectional LSP direction mismatch).

Error-value = 18 (Bidirectional LSP co-routed mismatch).

Error-value = 19 (Endpoint mismatch in the association group).

